### ISSUE TITLE
Please add MEGA support for 'External Storage' plugin [feature request]

### ISSUE THREAD

**Issue by arno01** [nextcloud/server#10118]
It would be nice to see [MEGA](https://mega.nz) support as they offer 50GB of free storage.

**Comment by MariusBluem** [comment]
MEGA seems to have a WebDAV-Plugin. You may want to try this together with WebDAV mounted as external storage to Nextcloud: https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/WEBDAV.md

**Comment by arno01** [comment]
@MariusBluem 

I wish it would...

According to the https://help.mega.nz/webclient/general.html#can-i-upload-data-using-ftp-sftp-webdav-or-similar

> We cannot provide Drive Mapping, SFTP, FTP, AFP, SMB or webDAV service capability. None of these protocols can be supported due to MEGA’s client-side encryption.

**Comment by TheHeurist** [comment]
1. After logging in to MEGA via MEGA-CMD inside a console (DOS, bash, sh,…), simply go to the folder you wish to share with nextcloud.
2. Type in “webdav .” You will receive a link (displayed in the console).
3. Copy that link or open it in a browser and there are the files you wish to share.
4. Now go to External Storage in Settings(!), not your personal External Storage, and create a WebDAV onnector. and place that link into the first field (URL) and a “/” in the one just below it (Remote subfolder). Turn off “Secure https://”, because the connection you received from MEGA-CMD is http://
5. Make sure YOUR Nextcloud credentials are in the “Username” and “Password” boxes.
6. Click on the “…” dots and assign the users or groups who should have access to the share.
7. Click on the Checkmark and you’re done!

Have fun with folders in Nextcloud which originate in MEGA. Syncing happens automatically as long as you always create the command shell to run after restarting your computer. Nextcloud needs this shelled “MEGA-CMD” running in the background in order to communicate with MEGA.
