### ISSUE TITLE
Integrity check not checking for owner (file system) of apps

### ISSUE THREAD

**Issue by LukeOwlclaw** [nextcloud/server#10154]
### Steps to reproduce
1. Install NC
2. Manually install app, with other user account that "web user"

E.g. my content of apps/ folder looks like this:
```
...
drwxr-xr-x  6 www-data www-data    4096 Jul  5 21:52 provisioning_api/
drwxr-xr-x 10 root     root        4096 Sep 17  2017 rainloop/
drwxr-xr-x 10 www-data www-data    4096 Jul  5 21:52 serverinfo/
...
```

### Expected behaviour
The integrity check should tell me, that `rainloop` is owned by a different owner.

### Actual behaviour
Integrity check shows that everything is OK.

Having a wrong owner results in a weird behavior of the updater: It shows that there is an update. On pressing the update button, the update seems to be performed but when refreshing the page in the browser, again an available update is shown.

**Comment by MorrisJobke** [comment]
> The integrity check should tell me, that rainloop is owned by a different owner.

I would not put this in the integrity check, but rather in the setup check, because it should not change that often and also is only needed for the app updates.

**Comment by weeman1337** [comment]
I would like to take this one.

@MorrisJobke what do you think? Should we test the app root directories only or perform a recursive check for all app files?

**Comment by MorrisJobke** [comment]
> @MorrisJobke what do you think? Should we test the app root directories only or perform a recursive check for all app files?

For now only the root directory, but we should look into the recursive way as well. Problem with that is also that it could be totally fine to have it like this until the app gets updated, because then the files are touched and need to be writable.

IMO also a setup check should be enough. See https://github.com/nextcloud/server/blob/master/settings/Controller/CheckSetupController.php#L535


cc @nickvergessen @rullzer
