### ISSUE TITLE
css, wrong css entrys

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#10181]
so, because i give not my realname and i can not create a patch
must you it does.. i tell you only a bug from entry/s

Version:  13.0.4

files-app > go to the free space under the file listing,
right mouse in Firefox, "Inspect Element(Q)"

*::-moz-focus-inner at 89a5-2a61-server.css / line1
*::-moz-range-thumb at files-music-player.css / line 201

a "*" it's never properly, i guess you should remove the lines ..

by the way, i have make a new version of my nextcloud-theme:
http://www.blackysgate.de/files/folder-root/nextcloud
http://www.blackysgate.de/files/folder-root/nextcloud/neXtrealTime%202018-07-10%2018-48-21.zip
have fun ! :)

by disable the themeing should also disable the officially NC Theme by 
custom theme and use only this what it is not set.. like icons and colors as placeholder..
so should by disable themeing, first load the custom theme, then load the not seted up icons and other colors .. if it is possible ..
the splashing of the of the officially Nextcloudtheme before the custom theme it is use 
disturbs and it boring because it splash every the blue colors and white background
before the custom theme load by every loading of an other page in the nextcloud.. 

if this fixed want i make other themes for nextcloud like wood or marmor, brushed metall and so on..

best regards
Blacky

![love nextcloud](http://www.blackysgate.de/files/folder-root/smilys/cookiemagik/_love__by_cookiemagik-d35xgjx.gif)

**Comment by blackcrack** [comment]
a idea/suggestion, if the page preload the css before it let view in the browser ..
it is give no flashing .. and the page it is format before it load and let show ..

**Comment by MorrisJobke** [comment]
> so, because i give not my realname and i can not create a patch
> must you it does.. i tell you only a bug from entry/s

You can also put your pseudonym into the git author. ;)



> *::-moz-focus-inner at 89a5-2a61-server.css / line1

https://github.com/nextcloud/server/blob/5e4e5531cfb98f35a8b3a52b4b355a4114049d35/core/css/fixes.scss#L4-L6

@nextcloud/designers Any comments on this? I would leave it in there, because it fixes a default style of Firefox.

> by disable the themeing should also disable the officially NC Theme by
> custom theme and use only this what it is not set.. like icons and colors as placeholder..
> so should by disable themeing, first load the custom theme, then load the not seted up icons and other colors .. if it is possible ..

There is no official NC theme. It's just the normal look and feel. The theming app basically does this job, by changing the color, logo and texts.

> the splashing of the of the officially Nextcloudtheme before the custom theme it is use
> disturbs and it boring because it splash every the blue colors and white background
> before the custom theme load by every loading of an other page in the nextcloud..

Then use the theming app, because it does properly replace the colors and doesn't use just additional files. The themes is anyway planned to be removed and only the theming app will be left in the long term. The reason for this is, that often those themes cause a lot of trouble and broken behavior while not adding much value. We also add a significant amount of work into our UI. And if you then still want to tweak the UI it is still possible by overwriting the files itself, but is not supported (in the same way current themes are not supported if they break stuff).

**Comment by juliushaertl** [comment]
We dont use `*::-moz-focus-inner` anywhere in the server repo, so I guess those are added somewhere in your theme or for the files-music-player.css file in the music player app.

Usages of -moz-focus-inner in the server repo:

```
core/css/inputs.scss
178:	&::-moz-focus-inner {

core/css/fixes.scss
4:	::-moz-focus-inner {
```

In general while using `*` might have a small performance impact, I doubt that it is recognizable for the one browserspecific rule.

**Comment by blackcrack** [comment]
@MorrisJobke 
Hi Morris :)

>There is no official NC theme. It's just the normal look and feel. The theming app basically does this job, by changing the color, logo and texts.

then test my theme and you know what i mean, a preload of the css-files would maybe not bad..
I want make my own theme and not easy change the color and the picture of login,
this is not a themeing this is a fastfood and foodstuff for narrow-gauge indians who not have a
correct idea of ​​modding with css ;) \*s\*

test my theme and add it in the config.php as theme => 'neXtrealTime'

and think this as marmor or morkienwood theme with a bit other buttons like in a Car
Marmor, like a Table or a Kitchen a little bit more noble,
this black/white with Dos-ttf it's only a start ..

best regards
Blacky
