### ISSUE TITLE
files dates ( enhancement )

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#10258]
hello, 

having two day ago, 7 days ago, 10 days ago  for the upload date stamp is, lets say, not usefull for clarity.

A nice clear timestamp might be better:

toto.jpg 7 days ago
vs
toto.jpg   13/07/2018 21:16

sorry, but my motto is clarity, simplicity is always better than anything else

**Comment by jancborchardt** [comment]
Simplicity and clarity are core design principles of Nextcloud: https://nextcloud.com/design :)

And a relative date like 7 days ago is much better than a timestamp, since it directly tells you how long ago it was. Faced with a timestamp, people need to calculate when it was changed, and if it was a month ago or just yesterday.

That’s why we show relative dates by default, and the exact timestamp on hover.
