### ISSUE TITLE
Sidebar standardization

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10289]
@skjnldsv @rullzer @jancborchardt and me had today some discussions about how to move the current sidebar forward and improve the layout to be consistent across apps and reusable.

Ref #8374 

## Apps that use the sidebar

* apps management
* bookmarks
* calendar
* deck
* files
* talk
* tasks
* (not yet) public share page - basically for comments

## Problems

* not reusable by apps and other views (like public share page)
* apps can only register separate tabs
   * activity, versions, comments are all separate tabs
* no standard in design yet

Overview of all existing sidebars (files, app mangement, talk, calendar, deck, bookmarks, tasks)

![out](https://user-images.githubusercontent.com/245432/42906857-84cbdd58-8adc-11e8-96d6-191352d559b0.png)

## Proposal

* having a standardized way to build a sidebar
   * common elements to use
   * hints on how elements should look like
   * given structure

### Specification

[<img src="https://user-images.githubusercontent.com/245432/42906850-7efe622e-8adc-11e8-88c0-c78d40059960.JPG" height="500">](https://user-images.githubusercontent.com/245432/42906850-7efe622e-8adc-11e8-88c0-c78d40059960.JPG)

* image (optional): preview, group image, events image based on title (like a generic one for haircutter, dentist,...)
* close button: x icon-close in top right
* title
* subtitle (optional): modified date, size, tags, authors, license
* icon left of title/subtitle: favorite, app icon, calendar switcher, task status/checkbox
* 3-dot menu (optional, right of title/subtitle): additional actions like rename, copy file link, delete
* call to action button (optional): start/join call, enable app
* tabs (optional): activity/chronology, sharing/participants, details
   * activity: comments, versions, chat, attachments, ratings
   * sharing: shares, participants, links, permissions, groups
   * details: description text, metadata like EXIF, map, reminders, repetition

Additionally we thought about showing the tabs as sections with a limited height that can be expanded. iOS and Android app store do this for descriptions, updates, ratings, etc. Benefit of this is having all recent/important information at a glance and the chance to dive deeper.

Example of how files and talk could work with this spec and minimal modifications:

![img_3169-2](https://user-images.githubusercontent.com/245432/42906831-73ba3bc2-8adc-11e8-8953-bc31f35fccbe.JPG)

iOS appstore:

[<img height="400" src="https://user-images.githubusercontent.com/245432/42906820-6c5b7db4-8adc-11e8-8a53-45240bae4218.PNG">](https://user-images.githubusercontent.com/245432/42906820-6c5b7db4-8adc-11e8-8a53-45240bae4218.PNG)

@nextcloud/designers @karlitschek and app developers @georgehrke @stefan-niedermann @marcelklehr @juliushaertl @tcitworld @nickvergessen @Ivansss What do you think?

**Comment by juliushaertl** [comment]
> Additionally we thought about showing the tabs as sections with a limited height that can be expanded. iOS and Android app store do this for descriptions, updates, ratings, etc. Benefit of this is having all recent/important information at a glance and the chance to dive deeper.

That rather depends on the content. It makes sense for the app store for example, where we could show the start of the description and changelog, but it feels wrong for showing a excerpt of a timeline, settings or basically anything that is not a descriptive text.

> tabs (optional): activity/chronology, sharing/participants, details
> activity: comments, versions, chat, attachments, ratings
> sharing: shares, participants, links, permissions, groups
> details: description text, metadata like EXIF, map, reminders, repetition

That separation makes a lot of sense. :+1: For merging all the chronological stuff into one.

**Comment by jancborchardt** [comment]
@juliushaertl yes, that’s why we only "thought about it". But we will for sure do it with tabs first.

For the timeline/chronological merge also ref **Sidebar: combine file Activity, Comments and Versions into unified »Activity« timeline tab** #658 where there’s a mockup about how that section specifically could look.

**Comment by sehucke** [comment]
Sounds great! I think there are many use cases where tabs fit well with additional expandable subelements together (like shortening long lists of elements). Feels like it should not be a "xor decision".

**Comment by danxuliu** [comment]
[As requested by @skjnldsv](https://github.com/nextcloud/spreed/issues/1390#issuecomment-446951567) here are the differences between tabs in Talk and in the server (Files app):
- Padding (larger in Talk, [12px](https://github.com/nextcloud/spreed/blob/020202c8c57a8ffe2f9fb9f66bb64e54e4a65dec/css/style.scss#L547) instead of [5px](https://github.com/nextcloud/server/blob/ac7c7782ff0681e6f192e4f0b9858af753cb7234/core/css/apps.scss#L792))
- Underline of inactive tab (shown in Talk, and explicitly mentioned as a fix in the pull request for Talk, while not shown in server)
- Opacity of active tab (stronger in Talk, [1.0](https://github.com/nextcloud/spreed/blob/f07e90d9c84887add1644caf80948535ff641afa/css/style.scss#L612) instead of [0.7](https://github.com/nextcloud/server/blob/ac7c7782ff0681e6f192e4f0b9858af753cb7234/core/css/apps.scss#L814))
- Opacity of inactive tab (in Talk is lower than the active tab, in server is the same)
- Highlight of hovered tab (in Talk the whole tab header is highlighted, in the server only the underline is highlighted)

**Talk** (faked to have the same tabs as the Files app):
![tab-header-talk](https://user-images.githubusercontent.com/26858233/50085446-59b50c80-01fa-11e9-8e9d-bfca0156e8c0.gif)

**Files app:**
![tab-header-files](https://user-images.githubusercontent.com/26858233/50085444-57eb4900-01fa-11e9-8e18-2ba13676505c.gif)

Some static screenshots too, as the colour palette of the GIFs makes difficult to see some details in the opacity:
**Talk:**
![tab-header-talk](https://user-images.githubusercontent.com/26858233/50086533-b1a14280-01fd-11e9-9c0d-6b98dece98a1.png)

**Files:**
![tab-header-files](https://user-images.githubusercontent.com/26858233/50086540-b4039c80-01fd-11e9-903e-0b3bab937372.png)

**Comment by skjnldsv** [comment]
@jancborchardt any opinion?
![1_ub9nyamooksgwhxx5ysqsa](https://user-images.githubusercontent.com/14975046/50109264-8e938480-0237-11e9-9995-31fb0776319d.gif)

**Comment by MorrisJobke** [comment]
@skjnldsv Any news here?

**Comment by skjnldsv** [comment]
@MorrisJobke this one will be delayed

**Comment by hitam4450** [comment]
Make the sidebar visible / hide by mandatory toggle switch !
reference: https://github.com/nextcloud/calendar/issues/1077

regards, hitam4450

**Comment by skjnldsv** [comment]
| 1 | 2 | 3 |
|:------:|:-----:|:-----:|
|![dev skjnldsv com_apps_vueexample_](https://user-images.githubusercontent.com/14975046/55719337-4377ca00-59fe-11e9-9457-6a4e0dbb82a7.png)|![dev skjnldsv com_apps_vueexample_ (2)](https://user-images.githubusercontent.com/14975046/55719241-13302b80-59fe-11e9-99ba-3009e5014b21.png)|![dev skjnldsv com_apps_vueexample_ (3)](https://user-images.githubusercontent.com/14975046/55719242-13302b80-59fe-11e9-9977-34ddfa32b1af.png)|
