### ISSUE TITLE
Check download server if it ist working before starting the upgrade

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#10357]
Update from NC 13.04 to 13.05 fails because download server download.nextcloud.com does not work properly and upgrade process can't continue.

Now Nextcloud instance stays in maintanance mode forever...

More details and screenshots:
https://help.nextcloud.com/t/nextcloud-13-0-5-and-12-0-10-secure-and-stabilize-your-server/34305/8

**Comment by MorrisJobke** [comment]
In the updater that is shipped with 13.0.5 this will not happen anymore, because the maintenance mode is enabled after the backup of code, download and successful extraction happened. So in the worst case some stray files are in the updater folder, that will be cleaned up later in a background job.

See https://github.com/nextcloud/updater/pull/169 for more details
