### ISSUE TITLE
Feature request: Provide UI for OCC command

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#10529]
The OCC command is essential for Nextcloud maintenance, but is only useable for admins with shell access to the webserver.

In many cases, shared hosters don't provide shell access to their customers, and in that case a user interface for the OCC command would be useful. For example, if a user can't login into Nextcloud anymore: https://help.nextcloud.com/t/kain-web-zugang-nach-update/34699.

**Comment by sunjam** [comment]
Hi, the [NextcloudPi](https://ownyourbits.com/nextcloudpi/) project adds exactly this functionality.  Installations are currently based on Debian Stretch.  Includes an admin tool called ncp-config, which is run from the terminal, or ncp-web can be accessed from port 4443.  [You are welcome to try it out and submit pull requests, etc!](https://github.com/nextcloud/nextcloudpi)  I would love to see these kinds of tools make their way into a deeper integration with core Nextcloud!
![ncp-dashboard](https://user-images.githubusercontent.com/1787238/43655561-eb1ad446-9703-11e8-8241-1d4d87b126ed.png)

**Comment by tflidd** [comment]
@sunjam can you give more instructions on how to use this on a shared hosting environment?

Something to keep in mind is that the occ command is often used because it is not subject to runtime timeouts. However, on shared environment and especially if you use it via browser, you will have timeouts and then some procedures could be killed ...

**Comment by skjnldsv** [comment]
App exists now https://apps.nextcloud.com/apps/occweb

**Comment by Sanookmakmak** [comment]
But version 0.0.4 not for Nextcloud 16
