### ISSUE TITLE
Ideas for NC 14

### ISSUE THREAD

**Issue by plyaskin** [nextcloud/server#10603]
Hi all!

Sorry but I don't know where I need to write the ideas so I will write it here :)
1. Support to change the "datadirectory" to the folder of WebDAV storage (mount with davfs2 or other methods). When mounting, the speed for Desktop sync and surfing via Browser is very slow and a lot of errors. This needed because the storage of VDS (SSD) is very expensive.
2. Default support of uploading the large files (and other often needed functions) without manipulations with config files etc.
3. Solve the regular problems (with locking files when uploading, Putty URL, etc.).

**Comment by MorrisJobke** [comment]
> Default support of uploading the large files (and other often needed functions) without manipulations with config files etc.

We do this now. Uploads in the browser are now also chunked and thus updates to the post size and max upload size don't seem to be needed anymore.



> Solve the regular problems (with locking files when uploading, Putty URL, etc.).

We are working on this and improved recently a lot in this space. Pretty URLs can be accomplished with those config options: https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#pretty-urls (yes they are needed because we can't detect them automatically)



> Support to change the "datadirectory" to the folder of WebDAV storage (mount with davfs2 or other methods). When mounting, the speed for Desktop sync and surfing via Browser is very slow and a lot of errors. This needed because the storage of VDS (SSD) is very expensive.

We improved on this in the past a lot. If there are still issues on your side we would like to know more stuff in detail. At least a proper profiling with a profiling tool would help a lot on this to know why it is slow. Blackfire or xdebug provide those profiling capabilities.

I will close this general ticket here. If there is a special issue you have feel free to open a new ticket with as much detail as possible. Also fill out the issue template that is shown when opening a new ticket.

Thanks for the feedback.

**Comment by plyaskin** [comment]
Hi @MorrisJobke and thank you very much for your attention.
`We are working on this and improved recently a lot in this space. Pretty URLs can be accomplished with those config options: https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#pretty-urls (yes they are needed because we can't detect them automatically)`
I tried it instruction twice but don't work and I don't know why, no any errors, just URL with "index.php". Could you recheck the instruction?

`We improved on this in the past a lot. If there are still issues on your side we would like to know more stuff in detail. At least a proper profiling with a profiling tool would help a lot on this to know why it is slow. Blackfire or xdebug provide those profiling capabilities.`
Some information here [#10612](https://github.com/nextcloud/server/issues/10612), but I will create the new ticket with all the information which I have.

**Comment by MorrisJobke** [comment]
> I tried it instruction twice but don't work and I don't know why, no any errors, just URL with "index.php". Could you recheck the instruction?

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by plyaskin** [comment]
@MorrisJobke 
> If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

I don't found the price for part of the subscription, only for full support, could you give me the link or the price? Will you set up WebDAV as home data directory with my max. speed (6-12 mb/sec) without freezes and with other settings?

**Comment by MorrisJobke** [comment]
> I don't found the price for part of the subscription, only for full support, could you give me the link or the price? Will you set up WebDAV as home data directory with my max. speed (6-12 mb/sec) without freezes and with other settings? Will you give the guarantee?

There is a calculator: https://nextcloud.com/enterprise/order/



> Will you set up WebDAV as home data directory with my max. speed (6-12 mb/sec) without freezes and with other settings? Will you give the guarantee?

Usually you can hardly give guarantees, because there are so many factors involved, but there is some quite good experience of bottlenecks available and we also help to debug together with customers right on their infrastructure to have a short feedback loop and get the needed details.

**Comment by plyaskin** [comment]
> There is a calculator: https://nextcloud.com/enterprise/order/

@MorrisJobke, I found the price, but EUR 990 for the install is very expensive in my case (2-5 users) (WebDav I needed for economy as I wrote), I'm ready to pay max EUR 50 with your guarantees that my speed via WebDAV as home data directory will maximum of possible (6-12 mb/sec). As you have the experience with it, you will spend no more 15-60 minutes for this (in my experience with set up), I think this very nice cost for this time. All the rest I will set up myself.

**Comment by MorrisJobke** [comment]
> @MorrisJobke, I found the price, but EUR 990 for the tries to set up is very expensive in my case (2-5 users) (WebDav I needed for economy as I wrote), I'm ready to pay max EUR 50 with the short instruction for me for the future and your guarantees that the speed upload and download via WebDAV as home data directory will maximum of possible (6-12 mb/sec) without any freezes (sync and web). As you have the experience with it, you will spend no more 15-60 minutes for this task (in my experience with set up), I think this very nice cost for this time spend. All the rest I will set up myself.

Then maybe one of the many consultants out there might be helpful. https://www.techandme.se had something like that in the past. cc @enoch85 

Or check out the forums. There are also people willing to help, but this issue tracker here is about bugs and not about setup issues.
