### ISSUE TITLE
email settings should be under groupware

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#10629]
We currently have email server settings in 'basic settings' and a Groupware category that has only calendar in it. Why not move the mail there, it is at least where I would have expected it... ? @nextcloud/designers

**Comment by rullzer** [comment]
That makes no sense to me. It is not about your e-mail settings it is about mail for sending from the server. I would expect global settings (if there are any) of the mail app to be there. But the default mail server from which your instance sends e-mail has nothing to do with that.

If anything it would be more confusing because people might think the setting there is somehow related to the mail app.

**Comment by jospoortvliet** [comment]
fair enough.

**Comment by jancborchardt** [comment]
Yup, absolutely agree with @rullzer. If there's ever global settings for the Mail appnwe of course can put them in Groupware. :) cc @ChristophWurst
