### ISSUE TITLE
Can I please get clarity from a developer on if this configuration is a valid use of NextCloud?

### ISSUE THREAD

**Issue by thedonquixotic** [nextcloud/server#10625]
I know this is probably more of a support question but I have asked in the forums and on reddit, and I've been getting many conflicting answers and I want to make sure I have a clear understanding if my configuration is a good idea or not, so I thought it would be best to check with the devs to get a solid answer. 

This is my plan:

![image](https://user-images.githubusercontent.com/9451726/43910964-d4189e12-9bc3-11e8-9926-575804d527bb.png)

I have two machines. A laptop and a desktop. The desktop is running the server. It also has my work folder (/home/david/work) mounted to NextCloud using the external folders application. This external folder is then being synced to my /users/david/work folder on my Windows 10 laptop. I intend to directly manipulate the files in this work folder (rename, delete, move, edit in a text editor, edit in a image editor etc) both on the desktop and on the laptop. 

Is this okay? I've gotten answers saying No, and others saying Yes, and some saying it's fine in particular use cases. 

My understanding:

[x] It is not recommended use of NextCloud to directly manipulate files in the mounted external folders even if those folders are external and not directly in the NC datapath. 

[x] BUT, I can manipulate those files, and as long as a cron job runs on the server to scan those folders, I should be okay. 

[x] By default, NC runs a cron job to check folders for changes, every 15 minutes. 

[x] After the changes have been made, and before the cron job has run, there will be some possibility for stuff messing up in that those changes won't have been indexed by NC, and therefore won't show up in the NextCloud Web GUI, 

[x] AND therefore those changes won't be synced over to the laptop until after those changes have been made. 

[x] If I make a change on the desktop and then go over and make a change on the laptop, before the cron job runs, NextCloud will not have a way of telling which change came first and it will create a conflict file. 

Is that all correct?

**Comment by tflidd** [comment]
> It is not recommended use of NextCloud to directly manipulate files in the mounted external folders even if those folders are external and not directly in the NC datapath.

You must not change files manually in the main data folder of NC. On external storage, this is accepted and when mounting a storage you can define if the folder is scanned on each access. This "access" refers to the web interface, since NC can't see on your client, if you open a folder. If you only access by the client, you probably need to induce some changes (create a new file, rename something, ...) to trigger this or run a cronjob.



> [x] If I make a change on the desktop and then go over and make a change on the laptop, before the cron job runs, NextCloud will not have a way of telling which change came first and it will create a conflict file.

Yes, very likely.

If you often run both sytems at the same time and risk to create conflicts, it would be probably easier to either pass everything through nextcloud (sync client, or webdav access). Or if it is in your local home, use a samba share and do everything on local with these smb-share, then also use this as external storage in Nextcloud when you want to share it with someone or use it externally (mobile device, ...).

**Comment by thedonquixotic** [comment]
@tflidd 

Thank you for the response. I have managed to get my sync process working after using bindfs to deal with permissions issues. While I still have some risk of creating conflicts through the simultaneous use of the two systems etc, I haven't yet encountered that issue, and I have a cron job running every 15 minutes so I think as long as I am careful it shouldn't be an issue. 

Thank you for the response!
