### ISSUE TITLE
missing SQL-Indexes since upgrade? Looking for a nice shirt :-)))))

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/server#10632]
Hi,

I've upgraded from 13.0.5 to 14beta3, now I've got security warnings ...
Fehlender Index "parent_index" in der Tabelle "oc_share".
Fehlender Index "fs_mtime" in der Tabelle "oc_filecache"
Can someone confirm the missing SQL-Indexes since upgrade?

Regards

**Comment by kangaroo72** [comment]
there's a hint to fix it with
ooc db:add-missing-indices (that's misspelled)
solved with
o**c**c db:add-missing-indices

**Comment by kangaroo72** [comment]
hmm .... happened first time 12 > 13 was no problem. Let's monitor further comments

**Comment by rullzer** [comment]
@kangaroo72 well we only started warning about this in 14 so it makes sense you only see them now :wink: .

The reason we don't add them automatically is that we don't know the size and setup people are running. Because if your installation is big enough adding them can take a long time.

So it seems the code is actually doing what it should :)

**Comment by kangaroo72** [comment]
okay - no shirt ... time to open an accessoire-shop ... roffffl
