### ISSUE TITLE
(Feature request) Manager <- Employer activity

### ISSUE THREAD

**Issue by Trafikson** [nextcloud/server#10872]
Hi,

I didnt see that any plugin is doing that and it should help with better control of data flow:

Possibility to select who is "manager" of someone manager can setup which aspects of activity he wanna be noticed, for example:
someone is setting public share, someone downloaded file from that share, user see mail with activity info, manager got that mail as well.
ofc perfect version would be that this could be imported from ldap manager attribute but setting it on nextcloud directly is nice too

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Also this should be implemented as an app instead of right into the server core. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
