### ISSUE TITLE
Add labels to the header app navigation icons

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#10952]
From [AppOrder Issue #47](https://github.com/juliushaertl/apporder/issues/47).  I'd love to be able to see Nextcloud apps by their text name (_Calendar_) instead of the icons.  This is especially true for new users, who find the icons very confusing.

**Steps to reproduce**

1. Browse over the application menu as shown in this screen capture
![](https://i.imgur.com/ub9Tqyd.png)
2. Note how (...) apps listed both text names and icons, but those along the top bar do not.

**Expected behaviour**

Applications would fill the entire top bar of my browser before the (...)
Possible to display just application Icons OR Text Names OR Both OR some combination of both.

**Actual behaviour**

Only 7 app icons are currently displayed before (...) despite having plenty of browser real estate.
I'm often confused when I see an icon and have no idea what it pertains to until I mouse over it to see the text name pop up.
No option to customize.
No option to display application names and hide associated icons.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by pixelipo** [comment]
Names for the app icons popover on hover - I think that's enough help for new users or those unfamiliar with a freshly installed app.

**Comment by jancborchardt** [comment]
And exactly this is also the reason we _do_ limit the number of apps shown in the top bar. The most used ~7 ones you can kind of remember and identify, but for more than that we have the menu with text.

**Comment by sunjam** [comment]
Interesting.  I myself do not find the 7 icons in the top bar easily
identifiable.  Example is Notes icon doesn't mean anything to me visually,
even after years.  When I do not access one of those apps for a few months
I forget what the icon means.

Also, I find new users will be frustrated that they cannot identify what
any of the icons mean across the top bar.  Optionally displaying the app
name as text would be really helpful.  For me, I'd rather see a text name
than an icon for even just 7 apps.

**Comment by pixelipo** [comment]
@sunjam I suggest proposing a better icon for those apps that you find hard to identify.

**Comment by sunjam** [comment]
Perhaps, but Nextcloud has over 150 apps available.  It makes the most
sense to allow the icons and/or names to displayed in the top bar.

**Comment by jancborchardt** [comment]
The problem is that it creates a lot of permanent noise in the top bar.

Another thing I thought about is to show the names of _all_ apps, but only when hovering/focusing the header.

So normally it shows this:
![screenshot from 2018-10-03 22-28-28](https://user-images.githubusercontent.com/925062/46437492-c96b3d80-c75b-11e8-98f6-44e328678168.png)

And on hover/focus it animates to this (moving the icons slightly up and showing the text below):
![screenshot from 2018-10-03 22-28-01](https://user-images.githubusercontent.com/925062/46437493-c96b3d80-c75b-11e8-94fe-c3040c5e5ca7.png)

What do you think @nextcloud/designers?

**Comment by sunjam** [comment]
I love having those names!  Easy to read.

**Comment by juliushaertl** [comment]
@jancborchardt It looks pretty decent to me. The only thing I'm a bit concerned about is how it will look with longer app names like translated ones. We probably should not ellipsize the text here, since it will make it very hard to recognize an app name.

**Comment by skjnldsv** [comment]
@jancborchardt pretty good!
SHould we add this into one of our accessibility option?
Make this the default?

**Comment by pixelipo** [comment]
This will not have an effect on accessibility, since 1) contrast is too low and 2) it's only on hover.

I'm not a fan of adding too much text where icons fill appropriate the role, but I have to admit @jancborchardt screenshot looks nice :blush:

**Comment by MorrisJobke** [comment]
> Do we limit how long an app title can be? Do we ellipsise long ones? What about translations?

We don't do anything yet :/

**Comment by jancborchardt** [comment]
We have to ellipsize, otherwise the clickable area will also change size. We could have the currently hovered/focused icon text take precedence though and overlap the ones to the left and right.

If we do it, it should be default. Does not really have anything to do with accessibility (more with usability) and I'd like to keep accessibility settings low, instead doing as much as possible in core directly.

I will look into it, and also think it's a good thing to fix since it's the last remaining part where we are guilty of using [Mystery Meat Navigation](https://en.m.wikipedia.org/wiki/Mystery_meat_navigation). :wink:

**Comment by skjnldsv** [comment]
@pixelipo ah, I did not realized this was on hover only!
I would be totally fine with this being like that by default :)

Let's scroll the text with marquee :grin:

**Comment by jancborchardt** [comment]
Pull request at https://github.com/nextcloud/server/pull/12153 – please review! :)

**Comment by ArchI3Chris** [comment]
Ok, so now we have labels. And now, is there an option to disable them? Personally I think, it's not that hard to get used to the icons after clicking them like 3 times. Even for new users. And if NextCloud needs one thing, it's getting lighter and not getting more bloated.

**Comment by jancborchardt** [comment]
See design reasoning and discussion on why we introduced this at: https://github.com/nextcloud/server/pull/12153

And reasoning on why we don’t have an option to disable them at https://github.com/nextcloud/server/issues/12778 (Short version: We need to test and maintain every setting which takes up a lot of resources.)


> Personally I think, it's not that hard to get used to the icons after clicking them like 3 times. Even for new users.

After seeing many confused users and issue reports, it was very clear that people don’t "get used to the icons". Icons without text always tend to be confusing, as people don’t use only that system all the time.

> So, how do I turn this thing off?

Take out the code that was introduced in https://github.com/nextcloud/server/pull/12153

**Comment by ArchI3Chris** [comment]
Let me say this: So, people are intelligent enough to set the whole thing up, but are too stupid to understand the icons? Maybe your icons are not ideal. Interesting though is, that people are not intelligent enough to understand the icons, but now have to become developers to disable the text or develop whole themes? Interesting idea. So, how does that make sense? If you want, I can list a number of problems that have far more severe consequences. For a while I had troule creating files, uploading files, downloading files,... upgrading 2 versions despite the one in the middle not being in the repos is not possible. THOSE are far more severe problems than this one. So, your "preferences" are WAY off anyway. So are people who don't get the icons after looking at them like three times. Here is another thing to consider: did you know that ads with images sell WAY higher than ads with just text? Do you know why that is? Because IMAGES are easier to understand than text. In fact, the mind thinks in IMAGES, not in text. Images are part of nature and the mind can actually process them. Unlike text, which, just as language, is made up by people. Images performing better than text is a FACT in marketing. Just not in UX. For some reason, in UX text is easier to understand than images. It's against all nature and marketing laws. You might have a point in terms of resources. You don't have a point in UX though. Because proven FACT is, just because 5 people of thousands complain, this doesn't make a better UX. And if you don't believe me, just read ANYTHING on marketing and ads and you will ALWAYS find the hint to use images to improve your sales! Nobody says, cut the images and write more text! That's ridiculous!

**Comment by eduardtoma** [comment]
Hello, could you point out a simple way to always show the icon labels/names, the same way they are shown when you hover over them.
Thank you in advance.

**Comment by szaimen** [comment]
> Hello, could you point out a simple way to always show the icon labels/names, the same way they are shown when you hover over them.
> Thank you in advance.

This won't work because most of the labels would overlap each other

**Comment by eduardtoma** [comment]
I just want it to always display like on the image bellow.
![image](https://user-images.githubusercontent.com/8247935/112362066-b60e0d00-8cdc-11eb-989f-1865579c6c9a.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@szaimen, if they wouls overlap, contain them in a vertical list. English isn't designed to be observed as adjacent sections of text, because it limits verbosity.
