### ISSUE TITLE
App config/settings REST/OCS API

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/server#10961]
**Story**
As an app developer I want to have an API for reading and storing app config/settings,
so I save time that I can spend on implementing amazing features in my app ;)

**Background**
Some apps use app config/setting values. Currently they're all implementing an own "store settings handler". It would be handy to have an API that can be used for this.

This is about making the app part of `IConfig` available as an API.

**Outline**
* Endpoint for reading all, one or more app config values
* Endpoint for storing one or more app config values
* Endpoint for deleting app config values
* Update of the NC app development documentation settings section

**Comment by weeman1337** [comment]
@MorrisJobke maybe the title is a bit misleading. It's about a _REST_ API.

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen @blizzz Isn't there already an OCS API endpoint for this?

**Comment by rullzer** [comment]
I have been thinking about this as well.

For me it would make sense to have a basic controller. That exposes the appconfig for a specific app

The dev can then set some types for the config values they have
like `setType('foo', 'int')` etc.

And then it can also write some functions like

`function fromFoo(int $var): string`
`funtion toFoo(string $var): int`
`function validateFoo(string $var): bool

etc. That way there is an easy framework to validate appconfig vars of an app. And the dev only has to worry about the part specific for their app and variables. The rest is all magically handled by the controller.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/47cc5e5895ded011a42cfc02957017aa61a42979/apps/provisioning_api/appinfo/routes.php#L64-L69

So try `/ocs/v2.php/apps/provisioning_api/api/v1/config/apps*`

Does exactly that with the IConfig::*AppValue methods:
https://github.com/nextcloud/server/blob/47cc5e5895ded011a42cfc02957017aa61a42979/apps/provisioning_api/lib/Controller/AppConfigController.php

The only thing it does not allow is setting the install/enable/type configs, because they should not be set manually.
