### ISSUE TITLE
upgrading from 13.0.6 to 14 failed on GuzzleClient\Client

### ISSUE THREAD

**Issue by cyrg38** [nextcloud/server#11166]
### Steps to reproduce
1. launch upgrade with web interface as usual (although many apps are automatically disabled)
2. stucked in upgrade step with error
3. when trying to continue via "occ upgrade" : complains with invalid code : inexistant method GuzzleClient\Client->request on lib/private/Http/Client/Client.php : 161

### Expected behaviour
upgrade normally

### Actual behaviour
restarted upgrade manually : actual stage is web GUI blue without images, unable to login.
apps disabled are among the best utils : rainloop, mail

Note that when trying to login the page redirect to rainloop as default app resulting in infinite loop of 302 HTTP responses from nginx server : I don't know how to restore default app as files on session startup !

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** (unable to access Nextcloud admin page) 14

**Updated from an older Nextcloud : 13.0.6**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
<pre>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_pdfviewer
  - files_videoplayer
  - firstrunwizard
  - gallery
  - rainloop
  - user_ldap
</pre>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<pre>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.2",
            "DOMAIN.fr",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/DOMAIN",
        "version": "14.0.0.19",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files",
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "installed": true,
        "loglevel": 0,
        "forcessl": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "auto",
        "asset-pipeline.enabled": true,
        "appstore.experimental.enabled": true,
        "log_type": "owncloud",
        "log_rotate_size": 10240000,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\Image",
            "1": "OC\\Preview\\MP3",
            "2": "OC\\Preview\\TXT",
            "3": "OC\\Preview\\MarkDown",
            "5": "OC\\Preview\\Epub"
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</pre>
</details>

**Are you using external storage, if yes which one:** local/GDrive

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by iniOr** [comment]
Hi, experiencing the exact same issue :

**Steps to reproduce**

    launch upgrade with web interface as usual (although many apps are automatically disabled)
    stucked in upgrade step with error
    when trying to continue via "occ upgrade" : complains with invalid code : inexistant method GuzzleClient\Client->request on lib/private/Http/Client/Client.php : 161

**Expected behaviour**

upgrade normally
**Actual behaviour**

Started upgrade from web gui, then continued with occ, got this error :

sudo -u www-data php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Checking for update of app activity in appstore
An unhandled exception has been thrown:
Error: Call to undefined method GuzzleHttp\Client::request() in <webserver path>/lib/private/Http/Client/Client.php:161
Stack trace:
#0 <webserver path>/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
#1 <webserver path>/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#2 <webserver path>/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
#3 <webserver path>/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
#4 <webserver path>/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('activity')
#5 <webserver path>/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Array)
#6 <webserver path>/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.0.19', '13.0.6.1')
#7 <webserver path>/core/Command/Upgrade.php(262): OC\Updater->upgrade()
#8 <webserver path>/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 <webserver path>/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 <webserver path>/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 <webserver path>/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 <webserver path>/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 <webserver path>/console.php(96): OC\Console\Application->run()
#14 <webserver path>/occ(11): require_once('/home/web/cloud...')
#15 {main}

Server configuration

Operating system: Debian 9

Web server: Apache

Database: MariaDB

PHP version: 7

Nextcloud version: (unable to access Nextcloud admin page) 14

Updated from an older Nextcloud : 13.0.6

Where did you install Nextcloud from: Webui then OCC

**Comment by timm2k** [comment]
Disable apps “boomarks” or “files_external_gdrive” if they are in use before upgrading nextcloud.
These apps ship an incompatible version of gruzzle.

**Comment by cyrg38** [comment]
The only app getting guzzle I have is "files_external_gdrive".

In fact, the fresh re-install produced an effect on upgrading database I think, so that switching again on old install I can get on to the promised 14 version : getting here back with GUI access.

This is SOLVED for me ! Thanks.
