### ISSUE TITLE
Verification email not sending NextCloud Forums

### ISSUE THREAD

**Issue by sixnoteprod** [nextcloud/server#11232]
This probably isn't the right place for this but I cannot create a login on the NextCloud Forums and as usual there is nowhere to report an issue other than the package github. 

Anyway I've tried with many different browsers, systems, emails etc... The verification email is not arriving. I have resent it many times and waited for hours. Nothing comes.

**Comment by patschi** [comment]
Can you check if there's anything in the spam folder of your mail provider? Otherwise I would recommend trying an other mail address for testing purposes.

I've also tried to request a password change on my account for testing purposes, haven't received any mail since over 15 minutes on my Google Mail address. Maybe the @nextcloud/infrastructure might check if something goes wrong server-side?

**Comment by sixnoteprod** [comment]
Yeh I've definitely been checking spam and also any categorised folders. I've tried three different email addresses, one of which doesn't use gmail-suite.
