### ISSUE TITLE
Drag'n'drop not working on public share page anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1125]
Not sure if this is intended, but I'd say we should (re?)enable drag'n'drop on the public share page.
Ref https://help.nextcloud.com/t/drag-and-drop-and-share-links/2710

cc @rullzer

**Comment by rullzer** [comment]
Yes I agree

**Comment by axllent** [comment]
I also agree. The fact that this doesn't work any more is actually a pain as we use Nextcloud to allow our clients to (easily) upload images & files to us. I'd hoped that there would have been a fix in 10.x however I see that it has been marked with the v11 milestone (although the bug is still open)... Thank you.

**Comment by MorrisJobke** [comment]
Works for public link shares and files drop links in 11
