### ISSUE TITLE
Can I delete ""Get your own free account""Share URL?

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/server#11327]
Hey, I don't like  "Get your own free account" text in share URL, it very ugly. It like "ads".
Can I close this?
If not, please make a function to close this text. (next version)
These few words make my feelings about nextcloud much lower.

I use 14.0.0.0
thanks.

**Comment by chiyi4488** [comment]
I seem to find the answer I want through the nextcloud bot, but I haven't tested it yet. If I test it successfully, I will close this issue.

**Comment by JSoko** [comment]
https://help.nextcloud.com/t/signature-advertising-for-nextcloud/36469/2

**Comment by msberends** [comment]
> These few words make my feelings about nextcloud much lower.

You're not the only one. Please read [this at the community pages of Nextcloud](https://help.nextcloud.com/t/how-long-have-nextcloud-file-shares-had-get-a-free-account/36053):

It’s tremendously rude and a ridiculous marketing trick. Really makes me sick and tired, I thought I left ownCloud for these kind of strange programming actions. Horrible. And an option in config.php is just discouragement policy. It should’ve been an option on the admin page. Or better yet, it should’ve been A QUESTION in the NC 14 update progress! It’s not even in the changelog.

It’s bizar. Besides, the advertisement itself is completely silly since Nextcloud is nowhere near an easy deploy possibility of their product - you still need to be a quite serious admin with server knowledge. So to think that most of your guests would be willing to do this, is silly to think in my opinion.

The option is not even on [the production pages of the admin manual](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html)!! 
So give me a break. **Nextcloud is Googlifying.** Ridiculous.

**Comment by chiyi4488** [comment]
You look angry (me too)
Need to reopen the issues?

**Comment by derekblankmccoy** [comment]
> > These few words make my feelings about nextcloud much lower.
> 
> You're not the only one. Please read [this at the community pages of Nextcloud](https://help.nextcloud.com/t/how-long-have-nextcloud-file-shares-had-get-a-free-account/36053):
> 
> It’s tremendously rude and a ridiculous marketing trick. Really makes me sick and tired, I thought I left ownCloud for these kind of strange programming actions. Horrible. And an option in config.php is just discouragement policy. It should’ve been an option on the admin page. Or better yet, it should’ve been A QUESTION in the NC 14 update progress! It’s not even in the changelog.
> 
> It’s bizar. Besides, the advertisement itself is completely silly since Nextcloud is nowhere near an easy deploy possibility of their product - you still need to be a quite serious admin with server knowledge. So to think that most of your guests would be willing to do this, is silly to think in my opinion.
> 
> The option is not even on [the production pages of the admin manual](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html)!!
> So give me a break. **Nextcloud is Googlifying.** Ridiculous.

Agree 100%

**Comment by omysurya** [comment]
Edit on: 
core/templates/layout.public.php

**Comment by yoretech** [comment]
> Edit on:
> core/templates/layout.public.php

But I do not believe this can be changed on the snap instance.

**Comment by kesselb** [comment]
You can use occ to remove the link:

https://github.com/nextcloud/server/issues/11101#issuecomment-453740147

(check the snap documentation how to use occ with snap)

**Comment by Sx3** [comment]
something strange I have set 
**'simpleSignUpLink.shown' => false**, in config.php but the message was there.
I needed to run
**occ config:system:set --type=bool --value=false simpleSignUpLink.shown**
using terminal to get it working .

**Comment by msberends** [comment]
Why was @Sx3 comment of three hours ago marked as spam?? That wasn’t spam! It was guidance. Don’t fume our frustration again please.

**Comment by kesselb** [comment]
It's spam. You can have exactly that guidance if you click on my previous post. Please don't push such old threads without a good reason. It's just notification spam for everyone subscribed.
