### ISSUE TITLE
Upload of folders in IE via web does not work anymore

### ISSUE THREAD

**Issue by Rowtag** [nextcloud/server#11366]
### Steps to reproduce
1. Upload a Folder with Chrome
2. Upload a Folder with Internet Explorer
3. Maybe test with other Browsers

### Expected behaviour
Uploading folders should work with all Browsers.

### Actual behaviour
When uploading with chrome it works, wenn Uploading with Internet Explorer or other Browsers there is a Message showing up which says that uploading files of that type isn't supported.

### Server configuration

#Docker Image:
14.0-rc

PHP 7.2
Apache Webserver
Maria DB

**Nextcloud version:** (see Nextcloud admin page)
NextCloud 14.0.1RC

**Updated from an older Nextcloud/ownCloud or fresh install:**
Dockerized, so fresh Image.

**Where did you install Nextcloud from:**
Docker Repository

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript Any idea?

**Comment by danxuliu** [comment]
>  It did work with Version 12 on IE

I have just tested with the latest _nextcloud:12_ Docker image, and with a Git repository in the _v12.0.0_ tag and latest _stable12_ branch. In all cases, when the file selector is opened through the _Upload file_ and a folder is selected the folder is opened to select the files in it, but the folder itself is not uploaded; when dragging and dropping a folder into the file list the file list is highlighted in blue and keeps highlighted forever (because #9807 was not backported to _stable12_), but nothing else happens.

Apparently [drag and drop of folders in IE 11 is not even supported by Microsoft itself in OneDrive](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/18785629-drag-and-drop-of-a-folder-and-or-multiple-files-us).

@rowtag Given all of the above I do not know why it worked for you with Nextcloud 12 (maybe you had some special patches applied?), but I am 99.99999% sure that it did not work out of the box :-)

If you find out how you made it work with Nextcloud 12 it would be great if you could send a pull request so we can add support for it in Nextcloud 14 :-)

**Comment by Rowtag** [comment]
Hmm the only thing, we had the V12 machine installed from : https://www.techandme.se/nextcloud-vm/
Maybe they had a solution to get it work. But i was not happy with the updates there which we moved to Docker.

I'll check if i can see how that did work.

**Comment by MorrisJobke** [comment]
> Hmm the only thing, we had the V12 machine installed from : https://www.techandme.se/nextcloud-vm/
> Maybe they had a solution to get it work. But i was not happy with the updates there which we moved to Docker.

Those VMs just ship the vanilla server code and don't have adjustments applied.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
