### ISSUE TITLE
Provide event hooks to authentication events

### ISSUE THREAD

**Issue by nexus186** [nextcloud/server#11431]
Please provide a way to run a custom script (bash etc) when a specific event occurs (such as run a bash script when an invalid login occurs). This would be much better than polling the next cloud log file (for an example, if you want to send an SMS through a web service based on some log event when don't have access to SMTP).

**Comment by MorrisJobke** [comment]
You could write an app, that does the triggering for you. We have a lot of events inside PHP: https://docs.nextcloud.com/server/14/developer_manual/app/hooks.html

You could then based on this trigger whatever code you want to run. We will not integrate this into the server as it is a super special use case and can be accomplished by an app. I hope this is okay for you, because otherwise we need to add a lot of specific code and config for a small feature that can already be accomplished in a fully supported way. See the admin_audit app for an example on how to listen to events and trigger stuff then: https://github.com/nextcloud/server/tree/master/apps/admin_audit
