### ISSUE TITLE
User search not efficient, returns partial matches

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#11540]
### Steps to reproduce
1. Go to the user section
2. Search for part of the full name or username

### Expected behaviour
I should find users with parts of there full name or there username

### Actual behaviour
I only find user when i start with the full name, if i just enter the lastname or the username I don't find anything

### Server configuration

**Operating system**:CentOS

**Web server:** NginX

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Comment by MorrisJobke** [comment]
Related to #7510

**Comment by skjnldsv** [comment]
We're using the ocs api search: https://github.com/nextcloud/server/blob/0b27595eb46aa6ad4dacf5506670dc0ced267537/apps/provisioning_api/lib/Controller/UsersController.php#L132
Which is apparently only filtering by id :)
https://github.com/nextcloud/server/blob/0b27595eb46aa6ad4dacf5506670dc0ced267537/lib/private/User/Manager.php#L218-L245

**Comment by paszczus** [comment]
Hello. Any update on this? We have 1400+ users and we are unable to search for any of them.

**Comment by devil1970** [comment]
Hi, I'have two servers, one is "Owncloud 10.3.2" the other is "Nextcloud 23.04". 

- Both the machines are connected via LDAP to an AD Windows Domain. 
- Connection string is the same. 
- Cache is the same. 
- Time to live is the same. 
- Also advanced options are the same. 

Now: Owncloud server is dying, in fact I'm not upgrading it since I've installed Nexcloud with nicer interface. The problem instead is in the "users searching!!" Particularly LDAP/AD USERS!!! 
Ever since (also wth previous version of OwnCloud/Nextcloud/Windows Domain) if I search AD connected users in Owncloud I find every users I'm looking for. I can write two letters in Owncloud and I will find every thing. Instead if I search under Nextcloud most times I can't find what I'm looking for. Very sad is that Nextcloud can tell me one time a user is not present and the second time I seek, the user is present. Also if I use wildcards. Also if I write whole user account name. If I try on both the platforms via SSH with OCC and I write: 'sudo -u www-data php ./occ user:list | grep "string I'm lookin for"', here I can find every thing.  
Other problem is "sorting". Under Nextcloud users are loaded gradually and in a strange way (likely they are sorted first by objectguid). The first loaded page is alphabetic sorted by A To Z. After that the system load another page with "other" users newly sorted by A to Z. The right way is receveing A To B on the first page, B To C on the second and so on. 
Now also if I search for a displayed user Nextcloud sometime find it and in other time it doesn't find anything. 

Someone of you has the same experience?

Greetings and many thanks for reading.
Davide

**Comment by devil1970** [comment]
> Hi, I'have two servers, one is "Owncloud 10.3.2" the other is "Nextcloud 23.04".
> 
> * Both the machines are connected via LDAP to an AD Windows Domain.
> * Connection string is the same.
> * Cache is the same.
> * Time to live is the same.
> * Also advanced options are the same.
> 
> Now: Owncloud server is dying, in fact I'm not upgrading it since I've installed Nexcloud with nicer interface. The problem instead is in the "users searching!!" Particularly LDAP/AD USERS!!! Ever since (also wth previous version of OwnCloud/Nextcloud/Windows Domain) if I search AD connected users in Owncloud I find every users I'm looking for. I can write two letters in Owncloud and I will find every thing. Instead if I search under Nextcloud most times I can't find what I'm looking for. Very sad is that Nextcloud can tell me one time a user is not present and the second time I seek, the user is present. Also if I use wildcards. Also if I write whole user account name. If I try on both the platforms via SSH with OCC and I write: 'sudo -u www-data php ./occ user:list | grep "string I'm lookin for"', here I can find every thing. Other problem is "sorting". Under Nextcloud users are loaded gradually and in a strange way (likely they are sorted first by objectguid). The first loaded page is alphabetic sorted by A To Z. After that the system load another page with "other" users newly sorted by A to Z. The right way is receveing A To B on the first page, B To C on the second and so on. Now also if I search for a displayed user Nextcloud sometime find it and in other time it doesn't find anything.
> 
> Someone of you has the same experience?
> 
> Greetings and many thanks for reading. Davide

FINALLY SOLVED!!!!

Hi folks, I've finally found the solution to this very bad problem.
The system is not able to sort recursively all the users it gradually finds BUT there is a solution about the search of the LDAP users (users connected via LDAP) and after all these years it doesn't real to me. 
Solution:

Under: 
_Settings -> LDAP/AD Integration -> (on the Right Top of the page) Advanced -> Directory Settings -> User Search Attributes_ 
Write the fields in which you want the search has to be done, in my case I wrote:
_samaccountname
mail
givenname
sn_
At the end of the page push on:
_Test Configuration_
  
Note:
_The solution is useful to administrator searching users in the system and to users sharing folders with other users in the organization_ 


Greetings.
Davide

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by XjeEDK** [comment]
Hi,
I don't use nextcloud anymore.
You can close this issue or wait for someone else to confirm that it's solved.

**Comment by smarinier** [comment]
Hi,

This is still a bug to my opinion. As searching users from Database or users from LDAP doesn't act the same (LDAP works only as "term*" and Database as "*term*"
