### ISSUE TITLE
Show login-history to user

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#116]
The last login of each user is already available on the admin-interface. So it would be nice to show your last login and the IP on your personal page. With more audit/logging, the number of failed login attempts could be shown as well.

This would enable each user to spot suspicious behavior on their account.

**Comment by MorrisJobke** [comment]
Most of this is available via https://github.com/owncloud/core/pull/24703#issuecomment-220284937

This will come to Nextcloud 10. Is it okay for you to close this ticket for now and reevaluate the status of this once we have a version that includes the above, because there was a lot of working going on in the last weeks regarding users sessions.

**Comment by tflidd** [comment]
Perfect. I should have a look at the daily-builds and check features out before I put a feature request 😓

**Comment by MorrisJobke** [comment]
> Perfect. I should have a look at the daily-builds and check features out before I put a feature request

No problem :) This is not yet part of nextcloud (at least not Nextcloud9 ;))
