### ISSUE TITLE
Enhancement: Limit preview sizes and scale from closest match

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#11722]
Currently, Nextcloud can generate several different previews of different sizes for the same file. This depends on for example, what client is used.

Eventually this will eat up a lot of storage space and server resources.

So my feature request is:
* limit preview sizes, perhaps 3 different sizes. 
* scale icons and displayed images from nearest sized preview.

I know it is possible to use previewgenerator and also to lower its jpeg quality to save space, but it isn't enough. Also, generating a small preview takes much more time than sending a slightly larger file and let the client's browser scale it down.

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by Gatak** [comment]
@rullzer You are of course correct. I will assume that there different use cases and in that regard a custom setting for this would be very useful.

Examples
* Home user on low end server (that's me). With limited CPU resources one night prefer fewer previews to speed up responsiveness.
* high end server users might want more previews to allow for better quality. 
* in a corporate setting there might be a defined size and resolution for all users. Enabling only matching previews might be preferred.

So an option to specify what sizes that should be generated would probably be very beneficial for many users.

Also, png's might be a better choice for really small sizes. This could be an additional option. 

Thank you.

**Comment by nero120** [comment]
Would love to see this implemented as well. Using default nextcloudpi config, I have 13GB of previews from a 28GB account! :scream:

**Comment by dgtlmoon** [comment]
Additionally, if the browser requests say a 130pixel thumbnail you'll get a 1024pixel image ...
see  https://github.com/nextcloud/server/issues/13709#issuecomment-554658438

**Comment by dgtlmoon** [comment]
@rullzer I'm going out on a limb here, I think people care a little less about the exact resolution of the thumbnail and care more about web page performance and disk usage, there's the bug in https://github.com/nextcloud/server/issues/13709#issuecomment-554658438 ... in other words, if someone gets a little lower resolution thumbnail, but everything is FAST and doesnt chew up much disk, no one will care

**Comment by szaimen** [comment]
Please use the recommended settings from this article which will limit the numbers of previews that get generated. 
https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/
Thanks!

**Comment by charleypaulus** [comment]
The link provided as an answer is broken.

**Comment by charleypaulus** [comment]
I ran the steps below to see which actions generated which previews. This test was done with a landscape-oriented photo.

- **Upload** (via RClone to avoid generating previews by using the GUI)
  - No preview generated
- **Access Files list view**
  - (a) Rectangle preview of width as per preview_max_* configuration
  - (b) Rectangle preview of width 1024 (and smaller height), probably used as icon thumbnail
- **Access Photos list view**
  - (c) Rectangle preview of width 256 (and smaller height), probably used as photo thumbnail
- **Open photo in full screen** (either in Files view or Photos view)
  - No new preview generated
- **Open side bar** (in Files view)
  - (d) Rectangle preview of height 1024 (and larger width)

@rullzer I understand we need several sizes, but my test above brings these questions:
- If the browser is able to use preview b (1024 width) for file thumbnail in Files view, why can't it use the same preview for photo thumbnail in Photos view, instead of generating preview c (256 width) (which is actually a smaller preview for a larger thumbnail!) ?
- If we have to have preview b of _width_ 1024, couldn't we use it for the side bar, instead of generating preview d of _height_ 1024 ? It seems close enough to address both needs.
