### ISSUE TITLE
Processing files ...

### ISSUE THREAD

**Issue by CHazz** [nextcloud/server#11724]
after uploading a large file (more than 2gb) .. this message remains .. for an infinite time .. (on all versions and on few installations... it must be a bug ) after refresh the page is all right and the file is uploaded without any problem

https://imgur.com/a/oRFmJ1F

thank you for great job !

**Comment by Ramalama2** [comment]
Exactly same here, but i have it since v14... (atm 14.0.3)
on v13 this didnt happend...

**Comment by Ramalama2** [comment]
Hi, me again, this bug is critical.

Small files are working without any problems, big files (500mb+) doesnt work, always infinite "processing files"

This happens on all 3 Nextcloud instances (all 3 are 14.0.3)

Cheers

**Comment by Ramalama2** [comment]
Here is a debug log, what happens if you uplad a file:

`{"reqId":"3ShfGCdWdR8eXSjzRXwA","level":0,"time":"2018-10-18T17:41:16+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"MKCOL","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"3ShfGCdWdR8eXSjzRXwA","level":0,"time":"2018-10-18T17:41:16+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"MKCOL","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"lZBD9BEoJb9VhKWfBffZ","level":0,"time":"2018-10-18T17:41:16+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"lZBD9BEoJb9VhKWfBffZ","level":0,"time":"2018-10-18T17:41:16+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"lZBD9BEoJb9VhKWfBffZ","level":0,"time":"2018-10-18T17:41:16+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/0)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"Ij4XIGeL5WZIE5RrRyP5","level":0,"time":"2018-10-18T17:41:17+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"Ij4XIGeL5WZIE5RrRyP5","level":0,"time":"2018-10-18T17:41:17+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"Ij4XIGeL5WZIE5RrRyP5","level":0,"time":"2018-10-18T17:41:17+02:00","remoteAddr":"88.34.33.34","user":"alka","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/alka\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760","message":"No cache entry found for \/alka\/uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760 (storage: home::alka, internalPath: uploads\/web-file-upload-97e882f53055a2408c8da79997c8d0d1-1539877276762\/10485760)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}`

**Comment by Ramalama2** [comment]
Guys, i found it out:

I can exactly upload files with maximal size of 9.99 MB
if i try to upload 10.01 MB i get the bug with processing files....

Cheers!

**Comment by Ramalama2** [comment]
I found the solution, at least for me:

location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
}

I have removed that block and its working now!......

What a crap...

**Comment by Nobunaga161RUS** [comment]
Greetings, is there a solution to this baggage? In my logic, when I upload a file, I write the following
{"reqId":"wtdbzPAnPhNOOm0CDQ7P","level":0,"time":"2019-02-01T18:39:35+03:00","remoteAddr":"172.16.11.161","user":"n.gamzin","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/n.gamzin\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120","message":"No cache entry found for \/n.gamzin\/uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120 (storage: home::n.gamzin, internalPath: uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"wtdbzPAnPhNOOm0CDQ7P","level":0,"time":"2019-02-01T18:39:35+03:00","remoteAddr":"172.16.11.161","user":"n.gamzin","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/n.gamzin\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120","message":"No cache entry found for \/n.gamzin\/uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120 (storage: home::n.gamzin, internalPath: uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"wtdbzPAnPhNOOm0CDQ7P","level":0,"time":"2019-02-01T18:39:35+03:00","remoteAddr":"172.16.11.161","user":"n.gamzin","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/n.gamzin\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120","message":"No cache entry found for \/n.gamzin\/uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120 (storage: home::n.gamzin, internalPath: uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5630853120)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"QVR95gWRDYaNh6dsqilG","level":0,"time":"2019-02-01T18:39:36+03:00","remoteAddr":"172.16.11.161","user":"n.gamzin","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/n.gamzin\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880","message":"No cache entry found for \/n.gamzin\/uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880 (storage: home::n.gamzin, internalPath: uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"QVR95gWRDYaNh6dsqilG","level":0,"time":"2019-02-01T18:39:36+03:00","remoteAddr":"172.16.11.161","user":"n.gamzin","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/n.gamzin\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880","message":"No cache entry found for \/n.gamzin\/uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880 (storage: home::n.gamzin, internalPath: uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"14.0.6.0"}
{"reqId":"QVR95gWRDYaNh6dsqilG","level":0,"time":"2019-02-01T18:39:36+03:00","remoteAddr":"172.16.11.161","user":"n.gamzin","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/uploads\/n.gamzin\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880","message":"No cache entry found for \/n.gamzin\/uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880 (storage: home::n.gamzin, internalPath: uploads\/web-file-upload-eb3d8ffa30f02708375177b00a6cc743-1549035192461\/5641338880)","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"14.0.6.0"}
and after the file is flooded it hangs on the processing file

**Comment by obendev** [comment]
Hey. Same issue here.

Nextcloud 15.0.4
PHP 7.3.2
MySQL 8.0.14
Chrome 72 on Windows 10

Filesize 6,51 GB, *.zip
Log after I try to "re-"access my cloud
`{"reqId":"9ZAPfKeMqphuesRJt12l","level":3,"time":"2019-02-08T19:05:45+00:00","remoteAddr":"myip","user":"admin","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/uploads\/admin\/web-file-upload-5bb0c34184ac3e9b673fb33fa13484d5-1549647751476\/.file","message":"fopen(\/var\/www\/cloud\/data\/admin\/files_encryption\/keys\/files\/test20190206v01.zip.ocTransferId1930963625.part\/OC_DEFAULT_MODULE\/master_4aec25d3.shareKey): failed to open stream: No such file or directory at \/var\/www\/cloud\/lib\/private\/Files\/Storage\/Local.php#284","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.96 Safari\/537.36","version":"15.0.4.0"}`

On `remoteAddr` I changed my IPv6 with `myip`

In the browser it just gives me a Gateway Timeout


I also think that this is critical @MorrisJobke 

If you need further information I can give them to you, I will keep this "buggy" instance running.

**Comment by Irillit** [comment]
Hello. Same in my Nextcloud;
**OS**: CentOS 7.5
**Nextcloud version**: 14.0.0.4
**HTTP Server**: Apache 2.4.6 
**PHP**: 7.0.31

As I got, "Processing files" should be in place until you realod or until the **uploads** folder of user gets cleared. I suspect the parts of file are merged this time.
I see when using web-interface, part size in uploads is 10485760, and quite different in Nextcloud client (it seems 10000000). I hadn't found this value in server code. 

I wonder if changing part size would increase performance of merging? And on what side was it defined?

**Comment by fabide** [comment]
Same Issue here as well

**OS:** Debian 9.9
**Nextcloud version:** 15.0.7
**HTTP Server:** Apache 2.4.25
**PHP**: 7.0.33

My solution to this problem was to change php.ini:
max_execution_time = 7200
max_input_time =7200

**Comment by Irillit** [comment]
I have to mention that I also tried to modify App.php
https://github.com/nextcloud/server/blob/master/apps/files/lib/App.php#L60
I changed from 10 Mb to 30 Mb, and it worked faster in my case. Not sure whether it's a good practice.

**Comment by fabide** [comment]
I dont' think changing php.ini is a good practice as well. I changed from solution to workaround in my above post because I think it works only if your upload isn't longer than 7200 seconds. That fits my needs but definetly not everyones.

**Comment by bkmgit** [comment]
Hi, having the same issue.

**Comment by karl-in-office** [comment]
This issue might be related to #8802
Please check whether your front-end server allows accesses to ".file" or not.

**Comment by SokoFromNZ** [comment]
Hi guys,

This error still exists for me (see https://help.nextcloud.com/t/problem-uploading-files-larger-than-8-10mb/48260/4).

The weird thing is that an upload via a FileDrop shared folder works perfectly!
Files < 10.0MB work as well.

@Ramalama2 : in which file did you delete
location ~ /.(?!well-known).* {
deny all;
access_log off;
log_not_found off;
}
???
Thanks
Soko

**Comment by SokoFromNZ** [comment]
I found my issue:

in my .htaccess file I had the line
    RedirectMatch 404 /(?!.well-known)(\.)\w+

which was added by the Statamic framework.
Once I deleted this line everything worked again.

Hope this helps someone.

Soko

**Comment by chrissi55** [comment]
Hi,

is there any comparative solution for nginx based NC Servers?
Thanks.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
