### ISSUE TITLE
Transfer Files to Another User When They Leave the Instance (or company)  (ex Owncloud 9 issue)

### ISSUE THREAD

**Issue by J-A-M** [nextcloud/server#119]
Is it good form to post planned enhancements to OwnCloud (v9)  as requested enhancement to NextCloud?

See https://github.com/owncloud/core/issues/19154

This one is a killer for us as we have a large turnover of interns.

**Comment by mar1u5** [comment]
Thank you for your interest into Nextcloud. Seems like the feature (transfer files to another user) is already implanted in ownCloud 9 (and so - it is also implanted into Nextcloud 9 😅):
 https://docs.nextcloud.org/server/9/admin_manual/configuration_files/file_sharing_configuration.html#transferring-files-to-another-user

I don't know if we should open every enhancement new here, I think there are 3 options:

- Let the community open all enhancements (also the old ones as duplicates from the core) here
- only those enhancements which have no concrete release plan in `owncloud/core` (those, with an assigned milestone in the near feature will be also implanted into Nextcloud because we downstream them - for long term - this isn't a solution)
- leave old enhancements in `owncloud/core` (...and ask people to only open new enhancements here; would require every user to search here and in the `owncloud/core` repository for issues - too complicated I think)

**Comment by MorrisJobke** [comment]
> I don't know if we should open every enhancement new here, I think there are 3 options:

If it is implemented we simply could close it as "fixed". Beside that we are open to get all enhancements listed also in this repo, but we try to give feedback on them faster and also close tickets faster if they completely doesn't fit in our vision (of course we then also describe why it doesn't will land in here and we are open for discussions).

This is clearly fixed in Nextcloud 9 (see the ./occ command)
