### ISSUE TITLE
Sidebar should show full file name

### ISSUE THREAD

**Issue by pellaeon** [nextcloud/server#12003]
There are enough spaces in sidebar, we should show the full file name, instead of requiring the user to hover over to see the full.

![2016-01-12 11 45 49](https://cloud.githubusercontent.com/assets/916913/12254335/33daee5e-b922-11e5-903c-0b73ebac5d60.png)
## Expected behavior

Sidebar shows the full file name, no tooltips.

## Reference

This issue has been raised in 2016 https://github.com/owncloud/core/issues/21636
Recently I [developed an app to overcome this](https://github.com/nextcloud/app-certificate-requests/pull/161), but rejected, @MorrisJobke asked me to open an issue here. 
Please read the discussions in the above two links as well.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers Please have a look at this - I think it is quite crucial to fix this. Also should be addressed in the context of the grid view (#11573).

**Comment by juliushaertl** [comment]
Looks totally fine to me if we just remove the ellipsis and allow the filename to have multiple lines. :+1: 

![image](https://user-images.githubusercontent.com/3404133/47426691-3471c800-d78e-11e8-9f7c-b14cfe1cf471.png)

**Comment by skjnldsv** [comment]
Yes, the filenames won't probably have more than 2 lines anyway :)

**Comment by jancborchardt** [comment]
> Yes, the filenames won't probably have more than 2 lines anyway :)

Hehehe ;D we can’t really expect this.

I’m fine with showing 2 lines for Files here. We shouldn’t allow that for others for now though, like say Talk conversation names. And we should limit it to 2 lines max, because otherwise a very long filename will just occupy everything, even though it’s not the most important thing in the sidebar.

Ok @juliushaertl @skjnldsv @MorrisJobke?

**Comment by skjnldsv** [comment]
> And we should limit it to 2 lines max

This is where css fails! css clamp is not supported enough, but we can set the height to 2x line height and use clamp to ellipsis o supported browsers or just hide overflow on unsupported ones)

**Comment by jancborchardt** [comment]
Ok – for the record, I’d rather have it stay limited to 1 line like now, than risk it being all messed up with many lines or non-consistent 2-lines. 

So maybe we need to wait a bit with this for compatibility?

**Comment by skjnldsv** [comment]
@jancborchardt it will be consistent *enough*, just the ... can be missing on some browsers :)
https://caniuse.com/#feat=css-line-clamp

Still 85% supported :)

**Comment by weeman1337** [comment]
I had some struggle with that in the last time.

My conclusion for line clamp is: Don't do it because of the lack of support. And don't use any polyfill or JavaScript since they all came up with limitations or bugs. I really spent many hours with that. Neither solution I tried worked.

What works for me is having some CSS fading out the text. It's based on an `after` element that overlays the end of the text:

![image](https://user-images.githubusercontent.com/6216686/49690189-e2fa7e00-fb2c-11e8-914d-7b972f1b503d.png)

Maybe that could be done in a mixin and can be replaced by real line clamp when it's supported by Firefox and IE doesn't have to be supported any more.

**Comment by weeman1337** [comment]
Anyway I could have a look at this one if we go for the "max. two instead of one line file name" solution.

**Comment by pellaeon** [comment]
I'd like to again raise attention to this issue. It has been two years and there is still no way of viewing the full filename in the sidebar. Even the tooltip no longer shows.

**Comment by skjnldsv** [comment]
We can most likely start using https://caniuse.com/css-line-clamp now that we dropped ie11

**Comment by szaimen** [comment]
I think this was fixed with https://github.com/nextcloud/server/pull/28046
