### ISSUE TITLE
WebDav issue with One Drive

### ISSUE THREAD

**Issue by fl0wde** [nextcloud/server#12042]
### Steps to reproduce
1. Create WebDav as external Storage (System or User doesn't matter)
2. Using OneDrive for Storage and WebDav: https://blogs.msdn.microsoft.com/robert_mcmurray/2014/09/30/using-the-webdav-redirector-with-onedrive-part-1-standard-security/
Name: WebDav_Strato
Type: WebDav
Auth: User & Password
URL: https://d.docs.live.net
Folder: /##############3E/
Secure HTTPS: yes
User: myuser@outlook.com
PW: mypassword

### Expected behaviour
Mount OneDrive via WebDav.
--> Testes mount in Windows & also 3rd-party-Tools: everyting is working with credentials above.

### Actual behaviour
Nothing, error accours via gui with red exclamation mark.
No log available (nextcloud.log is empty regarding this issue), please advise how I can support here with logs.

Other WebDav works as expected, only issues with OneDrive WebDav.

Thanks for your support.

Greets Fl0Wde

**Comment by hifihedgehog** [comment]
Same issue. It doesn't work for me. I would love to be able to connect with OneDrive at least through WebDav. This used to work according to some users in the forums but a bug has apparently been introduced within the couple of years. Since you are already adamantly against formal OneDrive support [even though it is a highly requested feature](https://github.com/nextcloud/server/issues/2097#issuecomment-349916370), we would at least expect WebDav to a functioning workaround

**Comment by kesselb** [comment]
> Since you are already adamantly against formal OneDrive support [even though it is a highly requested feature](https://github.com/nextcloud/server/issues/2097#issuecomment-349916370)

Please don't spread untruths. Someone has to build an app for OneDrive support.

**Comment by hevelius** [comment]
Hi everyone,
if you are interested I am working on an app to integrate onedrive in nextcloud.

https://github.com/hevelius/files_external_onedrive

**Comment by viruslab1** [comment]
webDAV wont work with one drive. It sad ((

**Comment by szaimen** [comment]
There is an app for this https://apps.nextcloud.com/apps/files_external_onedrive -> closing.
