### ISSUE TITLE
Improve expired share message

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#12062]
* having a share with an expiry date
* once this is reached an activity is created (and maybe send to the user via email)
* expected: it says "share has expired"
* actual: "{actor} removed you from {file}" which is confusing to users and does not reflect the automatic expiry of the share

cc @nickvergessen

**Comment by rullzer** [comment]
So this happens because we have internal expiration dates now. And they are basically removed the moment a user (either sharer or recipient) check the share in some way.

@nickvergessen Do you think it is enough to check the expiration date and conclude on the basis of that if it is an expiration or not?

**Comment by nickvergessen** [comment]
So user shares can expire now?

Well i guess we simply remove/ignore the user in this case

**Comment by rullzer** [comment]
Yeah was added in 14 by @schiessle

**Comment by MorrisJobke** [comment]
@nickvergessen Mind to look into this?

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/server/pull/16723 & https://github.com/nextcloud/activity/pull/383
