### ISSUE TITLE
Tags in files sidebar broken on master

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#12320]
Steps to reproduce:

1. Open files details sidebar
2. Click on the "Tags" icon 
3. No input appears

Seems this somehow slipped though due to the randomly failing acceptance test. However this is really broken on master:
```
  Scenario: show the input field for tags in the details view             # /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files-tags.feature:4
    Given I am logged in                                                  # LoginPageContext::iAmLoggedIn()
    And I open the details view for "welcome.txt"                         # FileListContext::iOpenTheDetailsViewFor()
    And I see that the details view is open                               # FilesAppContext::iSeeThatTheDetailsViewIsOpen()
    When I open the input field for tags in the details view              # FilesAppContext::iOpenTheInputFieldForTagsInTheDetailsView()
    Then I see that the input field for tags in the details view is shown # FilesAppContext::iSeeThatTheInputFieldForTagsInTheDetailsViewIsShown()
      Failed asserting that false is true.
```

@nextcloud/javascript 

https://drone.nextcloud.com/nextcloud/server/12455/271

**Comment by skjnldsv** [comment]
```
[06 09:03:09] <skjnldsv> Silly question, how do you add a tag to a file?
[06 09:24:57] <danxuliu> skjnldsv: open the sidebar for the file, click Tags, which will show an input field, and type the name of the tag
[06 09:25:00] <danxuliu> note, however, that the input field for tags may not appear due to a known bug related to the rendering of the details view (I'm on it, but unfortunately I've other things to do with higher priority :-( )
[06 09:25:11] <danxuliu> in that case... just reload the page and try again :P
[06 09:25:14] <skjnldsv> ahaha
[06 09:25:17] <skjnldsv> okay :p
[06 09:25:19] <skjnldsv> thx danxuliu :)
[06 09:25:26] <danxuliu> you're welcome ;)
```

**Comment by danxuliu** [comment]
@skjnldsv No, this is a regression introduced in #12231 (which was backported to 14... :-P ); before it the input for tags was shown as long as the sidebar was not opened again (that is what I was referring to in our conversation which, in turn, was a regression introduced in 16f6c071735577453ab8c4fb24451de28828195e; before that the input for tags was shown without problems after opening again the details view), but now it is not even shown the first time.

Anyway, in the next days I will have to fight with the rendering of the sidebar in order to fix some issues when embedding in it the Talk UI; I already intended to fix the _original_ issue with the tag input plus a race condition that makes the acceptance tests fail sometimes, so if you can wait I will take care of all this hopefully next week. But if someone else is eager to fix it go ahead ;-)

**Comment by blizzz** [comment]
dup of #10774 ?

**Comment by jospoortvliet** [comment]
I can confirm it's broken in beta 2 too, for what it's worth (probably not much :crying_cat_face: )
