### ISSUE TITLE
Minor improvements to iMip mail message text

### ISSUE THREAD

**Issue by brad2014** [nextcloud/server#12391]
The cancelation email says "The meeting  »title« with \<organizer\> was canceled." That is not the semantics of an iTip CANCEL message. It should say that the invitation was withdrawn/canceled for the recipient (the meeting itself may or may not have been canceled, or the recipient may have been removed from the attendee list by the organizer). Also meetings are not necessarily with the organizer, they are by the organizer. Person A can organize a meeting between person B and person C.

Also, using inward (German) »guillemets« in the default English text around meeting titles is a problem, since they are not used in English. English uses super-scripted “double quotes”.  (I notice some l10n files may not have properly localized the quotes).

Better: `The invitation for “title” by \<organizer\> has been canceled.`
or maybe `The invitation for “title” scheduled by $organizer has been canceled.`

See also #11230

**Comment by brad2014** [comment]
Also, the plain  text for iMip messages is
```
Hello John Smith,

  * Wed, Nov 14, 2018, 4:00 PM - 5:00 PM (America/Los_Angeles) (When:)
  * Grand Central Station, New York, NY (Where:)
  * This is a description,
it may be on more than one line. (Description:)
```

Better would be:
```
Jane Doe has invited you to "Meeting title".
* When: Wed, Nov 14, 2018, 4:00 PM - 5:00 PM (America/Los_Angeles)
* Where: Grand Central Station, New York, NY ([Map](https://www.openstreetmap.org/search?query=Grand%20Central%20Station%2C%20New%20York%2C%20NY)
* Description:
This is a description,
it may be on more than one line.
```

**Comment by brad2014** [comment]
Also, the email has a footer that says 
```
This is an automatically sent email, please do not reply.
```
That is incorrect.  The e-mail has a "reply-to" to accept replies, and replying to iMip messages is pretty common (to ask the organizer a question, to propose an alternate time, etc).

**Comment by JonasDralle** [comment]
the mail formatting issue has it's own ticket now: https://github.com/nextcloud/server/issues/13555.

**Comment by georgehrke** [comment]
@brad2014 Would you be up for sending a pull-request for this? :)

**Comment by brad2014** [comment]
I'm going to integrate the suggestions from #13555 and the suggestions from this issue, above, and come up with a PR.  I'll use this issue for tracking.

**Comment by brad2014** [comment]
Note: Both this and #13555 need to account for cases where links to the server are suppressed via dav.invitation_link_recipients introduced into NC 17 via PR #12392.

**Comment by JonasDralle** [comment]
# Calendar Invitations for plain mail are poorly formattet

First off: it's really nice that NextCloud sends HTML emails as `multipart/mixed` and that they put some thought into the `text/plain` segment. I really appreciate this.
There's still room for improvement IMHO.

## What's wrong and how could it be improved?
Plain invitations look like this:
![plain email displaying "meh" formatting](https://user-images.githubusercontent.com/6533815/51083864-4a55b000-1721-11e9-924f-24c747729f00.png)
(another image: [HTML version of the same invitiation redered via Gecko engine](https://user-images.githubusercontent.com/6533815/51083912-f8f9f080-1721-11e9-807f-b17ffb748d6b.png))

### Personally I see three issues:
- Lacking event title. Sure it's in the mail subject but it's important enough to repeat
   - E-Mail subjects behave more like a micro-promotion to consider "Is this worth reading?"
   - the subject line is usually forgotten upon clicking the mail (test on self, sample size = 1)
- Description of Invitiation-Properties are at the end of the line.
   - a question is answered before asked ("Saturday.", "When?")
   - it's very clear that the reader is regarded as a second thought (especially due to the colons)
- inline URLs which are long and can wrap around.

### Proposed changes:
- Add title
- Format Properties in a more straightforward manner and/or change the wording of the property name
- move the URLs at the end of the mail

This is the current formatting:
```
Hello [contact],

  * Fri, Feb 1, 2019, 8:00 AM - 9:00 AM (Europe/Berlin) (When:)
  * Some cool place (Where:)
  * everyone pls bring some food! (Description:)
Accept: [real long accept url]
Decline: [real long decline url]

More options at [real long more url]


-- 
Nextcloud - a safe home for all your data
This is an automatically sent email, please do not reply.
```

This can be considered to be a better formatting:
```
Hello [contact],

  * What:         Picnic
  * When:         Fri, Feb 1, 2019, 8:00 AM - 9:00 AM (Europe/Berlin)
  * Where:        Some cool place
  * Description:  everyone pls bring some food!

Use the links below to [Accept], [Decline] or see [More options].

[Accept]: [real long accept url]

[Decline]: [real long decline url]

[More options]: [real long more url]

-- 
Nextcloud - a safe home for all your data
This is an automatically sent email, please do not reply.
```

This way of formatting links is in line with the [Markdown link sytnax](https://tools.ietf.org/html/rfc7763#section-1.2) (RFC 7763, page 4) which is a very readable format even for people not fond of markdown.

Please be aware of how spacings are used for indentation since the specific tab character configuration of the reader is unknown.

Perhaps add a linebreak after `Description:` to not folly around with multiline descriptions

Perhaps lose the uppercase for the links. `[accept]` instead of `[Accept]`. Your call.

### Assumptions:
- People who read plain likely use a monospaced font (otherwise the spacing will be off)
- People who read plain are not put off by brace-based markdown syntax

---

~I'd like to nominate this issue for being tagged as `good first issue `, `papercut`, `low`, `feature: accessibility`, `feature: emails`.~
Moved from #13555.

**Comment by JonasDralle** [comment]
There's a lot room to improve considering calendar e-mails. There are various issues regarding the e-mail system. Perhaps they can be aggregated into one new concept issue.

To me, calendar invites are important since they allow for sending .ical files to friends which in turn can lead to automatic reminders (e. g. `@icloud.com` addresses and iWatch integration).

**Comment by Luncheon3462** [comment]
@ChristophWurst @miaulalala @st3iny, please help get this fixed. When Office 365 sends calendar invitations, the snappymail nextcloud app by @the-djmaze handles them perfectly. They appear in the email message and can be added to a nextcloud calendar with one-click. Maybe this code that @the-djmaze mentioned will work? https://github.com/the-djmaze/snappymail/blob/fffc04499875531bd3dd626d01baaf7a86452cd3/plugins/nextcloud/js/message.js#L111-L179
