### ISSUE TITLE
Update notification shows warning for non-app store app

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#12475]
* having an app installed, that is not in the appstore or where the appstore doesn't deliver the latest version
* this app has following dependency:
```xml
<dependencies>
	<nextcloud min-version="14" max-version="15" />
</dependencies>
```
* having Nextcloud 14 installed
* change to beta channel to get the update notification for 15
* expected: if the app has max version of 15 at least it is not listed in the section "apps missing updates"
* actual: it is listed in "apps missing updates"

cc @nickvergessen

**Comment by skjnldsv** [comment]
Still happening?

**Comment by MorrisJobke** [comment]
> Still happening?

Yep.

**Comment by nickvergessen** [comment]
Throw here in place 1 instead of returning false and add a catch around place 2:
https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/lib/private/Installer.php#L427

https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/apps/updatenotification/lib/Notification/BackgroundJob.php#L164-L167

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
