### ISSUE TITLE
Adding users to NC from separate file

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#1254]
To ease mass-adding users and their Standard password ot would be very advantageous, if there will be a possibility to add users and their credentials fro  a separate file. Upon first login, th user should be forced to change the standard password!

regards, hitam445r0

**Comment by mar1u5** [comment]
Thank you for your report. If you want to add a whole company or organization into your Nextcloud-Instance, without using LDAP or any separate backend, it would be cool indeed to do an mass-import of users via a CSV-file.

The CSV could include:

- username
- password
- email
- groups

The "force user to change password" stuff is some kind of another request, which could be also interesting for normal (non-mass import purposes) ... Could you open a separate issue on that?
However, I find this issue - but its some time since this, so maybe its a good time for consider about that again: https://github.com/owncloud/core/issues/5308

**Comment by mar1u5** [comment]
cc @blizzz @LukasReschke

**Comment by blizzz** [comment]
Yes, plus as an alternative the Provisioning API can be used to programmatically create local users, https://docs.nextcloud.com/server/10/admin_manual/configuration_user/user_provisioning_api.html

But if you deal with already existing users … yes, use LDAP.

**Comment by hitam4450** [comment]
Adding users by means of using the **occ** command would be a possible solution as well....
So far the commands enabling / disabling users are available at this time!
The **occ** command Adding / removing users is still missing !!!
regards, hitam4450

**Comment by rullzer** [comment]
@hitam4450 nope they are there

`./occ user:add`

**Comment by hitam4450** [comment]
Thanks for the Info! I'll have a look!
