### ISSUE TITLE
Error when sharing to user with email

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#12597]
1. Have no mailserver configured
2. Create a user `userX`
3. Set e-mail for `userX`
4. Share a file to `userX`

Now: You get a nice error message.

You should not get an error message.

**Comment by schiessle** [comment]
I had a quick look at the issue. The problem is that we try to send a mail to the recipient, informing them that a file was shared: https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L679

This could be fixed quite easy with some error handling or a check if mail is configured on the server... **But** I don't understand why we send this mail at all in the sharing code? Istn't this something activities should handle? In the activities settings you can configure mail notifications for shares, in this case you would get them twice. Further as far as I understand there is no settings where a user/admin could configure if this mails should be send or not, by default it is always set to true.

At the moment I tend to just remove it completely... Do I miss something?

**Comment by schiessle** [comment]
I will have a look at it and propose a PR

**Comment by blizzz** [comment]
This also happens on a fresh NC 14 installation
