### ISSUE TITLE
Nextcloud beta to RC web-updater CSP issue 

### ISSUE THREAD

**Issue by xf-** [nextcloud/server#12601]
### Steps to reproduce
1. Go to admin area and click "Open Updater"
2. Loads the Updater and replaces the current content of the page but with initial CSP still in place.
```default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-BLUBB';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self';frame-src https://office.catchit.xyz```
3. Error in console about eval
```Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).```

### Expected behaviour
No CSP issue

### Actual behaviour
Without execution of loaded JS the "Start update" button does nothing.

### Server configuration
**Web server:** Nginx

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 15.0.0 beta 2

Edit: Maybe a duplicate of https://github.com/nextcloud/server/issues/12497 - searched for CSP and eval and found nothing.

**Comment by xf-** [comment]
@MichaIng yes after writing the issue the github search included a link to the issue (because your comment was related). I searched and also looked into milestone (is a blocker for me) and found nothing. The problem is no new page is loaded (Take a look at URL) = old URL and <script> tag with inline script is eval code in CSP. (Server is unrelated as long the CSP header is added.)

Ugly temp solutions:
- Remove the header via webserver
- Allow via Browser Addon or Browser argument CSP
- Modify the source and add eval to CSP - will be removed in update process.

Clean Solution:
- Update via CLI

**Comment by MichaIng** [comment]
@xf- 
Jep, makes sense.

Will stay on Beta 2 for now, to test fix on code bases 😉.

**Comment by xf-** [comment]
@MichaIng i added a second clean way. 
@nextcloud i never got beta 1 - updated said always up to date. Never worked with new Vue router stuff.

**Comment by rullzer** [comment]
Ai. Yes we might need to losen the CSP for the updater page

**Comment by xf-** [comment]
Update itself has no CSP. Because you stay on admin/overview the CSP of admin/overview breaks the updater. Maybe open a new tab or reopen the site should fix it and avoid the Vue router with old CSP.

**Comment by MorrisJobke** [comment]
I will look into this tomorrow. Thanks for the feedback. We totally missed this one.

**Comment by MorrisJobke** [comment]
> Should we try to add the script elements inline via HTML tags?

I tested and it doesn't work. There is another creepy way: parse the `<script>` tags, send them to the server as "here serve this on the next request I will issue" and then insert a "<script src="/apps/updaternoticiations/serveCachedJS.js">" which then serves the previously cached JS. Sounds totally wrong but would be an intermediate workaround. Another option: pass the secret as GET parameter and instead of loading the updater inline, you query `/updater/?secret=ABC` and the updater checks for this GET parameter and does the form submit then on it's own. This is then more self contained and the better option IMO. Is there any problem with this approach? Any bad thing with exposing the secret somehow?
