### ISSUE TITLE
request - add latest tag to latest stable release 

### ISSUE THREAD

**Issue by dkebler** [nextcloud/server#12657]
Can you please always update the latest tag to latest stable GitHub release like the hugo project does
https://github.com/gohugoio/hugo/releases/latest

if you do this with your repo you'll see it takes it to some theme release.
https://github.com/nextcloud/server/releases/latest

This would allow (me/others) to write a script to check for latest release/install it with a bash script.  (Your web based updater never worked for me).

Without a latest tag I won't be able to automate this with a script like I have done for keeping hugo up to date.

**Comment by ChristophWurst** [comment]
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
> if you do this with your repo you'll see it takes it to some theme release.
> https://github.com/nextcloud/server/releases/latest

We actually don't use this feature, because we don't publish releases on GitHub but on our download.nextcloud.com server. We also do not plan to update our script to publish here. I'm sorry if this is not what you expected but we want to focus on the more critical issues. Our stable releases are all like `vA.B.C` without any postfix like `RC1` or `beta2`. Maybe this helps with your script.
