### ISSUE TITLE
[Feature Request] Admin access while maintenance mode is enabled

### ISSUE THREAD

**Issue by jwarkentin1993** [nextcloud/server#13052]
It would be very nice to have the possibility for the admin users to have access to the nextcloud instance while the option "maintenance mode" is enabled.

**Comment by MorrisJobke** [comment]
We had this in the past but it caused a lot of problems. It allowed basically all admins to login. We removed it because it was too rarely used and had a lot of broken parts. And as this still sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature again. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by JD2005L** [comment]
Well I'd add my hat in for some sort of user login prevention for non-admins, doesn't need to be maintenance mode specifically, but just disabling all logins/sessions temporarily while the server is being worked on.

**Comment by thelfensdrfer** [comment]
For example to setup/test plugins, external storage, etc.

**Comment by joshtrichards** [comment]
Current issue tracking this functionality is #40601
