### ISSUE TITLE
Upgrade don't fail cleanly for two majors versions

### ISSUE THREAD

**Issue by rgarrigue** [nextcloud/server#13060]
Hi

I'm running Nextcloud 13 using docker, with a postgresql database and a redis cache. Tried to upgrade to Nextcloud 15. Logs say upgrading two major version isn't supported. Ok, so I change of plan, I'm trying to upgrade from 13 to 14 beforehand. But...

```
nextcloud_1      | Can't start Nextcloud because the version of the data (15.0.0.10) is higher than the docker image version (14.0.4.2) and downgrading is not supported. Are you sure you have pulled the newest image version?
```

I'ld expect an upgrade failed due to requirements not met to avoid messing with the data...

So from here I'ld like to know
- Which data got corrupted ? Is it just a couple of version number, where, or worse ? 
- How do I revert ? I backed up database, apps and settings by copying the data folder. But reverting those still give me the error message. Could it be redis ? 

Best regards,

**Comment by feikede** [comment]
Have this problem, too. Also from 13->15, then to 14. Do you have a solution meanwhile? Thank.

**Comment by sebw** [comment]
Docker hub documentation is terribly lacking. I followed the doc and now I've got a corrupt instance.

I'm running Nextcloud in a container because it's supposedly simpler to manage, less work and less headaches.

**Comment by alexhaas** [comment]
I fell into this exact same trap. 13 → 15, then 14 wouldn't start. I restored my old nextcloud/version.php file from Time Machine (from the nextcloud:13 installation) and then started up the nextcloud:14 container again. CPU went through the roof, so I assume some migration work kicked in. About 10 minutes later, I was back online.

It seems like the problem here is the upgrade to 15 messed with the version.php and this puts nextcloud in an unrecoverable state.

**Comment by sebw** [comment]
Regarding documentation lacking an issue has already been reported: https://github.com/nextcloud/docker/issues/585

I'm going to make a PR.

**Comment by Niondir** [comment]
Thanks a lot, for me it was also just the version.php that was broken after starting v15. Just reverting the version to 13 and using the container v13 woked.
Now I was also able to update from 13 -> 14

**Comment by skjnldsv** [comment]
Please do not skip major upgrades.
If you need to update, please do 13, 14 and 15.

**Comment by vityafx** [comment]
@skjnldsv obviously, no one wants to violate the things you say. But it just happens sometimes, regardless of your intention. Accidentally, I thought, there was only nextcloud 17, but recently newer, 18 version of nextcloud has been published and so I broke my cloud because I was upgrading from 16 to 18. It was not my intention, it just happens. A much better way would be to not tell people what to do and what not to, but to keep a code safe-guards for such situtations, which don't allow breaking the instance while upgrading which is actually not possible. So that you may re-run the process correctly, even if you failed.
