### ISSUE TITLE
New user prompt error, but can normally create

### ISSUE THREAD

**Issue by 330201818** [nextcloud/server#13065]
An error occurred during the request.Can't continue.
Bad request

**Comment by fankijo** [comment]
Same problem here. I've first seen this issue in NC15. While creating a user it sys bad request. This bad request is, due to my logs, because i didnt change the standard email configuration which is set to localhost. So while creating the user your nextcloud wants to send an invitation Email which was given but cant do this, because it cant send an email over localhost due to wrong configuration.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
