### ISSUE TITLE
[NC 15] Error while checking server setup (related to #11088)

### ISSUE THREAD

**Issue by bjoern86** [nextcloud/server#13238]
i have the same error like discribed in issue #11088 on 14.0.4 and 15.0.0. i am running php-fpm without posix.

**Comment by ouafnico** [comment]
Got the same on Nextcloud 15.0.2, with apache2 and php7 (debian 9).

**Comment by danielkesselberg** [comment]
Best guess enable posix?  Please fill out the issue template (https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md). Can't reproduce when you don't provide these information.

**Comment by ouafnico** [comment]
Enable posix ? The setup check was working on versions below 15.

### Steps to reproduce
1. Log to admin account
2. Go to "Vue d'ensemble" (french :p)

### Expected behaviour
Supposed to have warnings about setup or all good and green

### Actual behaviour
Got: "Il y a quelques erreurs concernant votre configuration.
Une erreur s'est produite lors de la vérification de la configuration du serveur"


### Server configuration

**Operating system**: Debian 9 64bits

**Web server:** Apache 2.4.25-3+deb9u6

**Database:** mariadb 10.3.12+maria~stretch

**PHP version:** 7.0.33-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page) 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updates from Owncloud, then to nextcloud at first release, then updated every time to new nextcloud's release

**Where did you install Nextcloud from:** manually from tar.gz

**Signing status:** 
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - sharebymail: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - activity
  - calendar
  - comments
  - contacts
  - encryption
  - federation
  - files_texteditor
  - firstrunwizard
  - logreader
  - previewgenerator
  - serverinfo
  - support
  - survey_client
  - systemtags
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "HIDDEN"
       ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/HIDDEN",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "forceSSLforSubdomains": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "trashbin_retention_obligation": "30",
        "has_internet_connection": "true",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "versions_retention_obligation": "30",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one: None

### Client configuration
**Browser:** Chrome, Firefox last versions

**Operating system:** Debian sid, archlinux

### Logs
#### Web server error log

When error appears, I got this on nextcloud.log : 

{"reqId":"Cua6WrH1aOE62o25bHw8","level":3,"time":"2019-01-15T14:15:55+00:00","remoteAddr":"hidden","user":"hidden","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"Doctrine\\DBAL\\Schema\\SchemaException","Message":"There is no column with name 'object_id' on table 'oc_activity'.","Code":30,"Trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Schema\/Table.php","line":671,"function":"columnDoesNotExist","class":"Doctrine\\DBAL\\Schema\\SchemaException","type":"::","args":["object_id","oc_activity"]},{"file":"\/var\/www\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":629,"function":"getColumn","class":"Doctrine\\DBAL\\Schema\\Table","type":"->","args":["object_id"]},{"file":"\/var\/www\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":681,"function":"hasBigIntConversionPendingColumns","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Schema\/SchemaException.php","Line":86,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"15.0.2.0"}


</details>

</details>

**Comment by danielkesselberg** [comment]
@ouafnico thank you for posting the issue template. Your problem is not related to #11088. I would try this one https://github.com/nextcloud/activity/issues/309#issuecomment-436929111 because the column `object_id` is missing on table `oc_activity`.

**Comment by ouafnico** [comment]
Well done !

I've done the two requests.

MariaDB [cloud]> ALTER TABLE `oc_activity` ADD `object_type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL;
Query OK, 0 rows affected (0.016 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [cloud]> ALTER TABLE `oc_activity` ADD `object_id` bigint(20) NOT NULL DEFAULT '0';
Query OK, 0 rows affected (0.013 sec)
Records: 0  Duplicates: 0  Warnings: 0

Now I got the warnings on setup (imagick and binint) ;)  Now it's all good except php7 warning version.

Thanks !
