### ISSUE TITLE
Top toolbar twitches when mouse pointer is on bottom border

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13263]
NC 15.0.0
Firefox 64.0

### Steps to reproduce
Move mouse pointer to bottom border of top toolbar

![toolbar_twitch](https://user-images.githubusercontent.com/9205230/50441771-44806200-090d-11e9-8b08-a1bf8814cf40.gif)

**Comment by jancborchardt** [comment]
Yep, this is due to the way it’s implemented with the element showing and then fading in via opacity. This is a good first issue, anyone who wants to work on this is welcome to do so! :)

The code is in `core/css/header.scss`, more specifically the code which implemented this is at https://github.com/nextcloud/server/pull/12153/files

If there are any questions, feel free to ask here! :)

**Comment by Xavierando** [comment]
I am new to git and this is my first issue try
i think this issue can be resolved putting the same bottom value in **#appmenu li span** and **#appmenu:hover li span**
 for a better design the value to be changed is in **#appmenu li span**
**from** bottom: -5px **to** bottom: 2px;

**Comment by jancborchardt** [comment]
@Xavierando welcome! :) 
- For a very simple git workflow without Terminal I can recommend the Github desktop app: https://desktop.github.com/
- Or if you want to learn git, check out Git-it! https://github.com/jlord/git-it-electron/releases/latest

Then just open a pull request with your proposed changes and people can review it. :slightly_smiling_face:

**Comment by R0maNNN** [comment]
ok, fixed in 15.0.5, thx

**Comment by MorrisJobke** [comment]
Fixed in #13574
