### ISSUE TITLE
Reverse proxy URL problems

### ISSUE THREAD

**Issue by Rillian-Grant** [nextcloud/server#13310]
When running nextcloud in a docker container exposed to the world via an nginx reverse proxy. Some urls such as the ones that get followed when you click on notifications go to localhost:#### instead of the address of the reverse proxy. Also the desktop sync client doesn’t work on this server. How can I fix this.

**Comment by effektsvk** [comment]
I'm probably having the same issue. I've set up a Docker container but I use traefik instead of nginx. When I go to mydomain.com/nextcloud, it works okay but when I click on Finish setup button, I get to mydomain.com/index.php. I need to get to mydomain.com/nextcloud/index.php.

Here is snippet of my `config/config.php` which I believe is relevant to this issue:
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'overwritehost' => 'mydomain.com',
  'overwritewebroot' => '/nextcloud',
  'overwrite.cli.url' => 'https:\/\/mydomain.com\/nextcloud',
```

Also, @Rillian-Grant maybe you forgot to put these in your config? ☝️ 😉

**Comment by Mythos** [comment]
Thanks @effektsvk that fixed it on my side! 😄 

But somehow it is changed behaviour/a bug, as it worked fine in 15.0.0.
When I updated my docker container to 15.0.2 I started experiencing this problem.

**Comment by effektsvk** [comment]
No problem, @Mythos! I'll try it out with 15.0.0, maybe that will fix my issue as well. 😊

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. 
Though, as this now seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
