### ISSUE TITLE
LDAP with ldaps:// and port 636 not working

### ISSUE THREAD

**Issue by Perflyst** [nextcloud/server#13312]
While setting up ldap with ldaps:// and port 636 I found following issue. Nextcloud still tries to connect via port 389.

I blocked port 389 via iptables on the ldap server and allowed only port 636. That this is working has been proofen via Apache Directory Studio, connection works there via port 636.
Nextcloud is on latest version (v15.0).

`Error	index	OC\ServerNotAvailableException: Lost connection to LDAP server.`

If any further information is required just ask, I will try to provide it.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
My bet is that there is a certificate issue, as it iself does work, respectively the Nextcloud code just passes the connection details to the PHP module. Cf https://docs.nextcloud.com/server/15/admin_manual/configuration_user/user_auth_ldap.html#troubleshooting-tips-and-tricks

Thus, I also would like to ask you to discuss it in the [https://help.nextcloud.com](forums) since it is 99% a configuration issue. Otherwise, if you are convinced it is a bug, please use the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) to provide us the necessary information.

**Comment by stfast** [comment]
Here is solution for Fedora:

1. Copy your exported CA cert:

$ mv domain-CA.pem /etc/pki/ca-trust/source/anchors
$ update-ca-trust

2. Quick check 
$ head /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
....
# domain-CA
-----BEGIN CERTIFICATE-----
MIIFVzCCAz+gAwIBAgIQcs9qUH/7bpFKm3VaChvcnTANBgkqhkiG9w0BAQ0FADA+
....

3.  Since you have all your (AD) LDAP's on domain DNS A record (RR), you should disable certificate check  (or create common certificate ldap.domain.com for (AD) LDAP's).

(With this setting you can skip step 1. and 2.)


$ cat /etc/openldap/ldap.conf 
....
TLS_REQCERT	never
...

so you can use ldaps://domain.com for all domain AD LDAP's and not particular server ldaps://server1.domain.com

4. restart PHP-FPM:

systemctl restart php-fpm
