### ISSUE TITLE
Add an option to prevent indexing of external shares

### ISSUE THREAD

**Issue by helmut72** [nextcloud/server#13472]
**Is your feature request related to a problem? Please describe.**
https://github.com/nextcloud/server/issues/7312

**Describe the solution you'd like**
Please add an option to enable/disable file scan for external mounts. I don't need any fancy indexing for some external mounts. Indexing on the fly is more than enough.

![bildschirmfoto 2019-01-10 um 09 36 27](https://user-images.githubusercontent.com/1388751/50956342-b931cf80-14bb-11e9-8161-2a5cc3448fe9.png)

**Comment by reuterbal** [comment]
Second that! This would also allow to avoid #6395

**Comment by FeistyViking** [comment]
Boy oh boy would this be a life saver of a feature! I third this

**Comment by kaoschris** [comment]
I would like to have that too, we have an Database Size Issue with CIFS Mounts related to Indexing too.

**Comment by helmut72** [comment]
I found a little workaround and use Ajax instead of a Cronjob for the Nextcloud instance, that use CIFS mounts only. Database size is now nice since months. I'm glad it's not used that much, only by a few users.

**Comment by szaimen** [comment]
As a LOT of effort is needed to implement such an feature because many apps rely on the oc_filecache table, currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
