### ISSUE TITLE
Missing "copy" function when source dir is write protected

### ISSUE THREAD

**Issue by nikslor** [nextcloud/server#13577]
The following issue happens on Nextcloud 13.x

Not sure if this qualifies as a bug or a feature request, please feel free to correct me.

Unfortunatelly I can't test it on Nextcloud 14/15 - I hope this is not something that's already fixed there.

### Steps to reproduce

The following is done through the Nextcloud webinterface:

1. create two folders, e.g. folder "read_write" and folder "read_only"
2. place a file "file.txt" into the folder "read_only"
3. restrict folder "read_only" in a way your user can not write into it
4. try to copy the file "file.txt" from the folder "read_only" into the folder "read_write"

### Expected behaviour

The "Move or copy" button should be visible as soon as the file "file.txt" is selected.

### Actual behaviour

The "Move or copy" button is not visible.

**Comment by MorrisJobke** [comment]
> * 
> * restrict folder "read_only" in a way your user can not write into it

How did you accomplished that? 

Because I did it like that:

* create two users
* share a folder with read only permissions from userA to userB
* as userB select a file in this folder
* the option is called "Copy" in this case

![bildschirmfoto 2019-01-15 um 10 45 13](https://user-images.githubusercontent.com/245432/51172115-d0edc700-18b2-11e9-90af-0fa48bf566f1.png)


Let me check if this is a bug in Nextcloud 13.0.x.

**Comment by MorrisJobke** [comment]
Indeed - it is not there in 13. Let me track that further.

**Comment by MorrisJobke** [comment]
This feature was added to 14 via #8203. Thus I will close this here as it is a new feature (the split of "move and copy" into "move" and "copy" operations to better show them partially).
