### ISSUE TITLE
ClearGeneratedAvatarCache upon upgrade is super slow with lots of users/files

### ISSUE THREAD

**Issue by landryb** [nextcloud/server#13587]
Upgrading from 14.0.3 to 15.0.2 on debian stable w/ php 7.2, users in ldap backend by `user_ldap` module, and login via `user_cas` module.

Doing the `occ upgrade` step is super slow on the `Repair step: Clear every generated avatar on major updates` step, as i see it slooooowly removing dirs&files under `$datadir/appdata_$instanceid/avatar/` (and unregistering them from `oc_filecache`). Something like 2s per dir/user, and since i have ~1000 users... it took about 30mn:
```
2019-01-14T14:38:21+00:00 Repair step: Clear every generated avatar on major updates
2019-01-14T15:06:22+00:00 Repair info: Avatar cache cleared
```

dunno if this is related but on this testing instance i have ~4M files in `oc_filecache` - using postgresql 10.5 as the backend. Is the large amount of users to blame ? large amount of files ? could it be sped up in some way ? I don't have a module doing anything specific wrt avatars (ie no user-uploaded avatars, only the generated ones)

**Comment by MorrisJobke** [comment]
This looks very long indeed. We should maybe profile the method https://github.com/nextcloud/server/blob/1aecee52f98727430e82a1611bc7416979a05c80/lib/private/Repair/ClearGeneratedAvatarCache.php#L64

**Comment by ArnY** [comment]
I can confirm this operation is very slow, it took us 3 hours for 10 000 users and 24 millions of files on a S3 ceph storage. But the worst is not only the poor speed, it's also the absence of progress indication during the operation (the amount of iterations is known before launching the operation, a progress bar would have been really easy to implement) and the absence of warning when some other operations like database upgrades are always preceded by a warning that it could take a long time.

**Comment by MorrisJobke** [comment]
I just looked into the code a bit:

This is most likely due to the storage. For local storage and 100 users it took 350 milliseconds here. This is with a DB on the same machine and local storage used. This would then count as 3,5 milliseconds per user, which is over factor 500 from the values from @landryb, nearly factor 300 from @ArnY and factor 200 from another case we know of.

All what is done is that it fetches a folder, tries to delete it and then sets a value in the DB. Then it continues with the next user. I could only explain the high numbers with some latency on the storage level (network attached storage would explain that and is used in the above cases).

@rullzer You added this. I would not manipulate this that much anymore, because it only affects the upgrade from 14 to 15. We could make it an repair step of the category "expensive" and then it needs to be manually triggered.

This should be save, right @rullzer? Because in the worst case it would only delete an avatar that was already generated by the new code and just is generated again.

**Comment by MorrisJobke** [comment]
> Is the large amount of users to blame ? large amount of files ? could it be sped up in some way ?

As written: it's not easy to speed up. Also as this is a one time job that is executed there is currently no plan to change the repair step in hindsight. If you still encounter issues and need dedicated help for big installations we can help out on a case by case basis in combination with your Nextcloud Subscription. See https://nextcloud.com/enterprise for more details.

**Comment by landryb** [comment]
Fwiw, for me this is on local storage on a dell R720xd server, so not really "slow" storage :)

**Comment by MorrisJobke** [comment]
> Fwiw, for me this is on local storage on a dell R720xd server, so not really "slow" storage :)

Could you run a profiler for this request and check what is slow then, because as of now it's hard to predict from the outside.

**Comment by landryb** [comment]
i have zero experience in profiling php stuff, and few time to spend on it, so i doubt i'll manage to debug this without more baby steps on how to profile the request ;)

**Comment by MorrisJobke** [comment]
> i have zero experience in profiling php stuff, and few time to spend on it, so i doubt i'll manage to debug this without more baby steps on how to profile the request ;)

Quite often we use Blackfire: https://blackfire.io/docs/introduction

It has some nice steps, but unfortunately only works on localhost only for free.
