### ISSUE TITLE
FILTER_VALIDATE_EMAIL is too aggressive for administrator e-mail

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#13594]
In the new addition to `maintenance:install` command that allows to also set an admin user's e-mail address, the provided e-mail address is checked against PHP's `FILTER_VALIDATE_EMAIL`:

https://github.com/nextcloud/server/blob/bbec0f0605789687ddd74733def12609f6808524/core/Command/Maintenance/Install.php#L175

This disallows local e-mail addresses such as `root@localhost` -- which would be a better destination on non-public home servers than an outside e-mail address (because it is notoriously hard to get e-mail delivered from broadband IP addresses, for various reasons including port blocking by the ISP and blacklisting of broadband IP address ranges en-bloq by various unaccountable entities).

On second thought, it appears that the same line of reasoning applies to all other e-mail addresses if Nextcloud is run on home servers.

Two ways I can think of addressing this:

#. Relax the requirement to something like `$adminEmail !== null && !filter_var($adminEmail, FILTER_VALIDATE_EMAIL && !filter_var($adminEmail, FILTER_LOCALHOST_EMAIL )` with a suitable `FILTER_LOCALHOST_EMAIL`
#. Do the previous, but make the filtering through `FILTER_LOCALHOST_EMAIL` optional, activated by a `IS_HOME_SERVER = TRUE` setting or such.

See also: `FILTER_VALIDATE_EMAIL` documentation at https://secure.php.net/manual/en/filter.filters.validate.php

**Comment by sklrbecker** [comment]
Hey, taking a stab at this.

### When running:
```bash
sudo -u www-data php occ maintenance:install --database "mysql" --database-name "nextcloud" --database-user "username" --database-pass "password" --admin-user "admin" --admin-pass "password" --admin-email "root@localhost"
```
 in `/var/www/nextcloud`

### This happens:
![image](https://user-images.githubusercontent.com/41128548/97115619-40fec300-16bd-11eb-999a-f32e02ab3f92.png)

This is unintended behaviour and the email validation should allow dotless email addresses.

### This would be achieved by: 
having the address succeed if 
```php
!preg_match('\S+@\S+', $adminEmail)
```
instead of
```php
!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)
```
___
**With that being said**, wouldn't having any string that has at least one `@` in it pass the validation, defeat the purpose of validating in the first place?

Would prompting the user to verify their email address fulfill the same need?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
