### ISSUE TITLE
Have something like apps-data for data of applications

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#136]
> BeS>  LukasReschke: do you have some time looking at https://github.com/nextcloud/server/pull/59#issuecomment-225729589
what's the best solution here?
>
> LukasReschke> BeS: Lemme take a look at the source.
 actually I'd even be provocative on that one and say: we don't write directly to the themes folder but store it in /data/themes (then again if an user is called themes … right … do you see the problem? We might need another folder "apps-data" in the future or so ;)) so in /data/logo.svg and have a controller that delivers the image.
so something like a controller that does readFile(data/logo.svg) and returns it with the correct mimetype for example /index.php/core/custom-template/logo.svg or whatever you like ;-)
> 
> BernhardPosselt> purple 
LukasReschke: god, please yes
app data folder has been missed over all the years
>
> LukasReschke> lemme create an issue for that right away

**Comment by rullzer** [comment]
Yes we need this!

So then it will be `<datafolder>/apps-data` right? As our FS stuff won't properly work otherwise. CC: @icewind1991 

I assume we have to pick something and we just run a pre-update check for NC11 that no user with the name exists.

**Comment by rullzer** [comment]
So as a first step I think it would work to have an AppDataManager. Which has something like `getFolder(<appid>)`.

As a first step we just map this to `/data/<instanceid>/<appid>`.

Since we want something simple. And we want admins to be able to have full control over this. I think we should pose limitations on what can happen in the AppDataDir. I think having something like #1039 (the simplefs) there would make sense.

However that might be a bit to limiting for some use cases (if you want to store files per users you will basicly end up with).

```<AppDataFolder>/<uid>/```

If we chose to go the route of the simplefs you could only store files there. Is that to limiting?

**Comment by MorrisJobke** [comment]
#1306 is merged

**Comment by MorrisJobke** [comment]
@rullzer Could you add the documentation for this?
