### ISSUE TITLE
Enable login wallpaper in public activites

### ISSUE THREAD

**Issue by fulljackz** [nextcloud/server#1360]
### Feature

Not sure if titlte is correct..

As we have a custom login wallpaper, would it be possible to apply this wallpaper to public upload and in public links folders sharing ?

Thanks

**Comment by juliushaertl** [comment]
@fulljackz Thanks for your feature request. This is something for @nextcloud/designers to discuss.

I guess this would only work on the public upload with hidden file listing, if there is a file listing the background is distracting to much from the content.

**Comment by juliushaertl** [comment]
@fulljackz I guess you meant those two screens, right?

![2016-10-05-200537_953x461_scrot](https://cloud.githubusercontent.com/assets/3404133/19125386/23885554-8b37-11e6-96cd-9b2292426188.png)

![2016-10-05-200618_957x327_scrot](https://cloud.githubusercontent.com/assets/3404133/19125412/39fd924a-8b37-11e6-8a1a-202ed8a5e1b8.png)

**Comment by fulljackz** [comment]
Yep, you are right.

I meant the public upload page, like on the first screen.

**Comment by jancborchardt** [comment]
Yeah, it would be too distracting to have the full background there. It’s too much crucial text info there.

On the log in and installation page it’s fine because we have lots of big text and white input boxes. But anywhere else all info must be perfectly readable, so we keep it for uploading the same as for the folder view. :)

**Comment by eppfel** [comment]
I think the problem is not, whether to use a wallpaper or not. There is too much non-crucial text and everything is squeezed in the middle of the screen. Public activities are for people outside of your infrastructure, heck they even have no idea what nextcloud is. 

I feel this needs revising. More than other aspects of nextcloud.

**Comment by Espina2** [comment]
@fulljackz you talking to have something similar to wetransfer? 

https://www.wetransfer.com/

> Yeah, it would be too distracting to have the full background there. It’s too much crucial text info there.
> 
> On the log in and installation page it’s fine because we have lots of big text and white input boxes. But anywhere else all info must be perfectly readable, so we keep it for uploading the same as for the folder view. :)

I totally agree with this.

**Comment by Espina2** [comment]
> I think the problem is not, whether to use a wallpaper or not. There is too much non-crucial text and everything is squeezed in the middle of the screen. Public activities are for people outside of your infrastructure, heck they even have no idea what nextcloud is.

@eppfel I think its not problem that the people dont know, because what matters is the file not the application who are delivering the file. You know what I mean? For sure we can make this look better and more "Nextcloud" but in the end what matter is the file.

**Comment by jancborchardt** [comment]
> There is too much non-crucial text and everything is squeezed in the middle of the screen.

@eppfel what do you mean exactly by this? This is something we recently designed so I’m interested in your take (also that of @Espina2).
- The footer in the screenshot is of course very close to the content because it’s a small screen size. Normally it floats on the bottom.
- We chose to have the avatar very present to make it visual and provide context who you send files to. Maybe when there’s no avatar set, the placeholder should not be shown in this giant fashion.
- Then it’s the folder name which provides context.
- And the upload button which also lets you know about the possibility of drag & drop.

Which of this is non-essential?
