### ISSUE TITLE
Integrity Check: add files/change files

### ISSUE THREAD

**Issue by Micha-Btz** [nextcloud/server#1366]
Hi there,

some of us especially the owns how have hosted webspace needs to put additional settings in .htaccess or need to add some files like .php.ini. Since i have to enable HSTS over the .htaccess i have always errors in the code signing. 

I really like this feature and therefore it would be great when i can update the checksum if i have changed the file or create new ones for uploaded additional files. If you have always the message displayed that files have been changed you will just ignore them and if something bad happen you maybe will get it to know to late.

Is this possible to add a solution for that?
Micha

**Comment by drsbaitso** [comment]
This is also important if you want to change the order of the apps (for instance I don't want activity first I want it last), and then it throws up the error.  I can ignore it, but if I make a known change it would be nice to as @Micha-Btz says, update the checksum or add an exception or something so that if there is a real issue it comes to my attention.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
