### ISSUE TITLE
updater tries to break out of web

### ISSUE THREAD

**Issue by fireba11** [nextcloud/server#13736]
### Steps to reproduce
1. use a webhosting framework like ispconfig
2. try to update
3. updater tries to read from .../updater/../

### Expected behaviour
updater stays within the nextcloud folder

### Actual behaviour
updater tries to read one folder above for "check for expected files", failing due to strong filesystem restrictions

### Server configuration

**Operating system**: debian 9

**Nextcloud version:** update to 15.0.2 (from 14.0.x)

**Comment by j-ed** [comment]
@fireba11 As far as I understood, the updater folder is used to cache the downloaded updates before
they're installed. In the folder hierarchy it is a sub folder of the nextcloud root, which is ok to get everything updated. In your example you wrote that the update function tries to read from `.../updater/../` (one directory above the updater folder is the **nextcloud** root directory) which is absolutely correct from my point of view, because otherwise it could not update the installation nor apps etc.
```
+ nextcloud
  + 3rdparty
  + apps
  + apps2
   ...
  + updater
```

**Comment by fireba11** [comment]
you're right, seems i missread the message. will check again on next update but seems to be fine
