### ISSUE TITLE
Integration of DLNA capabilities

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#1385]
Since **integration** is the **buzz word** these days, why not considering integrating DLNA capabilities into the server or providing them by means of a separate app ??

regards, hitam4450

**Comment by nickvergessen** [comment]
More like an app I think.
Also I don't really understand how this touches Nextcloud. Seems to be more on the hardware side of things.

**Comment by hitam4450** [comment]
Well, it is about interfacing to some  (DLNA - compatible) services or standalone DLNA - server !

regards, hitam4450

**Comment by bavay** [comment]
I'm sorry to comment on a closed thread, but it is exactly what I was looking for: a way for Nextcloud to act as a DLNA server so any smartTV / media player could play media files hosted by Nextcloud. I know that there are already DLNA servers that could be installed, but having one integrated within Nextcloud could be a big plus (so we avoid the issues of one system not being aware of some of the files because it would need a rescan, etc). Most probably this should be an app...

**Comment by schiessle** [comment]
@bavay Yes, having a app which serves as a DLNA server would be really nice. Although I have no ideas how hard it is, if there are already ready to use PHP libs, etc. Maybe you want to start a discussion at help.nextcloud.com to brainstorm a bit... Who knows maybe someone will get motivated to develop such an app.
