### ISSUE TITLE
Booking and Managing Conference Rooms

### ISSUE THREAD

**Issue by circlenaut** [nextcloud/server#13875]
I think it would be really cool for Nextcloud to feature a conference room management portal. For example, I would invite a certain number of people to a room and from the invite panel I would be able to see the schedule and availability of certain rooms. Bonus points for having an iOS or Android app were we could attach to each room so people can see in real time the schedule of the particular room and book right there!

**Comment by MorrisJobke** [comment]
@circlenaut Have you had a look at the talk app already? Because this sounds exactly like that and it has native apps for iOS and Android 😉 

https://apps.nextcloud.com/apps/spreed

I will close the ticket for now, but if there is something unclear, maybe raise your voice in the repo of the talk app: https://github.com/nextcloud/spreed

**Comment by Spartachetto** [comment]
@MorrisJobke my impression is that @circlenaut is looking more to something like #9773 ....

**Comment by MorrisJobke** [comment]
@Spartachetto Ah - thanks 🙈 I misread this totally. But then the question is answered as well 😉
