### ISSUE TITLE
Global OAuth Configuration

### ISSUE THREAD

**Issue by williambargent** [nextcloud/server#140]
### Expected behaviour

When configuring OAuth for Google Drive and Dropbox the Client ID and Secret Key should be set once in the /config/config.php file. This is so all users use a single API and the secret key doesn't need to be shared with users or the need to create their own.
### Actual behaviour

Each user who wants to mount one of these locations need to provide a client ID and secret key.

**Comment by MorrisJobke** [comment]
This is what the global auth configuration in ownCloud EE did for some external storage providers.

@blizzz Maybe we could build this in a way, that every external storage benefits from it ;)

**Comment by williambargent** [comment]
It makes sense for it to be in the standard edition, many users won't know what/how to obtain this. The admin should and will then be able to manage it for the whole installation. Would make life simpler for sysadmin's.

**Comment by MorrisJobke** [comment]
This would mean that you run faster in the rate limiting of the services. Additionally it doesn't look like this is possible anyways in the future, because they look down more and more - ref #5815

As of now there is no plan to do this in config.php. If at all this should happen in a dedicated app only responsible for the specific storage.

I will close this here for now.
