### ISSUE TITLE
Undefined variable: vendor at /var/www/html/lib/private/Updater.php#195	

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#1411]
After an update from 10.0.0, I guess we should also make a check if the variable actually exists?

Ref https://github.com/nextcloud/server/blob/908cbcea838c1344105682e19864b1357b937fd9/lib/private/Updater.php#L195

cc @nickvergessen

**Comment by nickvergessen** [comment]
Well, the variable exists:
https://github.com/nextcloud/server/blob/stable10/version.php#L41-L42

We could of course add code to check for it:
https://github.com/nextcloud/server/commit/b576c46dd874de4381e2101753d6057588c137dd

But the problem seems to be packaging, which replaces the file with the following content:
```php
<?php 
$OC_Version = array(9,1,1,0);
$OC_VersionString = '10.0.1 RC1';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(9,0);
$OC_Build = '2016-09-14T18:07:25+00:00 908cbcea838c1344105682e19864b1357b937fd9';
```

Can this be fixed to also include the vendor variable? Or should I rename the var to `OC_Vendor` does that automatically fix it?

**Comment by LukasReschke** [comment]
What is the use-case of the variable? Should it be there? For what versions? The release script does some magic but I guess it should be adjustable ;)

**Comment by nickvergessen** [comment]
It is to allow to "upgrade" a higher version of the same branch from an other vendor to nextcloud.

So you can "upgrade" owncloud 9.1.1.1 to nextcloud 9.1.0.13

**Comment by nickvergessen** [comment]
Branches 10+, so stable10 and master atm

**Comment by nickvergessen** [comment]
But we could also add it in 9 to avoid version magic in the release script, and just not make use of it

**Comment by LukasReschke** [comment]
> But we could also add it in 9 to avoid version magic in the release script, and just not make use of it

👍

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/1416 for stable9

packaging fix will come from lukas

**Comment by LukasReschke** [comment]
Added with https://download.nextcloud.com/server/prereleases/nextcloud-10.0.1RC2.tar.bz2
