### ISSUE TITLE
Missing hamburger menu in mobile mode

### ISSUE THREAD

**Issue by shorty-look** [nextcloud/server#14252]
### Steps to reproduce
1. Log-in as an admin user with a smartphone/tablet browser or in a small size browser
2. Go to Users settings
3. try to add new user or group

### Expected behaviour
I can create a new user or a new group

### Actual behaviour
menu for new user or new group disappears and can't add a new user or a new group, I can only see users already active

### Server configuration
**Nextcloud version:** 15.0.4

**Comment by MorrisJobke** [comment]
I also noticed that. 

Happens on small screens:


small screen:
<img width="828" alt="bildschirmfoto 2019-02-20 um 14 39 23" src="https://user-images.githubusercontent.com/245432/53095517-5c472180-351d-11e9-924b-5123103d633d.png">

once it is a bit wider the sidebar is there and accessible:
<img width="933" alt="bildschirmfoto 2019-02-20 um 14 39 27" src="https://user-images.githubusercontent.com/245432/53095519-5c472180-351d-11e9-9ce0-89097292ed19.png">


@nextcloud/javascript @skjnldsv May it be because there is no hamburger menu there?

**Comment by skjnldsv** [comment]
Yes, there is an issue with the :hamburger: :confused:

**Comment by MorrisJobke** [comment]
@skjnldsv Any news here?

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/14934
