### ISSUE TITLE
Fulltext Search and indexing

### ISSUE THREAD

**Issue by skerbis** [nextcloud/server#1431]
Please add a Fulltext Search.

**Comment by SlavikCA** [comment]
It's done via https://github.com/nextcloud/nextant

**Comment by 8347** [comment]
It's not done if you need to install additional stuff - which can't be installed on a hosted/shared server...

**Comment by kvoit** [comment]
It IS done. The really last thing I want to use is a full text search implemented in PHP.

**Comment by skerbis** [comment]
It's done, yes but the really last thing I want to use is a full text search implemented in JAVA on a production Server.

**Comment by kvoit** [comment]
Sounds clever, he? Unfortunately, Apache Solr is a reputable, highly scaleable enterprise solution that can e.g. also be used for indexing mails in larger dovecot email configurations, which is an awesome solution for indexing the amounts of data that many Nextclouds will face. Badmouthing that in favor of some home-brewed PHP solution just to save the 2 bugs price difference between hosting and virtual server for some hobby installation is just ridiculous.

**Comment by skerbis** [comment]
Can i use Solr under PLESK / Odin , i can't find a Tutorial.  I would give it a try.

**Comment by Bugsbane** [comment]
I'm running my Nextcloud on a dedicated server, so I don't personally have a horse in this race, however it is worth noting that is part of Nextcloud's mission (and ownCloud before it) to run on shared hosting, so virtually anyone can use it, not just universities, government departments and corporations with IT departments.

As such, it seems that if full text search is to be considered a core part of Nextcloud, then it too should be able to run on most shared hosting.

**Comment by MariusBluem** [comment]
Come on guys... Nextcloud 11 has introduced **Full-Text Search** with **Nextant**: https://nextcloud.com/blog/nextcloud-11-introduces-full-text-search/ - which is great!

You all are correct, if you say that is more complicated to install then other Nextcloud apps or even in parts impossible to use it on shared hosting or any other restricted instances. But this is how intensive and big tasks work ... they are not one-click. Same applies to Collabora Online ... and Spreed.ME. At least Video chat (Spreed) is now available in pure PHP with one-click installation: https://github.com/nextcloud/spreed

...it does not make sense to give any additional effort in the task to make this (Full-Text Search) available in pure PHP and without additional stuff.

The performance of Full-Text Search with a shared hosting would be incredibly slow, everybody would complain about that. The answer would be - please use a more powerful instance - with Solr! And I think neither you as an admin - nor the provider will be happy if you would run full-text searches on shared instances cause of the memory it would take.

If you rely on your shared-instance Nextcloud (which is legit) you may want to [run a standalone Solr server](https://github.com/nextcloud/nextant/wiki/Setup-your-local-standalone-Solr), and integrate it with Nextant on your shared hosting ... this should be generally possible, but i would not recommend it for the reasons I've given you above.

If you need a custom solution with Nextant - and dont have the time or the knowledge to use an root-instance, you may also want to ask **your** provider - or one of our [Nextcloud providers](https://nextcloud.com/providers/) for help.

Of course... if anybody who is interested in this wants to write an implementation as an app, it would be great - and he is welcome to.

I will close this ticket now because the task itself - "Fulltext Search and indexing" is solved with Nextcloud 11 and Nextant.

**Comment by skerbis** [comment]
Does anyone know how to install solr in Plesk/Odin? Can i install it without getting Problems?

**Comment by MariusBluem** [comment]
> Does anyone know how to install solr in Plesk/Odin? Can i install it without getting Problems?

Try to setup Solr as Docker Container inside of Plesk ... I've not tested this, but Plesk does support Docker since the newest version 😉 ... https://hub.docker.com/_/solr/
