### ISSUE TITLE
Won't rly sync at Mac (alle dateien im lokalen synchronisationsordner)

### ISSUE THREAD

**Issue by truskalm** [nextcloud/server#14360]
<img width="554" alt="bildschirmfoto 2019-02-24 um 01 36 56" src="https://user-images.githubusercontent.com/20729432/53293507-42376880-37d5-11e9-8c75-5f900e4f9355.png">

**Comment by MorrisJobke** [comment]
This means that there were some files in your Nextcloud, but then somehow all files were not available in this root folder (maybe intentional) - then the client warns about this. If this was intentional you can continue the sync. Otherwise click "keep local files" and it will add them again to the server.

**Comment by MorrisJobke** [comment]
As this seems to be setup related I would like to ask you to raise future questions in the forums: https://help.nextcloud.com
