### ISSUE TITLE
Language with incorrect name 'af' in Language drop-down in Settings

### ISSUE THREAD

**Issue by krupenja** [nextcloud/server#14378]
### Steps to reproduce
1. Open Nextcloud.
2. Go to Settings -> Personal info
3. Scroll all the way down.

### Expected behaviour
Only languages with correct names appear in the list.

### Actual behaviour
Language with a strange name 'af' appears in the list. If you select it, Nextcloud language stays English.
![image](https://user-images.githubusercontent.com/26354715/53366532-7bdeaf80-394c-11e9-9c73-8f67bdf7d553.png)

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache/2.4.29 (Ubuntu)

**Database:** mariadb  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )

**Nextcloud version:**  15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://nextcloud.com/install/#instructions-server

**Comment by MorrisJobke** [comment]
Thanks for noticing. I fixed the transifex sync script to fetch also languages that are only 0-1% translated. This is the case if in the translation package only the name of the language is translated. It showed up in the menu, because some apps have pretty good Afrikaans translation but the `lib` module which holds the language name only had this single entry deleted. 

Should be fixed in the next versions of Nextcloud.
