### ISSUE TITLE
Enterprise Features...

### ISSUE THREAD

**Issue by b1ggjoe** [nextcloud/server#144]
Would it be possible in the future to add a few more Enterprise features , such as integration with DRM platforms and the likes of that which is found here:

https://www.syncplicity.com/features/

?

Thanks!

J.

**Comment by LukasReschke** [comment]
Depends always if somebody is doing them, or whether somebody is paying somebody else to do them. We don't have really done much thinking into thoughts such as "DRM" or so on. (also because DRM is mostly a snake-oil anyways)

Anyhow, please file dedicated feature requests for each feature that you miss. Such generic discussions as these should otherwise be filed on our forums: https://help.nextcloud.com

**Comment by b1ggjoe** [comment]
Makes sense. Ok, will do.

Thank you!

J.

**Comment by b1ggjoe** [comment]
Lukas,

My apologies! After re-reading this post for some odd reason (perhaps it was my auto-correct on my phone...I dunno) I put 'DRM' as an Enterprise coveted feature.

LOL what I meant was integration with Enterprise platforms such as 'MDM', like 'Mobile Device Management'.

That way, in an Enterprise organization once an employee leaves the company, the IT Staff can remotely 'wipe' or remove the actual 'data' that belongs to the company and so forth, leaving any 'personal' data un-touched.

My apologies for saying 'DRM'.

DRM and I get a long about as much as the MPIAA and Pirate Bay does so my apologies LOL.

BJ.
