### ISSUE TITLE
Login with a nonexisting username shows error "Wrong password."

### ISSUE THREAD

**Issue by Nutomic** [nextcloud/server#14460]
### Steps to reproduce
1. go to index.php/login
2. enter a random username that does not exist, and a random password
3. press submit

### Expected behaviour
Nextcloud should indicate that the username is wrong. For example, a message like "Wrong Username or Password" could be shown.

### Actual behaviour
Nextcloud just shows "Wrong password.", making users think that the username was entered correctly when it was not.

### Server configuration

Reproduced with Nextcloud 14 (Docker installation) and Nextcloud 15 (Snap installation).

I will probably make a PR soon to fix this issue.

**Comment by bpcurse** [comment]
It think it should be considered to simply show "wrong username / password combination provided" or something similar as many other webservices do. If the naming schema of the instance is known an attacker can easily check if a certain person has an account registered at this instance thus leaking this metadata. It probably is not a problem in the most cases but it could be in some.
Please don't get me wrong, I am aware that no large scans are possible due to bruteforce protection and this also is not about security through obscurity, just the potential metadata leak.

**Comment by Nutomic** [comment]
@bpcurse agreed, thats why I only want to change the error message, not any of the logic. So an attacker wouldnt get any more information than they could get today.
