### ISSUE TITLE
Settings Link in Navigation

### ISSUE THREAD

**Issue by digitalhandwerker** [nextcloud/server#14827]
When using Nextcloud I find myself often clicking the menu item "Settings" on the bottom left rather than the popup hidden behind the avatar expecting to be brought to the settings menu.

![nextcloud_settings_ux](https://user-images.githubusercontent.com/30568489/54882932-a47c9b00-4e5f-11e9-827a-ff58ac0b0d36.png)

I suggest changing the link and making the WebDAV settings part of the settings page.
I think this would enhance the user experience. Especially when setting up Nextcloud the link to the settings page should be visible on the first overview of the dashboard.

**Comment by skjnldsv** [comment]
Wrong repository.

@nextcloud/designers @jancborchardt thoughts?

**Comment by jancborchardt** [comment]
Not really sure here. The thing about these in-app settings is that they are directly related to the app, like in the case of Files also "Show hidden files". People shouldn’t need to exit the app and go to a separate settings section to quickly toggle that.

The idea is that Settings in the top right are for either admin settings or user settings that you likely set once and then not anymore. And the bottom left area is for common actions. Since with Nextcloud we prefer to design things simply, apps tend to not have any settings in the user settings, only in admin settings at most, and maybe something in the direct app settings, if at all.

**Comment by MorrisJobke** [comment]
> Not really sure here. The thing about these in-app settings is that they are directly related to the app, like in the case of Files also "Show hidden files". People shouldn’t need to exit the app and go to a separate settings section to quickly toggle that.
> 
> The idea is that Settings in the top right are for either admin settings or user settings that you likely set once and then not anymore. And the bottom left area is for common actions. Since with Nextcloud we prefer to design things simply, apps tend to not have any settings in the user settings, only in admin settings at most, and maybe something in the direct app settings, if at all.

Makes sense and that's why we put it where they are now. Let's close this ticket for now.
