### ISSUE TITLE
DB error while updating to 15.0.5

### ISSUE THREAD

**Issue by gcarpent** [nextcloud/server#14846]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by wallenium** [comment]
I had the same for 16.0.0 Beta 2

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Most likely because of outdated MariaDB 5.5.31. Hoster WebGO said, they are not able to upgrade...

https://github.com/doctrine/orm/issues/7416

**Comment by kesselb** [comment]
Thank you for reporting this issue :tada: 

See this issue for more information https://github.com/nextcloud/server/issues/15058
