### ISSUE TITLE
An unknown error occurred when canceling big upload

### ISSUE THREAD

**Issue by JochenEmmes** [nextcloud/server#14897]
### Steps to reproduce
1. Upload a large file (>2 GB)
2. Cancel the upload while it is still running
3. Error message pop up

### Expected behaviour
Tell us what should happen: Confirmation (Upload cancelled by User) or nothing

### Actual behaviour
Tell us what happens instead: An unknown error occured. In the log I see 

Error | PHP | rmdir(/media/nextclouddata/admin/uploads/web-file-upload-18d7f2204cc78a95bddd48c88affbadc-1553760974752): No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#118
-- | -- | --

### Server configuration

**Operating system**: Ubuntu Server 18.04  LTS

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page):15.05.03

**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:** Nextcloud download page

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Standard apps as after a fresh install

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome Ver. 73
**Operating system:**
Win 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Error | PHP | rmdir(/media/nextclouddata/admin/uploads/web-file-upload-18d7f2204cc78a95bddd48c88affbadc-1553760974752): No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#118 |  
-- | -- | -- | --



</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by GuyPaddock** [comment]
I am seeing this issue here as well, with an upload of a folder containing 1.5 GB files.

**Comment by harveytj03** [comment]
I can confirm this is still a issue with Nextcloud 19.0.1. I have made multiple fresh installs on different hardware and VMs with no fix. There was a "fix" but ended up causing a "NotFoundError" file to appear if I upload a folder over 1GB and the status would be "100KB out of NaN"

**Comment by PVince81** [comment]
the issue still exists but has changed form a bit, this is what I saw on 22.2.0 and 22.2.4rc1:

it seems the DELETE request is sent twice
<img width="877" alt="image" src="https://user-images.githubusercontent.com/277525/148925951-a19eb114-d3d3-474d-9743-c1d55f5dae60.png">

and because of the second one, it causes a JS error 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/277525/148926070-80f9b2f0-9b84-48dc-a87c-b10c3f22ef5a.png">

and doesn't remove the progress bar

**Comment by PVince81** [comment]
it looks like browsers have changed behavior when cancelling a request (or jQuery changed)

in the past when aborting a request, jQuery would through an error of type cancelled or aborted

but now, the browser cancels the request but we still get a response from the server, usually 500, probably because it stopped receiving data and complains about missing bytes or something

so we need to change the approach

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/30620
