### ISSUE TITLE
Ability to click on part of row in webview to open sidebar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#14944]
Right now the click event on the whole row of a file triggers a download/open. What I would expect and what I already heard from many other users:

1. Clicking on the filename/folder should trigger a download/open
2. Clicking on the empty area between file name and share icon should open the sidebar

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
We used to have something like this, if you remember. :) It resulted in a lot of confusion about where an open is triggered and when the sidebar shows. And filenames have different lengths, so is the sensitive area basically per file? And how do we do it on mobile? And what about the grid view?

These are some of the reasons why we just went for the simple approach.

Also, the people you refer to when saying
> what I already heard from many other users

what’s their background? How many were there? It doesn’t sound like it came up in a usability test but was a conscious request – which we need to weigh against what will happen in the real world.

**Comment by jancborchardt** [comment]
> Intuitively I (and others I heard from) try to select another file by clicking on the empty space of the row

Sorry, but this really sounds like anecdotes or a personal wish rather than a usability issue? As said we actually _did_ have it just like that in the past and it led to lots more confusion, where half the time when you wanted to open a file it opened the sidebar instead.

If you really want to dive into it, it’s best to check how some other online file managers do it, like those of Dropbox, iCloud and Google Drive, list their behavior and we can discuss based on that. (Of course desktop file managers handle this with single click to select vs double click to open, but we’re not going to introduce necessity of double click.)

**Comment by radoslavius** [comment]
But this behaviour is still working in latest version of NC
https://help.nextcloud.com/t/show-info-after-click-on-file-folder-icon-instead-open-it/66460
Clicking on the icon to display sidebar would be nice. I do not know if this is intention or bug.

**Comment by eibex** [comment]
Previously it was possible to open the sidebar by clicking on the last modified date of the file. Now it is downright impossible except for photos (open the photo preview and then open the sidebar from the menu).

How can older versions be restored and/or file activity be viewed if it is not possible to open the sidebar at all?

Not even the options button (or right click) have a "view details" option. Adding a "view details" option from right click could be a possible solution if clicking on a different area of a row and leading to a different action is an issue.

**Comment by skjnldsv** [comment]
Fixed. Clicking on any column after the three-dot menu actions opens the sidebar if available.
