### ISSUE TITLE
Nextcloud uses oc_ prefix on clean install

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/server#150]
### Steps to reproduce
1. install nextcloud (no upgrade)
2. setup user/db
3. look at config.php

### Expected behaviour
nc should use nc_ as prefix and userprefix

### Actual behaviour
nc uses oc_ as prefix and userprefix

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache2

**Database:** MySql

**Nextcloud version:** 9.0.50

**fresh install:**

**Where did you install Nextcloud from:** tar archive

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx.ddns.net',
  ),
  'datadirectory' => '/mnt/SSDSA2CT040G3/rootfs/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://xxx.ddns.net/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.0.50.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_Darkwing1',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```

**Are you using encryption:** no

**Comment by mar1u5** [comment]
This is correct. We are currently using `oc` at many places in Nextcloud 😉 ...we are also calling the command line tools `occ` instead of `ncc` for reasons of compatibility. (I think) this will also be part of Nextcloud 10 ... we have currently no plans to change this in the next weeks and months. But in the long term ... of course 😁

**Comment by smirkybg** [comment]
I just installed phpmyadmin, it has a nice feature to select all the tables you need and rename the prefix.
Removed the package, then changed the config.php to use the new nc_ prefix and everything worked without additional changes.
Anyway, that has nothing to do with the problem here, I know.
I'm just mentioning that renaming the tables has no effect on nextcloud and perhaps the change to install the tables with nc_ prefix won't be that much of an effort.

**Comment by mar1u5** [comment]
You are right @smirkybg 😉 Changing the prefix is possible in the config: `dbtableprefix` ... Maybe we should consider about using nc_ instead of oc_ 😁 

cc @MorrisJobke

**Comment by mar1u5** [comment]
Maybe we could also do this for security reasons, by using an random one, or by making this configurable due the setup 😉 

cc @LukasReschke

**Comment by BernhardPosselt** [comment]
@mar1u5 no security benefits here :)

This is a known "feature" that might not work in various apps if they did not explicitely use it. As noted above we should keep all the owncloud prefixes for compatability reasons. 

@MegaV0lt if this is fine for you, could you close the issue :)?

**Comment by mar1u5** [comment]
WordPress declarates it as Security improvement. Thats why I thought  :grin: @BernhardPosselt

**Comment by MegaV0lt** [comment]
No problem.
