### ISSUE TITLE
Move database container to Ramdisk in CI

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#15013]
To avoid slow test execution we should move the data dirs of the database containers (mysql & Postgres) to shared memory (/dev/shm). The option `shm_size` in drone should be useful to increase the size from 64 MB to something useful. (see https://github.com/nextcloud/server/blob/0f7f839c590f736a4044f7ca460a0b57147b6e37/.drone.yml#L2282)

Here is a very slow CI job, that ran on one of our main servers with old HDD instead of SSDs (https://drone.nextcloud.com/nextcloud/server/17649/22/5).

cc @ChristophWurst @rullzer

**Comment by rsynnest** [comment]
Looking into this as my first issue. The database containers defined in `.drone.yml` are already using tmpfs (ramdisks) for their datadirs. So I'm not sure why the slow CI job may have occurred (which is now a dead link) but it looks like this is a non-starter?

**Comment by PVince81** [comment]
not sure if this will still be relevant when moving everything to Github actions ?

**Comment by joshtrichards** [comment]
Moving the db to `/dev/shm` (or to a another mount point that is `tmpfs` based) still seems to be an option, but probably far less necessary since it's all SSD backed these days (no HDDs!):

Refs:
* https://stackoverflow.com/questions/75726151/is-it-possible-to-use-tmpfs-on-a-github-workflow-service
* https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by skjnldsv** [comment]
Probably not relevant anymore yeah
