### ISSUE TITLE
Troubles syncing SMB Share

### ISSUE THREAD

**Issue by whberkhof** [nextcloud/server#15156]
Hi We are running a nextcloud server 15 to open some files with external users and employees who are working outside the office. But we are having some troubles to get everything up to date. A user reported some folders on his client are empty, when logged in to the webinterface as the user and browsing to that folder the client starts to sync the data. But we don't like this, you understand. Can anyone help me?

**Comment by thechonta** [comment]
https://github.com/nextcloud/server/issues/15033
#15033
It is the same Problem, probably related to the Syncclient itself.
If you open an File over the Webbrowser , nextcloud will connect to the File on the backend and display the new one.
Also the Client get new informations about new and changed files.
The Problem is, if you change a file over the browser, the timestamp will not be changed and no one else but you will get the changes synced over the desktopclient.
Even wors if another one changes the same file a little bit later and  sync it with the desktopclient it will be handled as new and actual file and your changes made via browser are gone.

**Comment by kesselb** [comment]
Would you mind to edit your post and provide the issue template? https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by whberkhof** [comment]
Hi, we have found a solution/workaround. The solutions was making a cron job running 2 times day which will scan the SMB share on changes. That works fine.
