### ISSUE TITLE
Microsoft Office Online Integration

### ISSUE THREAD

**Issue by FelR** [nextcloud/server#15234]
ownCloud has added support for on-premise Microsoft Office Online servers with its 10.1 release. https://doc.owncloud.com/server/10.1/admin_manual/enterprise/collaboration/msoffice-wopi-integration.html

I would love to see this feature be implemented in nextcloud too.

Best regards,
Felix

**Comment by informatik-bks** [comment]
I also vote for this!

**Comment by lenaulrich** [comment]
For Nextcloud there is an app called Office Online. I guess this is probably what you are looking for?

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
