### ISSUE TITLE
DLNA Server

### ISSUE THREAD

**Issue by Ang3er** [nextcloud/server#15362]
I would like to reqeust the feature of a properly build DLNA server inside Nextcloud, to use the gallery app as well as a network wide DLNA/UPNP server. All current solution I tested (minidlna, universal media server, plex, ps3 ...) dont realy address my need of a small handy ONLY dlna server, as I do not want to replace the gallaray of nextcloud. Unfortanatly my tv is to dumb to use this gallary. 

Iam also refereing to https://help.nextcloud.com/t/dlna-server-within-nextcloud/15012 and https://github.com/nextcloud/server/issues/1385 which are describing the same issue.

Thanks in advance

**Comment by GAS85** [comment]
You can easily do this by standard tools.
1. Create directory like `/home/user/myNextcloud`
2. Added this directory as Video/Audio/Pictures source to your DLNA Server.
3. Mount with davfs2 your Nextcloud user folder (or other needed with Audio, Video, Picrutre) via WebDAV to `/home/user/myNextcloud`
4. Enjoy!

**Comment by daveybops** [comment]
There seems to be a few ways to get this to work on Nextcloud, a quick web-search reveals multiple suggestions, which are going to work for some people, and won't for others due to varying configurations.  Example, I use the Nextcloud Snap installation on a Pi v4 with one USB HDD storing my nextcloud data.  Since Snap installations of Nextcloud runs as root, I made the miniDLNA user part of the root group!

This is not secure in my mind, but was a quick and dirty way of getting it to work.  And the miniDLNA service crashes occasionally, so I have a cronjob set to restart the service daily.  I think a better way for this to work, if at all possible, is for the function to be included in Nextcloud.

Since I'm not a programmer, I am relying on the goodwill of developers, who know more than me to implement this in the future.  I, among others, would really, really appreciate it!

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers

**Comment by thanek** [comment]
If anyone's interested, I created a simple DLNA server which is integrated with the Nextcloud app. You can grab it from here https://github.com/thanek/nextcloud-dlna
