### ISSUE TITLE
spelling mistake in english reset password screen

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/server#15529]
![image](https://user-images.githubusercontent.com/3179748/57695134-bf90ad80-764d-11e9-9d6d-fac255c79dd8.png)

Spellingerror in reset password screen, it should say "sent"  instead of  "send"

**Comment by wiswedel** [comment]
confirmed, needs some love

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/ee6011d2d5093e0f9a6bb2540726a286364d6896/core/src/lostpassword.js#L6

**Comment by BrookeDot** [comment]
How about:

> A password reset message has been sent to the e-mail address for this account. If you do not receive it, check your spam/junk folders then ask your local administrator for help.

?

**Comment by GretaD** [comment]
@BrookeDot sounds good, do you want to submit a pull request or should I do it?

**Comment by AdrianaTobon** [comment]
Hi @BrookeDot  @GretaD  I am new to the project and am looking for a good first issue, seems like this is super straightforward, I'd love to help!

**Comment by GretaD** [comment]
@AdrianaTobon sure, go ahead, and comment here if you need any help.

**Comment by BrookeDot** [comment]
>  I am new to the project and am looking for a good first issue, seems like this is super straightforward, I'd love to help!
👍

**Comment by AdrianaTobon** [comment]
Hi @GretaD @BrookeDot I hate to say this but I have had some issues setting up the dev environment, seems like this issue is pretty straightforward so I don't want to hold it up. As soon as I can I will try to install again and see if there is any other open issue I can contribute to. Thanks and sorry for the inconvenience!

**Comment by akshala** [comment]
I am new to this project and I would like to work on this issue.

**Comment by akshala** [comment]
Hi I am new to this project and  would like to work on this issue.

**Comment by akshala** [comment]
Hi I am new to this project and open source. I would like to work on this issue.

**Comment by GretaD** [comment]
@akshala sure go ahead, and thank you :)

**Comment by BrookeDot** [comment]
@akshala have you had time to look into this? If you need any help, leave a comment here. I would love to see this fixed.

**Comment by akshala** [comment]
@BrookeDot, I was having trouble in locating the lostpassword.js file

**Comment by GretaD** [comment]
Hey @akshala and @BrookeDot,
I think this bug is fixed because of this change: https://github.com/nextcloud/server/pull/15647
Thats why you cannot find the file lostpassword.js, now its called ResetPassword.vue. 

But if you want, maybe you can change it as @BrookeDot suggested above:
> A password reset message has been sent to the e-mail address for this account. If you do not receive it, check your spam/junk folders then ask your local administrator for help.

because on the new file its exactly the same, it is just fixed the "sent" word.
