### ISSUE TITLE
mysql port syntax in config

### ISSUE THREAD

**Issue by netroby** [nextcloud/server#15560]
nextcloud-server：16.0.1

If the mysql server port not default 3306, then your config.php `dbport` not have effect. 
error log show us : refuse to connect mysql server

and the solution, is make the dbhost `ip:port`

like 
```php
    'dbport' => '192.168.1.3:3358',
```

**Comment by BernieO** [comment]
There is no configuration value like `dbport` in the admin manual and the admin manual clearly states that the port has to be added in `dbhost`:

https://docs.nextcloud.com/server/16/admin_manual/configuration_server/config_sample_php_parameters.html#default-parameters
> To specify a port use hostname:####

This is desired and documented behaviour and not a bug in my opinion.

**Comment by kesselb** [comment]
Thank you for triage @BernieO :tada:

Feel free to repopen if dbport is documented anywhere @netroby.

**Comment by netroby** [comment]
@BernieO @kesselb 

https://github.com/nextcloud/server/search?q=dbport&unscoped_q=dbport

The nextcloud install wizard will create configure file, contains the dbport config section.
So it not a document problem your code should  not contains `dbport` configure section,
It was not right.

**Comment by kesselb** [comment]
Fair enough ;)

@nextcloud/server-triage Remove `dbport` or use the value?

**Comment by BernieO** [comment]
good find @netroby

**Comment by MorrisJobke** [comment]
> @nextcloud/server-triage Remove `dbport` or use the value?

I guess I don't get it fully. The port is written back to the config file, but this should not cause problems. Also the port is used and only if not filled then it uses the part from the host config:

https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Setup/AbstractDatabase.php#L120-L135

**Comment by BernieO** [comment]
Is this code exclusively used when installing Nextcloud?

**Comment by kesselb** [comment]
@BernieO i think so ;)

https://github.com/nextcloud/server/blob/0ee191bf44a4204dae0dd5ee641ccbf6720e1341/lib/private/DB/ConnectionFactory.php#L188

Usually the connection factory is used to create the db connection. `dbport` is not used there. Lets fix this mess :rofl:

**Comment by MorrisJobke** [comment]
> Is this code exclusively used when installing Nextcloud?

Not really - it's used on every DB connection init call - so on every request.

**Comment by DasSkelett** [comment]
Somewhat related:
It's a real mess to specify an IPv6 address for the db. You can't write it in square brackets like everywhere else in the config.
This results in a very messy look, and possibly buggy behaviour, because the port cannot be unambiguously separated from the address.

Examples:
Fictional DB IP: `[2001:DB8::1:2]`
Fictional DB port: `5432`

This doesn't work, but should (assuming specifying the port in `dbhost` is allowed, which is currently):
```php
'dbhost' => '[2001:DB8::1:2]:5432',
'dbport' => '',
```

This doesn't work, but should:
```php
'dbhost' => '[2001:DB8::1:2]',
'dbport' => '5432',
```

This doesn't work, and maybe should:
```php
'dbhost' => '2001:DB8::1:2',
'dbport' => '5432',
```

This works (in my case), but is very susceptible to errors. It assumes the part after the last `:` is always the port, happens in `splitHostFromPortAndSocket()`: https://github.com/nextcloud/server/blob/0ee191bf44a4204dae0dd5ee641ccbf6720e1341/lib/private/DB/ConnectionFactory.php#L237-L254
Which is fatal if it isn't specified to make use of the default values:
```php
'dbhost' => '2001:DB8::1:2:5432',
'dbport' => '',
```

The DB `ConnectionFactory` code ignores IPv6 totally, and it only works by pure chance in some cases.

From a first look it doesn't seem too hard to fix the code, however a proper fix might break backwards compatibility for the config.php, especially for IPv6 addresses.

If you motivate me a little, I can try to do a PR. But prepare for some review work, it would be my first for Nextcloud.

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/72191419-63f80900-3402-11ea-936f-8ed274bbc1fd.png)

That seems to be okay to me. I think we should remove `dbport` and keep it with `dbhost`.
