### ISSUE TITLE
Vue contacts menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15586]
**Is your feature request related to a problem? Please describe.**

The contacts menu is plain old jQuery.

**Describe the solution you'd like**

I would like to replace that with a Vue component.

As per discussion below the contacts menu should actually get merged into the unified search: https://github.com/nextcloud/server/issues/15586#issuecomment-901268383

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/orgs/nextcloud/projects/31

---

@nextcloud/javascript @nextcloud/vue objections?

**Comment by rullzer** [comment]
Do it :) IF there is an API to hook into it we should wrap and deprecate.
But moving this to something maintainable yes please!

**Comment by juliushaertl** [comment]
@jancborchardt @nimisha-vijay I've been wondering if we could not just merge the contacts menu to the new unified search. Currently you can use both to search for contacts, just that the contacts menu also provides you with the actions immediately. I think having two ways for contacts doesn't make much sense:

![image](https://user-images.githubusercontent.com/3404133/129938601-271d1422-3fac-4f92-bd28-62ea2b6805f6.png)

![image](https://user-images.githubusercontent.com/3404133/129938707-f3a05834-28eb-4a6f-8b20-9d65e2824322.png)

The search currently does not search the system addressbook i think, so that could be something that would need to be extended as well.

**Comment by nimisha-vijay** [comment]
Agreed, especially since it does show up in the unified search also, but without the actions.

**Comment by ChristophWurst** [comment]
> I've been wondering if we could not just merge the contacts menu to the new unified search

We also got this feedback from one of our customers. Makes sense IMO :+1:

**Comment by blizzz** [comment]
> > I've been wondering if we could not just merge the contacts menu to the new unified search
> 
> We also got this feedback from one of our customers. Makes sense IMO +1

Keep in mind that contacts menu allows different actions and we have apps for this (https://apps.nextcloud.com/apps/ldap_contacts_backend, https://apps.nextcloud.com/apps/telephoneprovider – given, the latter seems unmaintained), which the universal menu does not at the moment. This should be considered when replacing the contacts menu.

**Comment by ChristophWurst** [comment]
PR at https://github.com/nextcloud/server/pull/40749
