### ISSUE TITLE
Running on WAMP ?

### ISSUE THREAD

**Issue by beppe9000** [nextcloud/server#15669]
The reasons ownCloud dropped windows are probably outdated.

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by beppe9000** [comment]
Actually this issue is about development (unless you secretly support windows) was posted to investigate if the reasons behind the lack (it was dropped in ownCloud in 2015, before the nextcloud fork) of support for native windows installation are still current (among them the low adoption rate of php 7.x) and to identify compatibility issues with Windows servers and list them.

BTW OwnCloud used to have windows support but it looks like they developed against IIS server: since apache runs on windows too I think there may be some issues that could entirely be avoided.

I believe this could be useful for home servers that lack the resources for virtualization.

**Comment by skjnldsv** [comment]
Well, sorry, your post was not very clear :stuck_out_tongue_closed_eyes: 
We do not support windows and never will. Sorry :/

**Comment by beppe9000** [comment]
> We do not support windows and never will.
I would love to know the actual reasons behind that draconian conclusion ;)

**Comment by skjnldsv** [comment]
@beppe9000 Windows is a mess to support.
All the software we use for nextcloud is linux-based and updated there.
We do not have the time nor the will to do some work to support a barely used platform :)

If you want nextcloud, go with Linux. Nextcloud is supposed to be run in a server, 90% of the cloud server share is run on linux :wink:

**Comment by beppe9000** [comment]
Well, is Windows Subsystem for Linux supported then?

**Comment by kesselb** [comment]
> I think that should be re-evaluated from time to time.... never say never :)

Apart from your point about home severs is there any other point? Is there any benefit for nextcloud by supporting windows?

> What about Windows Subsystem for Linux? Does it lack some commands?

If you use it for production and loose some data don't blame nextcloud. Since Windows Subsystem for Linux (1.x at least) is a modified Ubuntu (or some other distributions) it could work. I used it for development some time ago and was running into weird permission problems. This might be fixed today.

> I posted to investigate if the reasons behind the [lack](https://github.com/owncloud/core/pull/14540)

Do you read the related issue and the blog? 

1) There were some points about changes for the filesystem layer that would be required for stable windows support. I doubt there's any progress on this.
2) Another point is that libsmbclient is not available for windows. If you want the best performance with smb shares this extension is required. 
3) In addition a new testing infrastructure for windows would be required. Take a look at https://drone.nextcloud.com there are many automated tests for nextcloud/server and the apps. All these tests must run on windows as well (like php7.1 / mysql, php7.0 / postgresql, ...). This is not done with one server.

**Comment by beppe9000** [comment]
> Apart from your point about home severs is there any other point? Is there any benefit for nextcloud by supporting windows?

Real (not emulated) cross-platform across the whole spectrum of OSes. Differentiate from ownCloud. Reaching more potential install base from users who do not have the specs to run virtualization. Etc...

> If you use it for production and loose some data don't blame nextcloud. Since Windows Subsystem for Linux (1.x at least) is a modified Ubuntu (or some other distributions) it could work. I used it for development some time ago and was running into weird permission problems. This might be fixed today.

I will try it in the future and write back if I find problems when I 'm done. 

<hr>

> 1. There were some points about changes for the filesystem layer that would be required for stable windows support. I doubt there's any progress on this.

> ![image](https://user-images.githubusercontent.com/6625123/58375440-5bc28a80-7f53-11e9-9baa-91f90940becd.png)

The blog is pretty vague, probably it's NTFS fault somehow. That development effort could be mostly offloaded to the [many libraries](https://libraries.io/search?keywords=filesystem&languages=PHP) that exist today.

![image](https://user-images.githubusercontent.com/6625123/58375432-32096380-7f53-11e9-833f-d4e7d7871c5c.png)

> 2. Another point is that libsmbclient is not available for windows. If you want the best performance with smb shares this extension is required.

This guy made a port: http://allandynes.com/2016/05/samba-client-for-windows-smbclient-exe-v3-6-25/

> 3. In addition a new testing infrastructure for windows would be required. Take a look at https://drone.nextcloud.com there are many automated tests for nextcloud/server and the apps. All these tests must run on windows as well (like php7.1 / mysql, php7.0 / postgresql, ...). This is not done with one server.

I could not open that. Could you authorize me for https://drone.nextcloud.com? I did oauth but gives me an error about organizations. Assuming I bypass the install checks and complete it, how can I run those tests?

4.  PHP Version
> ![image](https://user-images.githubusercontent.com/6625123/58334570-1f523a00-7e40-11e9-8631-7aa7f353f02e.png)

This no longer seems a problem, since PHP 7+ is now required, so most of those needed improvements are likely already there.

5. ownCloud complained about MSSQL

> ![image](https://user-images.githubusercontent.com/6625123/58375521-274fce00-7f55-11e9-8e43-e59fbeffa636.png)

MySQL runs on windows, so not really a problem if that's still true.

![image](https://user-images.githubusercontent.com/6625123/58375541-b5c44f80-7f55-11e9-8589-2345c452d26a.png)

<hr>

Ps. I was thinking that a "Lite" version of nextCloud with file storage only could make sense and be easier to support and build on. 

About that, is there any documentation you could point me to? In particular I'm after some information on what is the minimum set of API requests that the server must implement to enable synchronization with the desktop and mobile apps. 

If you give me some pointers I might try to cook up something like that by myself.

Thanks :)

**Comment by kesselb** [comment]
> I could not open that. Could you authorize me for https://drone.nextcloud.com? I did oauth but gives me an error about organizations. Assuming I bypass the install checks and complete it, how can I run those tests?

Sorry I don't have the permission for that. 

> That development effort could be mostly offloaded to the many libraries that exist today.

https://github.com/KnpLabs/Gaufrette: "This project does not have any stable release yet but we do not want to break BC now."

https://github.com/thephpleague/flysystem/blob/master/tests/LocalAdapterTests.php: Some of these tests are skipped because this is not possible on windows.

These are great libraries and flysystem is already used by nextcloud somewhere but they are only a part of the filesystem topic. 

> Ps. I was thinking that a "Lite" version of nextCloud with file storage only could make sense and be easier to support and build on.

You might join https://github.com/nextcloud/server/issues/15275 than ;)

> Nextcloud Server does not support Microsoft Windows.

The message is part of the [web installer](https://github.com/nextcloud/web-installer/blob/c263c82c3f553c29246609b58716a723b08b3824/setup-nextcloud.php#L84-L86) but not nextcloud/server. There is no "kill if windows statment" in `nextcloud/server` itself. Give it a try ;)

Don't be mad with me, but I'm leaving the discussion ;) I'm not a paid engineer and only contributing from time to time. @skjnldsv already gave you an official statment.

**Comment by beppe9000** [comment]
Thanks for your unpaid time :)
