### ISSUE TITLE
Add ZIP file Support (ZIP/UNZIP)

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#1573]
### Expected behaviour
- Allow to ZIP and UNZIP Files/Directories
- A ZIPed File/Directory should replace these which itself should be listed as old Version.
- ZIP File should opens like a normal directory and allow to move files in and out of it
### Actual behaviour

I get a download dialog

**Comment by MorrisJobke** [comment]
@LukasReschke We had this and removed it because of security reasons, right?

**Comment by Mannshoch** [comment]
security reason? WHAT?

**Comment by LukasReschke** [comment]
> @LukasReschke We had this and removed it because of security reasons, right?

Yes. At the time being there was no sane library that:

1. Did not easily DoS the server (you don't want to have someone open a [ZIP bomb](https://en.wikipedia.org/wiki/Zip_bomb) etc.)
2. Was implemented in a way that it didn't disclose arbitrary files on the server. I'd rather prefer a small ZIP library that doesn't necessarily follow the standard 100% but excludes every potential insecure thing :-)

If someone wants to work on that and has a secure library in mind. Pull requests are always welcome. 😉  – Or an app on apps.nextcloud.com :-)

**Comment by Mannshoch** [comment]
LOL. Bombs got Digital. Thats strange. Even more that this seems to be an old security problem.

**Comment by Happyfeet01** [comment]
Is this still an security problem? I have many zip files on my server.

**Comment by virtualdxs** [comment]
It should be implemented but with a security option. I'm migrating between nextcloud servers and this would be very helpful - I can download a folder as a zipfile but I can't upload it as such.

**Comment by emresaracoglu** [comment]
Is there a new plan in this regard?

**Comment by virtualdxs** [comment]
Another idea, do you see any potential problems in a plain tar archive? There's no compression so no zip bomb vector, but it still makes dealing with moving folders exponentially easier. I think zip would still be better because of size and cross-platform compatibility (my stance is still that it should be implemented, disabled by default, and have a checkbox to turn it on preceded by a security warning), but tar would be better than nothing.

Also, another possibility would be to read the `uncompressedSize`, compare that to the user's remaining space, and start writing, and if it either a. exceeds its `uncompressedSize` by more than a small margin or b. exceeds the user's available space, regardless of any margin, it stops writing, deletes what it's written so far, and throws an error.

**Comment by Yetangitu** [comment]
I got a feature request for an app to allow individual file access from archive files. I feel this feature should really be implemented in core as that already does file access abstraction for apps. I do not see security issues with read-only access so that should be implementable without problems. Given the abundance of archive file formats a generic archive abstraction layer would be more useful than individual zip/tar/7z/whatnot features.

With regard to the danger of 'zip bombs' I'd say that user quota could be used to guard against them? Just don't allow the extracted file to go over the set quota and the temporary 'damage' would be confined to a single user's max allowed file space. Temporary as the extracted files would be deleted on reaching the quota before finishing the extraction - there is no use in keeping those around after all.

**Comment by jirislav** [comment]
2019 here, yet still waiting for this feature, which is very common in most cloud solutions :)

>  **virtualdxs** commented on 12 Feb 2018:
> Also, another possibility would be to read the uncompressedSize, compare that to the user's remaining space, and start writing, and if it either a. exceeds its uncompressedSize by more than a small margin or b. exceeds the user's available space, regardless of any margin, it stops writing, deletes what it's written so far, and throws an error.

What a great idea, this should solve the bomb problem. However the `uncompressedSize` ZIP header [probably is not tamper-proof](https://serverfault.com/questions/854486/is-there-any-way-to-detect-an-incoming-zipbomb/854499#comment1097901_854499), hence the attacker could probably lie about it - this would need a research.

Btw, I've stumbled upon something funny you can do with ZipBombs to prevent bad guys from tampering without your server :grinning: , see [this HackADay article](https://hackaday.com/2017/07/08/dropping-zip-bombs-on-vulnerability-scanners/).

**Comment by virtualdxs** [comment]
@jirislav That's why I included the check for how much actually gets written.

**Comment by Iceberg1988** [comment]
For my purposes it would already be very usefull if I can simply zip a folder to archive old datas. It would be nice, if I can open zip files but for my usecases I don't need this feature very often.

**Comment by maxolasersquad** [comment]
This feature would be very helpful for anyone trying to upload a directory with a large amount of folder. I have directories containing source code with many thousands of files and even though the total size is a dozen MB, the uploads can take hours and sometimes even days. If I could upload everything as a zip and have NC decompress I could save myself many thousands of expensive web requests.

It seems to me there are two very good solutions to zip bombs.
1. Extract file-by-file, checking each time if the file would make the user go over their limit. Give a standard out-of-space error message and terminate the extraction. This is what happens when unzipping a file locally.
2. Check the size of the total extraction. If it is larger than the available space for the user either warn the user and continue as in option 1, or stop the extraction immediately.

**Comment by skjnldsv** [comment]
An app is on the app store for this exact purpose: **closing**  :wink: https://apps.nextcloud.com/apps/extract

**Comment by emresaracoglu** [comment]
@skjnldsv 🎉

**Comment by yoseph1998** [comment]
I'd like to add that the extract app only solves half of the issue. There does not seem to be a solution to zip a file without downloading it.

Right now there are two things you can do
1. Using the Extract app, unzip a file
2. Using the native download folder, zip and download a directory

However it is not possible to:
1. Zip a file/folder without downloading it. (i.e. zipping a file/folder into the current directory)

Why is this useful?
1. One usecase is to zip a folder for archival purposes using the WebUI
2. Zipping a large directory that would overload the php zipping process. Currently if you try to download a very large directory, the zipping would take forever and be capped by system ram. However if a zipping only button was added, this could zip the folder on the backend and tell the user to come back later when the zipping is complete. Basically Queue the zipping process and download later.

**Comment by ShGKme** [comment]
A proposal for unzip - web-only solution.

On a web-client:
1. Download an archive
2. Extract it in a web-browser
3. Show files or download extracted files to the server

This won't work well for a large archives and breaks on web-browser tab close.

But it would be safe for a server and independent from encryption and external storages support.

**Comment by Fantu** [comment]
Hi, from what I see here are reluctant to add it due to possible security issues, can't it be enough to have it but disabled by default?
Unfortunately even if there are possible risks for someone it is an indispensable function, as for example I have a client with dozens of users who use it a lot and it is one of the things for which they block me from updating nextcloud if it introduces regressions :( (although it is not good to keep old versions)

The "extract" app even if abandoned has a fork compatible with nc 29+ (not tested yet), but like other abandoned apps seen in the past it seems to me that there is no management of orphaned apps, or am I wrong?
I have been contributing to Debian for over a decade and I have seen that it has several possibilities to manage orphaned packages (and replace the maintainer) or even replace the abandoned upstream with a possible live fork and make the transition as transparent as possible for users.
I don't have time to follow nextcloud much but it happened to me with several abandoned apps that I had to manually apply patches from forks to keep them working so I wonder if there isn't a management system for orphaned apps.
Another thing it would be useful to automatically report unmaintained and perhaps orphaned apps if they haven't released updates for new versions within a certain number of months and/or haven't uploaded new versions for a long time.
Adding this also to the "new version" control (in the admin overview), in addition to apps not supported in the next update (based on the currently installed version) would give more forewarning.

**Comment by christiansass** [comment]
I understand that this has security implications, but it's no reason to close the issue. This is something that should be addressed as it's pretty default in most OS and cloud platforms that are competing with this. What can we do to reevaluate?

**Comment by kylerobi** [comment]
I cannot believe there's no easy way to unzip in nextcloud. every competitor has this feature standard

**Comment by Fantu** [comment]
I'm replacing extract with [files_archive](https://github.com/rotdrop/nextcloud-app-files-archive), even if there are no recent version in store is still supported.
also added some things like "extract here" in the menu (is the most used thing by my users) and it already had a limitation to try to avoid zip bombs, among other things that extract app doesn't have

**Comment by Happyfeet01** [comment]
I Tried an Solution with Compress
And uncompress![image](https://github.com/user-attachments/assets/605fa79e-6400-4702-937a-632cea33f624) ![image](https://github.com/user-attachments/assets/5fc2e6e9-fa79-4686-a88f-b72c1d3dbd6f)
![image](https://github.com/user-attachments/assets/548193f4-84e0-41a6-933f-01dc0c1cb640)
https://github.com/nextcloud/files_zip/pull/491

**Comment by Fantu** [comment]
I looked also this time ago and if I remember good files_zip refuse to add extract function and to use extract app instead, thing I did. And recently I'm switching to files_archive.

**Comment by Mannshoch** [comment]
Could we have kind of a transparent usage of ZIP or TAR?

Let's say you are in Nextcloud and have a directory, where you could set a ZIP flag. Online you could still browse the directory but have limitation to the usage of the content. e.g. no file open. Then you could remove the ZIP flag and in background it get exported and replace the zip file. (and may the file or the directory is kind of a newer version, so you could restore the zip file if you want.

It would also mean, after an upload Nextcloud analyses the ZIP and create a virtual directory to browse.

On the Opposite, you may want to zip a directory because the content clutter the Nextcloud file index. In this case you could set a no Index setting and the directory get replaced with a TAR file.
