### ISSUE TITLE
2FA challenge after 2FA setup during login is problematic

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15744]
Steps to take
* Admin enforces 2FA
* Admin enables Two-Factor TOTP
* User logs in
* User sets up TOTP
* User is redirected to TOTP challenge

If the user is quick, their TOTP app will show them the very same code as during the setup. TOTP does, however, detect code reuse and therefore will fail.

**Comment by szaimen** [comment]
I guess this isn't as dramatically since they probably need to be pretty fast to be able to reuse the same totp key. Also they can just try againn in the worst case.
So I vote for closing it also because there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
