### ISSUE TITLE
Always show toggle for snap.js to hide appnavigation

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#15831]
Hi, 
it would be most advantageous especially on smaller screens  e.g. notebooks to be able to hide the left side panel showing the different calendars and therefore increasing the viewing area of main information window !!!

Such a toggle switch  should be mandatory for all apps, showing a distinctive left side panel to achieve a common design goal and experience! 

Sample can be found e.g. in the DECK app!

Regards, hitam4450

**Comment by georgehrke** [comment]
> What do you think @nextcloud/designers?

ping @nextcloud/designers :)

**Comment by jancborchardt** [comment]
Seeing from the comments above, we basically agree. Just takes someone to implement it. :)

**Comment by juliushaertl** [comment]
@skjnldsv I guess this is something we can move to the components repo?

**Comment by skjnldsv** [comment]
Yes, we had a talk about this with @ChristophWurst

**Comment by georgehrke** [comment]
@juliushaertl Snap.js is part of the server though: https://github.com/nextcloud/server/blob/fd9ff581e2a92f65def3f5d3209c4328fb65416a/core/src/init.js#L216

**Comment by skjnldsv** [comment]
@georgehrke not if you use the components :)

**Comment by alexanderdd** [comment]
I think the following actions need to be taken:

1. change the server code so that the "toggle sidebar" (=hamburger) icon is always shown, not just on tiny screens (this is what this bug is about IMO)
2. change components code in the same way
3. update the "guideline for developing (core) apps": you  must integrate the toggle sidebar icon into your design
4. calendar needs to update design so the toggle sidebar icon fits in more naturally. (other apps look pretty well for me with the icon)

does it make sense to  open separate issues for each?

PS: I was about to file an issue about this, but then I found it here ;+)

**Comment by skjnldsv** [comment]
> * update the "guideline for developing (core) apps": you  must integrate the toggle sidebar icon into your design

should be done automatically regardless you using the components or in server :)

**Comment by alexanderdd** [comment]
@skjnldsv yes the hamburger icon should just show via components *and* server. But in some apps it is not well-integrated in the design, e.g. in calendar and contacts app the icon hovers over other content, slightly covering it.


(Maybe off-topic?)

[[Gnah can't post picture examples from.mobile]]

**Comment by skjnldsv** [comment]
> in calendar and contacts app the icon hovers over other content, slightly covering it.

Maybe check if there is not already an opened issue on calendar about this? 
If not create one :)

**Comment by nickvergessen** [comment]
Would also be nice for Talk, can we have this?

**Comment by georgehrke** [comment]
@nickvergessen Afaik this issue is mostly blocked by https://github.com/nextcloud/server/issues/16934 at the moment

**Comment by nickvergessen** [comment]
Then we add a property to the Component allowing apps to say yes/no?

**Comment by skjnldsv** [comment]
@nickvergessen I'd rather do it properly once and for all

**Comment by jancborchardt** [comment]
> Then we add a property to the Component allowing apps to say yes/no?

If an app has a navigation, and it’s below a certain width, then it should automatically work. Saying no should not be possible as it doesn’t depend on the app but on the screen size. Right @skjnldsv?

**Comment by nickvergessen** [comment]
The "no" was regarding always show the toggle.

**Comment by ma12-co** [comment]
> I'd rather do it properly once and for all

I think that on top of that we should have a prop to toggle the visibility of the collapse button regardless of the window width.

**Comment by skjnldsv** [comment]
> I think that on top of that we should have a prop to toggle the visibility of the collapse button regardless of the window width.

Nope, the idea is to show it all the time if there is an appnavigation. So No need for a toggle. The toggle is the appnavigation being here or not

**Comment by jancborchardt** [comment]
> The "no" was regarding always show the toggle.

Ah ok – for that we should also agree on something centrally though, not having this decided by individual app developers.

- Right now the toggle is only showing on narrow screens which is nice and unobtrusive. You can not accidentally hide the navigation on desktop and then be confused about why stuff looks differently. Also, the navigation should only have essential stuff in it, so it has a reason for being there.
- Showing the toggle all the time makes it possible to also hide the navigation if it’s not needed but you actually have enough screen space. Not 100% convinced we actually need this, since as said the navigation should usually only contain essentials.

**If we move the code to a standard, we should make sure to keep the current experience for now: Only show the toggle on narrow screens. Then from that as a base, we can see if always showing it is works well and has more advantages than drawbacks.**

**Comment by korelstar** [comment]
I would like to remind of the discussion [here](https://github.com/nextcloud/notes/issues/413#issuecomment-569496547), where a permanent toggle (i.e. shown also on non-mobile) was proposed by @jancborchardt and @ma12-co . That is why we have the issue https://github.com/nextcloud/nextcloud-vue/issues/791
Therefore, it would be nice, if the solution which is developed here, will fix also the above mentioned issue.
