### ISSUE TITLE
decryption not working on files in trashbin

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/server#16045]
Running occ encryption:decrypt to decrypt files of a user results in the files in the trashbin not being decrypted.
Most likely this can be fixed together with #7284.
@nextcloud/encryption

**Comment by chainria** [comment]
Actually, I simply went forward and in lib/private/Encryption/DecryptAll.php line 30 I added:

        $directories[] = '/' . $uid . '/files';
+        $directories[] = '/' . $uid . '/files_trashbin/files';

and it simply worked like a charm. I suspect because the directory structure is very similar, see https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#id6

This unfortunately does NOT fix #7284, which actually would be the more important thing. But maybe this can be of any help to someone? Also, maybe this should be merged into NC as well? I see no harm done at all.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
