### ISSUE TITLE
16.0.1.1 no Masterkey but there is and was

### ISSUE THREAD

**Issue by Jockelchen** [nextcloud/server#16181]
I can't change my users Password since upgrading to nextcloud 16 (16.0.1.1). I can change the Masterkey, but it doesn't get recognised.

occ encryption:status

    enabled: true
    defaultModule: OC_DEFAULT_MODULE

how can i fix this? I was asked do change a users password soon.

**Comment by Jockelchen** [comment]
no help? rare problem?

**Comment by blu-IT** [comment]
I have this problem too! Masterkey is enabled:

```
occ $ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```

NC v. 18.0.3

Another strange behavior is, that I can't change my **groupmemberships** anymore - obviously because **I can't change any details, password,** etc of my user now.
I can configure new groups as admin, but I can't configure anymore that admin is part of the new groups. I had to do so directly in the database.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
