### ISSUE TITLE
Nextcloud offers me Upgrade from 15.0.10 to 16.0.3 with php 7.0 only installed. WHY?

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/server#16316]
#### Expected behaviour: 
No Upgrade offer

#### Actual behaviour:
Upgrade offer to 16.0.3

#### Server configuration:
Debian Stretch 9.9
**PHP 7.0.33-0+deb9u3**
Nextcloud 15.0.10 "Stable Channel"

Hello.

I do every Nextcloud update, but until today i only got 15.x.x updates. Never a 16.x.x upgrade offer.
**I [learnd](https://docs.nextcloud.com/server/16/admin_manual/installation/system_requirements.html) that Nextcloud 16 need at least php > 7.1 but i only have installed php 7.0**

Today, after upgrade from 15.0.9 to 15.0.10, i got **the first time** an upgrade offer to a Nextcloud 16 version. *Very surprising*. Until today i never got a 16.x.x offer.

My question is:
**Can i upgrade to Nextcloud 16 on my Debian Stretch 9.9 System with PHP 7.0.33-0+deb9u3?**

If yes, why did i not get any upgrade offer in the past?

Thanks for information.

![ncphp](https://user-images.githubusercontent.com/47995430/60905544-8f444480-a275-11e9-9883-52682c3cb453.png)

**Comment by Nils160988** [comment]
Just wanted to report the same issue, it occurred directly after the upgrade to 15.10...

**Comment by kesselb** [comment]
> Can i upgrade to Nextcloud 16 on my Debian Stretch 9.9 System with PHP 7.0.33-0+deb9u3?

Thanks for reporting :+1: [PHP 7.1 is required for Nextcloud 16](https://docs.nextcloud.com/server/16/admin_manual/installation/system_requirements.html)

**Comment by kesselb** [comment]
https://github.com/nextcloud/updater_server/pull/229/files looks like they do this on purpose.

**Comment by pm-pm** [comment]
"[Inform Nextcloud 15 users on PHP 7.0 about outdated PHP](https://github.com/nextcloud/updater_server/pull/229/files)"

Who in hell stopped supporting Debian Stretch 9.9 Version?

Until 3 days ago (Release of Debian Buster 10) Debian Stretch was the Stable Version, now it is still old-stable and supported. Unfortunately Debian Stretch 9.9 has only php 7.0 Version.

Of course I will NOT upgrade 3 days after release of new Debian my Server from 9 to 10. I need some time for testing and planning.

I request (wish) is to support Debian Stable version until its end +6 Month (old-stable) to have time to migrate in a smooth way.

Summary:
I know php 7.0 is old, but pushing me around by Nexcloud team to upgrade my server so early is not nice. ;-)

**Comment by kesselb** [comment]
> Who in hell stopped supporting Debian Stretch 9.9 Version?

No one?

> I know php 7.0 is old, but pushing me around by Nexcloud team

PHP 7.0 is [EOL](https://www.php.net/supported-versions.php) for a while. Add https://deb.sury.org to sources.list and install PHP7.3.

**Comment by pm-pm** [comment]
"https://deb.sury.org" is not part of official Debian OS.

If you argue that way, tomorrow you can demand that some strange tool is necessary to keep the application running. This is not the point of a stable operation system.

**Nextcloud is supposed to be safe software, isn't it? Then you shouldn't have to include insecure sources to run it!**

**Comment by kesselb** [comment]
> I am a Debian Developer since year 2000, and I have been packaging PHP for Debian since PHP 5. That means the official packages in Debian and Ubuntu are either my work or they are based on my work. The PHP packages in my Ubuntu PPA and Debian DPA matches the official packages in Debian. Basically I am saying that you can’t get any closer than that.

 from https://deb.sury.org or compile php by yourself or use docker or use snap or ignore the upgrade notification. There are many options ;)

**Comment by kesselb** [comment]
cc @MorrisJobke I understand why you're doing this but i'm not a fan of this fake update either.

**Comment by MorrisJobke** [comment]
> cc @MorrisJobke I understand why you're doing this but i'm not a fan of this fake update either.

Usually there should also be a hint with a link to the page we have created for this as @kesselb noticed in:

> https://github.com/nextcloud/updater_server/pull/229/files looks like they do this on purpose.

We typically do this information only if the last stable release is installed to notify admins about the underlying issue. Otherwise we would only do this once 15 is EoL and thus causing a even worse situation where there is no time to plan an update.

cc @jospoortvliet for more details.

**Comment by rullzer** [comment]
The bug here is that you see the update to NC16 while you can't run it. We will look into that.

Regarding supporting debian. We can't help it if that there was no new Debian release yet. Else you could also argue we'd still have to support php 5.4 since there is some supported Red Hat out there that still has this. We follow the supported php versions from https://www.php.net/supported-versions.php

Note that Nextcloud 15 is still supported (even Nextcloud 14 is still supported). So we are not forcing anybody to upgrade their system right away.

Like I said we have to fix the bug here since you should not see the upgrade to 16. But the dropping of PHP7.0 in NC16 is justified in my opinion :smile:

**Comment by MorrisJobke** [comment]
> Like I said we have to fix the bug here since you should not see the upgrade to 16. But the dropping of PHP7.0 in NC16 is justified in my opinion 😄

Let's rephrase: you should see that there is a blocker for you that does not allow an upgrade to 16 even if there is this version available. We should help admins to guide them through missing dependencies.

**Comment by pm-pm** [comment]
> Regarding supporting debian. We can't help it if that there was no new Debian release yet. Else you could also argue we'd still have to support php 5.4 since there is some supported Red Hat out there that still has this. We follow the supported php versions from https://www.php.net/supported-versions.php

@rullzer 
Here you are wrong. We are not talking about any supported Red Hat or Linux versions, but Linux versions supported by Nextcloud!

And Debian 9 (without tricks) is no longer supported at Nextcloud 16. **That would be ok, if you would announce it out loud. You should have done that when Nextcloud 16 was released.**

At this time (Release Nextcloud 16) there was no official Debian version with php > 7.0!

_If you can only get Nextcloud to run with tricks and foreign and insecure packages, then you can surely get Nextcloud to run on Windows 98 as well. ;-)_

Nextcloud must run on normal and not bent operating systems. Accordingly you should delete Debian 9 (and Debian 8) from the support pages of Nextcloud 16. Or at least describe the tricks you can use to make it work.

BTW: What about Debian 10? I can't find anything about it. :-)

I know that it is not Nextcloud's fault that there is no current php for Debian 9. But it's your decision if you support a stable (main) operating system or not.

> Note that Nextcloud 15 is still supported (even Nextcloud 14 is still supported). So we are not forcing anybody to upgrade their system right away.

Nextcloud 15 is end of life at 12.2019. So the admins has only 5 month time to migrate komplex Server from Debian 9 to Debian 10 (Released July 2019) if they want to keep Nextcloud on their server. There is also a world outside Nextcloud. ;-)


Thanks. :-)
pm-pm

**Comment by MorrisJobke** [comment]
> Nextcloud 15 is end of life at 12.2019. So the admins has only 5 month time to migrate komplex Server from Debian 9 to Debian 10 (Released July 2019) if they want to keep Nextcloud on their server. There is also a world outside Nextcloud. ;-)

Just to shed also some light on the other side of the equation: we decided to upgrade the PHP minimum requirement, because our dependencies also moved forward and stopped to provide security fixes for PHP 7.0 based libraries. We are here in an ongoing balance act of supporting as many as possible operating system with as few as possible manual patches (because those also have the likelihood of introduce other security or normal bugs). Thus we decided to go that route. If you want longer support for Nextcloud 15 there is always the option to pay for the Nextcloud subscription, so that Nextcloud engineers get the time paid that they spend on fixing bugs there. Sorry that this is the solution I'm proposing here, but unfortunately we are also just humans that have a life outside of the open source world.

And it is sure that not need to upgrade any software and writing software without security issues would be the ultimate goal, but nobody has found a reliable way to do so yet ;)

**Comment by hitam4450** [comment]
Same issue here.......

**Comment by gohrner** [comment]
Will there be a way to use the web updater to stay on the Nextcloud 15 branch on Debian Stretch systems, or will I have to update to Nextcloud 15.0.11 and so on using manually downloaded tars?

**Comment by anoymouserver** [comment]
After I did the suggested update from 15.0.10 to 15.0.11, it offers me version 16.0.4 again.  As PHP version I still have 7.0, from the official Debian Stretch sources.

**Comment by cramaboule** [comment]
> After I did the suggested update from 15.0.10 to 15.0.11, it offers me version 16.0.4 again. As PHP version I still have 7.0, from the official Debian Stretch sources.

Same here, but you cannot upgrade to NC16

**Comment by hex-m** [comment]
I usually don't post "me too", but it's more than a month later. I just got the "A new version is available: Nextcloud 16.0.4"-message after upgrading to NC 15.0.12. (on Debian 9)

**Comment by korelstar** [comment]
I think this can be closed since Nextcloud 15 isn't supported anymore (?)

**Comment by Nils160988** [comment]
I don't think this issues should be closed because it is about the general question how to inform admins when a new major version is available, but the currently used php version is not supported anymore. This could easily happen again for another version and might confuse admins again.

As @rullzer said:

> The bug here is that you see the update to NC16 while you can't run it. We will look into that.
> 
If you think that the behavior is intended to inform admins that they use an outdated version of php, then keep it closed. But in my opinion, some improvement is possible.
