### ISSUE TITLE
Download Permission restriction like Hide Download option for internal (user/group) shares

### ISSUE THREAD

**Issue by maliknet** [nextcloud/server#16413]
![hide download](https://user-images.githubusercontent.com/35651642/61263408-ee90e000-a7b2-11e9-8e1b-0c2f59373b5d.png)

Hide Download option is already in Share link options in Nextcloud. But the option isn't available if you share with another user / group. The idea is to create a download permission like a hide download option in share link.

I think this feature very needed in real world case especially for strict permission.

**Comment by violoncelloCH** [comment]
how do you mean this? I don't think this would really make sense, because the user could anyway sync the file / folder via the sync client, what is equivalent to a download...
also you can never really make sure the file(s) aren't downloaded, because hiding a download button can't prevent (a little more experienced) users from downloading it anyway...

**Comment by maliknet** [comment]
the sync via client apps (Windows, Android & IOS) will be restricted by file access control rules. So that's no issue. 
Indeed. But we can prevent a standard (not know how to do that) user to download it.

**Comment by iMoshi** [comment]
Is there a workaround to achieve this? I like the feature how you're able to hide the Download button when sharing as a link, but the button is visible and function-able when sharing with an internal user.

Idea is that I only want to share a .PDF with a local user for preview, and be quick to preview the given document not save it for later. I know you can CTRL+P, but not many users are that savy :) any app that makes it happen or..?

**Comment by szaimen** [comment]
I don't know if hiding the download button makes sense because you will be easily access them internally by e.g. using the desktop client or webdav, etc.
cc @nextcloud/designers does this option make sense?

**Comment by iliugh** [comment]
> I don't know if hiding the download button makes sense because you will be easily access them internally by e.g. using the desktop client or webdav, etc. cc @nextcloud/designers does this option make sense?

We need the feature too.
This feature is very needed in our use case for strict permission.
Would you like to provide a modification prompt?

**Comment by elhananjair** [comment]
> I don't know if hiding the download button makes sense because you will be easily accessing them internally by e.g. using the desktop client or WebDAV, etc. cc @nextcloud/designers Does this option make sense?

Somehow it might help to at least not give someone an idea to download that document. The point is there must be some way to restrict the replication of shared documents in nextcloud.

**Comment by raimund-schluessler** [comment]
I still don't understand what's the point of this feature, honestly. If I understand correctly, you want someone to be able to look at the document and view it, but not download it, right?

But if the document is viewed as a PDF, you can just as well simply save it, since it is transferred to your browser as a PDF anyway, no? Simply hiding the Download button does nothing for the confidentiality of your document, if you are allowed to view it.
@PVince81 Since you implement this feature, maybe you can explain how it is supposed to work?

**Comment by PVince81** [comment]
while one cannot fully prevent downloading, if someone does there could be a watermark (could be a future feature) so that if someone leaks the doc, at least it is possible to know who did

the PDF viewer will need to be adjusted as well accordingly to prevent download

it's technically not possible to fully block downloading, but make it at least more cumbersome for less tech-savvy people

**Comment by raimund-schluessler** [comment]
> while one cannot fully prevent downloading, if someone does there could be a watermark (could be a future feature) so that if someone leaks the doc, at least it is possible to know who did
> 
> the PDF viewer will need to be adjusted as well accordingly to prevent download
> 
> it's technically not possible to fully block downloading, but make it at least more cumbersome for less tech-savvy people

Hm, I see your point and I guess it kind of makes sense.
But it reminds me a bit of the encryption discussion that pops up once in a while: "If you make encryption illegal, only criminals will have privacy."
So: "If you hide the download button, only tech savvy people will be able to download."
Sorry, if this went to far off-topic 🙈😄

**Comment by iMoshi** [comment]
We really don't care who downloads what, what matters is if there was a policy as well as a way of corresponding feature, all for legal purposes.
