### ISSUE TITLE
How can i make banner "This website is using cookies" for Nextcloud?

### ISSUE THREAD

**Issue by psyapathy** [nextcloud/server#16453]
Hello! 
How can i make banner "This website is using cookies" for Nextcloud?

Like on main page https://nextcloud.com/

**Comment by MorrisJobke** [comment]
Write an Nextcloud app for that. It might be that in the forums somebody already developed something like this. See https://help.nextcloud.com/t/gdpr-and-cookie-law/29450 for example.

If you need help, then the forums is the better place, because this is the issue tracker to help developers of the server keep track of issues with the code.

**Comment by MahirReilly** [comment]
This can be done by using many companies, on wordpress like webtoffee, seers. they are the best[.](https://seersco.com/cookie-consent-banner.html
)
