### ISSUE TITLE
Migration path from current owncloud missing or not documented

### ISSUE THREAD

**Issue by callegar** [nextcloud/server#16460]
Migration paths from owncloud appear to be not well documented since the owncloud 10.1 release back in Feb 2019.  This may leave uncertainty in the user.

Web page https://nextcloud.com/migration/ suggests that only owncloud 10.0.x can be migrated, not 10.1.x or 10.2.x. Because owncloud moved to semantic versioning at 10.1.x, one may fear 10.1 or 10.2 to have sufficient differences from 10.0.x to trouble the migration. Page https://nextcloud.com/migration/ also suggests the possibility of using an automated migration script.

With some contraddiction to the above page, the nexcloud manual for the current version 16 suggests that any owncloud version from 10.0.1 can be migrated to nextcloud (using any nextcloud version from 12.0.1 on). Furthermore, there is no mention to the migration script and the manual indicates that one should use the "manual upgrade procedure".

I would like to suggest an upgrade to https://nextcloud.com/migration/ to align it with the current manual (if sensible) and I would also suggest an upgrade to the manual in case an automated migration tool can be adopted.

Another reason for uncertainty is the issue of PHP versions. Owncloud currently does not run on PHP 7.3 (as nextcloud does). Indeed one of the reasons for migration is that owncloud does not run anymore on debian after an upgrade to debian 10 that only provides PHP 7.3. It would be great if the migration documentation could be enhanced by clarifying if it is safe to upgrade an owncloud instance that has so far ran on a pre-7.3 PHP version using the manual upgrade procedure of nextcloud with PHP 7.3.

**Comment by kesselb** [comment]
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
@nickvergessen @blizzz DIdn't one of you looked into this lately?

**Comment by nickvergessen** [comment]
Yeah, it's a bit tricky and needs to be done manually (at least the first migration) because files need to be modified atm:

* Upgrade to ownCloud 10.1 or 10.2
* Download Nextcloud 12 and apply https://github.com/nextcloud/server/pull/16361/files
* Add your version (check `config/config.php`) to https://github.com/nextcloud/server/blob/stable12/version.php#L39
* Do the migration by following the manual upgrade docs: https://docs.nextcloud.com/server/16/admin_manual/maintenance/manual_upgrade.html
* Upgrade Nextcloud until 16 (you can use the upgrade tool there or do it manually while you just mastered it once)
* :tada: Enjoy and welcome on your Nextcloud

**Comment by szaimen** [comment]
I think a way was implemented to migrate from any recent owncloud version to Nextcloud 20 -> closing.
