### ISSUE TITLE
Direct download endpoint: Progressive stream not working

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#16511]
Direct endpoint was introduced with: https://github.com/nextcloud/server/pull/9178

- choose a long audio file 
- create a direct download link via /ocs/v2.php/apps/dav/api/v1/direct
- open it with VLC on Android/Linux
- try to directly jump to nearly end 
-> hear nothing

It seems that one can only seek in the already downloaded area.
I assumed that this will work out of the box with http range header.

Maybe vlc is doing something different here?

@rullzer as you implemented it.

**Comment by rullzer** [comment]
I just tried and as far as I can tell the range request works properly

**Comment by rullzer** [comment]
Can you send me a file you have this happen with?

**Comment by tobiasKaminsky** [comment]
It was a plain mp3 file, ~38min long.

**Comment by rullzer** [comment]
Could you share the file in question with me. As this works as expected on what I throw at it

**Comment by cieska** [comment]
I have very same problem since I have installed NC from about v13.x untill now 17.x I'm lucky if I finish any one video play even on the same LAN WiFi on Android. It's bit hitt or miss bit. Maybe better sometimes on browser, but question. And just happens that the same videos that didn't played just plays. I understand when heavy videos phoen recorder videos more difficul playing than just some nicely compressed video tutorials, but not guaranteed.

**Comment by titilambert** [comment]
I have the same behavior with 17.0.4. I tested with android app and webdav mounted share (with davfs). Playing video is sooo slow if the bitrate of the video is too high. But playing the video on the webbrowser is working perfectly.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
