### ISSUE TITLE
Users have wrong locale/language when creating multiple users consecutively

### ISSUE THREAD

**Issue by konwin** [nextcloud/server#16522]
I have an issue when adding users consecutively, without reloading the users page.
I'm using Nextcloud with the config.php options
`'default_language' => 'de',`
and
`'default_locale' => 'de',`
and when adding users (without a password) the first gets the german welcome email and his account will be in german. But when adding directly a second (or third/fourth/...) user he will get the english welcome email and his account settings will be set to english!
If I reload the users page before creating the next user he will get the german welcome email and his account will be set to german again!

**Comment by J0WI** [comment]
This is not related to Docker. Could you please post your NextCloud version, server variant etc.?
There was a similar issue (#11306) in older versions of NextCloud.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/fced73aa3779c9c38e2bb845c7496fc23c6f0391/settings/src/components/userList.vue#L342-L348

The form is cleared after the user has been created. Default value for language is `en`.

https://github.com/nextcloud/server/blob/fced73aa3779c9c38e2bb845c7496fc23c6f0391/settings/src/components/userList.vue#L184-L189

I guess we need to move this code into a method and call it from resetForm too (because the mount stage is not executed again) or use the updated stage.

cc @skjnldsv @nextcloud/vue

**Comment by skjnldsv** [comment]
Nice catch!

**Comment by skjnldsv** [comment]
Fix https://github.com/nextcloud/server/pull/16727
