### ISSUE TITLE
Comments missing for new user

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#16605]
### Steps to reproduce
1. have file X (or other object, also impacts e.g. Deck cards)
2. have users work with file X, creating history (metadata, provenance) that is important to understanding the current state of X
3. bring in new team member (new user) and give them access to the file
4. get them to look at the history of file

### Expected behaviour
They can view the history of the file to help them understand why it is what is

### Actual behaviour
They cannot view activity that took place before they were added

### Server configuration
All/any

I get this might be a by design bug, but for collaboration purposes its still a bug. In any scenario where you don't want the new user to see the history of a file/card etc., you can always copy it first.

**Comment by nickvergessen** [comment]
Hmm that is indeed correct and our current design decision.
The activities is a stream of things that happen in your part of Nextcloud, but they are not retro-active. The idea also comes with lot's of effort and problems in the pocket. The current way of how activities are stored means that when you get access to a file we would have to copy all the activity there for you. For files this get's worse, because we need to detect all children files and folders and do the same there.

> In any scenario where you don't want the new user to see the history of a file/card etc., you can always copy it first.

The question is always what people expect and if they can think so far themselves to have this idea for the workaround. I guess most people wont and just be confused why it all of a sudden shows all the history, although you waited with the share until you were done with editing the file.

**Comment by nickvergessen** [comment]
Yeah, I totally get that. But comments should be available independent from the activities. I think the deck app just got an update or will get one in the next version where the timeline and comments are split so comments are available although the timeline is not and for comments on files this is already the case.

But feel free to make up a plan how this could improved in a way to cover the current situations with your usecase in mind.

**Comment by putt1ck** [comment]
Yes seen comments are being split out, wasn't sure if that was just a UI change or a new comment store. I think if comments are independent the rest of the item's history is less of an issue, although potentially so in some work flow scenarios - and those can maybe be handled with an add-on like group folders, if the activity issues in there can be fixed.

**Comment by nickvergessen** [comment]
cc @juliushaertl for clarification on Deck

**Comment by juliushaertl** [comment]
> Yes seen comments are being split out, wasn't sure if that was just a UI change or a new comment store. I think if comments are independent the rest of the item's history is less of an issue, although potentially so in some work flow scenarios - and those can maybe be handled with an add-on like group folders, if the activity issues in there can be fixed.

The limitation that activites needed to be enabled was an issue of the initial frontend implementation, so with the separation of comments/activities in deck in the next version, so comments will be available even if the activity entries are not.

**Comment by putt1ck** [comment]
Ok, have changed title and will call it closed.
