### ISSUE TITLE
Allow custom app settings in bottom left of Files app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#16602]
My understanding is that no app may customize the bottom left side settings menu of the Files app.  Please consider allowing apps to customize the bottom left of the Files app, as opposed to the Admin or User Admin Panels on the top right.

Request is related to [this request for Recommendations app](https://github.com/nextcloud/recommendations/issues/72).

**Comment by gary-kim** [comment]
## Just to add some more complete info
**Is your feature request related to a problem? Please describe.**
nextcloud/recommendations#108
The ability to disable Recommendations on a per user basis is needed. The best place to have this toggle would be in the sidebar of the Files app but unfortunately, that cannot be modified from another app. 

**Describe the solution you'd like**
An API that could allow apps to inject settings into the Files app or perhaps a more general purpose API that would allow any app to add their settings to another app's sidebar. Perhaps each app could have a whitelist of other apps that have permission to inject settings?

**Describe alternatives you've considered**
There is an implementation for adding a personal settings page but adding an entire settings page for Recommendations is not good UI wise and most users would think that Recommendations is part of the Files app anyways.

nextcloud/recommendations#100
nextcloud/recommendations#110

We're in a sort of bad place in the release cycle for this since it is not a good time to be adding large features but the ability to disable recommendations is also an important.

**Comment by jancborchardt** [comment]
As always though: Sure it’s good to have an API for these things, but we don’t want every little app register things in there.
We need to make sure that any settings which are added make sense and don’t clutter up the whole interface with minutiae. :)

In this specific case for example, we only want a checkbox saying "Show recommendations", nothing more. :)

**Comment by gary-kim** [comment]
This is a small enough scenario that we could just have the Files app check for the Recommendations app and edit the settings itself but I'd rather find a app agnostic way to do this. In a best case scenario, the server has not extra code for one specific app. 

I think it should be okay to leave what the API is used for to the Apps themselves but what do you think @jancborchardt? Would you rather have some limitations for what settings apps can add?

**Comment by ChristophWurst** [comment]
Even if this shouldn't be used too much, we should go the clean way and offer a generic API for arbitrary settings instead of some hard coded dependency on a specific app. In the long run this is a lot easier to maintain and might potentially be useful for another integration.

**Comment by GlenHuf** [comment]
Can't the "setting" go into the recommendations app itself? just add a tinny toggle button or triangle to minimize or enable the recommendations pane. That's more simple than a check box down in the lower left by user settings.

**Comment by jancborchardt** [comment]
@GlenHuf it’s a setting you likely change only very rarely. So it has no place floating around permanently in the interface. :)
