### ISSUE TITLE
Nextcloud site Scan error Number version

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#16687]
https://scan.nextcloud.com/

on different servers nextcloud when I go to your photo to verify security it gives me A and not A + because it says I have old version 16.0.1.1, but that's not true I installed latest release 16.0.3.  why from this bug?  how to solve?  on 6 server installations only one finds the correct version.  error screen place
![Screenshot_20190807-224108](https://user-images.githubusercontent.com/35575744/62656703-15cb6f00-b965-11e9-8a72-95c3255074d5.png)

**Comment by rullzer** [comment]
Check the scanned at time. It is from early june.
A trigger of the rescan fixes it.

**Comment by ant0nwax** [comment]
I would like to reopen this issue and transform it into a feature request for an improved functionality. i was tricked by this issue myself yesterday, read here for details: https://help.nextcloud.com/t/nextcloud-security-scan-vs-installed-version-mismatch/158855

1. The Interface shows an outdated version, which is not really helpful to anyone, but you are open to explain this
2. the retrigger button is with very few contrast, instead of a button the retrigger shall be written in the beginning when you entered the URL and then it could write the old result and that we shall come back later for the fresh result... but a manually trigger is not useful if i get a result presented that is super ancient
