### ISSUE TITLE
Question: Can server admin get your password or see your files?

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/server#16755]
I have been using sync.com for years and sync.com cannot get see my password or read my files. Only I can access my account and no one else. Is Nextcloud designed the same way weather one self-hosts, pays for hosting or uses a service like hetzner.com or armored.net?

I like Nextcloud's UI, features and how it is available on F-Droid and and has Linux clients!

**Comment by the-sane** [comment]
Regular user here.  I can answer the files question:  By default, files are stored unencrypted and, yes, an administrator can access them.

Server-side encryption is an option, but it is a bit buggy and requires some workarounds being tracked in other issue reports.  That said, I have managed to enable it and it (mostly) works.  By default, it operates in a server-wide key mode where the admin would have access to your keys.  It can be switched into a per-user key mode where your keys are protected by your login passwords to protect them from an admin.  Some community members are working on bringing attention to the bugs to get them fixed.

End-to-end encryption is currently in beta and encrypts your data client-side so the server never has your keys.  This means some features like public file sharing are sacrificed for security.

These encryption methods only encrypt file data, so other data such as calendar and contact info remains stored unencrypted.  You can read more here, but treat it a bit like a press release with the caveats I mentioned above:
https://nextcloud.com/blog/encryption-in-nextcloud/

I don't know for certain about password access because I don't know how they are stored.  I assume they are hashed and protected.  Either way, an admin can reset a user's password and gain access that way.  If server-side encryption is enabled in per-user key mode, admins can no longer reset passwords without a recovery key.  Even with a recovery key, that functionality is currently bugged so they can't reset passwords at all.

I promise, although the encryption aspect of Nextcloud sounds super buggy, the rest of it really isn't.  Hope that helps!

**Comment by yahesh** [comment]
**The server-side encryption is not intended to protect you from malicious admins but to prevent external storage providers from reading your files.**

From a more technical standpoint: In most cases the admin will always be able to get your password and see your files. Each time you log in (either through the web or through an app) you provide your password to the application which can easily be patched to write it to some file. Even with user key encryption enabled instead of master key encryption this is enough to decrypt your files. Even if the admin is not capable of patching the software there is the additional option to activate the recovery key encryption in conjunction with the user key encryption whereby each file is not only encrypted with the user key but also with an admin-only recovery key.

So if you want to protect yourself from spying eyes, it would be easiest to add an additional layer of encryption, e.g. by employing [gocryptfs](https://github.com/rfjakob/gocryptfs).

We haven't looked into the inner workings of the E2E encryption yet so I cannot comment on the security of its implementation.

**Comment by trymeouteh** [comment]
I hope nextcloud implements client side encryption. That will make cloud storage much more safer for users if they self hosting service or nextcloud provider gets hacked. Sync.com does client side encryption and it makes you rest assured your data is safe.

**Comment by the-sane** [comment]
As mentioned, end-to-end encryption is in beta: https://nextcloud.com/endtoend/

And yes, you can configure it to use certificates (ie from Let's Encrypt) and access everything over https.

**Comment by pierreozoux** [comment]
I think @yahesh answered your question. Closing now. Feel free to go to the [help forum](https://help.nextcloud.com/) to ask more around that topic
