### ISSUE TITLE
Global guest name setting

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#17147]
Since more and more apps allow users without an account to set a guest name if they use a public sharing link, we should provide a server api to properly store the name so that all apps (talk, text, onlyoffice, collabora) can use it.

For live updating open sessions with the new name we could use the [local storage onChanged event](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged).

For the backend I would propose to have a similar interface to IUserSession e.b. IGuestSession. It might make sense to have a dedicated unique id in case apps store additional information for the guest user, so a user name change will not lead to issues.

cc @nickvergessen 

@jancborchardt Maybe we should also discuss some more unified way of setting the guest user? Super quick mockup just for the positioning:
![image](https://user-images.githubusercontent.com/3404133/64918780-3b893680-d7a3-11e9-9af4-3e5363c38a4b.png)

**Comment by juliushaertl** [comment]
Maybe it should also handle guest avatars as in https://github.com/nextcloud/spreed/issues/357

**Comment by nickvergessen** [comment]
Yeah, as long as updating the name goes to a central location and triggers an event as well, so apps like talk can listen to it and update the database it sounds good to me.

**Comment by 05nelsonm** [comment]
This might be where my issues lie... When sharing a file via a link, it is automatically popping a "start call" window up where the person can start calls as a guest.

I tried shutting all of this off in the Talk settings under General Settings Start Calls, but it always reverts back to "Everyone" and cannot be saved to "Users & Moderators".

This is also causing issues with file shares when viewing them on mobile devices because the automatically opening start call activity cannot be closed and encompasses the entire screen.

**Comment by jancborchardt** [comment]
@05nelsonm the issue you encounter seems to be unrelated to this? Best open a separate one in the Talk app repository at https://github.com/nextcloud/spreed/issues – thanks!

**Comment by joshtrichards** [comment]
Related: nextcloud-libraries/nextcloud-browser-storage#3
