### ISSUE TITLE
Select file range

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#17313]
I like the "select file range" but the current flow seem contraproductive. Instead of having to go through the menu->"select file range"; user should just hold the SHIFT key to automatically enable the function.

Pic: "select file range" feature.
![Screenshot_1](https://user-images.githubusercontent.com/36133540/65821149-50dd7680-e221-11e9-8520-81737c14c5a0.png)

**Comment by TessyPowder** [comment]
You can mark one file via the checkbox, hold shift and click on another File **Name** (not another checkbox). Then everything between the first file and the other gets selected.

**Comment by pilsnerbeer** [comment]
Yes, I can confirm that works for me. Thanks

**Comment by major-mayer** [comment]
I also think that the current behavior is very weird.
I selected the first and the last item using the checkbox. 
Then i opened the drop down menu "Actions" (that's how i would translate it from German) and clicked on select range.
Interestingly nothing happened. That's at least what i thought first.

But turns out that now when you hover over the checkboxes (!!! not the filenames) it will start selecting a range from the last item.
The first item that i selected keeps being selected.

I think this behavior is really confusing. 

Here is a screenshot from what i mean (i clicked on the third menu item): 
![grafik](https://user-images.githubusercontent.com/17907799/142160998-1b1f2049-b76d-403e-8ff9-5f3b51b2f8f8.png)

**Comment by hede5562** [comment]
It seems none of the variants above are working with NC 28.0.1.

**Comment by daufinsyd** [comment]
Indeed, I can't range select files anymore with nextcloud 28 / 28.0.1

**Comment by joshtrichards** [comment]
@daufinsyd See #42202

**Comment by daufinsyd** [comment]
Thank you @joshtrichards
