### ISSUE TITLE
Question: Why not use Database for mapping files in virtual folders?

### ISSUE THREAD

**Issue by rs-development** [nextcloud/server#17315]
Not a feature request, but I did not find a suitable answer to the question elsewhere, so here I am.

From time to time users move big chunks of data around in the cloud. This is actually moving the data to the filesystem. From a backup perspective, it looks like there is data deleted somewhere and new data created somewhere else.

So I wonder why not use a hash for the filename and a database to map files to virtual cloud folders?

**Comment by dirigit** [comment]
As consequence you might have all files in one folder.

Ever tried to hold 1.000.000 or more files in one folder?

**Comment by herbetom** [comment]
What you are suggesting would mean that pretty much the data would be lost when the DB or Nextcloud fails. Or you would have to sort all files manually. That seems really bad. 

The main advantage from storing the files with the current method is that it is usable without Nextcloud. Also injecting data from the command line wouldn't really be possible.

**Comment by rs-development** [comment]
I see all the pros for no mapping, I just wanted to hear how absurd the idea of mapping is. I would think that bigger storage solutions make use of some kind of mapping tables or similar.

So I am going to change my backup plan with something capable of tracking the files and deduplicating them accordingly.

**Comment by joyov** [comment]
> So I wonder why not use a hash for the filename and a database to map files to virtual cloud folders?

If you're using [S3 as primary storage](https://docs.nextcloud.com/server/17/admin_manual/configuration_files/primary_storage.html) (not as mounted storage) it works like this: the file/directory structure only exists in the database (`fc_file_cache` table) and files in S3 are addressed by id.

```
/
├── urn:oid:10000
├── urn:oid:10001
├── urn:oid:10003
├── urn:oid:10004
├── urn:oid:10005
├── urn:oid:10006
├── urn:oid:10009
├── urn:oid:10013
├── urn:oid:10014
├── urn:oid:10015
...
```

I see several benefits here, e.g. file operations are faster (moving files can be archived by updating the database only, no need to touch the storage), no problems with long file paths or file name encoding and features like adding a file or directory to multiple locations can be implemented more easily (Google Drive supports this (select a file or directory and press Shift+Z) and it is a really useful feature).

The file structure is in the database anyway, why keep this duplicate?

> The main advantage from storing the files with the current method is that it is usable without Nextcloud. Also injecting data from the command line wouldn't really be possible.

There is really no reason for this, you can use the API/WebDAV to access files. (And if a mounted volume is required use something like `rclone mount`.)

> What you are suggesting would mean that pretty much the data would be lost when the DB or Nextcloud fails. Or you would have to sort all files manually. That seems really bad.

First of all: no backups, no mercy. Second: there are many ways a piece of software can destroy your data and you might wouldn't notice immediately: writing empty files, writing corrupted data, etc. As said, it is already done when using a different storage backend and our Nextcloud instance (10.000.000+ files/file versions/thumbnails) never lost anything. Also there is already a lot of data that only exists in the database (Nextcloud Calendar, Contacts, Tasks, basically anything except for the blobs).

> Ever tried to hold 1.000.000 or more files in one folder?

Modern file systems can do that without any problem, but the tools you're using might not work well with it. A common solution is to create a nested structure but still address files by id. This is [what Git does](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects): the object with id `65c8b28ffe4a12eb64918e25ef57331d06cf2ba4` will be stored as `65/c8/65c8b28ffe4a12eb64918e25ef57331d06cf2ba4` (since Git object ids are hex this will decrease files per directory by 256^2 so even with 1.000.000 files it would only be about 15 per directory).

**Comment by szaimen** [comment]
If you are looking for such functionality, you could either try the S3 external storage feature or use Seafile which uses this technique for storing its files. But it won't get implemented in Nextcloud for normal storage.
