### ISSUE TITLE
 WebDAV interface seems to be broken

### ISSUE THREAD

**Issue by yward** [nextcloud/server#17423]
After updating to the latest version of nextcloud my overview screen has the following error:

> Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken

I haven't changed any server configuration nor have I installed any new apps or made any changes to the system.

Edit: it's worth noting that my desktop client is working fine and visiting remote.php/webdav displays no errors just the regular message 

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.

**Comment by kesselb** [comment]
Please edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md). Triage is much harder without. 

>  latest version of nextcloud 

Which one? 17.0.0, 16.0.5 or 15.0.11?

**Comment by worksmarter** [comment]
I too am getting the same response as the above poster. I am running Nextcloud v16.0.4. I know I am not using the issue template, but I want to add a comment here of my experiences. I am running CWP Control Panel. The set up is pretty hard for lots needs changed, but I had everything working 100% and made no changes to my Nextcloud files or any files/settings in CWP. It just started showing the, "Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken." message with no provocation. I contacted CWP as I believe they were the only ones that kept pushing updates that I think broke WebDAV. They acted stupid and said they had done nothing, even though they pushed dozens of updates during the time this error started showing up. I found the problem because there was a Nextcloud update, but I am not updating until WebDAV is straightened out. I am also wonder if the OP is running CWP Control Panel?

Can you assist me in finding the developer tools that look like what you have posted so I can check my response code? In my tools everything is a 200, but that is just to load the page; I can't find the diagnostic option you have pictured in either browser - could you assist?

**Comment by yward** [comment]
> 
> 
> Please edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md). Triage is much harder without.
> 
> > latest version of nextcloud
> 
> Which one? 17.0.0, 16.0.5 or 15.0.11?
> 
> ![image](https://user-images.githubusercontent.com/3902676/66271228-d5507a80-e85b-11e9-99f1-7eddebfef16b.png)
> 
> You can use the development tools (chrome or firefox) to debug this error. The warning is displayed if the response to the propfind request is not 201 or 401. What is the response in your case?


@kesselb 
I've very sorry for the late reply I have been trying to debug from my end ever since.

The error happens with all recent versions, when I originally posted the issue I had version 16.0.5 then I have updated to 17.0.0 and now to 17.0.1 RC1 and the issue still persists.

As for the console error my respond code is 302.

Any feedback would be much appreciated, thank you.

**Comment by yward** [comment]
@kesselb any update on this?

**Comment by kesselb** [comment]
> HTTP/2.0 302 Found

Is the wrong status code. You need to figure out why ;)

**Comment by kiplingw** [comment]
Experiencing the same problem with 20.0.5: `Your web server is not yet properly set up to allow file synchronisation, because the WebDAV interface seems to be broken.`

**Comment by unalignedcoder** [comment]
On Nextcloud 23.0.3. 
I get this error only if I switch to PHP 8.0. 
On PHP 7.4 I pass all checks.
Both PHP instances have the same modules installed and same settings.

**Comment by elyograg** [comment]
I am also having this problem. Version 25.0.0 RC2.  Didn't have this error yesterday.  I think that I was running RC1 yesterday.  I've got PHP 8.1.2 . Running under Apache 2.4 with haproxy sitting in front of that providing TLS.  The haproxy is installed from source, Apache and PHP are installed as Ubuntu packages.  Nextcloud was incrementally upgraded from previous releases.  I believe I started with a binary install archive, as there is no .git directory in the webroot.

This error seems to be preventing the nextcloud android app from auto-uploading new pictures.  The app says "SSL initialization error" but I am betting that's a red herring, especially since the android app worked perfectly yesterday and there have been no TLS changes recently.

Also getting warnings about the .well-known paths not working.  I've tried everything I can find on how to fix that, nothing works.  I know that those warnings have been there since at least version 24, not sure about earlier versions.

**Comment by elyograg** [comment]
> I am also having this problem. Version 25.0.0 RC2.

Figured out how to get things working.  Earlier today I was looking at my work team's effort to disable problematic HTTP methods. specifically PATCH and TRACE.  I placed config in haproxy to only permit GET POST OPTION HEAD methods.  Nexcloud uses PUT, and that was being denied.  Added PUT to the allowed list, and now the android app works.

I still have the "Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken." error when I go to Administration in the UI.

**Comment by elyograg** [comment]
> I placed config in haproxy to only permit GET POST OPTION HEAD methods.

One more followup.  PROPFIND was also being denied.  Added that and now the error in the UI is gone.  Still have the .well-known path warnings, but since they are warnings, I can worry about those another day.
