### ISSUE TITLE
OCS API 'Direct Download' needs fileId in the body, How do I know the fileId of my file?

### ISSUE THREAD

**Issue by cuihaikuo** [nextcloud/server#17574]
![image](https://user-images.githubusercontent.com/20336322/66984783-f2a00700-f0ed-11e9-8e14-0f964c3eddb5.png)

**Comment by My1** [comment]
searching for example:

/apps/fulltextsearch/v1/remote?request=
~~~
{"providers":"all","search":"YOUR SERACH STRING","page":1,"options":{"files_local":"","files_external":"","files_extension":""},"size":20}
~~~ 
(the stuff in the box needs urlencode)
helps me. but I dont get the download API itself working so that's its own issue

**Comment by szaimen** [comment]
You can get the fileid by either clicking on the file and looking at the link:
![image](https://user-images.githubusercontent.com/42591237/120195230-cd0e3580-c21e-11eb-873e-9bde021c8ac2.png)

or looking at the direct link:
https://sub.domain.com/f/3822409
![image](https://user-images.githubusercontent.com/42591237/120195118-aea83a00-c21e-11eb-8564-0223034349ab.png)
