### ISSUE TITLE
Problem loading page, reloading in 5 seconds

### ISSUE THREAD

**Issue by MSP78** [nextcloud/server#1759]
After LogIn this message "Problem loading page, reloading in 5 seconds" is displayed.
This Message is showing sporadically by file und folder navigation.
By clicking on the "shared with me" link on the left side, the message is allwas displayed.

PHP
Version: 7.0.6
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513MB

The nexcloud.log shows no entry!

Can you help me?

**Comment by MariusBluem** [comment]
Could you please fill out the whole issue template you find here:

This would help us to assist you better - or to fix bugs 😅 ... https://github.com/nextcloud/server/blob/master/issue_template.md

**Comment by Ouack23** [comment]
The issue template link that you gave leads to a 404. You can find it here : https://github.com/nextcloud/server/blob/c1b2d90ed88a03bcd5ef6cf5eb510d5286196403/.github/issue_template.md

**Steps to reproduce**
Access public shared folder link

**Expected behaviour**
Access to files in that folder

**Actual behaviour**
Page refresh every 5 secs, with the following message at the top of the page : 
`Problème de chargement de la page, actualisation dans 5 secondes`
In english : `Problem during page loading, refreshing in 5 seconds`

In the source code, in `<body>` : 
`<div id="nojavascript"><div>Cette application requiert JavaScript pour fonctionner correctement. Veuillez <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">activer JavaScript</a> et recharger la page.</div></div> `

Javascript is obviously enabled on both our computers. Same issue with Linux and Windows, so that's a server issue on his side.

# Server configuration :

**Operating system : ** unknown

**Web server : ** Apache

**Database :** mysqli

**PHP version :** 5.6, I guess

**Nextcloud version :** 10.0.1 Fresh install, migration from owncloud latest stable.

**Where did you install Nextcloud from :** migration script from the internet

**List of activated apps :** calendar, contacts, tasks, encryption, ...

**The content of config/config.php :**

**Are you using external storage :** Nope

**Are you using encryption :** yes

**Are you using an external user-backend :** yes, webdav

# Client configuration

**Browser :** FF 49.0.1

**Operating system:** Windows 10 / Archlinux

**Web server error log** _To be published_

**Nextcloud log** _To be published_

**Browser log** _To be published_

**Comment by jgillich** [comment]
@MariusBluem How are you supposed to debug this? Nothing in the console, nothing in the nextcloud log, nothing in the nginx log. But my Nexcloud is stuck in a reload loop with this error. Whoever implemented this "feature" forgot to tell the user WHAT DAMN PROBLEM OCCURED. Sorry for being mad, I just installed Nextcloud after dropping OC two years ago for crap like this...

**Comment by MariusBluem** [comment]
> The issue template link that you gave leads to a 404. 

The Issue Template is now back on its old place, so my link is correct again 😅 

I'm sorry to hear about your experiences with Nextcloud ... Nothing in the logs is - there I agree with you - "nothing" 😜 Maybe you can you help out? @MorrisJobke 🤔

**Comment by MorrisJobke** [comment]
@nickvergessen @ChristophWurst Haven't we added something against this 1 month ago or so?

**Comment by nickvergessen** [comment]
Will have a look, but looks like the ownpad interferes here somehow

**Comment by MorrisJobke** [comment]
Is this still a problem?

**Comment by MorrisJobke** [comment]
Please reopen if this is still a problem with a recent version (i.e. 11.0.1)

**Comment by bseclier** [comment]
Hello, we currently are in 13.0.4.0 and the problem is still here as mentioned in https://github.com/nextcloud/server/issues/5274
