### ISSUE TITLE
Downgrade app

### ISSUE THREAD

**Issue by hoerup** [nextcloud/server#17615]
Once in a while a app update is broken, and since there is no way to downgrade to the last working version, the only option is to wait until the broken app gets fixet. In some cases this wait is not acceptable by the users, so we need a way to downgrade / revert an update.

Latest example is PassMan that in 2.3.3 uses NC17 API calls, so it breaks on NC16

**Comment by rullzer** [comment]
There currently is no way to do this. As upgrades might do database or format changes so you'd have to write both ways. I also doubt this is likely to happen any time soon.

**Comment by hoerup** [comment]
So just let me get this right:
It's not possible to downgrade
I can't uninstall and install a  working version since installer allways takes latest (broken) version
So the only way to fix this right now is to restore my nextcloud from latest backup

**Comment by kesselb** [comment]
> It's not possible to downgrade
I can't uninstall and install a working version since installer allways takes latest (broken) version

Yes. App maintainer released this version to the app store.

> So the only way to fix this right now is to restore my nextcloud from latest backup

Try to download a older version of the app: https://github.com/nextcloud/passman/releases/tag/2.3.2. Move apps/passman to somewhere else and upload the code from the zip.

For some reason the app maintainer released a version of his app for Nextcloud 16 with an api that is only available from Nextcloud 17: https://github.com/nextcloud/passman/commit/aefd7bd3b089583dfb10914f46bb8141d3742c76

**Comment by hoerup** [comment]
Manual downgrade with download zip and copy the files,

**Comment by rullzer** [comment]
The app maintainer can of course always release a new version (2.3.4) that fixes the issue.

**Comment by Zocker1999NET** [comment]
@rullzer The problem is that even if a fix exists, the app developers might have good reasons to not release a bug fix now but to wait e.g. until other bug fixes can be published as well. But I as user and admin of a Nextcloud instance just wait until this one bug fix will release because it makes the app mostly unusable to me. The example I am referring to is even an official Nextcloud app, namely Deck. Because of other bugs, which might impact the experience of other users more, at time of writing, the release of [version 1.2.2](https://github.com/nextcloud/deck/milestone/42) will be delayed. The upcoming version the patch nextcloud/deck#2584 for the issue nextcloud/deck#2580 which I am desperately waiting to be fixed because it prevents me to using Deck like I want to. And I think I'm not alone because only in the last 3 days multiple issues were opened.

Because of that I think admin-friendly rollbacks should be implemented, because sometimes app developers will not develop or push fixes fast enough for all users. It do not need to be a good supported feature which works for all apps in all cases or environments, but implementing such a feature is a further step for Nextcloud to be usable in production environments without delaying app updates for weeks/months just because of "If I update now and then I will find a bug, I cannot revert update anymore, so I will not update until I can be sure there are no bugs."

Maybe they are only possible if no database changes were done or by just ignoring the new database but warn the user before the rollback that a rollback might break more than the new version did.
