### ISSUE TITLE
where is minAppsDesktop ?

### ISSUE THREAD

**Issue by Nosirus** [nextcloud/server#17624]
I'm looking to change the number of apps displayed, but I can't find nextcloud/core/js/js.js

**Comment by kesselb** [comment]
Did you use the search? 

![image](https://user-images.githubusercontent.com/3902676/67229211-20ad8000-f43b-11e9-926d-56da63df42cc.png)

`minAppsDesktop` is already the variables exact name. But you probably need to compile (or transpile) that javascript again.

Here is the related feature request: https://github.com/nextcloud/server/issues/13079

I'm closing this issue because it's neither a bug or a feature request. Please use https://help.nextcloud.com for questions.

**Comment by ws-h-ono** [comment]
That value is gone and searching isn't going to help on NC17.

The issue linked hasn't solved the problem too and if you don't want to waste time chasing the issue around, open up `core/js/dist/main.js` and change all the `o>8`, `o=8` and `o<8` to whatever the number you desire.

**Comment by windware-ono** [comment]
If you don't mind seeing every item being listed, you can add these lines to your `Custom CSS` in the `Theming` (Needs Theming app enabled).

```
#appmenu li.hidden {
   display: flex !important;
}

#more-apps {
   display: none !important;
}
```
