### ISSUE TITLE
Multiple drives for data storage

### ISSUE THREAD

**Issue by cloo** [nextcloud/server#17671]
Storage is at the heart of Nextcloud functionality, but extending or upgrading storage is very, very inconvenient and officially even not supported. I strongly believe it should be supported in a user-friendly way, by allowing to mount more drives with full-featured functionality (without limitations of 'external storage' app).

**Comment by kesselb** [comment]
Mind to edit your post and use the [template for feature requests](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md)?

I have a vague idea of what you're talking about but providing a flexible to add more disks to your storage sounds more like a feature for your operating system. Something like lvm probably.

**Comment by szaimen** [comment]
> (without limitations of 'external storage' app).

@cloo What are those limitations you are talking about?

**Comment by cloo** [comment]
The specific limitations of NC (and not OS) are:
1. There can be only one location (path) for NC data, which means I can not simply expand storage by adding devices.
2. Moving NC data folder seems to be officially unsupported either, which probably means, that if I need to switch to a larger storage, I must retain data folder path, which can be messy if there is other data in that partition.

I agree that my issue was not formulated properly as it came in a frustrated moment, when I understood that expanding storage is so complicated.  I'd like NC to be more easily scalable, future-proof solution I could safely stick with. 
I will try to formulate it better after this discussion.

**Comment by Gatak** [comment]
On Linux you simply Mount another device in the data path.

I have these different mount points
```
/www
/www/mydomain.com/htdocs/nextcloud/data
/www/mydomain.com/htdocs/nextcloud/data/__groupfolders/1
/www/mydomain.com/htdocs/nextcloud/data/appdata_oc12k1234p0f/preview
```

**Comment by tsalwierz** [comment]
>     1. There can be only one location (path) for NC data, which means I can not simply expand storage by adding devices.

Well, as mentioned above you can setup different mount points in the data directory. Still not ideal though. External storage also works but also not ideal.

If your goal is to have the primary storage medium be expandable, some popular options:

1) Ceph/Gluster (ceph s3 is quite nice as primary, cephfs is fine as well)
2) MergerFS/SeaWeedFS/etc - downside, they use fuse.

There are other options. I've personally found ceph with s3 to be the sweet spot but YMMV.

**Comment by Gatak** [comment]
If it's a local server it would be by far easiest to use LVM, ZFS or Btrfs. You can simply add dissks and expand your storage without adding new mount points

**Comment by tsalwierz** [comment]
> If it's a local server it would be by far easiest to use LVM, ZFS or Btrfs. You can simply add dissks and expand your storage without adding new mount points

No, it's not. Let's ignore the memory requirements of ZFS for a minute and the fact BTRFS is not really production ready at this time. Let's just look at this from a capacity standpoint.

Most computer cases can store x hard drives (usually under 6). You can use external hard drives, but that's about the most they can do.

The vibe I get from the OP is that the OP needs a larger storage solution then what his computer can hold - because I'm sure the OP is well aware of what RAID is.

That leaves very few options other then mounting directories which is not really feasible when dealing with many users.

So, if the plan is to have an infinitely expanding file system you can either use cephfs, s3 or a remote file system like mergerfs. However, that uses fuse which isn't ideal for a large nextcloud deployment.

I'd say cephfs isn't really good for nextcloud either, but I've seen it load directories with millions of files with minimal delay. YMMV.

**Comment by Gatak** [comment]
What's wrong with Btrfs? It is very production stable. It is also default file system on OpenSuse. There are no known major issues with RAID1 or spanned disks. 

What you are referring to is the s.k. "write hole", something most RAID systems are affected by in some way unless you have battery backup on your RAID/DISK controller. It is a risk in RAID5/6 if you have a power outage and ALSO a hardware failure. Some data _may_ then have an incomplete or erroneous checksum. Since Btrfs can use a different RAID mode for metadata and data, you should always run RAID1 on metadata. 

Please do not post old information as today's facts.

LVM is also very reliable. You can use that with EXT4 filesystem. LVM is used by default on many Linux distributions. It has not specific memory requirements and is very fast. Ceph and other distributed networked file systems are a completely different type of setup, also much much slower.

**Comment by tsalwierz** [comment]
I've run benchmarks on BTRFS. It is not production ready.

I haven't mentioned LVM at all, but thank you for the reply anyway.

Ceph isn't slow, either. Do you have personal experience with ceph??

**Comment by Gatak** [comment]
I think this is getting rather OT. Perhaps @cloo can specify in a little more detail around what he means?

Only comment I can make is if performance and available features are sufficient for the job demanded.

**Comment by TessyPowder** [comment]
I dont think splitting data should be implemented on such a high level like the Webserver. There are many options to use multiple drives for nextcloud data. I personally use [UnRAID](https://www.unraid.net/) (its NOT free , but if thats a problem you can just use ZFS)

**Comment by Cinerar** [comment]
I believe S3 external storage should be polished (now it works, but sometimes some errors and bugs pops up here and there) , then you have excelent options to use mutliple drives for storage, smth like minio or ceph metnioned before.
