### ISSUE TITLE
Change files_versions

### ISSUE THREAD

**Issue by Irillit** [nextcloud/server#17714]
I’d like to offer some changes in versioning. I can also try to implement it, but before that, I need your word.

**Is your feature request related to a problem? Please describe.**
For instance the user with 200GB quota has 5GB file. Every month nextcloud stores a full-size version of this file. Nextloud removal policy might begin to clean them only after 20 months or sooner. And in the meantime the versions use up a significant amount of space while the user needs only some of those versions.

**Describe the solution you'd like**
1. Add specific threshold for storing versions: auto delete after 3 month and after having 100 versions or so.
2. Add a checkbox to disable version deletion for specific file. It was also requested in the issue #11263.
3. Allow user to delete each version manually.
4. A way to show the user how much space versions take or/and a notification when the size of versions exceeds a certain % of total quota.

**Comment by tomdereub** [comment]
An idea : instead of deleting versions when a certain % of total quota is reached, maybe take the used size as reference.
I mean : start deleting old versions when "all versions take so much space as original files" OR "x% of the quota is reached". In the case you describe with 5GB file for a 200GB quota, file versions won't take more than 5 GB, so total used space would be limited at 10 GB.

**Comment by szaimen** [comment]
Hi Irillit,
Feel free to create a PR for discussion.
Thank you!
