### ISSUE TITLE
Allow sorting the shared with my list by user

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#18032]
When browsing the "Shared with my" file list it would be useful to sort the files by the user who shared the file with me. Right now the view is only useful when the user knows the file name.

@nextcloud/designers

**Comment by jancborchardt** [comment]
Interesting thought. To even think a bit more about how to make this list more useful and less like a bland table, it could be also grouped by the sharer kind of like notifications are grouped by repository in Github notifications. Sorted by person with the most recent activity up top.

And that would be the default/only view – could also be used for the shared _by_ you, just the other way around, where it would say "To Frank" etc.

### From Camila
- 📄 Desktop design.md

### From Frank
- 📄 Release planning.md
- 📁 Requirements
- ➕ 3 more …

### From Nina
- 📁 Include

**Comment by ArnY** [comment]
Hello @jancborchardt

I'm the one who suggested this to @juliushaertl and The initial point of my suggestion was to allow a user to find a file without remembering the original filename with only the sharer. So the idea of sorting the "shared with/by me" pages by the sharer/"sharee" is indeed a good idea as long as the user can still search a username to filter the view to only files shared by this user. 

It also shouldn't prevent the possibility of searching, in those views, a file by name. In the search result the view would stay the same, allowing the user to search with partial filename and differentiating them using the sharer name. 

The problem is that this view isnt't compact and might not satisfy everybody.

The possibility of searching by shared is also something that would come handy on every pages, by the way.

**Comment by jancborchardt** [comment]
@ArnY maybe this related issue is also what you are looking for? :) "Use search to filter for share owner" #18033

**Comment by ArnY** [comment]
oops, indeed, gotta love Nextcloud's support, always taking their customer's suggestions seriously! :)

**Comment by juliushaertl** [comment]
This can be achieved starting with Nextcloud 30 with the files filter for users.
