### ISSUE TITLE
Birthday calendar - date keeps changing

### ISSUE THREAD

**Issue by JSDA123** [nextcloud/server#18046]
After updating the birthday field the recurring appointment is automatically created in Contact birthdays as expected, but the date is one or more days earlier than the birthday submitted.  The date continues to change over time with cron runs, always getting earlier and earlier.

This seems to occur anytime a birthday is entered or changed in a CalDAV client, but I have not been able to reproduce when using the Contacts page on the Nextcloud website to add/modify birthdays.

Nextcloud 15.0.13 with PHP 7.0.33-0ubuntu0.16.04.7

**Comment by j-ed** [comment]
Unfortunately this is the Nextcloud bug tracker and **not the official Nextcloud help forum**, which you can find [**here**](https://help.nextcloud.com/).

**Comment by georgehrke** [comment]
As @j-ed already said, this seems more to be a support request, not a bug report especially considering all the missing information, since you didn't use the issue-template.

Since you say, that it doesn't happen with the Contacts app, it seems to me that this is more a bug in the software you use on your cell phone / desktop to manage your contacts.

Unless you are able to give us concrete reproduction steps, there is no way for us to look into this issue. In the meantime it seems best to ask for help in the forum.
