### ISSUE TITLE
One Time Secret to send Passwords

### ISSUE THREAD

**Issue by guettli** [nextcloud/server#18060]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need to send a passwort to someone, and I have only his email address.

**Describe the solution you'd like**

I would like to have a service like: https://onetimesecret.com/

This way it is possible to send a password to someone. I know this is not 100% secure,
but much better than sending the password in the email.

**Describe alternatives you've considered**

I could use the service of above link, but I would prefer a self-hosting service. Since I already run nextcloud, it would be great, nextcloud could do this.

**Comment by j-ed** [comment]
What about the [Two-Factor Admin Support](https://apps.nextcloud.com/apps/twofactor_admin) app. Would thois be the function you're looking for?

**Comment by guettli** [comment]
Maybe this could be used for it, but my use case is more general. I want to send someone a secret.

**Comment by nursoda** [comment]
There's also [Two-Factor via E-Mail](https://github.com/rullzer/twofactor_email). I guess that's what you're looking for?
However be warned: I was NOT able to get it working reliably.

**Comment by guettli** [comment]
I was looking for a service like: https://onetimesecret.com/

**Comment by kesselb** [comment]
Seems to be something for https://help.nextcloud.com/c/feature/app-ideas?

**Comment by github-tomster** [comment]
@guettli
+1
@rest
if one knows what the request is about, one would welcome this handy feature in his nextcloud.
is there any solution or alternative available?

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
