### ISSUE TITLE
Support Preloading

### ISSUE THREAD

**Issue by Booteille** [nextcloud/server#18145]
Hi.

With the recent support of PHP 7.4 I was wondering if there is any plan to support OPCache Preloading for NextCloud.

**Comment by Booteille** [comment]
Hi. Is there any plan to move on this subject? Did you already test performances improvements this would imply?

**Comment by PriceChild** [comment]
https://help.nextcloud.com/t/nextcloud-faster-than-ever-introducing-files-high-performance-back-end/108633/2 shows this has been tested by the project.

I can't locate the preload script used.

**Comment by mweinelt** [comment]
> [help.nextcloud.com/t/nextcloud-faster-than-ever-introducing-files-high-performance-back-end/108633/2](https://help.nextcloud.com/t/nextcloud-faster-than-ever-introducing-files-high-performance-back-end/108633/2) shows this has been tested by the project.

Pretty sure that graphic was taken from https://developers.ibexa.co/blog/benchmarks-php-7.4-8.0-jit-opcache-preloading-symfony. No specific mention for preload support was made for nextcloud AFAICT.

**Comment by PriceChild** [comment]
@mweinelt bah you're right! That graphic is based on testing another app unrelated to nextcloud...

The page isn't loading for me anymore, but that's annoying.

**Comment by mweinelt** [comment]
Well, symfony isnt entirely unrelated, its what Nextcloud uses afaict. So it would be likely that Nextcloud can profit from that.

**Comment by lazerl0rd** [comment]
For what it helps, working backwards from the core/App.php script I was able to preload `/path/to/nextcloud/lib/private/AppFramework/App.php` successfully.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by PriceChild** [comment]
Would still be nice to have. Hoping this comment stops it going stale. @nextcloud/server-triage are you a thing?

**Comment by PriceChild** [comment]
Lets try stopping it going stale again.

**Comment by ndj888** [comment]
it cool

**Comment by skjnldsv** [comment]
Considering the small amount of support it received, it seems this is not in our priorities.
Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by ndj888** [comment]
> Considering the small amount of support it received, it seems this is not in our priorities.
> 
> Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

I tried to implement it, and it looked cool. I have five years experience in PHP. I need your help with the testing, and of course I will complete the self-testing.

**Comment by MichaIng** [comment]
@ndj888 
Did you make any progress on this? I just ran into the same question and opened a topic at the forum: https://help.nextcloud.com/t/php7-4-opcache-preloading/127356
Would be great if you could contribute there with the results you have. We could make this a HowTo and probably a documentation page first, for users to test and play with, report possible issues and whether there is some benefit noticeable. When we found a safe and beneficial list of scripts to preload, verified by a sufficient amount of users, we have a better change of getting it natively integrated into Nextcloud. Since `opcache.preload` still needs to be defined at PHP server level, it still requires manual steps, but Nextcloud could ship a `preload.php` and the documentation could provide how to actually have it preloaded.

**Comment by pulsejet** [comment]
For future reference of anyone who comes across this: I tried and could get all the Nextcloud and 3rdparty classes to preload, but it led to a very negligible (if any) improvement in performance. As such it doesn't seem worth the extra maintenance overhead. Tested on PHP 8, Nextcloud 25.

**Comment by MichaIng** [comment]
Could you share the `preload.php` (or how you named it) you used?

**Comment by pulsejet** [comment]
Nothing special, really. Basically just preload everything you can. I was hoping for at least (say) a ~10% improvement before thinking about optimizing this further; but saw basically nothing.

You do need a couple of small patches here and there besides this; lost track of that since it isn't a git repo. Basically check for `PHP_PRELOAD` and not run some init steps, such as session. You can do `print_r(opcache_get_status()['preload_statistics']);` to see what got preloaded (and restart the server every time there's a change).

```php
<?php
/*
define('PHP_PRELOAD', 1);
$_SERVER['SCRIPT_FILENAME'] = __DIR__ . '/index.php';
$_SERVER['SCRIPT_NAME'] = '/index.php';
require_once __DIR__ . '/lib/base.php';

function scanFolder($folder) {
    $files = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($folder),
        RecursiveIteratorIterator::LEAVES_ONLY
    );

    // names to skip
    $skip = [
        'update.php',
        'index.php',
        'cron.php',
        'console.php',
        'command.php',
        'routes.php',
        'authpicker.php',
        'grant.php',
        '/templates',
    ];

    // require all
    foreach ($files as $file) {
        // check skipping
        foreach ($skip as $s) {
            if (strpos($file, $s) !== false) {
                continue 2;
            }
        }

        if (substr($file, -4) === '.php') {
            require_once $file;
        }
    }
}

scanFolder(__DIR__ . '/lib');
scanFolder(__DIR__ . '/core');
```

**Comment by MichaIng** [comment]
How much MiB takes the OPcache then? Should be huge compared to when only preloading what is really used. However, if otherwise RAM is sufficiently large and this does not limit the concurrent FPM workers, I guess preloading more than necessary doesn't harm performance. I'll try to run some benchmarks when I find time.

**Comment by pulsejet** [comment]
~20MB when everything is preloaded IIRC. The preload stats do indicate most classes are loaded.

**Comment by MichaIng** [comment]
Ah, that isn't so much. I see about 30 MiB on a small setup without preloading, after most components were used/cached.

**Comment by pulsejet** [comment]
Makes sense, right? I don't expect preloading to have more memory consumption unless there's a lot of dead code.

**Comment by MichaIng** [comment]
I checked the size of all Nextcloud PHP files once which was much larger. And opcode usually is larger than the PHP scripts, at least what I saw in file cache once. But preloading classes/functions/interfaces is also not the same as caching the whole script's opcode.

The relative performance gain also depends on database and in case disk/RAM I/O performance and related bottlenecks. So when doing benchmarks, best cached database and assets (CSS, JavaScript, images, fonts, ...) needs to be assured as well, or doing them without loading the frontend at all, to test backend-only performance. But then again it doesn't say much about real world browser access performance.
