### ISSUE TITLE
Flow frontend polishing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#18191]
- ~The icons in the action boxes can be a bit closer to the text below. Should have same distance from the text as the button below https://github.com/nextcloud/server/pull/17997#issuecomment-555530183~
- when a second row of operations is shown, don't hide its elements (the + is visible after all anyway)
- ~The link to the apps is not created correctly when running in a subfolder (the subfolder is cut away), but that was already the case before. All changed things shiny :)~

**Comment by juliushaertl** [comment]
@jancborchardt Do you remember what the following was exactly about?

**Comment by jancborchardt** [comment]
> @jancborchardt Do you remember what the following was exactly about?
> 
> > when a second row of operations is shown, don't hide its elements (the + is visible after all anyway)

This is feedback from @blizzz actually :) https://github.com/nextcloud/server/pull/17997#pullrequestreview-322909502

**Comment by blizzz** [comment]
This was about the operation chooser on the top. We would show a second row, but only the first item of it. But things have changed since. It looks OK for admins (with the extra tile that points you to the app store), but for users when there are four ops (and four fit into a row), only three are shown:

![Screenshot_20200108_170314](https://user-images.githubusercontent.com/2184312/71994288-c56c7c00-3238-11ea-91b9-2212c8688b90.png)

![Screenshot_20200108_170344](https://user-images.githubusercontent.com/2184312/71994345-db7a3c80-3238-11ea-8439-88d43999e091.png)

Minor issue. In smaller windows, it's accurate when only 3 are show. 

Oh, back to Admin settings with a small window. 

Collapsed:

![Screenshot_20200108_170618](https://user-images.githubusercontent.com/2184312/71994531-3318a800-3239-11ea-9813-8142762a405b.png)

Expanded:

![Screenshot_20200108_170637](https://user-images.githubusercontent.com/2184312/71994563-3dd33d00-3239-11ea-95d9-7055a3832ae4.png)

All in all it's fiddly, but overall OK, and not really in the way or anything. Let's close.
