### ISSUE TITLE
Files: Checkbox position and row height slightly different on mobile/desktop

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#18336]
Check this out, happens at the breakpoint where the files app collapses the columns (688px):
![Checkbox jumping](https://user-images.githubusercontent.com/925062/70539652-978f0b80-1b96-11ea-9a27-53ffdce0a67f.gif)

- Checkbox jumps a bit
- Row height jumps a bit
- Table header and filename are not left-aligned on same position
- The summary "1 file" should left-align with the filename too

@GretaD since you worked on the filelist with mobile, you probably know the ins and outs best at the moment? cc @nextcloud/designers if anyone has an idea.

**Comment by go2sh** [comment]
I just head a quick look. The line-height is not consisten through all table cells. Some use 50px and some 1.6em (Size and Modified). If they are hidden the line-height shrinks into 50 px causing the visual glitch. There is also another visual glitch due to the recomendations section. The max-height is 189 px minus the padding 28 px is 161px. But in wide-screen mode the there are only 3 elements stacked on top of each other due to the flex-box and each height is 52.5 summing up to 157.5px.

**Comment by jancborchardt** [comment]
@go2sh good stuff, nice research! Do you want to submit a pull request to fix the issue, if you find out how to? :)

**Comment by go2sh** [comment]
Yeah, can try to fix it. I'am by no means a design pro/(s)css, more a js/ts person.^^ Do you have a preference or design guideline regarding the line-height? em or px?

**Comment by skjnldsv** [comment]
minimum element is 44px :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
