### ISSUE TITLE
Delete notifications on mentions in comments

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/server#18371]
### Steps to reproduce
1. User A mentions User B in a file comment. User B doesn't have access to that file.

### Expected behaviour
Nothing happens.

### Actual behaviour
User B receives a 'delete' notification.

**Comment by nickvergessen** [comment]
The notification is generated never the less, as removing it on render of said user is much easier. Otherwise we would need to create the full accesslist to check if a user has a valid path to the file. This is currently not working too well with external storages and group folders. So unless the delete notification is a really problematic thing, lets keep it like this?
