### ISSUE TITLE
Version on download.nextcloud.com is 9.0.51

### ISSUE THREAD

**Issue by nblock** [nextcloud/server#184]
The download link at https://download.nextcloud.com/server/releases/nextcloud-9.0.51.zip points to Nextcloud 9.0.51. There is no release on GitHub with such a version. What are the changes between 9.0.50 and 9.0.51?

**Comment by blackcrack** [comment]
@Developers

would nice if exist an tar.gz version :) 
makeable via Webplatform and php :)

backdate=$(date +"%Y.%m.%d-%H-%M")
tar -cvzf NextCloud-$vers-$backdate.tar.gz ./Nextcloudmaster

would be nice if this included in the Homepage,
fr able to make daily backups/ daily's
and grabbing an stable version :)
and if you make it in adminspace as simple buttons it's more easy
to use and add in cron daily snapshoots ;)

est regards
Blacky

**Comment by MorrisJobke** [comment]
It contains following PRs:

#88 Add strict config check to config.js
#108
#109
#110 Soften the cookie check if no cookies are sent
#114 fix padding of 3-dot button on mobile
#118 Fix strengthify issues
#134
#161
#170
#172
#174 Upstream Sync
#177 v9.0.51
#178 

I hope this answers your question.

The PRs without description are ownCloud -> Nextcloud renamings. Sorry for having this released this that short term, but this was needed due to the mentioned change :( We are now fully Nextcloud branded :)

**Comment by MorrisJobke** [comment]
> would nice if exist an tar.gz version :)

Why do you need this? There is a tar.bz2 which can be extracted by tar too. (`tar -xjf file.tar.bz2`)

**Comment by blackcrack** [comment]
ah okey... :+1:

**Comment by nblock** [comment]
> link ?
@blackcrack Click on 'more details'. There you can find the the .tar.bz2 link

**Comment by blackcrack** [comment]
ahhhh.... thank you very much..
humm.. "more details" inject not at all

maybe would be great a button : 

More Details
and Files

(es reimt sich, iss lso gut *vbg* )

could be this change, because only
"More Details" overview some one likely to be under it also other packformats ..

(also für dumme und vollpfosten *vbg*)
hihi :)

best regards
Blacky
