### ISSUE TITLE
Editing my user via user managment not possible

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18530]
### Steps to reproduce
1. Login as Admin
2. Go to user management
3. Try to change my quota

### Expected behaviour

I can change the quota.

### Actual behaviour

I can not change to quota for admin. It's possible to change the quota for other users.

![Peek 2019-12-22 12-42](https://user-images.githubusercontent.com/3902676/71321362-85776c00-24b8-11ea-90ef-3dd55c7106f3.gif)

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
@GretaD

**Comment by nursoda** [comment]
@rullzer / @juliushaertl : #19882 is neither present in 19.0 beta 2 nor in 19.0 beta 4 – still the admin user cannot modify himself.

**Comment by nursoda** [comment]
META: BUG REPORTING INFO REQUEST according my previous, now "marked as spam" post:

I was trying to be helpful. While I understand that it is quicker to mark a post that to answer, it does _not_ help me understand _what would help you_. My (limited) view as user is: I reported a bug and care to observe whether it's fix works for me. I read to expect it in 18.0.4, so nothing to do for me here. But I expected that it would already be present in 19b2 (or 19b4 at least). It was not, so I tried to report that in order to avoid regression and last minute includes in 19 release preparation.

I did report a week ago (here) but got no reaction. Instead 19b4 was released, so I ADDED info in "my" bug #18964 (marked "duplicate". I thought maybe it isn't read there (since it's marked duplicate, and I only _edited_), so I added it to the "main" bug here. Since it's now marked Spam, does that mean the edit was enough to be noticed?

So please help me/other users reporting bugs to understand: SHOULD I have (not) spoken up (again)? WHERE should I have reported it? In the Commit? Only here?
