### ISSUE TITLE
config option `'upgrade.disable-web' => true,` has no effect

### ISSUE THREAD

**Issue by zeigerpuppy** [nextcloud/server#18585]
### Steps to reproduce
1. enable option `'upgrade.disable-web' => true,` in config.php
2. attempt web update

### Expected behaviour
web updater should be disabled

### Actual behaviour
web updater opens and offers update

### Server configuration

**Operating system:**
Debian 9

**Web server:**
apache

**Database:**
mariadb

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**Comment by kesselb** [comment]
![updater-9-upgrade-page](https://user-images.githubusercontent.com/3902676/71534639-705b6c80-2900-11ea-9efa-081945781e84.png)

`upgrade.disable-web` will disable above page (`occ upgrade` from cli) via web. Web based updater will still work and is available for admins. If the above page is disabled everything works as expected.

**Comment by gary-kim** [comment]
@zeigerpuppy Do you think we should introduce a setting like `upgrade.disable-web-updater` for your use case?

**Comment by zeigerpuppy** [comment]
An option for disabling the web updater would be really useful.
We've found the cli updater to be more reliable for our purposes and it'd be a useful safety feature for less experienced admin on our platform.

**Comment by szaimen** [comment]
Ping

**Comment by Thaodan** [comment]
> An option for disabling the web updater would be really useful.
> We've found the cli updater to be more reliable for our purposes and it'd be a useful safety feature to prevent less experienced admins on our platform from mistakedly trying the web updater.

Also some distribute the server via external means and could disable this way of update/upgrade entirely.

**Comment by kesselb** [comment]
Closing because `'upgrade.disable-web' => true,` works as expected (disable `occ upgrade` from web). @gary-kim created a [feature request at nextcloud/updater](https://github.com/nextcloud/updater/issues/281) to disable the web based updater. 

Updater: Download a nextcloud update and move the files in place.
Upgrade: Populate the database changes to nextcloud and run maintenance / after update jobs.

If you need to disable the web based updater **now** I would suggest to block access to `/updater/index.php` until one implemented the linked feature request.
