### ISSUE TITLE
Renaming a file opens the sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#18613]
### Steps to reproduce 
1. Rename a file or folder
2. Press enter to submit the renaming

### Expected behaviour
File is renamed and that’s that.

### Actual behaviour
File is renamed but also the sidebar is opened for some reason. That’s unnecessary and especially annoying when on a small screen and you want to rename some more files and you have to close the sidebar again and again.

### Server configuration
Latest server beta

**Comment by gary-kim** [comment]
This can be fixed here.
https://github.com/nextcloud/server/blob/9e7f52d225c00873300d5966c68c896caa09cde3/apps/files/js/filelist.js#L2662-L2665
`self._updateDetailsView(fileInfo.name, false);` opens the sidebar so removing that line will make it so that files no longer opens the sidebar on rename.

**Comment by gary-kim** [comment]
Took a second to look at this again. Looks like its slightly more complicated.
@skjnldsv #15719 removed the show argument for `_updateDetailsView`. Just want to check with you that that wasn't intentional?
The fix should be adding the following back into the `_updateDetailsView` function.
```javascript
			// show defaults to true
			show = _.isUndefined(show) || !!show
			if (!show && OCA.Files.Sidebar.file === '') {
				return
			}
```
https://github.com/nextcloud/server/blob/9e7f52d225c00873300d5966c68c896caa09cde3/apps/files/js/filelist.js#L633

**Comment by skjnldsv** [comment]
I guess not @gary-kim !
I don't recall this, so it's most likely a mistake on my side!
