### ISSUE TITLE
File sorting should allow option to not list favorites first.

### ISSUE THREAD

**Issue by thorsten19** [nextcloud/server#18700]
**Steps to reproduce**
1. In the files application sort a folder or file list containing a file or folder marked as favorite.
2. Files are always sorted with the item marked as favorite first, then showing other files/forders as per the sort criteria.

**Actual Behaviour**
Sorted file lists always show favorite folders/files first. 
I did not know this and first thought the sorting function (by name, date and size) would have a bug. I then found that this was added as feature but seems not configurable.
https://github.com/nextcloud/server/issues/1802

**Expected Behaviour**
While the current sorting showing favorite files/folders first might be useful in many situations, the file function should have a feature to enable/disable this sorting behaviour and allow a regular sorting (aka disregard in the sorting if a file is marked as favorite)
Maybe this feature can be combined with the request to add new "Sort by Filters" listed here? https://github.com/nextcloud/server/issues/18426

Thanks!

**Configuration**

Nextcloud version:
17.0.2

**Comment by kesselb** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
> in many situations the file function should have a feature to enable/disable this sorting behaviour and allow a regular sorting

Could you give some specific examples or describe why favorites are not important in specific cases?

**Comment by thorsten19** [comment]
Thanks @jancborchardt. 
Example: You want to do a sort by the file size or age of the file as you search for the biggest/oldest/newest file in a directory.
Imagine now you have not one but several files/folders marked as favorites. 

If the webview does not allow to change the sorting behaviour, the only way two options are to either
- to remove the favorite tag for the file(s)/folder(s), then the list can be fully sorted in the Webview
- to sync all files to a another machine (for example using the Nextcloud sync agent) and sort in the target machine.
Both options are not user friendly. An option to allow "ignore favorites when sorting" would be pragmatic.

**Comment by siccovansas** [comment]
Another example. I favorite my best images. While most of the time you indeed would like to see your favorite images first in the folder, sometimes you would like to see all image chronologically. This is currently not possible.

**Comment by skjnldsv** [comment]
cc @jancborchardt

**Comment by thorsten19** [comment]
@skjnldsv  I see you marked this with "needs info" label last month: What information is required?

**Comment by skjnldsv** [comment]
> What information is required?

@jancborchardt's input

**Comment by siccovansas** [comment]
Small bump @jancborchardt to avoid this issue being closed (I'm not sure if such a bump comment to avoid closing is acceptable, my apologies if it isn't)

**Comment by Simon-Spettmann** [comment]
If someone is looking for a **quick workaround to disable this for the web interface:**
**Remove or comment out the following code** in ./apps/files/js/fileslist.js -> setSort: function(...)

[`if (isFavorite(fileInfo1) && !isFavorite(fileInfo2)) { return -1; } else if (!isFavorite(fileInfo1) && isFavorite(fileInfo2)) { return 1; }`](https://github.com/nextcloud/server/blob/874eff9aaaeb10961fcbdd93cc37833154f7fca2/apps/files/js/filelist.js#L2012)

**Comment by emes81** [comment]
> > in many situations the file function should have a feature to enable/disable this sorting behaviour and allow a regular sorting
> 
> Could you give some specific examples or describe why favorites are not important in specific cases?

I think it's notable that no similar interface of which I'm aware (Dropbox, GDrive, OneDrive) does this, nor does any file manager I use (Windows File Explorer, Nautilus, various Android). 

Both in the mobile app and the web UI, Nextcloud already has favourites in the sidebar, in a way analogous to quick access, starred etc. in other services/apps. So not only is pinning favourited folders/files to the top of a list superfluous; it also reduces other functionality (ability to sort all folders incl. favourited ones by name/date/size etc).

So the two ways of accessing favourites pinned to the top of a file/folder list are either superfluous (as the user reaches the folder via the sidebar favourites list anyway) or cumbersome (user has already had to navigate through nested folders to reach the favourite).

I stopped using favourites in NC because it made it _harder_ for me to find things (as i was looking for the "media" folder in its alphabetical location, not at the top, because that's where it is in Nautilus, File Explorer, etc.). Favourites _are_ important: making them quickly accessible should not mean that they also have reduced functionality.
