### ISSUE TITLE
Open apps in a new tab by default

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/server#18737]
I think it would make sense to open new tabs when opening apps. 
Sorry if this is already been discussed but I think it would be very beneficial.
Among our competitors we are the only ones that effectively don't have multitasking by default. By that I mean that when the user clicks an app icon, we completely shut down whatever he was doing with the current app and open the new app. 

One could say that yes, we shut it down but we don't lose data, but in fact, we're loosing important things like:
* the location in the files folder structure that the user is working in;
* the current opened talk conversation;
* current email that the user is reading;
* And so forth...

all this slows you down and ultimately makes you less productive, and this is not what we want :) 

Aside from our competitors, no multitasking enabled platform (desktop, mobile, web) that I can think of does that.The default behavior in all those platforms is that the current app goes somehow in the background and the new one opens on top of it, and the most convenient way to do that in a browser is opening a new tab.

What do you think @nextcloud/designers?

**Comment by stefan-niedermann** [comment]
I don't like the proposed behavior - for *my* workflow, it would slow down my productivity, because it would have to close the previous app each time.

I think it should stay under users control (one can use `ctrl` + click or use a scroll-wheel-click if one wants to open an app in a new tab).

Even the w3c sees `target="blank"` as an often misused, unwanted behavior.

**Comment by ma12-co** [comment]
> for my workflow, it would slow down my productivity, because it would have to close the previous app each time.

I'm confused there because this you're basically saying here that you only switch app only if you're finished with the work in the current app.That's not multitasking, that's one task at a time.

I know that there's ctrl-click, and I find myself ctrl-clicking all the time until I have opened the set of apps that I use the most. The problem with this is that not everybody knows about these shortcuts and the default/easy-behavior should be the most convenient.

**Comment by jancborchardt** [comment]
> One could say that yes, we shut it down but we don't lose data, but in fact, we're loosing important things like:
> 
>     * the location in the files folder structure that the user is working in;
>     * the current opened talk conversation;
>     * current email that the user is reading;
>     * And so forth...
> 
> 
> all this slows you down and ultimately makes you less productive, and this is not what we want :)

**This is a separate problem from opening apps in new tabs, and it should be handled and fixed separately. :)**

We should absolutely remember the last states of apps. Because this fixes the issue you describe also when you close the tab or browser window, not only on navigation within Nextcloud.

Also I’m quite wary about having that open-in-new-tab behavior as default (except for _external_ links, like in Talk), as it will lead to having the same apps open multiple times after clicking around a bit and that’s annoying as well. 

cc @karlitschek as this came up during our review of Office 365 and them opening everything in new tabs looked quite disjointed and incoherent.

**Comment by ma12-co** [comment]
> This is a separate problem from opening apps in new tabs, and it should be handled and fixed separately. :)

The new tab approach is a proposed solution to that problem. It's not only about remembering the state of things, it's also about speed when it comes to switching: switching tabs is immediate while switching app within the same tab takes quite a while. 
Moreover, implementing the remember-state feature across all the apps and reducing the app switching times are quite an effort compared to just using multiple browser tabs for multitasking.

>  as it will lead to having the same apps open multiple times after clicking around a bit and that’s annoying as well.

This is a legit worry, but our big competitors have already been doing this for quite some time now and their users have_gotten/are_getting familiar with the tabs workflow, thus getting more mindful about opening the same app multiple times

**Comment by karlitschek** [comment]
I really think the current behavior is fine. It switches to a different app in the same tab by default. IF someone is a power user and wants a new tab then there is a shortcut/right click for it. But forcing everyone to have 100 tabs open is confusing.

**Comment by ma12-co** [comment]
Right, so the consensus is pretty clear, I'll close this and file another issue for remembering the state.

Just 1 more little remark so that my opinion is fully expressed :)
The argument you've all brought up against this is the risk of duplicate tabs, which is real given the fact that at the moment we have sort of a tabbed navigation on the header (even now I open a lot of duplicate tabs as I find myself ctrl-clicking a lot to avoid losing current app-states).
So in my opinion this would be easily solvable by grouping all the apps into one menu (like gapps / office365 / iCloud do). That way it would be naturally easier to reach the already opened tab as opposed to creating a new instance of the same app.

**Comment by jancborchardt** [comment]
> So in my opinion this would be easily solvable by grouping all the apps into one menu (like gapps / office365 / iCloud do). That way it would be naturally easier to reach the already opened tab as opposed to creating a new instance of the same app.

We had this before ;)
![](https://civihosting.com/wp-content/uploads/manual/nextcloud.vs.owncloud/ownCloud.apps.png)

The reason we moved away from it is because people didn’t know there’s other things than Files. Google, Microsoft and Apple can do lots of marketing to make that clear, we need to make it more obvious directly in the app. :)
