### ISSUE TITLE
cnat disable 2nd factor auth for user

### ISSUE THREAD

**Issue by jookk** [nextcloud/server#18828]
One user used twofactor_nextcloud_notification.
I disabled it (security thinking) and now user cant login because twofactor_nextcloud_notification is enabled for account. I tried to disable twofactor_nextcloud_notification via cli: sudo -u www-data php7.4 occ twofactor:disable userid twofactor_nextcloud_notification , but It cant be disabled for user, because: "In ProviderManager.php line 54:

  The provider 'twofactor_nextcloud_notification' does not exist'

twofactorauth:disable [--output [OUTPUT]] [--] <uid> <provider_id>
_

So, I must now install / enable that totp provider and then manually disable it by user..
Not possible to disable totp app for user account.

**Comment by kesselb** [comment]
Please use the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) to report bugs. It's way harder to reproduce a issue without those information. 

https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/private/Authentication/TwoFactorAuth/ProviderManager.php#L87-L95

To make disable 2fa for disabled / uninstalled providers work we need to tweak the code a bit. Instead of `IProvider` / `IUser` passing `$providerId` / `$userId` should be enough to delete the row from the registry. But the events needs an update too and that's probably a bc break.

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Either you disable the provider while the app is enabled or you have to use the `twofactor:cleanup <providerId>` command.
