### ISSUE TITLE
Allow nextcloud autodiscovery though https://[server]/.well-known/nextcloud

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#19086]
**Is your feature request related to a problem? Please describe.**
It can be confusing for some users to enter the correct URL during the login process on the nextcloud clients. It would be great if instead of having to type *https://nextcloud.mycompany.com* or *https://mycompany.com/nextcloud* I could simply enter *mycompany.com*. This would be less confusing for the user, and less error prone.
This could also help to keep a consistent internet identity. For example, if I give you my email *name@mycompany.com*, you could share some file with me by using it in the nextcloud share interface. 

**Describe the solution you'd like**
If I enter *mycompany.com* as domain name during the login process on the nextcloud clients, the nextcloud client could try the following URLs:
- https://mycompany.com
- https://mycompany.com/.well-known/nextcloud
- http://mycompany.com
- http://mycompany.com/.well-known/nextcloud

If one of the well-known URLs works, the nextcloud client would have to follow the redirection and take note of the new domain name.

**Describe alternatives you've considered**
We could also use *.well-known/ocm* for Open Cloud Mesh.
We could also use a SRV DNS record.

**Comment by immerda** [comment]
This would be massively great for us, since we have centralized accounts, which are email addresses, whose domain does not correspond to our nextcloud's domain. Our users are regularly confused about all of that...

**Comment by skjnldsv** [comment]
cc @rullzer @MorrisJobke @nickvergessen :)

**Comment by szaimen** [comment]
> https://nextcloud.mycompany.com 

logging in with nextcloud.mycompany.com 

Should already work, no?

**Comment by artonge** [comment]
Oh, fogot this one. Guess I could have shared it in yesterday's meeting :)

The idea is not to limit the URL discovery to the protocol, but to allow more complex setups. Like when you connect to you mail account on a desktop client, you can simply enter domain.com even if the mail server is on mail.domain.com

**Comment by szaimen** [comment]
> Guess I could have shared it in yesterday's meeting :)

Yes, would have been possible :)

> The idea is not to limit the URL discovery to the protocol, but to allow more complex setups. Like when you connect to you mail account on a desktop client, you can simply enter domain.com even if the mail server is on mail.domain.com

I've understood that but I guess it would be needed to get implemented by the ios/android/desktop clients and not by the server itself, no?
Because I see no way that the nextcloud server does this if it is e.g. installed in a subdirectory or subdomain because you might interfer with any other webservice that is running on the main domain, no?

**Comment by artonge** [comment]
The server would have to implement it too I think, at least for federated sharing. But a good start would be to ease the login process on the client side.

**Comment by szaimen** [comment]
cc @nextcloud/desktop @nextcloud/android @nextcloud/ios

**Comment by KJarek** [comment]
`/.well-known/` is specific to a website/webserver (nextcloud.example.com). If the goal is to discover the URL from the domain name (example.com -> https://nextcloud.example.com/ or -> https://something.example.com/nextcloud/), a domain-level (so DNS-based) discovery would be more appropriate. Otherwise, one would need to publish the nextcloud metadata to an unrelated web server running in the domain apex, which goes bit against running nextcloud on a separate host in the first place. The end result might be users pointing to the right server themselves (user@nextcloud.example.com instead of user@example.com), which only slightly improves the situation (no need to specify the path on the host), but doesn't solve it completely.

The DNS-based discovery doesn't need to rely on SRV records. URI (RFC 7553) records might be a more suitable option, but even putting the metadata to a web server with a well-known name (similar to `autoconfig.example.com` used by Thunderbird) would be an improvement over forcing the apex web server (and would allow easy fallback to https://example.com/.well-known/ in those cases when such configuration is more convenient).

**Comment by grwg-gif** [comment]
Hi, I wanted to follow up and ask if there have been any updates on this topic. This remains an important need for us, and implementing it would represent a significant improvement.
