### ISSUE TITLE
Add option to config/config.php for 'datadirectory.cli'

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#19181]
On my shared host I do not have the same access as PHP has so the directory structure is a bit different. 

Please add the option 'datadirectory.cli'  to set up an alternate data directory If I run a command with occ

**Comment by kesselb** [comment]
You can do this already.

1) Create a new file in `config/` folder: `datadirectory.config.php`
2) Use something like below
```
<?php

if (\OC::$CLI) {
	$CONFIG['datadirectory'] = '/path/cli';
} else {
	$CONFIG['datadirectory'] = '/path/web';
}
```

3) Be careful: Such a setup is probably unsupported hence not tested. Nextcloud should save path information relatively to datadirectory.

**Comment by Mannshoch** [comment]
That is working very well. Thanks.
I'don't know if that is a common setup, but It's the second hoster with such a setup I have.
I'm not sure If I force creating this problem because I changed the datadirectory outside the nextcloud directory.

**Comment by drewjosh** [comment]
I solved it directly in config.php according to t[his thread in nextcloud help forum](https://help.nextcloud.com/t/your-data-directory-is-invalid/45978/7?u=drewjosh):

`‘datadirectory’ => (php_sapi_name() != ‘cli’) ? ‘/var/www/vhosts/[my hosting account]/httpdocs/[url to data folder]’ : ‘/httpdocs/[url to data folder]’,`

**Comment by drewjosh** [comment]
@kesselb Thanks so much, this solved the problem!!! (also after app updates or in my case inserting a backup for passwords)

**Comment by Micha-Btz** [comment]
@kesselb
This is a common setup on all plesk driven web hoster.
The full path for the website is:
/var/www/vhosts/webxxx.ssd-space.de/cloud/data <- this  is the path in the config.php.
And if you login in the path is chrooted to /var/www/vhosts/webxxx.ssd-space.de
so the path on the server is /cloud/data.

The solution you have posted above works, but have some negative side effects.
1. the cron.php is called and get confused so cron jobs stop.
2. the cli updater is not usable, because the logfile /var/www/vhosts/webxxx.ssd-space.de/cloud/data/nextloud.log is not available
3. the updater can't be run, because of the additional file.

Please rethink adding a cli data path :-)

Micha

**Comment by Mannshoch** [comment]
meanwhile, I use another solution. I ssh into my account and created a symbolic link from one directory to another. I t work that way since a half year now without any problems.

**Comment by drewjosh** [comment]
> @kesselb
> This is a common setup on all plesk driven web hoster.
> The full path for the website is:
> /var/www/vhosts/webxxx.ssd-space.de/cloud/data <- this is the path in the config.php.
> And if you login in the path is chrooted to /var/www/vhosts/webxxx.ssd-space.de
> so the path on the server is /cloud/data.
> 
> The solution you have posted above works, but have some negative side effects.
> 
> 1. the cron.php is called and get confused so cron jobs stop.
> 2. the cli updater is not usable, because the logfile /var/www/vhosts/webxxx.ssd-space.de/cloud/data/nextloud.log is not available
> 3. the updater can't be run, because of the additional file.
> 
> Please rethink adding a cli data path :-)
> 
> Micha

@Micha-Btz I used the setup as mentioned from you. According to the error message on the settings page of nextcloud some background jobs haven't been done since 2 months. So I deleted the file again. For background jobs I use Webcron. When I run the Webcron I receive success, but in the settings page I still get the error message. Is nextcloud maybe "blocking" something now?

Cheers
