### ISSUE TITLE
Could Nextcloud use the credentials from the login page for LDAP?

### ISSUE THREAD

**Issue by tcpluess** [nextcloud/server#19305]
**Is your feature request related to a problem? Please describe.**
To log in to Nextcloud via LDAP, an `user DN` needs to be provided. Therefore, one can use one of the existing users as `DN` for Nextcloud LDAP queries (not so good practice) or we have to create a specific user for that (better solution). However, if we could use the credentials of the user who is currently trying to login, we don't need to configure a `user DN` in Nextcloud, we don't have to add a specific user to LDAP and Nextcloud doesn't need to store credentials for the `user DN`.

**Describe the solution you'd like**
Would it be possible to use some kind of format strings in the `user DN` field?
For example, if I write `%username` as `user DN`, the user name which is entered on the login page is used as the `user DN`. Another example would be that one could enter `%username@domain.com` and the token `%username` would be replaced with the username entered on the login page. Of course the password from the login page would then also be used for that. Below screenshot maybe clarifies a bit what I mean.

![Screenshot_2020-02-05_16-05-51](https://user-images.githubusercontent.com/16662475/73853772-b5dd5480-4831-11ea-8788-e99117bf533c.png)

Is something like that possible?

**Comment by blizzz** [comment]
That would for authentication. For searches (e.g. sharing, users page) it is already more difficult, because every user would need to be able to browse the directory. Impossible it would be to do anything in the background (e.g. user updates, availability checks, group memberships, …). Login via email might break on some setups, and with other attributes than chosen as RDN. Authentication  via SAML breaks in some conditions, because we cannot  ensure that the LDAP user is known.

So the summary is simply: no, we would still need the service user. Further, for authentication we already do auth with the LDAP user, but the DN is being looked up via service account. Thus said, there are neither plans nor the desire to do so.
