### ISSUE TITLE
Password Reset not Working (HTTPS)

### ISSUE THREAD

**Issue by AquaMCU** [nextcloud/server#19355]
### Steps to reproduce
1. Install NC
2. Create User
3. At Login click "Passwort Vergessen" (Forgot password)
4. Click on the Link on the Mail with the Link to change the password
5. Enter new password
6. Click on Passwort Zurücksetzen (Reset Password)
--> The little popup opens with the text "Network Error"
----> When I see it correctly, that it wants to open http://XXXX/lostpassword instead of https://XXXX/lostpassword

### Expected behaviour
Password changed and no network error

### Actual behaviour
It says network error and nothing else. It even stays in the same page

### Server configuration

**Operating system:**
Linux 

**Web server:**
NGINX

**Database:**
SQLITE

**PHP version:**
I do not know

**Nextcloud version:** (see Nextcloud admin page)
18.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Followed this guide to install (using sqlite)

https://itnext.io/nextcloud-running-in-docker-compose-on-debian-with-lets-encrypt-ssl-510d937d115a

Webserver Log

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf http://XXX/lostpassword/set/zqyqxwKQUaEdokYOq7buO/OA blockiert ("connect-src"). xhr.js:178:12

Says request blocked.

**Comment by kesselb** [comment]
`overwriteprotocol` is what you are looking for. Without further configuration it's not possible to generate absolute urls in a reverse proxy setup. Please use the search here on GitHub and/or https://help.nextcloud.com to find similar issues and their possible solutions.

**Comment by aalku** [comment]
"_It's not possible to generate absolute urls in a reverse proxy setup_" then you please solve the problem another way that's not so hard to find, understand and configure. A lot of people would thank you for it.

The absolute URL is correct in my case because I click on the email and I get to the form, it's just the frontend that doesn't know the correct backend URL to submit the new password to it (it tries http instead of https) so it's a frontend issue (Vue).

In javascript you can just read the URL of the current window, it's not hard to read the right protocol (window.location.protocol) and keep using it.

Please consider fixing this. Thanks a lot.
