### ISSUE TITLE
Enable using the NextCloud apps as apps via Google Chrome shortcuts

### ISSUE THREAD

**Issue by ahahn94** [nextcloud/server#19406]
**Is your feature request related to a problem? Please describe.**
Google Chrome has a feature to create "shortcuts" to websites. It creates a shortcut that opens the website in a new window and integrates it into the apps menu of the operating system (Windows start menu, macOS/linux app launchers). This makes it possible to use a website as if it were an app, e.g. starting it from the apps launcher, switching between apps via keyboard-shortcuts, etc. With NextCloud, this does not work properly. You can create a shortcut for e.g. NextCloud Talk and if you start the shortcut, it will not show the Talk but the Files app. If you create more than one shortcut, the newer shortcut will replace the older one.
It is not possible to use e.g. NextCloud Talk and NextCloud Tasks apps in 2 separate windows created via shortcut. This is rather annoying, as it does not integrate well with an apps-focused workflow.

**Describe the solution you'd like**
Please enable the option of having a chrome shortcut for each NextCloud app.

**Describe alternatives you've considered**
For now, I have worked around this issue by creating aliases to the Nextcloud apps URLs via redirects using a local webserver. But it really should not be necessary to host an additional webserver on my desktop just to use the NextCloud apps as apps.

**Comment by ahahn94** [comment]
I think Google Chrome takes the URL for the shortcut from the PWA manifest, so having a PWA manifest for each app (which can be auto-generated) might be sufficient to resolve this issue.

**Comment by kesselb** [comment]
Seems similar to https://github.com/nextcloud/server/pull/18584/

**Comment by benfrancis** [comment]
+1 for a separate web app manifest per NextCloud app. This is not specifically just for Google Chrome, but for any browser or web app runtime supporting installable web apps via the [W3C Web App Manifest standard](https://www.w3.org/TR/appmanifest/).

Currently all NextCloud apps share a single web app manifest at `/apps/theming/manifest?v=0` with a `start_url` as the root URL of the NextCloud installation. This means that all apps share a single icon on an app launcher.

```
{
  "name": "Nextcloud",
  "start_url": "https://cloud.foo.com",
  "icons": [
    {
      "src": "/apps/theming/icon?v=0",
      "type": "image/png",
      "sizes": "128x128"
    },
    {
      "src": "/apps/theming/favicon?v=0",
      "type": "image/svg+xml",
      "sizes": "16x16"
    }
  ],
  "display": "standalone"
}
```

I'd like to suggest a separate web app manifest for each NextCloud app so that each app can be separately installed with its own launcher icon (the apps already each have their own favicons).

E.g. a manifest at `/apps/photos/app.webmanifest`:

```
{
  "name": "Nextcloud Photos",
  "short_name": "Photos",
  "start_url": "/apps/photos/",
  "scope": "/apps/photos/",
  "icons": [
    {
      "src": "/apps/photos/theming/icon.png",
      "type": "image/png",
      "sizes": "128x128"
    },
    {
      "src": "/apps/photos/theming/icon.svg",
      "type": "image/svg+xml",
      "sizes": "16x16"
    }
  ],
  "display": "standalone"
}
```


See also:
* https://help.nextcloud.com/t/separate-subdomain-or-web-app-manifest-per-app/50255
* https://github.com/nextcloud/server/pull/18584

**Comment by szaimen** [comment]
Should work with https://github.com/nextcloud/server/pull/28459

**Comment by MexHigh** [comment]
Is there any way to revert to the previous behavior? I loved the way that the whole Nextcloud was it's own application, where I could navigate to all my groupware stuff. I haven't found a way to tell Chrome to just use the whole domain as a dedicated desktop application (like it was before).
