### ISSUE TITLE
Missleading information about missing indices

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#19458]
After upgrading to NC18.0.1 I have information that the database have missing indices. 
I am proposed to run  "occ db: add-missing-index" 

However the correct command is "sudo -u www-data php occ db:add-missing-indices"
or even sudo -u www-data php /var/www/nextcloud/occ db:add-missing-indices

**Comment by kesselb** [comment]
Mind to join https://www.transifex.com/nextcloud/nextcloud/ and fix the wrong translation. I guess in general we should exclude such commands from translation because that's happening from time to time.

![Screenshot_2020-02-13 Nextcloud Transifex Editor](https://user-images.githubusercontent.com/3902676/74440607-91572d00-4e6e-11ea-8758-cce4d6226b42.png)

To find the translation on transifex:

- Open resource `core`
- Select swedish as language
- Use `text:'occ db:add-missing'` as filter

**Comment by rollanders** [comment]
I will do that. But also the english text is incomplete. I will check if I can also add some information there. 

Roland






Den torsdag 13 februari 2020 14:41:13 CET, kesselb <notifications@github.com> skrev: 





Mind to join https://www.transifex.com/nextcloud/nextcloud/ and fix the wrong translation. I guess in general we should exclude such commands from translation because that's happening from time to time.



To find the translation on transifex:

     
    * Open resource core
    
    * Select swedish as language
    
    * Use text:'occ db:add-missing' as filter

**Comment by kesselb** [comment]
Please keep the english text like that. `occ` is used as placeholder anywhere else. How you call `occ` depends on your individual setup. That's different for docker, snap or bare metal.

**Comment by rollanders** [comment]
Done
Roland






Den torsdag 13 februari 2020 14:54:39 CET, kesselb <notifications@github.com> skrev: 





Please keep the english text like that. occ is used as placeholder anywhere else. How you call occ depends on your individual setup. That's different for docker, snap or bare metal.

**Comment by kesselb** [comment]
Thanks @rollanders :+1:
