### ISSUE TITLE
IPV6 Trusted Domain Not Recognized with any settings including wildcards

### ISSUE THREAD

**Issue by karz1** [nextcloud/server#19597]
/var/www/nextcloud/config/config.php
array ('::1', '[::1]','5555:*', '[5555:asterisk],'[asterisk]','[asterisk:asterisk],'asterisk',),

(* wont show properly here on github, so I put asterisk)
I found my IPV6 from ip6only.me , tried the whole address inside [] and without.(5555 just an example, _not_ my real IP)
Still get error webpage
"Access through untrusted domain"
What is the proper format to allow all IPV6?
Documentation is not clear at all about IPV6

**Comment by sndrr** [comment]
AFAIK a trusted domain is how you can access the server. So this can be either an IPv6 address, or a DNS entry. Indeed, I only found [IPv4 documentation for adding trusted domains](https://help.nextcloud.com/t/adding-a-new-trusted-domain/26).

There seems to be a bug in the handling of IPv6 addresses, as seen in [nextcloudpi](https://github.com/nextcloud/nextcloudpi/issues/150), but I'm not sure it's already fixed in nextcloud/server.

The way around is to address via DNS (or local hosts file), and adding those to your trusted domains (trusted.example.org here):
```
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'trusted.example.org',
  ),
```

Hosts file entry:
```
2001:DB8::1:1 trusted.example.org
10.1.2.3 trusted.example.org
```

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/master/tests/lib/Security/TrustedDomainHelperTest.php

At least there are test cases for IPv6. I assume adding the IPv6 in brackets without a port should work. Probably not bad to add an example for IPv6 to `config.sample.php`. 

Please note that's a bug tracker. For questions use https://help.nextcloud.com the next time.
