### ISSUE TITLE
Show full size image in picture viewer instead of resized preview. Is it possible?

### ISSUE THREAD

**Issue by rkkoszewski** [nextcloud/server#1968]
### Steps to reproduce
1. Install Nextcloud and set preview_max_x and preview_max_y to 256
2. Go to a folder with images
3. Click on an image to view the image in big

### Expected behaviour
Show the image in full resolution.

### Actual behaviour
The image is shown in the maximum resolution for preview images (256x256px). Which is very small.

### Why?
I guess that the Nextcloud viewer is using the resized preview images to save server network bandwidth. 
But running a server on a low powered device makes optimisation a bit harder. 

Is there any option to view the raw image in the image viewer without having to disable enable_previews?

Or is there any option to generate all the previews in a cronjob (For example at night)?

### Server configuration
Nextcloud is running on a Apache server on a low power MK808 ARM device (Raspberry Pi alike).

**Nextcloud version:**
10.0.1

**Comment by rullzer** [comment]
Ah yes this is long on the todo list. We are actually improving the preview system to be more efficient for NC11. That will include an app that can generate previews. It is very simple and primitive right now but it is a start that we can hopefuly exand on.

Long story short we always server optimized previews for this yes. This because the UX is pretty terrible otherwise. For example a lot of devices (including mobile) are not happy when you try to load a 20mb image ;)

So short awnser. Currently there is no real solution. But hopefully we'll improve the situation soon :)

**Comment by MorrisJobke** [comment]
> Or is there any option to generate all the previews in a cronjob (For example at night)?

Yes - there is the preview generator app: https://github.com/rullzer/previewgenerator/

> Is there any option to view the raw image in the image viewer without having to disable enable_previews?

That would be a ticket for the gallery - so please open it there.

> Install Nextcloud and set preview_max_x and preview_max_y to 256

I guess this is not that much needed because we improved the preview generation a lot in 12 and 13.

**Comment by Temtaime** [comment]
Why closed? There's a NC16 and still no solution.
I want to see previews only in grid view, when i click on the file, i want to see an original one.

**Comment by derMart** [comment]
> That would be a ticket for the gallery - so please open it there.

E.g. this one: https://github.com/nextcloud/photos/issues/1702

**Comment by derMart** [comment]
For viewer, there is this one: https://github.com/nextcloud/viewer/issues/1205
