### ISSUE TITLE
Public dav endpoint doesn't allow GET of files

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#19700]
Because the token is passed as basic auth, you cannot do a simple get without this parameter, which is not what a basic auth is made for anyway.

We should use the cookie for authentication, and let us direct access any file a PROPFIND returns as this is most likely not compliant to any dav endpoint :)

https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/apps/dav/lib/Connector/PublicAuth.php#L76-L93
https://github.com/nextcloud/server/blob/5e4eda1ae0ea0ee7e690fee1017dae873a1a7512/apps/files_sharing/js/public.js#L59

**Comment by juliushaertl** [comment]
The token as username is not only for public share pages but also used by federated sharing this way. Also just storing in a cookie won't work as you could have multiple share links open at the same time, but we probably could store a list of all share tokens there.

cc @rullzer

**Comment by skjnldsv** [comment]
> The token as username is not only for public share pages but also used by federated sharing this way. Also just storing in a cookie won't work as you could have multiple share links open at the same time, but we probably could store a list of all share tokens there.

Argh, this complicates :(
We still should avoid this. What about a special dav endpoint like public.php/dav/TOKEN instead?

**Comment by ShaunCurrier** [comment]
This re-purposing of the basic auth header for sending the public share token also breaks my reverse proxy configuration.  I know this isn't an officially supported configuration, but I use basic auth on the reverse proxy to keep the big bad internet away from the Nextcloud application.  I send the (really long) basic auth credentials to anyone I want to share a public link with.  Problem is, the page only partially loads because it breaks when it gets to the public.php/webdav request which seems to require the basic auth header when hitting the backend server.  The reverse proxy is stripping that off, breaking the page.  I wish the header wouldn't be abused in this way so that standard things could work in standard ways.

Just my two cents.  I still love Nextcloud!
