### ISSUE TITLE
workflow : when file is commented 

### ISSUE THREAD

**Issue by meaz** [nextcloud/server#19849]
I have the workflow "Write to conversation" enabled.
It would be nice to be able to select "When File commented" and "Filter new comment" so that when someone adds a new comment to a file, a notification is sent.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by meaz** [comment]
Not yet. I haven't tested updating. Are those options available now?

**Comment by szaimen** [comment]
Please let me know if they are! :)

**Comment by Spartachetto** [comment]
An additional possibility is to put conditions on the content of the comment. Some examples:
- when @user is mentioned in the comment 
- when the comment contains the regexp "*foo"

**Comment by Spartachetto** [comment]
@szaimen I get that you are making a massive simplification effort in the open issues list. Yet could you please clarify a bit which is the supposed procedure here?

In my humble opinion the feature proposed is really interesting. It was not realized (if I got it right). People working on the Flow app were not involved in this issue discution.

Are we supposed to insist that this issue is valid or we have to understand that it does not fit in the current schedule?

**Comment by szaimen** [comment]
It seems like I simply missed pinging the correct people in the right time.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by Spartachetto** [comment]
@szaimen Thank you very much for the explanation!!!!
