### ISSUE TITLE
oc_filecache is huge over 100GB

### ISSUE THREAD

**Issue by miodzicho** [nextcloud/server#19911]
### Steps to reproduce
1. upload files into Nextcloud for few users
2.
3.

### Expected behaviour
oc_filecache should be smaller

### Actual behaviour
oc_filecache is over 100GB, killing my sql server

### Server configuration

**Operating system: Ubuntu 18.04

**Web server: apache2

**Database:MariaDB

**PHP version:7.3

**Nextcloud version:latest

**Updated from an older Nextcloud/ownCloud or fresh install: updated

**Where did you install Nextcloud from:nextcloud web page

**Comment by Dragon988** [comment]
Need more info. Any errors in the logs? Did this happen after a specific nextcloud version?

**Comment by anschuetz** [comment]
Hi there :) 
I've got the same issue: 
about 700 Users in LDAP-Backend, External SMB-Storage is connected for 60 of the users, active working are only 3 to 5 Users.
Although there are only 8GB of Data, the oc_filecache has a size of 44GB
occ files:cleanup --> no orphaned files
occ versions:cleanup --> no effect

Is there a way to shrink the filecache?  It would be wonderful, because I want to move the whole installation (docker-container) through a 1Mbit-Network to a cool server outside :)
best regards 
Jesko

**Comment by glorenzutti** [comment]
Hi there!
Check this similar bug
https://github.com/nextcloud/server/issues/7312

Someone suggested that you can optimize or alter the table oc_filecache to reclaim the space.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/7312
