### ISSUE TITLE
ContactsMenu is querying and processing _all_ contacts

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#20009]
The Manager of the ContactsMenu is currently querying all contacts, sorting them and filtering them.

https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/private/Contacts/ContactsMenu/Manager.php#L69

This is causing issues when a user has many contacts, possible also caused by a big system-addressbook. Instead of fetching all contacts right away, it would be better to pass down `$limit`, `$offset` and `$sortBy` the layers.

This would require breaking changes to the following interfaces:
- `OCP\Contacts\ContactsMenu\IContactsStore`:
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/public/Contacts/ContactsMenu/IContactsStore.php#L40
  - Proposed changes:
     - add `$limit`, `$offset` and `$sortBy`
     - add constants to `IContactsStore`, which can be passed into `$sortBy`

- `OCP\Contacts\IManager`
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/public/Contacts/IManager.php#L101
  - Proposed changes:
     - add `$limit`, `$offset` and `$sortBy`
     - allow to sort by VCard Property name

- `OCP\Contacts\IAddressbook`
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/public/IAddressBook.php#L82
  - Proposed changes:
     - add `$limit`, `$offset` and `$sortBy`
     - allow to sort by VCard Property name

- `OCA\DAV\CardDAV\CardDAVBackend`
https://github.com/nextcloud/server/blob/d224ee667e432d62ca29a88c56d64c9820e55a61/apps/dav/lib/CardDAV/CardDavBackend.php#L912
  - Proposed changes:
     - option 1
       - add `$limit`, `$offset` and `$sortBy` as parameters
       - allow to sort by VCard Property name
     - option 2
       - allow to specificy `$limit`, `$offset` and `$sortBy` via existing `$options` parameter
       - allow to sort by VCard Property name

---

Possible problems we will run into:
- Our implementation of `OCP\Contacts\IManager::search` calls  `OCP\Contacts\IAddressbook::search` for every registered addressbook. Pagination over multiple sources is a problem.
  - Possible solution:
    - Only offer `$limit`, but no `$offset`.
      - Pros:
        - Applying `$limit` to multiple sources is no problem
        - serves all needs for current design of ContactsMenu
      - Cons:
        - Still no proper pagination, which would be nice to have for other use-cases.

**Comment by georgehrke** [comment]
cc @rullzer

**Comment by blizzz** [comment]
We have the same scenario with pagination in user management and solve it there by applying the pagination to the user backends, but not globally.

The contacts menu will truncate the results to `sharing.maxAutocompleteResults ??  25` anyhow. We can apply it here as well. Otherwise it is not possible without tracking state, which would be complicated and overkill.

The good thing is, that the IManager::search already accepts limit and offset. Via the $options parameter and documented since 19. It passes it on to `IAddressBook::search`. The specific implementation has to deal with it. DAV apps' `CardDavBackend` does already.  

All it takes (on a minimal level) is to equip `IContactsStore::getContacts` with offset and limit parameters. It needs a change in the public API, with additional, optional parameters it is not a biggie, since this interface is not implemented apart of our concrete service. At least I am not aware and do not find it particularly useful. 

The sorting is left out. It does not help you on a backend basis anyway, only on the final result set.

**Comment by blizzz** [comment]
@skjnldsv @juliushaertl if you have other input ^ otherwise i'd implement it like this, should be backportable.
