### ISSUE TITLE
Improve readability with inline avatars

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#2012]
In #1926 it came up, that inline avatars break the reading flow and could be improved.

I already played around a little bit and it seems that making avatars smaller already helps.

![comments](https://cloud.githubusercontent.com/assets/1899308/20004457/b847532c-a28c-11e6-90ba-01254fd22920.png)
(a) original (b) smaller (c) smaller and some edges for better fitting with the lines

Another thing @jancborchardt came up with, was the problem of generated avatars, that do not really help.

The JS Helper, which we use could be improved as well I guess:
[server/core/js/jquery.avatar.js](https://github.com/nextcloud/server/blob/master/core/js/jquery.avatar.js)
Especially inline avatars could be transformed in respective to their lines.

This affects comments, activity and other occasions of inline avatars.

@nextcloud/designers

---

- [x] `/apps/activity/js/activitytabview.js`: 28px -> 21px in nextcloud/activity#65
- [x] `/apps/activity/js/script.js`: 28px -> 21px in nextcloud/activity#65
- [x] `/apps/comments/js/commentstabview.js`: 32px
- [x] `/apps/files_external/js/settings.js`: 32px
- [x] `/apps/files_sharing/js/files_drop.js`: 128px
- [x] `/apps/gallery/js/vendor/owncloud/share.js`: 32px
- [x] `/core/js/sharedialogresharerinfoview.js`: 32px
- [x] `/core/js/sharedialogshareelistview.js`: 32px
- [x] `/core/js/sharedialogview.js`: 32px
- [ ] `/settings/js/personal.js`: 32px & 145px -> 32px & 128px
- [x] `/settings/js/users/users.js`: 32px

Apps included in search:
activity, federation, provisioning_api, admin_audit, files, sharebymail, apporder, files_external, systemtags, bookmarks, files_sharing, testing, calendar, files_trashbin, theming, comments, files_versions, twofactor_backupcodes, contacts, firstrunwizard, updatenotification, dav, gallery, user_ldap, direct_menu, workflowengine, encryption, maps, federatedfilesharing, news

**Comment by jancborchardt** [comment]
@eppfel yeah, making them a bit smaller looks good indeed! I wouldn’t do the edges since we use round avatars everywhere and it looks out of place otherwise. :)

Maybe we should define a class for avatar size so it can be used globally? Like:
- .avatar-small (like here)
- .avatar-medium (share list)
- .avatar-large (like in the public files drop page)

**Comment by skjnldsv** [comment]
And what about a small icon with a zoom on hover?

**Comment by eppfel** [comment]
I searched for all occasions of the $.avatar() helper to get an overview. Seems like it would make sense to differentiate:

- .avatar-small: 21px
- .avatar-medium: 32px
- .avatar-large: 128px

There is an exception the 145px in `settings/personal`

And I would propose to move the avatar in the comments sidebar from medium to small:
![sidebar-comments](https://cloud.githubusercontent.com/assets/1899308/20038358/9081e42c-a432-11e6-8132-63a0dc43cc87.png)
Don't mind the offset in the submit icon

I still don't know the best way to deal with this. Maybe rewrite the avatar helper to use these CSS classes? But we should leave flexibility for exceptions. @nextcloud/javascript ?

**Comment by skjnldsv** [comment]
Ahaha, well, I won't suggest anything like that ever again I promise :grin:
Anyhow, do we really want the avatar everywhere? Like on the text-only stuff, why don't we only show the name?

**Comment by Espina2** [comment]
I think its better to remove the avatars when they are to small. Don't add really nothing since you can distinguish the image because are to small. Visually the avatars in the middle of the text gives the sense of "caos". So if you think its more difficult to understand a picture that small if you compare with a name. This really breaks reading... This panel text lacks on contrast to, is really difficult to understand what is most important.

@nextcloud/designers

**Comment by eppfel** [comment]
@Espina2 I also pledged for removing avatars on some occasions, e.g. in a horizontal list of users, and I think @jancborchardt, too:
> One consideration for this context could be to show the name without placeholder when there’s no avatar. And show only the avatar of everyone when there’s more than 3 people.

– #1926 

But I would oppose to completely remove them at this size, because **they are** distinguishable. Maybe you can't clearly see what the image is showing, but in a longer conversation the avatar is the first indication of the flow:
<img width="346" alt="bildschirmfoto 2016-11-07 um 20 09 40" src="https://cloud.githubusercontent.com/assets/1899308/20072053/409599c2-a527-11e6-8fbe-e0c4555a4033.png">

Of course there could be other ways, like coloring the conversation by participant, but let's first get avatars standardized first.

**Comment by Espina2** [comment]
I really think its very difficult to understand the avatars at small sizes and can confuse with other people if the photos are very similar, because you dont see the actual content you judge the photo by color and the shape and size its not enought to see the shape. For example in the screen above I place the some photos of the Nextcloud team and its very read to understand who they are if don't have the label. Right? 

![409599c2-a527-11e6-8fbe-e0c4555a4033](https://cloud.githubusercontent.com/assets/11150206/20074514/6fba5372-a528-11e6-9cfe-1d8895b24a1d.jpg)

So I think the small circle shape looks better with the text but the Avatar is not really needed at that size so In the end I think its not needed at that case. 

So this is what I think and of course you can have a different opinion. And I think that is not completely wrong to have avatars, because at some point you already learned what that avatar mean. So its okay the two ways, just think its redundant. And for example in the layout that you show now its better than the first one and its more readable.

I really think that your first example when you have the icons and avatars inside of the text looks very bad, caotic and breaks completely the reading ( example in the top of the conversation). 

Just for finish this are really bad aligned and have to many different "starts" and "ends". 

![screen shot 2016-11-07 at 20 46 55](https://cloud.githubusercontent.com/assets/11150206/20075241/557b81e0-a52b-11e6-9084-62a715e1d7cb.png)

I hope that I explain good what I think. :)

**Comment by jancborchardt** [comment]
In the sidebar activity list and comments, using avatar-small is much too small. Especially there it’s important to see faces!

@eppfel otherwise the sizes seem fine. We could also use the 128px one for personal settings as to make it consistent.

@Espina2 in the current sidebar all the text is correctly left-aligned at the same line.

**Comment by nickvergessen** [comment]
All done?

**Comment by eppfel** [comment]
The only arbitrary size is the avatar in the personal settings and I think this is ok, because there you edit it.
