### ISSUE TITLE
OCP\Files\NotFoundException on 18.0.2 log full of them

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/server#20200]
Hi

Log full of these, 

Seems to co-incide with extra load on the platform and external shares not being available immediately

full details here

[text] Error: OCP\Files\NotFoundException:  at <<closure>>

 0. /var/www/nextcloud/apps/text/lib/Service/DocumentService.php line 363
    OCA\Text\Service\DocumentService->getFileById(1656628, "hjones")
 1. /var/www/nextcloud/apps/text/lib/Service/ApiService.php line 160
    OCA\Text\Service\DocumentService->getFileForSession(OCA\Text\Db\Session {id: 38}, null)
 2. /var/www/nextcloud/apps/text/lib/Controller/SessionController.php line 81
    OCA\Text\Service\ApiService->sync(1656628, 38, "/UIUAubU594Q2Pp ... W", 0, null, false, false)
 3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Text\Controller\SessionController->sync(1656628, 38, "/UIUAubU594Q2Pp ... W", 0, null, false, false)
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Text\Controller\SessionController {}, "sync")
 5. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Text\Controller\SessionController {}, "sync")
 6. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Text\\Cont ... r", "sync", OC\AppFramework\ ... {}, {_route: "text.Session.sync"})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "text.Session.sync"})
 8. /var/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "text.Session.sync"})
 9. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/text/session/sync")
10. /var/www/nextcloud/index.php line 38
    OC::handleRequest()

**Comment by reallydoesntmatter** [comment]
I'm having exactly the same issues, also with external shares. (In my case SMB)
I hope this will be adressed soon as it slows down the cloud to an ususable speed within an hour or so.

**Comment by wedge47** [comment]
18.0.4 with external storage (if that is related?) ... waited until 18.0.4 to upgrade from 17 ... need a workaround or fix

**Comment by wedge47** [comment]
stumbled upon this ... which looks pretty much like this issue. Unfortunately no solution.

https://help.nextcloud.com/t/weird-log-message-related-to-text-app-ocp-files-notfoundexception-node-for-share-not-found/70893

**Comment by wedge47** [comment]
Ok i'm not sure if everything is correct but i want to share it anyway. 

The issue occurs in connection with the Notes App. In my environment users have a default quota of 1 Byte because all the storage is mounted externally or they use groupfolders to store data. This worked fine in the past (NC 17.0.2) 

Some users created Notes documents (.md-files) some of them are 1 Byte in size others are much bigger. With a test user i tried to create such a file. The app opened and i was able to write a view characters .. but as soon as nc tried to save it it run in to an error "File could not be loaded. Please check your internet connection." and immediatly i got the OCP\Files\NotFoundException in the nextcloud.log for this user. 

No i increased the quota and the error was gone and i could work with the Notes file. Resetting the Quota to 1 Byte now gave the user an error about exeeded quota and that the user is not allowed to add or sync new files. If the users deletes the  .md-file everything is fine again.

I think some users (those now throwing errors) were able to create md-files in NC17 without that beeing checked against the quota. But now with nc 18 this is checked and creating that massive amount of errors.

Currently i'm not sure what to do. I could increase the default quota to a few MB. But what i also saw was, that if i increase it for one of the users with exising documents the error continued to pop up. Even when i set the quota to unlimited. So i think there is something more. 

Any ideas?

**Comment by wedge47** [comment]
Updated the default Quota from 1 Byte to 10 MB without luck. Errors still appear. I also checked oc_preferences for custom quota entries and there are only some members of the admin group with unlimited quota all other users don't have this set and therefore should be using the default.

Would really appreciate any comment

**Comment by DanScharon** [comment]
do you have one application server or several behind a loadbalancer?

**Comment by wedge47** [comment]
Hi, this is only one application server behind a ngix reverse proxy. Running as an app within Univention Corporate Server. Nextcloud is running in a docker container. The PostgreSQL is running outside of the container.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
