### ISSUE TITLE
Show modules required for webauthn in setupcheck

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#20393]
So people can actually discover it.

**Comment by MichaIng** [comment]
@rullzer 
Just found this and must say I don't like to see two additional general PHP module recommendations for "performance and stability" reasons, which are only required for a specific feature. While searching for the reason for this two modules, I found a blog post about NC19 beta update experience, presenting very well that most users, also bloggers, simply pull everything that shows up as recommendations without a thought about what it is actually for. It is nothing serious but I would like to have this only checked and shown when someone actually attempts to setup webauthn.

So probably it could be switched:
- Always show webauthn option on security page.
- Do a check for required PHP modules as fast as user attempts to setup webauthn and prompt a warning if those are missing.

This would also better match the docs, which list those "for specific apps" instead of as "recommended packages": https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html

What do you think?
