### ISSUE TITLE
ocdownloader + darkmode

### ISSUE THREAD

**Issue by CrazyJannis44** [nextcloud/server#20563]
If you activated drakmode and use the ocdownloader there is a graphic bug!

**Comment by liamjack** [comment]
Hi @CrazyJannis44, could you provide a screenshot of the graphical bug encountered ?

I think this issue is probably not a problem with Nextcloud Server but more specifically the OCDownloader app: https://github.com/e-alfred/ocdownloader

I found an issue related to a problem with dark mode and the fact that it is not yet fully supported by the app: https://github.com/e-alfred/ocdownloader/issues/131

**Comment by CrazyJannis44** [comment]
okay thx
