### ISSUE TITLE
Reduce the amount of files/directories created by Nextcloud

### ISSUE THREAD

**Issue by Baptistou** [nextcloud/server#20633]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I have installed Nextcloud in February 2020 on a shared hosting and I am quite satisfied after 2 months of use. Because of server limits, I monitored regularly the size and the amount of files/directories generated and I noticed a constant increase due to every day use but also a huge increase after each Nextcloud updates.

The following paths are concerned and could be optimized :

- **nextcloud/data/appdata_oc0123456789/documentserver_community/**
  contains a huge amount of empty directories accumulated since the 2 last months
  represents more than 50 000 files/directories and few megabytes.
- **nextcloud/data/updater-oc0123456789/backups/**
  contains the 3 last backups "nextcloud-18.0.1.0", "nextcloud-18.0.2.0" and "nextcloud-18.0.3.0"
  represents almost 36 000 files/directories each and 1 gigabyte each.
- **nextcloud/data/user1234/uploads/**
  contains a lot of file parts from user uploads aborted by an error
  represents less than a hundred of files/directories and few gigabytes.

The total represents more than 200 000 files/directories despite having only a hundred of files uploaded by 7 users.

**Describe the solution you'd like**

The directories mentioned above could/should be optimized :

- We should delete automatically generated files/directories that are not relevant anymore after some period.
- We should avoid or delete empty files/directories (outside of user directory of course).
- Nextcloud only keeps the 3 last update backups : Good ! But why not to store backups as zip archive instead ?

**Describe alternatives you've considered**

I was able to save 10 gigabytes and to decrease the amount of files/directories from 200 000 to 37 600 thanks to the following actions.

Output the size of a directory
```bash
du -chs .
```

Count the amount of files/directories
```bash
find . -printf 1 | wc -c
```

Delete unnecessary files for each user
```bash
rm -r nextcloud/data/user1234/uploads/*
```

Delete empty directories
```bash
cd nextcloud/data/appdata_oc0123456789/documentserver_community/
find . -type d -empty -delete
```

Archive update backups
```bash
cd nextcloud/data/updater-oc0123456789/backups/
zip -r nextcloud-18.0.1.0.zip nextcloud-18.0.1.0
rm -r nextcloud-18.0.1.0
```

**Comment by kesselb** [comment]
> nextcloud/data/user1234/uploads/
contains a lot of file parts from user uploads aborted by an error
represents less than a hundred of files/directories and few gigabytes.

Is already done by https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/UploadCleanup.php

> Good ! But why not to store backups as zip archive instead ?

Because it's a bad idea. A web based update might run into a timeout while creating the archive. As this concerns the updater the right repository for such a enhancement request is: https://github.com/nextcloud/updater

> nextcloud/data/appdata_oc0123456789/documentserver_community/
contains a huge amount of empty directories accumulated since the 2 last months
represents more than 50 000 files/directories and few megabytes.

The right repository would be: https://github.com/nextcloud/documentserver_community

Closing this request as the only relevant part to nextcloud/server is already done. Thanks for reporting and have a nice weekend.
