### ISSUE TITLE
Design spec: Contacts menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#207]
Reasoning: We want to integrate contacts more nicely into Nextcloud and allow people to quickly communicate with their friends. This includes text chat, voice/video call, email, sharing and other means.

For this we decided to go for an icon in the top bar between search and the user menu which is always there. Tapping on it will expand the Contacts dropdown. We went with this over a permanent sidebar because it’s less distracting/intrusive and works nicely regardless of active app or form factor. (In Files for example there would otherwise be two sidebars on the right.)

cc @nextcloud/designers @LEDfan @sualko @Henni @karlitschek @schiessle 

Normal state
![contacts dropdown](https://cloud.githubusercontent.com/assets/925062/16298115/01ca582c-3934-11e6-9d36-07f38b006b94.png)

With actions expanded
![contacts dropdown actions](https://cloud.githubusercontent.com/assets/925062/16298116/01cc61b2-3934-11e6-84ab-44c4d5c6cb66.png)

Detailed specs:
- The contacts are sorted by last interaction. It’s easiest and most obvious for the first iteration. (Instead of also factoring in frequency etc)
- On opening the dropdown, the search field will automatically be focused so people can directly type to filter.
- Below the name the last chat message is shown.
- Tapping on the area of picture, name, message etc opens a chat window (a panel down below like in the chat app).
- The most used action with this contact (call, share, mail) is directly shown. Next to it there’s a 3-dot menu with the other actions, just like in Files.
- In there is an entry »Details« to show the other contact details. This could be done by a modal/card with information from the Contacts app to not break the flow. But as a first iteration, a direct link (in a new tab) to the contact entry in the Contacts app is fine. This card should be a global thing we can show everywhere where there’s a user name + picture.
- Scrolling will load new contacts via lazy loading. At some point (after say 25 people) there’s a link »Show all contacts …« which will lead to the Contacts app.

**Comment by MorrisJobke** [comment]
> This card should be a global thing we can show everywhere where there’s a user name + picture.

Check out how discourse does it (by clicking on the avatar):

<img width="1223" alt="bildschirmfoto 2016-06-23 um 14 43 21" src="https://cloud.githubusercontent.com/assets/245432/16303421/e20c1d1e-3950-11e6-94d1-6a44cde23612.png">

**Comment by enoch85** [comment]
Really hot! :fire:

**Comment by jancborchardt** [comment]
Other examples of these account cards are Diaspora, Facebook and Twitter:
![diaspora card](https://cloud.githubusercontent.com/assets/925062/16308017/b31004e0-3963-11e6-9351-82f05d6342ff.png)
![twitter card](https://cloud.githubusercontent.com/assets/925062/16308016/b30c27b2-3963-11e6-8da2-0c10c0a14883.png)

**Comment by karlitschek** [comment]
@leonklingele

**Comment by oparoz** [comment]
Since having the Contacts app is a requirement for this feature, shouldn't this issue be created there? Surely people who don't have the app installed won't see the new icon.

**Comment by Bugsbane** [comment]
Seems to me that there is already a lot of pre-established convention for clicking on an avatar icon bringing up info on the contact, rather than opening chat (which may not be installed anyway, unless this is going into Nextcloud core).

Currently just about every social network, forum and major mobile operating system I can think of brings up the contacts details when you click on a contacts avatar (as opposed to say the last message under their name etc).

Relegating this function to having to click on a three dot menu next to their name, and then on a second "Details" icon seems unnecessarily complex. What about, if clicking:
The avatar / username - brings up the contact details
The last chat message - brings up chat (possibly displays a generic message if they haven't been chatted to before).

I'd also suggest that users be able to star contacts and then have those display first, with unstarred, recently interacted contacts just after, much like how the Android phone app displays contacts.

Also, As long as we're making this dropdown a discovery point for RTC, it could be useful to display when users are online and available for chat, possibly with the common small green circle often seen in the bottom corner of many apps to denote being online, and maybe listing those online users preferentially.

**Comment by sualko** [comment]
I like the idea and design 👍 . For our chat it would be helpful, if there is a good api which enables us to inject buttons like chat, call, video etc..

**Comment by jancborchardt** [comment]
@Bugsbane good suggestions! Especially the online indicator makes sense, if that’s possible. The starring should be integrated of course.

About the clicking-avatar-to-chat: In Nextcloud, communication takes priority over a personal profile at this point. We don’t even have the possibility to view other people’s profiles currently, so there’s nothing to show. ;) For now, opening a chat makes way more sense to directly communicate and collaborate.

**Comment by Bugsbane** [comment]
> We don’t even have the possibility to view other people’s profiles currently, so there’s nothing to show.

I was assuming that it would show that persons contact in the contacts app... most likely identified by email address after a share was successfully completed in either direction.

Thinking about this, it seems that this actually touches on a much larger interaction issue - namely how contacts in the contacts app (used by the contacts and mail apps) relate to other Nextcloud users (which is presumably what the chat app and Spreed.me app uses). Right now, we seem to have two completely distinct lists of people that the user is exposed - Nextcloud users and the people in the contacts app.

**Comment by crossix** [comment]
I agree with @Bugsbane It would be nice if there were a way to "link" or "smart link" a contact from the contacts list to one that exists in the Nextcloud users area say via the email fields. It's never really made sense to me as to why these two are separate areas with no link in between.  I've often wondered if there was a way to expand upon the users area instead of just being able to add / remove users, change passwords, etc; to also include contact info for that user. Yes this could be possible with LDAP, but what if you aren't using LDAP integration? 

You wouldn't always have to link contacts (you could still create contacts separately), but if the user existed in the users area give to option to do so.

**Comment by icewind1991** [comment]
> Since having the Contacts app is a requirement for this feature, shouldn't this issue be created there? Surely people who don't have the app installed won't see the new icon.

Iirc with 9.1 contacts are stored by the `dav` app (always enabled) with `Contacts` just providing the web interface

**Comment by mar1u5** [comment]
That is correct. Tables for Calendars and Contacts are created in the DB ... Even if the frontends are not installed :wink: 

However: I dont think it makes many sense to show this widget, if the app is diabled :stuck_out_tongue_winking_eye:

**Comment by jancborchardt** [comment]
In any case we're going a bit deep overboard with this discussion and too much into wall of texts it seems. ;) We have enough to build a great first iteration, so let’s focus on getting that done. :)

**Comment by oparoz** [comment]
>Iirc with 9.0 contacts are stored by the dav app (always enabled) with Contacts just providing the web interface

Indeed, but that DB needs to be populated one way or another. I guess that if it's empty, you could show a message, inviting the user to install the Contacts app to be able to quickly share a document from the top bar, but I'm wondering if share should even be there. Wouldn't you start by selecting the document and then share it instead of selecting a contact first from the top bar? (It's not the same as sending a document from a chat)

Also, the specs as described in the OP have another dependency. You need a chat app installed for some of the features to work (show last message, opening a chat window). I'm guessing a lot of the described actions require if-else blocks, but it's not clearly stated and is it the best solution or should a plugin system be put in place, so that apps can add their own actions?

**Comment by oparoz** [comment]
Never mind, this is purely a specs discussion, not an implementation one.

I have 2 comments then:

>The most used action with this contact (call, share, mail) is directly shown

I'm not sure this will work. In my experience, automation almost always gets in the way. Sure the action I want will always be in the 3 dots, but then why have 2 icons?


Secondly, you have to be careful with the sub-menus and modal cards on mobile, it can quickly become a pain to use when content auto-scrolls or you have to zoom, etc.
Maybe we could get some screenshots on how it would look on an "typical" HD mobile screen?

**Comment by Bugsbane** [comment]
> You need a chat app installed for some of the features to work

Contacts is currently slated to be an installed-by-default, core app, right? Is this the case with the chat app also? (Will the default chat app be Spreed?)

**Comment by mar1u5** [comment]
> Contacts is currently slated to be an installed-by-default, core app, right? Is this the case with the chat app also? (Will the default chat app be Spreed?)

Uhm... No. I think you need to enable them. Also with Nextcloud 10 :confused: 

Maybe we should move the discussion to our forum, to keep this Issue as clean as possible.

**Comment by LEDfan** [comment]
So, I have been thinking about this for the last couples of days and here are some thoughts:

 - I'm quite sure we don't need the Contacts app as a dependency. The Contacts are now stored in core, and all the users are stored in the system addressbook anyway.
 - XMPP has it's own "contacts" inside, this is the roster. Currently the roster of OJSXC is created when requested on basis of the userManager. This could be changed to use the Contacts manager. XMPP also support vcards for more information.
 - Currently for [OJSXC](https://github.com/ownlcoud/jsxc.chat) no chat messages are stored.  However this can be implemented (refs https://github.com/jsxc/jsxc/issues/150)
 - If spreed.me would support XMPP as chat backend (which I think could have some great benefits) the chat system inside Nextcloud and inside Spreed.me could be 100% the same. (because they are both using the same XMPP server) https://github.com/strukturag/spreed-webrtc/issues/286
 - We should support both the internal XMPP server of Nextcloud and an external XMPP server. The external server should be for bigger and more advance installations of course.

**Comment by jancborchardt** [comment]
@LEDfan @sualko you should get involved in the planning discussion on integration of the video chat and text chat! :) At https://github.com/nextcloud/spreed/issues/35

**Comment by MorrisJobke** [comment]
Something for 12

**Comment by poisony** [comment]
WOW! I can't wait for this to available! This feature is exactly what I'm looking for! 💃

**Comment by ChristophWurst** [comment]
> * The most used action with this contact (call, share, mail) is directly shown. Next to it there’s a 3-dot menu with the other actions, just like in Files.
> * In there is an entry »Details« to show the other contact details. This could be done by a modal/card with information from the Contacts app to not break the flow. But as a first iteration, a direct link (in a new tab) to the contact entry in the Contacts app is fine. This card should be a global thing we can show everywhere where there’s a user name + picture.

Alternatively, we could expand the contact in the list and show that information underneath. Then we don't have a popover menu inside a popover menu. Nested popover menus look strange IMO.

**Comment by jancborchardt** [comment]
@ChristophWurst I’d say when »Details« is clicked, the menu popover is replaced by the details popover. It’s pretty similar to what you describe, except that it doesn’t break the flow or layout of the listing. :)

**Comment by ChristophWurst** [comment]
I'd highly appreciate input/feedback on the API design https://github.com/nextcloud/server/issues/3316 😉

**Comment by ChristophWurst** [comment]
@jancborchardt stupid question, but what should the 'share' action do? I can imagine the intention of 'call' and 'mail', but 'share' confuses me 😆

**Comment by ChristophWurst** [comment]
It's likely that contacts have multiple mail addresses, how should we handle that case - interface-wise?

**Comment by ChristophWurst** [comment]
> In there is an entry »Details« to show the other contact details. This could be done by a modal/card with information from the Contacts app to not break the flow. But as a first iteration, a direct link (in a new tab) to the contact entry in the Contacts app is fine. This card should be a global thing we can show everywhere where there’s a user name + picture.
> Scrolling will load new contacts via lazy loading. At some point (after say 25 people) there’s a link »Show all contacts …« which will lead to the Contacts app.

Summoning @skjnldsv @Henni @irgendwie for this one. Do you guys know if the contacts app currently supports such URLs? If so, which format should be used? Thanks :)

**Comment by MariusBluem** [comment]
> Summoning @skjnldsv @Henni @irgendwie for this one. Do you guys know if the contacts app currently supports such URLs? If so, which format should be used? Thanks :)

I think this was done with https://github.com/owncloud/contacts/pull/323, and the format is something like https://localhost/index.php/apps/contacts/#/all/2cbf6908-4a5b-403f-8e68-77165679b3bb 😁 
@ChristophWurst

**Comment by skjnldsv** [comment]
It's wih the default group: `All%20contacts` :)

`https://localhost/index.php/apps/contacts#/All%20contacts?uid=2587a92d-f70e-4d75-a5ad-938b699669c8`

**Comment by ChristophWurst** [comment]
> It's wih the default group: All%20contacts :)
> 
> https://localhost/index.php/apps/contacts#/All%20contacts?uid=2587a92d-f70e-4d75-a5ad-938b699669c8

Yeah I figured that too, but apparently it's localized, so I wasn't sure if this works for all users.

**Comment by skjnldsv** [comment]
I can add a redirect to a single uid easily if that's what we need :)

**Comment by ChristophWurst** [comment]
Yup, that would be great 🚀 

We can either handle this in the contacts app client-code or have a dedicated route where we redirect the request to the according address book.

**Comment by jancborchardt** [comment]
@ChristophWurst Share should open a filepicker - what do youtl think? :)

**Comment by ChristophWurst** [comment]
Really? I did not expect that. So what would happen after I presumably select a random file with the file picker? Are you planning to duplicate the file sharing workflow?

In order to implement this, I need more details. Please describe what and how all the actions should work. Ideally, some mockups would be really helpful here :-)

**Comment by jancborchardt** [comment]
Ok so first let's talk about if it makes sense. My idea would be:
1. You click share on a friend
2. Filepicker opens (problem is, how do you share stuff like contacts or calendars?)
3. Choosing a file could simply directly share it, with the default permissions. No opening of sharing sidebar etx.

How would you expect the flow @karlitschek @ChristophWurst?

**Comment by karlitschek** [comment]
Well. Tricky. Sharing files, calendars, contacts are in deed difficult. Maybe this was a bad idea from me in the first place. ;-) Maybe this menu should do stuff like, send mail, start chat, call, show contact details, ... But probably not sharing. At least I'm also unsure how the flow here should work ;-)

**Comment by skjnldsv** [comment]
I say, let's focus on simple actions like chat, call, show contact... And we'll see after the implementation if this is difficult enough and/or worth the work?

**Comment by jancborchardt** [comment]
@georgehrke will work on making it happen for everywhere an avatar+username is shown. On click, it will simply show the dropdown menu with the actions. :)

**Comment by MorrisJobke** [comment]
Implemented with #3233

**Comment by alexeyvolkoff** [comment]
Hi, is it any option to limit the list of users in the dropdown to group(s) a user belongs to, or circle?

**Comment by beerlao** [comment]
Wouldn't it make sense to at least give an option to hide local users in contacts menu or limit them to the same group? Then only contacts from contacts app or the same group would be shown. Otherwise users will be able to see contact details and contact images of other users on the same NC12 instance.
