### ISSUE TITLE
Error updating Nextcloud 18.0.3 and 18.0.4

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#20723]
### Expected behaviour
Nextcloud update without errors.

### Actual behaviour
The following errors occurred when updating Nextcloud 18.0.3 to 18.0.4:

```
Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
```

### Server configuration
MySQL version: 5.6.44
PHP version: 7.2.14

**Comment by kesselb** [comment]
https://github.com/nextcloud/spreed/issues/2663
https://github.com/nextcloud/server/issues/19102

I'm not aware of a solution yet :disappointed:

**Comment by learal** [comment]
I'm getting a similar problem upgrading from 18.0.3 to 18.0.4, however it terminates the upgrade on the first error.

Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version8000Date20200407073807, because the name is already in use in /config/www/nextcloud/apps/spreed/lib/Migration/Version8000Date20200407073807.php on line 46

**Comment by Githopp192** [comment]
Got a similar issue by ugprading NC from 17.0.3 to 18.0.3 -->


2020-04-08T13:53:46+02:00 Repair error:   Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2020-04-08T13:53:46+02:00   Repair info: No repair steps available |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
PHP   Fatal error:  Cannot declare class   OCA\Talk\Migration\Version8000Date20200331144101, because the name is already   in use in   /var/www/html/nextcloud/apps/spreed/lib/Migration/Version8000Date20200331144101.php   on line 54 |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

What i did to solve it:
-----------------------
Before that .. put your Instance to maintenance mode & stop the Web-Server !

1.) sudo -u www-user /bin/php /var/www/html/nextcloud/occ maintenance:repair
2.) sudo -u www-user /bin/php /var/www/html/nextcloud/occ db:add-missing-indices
3.) sudo -u www-user /bin/php /var/www/html/nextcloud/occ db:convert-filecache-bigint

After that .. disable your Instance from maintenance mode & start the Web-Server 

4.) Repeat the Upgrade (this time the Server is already on NC 18.0.3)
5.) Upgrade will become successful

**Comment by Githopp192** [comment]
little correction 

Before that .. put your Instance to maintenance mode & stop the Web-Server !
do this AFTER Step 1.)

**Comment by nickvergessen** [comment]
I added some explanation and a link to the real fix to the first post of https://github.com/nextcloud/spreed/issues/2806
