### ISSUE TITLE
WebDAV and mobile app urls do not use https

### ISSUE THREAD

**Issue by gerout7** [nextcloud/server#20728]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup Nextcloud with https enabled
2. Click on settings at the left site at the bottom of the default page
3. The URL that is presented for WebDAV uses http

The same is true for the example url in "Mobile and Desktop" as well as the monitoring url and possible others

### Expected behaviour
all URLs should use https if the server supports it.

### Actual behaviour
Urls in the WebDAV setting and mobile setting example start with http://

This could lead to users accessing files without transport encryption in case no permanent redirect or HSTS is used.

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mariadb

**PHP version:** Version: 7.3.17

**Nextcloud version:** Nextcloud 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** docker hub: https://hub.docker.com/_/nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
default apps only

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

Default config, no changes needed for reproduction

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by rullzer** [comment]
Most likely you are behind a reverse proxy.
See https://docs.nextcloud.com/server/18/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse

**Comment by gerout7** [comment]
That is correct.
So does nextcloud switch to https in the example urls when https is enabled on the webserver itself?
Is there a way to "fix" this issue with reverse proxies handling tls and the example urls being http only?

**Comment by rullzer** [comment]
See the documentation link I passed You need to overwrite the protocol. Then all is good.

**Comment by thgoebel** [comment]
@rullzer The docs say "If Nextcloud fails to automatically detect the hostname, protocol or webroot you can use the overwrite parameters inside the config/config.php".

The _If Nextcloud fails to automatically detect_ bothers me. It suggests `overwriteprotocol` is only a fallback? Or does Nextcloud always use `overwriteprotocol`?

I tried setting `overwriteprotocol` to both `http` and `https` but it does not make any difference. Nextcloud still uses http.

(I've also posted about my issue back [in the forum](https://help.nextcloud.com/t/some-http-links-not-rewritten-to-https/74192/8), but am still searching around and debugging it. Same root cause, Nextcloud doesn't get the https.)

**Comment by scar45** [comment]
I'm not sure if any of this may help @thgoebel, but I ran into the same issue as you, and I was able to resolve it on a fresh installation by modifying `config/config.php` to contain:

```
'overwrite.cli.url' => 'https://{{ url }}', # Note the change from 'http' to 'https' here
'overwriteprotocol' => 'https',
```

...and it appeared to fix a problem where users could not reset their password. I know you said you tried `overwriteprotocol` but perhaps the change to `overwrite.cli.url` may help if not already attempted.

**Comment by thgoebel** [comment]
Thanks for the tip, but I already had that as well :)

I was able to fix it for me by removing the `'overwritecondaddr' => '^172\\.20\\.X\\.X$',` line from the config.php. That seemed to clash with the `'overwriteprotocol' => 'https',` line.
Since the proxy's IP is not fixed in Docker it was wrong anyway (you can assign it a fixed IP, but I didn't do that).
