### ISSUE TITLE
Update sabre-io/dav to 4.1.0

### ISSUE THREAD

**Issue by mario** [nextcloud/server#20733]
This would allow the clients to use streaming propfind.

**Comment by rullzer** [comment]
Will take care of this early in the 20 cycle

**Comment by kesselb** [comment]
Streaming propfind is available since 4.0.3 :tada: That's luckily the version shipped with Nextcloud 19 :raised_hands: 

Streaming is disabled by default. You may have a look how owncloud enabled it: [https://github.com/owncloud/core/pull/36336](https://bit.ly/2zUY7Ax). 

It's seems they discarded it due some issue with their test suite. I support the idea to enable streaming only if the client is asking for it (e.g. by a header). 

But there is nothing wrong with updating sabre :smiley:

**Comment by mario** [comment]
I also think enabling streaming via a header is a good idea.
