### ISSUE TITLE
Absturz der Nextcloud- / Talk-App

### ISSUE THREAD

**Issue by whoch3** [nextcloud/server#20799]
Hallo,

unser Mitarbeiter hat ein Samsung XCover 4 mit Android 9 und aktuellen Nextcloud-Apps. Leider stürzen die Apps nach dem Start ab. Wir haben auch schon die Apps neu installiert. Das Problem besteht weiterhin.

Könnten Sie sich das bitte anschauen.

Mit freundlichen Grüßen

Robert Weise-Prüß

**Comment by kesselb** [comment]
If you have a Nextcloud Enterprise subscription: https://portal.nextcloud.com

Otherwise: https://help.nextcloud.com

GitHub is not a channel for support. If you report a bug use the provided issue template. The right repository to report a issue for the Talk apps are:

- IOS: https://github.com/nextcloud/talk-ios
- Android: https://github.com/nextcloud/talk-android
