### ISSUE TITLE
Fehlende Push-Benachrichtigungen bei Talk-App

### ISSUE THREAD

**Issue by whoch3** [nextcloud/server#20801]
Hallo,

bei mehreren unserer Mitarbeiter (iPhones) werden neue Benachrichtigungen der Talk-App auf der App-Übersicht nicht angezeigt und es gibt auch keine Push-Nachrichten.
Alle Einstellungen wurden bereits geprüft und angepasst (Systemeinstellungen, App-Einstellungen, Account-Einstellungen). Beispiel: unser GF hat ein aktuelles iPhone 11 Pro mit aktueller Software und aktuellen NC-Apps. Diese wurden auch schon deinstalliert und wieder neu eingerichtet. Leider ändert sich am Fehler nichts.

Bitte prüfen Sie den Fehler.

DANKE

Mit freundlichen Grüßen

Robert Weise-Prüß

**Comment by kesselb** [comment]
If you have a Nextcloud Enterprise subscription: https://portal.nextcloud.com

Otherwise: https://help.nextcloud.com

GitHub is not a channel for support. If you report a bug use the provided issue template. The right repository to report a issue for the Talk apps are:

- IOS: https://github.com/nextcloud/talk-ios
- Android: https://github.com/nextcloud/talk-android
