### ISSUE TITLE
In some modules, there will be some bugs when operating on files with the same name.

### ISSUE THREAD

**Issue by z536797212** [nextcloud/server#20926]
1. Upload a file to a folder (for example, the file path is 'b / a.txt'), and upload a file with the same name to another folder (c / a.txt).
2. Then click 'Recent', there are two files just uploaded. I clicked rename one of the files, and another file with the same name will also display the rename box.

In fact, other modules (such as share, favorite, tags, etc.) other operations  (such as delete, move, copy, etc.)  on files with the same name may also have this problem (some of which I have not verified). I studied the relevant code (but not very carefully), it seems that the file operation is based on the file name, not the file id or absolute path.
**Nextcloud version: 18.0.4**

**Comment by szaimen** [comment]
Seems like this was fixed in the meantime
![image](https://user-images.githubusercontent.com/42591237/120467149-2782cf80-c3a0-11eb-84a1-a14b212e54f2.png)

---

![image](https://user-images.githubusercontent.com/42591237/120467173-2ce01a00-c3a0-11eb-9fa3-19c65a42a3bb.png)

---

![image](https://user-images.githubusercontent.com/42591237/120467208-37021880-c3a0-11eb-95b7-a072a0d82275.png)

**Comment by parredondov** [comment]
Having the same issue
