### ISSUE TITLE
why is in user admin page the search bar is linked to" Allow username autocompletion in share dialog" ?

### ISSUE THREAD

**Issue by itsequans** [nextcloud/server#21031]
FOr privacy reason we want to deny auto completion of usernames in share dialog.
When admins are managing users in user admin page it is very useful to find users using the search bar.
But when "Allow username autocompletion in share dialog" is siable in sharing settings, this automatically disable the users search in the the search bar of the admin page.
Why ? Is it a decision you made by design ? It is a bug ? is it a side effect you never found before ?

**Comment by Dragon988** [comment]
Probably because it's a global setting and wasn't designed to be separate for admins. I haven't personally looked at the code but this is either a simple fix or a very long and complex fix depending on how it was designed.

cc @kesselb ?

**Comment by itsequans** [comment]
if it is a global setting so its labeling is wrong. it should not be "allow username autocompletion in share dialog" but "allow username autocompletion" and it should not be located in the sharing settings menu

**Comment by Dragon988** [comment]
It seems to be fixed in NC 19 RC2. It might even already be backported. Did you check if it was?

**Comment by itsequans** [comment]
I already use 18.04 and can tell that it's has not yet been backported.
I will check in the next 18 release when it will be published. Thanks for the info

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.2
cc @nextcloud/sharing Maybe we should rename the option "allow username autocompletion in share dialog" to "allow username autocompletion" as suggested? Where would this need to be adjusted in the code?

**Comment by minosimo** [comment]
I will bump this back open if that's ok, I believe this is still an issue in NC28. We run an instance where there are few admins who communicate with a bunch of users who should not be aware of each other. All users are in the same group, and creating separate groups for each would be rather inconvenient.

With the toggle disabled, users cannot contact each other, but admins also cannot contact users easily.

Making it so admins always get the full user list in share and other dialogs, regardless of the "allow username autocompletion in share dialog" toggle, would be very helpful.

Renaming the toggles should maybe be a separate issue. Since the toggle is not just for sharing, but also address book, talk, and other places, maybe it makes sense to simplify them to refer to just the "System address book" or "Viewing users".

The first toggle could be renamed to "Allow users to access the system address book", and the sub-option could be"Only allow users to view users in the same groups".
