### ISSUE TITLE
"Default quota" incorrectly displayed in administrator settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#21085]
### Steps to reproduce

1. Log in as an administrator.
2. Select from the "Users" settings.
3. Edit user settings.
4. Change "Quota" to "Default quota".
5. Save settings.

### Expected behaviour
Correct display of the "Default quota".

### Actual behaviour
The default limit is displayed as "0 B".

![obraz](https://user-images.githubusercontent.com/47037905/82763112-831d9300-9e05-11ea-8fc5-33ae91fbdf7a.png)

**Nextcloud version:** (see Nextcloud admin page)
19.0.0 RC2 and 18.0.4

**Comment by Valdnet** [comment]
The bug still hasn't been removed even though we already have **Nextcloud 20.0.1**.
@MorrisJobke Who to contact about correcting the code?

**Comment by MorrisJobke** [comment]
cc @skjnldsv @juliushaertl @PVince81

**Comment by PVince81** [comment]
Confirmed still happening in NC 20.0.0.

I guess that maybe the value isn't properly evaluated in the users list.

**Comment by PVince81** [comment]
Right, and once I refresh the page it displays the actual default value in GB instead of just saying "Default quota".
And when I change the default quota on the left panel, it doesn't refresh every entry in the list.

**Comment by PVince81** [comment]
Hmm there's a discrepancy in the data:

the server populates the "quota" value with the same like "total" when a default quota is set:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/277525/97284001-cbbbfb00-1840-11eb-8c75-af57a162d18b.png">

it's only when directly setting default quota that it becomes "default" locally. but upon next refresh, the server value will override it.

so will need to adjust the server to return the string "default" instead of a value

**Comment by skjnldsv** [comment]
I decided to not bother with this a long time ago (nc14 I think?)
Default quota will apply the default quota, but not display it. It's been like that since a long time and it's the cleaner way imho. Let's not bother handling string and numbers, just display the actual value of what "default quota" is. This was also requested by users as otherwise you don't always know what it refers to.

**Comment by MorrisJobke** [comment]
Regarding default quota there is also https://github.com/nextcloud/server/issues/11393 and https://github.com/nextcloud/server/pull/13909 where we tried to improve the default quota as well. It had some tricky side effects and for that reason wasn't continued.

**Comment by skjnldsv** [comment]
Also, remember this endpoint is also used by other data that might actually need the exact quota byte count. I would refrain from touching this.

**Comment by PVince81** [comment]
Yeah, I'm also worried about API breakage...

So the quick fix is that after applying the default storage upon edit, the string will display the matching size value. And after refresh you'll see the same value. This way it looks consistent.

**Comment by PVince81** [comment]
Also: when the default quota is "unlimited", the server returns "-3" for the quota (instead of "none") so "0 B" appears as well.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/23711

I also fixed the "-3" issue there in case of unlimited default quota.

**Comment by Valdnet** [comment]
@MorrisJobke @PVince81 @skjnldsv Thank you for your concern and thanks for the quick fix 🥇.
