### ISSUE TITLE
API for account registration

### ISSUE THREAD

**Issue by mabkenar** [nextcloud/server#211]
Following [a discussion](https://github.com/nextcloud/android/issues/53) about improving the setup screen for Android client, it would be nice to have an API for streamlined account registration, so that a new user can choose a provider in the the Android client's setup screen and directly register an account with that provider, from within the client. (Thunderbird and Pidgin for example offer the same in-app-account-registration feature for select email and XMPP providers, respectively.)
@jancborchardt @AndyScherzinger

**Comment by mar1u5** [comment]
Maybe we could integrate this one better:
https://github.com/pellaeon/registration

...but i am not really convinced about this feature especially with the provider and android client aspect 😕

**Comment by MorrisJobke** [comment]
This has nothing to do with LDAP ;)

In the past it was only referred to the registration app. Maybe we could somehow integrate this better as a possible capability and then let the android app detect if this is enabled and has proper endpoints?

cc @karlitschek @pellaeon

**Comment by karlitschek** [comment]
interesting idea. not sure how this works in practice because the setup process might be totally different. tos, pricing model, verification,...

**Comment by AndyScherzinger** [comment]
@mabkenar and @jancborchardt's point here is to lower the barrier especially when the Android app is the entry point and the user isn't really familiar with Nextcloud to provide an easy way to get all set.

There are probably three scenarios for a user:
1. login with your own server, address and login data is known
2. sign up for an account with in the app for an instance provided by a provider (ala dropbox)
3. sign up for your own Nextcloud instance which in the brackground would then have to be provisioned, etc, etc.

I am with @karlitschek that this is a bit tricky for tos and pricing model, etc.

1. is covered already
2. would need some kind of a service where we could query providers offering accounts probably with  a freemium model
3. tricky since the might not be possible in real time during the registration process, billing etc. etc.

As stated in the Android issue we might be able to add a filter to the app for a defined nextcloud URL which contains the server address which would enable the Nextcloud Android app to process the URL string, open the login screen and prefill the URL. This way people could send out emails (maybe via Nextcloud) to a user, the user click on the link, chooses the Android app to open the link, types in username and password, and is all set.

**Comment by mabkenar** [comment]
Ok I see the complexities involved. Currently there is not even a standard practice on the registration webpage among different providers. For example [Wint.global](https://wint.global/) uses [this other domain](https://wircon-int.net/cart.php?a=confproduct&i=0) for registration, and yet the actual server is on [this domain](https://ocloud.global/). And [oCloud.de](https://ocloud.de/) uses [this page](https://ocloud.de/products.php) for presenting different plans, and the server is on [this username-dependent domain](http://mabkenar.ocloud.de/).

Given the above mess, even pre-filling the server name by sending a link does not help. 

Therefore this API can be as minimal as "a standardized web address relative to the base server address" on which new users can register a new account. And we can make this an optional feature for providers if they want to participate. But I'm not sure if this is worth the effort.

If no other practical ideas come to mind, we can close this issue.

**Comment by jancborchardt** [comment]
@karlitschek we talked about this in the past thought, you also being a proponent of having 3 (or so) providers listed in the log-in process of the apps (Android, iOS and desktop as well). To make this flow easy, we would need such a registration API.

cc @Gomez as he runs a provider and might give input on how difficult this is to do.

**Comment by pellaeon** [comment]
I look forward to work together on this API, I have created an issue for it pellaeon/registration#41

**Comment by Gomez** [comment]
With this approach a installed nextcloud is needed (with registration app). I more like the idea of this [comment](https://github.com/nextcloud/android/issues/53#issuecomment-228072247) and an API to get a cloud created by a provider.

**Comment by jancborchardt** [comment]
@Gomez as you are a provider, do you maybe want to draft such an API so we know what is needed?

**Comment by Gomez** [comment]
Sure! 
As a first version i would suggest to just post a email and cloud/login name to a custom url of a provider and show the response. 
Would be good to join forces as a team and work on the parts. How is interested?

**Comment by jancborchardt** [comment]
@Gomez how should the password be chosen? Or is this best done by token based auth then? (Problem would be to then connect with other devices)

cc @LukasReschke regarding security aspects.

**Comment by Gomez** [comment]
@jancborchardt Send to the email. It does not solve a instant cloud creation, its just a first step. We can go further from there.

**Comment by rullzer** [comment]
I would strongly discourage getting this stuff into the core. I think that will be a nightmare security wise.

*IF* this is wanted I would propose the following:

1. Create a registration app which exposes a capbibility. So clients can verify if the server supports registration
2. Make the client react to a magic link kind of thingy. So I get an invite from company A. I click on the link it opens the Nextcloud app with server prefilled. It then checks if the capability is enabled and if it is gives me the ability to register.

**Comment by pierreozoux** [comment]
Agree with @rullzer, @Gomez let's discuss about it in https://github.com/pellaeon/registration/issues/41 (and sorry for the delay..)

I'm talking about it again, as we are again discussing about how to implement a SignUp screen for the Qt client.

**Comment by MorrisJobke** [comment]
@skjnldsv Isn't this done nowadays?

**Comment by skjnldsv** [comment]
Yes on https://github.com/nextcloud/preferred_providers :)
