### ISSUE TITLE
Production build not working on IE11

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#21316]
The production build of core/js/dist/main.js is failing on current master/stable19 with IE11 as terser seems to not use quoted properties:

![image](https://user-images.githubusercontent.com/3404133/84039040-f6480d00-a9a0-11ea-94a1-4e75036c5b0e.png)

```
SCRIPT1014: Invalid character
main.js (1005,21360)
```

Might be that the default changed or that this is a dependency update that pulled in the new object with the unicode properties. It works fine with the dev build so I assume that it is terser needs to get the `keep_quoted` setting passed somehow.

**Comment by Yomark1** [comment]
Sorry to ask questions here,  but as my own issue above is closed, does anybody have any pointers how to fix or work around this issue on 19 stable(downloaded from the Nextcloud website)? 
I just grabbed and overwrote the files from core/js/dist/ (master branch - that is the dev build?), and it does not help with the issue. Thank you.

**Comment by juliushaertl** [comment]
There is no fix yet, pointers on how it could be fixed are in my first post.

> I just grabbed the files from core/js/dist/ (master branch - that is the dev build?), and it does not help with the issue. Thank you.

Yes it is not fixed there, but this is most likely also a bad idea, since master might has diverged from the stable 19 release and this can cause various unexpected issues.

**Comment by Yomark1** [comment]
I know it was probably a bad idea(was on my test environment, but I also updated "production" to 19.0.0 because I myself found no issues)  but it was just to see if it fixed the issue and it was indeed only an issue in main.js.  Because you stated that it was fixed in devel, I though you meant in master. 
Sorry, my bad.
 I copied the the part starting with {"Ⓐ":"A","Ａ":"A" .... "ς":"σ"} from main.js from nextcloud 18.06 and placed it in(a slightly different spot, function has changed in) main.js from 19.0.0. That seems to do the trick.

Thank you for you pointer to the solution.
