### ISSUE TITLE
Remove asset pipeline support

### ISSUE THREAD

**Issue by nblock** [nextcloud/server#215]
The asset pipeline support should be removed. See https://help.nextcloud.com/t/asset-pipeline-enabled-leads-to-a-blank-calendar-with-error/1122/5 for details.

**Comment by LukasReschke** [comment]
Some support for this from me, @MorrisJobke and @BernhardPosselt:

1. HTTP 2 solves the problem
2. Broken with apps like calendar and contacts (one of them doesn't work properly) 
3. Breaks randomly
4. Makes your Nextcloud slower (loads different 2 MB on each request)

I'm in favour of making the config switch do nothing for the moment once these problems have all been fixed. It's not like it would really help you anyways… 🙈

**Comment by LEDfan** [comment]
JSXC is also broken with this: https://github.com/jsxc/jsxc/issues/255

**Comment by LukasReschke** [comment]
@schiessle @karlitschek @MorrisJobke @BernhardPosselt Thoughts? My proposal is:

1. Disable the pipeline for the moment. It has been broken since ages in oC as well.
2. Create a ticket to investigate what a simplified less magic pipeline could gain us. (such as by just concat CSS files which would not magically break random stuff)

**Comment by karlitschek** [comment]
I vote for disabling it for now. The benefits are questionable!

**Comment by BernhardPosselt** [comment]
Concating CSS files will actually hurt you more than help with Http 2 btw

The only benefit I see here is minifaction which I doubt will ever work properly (ES6 is quite a big standard)

**Comment by btk999** [comment]
removing the asset pipelining support will cause performance losses in galleryplus - won't it?
i enabled it and the preview generation is much faster in the app...

is there no other solution?

**Comment by BernhardPosselt** [comment]
@btk999 afaik those are two completely unrelated things.

**Comment by btk999** [comment]
possible (sorry - im a beginner) - but maybe @oparoz can tell us more? :)

**Comment by BernhardPosselt** [comment]
@btk999 right, thats only css and js which is kinda broken and like @LukasReschke mentioned even slowing your instance down

**Comment by BernhardPosselt** [comment]
@btk999 @oparoz the gallery app should ship minfied js and css instead. That way you can use whatever tools you want and its significantly faster than the current asset pipeline

**Comment by btk999** [comment]
@BernhardPosselt Thanks!
Did i get it right? if the feature would work, it would speed up the loading (by mixing js + css).
But the feature is broken and therefore it does not speed up the loading but even slows it down?

im excited for the answer of @oparoz - speeding up the galleryplus would be too great!

**Comment by BernhardPosselt** [comment]
@btk999 exactly, in addition it's also broken in that it produces broken output in certain cases :)

**Comment by MorrisJobke** [comment]
> speeding up the galleryplus would be too great!

The asset pipeline will definitely not speed up the gallery app. That must something different. It only should speedup the transfer of JS and CSS files to the browser, but as it is implemented in a weird way it actually slows this part down.

**Comment by oparoz** [comment]
I made the recommendation back on the 8.x cycle as it did noticeably shorten the time it takes for the app to load. Back then HTTP/2 wasn't really an option.
I haven't tested the difference lately, but easy minification is a nice thing to have because without it each app needs to include its own PHP minifier and a configuration switch to allow people to turn it off (when debugging)

**Comment by oparoz** [comment]
@btk999 - The easiest way to speed up the gallery apps is to user Redis for files locking. That's a 10x speed improvement when loading albums, especially large ones.

**Comment by MorrisJobke** [comment]
> @btk999 - The easiest way to speed up the gallery apps is to use Redis for files locking. That's a 10x speed improvement when loading albums, especially large ones.

Also with 8.2.3+? Because I added a fix for DB based file locking in 8.2.3.

**Comment by btk999** [comment]
@oparoz thanks! i already use redis and it is really a performance boost!
But with +45gb photos it is just simply slow - so i will try everything for speeding up the app.

i just wanted to be sure, that the feature does not get removed if it is stil be needed. but as far as ai understood, for asset pipelining this is not the case.

**Comment by oparoz** [comment]
>Also with 8.2.3+? Because I added a fix for DB based file locking in 8.2.3.

[It's slow on stable9](https://github.com/interfasys/galleryplus/issues/53#issuecomment-231522386), so unless the fix has also been added to the newer branches, then it's still an issue.

>But with +45gb photos it is just simply slow 

The size of the collection should have little effect. It's more whether it's accessed via the external storage app and if files locking is using Redis.

**Comment by tomchomiak** [comment]
Hey guys. Thank you for the great platform!

I would suggest leaving it to the admin to decide if they want to enable this feature within the config vs completely disabling it. You can disable it by default, but you should still allow the admin to enable it if they choose.

I do not plan on using the contacts app, calendar app, or many of the other apps. My use case for Nextcloud is strictly file sharing within the office and with clients. That said, I consider performance a better tradeoff vs stability of some of the addon apps.

@LukasReschke  Regarding the concatenation and minification making your Nextcloud slower, I do not see how this could make the front end slower over http 1. Less requests to the server will make the app noticeably faster. The only way I see this slowing things down is server side with php having to concat and minify files on every request, but this can be easily circumvented by the admin with configuring Nginx or Apache to proxy cache the requests.

@BernhardPosselt Although http2 is promising, it is experimental in Apache 2 and with http2 you pretty much have to forget about supporting IE and Safari users http://caniuse.com/#search=http2. Within an office environment, this is a huge downfall as most corporate users are on some version of IE and that version is not always the latest.

All that being said, I ran some tests on a fresh install of Nextcloud 10 running Apache 2 and followed the performance tuning guide in your docs (enabling Redis caching, etc.). And after following the guide to the T, still noticed slow page load for the frontend web interface. Due to the asset pipeline being disabled, the login page, dashboard, and download screen are extremely slow relative to Nextcloud 9. More specifically, i've noticed 10-20 second initial page load times. Followed by 5-10 second page loads for subsequent visits to the Nextcloud instance.

I would expect subsequent visits to be faster due to browser caching, but that is not the case. It's worth mention that I noticed the Cache-Control headers and gzip compression settings within the default Nextcloud .htaccess file are doing more damage than good. The presence of these headers are actually causing Etags to not work. So, with asset pipeline being disabled, subsequent visits to the NewCloud instance or refreshing the screen are just as slow. 

I checked your demo.nextcloud.com headers and you guys are not setting Cache-Control or enabling gzip compression for your demo.nextcloud.com instance. I presume for this reason. However, these headers are set within the default .htaccess file shipped with Nextcloud 10. So at the very least, I would recommend removing these headers from the .htaccess file if you do not plan on re-enabling the asset-pipeline.
