### ISSUE TITLE
Symbolic links in Files

### ISSUE THREAD

**Issue by manu-p** [nextcloud/server#21560]
Although I've been activating and use the "[Link editor](https://apps.nextcloud.com/apps/files_linkeditor)" app, which gives me the possibility to store URLs directly in folders (Files app), I was wondering if it would not be an idea to get a folder/file _option_ which would be "link this in...", the same way you can move or copy a file or folder from one folder to another.

I can do that with the internal link I get from the folder/file's share tab, which I use as an internal link with "Link editor".
The idea is just to do the same, but seamlessly: just right click on the folder/file and choose an option to link it in another folder following the same way as moving or copying elsewhere.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/9440

**Comment by manu-p** [comment]
> Sounds like #9440

Which is closed since may 31, 2018. I guess there's not enough demand on such a feature so far... But I still hope it'll be implemented some day.

**Comment by disenchant** [comment]
This would be a great feature to have. Google's ["Find files & folders with Google Drive shortcuts" help page](https://support.google.com/drive/answer/9700156?hl=en) could serve as a reference that describes the feature as I'm guessing that it ideally would behave like that in Nextcloud.

**Comment by jospoortvliet** [comment]
Some background based on a recent conversation.

# current situation

Currently, Nextcloud has what can be best described as [hard links.](https://en.wikipedia.org/wiki/Hard_link) These are, for example, created when a user has a folder shared with them, and a subfolder or file in that folder is again shared. This happens particularly often with Talk, where a user can share a file or folder in a conversation while users already had access to that file or folder.

It is not visible to users when a file or folder is in multiple locations and they can have different names. Users can also not (easily) create these themselves.

Showing hard links would be a very expensive operation (from a database perspective) and thus is not something we intend to do any time soon.

# Symbolic links

Right now, the Text app can 'link' to a file on Nextcloud. It simply links to the unique file ID and thus only people who have access to the file can see it - a public link is not being used here.

Symbolic links in Nextcloud could follow these same semantics, being just .lnk files that link to the public link URL of the file. The current Link Editor app could simply add a file picker that then creates a "https://mycloud.com/index.php/f/269" link. This would work outside Nextcloud and inside too - by just reloading the page when Nextcloud visits the URL, or opening in a new tab.

This would not work with the previewer/editor and other functions, though, unless they are changed/updated so this is still not a trivial task to fully implement.

# Could symlinks fix the hard link issue?

Maybe Nextcould could be smarter when creating/re-sharing a file. Maybe Talk could, for example, create a symlink instead of sharing a file into a chat when the user picks it from the local system and the participants in the chat already have access to the file. But I'm not sure if this information is readily available or still expensive... Plus, then Talk has to recognize the symlinks and treat them as 'normal' shares, or previews & viewer no longer work.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by b3** [comment]
I do not get why *Showing hard links would be a very expensive operation*? Any idea what is expensive?

Exposing or enabling user to show (file id) and create hard link is IMHO a very good option which should solve this need : having the same file accessible from different location in case where a folder is used by many user (as with group folder for instance).
