### ISSUE TITLE
reindex files in folder from Web UI?

### ISSUE THREAD

**Issue by Riccardomirto** [nextcloud/server#21675]
I have a website hosted by a provider and using a NextCloud site installed on my domain with their software tools - I have no access to the machine and cannot run any command. Is there a way to reindex files in NextCloud folder using the Web UI in NextCloud? 
I would like to recover a previous backup (saved in same server using a file manager offered by the provider) without doing a fresh upload.

Thank You

**Comment by violoncelloCH** [comment]
well the reason for this not being available in the web UI is that occ commands like file re-indexing can take a long time, and those php threads are aborted when executed via web request rather than command line... 
maybe this app can still do the trick for you: https://apps.nextcloud.com/apps/occweb

**Comment by Riccardomirto** [comment]
Thanks a lot for your answer, it solved my problem. I really appreciated.
