### ISSUE TITLE
All Shares Removed After System Power Outage!

### ISSUE THREAD

**Issue by flexy2ky** [nextcloud/server#21709]
I noticed that all shares are removed if server loses power or is shut down. This does not happen if system is rebooted. This is clearly a bug as the shares are supposed to be retained regardless of power supply state. Can this be fixed?

**Comment by gary-kim** [comment]
Could you fill out the issue template? This seems to be a strange situation and may have something to do with your exact setup, especially because Nextcloud is a PHP app meaning that with the exception of cron, no processing is going on until someone requests a page.

https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE/Bug_report.md
