### ISSUE TITLE
No sharing of contact birthdays calendar while sharing an address book

### ISSUE THREAD

**Issue by drupalwonder** [nextcloud/server#2172]
One more once: Is there an option to import the birthdays of the contacts in a shared address book into the birthday calendar?

The contact birthdays calendar (NC 10) works really fine with all contacts in my address book, but if I share my contacts with another nextcloud user he's getting all the contacs (including their birthdays), but the birthdays aren't shown in his contact birthdays calendar even this calendar is switched on. Sharing my birthday calendar (based on my contacts) via abonnement doesn't work while the server's refusing to do so.

Any ideas? Thanks!

**Comment by georgehrke** [comment]
Hm, looking at the code I can tell that shared calendars should theoretically be included.
Can you please run `php occ dav:sync-birthday-calendar` inside the nextcloud folder on your command line and check if the shared contacts are still missing?

**Comment by cemrich** [comment]
I'm experiencing the same issue with a fresh install of Nextcloud 11.0 beta 2. 

I have user1 with an address book shared to user2. User1 is seeing his contacts birthdays just fine. User2 has no own address book but is seeing all contacts of user1. I tried to create an abonnement for user2 to get the birthdays:

- https://my-server-url/remote.php/dav/calendars/user1/contact_birthdays/
- https://my-server-url/remote.php/dav/calendars/user2/contact_birthdays/

But creating either of the abonnements above does not work. A javascript error is thrown:

    https://my-server-url/index.php/apps/calendar/v1/proxy?url=https%3A%2F%2Fmy-server-url%2Fremote.php%2Fdav%2Fcalendars%2Fuser1%2Fcontact_birthdays%2F 422 (Unprocessable Entity)
    https://my-server-url/index.php/apps/calendar/v1/proxy?url=https%3A%2F%2Fmy-server-url%2Fremote.php%2Fdav%2Fcalendars%2Fuser2%2Fcontact_birthdays%2F 422 (Unprocessable Entity)

Unfortunately I'm not able to run any scripts because I use a shared hosting environment that's pretty locked down.

This issue may be related to #410

**Comment by cemrich** [comment]
The issue persists with the final 11.0 release. 

However, I found out that only birthdays of contacts created by user1 do not show up for user2. Once user2 edits the same contact (I edited the birthday), its birthday is showing up just fine. After that, birthday sharing is working as expected for all new contacts. 

This is a very strange behavior and would suggest some initialization problem when creating user2. I created this user **after** sharing the address book with the corresponding group, so maybe that's the whole cause of this error.

**Comment by cemrich** [comment]
I just experimented with creating new users of the group I shared the address book with. Every newly created user does not see any contact birthdays. Once the new user does edit any field of a contact, this contacts birthday does show up.

**Comment by georgehrke** [comment]
> I tried to create an abonnement for user2 to get the birthdays:
> - https://my-server-url/remote.php/dav/calendars/user1/contact_birthdays/
> - https://my-server-url/remote.php/dav/calendars/user2/contact_birthdays/
> But creating either of the abonnements above does not work. A javascript error is thrown:

That won't work, because:
1. you can only add ics files as subscription. `https://my-server-url/remote.php/dav/calendars/user1/contact_birthdays/` is a caldav-endpoint
2. `https://my-server-url/remote.php/dav/calendars/user2/contact_birthdays/` is a private calendar of user2 and obviously not readable for user1 and vice versa.

> Once user2 edits the same contact (I edited the birthday), its birthday is showing up just fine.

Just to clarify things:
- user 1 shared his address book with user 2
- user 2 is editing a contact in the shared address book or creating a new one
- the edited / created contact shows up in the birthday calendar

Is that correct?

**Comment by cemrich** [comment]
> Just to clarify things:
>
> - user 1 shared his address book with user 2
> - user 2 is editing a contact in the shared address book or creating a new one 
> - the edited / created contact shows up in the birthday calendar
>
> Is that correct?

Yes, exactly.

**Comment by godfuture** [comment]
I just noticed that the birthdays of my adressbook do not show up on the device of the person I have shared with.

Is there any solution planned?

**Comment by nonplusnl** [comment]
Bump. I notice too that birthdays in shared addressbooks do not show up in birthday calendars. Not even in my own. My setup: I have i) my own addressbook, and ii) an addressbook I share within my household. My other household members all have their own addressbook and the shared one from my account.
The birthdays in everybodies own private addressbooks show up in the respective birthday calendars as they should. The birthdays of contacts in the shared addressbook however, show up nowhere. Not even in my own birthday calendar, while I am the owner of the shared addressbook. 
Running NextCloud 14.0.4. I expect this has been around for long (also given the time this issue has been open), but I only discovered it today as I missed a birthday yesterday. 
Would be great if this could be fixed.

**Comment by Schneehexe** [comment]
I tried "php-cgi7.2 occ dav:sync-birthday-calendar"
Some more Birthdays are now visible for the user I shared, but all now new visible contacts where edit after I make the new user.

**Comment by Schneehexe** [comment]
In a test environment with Nextcloud 15.02 and the newest apps .the same behavior is shown.

**Comment by Schneehexe** [comment]
Download the Contacts, delete the Adressbook, make a new adressbook (all at main user) and import the data dosn't help also.

**Comment by Schneehexe** [comment]
Probably by my attempts by deleting and reloading the address books to create birthdays in the shared birthday calendars, I now have in my own birthday calendar all the entries three times in it.
If contacts are removed or address books are deleted, the entries from the birthday calendars are not removed. But if a calendar is reloaded, the existing entry is added again.

**Comment by Draghtnod** [comment]
I may have had a related issue. A contacts birthday of a shared calendar was not showing up in the birthday calendar. Editing that contact failed as well.
`php occ dav:sync-birthday-calendar` returned with Error `Calendar object with uid already exists in this calendar collection. `
So I added some debug output to that error and found out that some contacts were present in multiple address books with the same UID. There were even different versions of one contact spread across different address books. Deleting the duplicates solved all issues. The contacts are editable again and show up in all birthday calendars. I have no clue what caused the duplicates. Maybe a database upgrade bug?

**Comment by MorrisJobke** [comment]
@georgehrke I guess this is nothing for 16, right?

**Comment by georgehrke** [comment]
@MorrisJobke Indeed

**Comment by fsdfasf** [comment]
I also have double one and i think the IUD`s maybe come from exporting contact from one account and importing them in an other?

**Comment by fsdfasf** [comment]
OK full reproduce scenario! 

**How to create a double contact uid.** 
1. Export a contact (with a birthday off course)
2. import it in a different address book
3. Run dav:sync-birthday-calendar Et voila error. :)

**Fix** (i think since i did al lot):
Cleanup double uid in:
1. ownc_calendarobjects, just delete all the double records (they will be regenerated)
2. ownc_cards, keep one else our contact is gone! the the address book id for which address book. 
3. Run dav:sync-birthday-calendar , there should be no error and the birthdays are restored.

So the reason of the broken calender is that nextcloud doesn`t generate a new uid at import. But i think there are also reasons the keep the same uid.

**Comment by maphy-psd** [comment]
I think this is related to: #29374 

See my [answer](https://github.com/nextcloud/server/issues/29374#issuecomment-968334379).

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by maphy-psd** [comment]
with version 24.0.8 the issue persists.

in [#29374](https://github.com/nextcloud/server/issues/29374#issuecomment-1207424969) i wrote a possible fix. but the developers have to decide if this will work.

**Comment by szaimen** [comment]
Thanks for the feedback! Can you please open a PR with your patch? That makes discussions on the topic much easier. Thanks a lot! :)

**Comment by Tazzios** [comment]
> OK full reproduce scenario!
> 
> **How to create a double contact uid.**
> 
>     1. Export a contact (with a birthday off course)
> 
>     2. import it in a different address book
> 
>     3. Run dav:sync-birthday-calendar Et voila error. :)
> 
> 
> **Fix** (i think, since i did al lot):
> 
>     1. Cleanup double uid in ownc_calendarobjects, just delete all the double records (they will be regenerated)
> 
>     2. Cleanup double uid in ownc_cards, keep one else our contact is gone! the the address book id for which address book.
> 
>     3. Run dav:sync-birthday-calendar , there should be no error and the birthdays are restored.
> 
> 
> So the reason of the broken calender is that nextcloud doesn`t generate a new uid at import. But i think there are also reasons the keep the same uid.

Did a retest on NC26.0.1 , at step 2 both have the same UID, but at step 3 it does not give a problem. :)

There was also an other birthday sharing bug in NC25 which why i went to NC26 I only cannot find the issue at the moment.
