### ISSUE TITLE
Don’t show spinner in personal settings content

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2198]
In the personal settings, there’s a spinner shown in the center of view. This is confusing since the elements in the viewport area already loaded anyway, and the spinner is not needed.
It actually makes the software seem slower than it is in this case. Can be removed.

cc @nextcloud/javascript

**Comment by ChristophWurst** [comment]
screenshot? :-)

**Comment by jancborchardt** [comment]
It’s too fast :D open personal settings and you will see it. It’s just directly in the middle.

**Comment by skjnldsv** [comment]
![capture d ecran_2016-11-18_16-39-48](https://cloud.githubusercontent.com/assets/14975046/20435768/a418a08c-adad-11e6-9f75-3808062477dd.png)

**Comment by jancborchardt** [comment]
@skjnldsv @ChristophWurst if it doesn’t work then maybe place it next to the header? Or in a different container and overlay it? But it shouldn’t overlay the whole content area. :)

**Comment by skjnldsv** [comment]
We should not use table, this hould do the trick 😄 
It's taking the whole area because the loading icon itself has a position absolute and center itself in the full dimension of his parent. Parent, which is set by a position relative on the icon-loader class. But if there's no direct parent, it will take the first positionned element it can found as a direct container.

**Comment by schiessle** [comment]
fix is here:  https://github.com/nextcloud/server/pull/2219

**Comment by MorrisJobke** [comment]
New fix is in #2316
