### ISSUE TITLE
Emails from templates not displaying correctly in Zimbra

### ISSUE THREAD

**Issue by pielonet** [nextcloud/server#22016]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Do action that triggers a notification by email (e.g. share a file with some other user)
2. The email received appears as "blank" in Zimbra.
3.

### Expected behaviour
The email should appear with all its contents.

### Actual behaviour
Tell us what happens instead

The issue was already reported here : https://help.nextcloud.com/t/blank-html-notification-email-in-zimbra-webmail/66761

And the fix worked also for me.

So could you please modify EmailTemplate.php and remove "height: 100%"

/lib/private/Mail/EMailTemplate.php
```
...
<table class="body" style="-webkit-font-smoothing:antialiased;Margin:0;background:#f3f3f3!important;border-collapse:collapse;border-spacing:0;color:#0a0a0a;font-family:Lucida Grande,Geneva,Verdana,sans-serif;font-size:16px;font-weight:400;height: 100%;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;width:100%">
...
```
![Capture d’écran_2020-07-27_12-02-15](https://user-images.githubusercontent.com/15911394/88532777-797efa00-d005-11ea-89b5-77316a066f23.png)

**Comment by szaimen** [comment]
I think this was fixed in the meantime. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
