### ISSUE TITLE
Visual glitch: managing groups nearly impossible

### ISSUE THREAD

**Issue by cloudraiser** [nextcloud/server#22283]
![img002](https://user-images.githubusercontent.com/54961496/90515004-46daa400-e162-11ea-8644-f3486af9c77a.png)
![img001](https://user-images.githubusercontent.com/54961496/90515007-47733a80-e162-11ea-8ba9-d8d64a2ca187.png)

Managing groups which are supposed to be approved to use the Deck, are nearly impossible to manage. Select/Unselect or identify groups is difficult or impossible. Not all available groups are shown.

The bug I try to describe is as well a visual glitch as a functional one, in terms of finding all existing groups.

Thx guys for this fabulous app, which I like a lot! Please consider improving the visualisation.

**Comment by cloudraiser** [comment]
Thank you Julius, much appreciated.

**Comment by carlcsaposs** [comment]
This issue inspired me to take a look at other multi-select fields across [nextcloud/server](https://github.com/nextcloud/server/) and the featured Nextcloud apps.  Here's what I found.

# 1. Areas for Multiselect usability improvements
## 1a. Deselect requires searching or scrolling
If a Multiselect requires search or limits the number of results shown, an option has to be searched for before it can be deselected

For example, in Apps > App (e.g. Deck) > Limit to groups, the Multiselect does not show more than 5 groups at once.
![limited-results](https://user-images.githubusercontent.com/97926121/169196902-3a7c918a-98cd-45f5-94fe-26ffdde335aa.png)

## 1b. Viewing many selected options requires searching or scrolling
Using the same example as above (in Apps > App > Limit to groups), if many options are selected, it is not possible to view the selected options unless the user can guess the text and search for them
![view](https://user-images.githubusercontent.com/97926121/169196928-200f3328-71e6-4c5d-b241-28d6e5fe573d.png)

## 1c. Unclear when number of results is limited
Using the same example as above, it is unclear to the user that the number of groups is limited to 5 and that selecting other groups requires search.  Quoted from the [original comment](https://github.com/nextcloud/server/issues/22283#issue-681027977) of this issue:
```
Not all available groups are shown.

The bug I try to describe is as well a visual glitch as a functional one, in terms of finding all existing groups.
```

## 1d. Select and deselect hover state are identical
When hovering over an option, it is not possible to determine if clicking the option will select or deselect it.  (A lighter checkmark is shown in both cases)
![hover](https://user-images.githubusercontent.com/97926121/169197084-3c325f35-62f1-47df-b6cd-d9b5331eceaf.png)

# 2. Areas for improvement for specific Multiselects
## 2a. Too narrow: Apps > App (e.g. Deck) > Limit to groups
Options are truncated almost immediately and long group names are truncated in dropdown
![long](https://user-images.githubusercontent.com/97926121/169197097-4c8eb4e4-e117-426d-9301-edeb634cbbb8.png)

## 2b. Limited to 5 results: Apps > App (e.g. Deck) > Limit to groups
Other Multiselects for selecting groups do not have limited results (e.g. Settings > Administration > Admin privileges > Support)
![unlimited](https://user-images.githubusercontent.com/97926121/169197117-a0ff02ee-8e10-446e-8c83-e9f90306a314.png)

## 2c. Inconsistent with other Multiselects: Settings > Administration > Basic settings > Nextcloud announcements
Doesn't use checkmarks and has different selected & hover state
![inconsistent](https://user-images.githubusercontent.com/97926121/169197151-b9e5d2c7-5c46-4a0a-9489-d43089e3d7d4.png)

# 3. Potential solutions
## 3a. Show selected options on top of list (when search field is empty)
Solves #1a, 1b
Issues: Ordering might be confusing after previously selected elements are deselected
Example: GitHub labels
Selected options shown on top of list when search field is empty
![github-labels](https://user-images.githubusercontent.com/97926121/169197170-34a37d4f-f143-4fec-a7ab-7cf7f8b5bad4.png)
Example: Approval workflows
Selected options shown on top of list when search field is empty & on bottom otherwise
![approval](https://user-images.githubusercontent.com/97926121/169197195-38439718-11bc-4fb4-89a2-6b8d720d1bdf.png)

## 3b. Show selected options outside of Multiselect
Solves #1a, 1b
Example: Share sidebar
![share](https://user-images.githubusercontent.com/97926121/169197212-cbee408c-e9e1-441f-bb08-05dedb135b43.png)
Example: Add people to Nextcloud Talk chat room
![talk](https://user-images.githubusercontent.com/97926121/169197230-23e880cb-0564-4805-a7a4-690400ed9873.png)
Issues: Would require pop-up dialog or more screen space, which could be an issue for small Multiselects (see image below for example)
![small](https://user-images.githubusercontent.com/97926121/169197247-50816ee5-1478-4c74-a837-4e18d743f587.png)

## 3c. Use "X" icon for deselect hover state (instead of checkmark)
Solves #1d

## 3d. Show extra item in list of options when results are limited or searching is required
Solves #1c
Example: Approval workflows
![extra](https://user-images.githubusercontent.com/97926121/169197269-e8b39da0-1944-4f94-a1fd-d97c25ed95ef.png)

## 3e. For #2a, put Multiselect on its own line
Solves #2a

## 3f. For #2b, list all groups instead of limiting to 5
Solves #2b
Issues: Would this cause a significant delay if there were a large number of groups?  If so, should the other Multiselects where groups are selected have a limited number of results?

## 3g. For #2c, use standard component
Solves #2c

-----
# Feedback wanted
If improvements to the Multiselect component are desired, I welcome & would appreciate any design feedback.

I'd be happy to submit some PRs once any ideas (including ideas not listed in this comment) for design improvements are green-lit.

Also, please let me know if I should split this up into multiple issues--I wasn't sure how to organize it since it seems like some of these things are related.

**Comment by stefan-niedermann** [comment]
cc @nextcloud/designers

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
