### ISSUE TITLE
Allow to pass audit log to syslog

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22292]
The admin_audit app can only log to a file at the moment https://github.com/nextcloud/server/blob/7870ca06637453f4e72dbd67edbfb3603d813196/apps/admin_audit/lib/AppInfo/Application.php#L103

Ideally it should be possible to also send the log messages to the configured syslog server.

**Comment by dragospe** [comment]
I will second this issue, and add that Nextcloud appears to make it difficult to safely consume the log file using rsyslog. 

It seems that, at least with my setup, the log file mode is set to `0640` every time the log is written to with the owner `nginx:nginx`. 

This complicates consuming the log; either I need to run a rsyslog daemon as the user nginx or root, or otherwise add the syslog user to the nginx group. Neither is ideal.

Allowing the admin_audit app to set the appropriate user, group, and permissions (or preventing it from changing them each time the file is written to) would be helpful.

**Comment by wiswedel** [comment]
or even more flexible: have the same output config options like for the Nextcloud log (file, syslog, systemd => https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html)

**Comment by Pytal** [comment]
Closed by https://github.com/nextcloud/server/pull/30763
