### ISSUE TITLE
Dashboard backdrop filter in firefox

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22398]
From https://github.com/nextcloud/server/issues/20930

> - [ ] Look into fixing backdrop-filter for Firefox https://codepen.io/iamvdo/pen/VLOGdw
> - [ ] Nice fancy blur/transparency effect for the hover/focus effect of the widget entries would be nice too, instead of just grey

**Comment by jancborchardt** [comment]
I think it might not really be possible to do the backdrop filter in Firefox for our case.

The example at https://codepen.io/iamvdo/pen/VLOGdw duplicates the image, which in our case would not really be feasible as we would need to duplicate the background for each widget and button, and position it properly.

And of course the filter at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter is only blurring the element itself.

It might make more sense to just wait for Firefox to implement it. What do you think @juliushaertl @skjnldsv?

**Comment by jancborchardt** [comment]
This is still disabled by default in Firefox, but now works once `layout.css.backdrop-filter.enabled` is enabled manually. For further tracking there’s the upstream issue at: https://bugzilla.mozilla.org/show_bug.cgi?id=1578503

So yeah, we should simply wait for it to land per default in Firefox, especially since we had 0 people saying anything about it missing. Closing it here.
