### ISSUE TITLE
File templates

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22426]
We have custom template handling implemented in Collabora. Now it would generally make sense to have a unified template handling so that other apps as text, ONLYOFFICE or Collabora could use the same mechanism and the template management for admins and users can be unified.

I'll update this with some more details once I find my notes on the API proposal I already scribbled a while ago.

cc @rullzer

**Comment by jancborchardt** [comment]
Design-wise, this would be integrated with the "+" menu in Files:
![image](https://user-images.githubusercontent.com/925062/104187938-cb330980-5418-11eb-8bb3-65542590794a.png)

The bottom entries are registered by apps, and would get templates.

On clicking the entries, instead of triggering an input for the file name, a modal window would open for the second step. In that modal you can put in the document name on the top, and it will show a list of available templates, with "Blank" as the first entry which will give you just a normal empty document, like now.

Possible templates are:
- New text document (Text app, Markdown)
  - Meeting notes
  - Project plan
- New document (Collabora, odt)
  - Letter
  - Curriculum Vitae
- New spreadsheet (Collabora, ods)
  - Invoice
  - Reimbursement form
- New presentation (Collabora, odp)
  - Product presentation
  - …

I will check on what templates other solutions offer, @skjnldsv. :)

**Comment by juliushaertl** [comment]
@jancborchardt Open questions from my call with @skjnldsv 

- For new users a templates directory would be added by the example files, how should existing users become aware of the new feature. Should we automatically create such a folder for each user? Should we show a notification and give them the option to create it with the example files?
- Where should the templates folder setting be located?

**Comment by jancborchardt** [comment]
> For new users a templates directory would be added by the example files, how should existing users become aware of the new feature. Should we automatically create such a folder for each user? Should we show a notification and give them the option to create it with the example files?

Right, so this was also sort of my question in the call – and I’d be interested in @karlitschek’s take. From my view we have the following requirements:
- It should "just work" and you shouldn’t need to enable anything beforehand
- We don’t want to automatically add files or folders into people’s files as that is invasive
- There might be more templates in the future, possibly a lot (like in Google Docs, macOS, Dropbox Paper etc)
- People’s own templates are more important than ours, so if they already have some, ours should not drown out the people’s own ones

This is why I was talking about "having it in the backend". Cause e.g. macOS Pages or Google Docs have a ton of templates, but not a "Templates" folder with all of them.

**So we could have a "templates" folder centrally in the code, and only if you do go through the file creation flow it would actually copy the template that you used into the "Templates" folder of your account (and create the folder if it does not exist yet. This can also serve as a "Templates you used before" function. And there would be no setting.**


> The templates folder would just be called "Templates", right? We would also not have any translation if it is coming from the example files.

On desktop this is usually localized:
- Ubuntu: Templates / Vorlagen https://help.ubuntu.com/stable/ubuntu-help/files-templates.html.de
- macOS: My Templates / Meine Vorlagen https://qastack.com.de/apple/39827/where-are-microsoft-office-for-mac-my-templates-stored

So I would say while we call it "Templates" by default, we should indeed localize it as well. Otherwise this is very strange for people who do not know English. (Especially since it _will_ be localized in the "Choose a template" modal.)

**Comment by karlitschek** [comment]
> > For new users a templates directory would be added by the example files, how should existing users become aware of the new feature. Should we automatically create such a folder for each user? Should we show a notification and give them the option to create it with the example files?
> 
> Right, so this was also sort of my question in the call – and I’d be interested in @karlitschek’s take. From my view we have the following requirements:
> 
> * It should "just work" and you shouldn’t need to enable anything beforehand
> * We don’t want to automatically add files or folders into people’s files as that is invasive
> * There might be more templates in the future, possibly a lot (like in Google Docs, macOS, Dropbox Paper etc)
> * People’s own templates are more important than ours, so if they already have some, ours should not drown out the people’s own ones

For new users this feature is obvious because we ship example templates. For existing users it is indeed hard to discover. But we will have the setting in the backend to specific the used name and location of the template folder. We can add a short explenation text to it. So users can discover it like that. It's not an unusual situation. We always introduce new features that existing users have to find by looking around in the settings or the UI. Thats how it is.


> 
> This is why I was talking about "having it in the backend". Cause e.g. macOS Pages or Google Docs have a ton of templates, but not a "Templates" folder with all of them.
> 
> **So we could have a "templates" folder centrally in the code, and only if you do go through the file creation flow it would actually copy the template that you used into the "Templates" folder of your account (and create the folder if it does not exist yet. This can also serve as a "Templates you used before" function. And there would be no setting.**

I think this is too complicated. If there is no template folder set or found then the feature just doesn't show any templates until a users sets a folder and puts file in it. I think this acceptable.
I would not do any special magic as mentioned above.


> > The templates folder would just be called "Templates", right? We would also not have any translation if it is coming from the example files.
> 
> On desktop this is usually localized:
> 
> * Ubuntu: Templates / Vorlagen https://help.ubuntu.com/stable/ubuntu-help/files-templates.html.de
> * macOS: My Templates / Meine Vorlagen https://qastack.com.de/apple/39827/where-are-microsoft-office-for-mac-my-templates-stored
> 
> So I would say while we call it "Templates" by default, we should indeed localize it as well. Otherwise this is very strange for people who do not know English. (Especially since it _will_ be localized in the "Choose a template" modal.)

Sure. Good idea to have the option to localise it. If possible in the the given time.

**Comment by skjnldsv** [comment]
> I think this is too complicated. If there is no template folder set or found then the feature just doesn't show any templates until a users sets a folder and puts file in it. I think this acceptable.

Same, especially because the technical implementation of such said backend would be far more complicated.
If we want, and if the user have no Template folder, we could have an entry in the 3 dots menu saying "Create template", that create the template folder with a Readme in it?

**Comment by jancborchardt** [comment]
> If there is no template folder set or found then the feature just doesn't show any templates until a users sets a folder and puts file in it. I think this acceptable.

Ok, understood. We need to keep in mind that this however makes the feature really hard to discover for existing users who do not have a Templates folder (probably most do not).

> If we want, and if the user have no Template folder, we could have an entry in the 3 dots menu saying "Create template", that create the template folder with a Readme in it?

@skjnldsv seems ok as an intermediary solution, although not as nice a flow. Would be called "Set up templates" and just create that whole folder incl the templates?

**Comment by azul** [comment]
Hi y'all,

Great to see this coming together. I had a somewhat different vision for templates that might complement this later on:

### Folder specific templates
Some templates make most sense when inserting a file in a specific folder. Say you have a template for meeting notes of a particular group. You'd be using this template in the groups "meeting notes" folder most of the time.

If the template was defined inside the folder - say in a ".templates" subfolder or as a ".md.template" file it would be shared and copied alongside the folder and only affect the folder ( and maybe its subfolders ).

As I said... this is maybe complementary to the per user templates this issue is discussing. It could be added in a separate app or as part of the collectives app we are working on. In order for this to work we'd need a hook that allows apps to specify templates to be used given the folder the user wants to create a file in.

@jancborchardt what do you think about the UX of per folder templates? How could they be done in a way that is useful rather than confusing?

**Comment by jancborchardt** [comment]
@azul for the start, we tried to make it most compatible with what existing systems do – that is a "Templates" folder with the files in it, and the integration in the "New file" menu.

So for the case you describe, one would simply place that template also in the "Templates" folder. The drawback would be that the template shows up in all other creation flows too, but beneficial is that it’s more simple and obvious.

(E.g. I would have a template for "Design review call.md" – yeah I only use that in the "Design → Design review calls" folder, but still it would show up otherwise when I create a "New text document".
To alleviate that, we could in the future check which templates are often used and sort it by that, which could also take into account the specific folder. That might be a bit more generally useful?)

cc @juliushaertl

**Comment by azul** [comment]
@jancborchardt I understand your points. We'll probably look into per collective templates in the collectvies app since it's mostly about sharing between multiple people. Cluttering other peoples main templates seems too intrusive. We can see how that goes.
