### ISSUE TITLE
Feature request: do not overwrite custom .htaccess content

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#22473]
I'd like to ask for a small improvement in NC server - do not overwrite custom .htaccess content during upgrade. Let me provide an example:

One of my NC installations is used to store sensitive documents of company; therefore, I added a few lines of code into .htaccess file to ensure that users can only access files from office computers. In other words, if IP is not whitelisted, it gets "Forbidden" error. I'd like NC to offer this feature by default, but I have no bit problems writing .htaccess code manually.

The only problem is that NC overwrites .htaccess file during every update, and I need to manually re-add custom code. Not the biggest issue in the world, but it still bugs me a lot.

Would it be possible to copy custom content from old .htaccess to new .htaccess during upgrade? I realize it might be difficult to scan and parse custom code, so maybe NC could support some type of pattern? For example, if user enters these lines into file:

```
###start_of_custom_code_for_nc
some custom code goes here...
###end_of_custom_code_for_nc
```

it would be super-easy for NC upgrade wizard to identify, extract, and transfer custom code into new .htaccess. Of course, it's just an idea, and if someone has a better one for preserving custom code, I'm listening!

**Comment by NA1144** [comment]
if you have (root)access to your Server maybe you should try this.
Use the vhost file or the main config file of your webserver for Access Control not your .htaccess file
Refer to the official documentation
https://httpd.apache.org/docs/2.4/howto/auth.html
https://www.linode.com/docs/web-servers/apache-tips-and-tricks/apache-configuration-structure/
you can also take other measures that offer additional protection for Access Control with IPTables (be carefull with that !!)

**Comment by toxpal** [comment]
Yes, I do have full root access. Thanks for the info, will try it.

**Comment by datacosmos** [comment]
IMHO this is really a problem! There are quite a lot of people which run nextcloud on a hosted server - and these people do not have access to the webservers configuration files!  Similar issues come up every once and a while and the only suggestion is to have some edits in vhost config files.  
For shared hosting this is not an option! If I have overseen something here - please accept my apologies...

And to make things even worse, when you have the ONLYOFFICE integration the updater **crashes**, due to missing php_value memory_limit 512M settings in - guess where? .htaccess !

And from Version 18 on you get integrity check warnings. For shared hosting one cannot assume to have absolutely no changes in whatever way in the directory.... E.g. Some hosters create log files in the same directory if this is on a configured subdomain.

Perhaps in these case we could have a "runs-on-shared-hoster" setting, where you have the possibility to allow some files and dirs to be changed....

Otherwise just say clearly on the first step of the installation "Warning: do not to use on shared webhosting"

**Comment by bwurst** [comment]
We operate a shared hosting server and some of our customers run nextcloud.

On every update, the .user.ini (don't talk about PHP settings in .htaccess, who the heck runs mod_php nowadays on shared hosting?) is overwritten by a version that does not set memory_limit="512M" and after upgrade nextcloud complains about wrong setting of memory_limit. This is ridiculous and I do not have a workaround for this. Must insert this settings after every upgrade.

**Comment by toxpal** [comment]
Hopefully, NC devs will take a look at this problem because I'm sure it's really easy to implement such feature. All other CMSes (WrdoPress, etc.) use this technique since the beginning.

**Comment by acsfer** [comment]
I was having this problem too, my only solution was to load config **directly into apache** until this is solved...

**Comment by szaimen** [comment]
Sry but we will not do this. Please adjust your apache conf yourself to apply all needed modifications.
Otherwise A much more reasonable attempt is this: https://github.com/nextcloud/server/issues/19935#issuecomment-642279946

**Comment by dgrothaus-mc** [comment]
> Sry but we will not do this. Please adjust your apache conf yourself to apply all needed modifications. Otherwise A much more reasonable attempt is this: [#19935 (comment)](https://github.com/nextcloud/server/issues/19935#issuecomment-642279946)

I disagree. The solution you provided is about memory limit and PHP settings.
We host several Nextcloud instances on a managed server without root access and without access to the vhost files. The provider allows to change the used PHP version by setting it in the .htaccess file. Without that setting it uses the default PHP version for that vhost and that version vastly differs based on the main software used by the customer (Blog, Shop, CMS, Helpdesk).

**Comment by hkcomori** [comment]
I faced the same problem. Hope this issue will be reopen.

How about changing the specification to write the user defined settings separately in .htaccess_user?
The `occ maintenance:update:htaccess` would concatenate its contents to the end of the .htaccess.

This way, there is no need to parse the .htaccess file, just simply merge the files.
