### ISSUE TITLE
Nextcloud Text & Rich workspaces support in Settings

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22654]
I'd love to be able to call [Nextcloud Text](https://github.com/nextcloud/text/) or add rich workspaces in each section of `/index.php/settings/user`
so I can better track my personal settings by leaving notes for myself.  Especially useful for admins or anyone who must recall how they configured specific functionality.  Various settings are found in various places depending on the app, but easiest way to track what I'm configuring would be by writing text notes from within Settings itself, perhaps optionally at the bottom of each section.  Markdown support a plus.  This is a request for making it a bit easier to navigate through my settings, but in no way a priority.  Thanks for considering.

Tricky to remember where all the settings and options are within these choices for the User.  Same with Administration.
![image](https://user-images.githubusercontent.com/1787238/92413235-01c3e500-f104-11ea-9f28-a27809b2576e.png)

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
