### ISSUE TITLE
Integration with Discourse

### ISSUE THREAD

**Issue by AndrewMorsillo** [nextcloud/server#22786]
I’m using NextCloud and Discourse via Cloudron. It would be nice if Discourse integrated with NextCloud, even if it was only to make the “external site” embedding work properly. 

Having a feature packed discussion system like Discourse integrated with NextCloud feels like the “missing link” in NextCloud to myself and the other users of our instance. 

A quick search indicates that it should be possible [embed discourse comments](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) and [topic lists](https://meta.discourse.org/t/embedding-a-list-of-discourse-topics-in-another-site/125911) but it seems Discourse isn’t really designed for any sort of tighter integration so I’m not sure exactly what’s possible here.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by jospoortvliet** [comment]
You looked in the app store? https://apps.nextcloud.com/?search=discourse -> there's certainly more possible, but that should probably be done in an app. Perhaps the discourse integration app could benefit from an issue that details integration possibilities, or even code contribution. I'll close this here, not because it is a bad idea but because I think this isn't the right place for such rather vague ideas. Best put it in the repo of one of the apps that already do things like this. I suggest https://github.com/eneiluj/integration_discourse

**Comment by AndrewMorsillo** [comment]
Oops, sorry, not sure how I missed that. Thanks for pointing it out and sorry for the extraneous issue.
