### ISSUE TITLE
Custom theme color per user

### ISSUE THREAD

**Issue by pixelyo** [nextcloud/server#22872]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I can't choose a custom theme color per user. I would like that every user could choose their own custom theme color. Kinda like in the windows setup.

**Describe the solution you'd like**
A user could go to his `Settings > Personal info`  and select a custom theme color. (Just like the admin can right now in `Settings > Administration > Theming > Color`)

The color would be used as the primary color when the user is logged in.

This feature could also be made optional to let the admin decide, whether the custom user color setting should be available to the user. (Maybe as a checkbox next to the instance theme color)

**Describe alternatives you've considered**
Giving the user only to choose from a selected amount of colors could be an alternative.

**Additional context**
If the user doesn't want to select a different theme color, he will have the instance theme color set by the admin.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
