### ISSUE TITLE
share link should also copy the readable file name

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#23050]
**Issue**
share link copies only the URL into the buffer. 
Usually this link will be pasted into another document but without the human readable file name the information is of limited use.
**feature request**
instead of only copying the URL add also the filename 

it would obviously very advantageous if the 2 string above could be inserted directly into slack or HTML Mails avoiding entering the URL and text manually

slack for example uses this widget
![image](https://user-images.githubusercontent.com/6248560/94273153-4e9d1d80-ff44-11ea-840b-1564766f7a0a.png)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kitzler-walli** [comment]
This has to be an optional setting as it would break a lot my daily workflows if I would have to remove the filename after copying the public link to a file every time.

**Comment by szaimen** [comment]
I think what you are actually looking for is this: https://apps.nextcloud.com/apps/sharerenamer
Correct me if I am wrong.

---

Otherwise: As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
