### ISSUE TITLE
"Reason to use Nextcloud in your organization"" looks broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#23134]
I just saw the "Reason to use Nextcloud in your organization" document we link to on the personal settings page for the first time.

Some pages look broken, for example the second one (others are affected as well):

![image](https://user-images.githubusercontent.com/1589737/94912108-7130b880-04a7-11eb-9321-ec04e3bbc131.png)

When I download it as PDF everything looks fine.

Tested on conference.nextcloud.com

**Comment by nursoda** [comment]
If the PDF is fine when displayed with a local viewer program, this seems to be a CODE issue since you opened it with Collabora. Try with the PDF app or OnlyOffice.

But let me add a note that as admin I'd like to be able to suppress the button. A config.php entry would be sufficient, but at least docs.nextcloud.com doesn't yield such a switch.

**Comment by schiessle** [comment]
Seems like in the final NC20 version we open it with a PDF viewer in which it looks fine
