### ISSUE TITLE
Argument 2 passed to OCA\UserStatus\Controller\UserStatusController::setCustomMessage() must be of the type string, null given

### ISSUE THREAD

**Issue by SbloodyS** [nextcloud/server#23332]
### Steps to reproduce
1.modify the status

### Actual behaviour
Although the status was modified successfully. But an error was reported, and there was an error log

### Server configuration

**Operating system:ubuntu 16.04

**Web server:Nginx

**Database:Mysql

**PHP version:7.4.11

**Nextcloud version:20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:Updated from nextcould 19

**Where did you install Nextcloud from:Docker compose

### Client configuration
**Browser:Chrome

**Operating system:Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Exception: Argument 2 passed to OCA\UserStatus\Controller\UserStatusController::setCustomMessage() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 169
/var/www/html/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\UserStat ... {}, "setCustomMessage")

/var/www/html/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main("OCA\\UserSt ... r", "setCustomMessage", OC\AppFramew ... {}, { action: nu ... "})

/var/www/html/ocs/v1.php - line 88:

OC\Route\Router->match("/ocsapp/app ... m")

/var/www/html/ocs/v2.php - line 24:

require_once("/var/www/html/ocs/v1.php")</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
There was an error saving the status
```
</details>

**Comment by sharidas** [comment]
Verified in the master branch, it does throw issue if the custom message is not set and user clicks the `Set status message`. One quick solution is to allow empty message by allowing empty (i.e null in this case) https://github.com/nextcloud/server/blob/master/apps/user_status/lib/Controller/UserStatusController.php#L138. In which case the user_status table will have `custom_message` as NULL. 

It might look a little annoying if the empty message is causing error message shown up as shown below:
![nc_error](https://user-images.githubusercontent.com/3600427/95771849-652fcc80-0cd9-11eb-94da-de994ea5bb07.png)

Let me know if this makes sense?

**Comment by SbloodyS** [comment]
That's very helpful. Thanks

**Comment by fancycode** [comment]
From what I understand, this is still an issue - at least I didn't see a commit fixing the issue.

**Comment by DJ-3ncoder** [comment]
I am having the same error on the same software-configuration!
It is still an issue, @sharidas just told how it would be possible to fix but nobody fixed it as I understood.

**Comment by Jawn78** [comment]
Same here 
Exception: Argument 2 passed to OCA\UserStatus\Controller\UserStatusController::setCustomMessage() must be of the type string, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main()

/var/www/html/nextcloud/ocs/v1.php - line 88:

OC\Route\Router->match()

/var/www/html/nextcloud/ocs/v2.php - line 24:

require_once("/var/www/ht ... p")

Caused by TypeError: Argument 2 passed to OCA\UserStatus\Controller\UserStatusController::setCustomMessage() must be of the type string, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OCA\UserStatus\Controller\UserStatusController->setCustomMessage()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main()

/var/www/html/nextcloud/ocs/v1.php - line 88:

OC\Route\Router->match()

/var/www/html/nextcloud/ocs/v2.php - line 24:

require_once("/var/www/ht ... p")

**Comment by jult** [comment]
Why is this still in there? All my users are complaining about it.. It immediately gives the impression that wonderful update to v20 is yet another disaster waiting to happen for them because some IT guys think they need to upgrade their stuff.

**Comment by bkyceh** [comment]
Version 20.0.1
Same

Exception: Argument 2 passed to OCA\UserStatus\Controller\UserStatusController::setCustomMessage() must be of the type string, null given, called in /usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169
/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\UserStat ... {}, "setCustomMessage")

/usr/share/nginx/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main("OCA\\UserSt ... r", "setCustomMessage", OC\AppFramew ... {}, { action: nu ... "})

/usr/share/nginx/nextcloud/ocs/v1.php - line 88:

OC\Route\Router->match("/ocsapp/app ... m")

/usr/share/nginx/nextcloud/ocs/v2.php - line 24:

require_once("/usr/share/ ... p")

Предизвикана од TypeError: Argument 2 passed to OCA\UserStatus\Controller\UserStatusController::setCustomMessage() must be of the type string, null given, called in /usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169
/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OCA\UserStatus\Controller\UserStatusController->setCustomMessage(null, null, null)

/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController(OCA\UserStat ... {}, "setCustomMessage")

/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\UserStat ... {}, "setCustomMessage")

/usr/share/nginx/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main("OCA\\UserSt ... r", "setCustomMessage", OC\AppFramew ... {}, { action: nu ... "})

/usr/share/nginx/nextcloud/ocs/v1.php - line 88:

OC\Route\Router->match("/ocsapp/app ... m")

/usr/share/nginx/nextcloud/ocs/v2.php - line 24:

require_once("/usr/share/ ... p")
