### ISSUE TITLE
Wrong time in weather widget

### ISSUE THREAD

**Issue by LarsBauer** [nextcloud/server#23399]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
 
The time displayed in the weather widget is not correct. I took this screenshot just now (~ 13:00 in Germany) but it's showing 17:00. Is there any setting I am missing?

![image](https://user-images.githubusercontent.com/3920045/95738890-3f2f0b80-0c8a-11eb-829b-8dd47aeb40d5.png)

**Comment by juliushaertl** [comment]
Since we show the upcoming weather instead of the one right now, the time is indicating the time of the forecast. 

Not sure if we could indicate that a bit better? cc @eneiluj @jancborchardt

**Comment by LarsBauer** [comment]
Thanks for the explanation.
For me it was not clear that you are displaying the forecast instead of the current weather. Is there any plan to show this information as well? Every weather widget I know of displays at least the current conditions.

**Comment by jancborchardt** [comment]
The idea was that the _current_ conditions are pretty useless because that can be gotten by looking out the window. What is needed is an overview of the day, or basically the "worst possible condition" like e.g. rain, low temperature etc. So we can definitely improve there. But only showing the _current_ condition is definitely a step back as said. :) 

As a wording fix, we could adjust it to say "in 4 hours" or "later", or just cut it. 
As a proper fix it would be good to just say "No rain all day" or "Low temperatures until 13:00", a summary of the day (or tomorrow if it’s very late in the evening) just like https://darksky.net does.

@eneiluj

**Comment by eneiluj** [comment]
I agree with @jancborchardt that current weather might not be relevant in this widget.

> What is needed is an overview of the day

It's hard to summarize the weather forecast for a day in one small widget. What about making something looking like favorite locations? I mean adding a foldable entry showing entries for weather in 2, 4 and 6 hours (as we already have the data)?

> As a wording fix, we could adjust it to say "in 4 hours" or "later", or just cut it.

Why not. I think showing the absolute time is more precise...but do we need precision in this widget? :grin:

> As a proper fix it would be good to just say "No rain all day" or "Low temperatures until 13:00", a summary of the day

I would say it's hard to do and does not provide the information whether (not weather :wink:) it's becoming better or worse.

I guess there are plenty of ways to present summarized weather. I prefer seeing a series of forecasts than a sentence. I don't know if it's because I'm used to it or because I really think it makes more sense. What do y'all think?

**Comment by LarsBauer** [comment]
@jancborchardt That makes total sense. I was just expecting a different behavior. Maybe some wording changes or an expandable widget for more information would be nice.

**Comment by CountParadox** [comment]
Worth noting that I though the same thing and found this issue after triple checking my timezone was correct.
Maybe we need a clock widget to compliment the weather one 🤔

**Comment by DrCarsonBeckett** [comment]
If it is indeed like that, which sounds about right, then it just needs to formulated a bit different.
Because if you just take a look at it, it might indicate the wrong thing.

**Comment by Prog1563** [comment]
It would be nice to have an option to show the current weather instead of the upcoming weather.
My offices don't have a good view of outside, and if I need to go out to do something it would be nice to see the current temperature and weather so that I can dress accordingly.

Options are always nice to have, of course :)

**Comment by alexpovel** [comment]
> As a wording fix, we could adjust it to say "in 4 hours" or "later", or just cut it.

This would be welcomed. *X degC in 4 hours* is nice and humanly readable, with no avenue for misinterpretation. It is less precise, but I would prefer it.

Secondly, I would very much like a "current" temperature. The current *conditions* I can see looking out the window, absolutely. The current *temperature* not so much. It can vary (roughly, subjectively speaking) by as much as 15 degC from what it "looks like" to "what it is" (or better: "what it feels like", since it can be hard to see wind conditions if there's no trees etc. nearby).

**Comment by fischer-felix** [comment]
> The idea was that the _current_ conditions are pretty useless because that can be gotten by looking out the window. What is needed is an overview of the day, or basically the "worst possible condition" like e.g. rain, low temperature etc. So we can definitely improve there. But only showing the _current_ condition is definitely a step back as said. :)
> 
> As a wording fix, we could adjust it to say "in 4 hours" or "later", or just cut it.
> As a proper fix it would be good to just say "No rain all day" or "Low temperatures until 13:00", a summary of the day (or tomorrow if it’s very late in the evening) just like https://darksky.net does.
> 
> @eneiluj

I don't think It would be useless to show current conditions, because, yes I can tell if the sun is shining or if it's raining by looking out the window, but I can't easily tell the temperature, so from that standpoint, it might be useful for some people.

**Comment by DrCarsonBeckett** [comment]
I agree with @fischer-felix . I personally like current information, especially since I am very bad at "telling the temperatur". So I prefer information about the current weather.
But having both isn't too bad either.

**Comment by MrBenFTW** [comment]
Sorry but this is ridiculous. It is stupid as it is right now. I'm messaged countless times saying "the time is wrong" or stuff like that.

Please can someone make it so there is a master/global config in the admin settings which allows us to set the offset to zero and have the weather be from the time the page is loaded.

**Comment by geep33** [comment]
😂😂😂

**Comment by MrBenFTW** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/27426792/103241885-6d002400-494c-11eb-8a86-ecd13b1f6614.png">
OH MY GOD I am going to commit a war crime

**Comment by explorer79** [comment]
I'm glad I found this issue here. I was already about to send a support ticket to the hoster about the wrong time. I was assuming they might have set a wrong time in their server or something. This is absolutely not what I was expecting.
Every weather app that I know shows the current weather and maybe additional information about highest and lowests temperature of the day. When I want to know more or a forecast I click or tap on it and I will see a hourly or daily forecast.

The setting as it is now really disturbs me every time when I open my nextcloud. I just disabled it and I will check the weather app of my phone instead.

**Comment by nichtich** [comment]
The weather data [is queried here](https://github.com/nextcloud/server/blob/e10cad4a718422b8b9d19546cc61cb39e4c0ee26/apps/weather_status/lib/Service/WeatherStatusService.php#L368-L389) via [this API](https://api.met.no/weatherapi/locationforecast/2.0/documentation#Methods). The response actually contains data for right now, in 1 hour, in 6 hours and in 12 hours. I suggest to include all of these values in the widget as dropdown table.

**Comment by Cactus-Pete** [comment]
I was confused by this for some time and looked into misconfigurations before finally seeing someone else has reported it as a bug.  Perhaps given the name of the widget is "Weather **Status**" the time should be current.  Or change the name to Weather Future...?  Or change the "**at** 12:00" to "**by** 12:00" to indicate it's not current, but projected...

**Comment by MrBenFTW** [comment]
This still haunts me. How many years has it been here for? How many restless souls has this weather widget consumed

**Comment by weierophinney** [comment]
> I agree with @jancborchardt that current weather might not be relevant in this widget.

I disagree here, for a few reasons:

- I might want to know the current temperature prior to leaving the building, so I know whether or not to put on a coat, hat, etc. Temperature is not something I can necessarily gauge by looking out the window.
- If I am not near a window, I might not have the ability to, as somebody else noted, "look out the window". This can happen if I work in a sub-level, or in an interior office.

As such, making a blanket statement that current weather is not relevant is making a ton of assumptions about where people work and their ability to accurately determine the weather based on that location.

**Comment by MrBenFTW** [comment]
> > I agree with @jancborchardt that current weather might not be relevant in this widget.
> 
> I disagree here, for a few reasons:
> 
> * I might want to know the current temperature prior to leaving the building, so I know whether or not to put on a coat, hat, etc. Temperature is not something I can necessarily gauge by looking out the window.
> * If I am not near a window, I might not have the ability to, as somebody else noted, "look out the window". This can happen if I work in a sub-level, or in an interior office.
> 
> As such, making a blanket statement that current weather is not relevant is making a ton of assumptions about where people work and their ability to accurately determine the weather based on that location.

Fair enough... but SIX HOURS?? 

The weather is extremely hard to predict, 6 hours ahead is too much

**Comment by aptalca** [comment]
Just a quick comment on the `looking out the window`
Well, a lot of us are in air conditioned buildings with windows that don't open. I can `look` outside, but it can look sunny and be freezing, or look dark and dreary but be quite warm. How it looks outside has little bearing on what the weather conditions are.

With that said, I, like most folks in this thread, assumed the widget had the wrong timezone set. It also displays Celsius by default and requires one to change the language from English US to something else, and then back to English US to display Fahrenheit, so it was easy to assume `oh, there is a bug with both the locale and the timezone`.

Just my $0.02

**Comment by stooke** [comment]
I also was very confused by this.  I'd say just delete the time from the widget, or make it relative, like "rain, in 2 hours"

**Comment by darklight72** [comment]
> The weather data [is queried here](https://github.com/nextcloud/server/blob/e10cad4a718422b8b9d19546cc61cb39e4c0ee26/apps/weather_status/lib/Service/WeatherStatusService.php#L368-L389) via [this API](https://api.met.no/weatherapi/locationforecast/2.0/documentation#Methods). The response actually contains data for right now, in 1 hour, in 6 hours and in 12 hours. I suggest to include all of these values in the widget as dropdown table. By the way there is a more complex [weather app](https://github.com/nextcloud/weather) if more information is wanted.

So, while I'm not overly adept at javascript, this is a relatively easy fix for anyone who wants "current" information displayed.  The file to update is:
`nexcloud/apps/weather_status/js/weather-status.js`

ie: my full path below
`/var/www/html/nextcloud/apps/weather_status/js/weather-status.js`

Fix it with sed, restart apache2 and hard refresh your dashboard page and voila, "current" conditions.

The below sed command was run on a Pi4 with apache2 as the web server and fixed it for me.
`sudo -u www-data sed -i 's/this.forecasts\[5\]/this.forecasts\[0\]/g' weather-status.js`

Caveat - The forecast isn't updated all the time and caching is involved, so current is relative.

If you are bored, you can dig through the .js but be warned, it's not beautified so it's a longline, and it's 1.1mb.  If you run it through a beautifier, you are looking at lines 44702, 44705 and 44709 and need to update (this.forecasts[5]...) to (this.forecasts[0]...).

If you don't want to beautify the file, the first three instances of "sixHours" are where these three instances live.  Again, this is really only important if you want to manually edit the file.

Ideally, I would think this should be configurable, but I'm not going to pretend how to do that.

**Comment by scharmach** [comment]
If you want to manually edit the file you can also go ahead and search and replace `this.forecasts[5]` with `this.forecasts[0]`. That's at least what I did, since `this.forecasts[5]` only occurs at these three places already described by @darklight72:

```
        sixHoursTempForecast: function () {
          return this.forecasts.length > 5 ? this.forecasts[5].data.instant.details.air_temperature : ""
        },
        sixHoursWeatherForecast: function () {
          return this.forecasts.length > 5 ? this.forecasts[5].data.next_1_hours.summary.symbol_code : ""
        },
        sixHoursFormattedTime: function () {
          return this.forecasts.length > 5 ? u()(this.forecasts[5].time).format("LT") : ""
        },
```

While it's at least something, I really hope that this might become a setting in the future.

**Comment by LarsBauer** [comment]
Quick update. The weather widget is broken on my installation after updating to 20.0.7 Anyone facing similar issues?

![image](https://user-images.githubusercontent.com/3920045/107498679-66440e00-6b94-11eb-8ac8-97b759259915.png)

**Comment by jelofson** [comment]
I believe the current implementation could use some work.

If I want to know what the weather will be like in x hours, I will click the "More weather for [my location]" link and get the forecast. When I see weather on the dashboard, I want to know the CURRENT temperature. Sort of like every other weather widget on the planet.  The only other thing I can suggest is you could do something like: 
Currently: -9 C and partly cloudy
Tonight: -25 C Clear
Tomorrow: -12 C and sunny

**Comment by Exist2Resist** [comment]
> The idea was that the _current_ conditions are pretty useless because that can be gotten by looking out the window.

> I agree with @jancborchardt that current weather might not be relevant in this widget.

Are you actually justifying not fixing the issue with the solution "Look out the window"?
Then why do you have the page showing status Good Morning, Afternoon, Evening?
Yeah I can look out the window and you know what it looks like +7, well it's not, it's -4.

Can a setting be enabled for us to change this?

**Comment by Fuseteam** [comment]
could we maybe add the current time to the widget? that way it will be clear what the second time is for
as for why it doesn't display the current weather condition I get that, cause its not updating all the time it can't show the current weather conditions all the time but it can reasonably show the weather condition in a few hours, it just needs to be a tad clearer what it is.
i think some way to show the current time on the dashboard/weather widget will likely solve that confusion

**Comment by Lawkss** [comment]
I just noticed this too. It should show the current weather and local time.

**Comment by mkraemer0** [comment]
This is my patch to calculate the temperature for the current time and to show if the temperature is rising or falling.

![grafik](https://user-images.githubusercontent.com/16748443/118028957-f5172100-b363-11eb-8240-194b5f739b18.png)

`sed -i.orig \`
`-e 's/\(forecasts\.length\)>[0-9]/\1>1/g' \`
`-e 's/\(this\.forecasts\)\[[0-9]\]\(\.data\.instant\.details\.air_temperature\)\(:""}\)/\1[0]\2+(\1[1]\2-\1[0]\2)*(Date.now()-Date.parse(\1[0].time))\/(Date.parse(\1[1].time)-Date.parse(\1[0].time))\3,sixHoursTempUpDown:function(){return this.forecasts.length>1?(\1[1]\2===\1[0]\2?"":\1[1]\2>\1[0]\2?" ↑":" ↓"):""}/' \`
`-e 's/\(forecasts\)\[[0-9]\]\(\.data\.next_1_hours\)/\1[0]\2/' \`
`-e 's/this\.forecasts\[[0-9]\]\.time\()\.format\)/Date.now()+30000\1/' \`
`-e 's/\(this\.temperatureUnit\)\([^+]\)/\1+this.sixHoursTempUpDown\2/' \`
`-e 's/\(this\.useFahrenheitLocale?([^)]*)\)\(\.toFixed([0-9]*)\)\(:[^}]*\)/parseFloat((\1\3)\2).toLocaleString()/' \`
`~/nextcloud/apps/weather_status/js/weather-status.js`

Regardless of this, the accuracy of the weather data of the norwegian server used is imprecise compared to other services, at least for my region.

**Comment by Crosse** [comment]
Howdy. I just upgraded my v19 install to v21 (after a quick stop on v20), so this is the first time I've seen the new dashboard. My immediate reaction when seeing the time in the weather widget was, "why is this widget picking up that my server is in UTC while I'm in EDT and, uh…rounding up?" As I look at my dashboard now it is 7:33PM local, but the widget is showing me the forecast for midnight. This is sadly not useful to me.

While I understand the _intention_ of making the data useful as a "forecast", I think because it takes up so little space people (including me) assume it's supposed to show the _current_ conditions. I also disagree with the notion that "looking out the window" is a replacement for displaying current conditions. Sure, my desk is a good three feet from the nearest window, but I certainly don't want to open that window and stick my hand out just to gauge the temperature.

I think at the end of the day I have simply been conditioned to expect a weather widget, by default, to tell me current weather conditions. It's how the macOS weather widget works; it's how iOS does it; it's how the Dark Sky app—and most other weather apps—works; even weather.com and windy.com show current conditions first and most prominently. Deviating from the norm here seems to cause more surprise and consternation than usefulness, and also—I think—outweighs any perceived benefit from showing a forecast over the current conditions.

While I have nothing against a "quick forecast"/"overview of the day"/"worst weather indicator" kind of display, I believe that since there is so little space given to the widget, the default should not violate the principle of least surprise and only show the current weather. If more space could be allocated to the widget, I'd love to have both the current information and forecast. Unfortunately in its current form, it is not as intuitive or useful as it could be.

**Comment by MrBenFTW** [comment]
> I'd love to have both the current information and forecast. Unfortunately in its current form, it is not as intuitive or useful as it could be.


Unfortunately the developer doesn't see things the same way as the rest of the community so you'll just have to modify it manually as @mkraemer0 suggested. The issue has been open for almost a year.

**Comment by Crosse** [comment]
> Unfortunately the developer doesn't see things the same way as the rest of the community so you'll just have to modify it manually as @mkraemer0 suggested. The issue has been open for almost a year.

I mean, sure, that’s what it seems like, but I think that tone is a little harsh. In the end this isn’t my product or my code. I don’t pay for it, either, so I have zero rights to demand anything or get pissy when my requests are ignored. What I can do, though, is add another (hopefully civil!) voice to the request for this to be configurable and not have to resort to manual changes.

That said, as a developer myself I try not to leave issues open that I absolutely don’t intend to fix; they get closed or rejected with my reasoning for rejecting them so that they don’t pile up. On the other hand, I also have tickets that have been open with no movement on them for quite some time, simply because of lack of resources, higher priorities, etc. If this issue is not going to be fixed, it would probably be beneficial if someone from Nextcloud (@jancborchardt?) just closed it with a final summation. It being open gives hope that this issue is on some board somewhere, just waiting for someone with enough free time to address it. 😄

**Comment by brmiller** [comment]
To throw another suggestion out there (as I found this issue when my own server started forecasting futuristic times and I didn't realise it - I thought it was a bogus-set time), couldn't the widget show something akin to the iOS Weather App which shows you hour-by-hour weather icons and temperatures?  I think there's enough space on the screen to show "Now", 1 hour from now, and 3 hours from now (or 6 or whatever ends up being reasonable based on the API response).  A cute little table

```
Now    2pm    3pm    4pm
partly   sunny sunny sunny
cloudy image image image
image
73        75       79       79
```

**Comment by szaimen** [comment]
So @jancborchardt @eneiluj how do we proceed with this one?
If we will not implement this, please say say so and close this issue. 
If yes, please add the applicable labels to this issue.
Thanks!

**Comment by DrCarsonBeckett** [comment]
So whats about it now?

**Comment by MrBenFTW** [comment]
So has this been fixed then? 

The weather is no longer 6 hours into the future?

**Comment by DrCarsonBeckett** [comment]
It has not been changed so far.

**Comment by WereCatf** [comment]
I just came upon this thread because I was also confused about the widget showing the wrong time. Well, given the comments above, the widget is entirely useless for me: I'd either want to know the current conditions, or the closest forecast to a specific time of my choosing, but a random forecast? What's the point with that? Like, if I were e.g. doing some outdoors work at specific hours regularly, it'd be likely I'd want forecasts around those hours, but the widget showing some random forecast will offer zero useful information to me.

**Comment by Fuseteam** [comment]
nooooo let the issue close, the discussion has already reached an conclusion: the weather widget shows the weather conditions in 6 hours after various factors have been considered

**Comment by WereCatf** [comment]
> 
> 
> nooooo let the issue close, the discussion has already reached an conclusion: the weather widget shows the weather conditions in 6 hours after various factors have been considered

Knowing that doesn't make it useful and I just explained why. Being able to tell the widget e.g. "I want forecasts for around these hours (if available), since I'll be out and about then" would be, but the way the widget currently works makes it worthless.

**Comment by Fuseteam** [comment]
guess that's up to the maintainers, or someone to contribute a pr to add such a setting i guess

**Comment by jonathanmmm** [comment]
@all that got confused as well and want to help others not to get confused the same as you got, vote this request do remove/disable the weather widget from new installations up: https://github.com/nextcloud/server/issues/30436

**Comment by ya-d** [comment]
> The weather data [is queried here](https://github.com/nextcloud/server/blob/e10cad4a718422b8b9d19546cc61cb39e4c0ee26/apps/weather_status/lib/Service/WeatherStatusService.php#L368-L389) via [this API](https://api.met.no/weatherapi/locationforecast/2.0/documentation#Methods). The response actually contains data for right now, in 1 hour, in 6 hours and in 12 hours. I suggest to include all of these values in the widget as dropdown table. By the way there is a more complex [weather app](https://github.com/nextcloud/weather) if more information is wanted.

I really don't have any stakes in this bare bones weather widget so I try to propose a constructive solution to reach a middle ground between the two arguments.

**A.** Would it be a more sane **default to show the 1h forecast**? Six hours into the future is really rather useless for most of a typical work day unless you check the widget early in the morning. Its also a very long time in advance to check wich jacket to take. Should be simple to change, more useful for many and less confusing (display "… in 1h" instead of time to indicate purpose).

**B.** In a later step you could add the current weather, 1h forecast and 6h forecast to the popover menu as a further improvement. A modal view would probably be more appropriate then and more in line with how status is set.

**Comment by jonathanmmm** [comment]
@ya-d thats a good compromise, but that it is 1h in the future has to be made more clear. Either write in 1h, but not write like at 10 a.m., and the user just reads 10 a.m. thinks it is 10 a.m. and maybe rushes of. Or the admin thinks something is wrong with summer/winter time (if living in a region, where this applies).

**Comment by mkraemer0** [comment]
Please take a look at my solution in this post: https://github.com/nextcloud/server/issues/23399#issuecomment-840022712

There I calculate the temperature for the current time. Additionally this can be updated locally every minute without server access.

**Comment by jonathanmmm** [comment]
> Please take a look at my solution in this post: [#23399 (comment)](https://github.com/nextcloud/server/issues/23399#issuecomment-840022712)
> 
> There I calculate the temperature for the current time. Additionally this can be updated locally every minute without server access.

Seems great, but they shouldn't be a reason to fiddle with the source code. Thought about forking it and creating a new plugin and publishing it to the nextcloud app store. But just because of this small change? Seems to be overkill or what do you think?

**Comment by Fuseteam** [comment]
The reason why it isn't configurable is here: https://github.com/nextcloud/server/issues/23399#issuecomment-941010389

The idea behind the weather widget is here: https://github.com/nextcloud/server/issues/23399#issuecomment-707599315

I proposed adding the current time to the widget to make it clearer but i feel like it's way buried: https://github.com/nextcloud/server/issues/23399#issuecomment-826026672

**Comment by jancborchardt** [comment]
Hi everyone, we finally fixed this with https://github.com/nextcloud/server/pull/30496 – thanks all for the feedback and staying friendly! :)

**Comment by jerimiah797** [comment]
Thanks the Gods

**Comment by masterwishx** [comment]
i have no time at all , how to fix it  ?

![image](https://user-images.githubusercontent.com/28630321/178139252-e94c3df4-250d-4794-9570-e3b80f1779ac.png)
