### ISSUE TITLE
Nextcloud 20 Dashbaord pfd issue

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#23522]
Hello when you click on a pdf from the recommended files it opened it with Collabora and not with pdf viewer. This only happnes when you're on the dashboard screen 
    
    
![image](https://user-images.githubusercontent.com/59488153/96287586-cb517380-0fa7-11eb-88bb-afe034e98d9d.png)
![image](https://user-images.githubusercontent.com/59488153/96287728-fcca3f00-0fa7-11eb-83e9-7c0aa5999243.png)

**Comment by skjnldsv** [comment]
@juliushaertl ?

**Comment by juliushaertl** [comment]
Hm, Collabora also registers a handler for PDF in the viewer. For the files app we currently still use a old file action there to register a non-default open action, but for viewer it seems that with two handlers, Collabora always wins (maybe because it is registered last?)

I assume it makes sense for now to remove those from the viewer registration. However when we move the files app code to the viewer for richdocuments we need some way to let users open the file in Collabora through the files actions.

**Comment by axheli** [comment]
@juliushaertl this issue is back up with Nextcloud 20.0.5 everyone i open a pdf within the dashboard board it opens with only office
