### ISSUE TITLE
Misspelled Word

### ISSUE THREAD

**Issue by blackerking** [nextcloud/server#23553]
![grafik](https://user-images.githubusercontent.com/2019363/96420642-08ab4080-11f6-11eb-8705-9e0f1af4ad52.png)
When searching for a user I get "Kontake".
It should be "Kontakte".

Found in Version 19.0.4

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

I suggested a fix at transifex (the tool to manage translations). Feel free to join https://www.transifex.com/nextcloud/nextcloud/ to help. It's also possible to sign up with your GitHub account.

Should be fixed with the next maintenance release.

@rakekniven @MorrisJobke 

https://www.transifex.com/nextcloud/nextcloud/translate/#de/core/175862535
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/core/175862535

**Comment by rakekniven** [comment]
Reviewed strings. Thank you for reporting.
