### ISSUE TITLE
Opening a Markdown file does not change the URL.

### ISSUE THREAD

**Issue by shushugah** [nextcloud/server#23592]
### Steps to reproduce
1. Create a markdown Document (`*.md`) file
2. Open the file and copy the link in browser bar
3. The link is the same as the folder the file lives in.

### Expected behaviour
The link in URL bar corresponds with the file open/visible in browser, which is the case for every other file type, PDF's, images etc..

For example, while opening a new tweet is just a modal open, twitter updates the URL, `https://twitter.com/compose/tweet` which opens the modal automatically. 

This behavious is different in https://try.nextcloud.org 

### Version
`Nextcloud 18.0.2.2`
Chrome and Firefox browser.

**Comment by kesselb** [comment]
It's totally fine to leave out all those server related information if the issue is clearly related to the client side code. But something like the Nextcloud version is helpful. Or if you see any errors in the browser's console.

![Peek 2020-10-20 20-50](https://user-images.githubusercontent.com/3902676/96630878-ea3c6680-1315-11eb-81cc-286622e967fe.gif)

Works for me on https://try.nextcloud.com => adding needs info label. Please add how to reproduce the issue and/or provide details about your configuration.

**Comment by shushugah** [comment]
Thank you for the speedy reply! I enclosed a screenrecording, for Nextcloud version 18.0.2

A friend told me, that links are not available for the "Markdown Editor" and that this is expected behaviour. I also tried this on a 2nd nextcloud account, but could not confirm the version. 

![Animated nextcloud gif](https://im2.ezgif.com/tmp/ezgif-2-89a776ec0391.gif)

**Comment by shushugah** [comment]
I can also confirm, that the same behaviour is different on https://try.nextcloud.com, so it suggests that upgrading the version would fix this potentially?

**Comment by skjnldsv** [comment]
Yep, can't reproduce anymore :/
