### ISSUE TITLE
cs translation inaccurate/error

### ISSUE THREAD

**Issue by Aktron** [nextcloud/server#23694]
Hello,

I would like to ask for a help in relation of an error/inaccurate translation of Czech (cs) version of nextcloud

"Chyba při vytváření sdílení" does not state what error has happened. Turns out it means that an user has not logged in yet and thus an account of his cannot be used for sharing. Do you know where can I fix it or ask for fixing this? I haven't found anything in this repository in relation of translation or Czech or cs, nor have I found nothing on translatewiki.

Thanks!

**Comment by kesselb** [comment]
Thank you for reporting :+1: 

We are using Transifex to manage translations. Please join https://www.transifex.com/nextcloud/nextcloud/ to help. It's also possible to sign up with your GitHub account.

Translations are synced daily from Transifex to GitHub. Any change related to translation must be done there otherwise they are lost.

**Comment by svetlemodry** [comment]
> 
> "Chyba při vytváření sdílení" does not state what error has happened. Turns out it means that an user has not logged in yet and thus an account of his cannot be used for sharing. Do you know where can I fix it or ask for fixing this? I haven't found anything in this repository in relation of translation or Czech or cs, nor have I found nothing on translatewiki.

I just want to add that the Czech translation is correct in regards to what the original string nr. 10028 "Error creating the share" says. It would be difficult for us, the translators, to know if this error shows only if the user is not logged in yet.
Cheers!
Jaro
