### ISSUE TITLE
Share link menu going craaaaaaazy on scroll

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#23872]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a scrollable file list
2. Share a file at the top
3. Select some options (that expand the menu)
4. Scroll up/down

### Expected behaviour
Then menu stays where it was/is

### Actual behaviour
It jumps up and down and even scrolls away
![Peek 2020-11-03 19-49](https://user-images.githubusercontent.com/213943/98028182-05c36900-1e0e-11eb-8e1f-0c2bc12f4854.gif)

### Server configuration

**Nextcloud version:** master

**Comment by nickvergessen** [comment]
I guess its caused by the recent vue lib changes? cc @skjnldsv @PVince81

**Comment by PVince81** [comment]
I've seen the same today on NC 20.0.x on the company instance, in the Forms app.

Try creating a form that has multiple pages. At some point the three dots menu doesn't even appear any more because it appears on the first page instead of the current one. You have to scroll up to catch it.

So could be a regression introduced somewhere in a minor release...

**Comment by PVince81** [comment]
I just tested the share menu and it also appears on the company instance, NC 20.0.2.1 RC.

Let me bisect...

**Comment by PVince81** [comment]
also happening on v20.0.0.

**Comment by PVince81** [comment]
v19.0.4 works fine, the menu appears below the arrow and doesn't move when scrolling the file list.

I guess in v20 maybe the scroll container changed, or the menus are now attached to the main page container

**Comment by PVince81** [comment]
another one of those ghost bisects (first one was with https://github.com/nextcloud/server/issues/23617):

- working commit: aad30d3b33ea138a1d436405e25f285f7eda8436
- breaking commit: c772df81c30d497729bece12625c4c02cf82ffb6 which is only changing version.php

All I did was, with a clean checkout:
1. git checkout aad30d3b33ea138a1d436405e25f285f7eda8436 + git submodule update
1. run occ maintenance:install, etc
1. upload many files to generate a scrollbar
1. share the last file with link
1. click three dots menu => here it works fine
1. git checkout c772df81c30d497729bece12625c4c02cf82ffb6 + git submodule update
1. delete DB, data folder contents and config.php
1. re-run occ maintenance:install
1. then same steps as above
1. click three dots menu => the menu doesn't appear, scroll up to see it

I thought that all assets were checked in the repo and switching branches + submodule would be enough to not have weird side effects.

I don't have any extra apps.

**Comment by PVince81** [comment]
I'll need to redo the bisect...

**Comment by PVince81** [comment]
it's likely due to the introduction of Popover: https://github.com/nextcloud/nextcloud-vue/pull/832

and a possible solution could be to specify the boundary element: https://github.com/nextcloud/nextcloud-vue/pull/1351

so we need to grep for all apps that use Popover (like forms) and add a boundary element there.
- [ ] TODO: try out boundary-element
- [ ] TODO: grep for all apps
   - [ ] share link popover
   - [ ] forms context menu
   - more to come

**Comment by PVince81** [comment]
@ma12-co see above FYI

**Comment by geep33** [comment]
What are you talking about?,,🤣🤣

**Comment by ma12-co** [comment]
I think it's more about the container than the boundary element

see https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Actions/Actions.vue#L277

**Comment by geep33** [comment]
https://emailstuff.org/rfc/rfc4870#section-3.8

**Comment by Fiech** [comment]
Just want to chime in that we also have this problem on NC 20.0.9. It also happens, when I scroll down in the file list and then click on the Three-Point-Menu in the share tab in the side bar. The context menu just does not appear. But when I scroll up to the top of the page, it comes into view.

This is kind of complicated to explain to less technically inclined users, so a fix would be great and very appreciated (although I seem to be only the second one to hit the thumbs-up button).

Also I was just wondering if a fix would make it also to the NC 20 version (I know it's just in support until this October but I do not know yet when we will be able to upgrade).

**Comment by briantho** [comment]
Any word on a fix, or workaround? I'm running nextcloud 21.0.0 and having to explain this issue to new users is a pain. It's also very easy to reproduce when you have a lot of files...

**Comment by arnowelzel** [comment]
Same issue here with Nextcloud 21.0.3 and really a problem for new users - you have to explain that they must scroll all the way up to see the sharing menu. Depending on where the current scroll position is, the menu is even not visible at all. Also the arrow is sometimes separate from the menu.

![image](https://user-images.githubusercontent.com/6613614/125670268-fbbe855a-8c02-4c6d-b80b-7b9900d594b6.png)

![image](https://user-images.githubusercontent.com/6613614/125670415-b76b03d3-74a4-41a8-9d4c-e9a6fa78487e.png)

**Comment by ImaCrea** [comment]
hello, same here on 22.1.1 as I explained [here](https://github.com/nextcloud/server/issues/28906)

I wonder what's the situation for a fix here. It's already been 2 major versions with this issue and it is leaving our users with a bad feeling about the overall "quality" of the product :/

**Comment by arnowelzel** [comment]
Well - the "fix" in Nextcloud 22.1 seems to be to scroll the view up first before the popup menu is shown. And then the menu is still defect somewhat as you can see that the arrow on top is separated from the popup. So the bug is not really fixed yet, the current status is just a workaround and even not a very good one.

![image](https://user-images.githubusercontent.com/6613614/134136223-18cef859-d46c-4a94-9d69-8836da4cac38.png)

However the "Right Click" app shows, that it is possible to create a context menu which is always visible and correct, even when the view is scrolled down - maybe it would help to check how it is done there.

**Comment by blizzz** [comment]
still an issue?

**Comment by nickvergessen** [comment]
No, fixed with the new UI
