### ISSUE TITLE
application menu very slow

### ISSUE THREAD

**Issue by eglyn** [nextcloud/server#23941]
Hi everyone, 

I have an issue with the last version of Nextcloud (20.1), access to the application menu is very slow (like more than 5 min of loading...), other menu are working normally.

I am on Debian 10, with apache, php7.3 and mariadb.

Any idea ?

**Comment by kesselb** [comment]
Adding needs info because the bug report is inaccurate:

1. Add a screenshot of the application menu to make sure we all talk about the same thing.

2. Edit your post and add the issue template (https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md). As start we require only the basic information like Nextcloud version and if you see some errors in the browser log.

**Comment by eglyn** [comment]
I found the problem, there is a timeout to connect to the store, in the nextcloud log I have a timeout to curl https://etc..., but my server does not have access to internet, why it try to go to the store ? :/

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
