### ISSUE TITLE
Disabling Dashboard App does not disable Dashboard

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#24059]
I'm on NC20, and I'm really fed up with Dashboard and other really stark regressions in this version.

20.0.1 was supposedly there to fix Dashboard drawing all wrong, but it hasn't. So I figured I'd go disable the Dashboard app, and well, it hasn't actually disabled it.

Sure, I don't see the icon along the top bar, however every time I log into nextCloud i still get the Dashboard by default. I just want it OFF until this clearly insufficiently tested feature is actually working reliably.

So let me disable it please.

**Comment by bpcurse** [comment]
Adding to this, please let users decide individually if they want to use the dashboard or not (e.g. a simple checkbox "Do not show Dashboard on Login").
Although it is a nice feature and will be useful for a lot of people, a UI change with such impact should be configurable (especially as NC can easily be used without).

Please take into consideration that some only use Nextcloud as a file storage or on a "low level" and don't need/don't want all the powerful extra stuff.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/2f678e0aadb4bd637c53a6051a20d11ae3c96a9e/config/config.sample.php#L208-L217

To change the default app. The documentation seems outdated as dashboard is the default app with 20.

**Comment by IcedEarth** [comment]
I agree. Having an option to enable/disable the dashboard WITHOUT modifying php files would be nice.

**Comment by kesselb** [comment]
The outdated documentation has been updated by https://github.com/nextcloud/server/pull/25029. A ui option to change the default app is not planned.

**Comment by wohali** [comment]
Would you kindly reconsider the decision not to plan a UI option to change the default app on a per-user basis? I understand no UI option for server-wide, as a single line in `config.php` is simple.

**Comment by sbrl** [comment]
The new dashboard is way too slow to be useful, and doesn't currently contain anything that I find helpful either. By the time it's loaded, I've already had time to "url hack" (i.e. manually change the URL) to  go to the app I originally wanted.

**Comment by kesselb** [comment]
> It seems to me like there are a significant number of requests here to allow the disabling of the dashboard, so I'm rather confused as to why this has been explicitly rejected.

It's already possible to disable the dashboard?

> Would a pull request adding the ability to disable the dashboard be accepted at all?

If your idea is to add another configuration option `disable_dashboard`: No.

> Would you kindly reconsider the decision not to plan a UI option to change the default app on a per-user basis?

If you have in mind to build an UI to manage default apps on a per-user basis. That's possible as app. 

Starting point for app development: https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html

https://github.com/nextcloud/server/blob/db86bea18ce41ad73e9c1a06f2b2d89d8d4f2ef8/lib/private/legacy/OC_Util.php#L1112-L1113

Your app basically needs to call `$config->setUserValue('userid', 'core', 'defaultapp', 'whateverapp');` to overwrite the defaultapp for a given user.

**Comment by sbrl** [comment]
> It's already possible to disable the dashboard?

How can I disable the dashboard, @kesselb? From reading the comments here, it is not currently possible.

**Comment by mmuman** [comment]
I have a hard time understanding the rationale here.

I use several NC instances, and on one there's this Dashboard I have absolutely no use for, and since the server is not very beefy, it takes about 5s to load, then 1s for me point and click the Files icon, and again 7s for Files to load. I use the web interface for a single thing that is move a file to a folder that isn't sync'd locally because it's too large. I don't want weather info or a fancy background.

I just want to work efficiently, which means not wasting 6s loading useless stuff in my browser. If I want to know the weather I'll go to a known website I have bookmarked which will load even quicker anyway. Most people will already have weather info on their Windows machine in the tiles, then in the browser each time they open a tab… no need to put it there again. Still, I suppose most people wouldn't bother either. But just add an account setting for that, that can't be hours of coding.

Yes you could implement this as an app, but that means you have to ask the admin to install it, and you first need to know it exists. That artificially restricts the number of users who will actually be able to disable it.

It's painful to see everyone thinking they can become indispensable by providing more services everyone already provides. To me it feels more like the tactics of a proprietary company wanting to impose a new feature by force than a FLOSS project wanting to empower users.

I thought FLOSS projects would be less inclined to do this… 🤷

**Comment by BloodyIron** [comment]
LOL ARE WE STILL UNABLE TO FULLY DISABLE DASHBOARD? Wow... 5 days away from a full year later.

**Comment by BloodyIron** [comment]
Yeah looking around more it looks like the devs have done nothing to make it so we can disable the dashboard. The dashboard is useful in some scenarios, but we, the general public, have legitimate need to disable it whenever that is preferred. I can't fathom why the developers are literally doing nothing about this, it's not like we're asking for total removal here, just the ability to disable it in various ways, and at a minimum the ability to disable it fully for all users!

Why is this being ignored?

**Comment by BloodyIron** [comment]
Correction, disabling the App entirely, seems to make it so Dashboard doesn't load at all by default. That works for me for now.

**Comment by hoshi411** [comment]
So what happened with this?  Did the devs listen or are they still out of touch with their user base?  Did we get the option to set ou default page to the Files app instead of the Dashboard, yet?

Usually this kind of "out of touch" happens when devs do not use their own software in a serious way (just coming from my experience) .  It would benefit them to listen to their community , the people who use their software for actual life.

We would like the ability to set the default loading page to any app other than Dashboard.  Of course this should be a per user setting and optional admin setting.  If an admin wants to make it global, they should be able to and if an admin wants to leave it to the users' choice, they should be able to .

But it is shocking that we are here in 2023 and there is no setting for our default page.

C'mon guys.

**Comment by kesselb** [comment]
On the roadmap for 28: https://github.com/nextcloud/server/issues/40241
