### ISSUE TITLE
连接外部存储，在外部存储中一次删除多个文件时报错

### ISSUE THREAD

**Issue by xyufs** [nextcloud/server#24210]
连接的外部存储是minio，上传文件没有问题，单个删除文件也没有问题，同时删除两个以上文件时会报错
![err](https://user-images.githubusercontent.com/22907754/99614001-9081a600-2a53-11eb-80d2-cbc0be9d3a71.jpg)

**Comment by wiswedel** [comment]
@xyufs Would you mind translating your issue to English?

**Comment by Kuphi** [comment]
> 连接的外部存储是minio，上传文件没有问题，单个删除文件也没有问题，同时删除两个以上文件时会报错
> ![err](https://user-images.githubusercontent.com/22907754/99614001-9081a600-2a53-11eb-80d2-cbc0be9d3a71.jpg)
@xyufs 
您可以将您的问题翻译成英语和/或回答以下问题吗？
＃＃＃ 重现步骤
1。
2。
3。

###预期的行为
告诉我们应该怎么办

###实际行为
告诉我们发生了什么

###服务器配置
**操作系统：**
**网络服务器：**
**数据库：**
** PHP版本：**
** Nextcloud版本：**（请参阅Nextcloud管理页面）
**从较旧的Nextcloud / ownCloud或全新安装更新：**
**您在哪里安装Nextcloud：**

Can you translate your issue to English and/or answer the following questions?
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system:**
**Web server:**
**Database:**
**PHP version:**
**Nextcloud version:** (see Nextcloud admin page)
**Updated from an older Nextcloud/ownCloud or fresh install:**
**Where did you install Nextcloud from:**

**Comment by PVince81** [comment]
as far as I understood he said that:

connecting to minio external storage: uploading a single file and deleting a single file works fine.
but uploading two files causes an error

anyway, without logs it will not be possible to understand what's happening
