### ISSUE TITLE
Database Error on Update to 20.0.2

### ISSUE THREAD

**Issue by majaMH** [nextcloud/server#24238]
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by j-ed** [comment]
Please use the Nextcloud help forum to find answers on your question, because the purpose of this repository is to track confirmed issues and features requests for the developers only. See e.g. here:

https://help.nextcloud.com/search?q=Specified%20key%20was%20too%20long%3B%20max%20key%20length%20is%20767%20bytes
