### ISSUE TITLE
update of convert-filecache-bigint should give a reasonable time estimate

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#24277]
NC 19.0.5
reports the need to update - good
```
sudo -u www-data php occ db:convert-filecache-bigint
Following columns will be updated:
* filecache_extended.fileid
This can take up to hours, depending on the number of files in your instance!
```
it took a few seconds ...

suggestions:
pls report the number of records and a reasonable estimate instead.

the warning "can take up to hours" - what are the options and consequences?
what should you do as admin at this point - trial and error?

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kesselb** [comment]
Fair suggestion but technically not possible. 

There is no way to predict how long adding an index or changing column takes. Feel free to search the internet for more explanations like:

- https://stackoverflow.com/questions/39003403/how-do-you-calculate-the-time-to-create-an-index-on-a-large-postgresql-table
- https://stackoverflow.com/questions/18469918/is-there-any-way-tool-to-identify-estimate-query-run-time-in-sql-server

> what should you do as admin at this point - trial and error?

Prepare yourself. If you are connected by ssh to your server make sure to run the command with screen (or a similar mechanism) in case of connection interrupt.

**Comment by ferdiga** [comment]
https://stackoverflow.com/questions/39003403/how-do-you-calculate-the-time-to-create-an-index-on-a-large-postgresql-table
suggest :
The good news is that you may CREATE INDEX CONCURRENTLY, which takes longer but does not lock the table. So the operation has no side effects except higher load on server.
does nextcloud do this?
- if so, the message is not necessary.
- if not, pls implement - and the message is not necessary.

does this sound as a good solution ?

**Comment by kesselb** [comment]
> does nextcloud do this?

No

> does this sound as a good solution ?

No

> and the message is not necessary.

Mind to elaborate what's wrong about the message? It seems to me that some people (e.g. https://help.nextcloud.com/t/warning-regarding-need-bigint-after-17-01-to-17-02-upgrade/66531) are disappointed that the process is done on their instance in a few seconds. If that's your concern I can send a patch to make the process run at least one hour ;)

**Comment by ferdiga** [comment]
If the nextcloud database is blocked by this process for many hours - it must be a scheduled maintenance. - if it takes just a few seconds or does not interrupt the admin has to take no actions.
just my 2c

**Comment by stuckj** [comment]
I'm sure this doesn't apply to you anymore @ferdiga, but for anyone else curious you can get a fairly accurate estimate from the DB after the update is in progress. E.g., use `show processlist` from the mariadb client if you run mariadb. I can't recall the postgres table to see the equivalent in postgres, but I recall there's a mechanism to see running queries there as well.

Mariadb gives you a total runtime in seconds and a progress as a percentage. Assuming steady load you can do a little math to get an estimate of the total time for that query. Won't be perfect since the time can vary based on memory allocated to your DB and CPU or I/O load on the server, but should be a good ballpark.

NOTE: If there are multiple tables it still wouldn't give you a good estimate for ALL of the tables (since ALTER TABLE calls are run sequentially). But, most likely the largest is going to be the filecache so just wait until it's updating that one and check the progress.

This would be pretty difficult to predict from nextcloud's side, but DB's have tools for getting more insight into queries.

**Comment by ferdiga** [comment]
thanks,
- I didn't encounter this problem after my inital report
- after moving the installation to a NC SAAS provider, the "admin" of nextcloud has a limited toolset available to investigate what happens on the remote server. Hetzner for example allows to use a defined set of occ commands using the Hetzner admin tools. But IMO this should not be the the suggested way to go as less experienced users might create more harm than solving a problem.

**Comment by stuckj** [comment]
Fair enough.

As an update, the estimate from the DB wasn't all that accurate anyway. :-P Based on the progress and percentage it looked like it was going to take a couple days (for 80+ million records). It ended up taking a couple hours. So, there you have it. :-P
