### ISSUE TITLE
Request: User ID tracking function

### ISSUE THREAD

**Issue by tak-nagano** [nextcloud/server#24520]
# Situation
When we accessed our NextCloud sign-in page, we couldn't access the page because it had executed to redirection to Error page.
We found a support page which is resemble our problem, and hope you to add a minor fix for output an additional info like below when the error occurs.

# Request
Add user id to contenets in the error log

Thank you at advance.

REF) Concrete our Error Log
```
OCP\Files\NotFoundException:
/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php - line 130:

OC_Helper::getStorageInfo("/", false)

/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php - line 178:

OCA\Files\Controller\ViewController->getStorageInfo()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

OCA\Files\Controller\ViewController->index("", "", null, false)

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Files\Co ... {}, "index")

/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 126:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files\Co ... {}, "index")

/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("OCA\Files\ ... r", "index", OC\AppFramew ... {}, { _route: "files.view.index"})

<>

OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "files.view.index"})

/var/www/html/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { _route: "files.view.index"})

/var/www/html/nextcloud/lib/base.php - line 997:

OC\Route\Router->match("/apps/files/")

/var/www/html/nextcloud/index.php - line 42:

OC::handleRequest()
```

**Comment by szaimen** [comment]
On the shown error page there should be a reqID which you should be able to get the correct log entry.

Otherwise: as this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
