### ISSUE TITLE
SQL error while updating to 20.0.4

### ISSUE THREAD

**Issue by haqk** [nextcloud/server#24723]
The following occurred when I tried to update to 20.0.4. How to fix?

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by j-ed** [comment]
Do you know the Nextcloud help forum which should always be your preferred destination to address all kind of configuration/installation issues:

https://help.nextcloud.com/search?q=Specified%20key%20was%20too%20long%3B%20max%20key%20length%20is%20767%20bytes

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by haqk** [comment]
@kesselb thanks for addressing the issue and offering a solution.

@j-ed while you might be right, your comment does not solve anything. Just a heads up, if you do not want people to report it here, then you may want to change the link in the error message that directed me here.
```
<p>The update was unsuccessful. Please report this issue to the <a href="https://github.com/nextcloud/server/issues">Nextcloud community</a>.</p>
```

**Comment by kesselb** [comment]
> want to change the link in the error message that directed me here.

Fair suggestion ;) I have a saved reply for this problem for a while now because people are reporting this problem over and over again. There are more than 50 other issues referenced to #15058 :open_mouth: 

How would you rephrase the message? You know how to use a search engine so using the search on GitHub shoud be self explaining. There is also a pinned issue called FAQ + Known Issues that references this kind of problem. 

You went to the issue tracker, pressed new, picked bug, deleted the issue template (which is not cool), strg+c, strg+v and clicked submit. For some reason you didn't used the search or looked at the FAQ issue. How should we rephrase the text?

**Comment by haqk** [comment]
Fair point. ;)
