### ISSUE TITLE
Mix of language

### ISSUE THREAD

**Issue by jmruas** [nextcloud/server#24734]
Hi,

I use the Portuguese language and some parts are in French.

Please, see this.
Thank you.

JMRuas

**Comment by kesselb** [comment]
Thank you for reporting :+1: 

We are using Transifex to manage translations. Please join https://www.transifex.com/nextcloud/nextcloud/ to help. It's also possible to sign up with your GitHub account.

Translations are synced daily from Transifex to GitHub. Any change related to translation must be done there otherwise they are lost.
