### ISSUE TITLE
Improve user management for group admins

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#24749]
If I'm a group admin the user management looks like this:

![image](https://user-images.githubusercontent.com/1589737/102521019-ab682a00-4094-11eb-85f4-b18facfd4bd6.png)

But if I try to add a group I get this error message:

![image](https://user-images.githubusercontent.com/1589737/102521122-d3578d80-4094-11eb-886b-1e868cc2a6ca.png)

The reason is obvious. Group admins can't create new groups. But in this case we should hide the "Add group" button so that the user not even try it.

On the other hand if I try to add a user, the interface looks like this:

![image](https://user-images.githubusercontent.com/1589737/102521326-1580cf00-4095-11eb-992e-6d066f5d68f5.png)

If I try to create a user and don't chose a group I get an error that I have to select a group. Would be nice of the group would be already pre-filled.

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by rosa2** [comment]
Please, solve this because it gives bad impression to new users that are coordinators. Thanks

**Comment by bes1002t** [comment]
I don't think we should "hide" something. Please just disable the button and show an tooltip. That would be much more user friendly than hiding buttons which exist in other situations.

**Comment by walhallaRV** [comment]
> If I'm a group admin the user management looks like this:
> 
> ![image](https://user-images.githubusercontent.com/1589737/102521019-ab682a00-4094-11eb-85f4-b18facfd4bd6.png)
> 
> But if I try to add a group I get this error message:
> 
> ![image](https://user-images.githubusercontent.com/1589737/102521122-d3578d80-4094-11eb-886b-1e868cc2a6ca.png)
> 
> The reason is obvious. Group admins can't create new groups. But in this case we should hide the "Add group" button so that the user not even try it.
> 
> On the other hand if I try to add a user, the interface looks like this:
> 
> ![image](https://user-images.githubusercontent.com/1589737/102521326-1580cf00-4095-11eb-992e-6d066f5d68f5.png)
> 
> If I try to create a user and don't chose a group I get an error that I have to select a group. Would be nice of the group would be already pre-filled.

2024 now and nothing changed. Same behaviour, same bug. Why show a function knowing that it will end in an error? Can anybody give me an answer - because in my opinion absolutely senseless.

Even better: if you asked your Super admin to add the group, in the next step you can have to ask him to add the 100, 200, 300, ... users too. And the best: he can not simply add the users to the new group. NO, he has to edit all the 100, 200, 300 ... users manually and add the new group to every single user. Great job and every super admin will love you for this stupid extra - job :(
