### ISSUE TITLE
Creating public link with an enforced expiration date

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#25123]
When I enforce a expiration date as an admin (Nextcloud 20) and than try to share a file I see this dialog:

![image](https://user-images.githubusercontent.com/1589737/104600096-dbe1ba80-5678-11eb-8067-4f30b966d1b4.png)

But how to I proceed? I tried to press enter, nothing happens. I try to open the date picker and tried to pick a date in the hope that this will finish the process with the selected date... nothing happened. I still see:

![image](https://user-images.githubusercontent.com/1589737/104600204-ff0c6a00-5678-11eb-81bf-8a50991c467b.png)

At some point I found out that I just have to click outside of the dialog to close it and accept the input. But that's a really special way to accept the input of a dialog and continue/finish the process.

Can we come up with a more user friendly and better understandable way of to create a share?

Maybe replace the "Cancel" button with an "Accept" button and trigger the cancel operation instead if people click outside of the dialog? I think that would fit better the "I want to escape" thought most people have when they click outside of a dialog.

cc @nextcloud/designers

**Comment by bes1002t** [comment]
To be honest, in my Nextcloud 20 installation I don't have a cancel button at this location.

But I agree, the process to share a link is not that intuitive at the moment. Currently if you click on "share" the link is shared automatically. I would suggest to open the share settings dialog, instead of automatically sharing the link. At the bottom of the dialog there should be a "share" button.

So the process would be:
1. Click on the plus behind "share link"
2. "share link" settings dialog would appear
3. configuration if needed
3. click on the "share" button at the bottom of the dialog

by the way, the datepicker is kind of invisible in a light theme. Maybe it's better to place it somewhere else or use a 2px border to emphasize it in front of the share settings dialog.

**Comment by szaimen** [comment]
cc @nextcloud/designers for a mockup how this could be improved.

**Comment by skjnldsv** [comment]
There's now a dedicated button to create the share
https://github.com/nextcloud/server/blob/9467a9386629468c3ddf3c77de2db6b9621e972f/apps/files_sharing/src/components/SharingEntryLink.vue#L121
