### ISSUE TITLE
Error in web updater: "Possible CSRF attack. Connection will be closed."

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#25311]
Error in web updater: 

"Possible CSRF attack. Connection will be closed."

By commenting out lines 85-88 in OC_EventSource.php the updater works fine.

cc @rullzer

**Comment by rullzer** [comment]
Well yes. if you comment out the protection then sure it will work.
Did you by any chance start the updater after resuming from hibernation etc?

**Comment by ma12-co** [comment]
Nope

**Comment by szaimen** [comment]
Is this still happening on NC21.0.4?

**Comment by renaudallard** [comment]
Even still present in nextcloud-24.0.10. Although I never had it with any former version.

**Comment by Mrs-Feathers** [comment]
version 27 too. also never had it until now

**Comment by genkigenki** [comment]
Version 28 has it too. Seems to be persistent.

**Comment by ChristophWurst** [comment]
Dear @szaimen, could you please re-triage so this isn't auto-closed another time? Thank you very much

**Comment by szaimen** [comment]
I am not going to close it this time so it should stay open :)

**Comment by plantarum** [comment]
I am running into this now, having just used the web updater to update to 31.0.6.

Immediately following the update I saw this:

![Image](https://github.com/user-attachments/assets/b4dc27c3-4955-4fd9-9188-76063508dea2)

The first few times I clicked on it it said Nextcloud was already updated, but when I clicked the link to 'continue to Nextcloud' I got the same screen again.

Now when I click the update button I get this:

![Image](https://github.com/user-attachments/assets/d8d40d3f-30eb-4ee8-88eb-731b436779e2)

I don't have ssh access to the machine, so I can only use the web update. But at this point I can't access anything, since this screen is presented to anyone who goes to my site (i.e., you don't need to login to get there).

Any suggestions?
