### ISSUE TITLE
Dashboard: default settings for all users

### ISSUE THREAD

**Issue by tobidwest** [nextcloud/server#25553]
A setting that allows to set default setting for which widgets to enable and disable on the dashboard and which baground image to set

See this community thread for details: https://help.nextcloud.com/t/dashboard-default-settings-for-all-users/104395

**Comment by daniron26** [comment]
upvoted. Useful for me too.

**Comment by daniron26** [comment]
Actually it is possible to change the dashboard settings for a user database directly:

Database Table name: <prefix>_preference
Table structure: userid, appid, configkey, configvalue

example entry:
userid = "user"
appid = "dashboard"
configkey = "layout"
configvalue = "announcementcenter,mail,recommendations,calendar"

will enforce a new user to have these four widgets on their dashboard.

Please backup your data before changing anything, use at your own risk.

**Comment by benwrth** [comment]
daniron26 Is there a way like this to enforce for all new user accounts? Thanks.

**Comment by daniron26** [comment]
If you are comfortable using SQL, you can use that one line SQL to INSERT an initial dashboard setting to all (new) users. Once the user login and open the dashboard app for the first time, I presume dashboard would populate the database with its own default setting (it will respect pre-exiting setting in the database), in that case the INSERT will work for a user that has not yet log in, but fail for the user who has logged in because of the preexisting setting in the database (duplicate key error), therefore his custom settings are preserved and no harm is done.

If you are looking for an automatic way which whenever a new user is created the database is modified by a custom script, I did a brief lookup and don’t see a way of doing that provided by nextcloud itself. You can always use a cron job to periodically change this database entry for any user you like, in a way the user will always return to dashboard and see their custom setting being overwritten by your SQL command.

As always take your own risk, exercise care and backup all data.

Cheers
DS

**Comment by szaimen** [comment]
This was implemented with https://github.com/nextcloud/server/pull/25309

and is possible on NC21 and above via:
`occ config:app:set dashboard layout --value="recommendations,spreed,mail,calendar"`

**Comment by ruedigerkupper** [comment]
The original post was about setting the default backhround, too. Is this also implemented? If not, this issue should not be closed.

**Comment by r0tifer** [comment]
I agree with others that having the ability to manage the Dashboard from within the Theming menu would be helpful. Additionally, I would like to include the suggestion to manage font colors used on the dashboard.

**Comment by luminous706** [comment]
Would be nice to have a way to achieve this via the GUI instead of the CLI.

**Comment by diemelone** [comment]
Are there any news regarding this topic? I am really hoping for that feature to be implemented.
A useful option would also be instead of overwriting everything, just add new widgets for example after installing a new app (e.g. deck) I want to add that widget to every dashboard for users in group "group-deck-users" but not change their current layout or settings more that that.

**Comment by RobertRoberts2020** [comment]
Why is this closed?

**Comment by Mte90** [comment]
> Why is this closed?

My guess is that they just implemented on occ level with no UI for this https://github.com/nextcloud/server/issues/25553#issuecomment-866742281
So is not possible everywhere as a lot of hosting doesn't let you to use CLI...

**Comment by PaxJaromeMalues** [comment]
Implementing this above occ level as an admin UI option should have been an absolute no-brainer upon touching the occ functionality.
How come this hasn't been implemented in over 5 years?
Is it a permission:access sort of difficulty?

edit: pls excuse all the comment edits, I am currently learning blind typing.

edit2: no-brainer clarification. Removal of passive aggressive comment.

**Comment by luflow** [comment]
@PaxJaromeMalues You can just open a PR 👍🏻  Looks like no one needed it as UI setting so urgently until now. But its open source, so why not contribute to a nice admin panel for that 🤓

**Comment by PaxJaromeMalues** [comment]
> @PaxJaromeMalues You can just open a PR 👍🏻  Looks like no one needed it as UI setting so urgently until now. But its open source, so why not contribute to a nice admin panel for that 🤓 

If I could I would. I have translated a bunch for Canonical once but that is really all I can do. I am a script kiddie at best, as can be seen on my profile. I have zero dev experience nor do I know how to code software or UI.

Edit: if you commented because I said "no-brainer" I thought it was clear I meant "this option should be available in UI" as a thought that should have jumped right into the face concerning UX, once the occ issue was touched.
