### ISSUE TITLE
Exception: Repair step 'OCA\DAV\Migration\GenerateBirthdays' is unknown

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2566]
RC1:

```
Exception: Repair step 'OCA\DAV\Migration\GenerateBirthdays' is unknown

    /media/psf/nextcloud/lib/private/Migration/BackgroundRepair.php - line 91: OC\Repair->addStep('OCA\\DAV\\Migrati...')
    /media/psf/nextcloud/lib/private/BackgroundJob/Job.php - line 53: OC\Migration\BackgroundRepair->run(Array)
    /media/psf/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 54: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
    /media/psf/nextcloud/lib/private/Migration/BackgroundRepair.php - line 64: OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
    /media/psf/nextcloud/cron.php - line 145: OC\Migration\BackgroundRepair->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
    {main}
```

**Comment by rullzer** [comment]
well yes... it is removed. Probabaly a leftover in the db...

**Comment by MorrisJobke** [comment]
> well yes... it is removed. Probabaly a leftover in the db...

We then should then log this and drop the job.

**Comment by LukasReschke** [comment]
Should we? Shouldn't we not prevent upgrading in such cases then?

This is likely because I updated from 9 -> 10 -> 11 in a very short timeframe and this one got removed?

**Comment by MorrisJobke** [comment]
We do the same for cron jobs itself:

https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/lib/private/BackgroundJob/JobList.php#L248-L256

**Comment by MorrisJobke** [comment]
> This is likely because I updated from 9 -> 10 -> 11 in a very short timeframe and this one got removed?

Told you so: https://github.com/nextcloud/server/issues/2270#issuecomment-265729897 🙈

**Comment by schiessle** [comment]
> We then should then log this and drop the job.

This doesn't sound right to me. The repair job was there for a purpose. Just drop it and don't care that the issue was never repaired can't be the solution.

**Comment by MorrisJobke** [comment]
> I don't think we can compare this with cronjobs. Typically cronjobs perform regular actions, if the action is no longer supported because the app was deactivated, the feature was removed,... it is totally fine to drop the cronjob.

True point :+1:

**Comment by rullzer** [comment]
Well we insert them into the cronjob system. The error here only can occure for people that do 10 => 11 beta => 11 rc. Since the code is removed in the RC. And this would mean that that (as @LukasReschke probabaly did) upgrade quickly on that path.

I mean that is what you get with background repair jobs. If people upgrade before the job was run it throws an exception because the code is no longer there.

**Comment by MorrisJobke** [comment]
> I mean that is what you get with background repair jobs. If people upgrade before the job was run it throws an exception because the code is no longer there.

And maybe the step to prevent this now: "don't remove the background job code" (or revert the removal)

**Comment by rullzer** [comment]
No because the background job was what caused the issues with invalid ical stuff.

**Comment by schiessle** [comment]
Just thinking... Maybe we can detect in advance if there are some repair jobs left and warn the admin, including the option to run the repair steps first and then do the actual update. For manual updates we could refuse to run the upgrade so that the admin has a chance to copy back the old version and perform the repair steps before he continues.

I fear that really bad things can happen if we just throw away the repair jobs.

**Comment by MorrisJobke** [comment]
> Well we insert them into the cronjob system. The error here only can occure for people that do 10 => 11 beta => 11 rc. Since the code is removed in the RC. And this would mean that that (as @LukasReschke probabaly did) upgrade quickly on that path.

Not that likely anymore to happen and in case we would have a workaround -> close
