### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by DrAxelbauer** [nextcloud/server#25692]
Hi there!
Since about 1 month I am struggeling with a critical Server Error, which seems to be inside NC.

Error description:
1. Trying to log in to my NC via Browser
2. Internal Server Error directly after the login attempt

All my sync clients (Joplin Note Sync, Calender) are not syncing. 
Nothing in the Serverlog or php log only a log with Code 500.

The problem seems to be initiated either by the Joplin Sync Client or the Calendar Client. I am not sure about it. Maybe it has to do with Webdav/Sabredav.

What i tried to solve the issue:
1. Upgraded my NC from 18. all the way up to the newest version 20.  But still the same issue after about 2 weeks running time. Within the 2 weeks NC seemed to have worked as expected.
2. sudo -u www-data php occ maintenance:repair did crash the server fully. Login Page is not loaded any more:
`Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.`

Here is the Error from Joplin's Sync Client:
`Error: GET info.json: An exception occurred while executing 'INSERT INTO `shw18_file_locks` (`key`, `lock`, `ttl`) VALUES(?, ?, ?)' with params ["files\/fc7b57b2da41edd2c9a19c0a431ef195", 1, 1613562776]: SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'oci-qpjxmmkl94'@'10.0.0.61' for table 'shw18_file_locks' (Exception Sabre\DAV\Exception) (500): <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>`

I appended the nextcloud.log I hope there is some info in there:
[nextcloud.log](https://github.com/nextcloud/server/files/5995103/nextcloud.log)

Help really appreciated, due to some critical data ;) THX. Benjamin.

**Comment by freebrowser1** [comment]
Here as wel with NC21 RC2. Logging in and other tasks do work normally, but when changing System Settings a 500 error occurs and nothing is logged into the error.log of Apache.

Function  OCA\ServerInfo\sys_getloadavg() does not exist.

`
Error | index | Exception: Call to undefined function OCA\ServerInfo\sys_getloadavg()/data/data/com.termux/files/home/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "index")/data/data/com.termux/files/home/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("OCA\\Settin ... r", "index", OC\AppFramew ... {}, { section: " ... "})/data/data/com.termux/files/home/nextcloud/lib/base.php - line 993: OC\Route\Router->match("/settings/admin/serverinfo")/data/data/com.termux/files/home/nextcloud/index.php - line 37: OC::handleRequest()Caused by Error: Call to undefined function OCA\ServerInfo\sys_getloadavg()/data/data/com.termux/files/home/nextcloud/apps/serverinfo/lib/SystemStatistics.php - line 68: OCA\ServerInfo\SystemStatistics->getProcessorUsage()/data/data/com.termux/files/home/nextcloud/apps/serverinfo/lib/Settings/AdminSettings.php - line 118: OCA\ServerInfo\SystemStatistics->getSystemStatistics()/data/data/com.termux/files/home/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 138: OCA\ServerInfo\Settings\AdminSettings->getForm()/data/data/com.termux/files/home/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php - line 83: OCA\Settings\Controller\AdminSettingsController->formatSettings([ [ OCA\Serv ... ]])/data/data/com.termux/files/home/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 149: OCA\Settings\Controller\AdminSettingsController->getSettings("serverinfo")/data/data/com.termux/files/home/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php - line 68: OCA\Settings\Controller\AdminSettingsController->getIndexResponse("admin", "serverinfo")/data/data/com.termux/files/home/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\Settings\Controller\AdminSettingsController->index("serverinfo")/data/data/com.termux/files/home/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "index")/data/data/com.termux/files/home/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "index")/data/data/com.termux/files/home/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("OCA\\Settin ... r", "index", OC\AppFramew ... {}, { section: " ... "})/data/data/com.termux/files/home/nextcloud/lib/base.php - line 993: OC\Route\Router->match("/settings/admin/serverinfo")/data/data/com.termux/files/home/nextcloud/index.php - line 37: OC::handleRequest()
-- | -- | --


`

**Comment by kesselb** [comment]
> Here as wel with NC21 RC2. Logging in and other tasks do work normally, but when changing System Settings a 500 error occurs and nothing is logged into the error.log of Apache.
It runs in a prooted environment.

Marked the comment by freebrowser1 as off-topic because it's unrelated.

> INSERT command denied to user 'oci-qpjxmmkl94'@'10.0.0.61' for table 'shw18_file_locks'

Sounds like a database permission issue?
