### ISSUE TITLE
coloring of external storage folders not working

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#2574]
With Nextcloud 11RC1, I notice that the folders follow the color scheme, with one exception:
![spectacle t11492](https://cloud.githubusercontent.com/assets/551757/21022022/6913e1bc-bd7b-11e6-9f20-5ed2c3ec1658.png)
The external storage folder stays blue. I guess we should try to fix this, yes?

@nextcloud/designers ?

**Comment by juliushaertl** [comment]
I just had a quick look, this happens because the files_external app is overriding the icons from the mimetype javascript code. https://github.com/nextcloud/server/blob/7e6f829d546a95acc3421c5fd9dd7574fa291994/apps/files_external/js/statusmanager.js#L518-L559

We could either add a check for OCA.Theming in the files_external or add the theming globally to the JS imagePath function like I did it with the PHP function in #840. I need to think a bit about what makes more sense. 

@icewind1991 Is this extra code in files_external still needed? It looks like they were just for windows_network_drive and sharepoint apps which are not available for Nextcloud at the moment.
