### ISSUE TITLE
Workflow: Move file by filename

### ISSUE THREAD

**Issue by Discostu36** [nextcloud/server#25789]
I learned about workflows today but noticed that there are not many workflows available yet. I think it'd be great to have an automatic move of files by filename or file type:

1. I upload into a special folder ("File Inbox")
2. If the filename includes "school" the file is automatically moved to the folder "/school"
3. If the file type is .jpg or .jpeg the file is automatically moved into the folder "/photos"

This idea seems to be quite old, see [this forum thread](https://help.nextcloud.com/t/automatic-moving-of-uploaded-files-to-another-folder/12820/2) for example, but I couldn't find a GitHub issue about it.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
