### ISSUE TITLE
Themes per user/group

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2601]
So I've been considering a couple of things, mainly around splitting my NC install off into personal/work profiles to share with colleagues as an alternative to Dropbox at the office.

In thinking about this I recalled the work install I setup with owncloud and a company branded theme a long time ago and wondered:

Would it be possible to offer a theme based on user group? If I were to open the install to colleagues they'd all sit in a company group and applying a branded theme would be super useful without setting it globally.

It's such an option feasible?

I'd be happy with one generic login, but different colours for different groups, maybe even different logos in the top left too.

Context: https://help.nextcloud.com/t/user-group-based-themes/2070/3

**Comment by nickvergessen** [comment]
And for public pages etc?

**Comment by nickvergessen** [comment]
Honestly I don't think we should go down this road.

**Comment by jasonbayton** [comment]
That would be great. Presumably if themes could be assigned based on group, folders created by people in a group could pick up on the relevant metadata too?

**Comment by juliushaertl** [comment]
> That would be great. Presumably if themes could be assigned based on group, folders created by people in a group could pick up on the relevant metadata too?

What should happen if people are in multiple groups?

I'm absolutely with @nickvergessen. This would add way to much complexity for a very small use case.

**Comment by jasonbayton** [comment]
> What should happen if people are in multiple groups?

Precendence setting on the user's entry. But if you're theming based on group it wouldn't make sense to actively put users into multiple themed groups necessarily.

**Comment by nickvergessen** [comment]
@jasonbayton I get your idea, but as julius also just said:

> This would add way to much complexity for a very small use case.

Feel free to write an app for that, but I don't think we should do that in the server.

**Comment by dseeker** [comment]
we could this working fairly easily. there is already an app that allows us to add [custom CSS](https://apps.nextcloud.com/apps/theming_customcss)
the piece that's missing is adding the group name as another head attribute, similar to how we have now with `data-user` and `data-user-displayname` does. 
this way we can specify on the custom css app targeting this document attribute, because they are in HEAD we need to use a sibling to body selector, and we can also have multiple values

groups this user belongs to: Client, Support
```html
<head data-user="ds" data-user-displayname="David Silviero" data-user-group="client,support">
```

in Custom CSS App
```
[data-user-group*="client"] + #body-user #header,
[data-user-group*="client"] + #body-settings #header,
[data-user-group*="client"] + #body-public #header{
	background-color: #F0F;
}
```

I saw these values are added in https://github.com/nextcloud/server/blob/master/core/templates/layout.user.php#L3
but I have no idea how to get the groups the user belongs to into that document, can someone help?
