### ISSUE TITLE
1. 点击tabbar 菜单，a标签的点击事件有重复点击事件，一个是href点击，一个是onclick点击

### ISSUE THREAD

**Issue by zhengxianyu** [nextcloud/server#26187]
1. 点击tabbar 菜单，a标签的点击事件有重复点击事件，一个是href点击，一个是onclick点击

**Comment by j-ed** [comment]
@zhengxianyu Unfortunately no-one is able to speak or understand Chinese language in this forum. Please use English to report any issues and also provide DETAILED information about your environment, the used software versions and how your problem can be reproduced, otherwise the ticket will be closed.
