### ISSUE TITLE
Feature - Send2Link for non users (Nextcloud App)

### ISSUE THREAD

**Issue by hoergen** [nextcloud/server#26235]
A new feature "Send2Link" where you can store an upload URL, like a server bookmark and use it to upload data with your smartphone.
So you are able to use the share function of your smartphone from any app to send files to a Nextcloud share, without having an account on that Nextcloud server.

**Background**: I want to give listeners of my podcast "Besser - Der Podcast"  the opportunity to send in audio messages without joining any service or app or provider or anything. For that I create a public Nextcloud share for a defined time where people can normally upload audio messages via browser. 
But it would be far better if people can record their message on their smartphone and share this message directly via a "bookmarked server" to this share. 

I thought about that workflow:

**Installation & Configuration**
1. User can ...
2. scan QR code (URL)
3. or send link to Nextcloud App
4. or set it by copy&paste
5. Give it a name manually or given by QR Code
6. Have an entry in their Nextcloud App "Servers list"

**Sending Data**
1. Select the data you want to share
2. use the "Share" function on your smartphone
3. select Nextcloud App
4. select configured link/URL by name
5. send your data
 
Such a solution would make a lot of those "specialized" apps unnecessary and give e.g. a lot content providers new possibilities.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
