### ISSUE TITLE
Hide shares name on public shares

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#26541]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
As a user I want to be able to disclose my name from public shares, because 
a) my organisation has a policy not to expose personal infomations of our employes (Organisation's force) 
b)I don't want my name to be exposed on wide spread shares. (user decision based on self determinated privacy)

**Describe the solution you'd like**
Define on a per share basis or add the possibility to hide the username as an admin setting.

**Additional context**
#9789

**Comment by jospoortvliet** [comment]
There is a bunch of work-arounds that will cover most (but not all) use cases for this.

1. You can simply link to the link with /download appended, so no page gets shown at all but the download starts immediately
2. You can share from a different, dummy user account
3. You can hide the user name by using this CSS trick: https://help.nextcloud.com/t/how-to-remove-shared-by-name/32492/5

If you can not use a dummy account AND don't want to deep-link (for example because you want to allow uploading or editing) AND you want to be able to do this on a per-share basis or don't want to disclose the name even in the source code of the page (solution 3 works only for ALL shares on the server, the user name is still visible in the code of the page, just not in the UI) you would need an option in the share menu that hides your user name.

As we don't want to overload the share menu with options that are useful only in a 0.0001% case, making it harder for everyone, just adding the option to the existing, already too long menu would not be acceptable. So how to approach this problem?
* A solution for that would be to make this option only available after a server admin has enabled it, but that would result for sure in a code path that would pretty much NEVER be tested and very likely to regularly break - creating a lot of work. 
* So the only option I see to get this changed is once/if/when we redo the whole sharing menu in a way that scales better with more (obscure) options and settings for each share. We do want to do this, but there is no time frame for this - it won't be done in the first half of 2021, at least. After that rework is done, the usual process will have to kick in: somebody has to feel like doing this and can then write code for this and submit a pull request. Or somebody who wants it hires somebody that does it, of course. The core team is very unlikely to do this as we have to focus our efforts on very common use cases.

If you need this feature, you can let us and anyone who might be interested in implementing it know by giving a 'thumbs up' to the original issue on top of the page by @dartcafe  (please do not post a "I want this too" kind of comment, that makes it hard to have a substantive discussion).

If I missed anything, let me know.

**Comment by szaimen** [comment]
I have another idea how this could be solved: maybe allowing the server admin to enable/disable this for all accounts for public share links would be a good solution? (If this option gets enabled by the admin, it would never show the username of any user on public pages).

**Comment by dartcafe** [comment]
Sorry @jospoortvliet, but your comment is not helpful. There is a feature request and you answer with a lot of caveats and reasons, why this is difficult and expensive and not worth the work. This is not how customer centricity works. 

> that are useful only in a 0.0001% case

Can you quote the survey which covers your argument? I would say it is useful in 50%. 😁 Seriously, I doubt that only 1 user out of 1.000.000 user would request that feature. There where at least 5 users in the other threat, who have use cases for that. 😉 

I believe, that we should first think in values for the customer and than what it costs, if we found a good UX solution. And then the balance between costs and value decides over the development or its priority. And the value is not defined by your or my personal opinion, it is decided by the customer.

Why do I think this feature has a value for the users AND for nextcloud? 
I think it's in the interest of nextcloud to get spread in private and commercial environments and @spackmat described a real world example https://github.com/nextcloud/server/issues/9789#issuecomment-810117245, which you can find in other organisations as well. This could make the feature a key feature. 

And to tell from our organisation, or work-around simply is using other services for sharing files if we don't want to expose user's personal information. For my private installation in constrast I don't care about that.

And hiding the user name is no privacy solution. I.e. in polls users often request real anonymous polls, which I personally deny because it is not in the focus of polls to support elections or other confidential surveys and we cannot guarantee anonymity by design. And therefore we try to avoid pretending polls can do that.

At last as a devolper, I definitely see your points and the caveats. But in real life I got more than once suprised by UX designers, how complicated things could be realized easily for the user. And that raises user acceptance and that raises the level of utilization.

**Comment by bpcurse** [comment]
@jospoortvliet @karlitschek There is another important argument and I am wondering why it hasn't been stated yet:

Legal implications regarding GDPR: This default violates Articles 5(1) lit. c, 25(2) and probably in many cases Art. 12 GDPR. See also Art. 6 and 7.

Although it does not if the instance is used solely for private (family) usage, it is applicable to all other users, especially enterprise customers.

Imagine your full name is registered in the corporate Nextcloud as display name (maybe infos like division or office are appended) and you share a link on behalf of the company to social networks or websites. Your personal data is then disclosed to the internet and you don't even know about the fact if you do not open the link yourself as a non-registered user or if someone informs you.
I personally have been surprised by this fact as there is no evident info that personal data is added when sharing a link.

Affected users can file a complaint to the supervisory authority based on Art. 77 GDPR which can lead to severe penalties.
Art. 83(5) GDPR: "administrative fines up to 20 000 000 EUR, or in the case of an undertaking, up to 4 % of the total worldwide annual turnover of the preceding financial year, whichever is higher"

This should make it clear that keeping personal data from being publicly accessible is **not** an optional feature, it is a legal obligation.

**Comment by newhinton** [comment]
Maybe a way to go would be to "remove" most of the settings, and only keep the 3 most important ones, while adding a "more settings" button, which opens a modal with all the settings that are available. This allows to better group everything, and possibly even add explanations where necessary, but i don't know if that breaks with nextclouds general design guideline.

In any case, one possible way to supply this override could be to copy the existing "note to recipent" option.
If it is left alone, the default username is shown. If it is checked, a textbox opens where you can supply a new name. If it is empty, just show "X was shared with you" in the shared fileview. If not, just replace it.

There could be a case for making it the default setting to not show a user's name, privacy by default so to speak

**Comment by szaimen** [comment]
Ref https://github.com/nextcloud/server/issues/22072

**Comment by szaimen** [comment]
On NC21.0.2 the avatar and username don't get shown on shared link sites in my testing. 
Can you all reproduce this? Because in this case we can close this issue, no?

**Comment by dartcafe** [comment]
As the removing of the avatar is by intention and for privacy reasons, I would agree that this issue is done.
