### ISSUE TITLE
Add excluded_directories as config option

### ISSUE THREAD

**Issue by thopico** [nextcloud/server#26651]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
An Owncloud instance I administrate has lots of directories with tons of irrelevant files (eg temporary files or symlinks) on local and external storages. For now, we can use the `excluded_directories` option to tell OC to completely ignore the directories matching some patterns and to not include them in DB.

We would love to migrate our users to Nextcloud, but we can't find such option available. Nothing in the doc, and #6888 mention the app [files_excludedirs](https://github.com/nextcloud/files_excludedirs) which doesn't seem to live anymore. I believe there is a few more people [hoping for this feature](https://help.nextcloud.com/t/exclude-blacklist-hide-folders-eg-from-occ-files-scan/92739) as well.

**Describe the solution you'd like**
Would be great if this option was also available on NC, either natively or through a custom app.

**Describe alternatives you've considered**
Haven't found any alternative.

**Additional context**
If someone has enough time to develop this feature, a bonus would be to accept wildcards in patterns.

Thank you

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers

**Comment by thopico** [comment]
I moved the feature request to help.nextcloud.com as requested : https://help.nextcloud.com/t/add-excluded-directories-as-config-option/119671

**Comment by rightsaidfred99** [comment]
Would be great to have. 

Having a hard time where clients are downloading directories with @eaDir folders everywhere from the NAS

**Comment by GuyPaddock** [comment]
Please give this unsigned release a spin; should work on 23x.:
https://github.com/Inveniem/nextcloud-files-excludedirs/releases/tag/v1.0.0-beta

I've provided updated docs in my fork of the Readme (specifically, how it works with existing vs. newly-added files):
https://github.com/Inveniem/nextcloud-files-excludedirs/blob/master/README.md

Feedback is welcome here:
https://github.com/Inveniem/nextcloud-files-excludedirs/issues

I'll have to look into publishing an official, signed package because I wasn't the original author of this one -- I just updated the work of others.

**Comment by wonx** [comment]
I tried it on my 24.0.2 Nextcloud. It lets me activate the app, but I don't think it's actually paying attention to my exclusion rules.

I have a folder that I want to exclude in `/user/files/Warehouse/Library/` (a Calibre library, containing thousands of folders that really slows down the scan). So I ran the following:
` occ config:app:set files_excludedirs exclude --value ["Warehouse/Library"]`

and then I rescan the library using: `occ files:scan user --verbose`
However I still see that folders within Warehouse/Library are still being scanned to the database.

Am I doing something wrong? Is it just that it is still not compatible with Nextcloud 24?
Also, is there a way to check what are the current excluded dirs?

**Comment by GuyPaddock** [comment]
@wonx Did you see my note here? https://github.com/Inveniem/nextcloud-files-excludedirs/blob/master/README.md#removing-unwanted-existing-files-from-nextcloud-file-cache

**Comment by wonx** [comment]
Yes. But I assumed that was to remove the existing files from the database. For now, I just wanted to test if adding an exclusion, the scan process would ignore that particular folder (which apparently didn´t). Is it because I'm using Nextcloud 24 and the excludedirs app is only compatible with nextcloud 23 and lower?

**Comment by GuyPaddock** [comment]
@wonx Hmm, I haven't yet tested with 24 so I am not sure. I know that on 23 it took effect for my next scan and matching files did not get added. Can you file an issue on my fork and let me know what your exclusion patterns look like and provide an example of an absolute path that's not matching?

**Comment by wonx** [comment]
@GuyPaddock I can't seem to create an issue, it redirects me to Pull requests instead. Maybe you have to enable that option in your repository?

**Comment by GuyPaddock** [comment]
@wonx Sorry about that; just added it. Also, I've discovered a show-stopper issue on login that I need to address (https://github.com/Inveniem/nextcloud-files-excludedirs/issues/1).

**Comment by SimJoSt** [comment]
It seems this functionality can be achieved with Nextcloud Flow and the File access control : https://apps.nextcloud.com/apps/files_accesscontrol
GitHub: https://github.com/nextcloud/files_accesscontrol
Docs: https://docs.nextcloud.com/server/stable/admin_manual/file_workflows/access_control.html#prevent-uploading-of-specific-files

On the path `/settings/admin/workflow` of your Nextcloud you can set it up.
