### ISSUE TITLE
Consider about One-Page layout for administration

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#267]
The fact, that we have introduced some new administrative settings like **Theming**, **Password Policy** (and more to come... see https://github.com/nextcloud/user_saml/pull/16 for the saml-using guys) makes me thinking about whether it makes sense to put all these things on one single page.

It would may make sense to:

- give every option an **own page** you could access with the left-side bar 
- introduce **new categories** (status, user authentication, sharing, ...) and order settings into these categories
- ...

What do you think?

cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
I guess this would make it a bit cleaner, but on the other side it's harder to find settings.

**Comment by mar1u5** [comment]
Just one keyword: search :sweat_smile: @MorrisJobke

**Comment by jancborchardt** [comment]
It was actually the intention for oC 9.1 (I think) to have one proper section per thing in the admin settings instead of a whole scrollable page. Also, to combine personal and admin settings. In the whole forking stuff of course that kinda went under. ;)

I will check to find the original issue tomorrow.

**Comment by ungesundes-halbwissen** [comment]
I'd like to leave my "no-dev-enduser.only" point of view, as I happen to remember, that it was the admin page itself of which I thought "wow, that's a bit awkw... eh ....non-intuitive" when I first laid my eyes on owncloud 4.0.x a few years back. To be honest, I struggled to find some of the settings I was looking for simply because I didn't expect the page to feature topics OTHER than what I saw on the screen right away. It was like "ok, here's security warnings and sharing config, but where on earth are the logfiles"

While this admittingly might have been stupid and short-sighted, I'd still be glad for some less "bulky" design.

Now, that this is said...

I know, the following might be due to me gotten used to the admin page by now, but with the clickable sidebar options you all have for sure moved in the right direction. Perhaps elaboration on that is already good enough: just divide the one long page into several small ones, accessible by clicking the existing sidebar and you are done.
If for some reason you want to stick to the "one admin page" approach, the various section could do with some distinction at least: how abut a box frame optically separating (and grouping for that matter) security warnings from share configuration from federation from ... tbc

**Comment by MorrisJobke** [comment]
> guration from federation from ... tbc

That was removed by intention to unclutter the interface

**Comment by jancborchardt** [comment]
> just divide the one long page into several small ones, accessible by clicking the existing sidebar and you are done.

@ungesundes-halbwissen as said above, that’s exactly the design plan. Someone just needs to implement it. If you have any developer friends who can help, feel free to point them to this project. :)

**Comment by ungesundes-halbwissen** [comment]
@Jan-Christoph Borchardt I seem to have misread that, thanks for the heads up. I didn't want to steal anybodys time. Sorry!

**Comment by ChristophWurst** [comment]
Here's the original ticket: https://github.com/owncloud/core/issues/24188.

What should that look like? Split all the sections into separate pages and only show one section at a time? That *could* work, although I'm worried about breaking the JavaScript of some apps that expects the section to be shown when the page is loaded. AFAIK we don't have control over when JS files are loaded on the settings pages.

**Comment by jancborchardt** [comment]
@ChristophWurst yeah, basically as you described it. What would be the problem with the JS? Cause the pages could be there in the DOM, just not visible. That would also make sure that navigating the page is very fast.

**Comment by jancborchardt** [comment]
I’m closing this in favor of https://github.com/nextcloud/server/issues/712 because we talked more about it and have a more detailed writeup there. :)
