### ISSUE TITLE
Public link doesn't work if a slash is added at the end

### ISSUE THREAD

**Issue by biva** [nextcloud/server#26822]
When I share a public link (https://nexcloud.server.com/s/HJOejfIeJL8 for example), it doesn't work if a slash is added at the end (https://nexcloud.server.com/s/HJOejfIeJL8/) → it lands on the login page.

This is not a big issue, but a slash can be added by mistake and it creates confusion.

Would it be possible to make it work also with the slash at the end?

(this is the same with the direct download link: https://nexcloud.server.com/s/HJOejfIeJL8/download works but https://nexcloud.server.com/s/HJOejfIeJL8/download/ doesn't work)

**Comment by szaimen** [comment]
Hi, thanks for your bug report!
Since I don't aggree that "a slash at the end can be added by mistake" is a valid argument (you might also add any other character to the end of the link by mistake which will also end with a broken link), I am going to close this issue now. You might talk to your staff instead, if they add slashes to links.
