### ISSUE TITLE
Dashboard Option to change icon or header background color

### ISSUE THREAD

**Issue by schlagmichdoch** [nextcloud/server#26873]
When Using a Picture with white parts, the transparent header makes icons appear transparent.
A Option to change the icon color or header background color would be great.

**Comment by pieter-groeneweg** [comment]
@artonge
"nice to have" is not the same as "oops, didn't think of that".

# header css was added by the devs of the dashboard. the ribbon is supposed to show when fully scrolling down?
At least that happens when I have a smaller than monitor window in my browser (FF, Chrome) But only if the widgets are bigger than the available space. On a maxified browser window nothing happens. Bug?

Take out all #header styles from the css and the ribbon is respected as set in the theme settings.
That is the way it is expected by the admins.
Since it probably will come back with an update, I am sorry to say, I now am left with disabling the dashboard since your "theme design addition" breaks mine.

The issue is already acknowledged for version 21 (https://github.com/nextcloud/server/issues/22864)  But it would be nice and welcome to take the #header stylings out for current 20 which is stil an active version.

**Comment by quentinDupont** [comment]
Hello !
@schlagmichdoch I had the same issue.
I installed https://apps.nextcloud.com/apps/theming_customcss and add in Custom CSS (admin panel > theming) : 

#header[role="banner"]{
   background-color: var(--color-primary-element)!important;
}

The only problem with this workaround is that I didn't suceed to have a different css betweend Dashboard and the rest of Nextcloud
