### ISSUE TITLE
Delete a file while uploading a file hides the upload bar

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#27220]
* having a folder with a single file in it
* upload a longer running upload (I used a file that is a few hundred MB)
* delete while the upload is running the file in the folder
* the file is removed from the UI properly
* expected: the upload bar continues to show the progress
* actually: the bar hides and only the cancel button is visible - after some time the upload finishes and is shown in the file list properly

Tested on 21.0.2

cc @nextcloud/javascript @skjnldsv

**Comment by gary-kim** [comment]
To add, the issue seems to be that removing a file calls `reportOperationProgress` which at the end calls `hideProgressBar` regardless of whether there was an operation occurring when the removal started. I suspect this occurs with other long operations such as moving a large number of files (testing right now).

https://github.com/nextcloud/server/blob/96515d7338006a99b853c899708d7f6667bd43fd/apps/files/js/filelist.js#L3138

https://github.com/nextcloud/server/blob/96515d7338006a99b853c899708d7f6667bd43fd/apps/files/js/filelist.js#L2528

**Comment by blizzz** [comment]
still a thing?

**Comment by MorrisJobke** [comment]
Yes - verified on 24.0.5

**Comment by MorrisJobke** [comment]
@skjnldsv If you need help with reproducing, just ping me 😊
