### ISSUE TITLE
Make sharing of images more straightforward

### ISSUE THREAD

**Issue by mankeli** [nextcloud/server#27427]
One of my primary usecases with NextCloud is project screenshot sharing. Basically I would like to take a screenshot to clipboard, directly paste it into browser and just copy share link back to clipboard. (Imgur does this pretty neatly, but I would like to keep the data on our own server)

Currently the procedure involves saving screenshot to a disk, uploading it, clicking open the share menu, creating share link.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
