### ISSUE TITLE
Personal-/Group-Vault

### ISSUE THREAD

**Issue by Shen** [nextcloud/server#27840]
Currently, it is possible to increase data security and access security via encryption or two-factor authentication or eID-Login, for example.
Nevertheless, it would make sense to have a kind of vault for the most important and particularly sensitive data.

This vault should be a protected area in Nextcloud that you can only access with a strong authentication method or a second step of identity verification, such as PIN or email or hardware-token or the new eID-feature.

Microsoft has already implemented this in OneDrive: https://www.microsoft.com/en-us/microsoft-365/blog/2019/09/30/onedrive-personal-vault-expandable-storage-available-worldwide/

In Nextcloud, a vault could be integrated in connection with Circles or Group-Folders. Thus, there could either be the option for users to create vaults themselves or an admin could create vault group folders.

Functions should be:
- a strong authentication method
- An encrypted directory
- an automatic logout function
- limited rights to share files

Many of these functions already exist and would need to be brought together in a vault concept.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers

**Comment by jospoortvliet** [comment]
sounds like this is end-to-end encryption - no access on the web, of course.
