### ISSUE TITLE
Set user status automatically (based on e.g. being in a call or events)

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#27990]
Status can automatically change depending on what event is happening
- Call started
- Event matching specific criteria
- ... ?

To be discussed:
- Setting page for this feature:
  - Should this be configurable ?
  - What can be enabled/disabled ?

cc @jancborchardt

**Comment by ChristophWurst** [comment]
> Event matching specific criteria

It's simple. Any event in a calendar that is not *transparent* and where the status is set to *busy*. Sabre and free/busy will do this. We don't need to define our own logic for this.

**Comment by jancborchardt** [comment]
Design spec based on a call with @CarlSchwan and @nimisha-vijay 

* **Talk:** Set an automatic status when you are in a call
  * Do not disturb, with "💬 **In a call**" as custom message
  * Teams also does this
  * Talk busy status takes precedence over calendar because there we can for sure say that you are in a call.
* **Calendar:** Set an automatic status when you are in a meeting
  * Do not disturb, with "**📅 In a meeting**" as custom message
  * Should only take into account "busy" status. Full day events are also "busy" by default, possibly check with that.
    * Make sure to not leak event title into status (e.g. customer names) → Just set "In a meeting"
    * Drawback: We don’t know if it’s a vacation or what exactly
    * What about if you are at the dentist or other appointment → maybe better wording is needed
* Mail (maybe, low priority): Set an automatic status when you are traveling
  * Do not disturb, with "**🚌 Traveling**" as custom message
  * Based on the itinerary information. Although this is probably something people added to their calendar anyway.
  * Doesn’t catch when commuting via public transport or bicycle or car → Hence not "Commuting" but "Traveling"

**Questions & clarifications**
* What happens when a status is set and you don’t want it? → If someone sets a custom status over the "In a meeting" one, that is respected of course.
* Ideal would be showing the status icon over the avatar in the top right so you are aware if you are set to do not disturb e.g.
* When the meeting/call is over, ideally set back to the previous status

**Comment by jancborchardt** [comment]
@ChristophWurst right, good point on the "reset to previous status", moved it up in the list.

Regarding the "preferred status" setting, is this something which you know from other solutions? (And if we would have a setting like that I assume the place to put it would be the app itself, in this case Calendar?)

**Comment by ChristophWurst** [comment]
> Regarding the "preferred status" setting, is this something which you know from other solutions?

Nope, this is just how I imagined this could work.

Nevertheless I found https://support.microsoft.com/en-us/office/change-your-status-in-teams-ce36ed14-6bc9-4775-a33e-6629ba4ff78e

> If you’re in a meeting or call, Teams will automatically change your status to In a meeting or In a call (Busy) when not set to Do not disturb.

Which is interesting. You could possibly derive the info about whether the current busy event is a meeting or an ordinary event based on whether there are participants. But then again *meeting* is very specific. Maybe I'm meeting a friend in the park and invite them. That's not a meeting. :shrug:

**Comment by CarlSchwan** [comment]
Some small MRs implementing the feature for Talk:

* https://github.com/nextcloud/server/pull/28403
* https://github.com/nextcloud/spreed/pull/6110

**Comment by nickvergessen** [comment]
> Talk: Set an automatic status when you are in a call
Do not disturb, with "💬 In a call" as custom message

This is fatal to Nextclouds notification system. For me it would mean that I mostly never get any push or browser notifications anymore. I guess it's similar on Teams which is why Busy sounds more logical.

Also what if the meeting/call is secret?

**Comment by Pilzinsel64** [comment]
> Also what if the meeting/call is secret?

As I know from Teams and Skype for Business you can't really change "In Call" status before. But you can set how you are available in a meeting in the Calendar. See here in Outlook:
![grafik](https://user-images.githubusercontent.com/23138465/143395398-56af2d52-f0a0-48a3-8182-261f50ce86f3.png)

"Frei" and "An anderem Ort tätig" basically don't change your status for the time of the event.
"Mit Vorbehalt" and "Gebucht" sets your status to "Busy.
"Außer Haus" sets your status to "Away" to signal that you are not at work or on the PC and not available.

And that's why I would suggest more to add one more Status "Busy" that basically is like "Online" but green and another text. You still get notifications there, like on "Online" and "Away" or "Offline".
But also keep "Do not distrube" or "Nicht stören" where you don't get any notifications, how it is already in.
See how it is in Skype for Business and Teams:
![grafik](https://user-images.githubusercontent.com/23138465/143395985-f2db00fd-c2d0-45c1-96e1-83798fff23b9.png) ![grafik](https://user-images.githubusercontent.com/23138465/143396025-9d1618da-afc6-4014-8d50-45e4dcdb12df.png)
