### ISSUE TITLE
Migration error on update to 22.0.0

### ISSUE THREAD

**Issue by reitbauer** [nextcloud/server#27998]
I tried to update to version 22.0.0.
if I'm click on "Start update" I get the following error:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/31218726/125845856-4e3d6ed6-76dd-4591-965d-a60b5aae0b8d.png">

**Operating system:**
Debian 10.10 with Docker (v 20.10.7, build f0df350)

**Image**
nextcloud:latest

**Database**
mariadb:latest

**Comment by kesselb** [comment]
Nextcloud does **not** support MariaDB 10.6 for now. The reason is the compressed row format.

A possible solution is:
- To stick with MariaDB 10.5 
- `--innodb-read-only-compressed=OFF` to make compressed tables writeable again.

https://github.com/nextcloud/server/issues/25436 is the issue to track the progress. It's on the roadmap. A solution requires a migration of the row format to something different. Don't expect this migration for Nextcloud 22 / 23.
