### ISSUE TITLE
Server side scheduling

### ISSUE THREAD

**Issue by m707** [nextcloud/server#2800]
Since summer invitations of calendar component of (o)NC are unusable for me. In mozillas bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1297009

it turned out that the root of evil is that (o)NC decided to use server side scheduling. This is prohibiting that calendar clients take care about invitations they send themselves (set from adress, keep copy of invitaion in "send folder" of application).

I used to connect to the caldav component by thunderbirds lightning and calDav sync from androids playstore. Worked like a charme I could set what from address to use for invitions from what so ever calendar and had a copy of that invitaion in the sent folder of corresponding e-mail account. 

This functionality is broken for over 6 month now and that is why I am wondering:

What is the benefit of using such "server side scheduling"?

Will it be possible to have a small checkbox to configure to use it or not in the admin pannel?

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer

**Comment by cstackpole** [comment]
Greetings,
I think my problem might be related. I originally reported it on the [nextcloud forum](https://help.nextcloud.com/t/calendar-issues-since-upgrade-to-11/6439) but got no response there. Then I tried the [nextcloud calendar](https://github.com/nextcloud/calendar/issues/170#issuecomment-268448313) and they asked me to report here. This ticket seems to match my problem.

The short version, after updating from 10.0.2 to 11 I can no longer send calendar invites from Thunderbird. When I create them, nothing happens. It used to send them out. Any help would be appreciated. As I use this feature regularly & it is really messing with me right now.

Thanks!

**Comment by kosli** [comment]
same problem over here since upgrade to NC11

**Comment by biva** [comment]
Apparently related to https://github.com/nextcloud/server/issues/2149

Any update?

**Comment by biva** [comment]
And related to this ownCloud issue also: https://github.com/owncloud/core/issues/25470

**Comment by kosli** [comment]
any update/decision on this one? 
how about a side wide config option to at least easily disable the invitation mails by NC? see my comment in https://github.com/nextcloud/calendar/issues/170

**Comment by biva** [comment]
Hello, any news on this one? Nobody is working on it on owncloud side: https://github.com/owncloud/core/issues/25470#issuecomment-301516955 :(

**Comment by georgehrke** [comment]
This pull request will make it possible to opt out of server side scheduling: 
https://github.com/nextcloud/server/pull/5304

**Comment by andyboeh** [comment]
I just had a look at #5304, am I right that the option for opting out of server side scheduling has been removed from the final commit?

**Comment by biva** [comment]
Still not working on my side (thunderbird + NC 13.0.2). Any plan for NC14?

**Comment by georgehrke** [comment]
Having Server side scheduling is the desired behaviour.
We are looking forward to allow users to set up their own email account for sending the invitation emails.

See https://github.com/nextcloud/server/issues/5080#issuecomment-501158303
