### ISSUE TITLE
[feature request] Please support hosting git repositories

### ISSUE THREAD

**Issue by paulvi** [nextcloud/server#28035]
**Is your feature request related to a problem? Please describe.**
Nextcloud is great collaboration tool, however it seems not yet ready for software development teams, that nowadays use git on own server or on GitHub.

**Describe the solution you'd like**
Nextcloud supporting hosting git repositores.
WebDAV protocol seems not helping in this use case.

**Describe alternatives you've considered**
Alternatives would be other non NextCloud solutions like GitLab, Phabricator (that is winding down operation) 
but they are too much of DevOps and limited on collaboration.

**Additional context**
Possibly there are ways to integrated existing git server into Nextcloud (to use Nextcloud  identities for access control with UI or not, etc), then Nextcloud can recommend some exact way or give reference example in documentaiton.

Also asked on https://stackoverflow.com/questions/68426471/git-repositories-in-nextcloud

**Comment by acsfer** [comment]
This seems more a job for an Application then for Nextcloud core.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
