### ISSUE TITLE
Preview generation for video files might fail for files greater 5MB

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#28694]
Starting with Nextcloud 20 the preview generation for video files is only using the first 5MB to process the thumbnails when using any non-local storage, e.g. as encountered with primary object storage.

This might work depending on the video file if the moov atom is located early enough in the original video file that it will be contained in the first chunk as well, however if the moov is outside of that chunk there is no chance that ffmpeg can parse it and generate a preview from it.

Basically we cannot be sure that the first 5MB will be enough to generate a preview.

Before 20: https://github.com/nextcloud/server/blob/31c5c2a59277fa2f597836097601da50ee1430ea/lib/private/Preview/Movie.php#L46
Nextcloud 20+: https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Preview/ProviderV2.php#L81

It worked before Nextcloud 20 as it just used the full file there also for non-local storages, however i would assume that is has always been an issue for external storages.

The only possible way to solve this would be to try the first 5mb part and if that fails to generate a preview we will need to fall back to use the full file, but I'm open for other ideas.

**Comment by ocrete** [comment]
Yes, you're right, for MP4 files, part of the header may be in the end.. You could even need something from a random spot in the middle in theory.

In practice, instead of downloading a 5MB chunk of the file and then running ffmpeg on it locally, you should just give the http URI to ffmpeg and have it do the http requests for you, it should do the proper byte-range requests to get the appropriate part. I guess you're using ffmpeg as a binary instead of the library? You should be able to  give ffmpeg the cookies, extra header or whatever else is needed to make it connect.

**Comment by ocrete** [comment]
I'm seeing some stuff about encryption, you may need to write your own AVIO that calls into your code (but that means writing it in native code, not PHP)

**Comment by PVince81** [comment]
passing an HTTP URI is not an option because Nextcloud has many storage types that are not accessible through HTTP, like SMB or SFTP

Another idea would be to pipe the stream from the storage into ffmpeg, having ffmpeg read from stdin. Here the hope is that ffmpeg already quits as soon as it has enough data to process the frame in question. If the latter works, then we don't need to pipe the whole file and rely on ffmpeg to abort early enough.

**Comment by PVince81** [comment]
PR here that uses a fallback approach: https://github.com/nextcloud/server/pull/28889
