### ISSUE TITLE
Consider about the client links in the Personal settings

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#2901]
We should remove Google Play and AppStore Links from Personal Settings, and link instead to https://nextcloud.com/install/#install-clients, because

- we do it the same way with the desktop clients
- we have more clients there (F-Droid, Beta-clients, Windows Phone experimental)

This makes it more easy for us to update links and guide users to beta-clients ;)

The new "Mobile client" (iOS, Android, Windows Phone) link should have the same size as the "Desktop app" link - which is currently not the case 😁 

<img width="664" alt="bildschirmfoto 2016-12-31 um 11 49 02" src="https://cloud.githubusercontent.com/assets/19711361/21577116/8f07800a-cf4f-11e6-91e6-a698fe2311bb.png">

What do you think @nextcloud/designers @nextcloud/android @nextcloud/ios

**Comment by enoch85** [comment]
Not removing the logos, but making them better. Like:

<|Desktop App|> (link to desktop install page) **|** <|Mobile Clients|> (link to mobile clients)
(logos for all the desktop clients)                                **|** logos for all the mobile clients)

This would require an update of the links so that desktop and mobile clients are separated, because right now it's hard to find for a new user.

**Comment by eppfel** [comment]
Why not dynamically show the corresponding client for the OS of the user? If you open on Android, we show the Google Play Store Button.

And in addition a link to the other clients, as proposed by @MariusBluem

**Comment by stefan-niedermann** [comment]
@eppfel there is no proper way to detect a mobile client. Using the user agent will cause problems for every advanced user who changes it for e.g. privacy or compatibility reasons. and even not-advanced users may have probems because many anti virus softwares change the user agent of the installed browsers...

just my 2 ct...

**Comment by strugee** [comment]
It's also possible to trigger a mobile app install from a desktop.

**Comment by MorrisJobke** [comment]
> and even not-advanced users may have probems because many anti virus softwares change the user agent of the installed browsers...

Umm what? I never heard of this - but still interesting. But we don't use the user agent but the browsers Javascript variable which can't be changed AFAIK ;)

**Comment by jancborchardt** [comment]
We show all of the icons / platforms because you might also change the platform, or have colleagues / friends who use different devices. It’s not purely a download link for your own device but also in general pointing out where it’s available.

**Comment by eppfel** [comment]
Yeah, the "we got them all aspect is quite nice" 😜 I propose closing the issue...

**Comment by MorrisJobke** [comment]
I also vote for close.

**Comment by skjnldsv** [comment]
Agree too
