### ISSUE TITLE
rootcert.crt empty after update to latest stable11 commit 

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2910]
```
GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations: CAfile: /var/www/data/files_external/rootcerts.crt CApath: /etc/ssl/certs
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/html/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/html/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/html/lib/private/Http/Client/Client.php - line 137: GuzzleHttp\Client->get('http //www.next...', Array)
/var/www/html/settings/Controller/CheckSetupController.php - line 124: OC\Http\Client\Client->get('http //www.next...')
/var/www/html/settings/Controller/CheckSetupController.php - line 107: OC\Settings\Controller\CheckSetupController->isSiteReachable('www.nextcloud.c...')
/var/www/html/settings/Controller/CheckSetupController.php - line 363: OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()
[internal function] OC\Settings\Controller\CheckSetupController->check()
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\CheckSetupController), 'check')
/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\CheckSetupController), 'check')
/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/lib/base.php - line 1010: OC\Route\Router->match('/settings/ajax/...')
/var/www/html/index.php - line 40: OC handleRequest()
{main}
```

```
cURL error 77: error setting certificate verify locations: CAfile: /var/www/data/files_external/rootcerts.crt CApath: /etc/ssl/certs	
```

**Comment by LukasReschke** [comment]
`/var/www/data/files_external/rootcerts.crt` is an empty file on the FS.

**Comment by blizzz** [comment]
The certificate file is (re)created by ``CertificateManager::createCertificateBundle()``. It also gets modified when adding or removin certificates, but this happens for users certificates bundles only, and they are intact – anyway they'd call this method. But it is unlikely that this pathed caused it. 

The other callee is ``getAbsoluteBundlePath()``, and this triggers are creation when ``needsRebundling`` is not false. Basically it returns true when the mtime of the resources/config/ca-bundle.crt is more recent.

``getAbsoluteBundlePath()`` is called in the constructor of our DAV storage and by ``OC\Http\Client\Client::setDefaultOptions()``. This is now pretty general.

My current theory is:

1. The updater is running (via web) and removing the source files
2. There is still a request going on and  ``CertificateManager::createCertificateBundle()`` callled
3. It recreates (but why?) the bundle, but the new files are not in place yet. Thus, it cannot read from the shipped ca-bundle.rst
4. It writes empty content to rootscert.crt
5. We have a new empty file with a very recent mtime, so it stays like this…

Because of 3. I am not entirely convinced of this scenario… Also, the requirement is that this code path is even followed while in maintenance  mode… or it is an older request still running (e.g. cron job). In any case, "mitigation" would be to never write empty content to  rootscert.crt.

**Comment by LukasReschke** [comment]
The strange thing is I increased the version on the affected system for another minor step and it worked fine… So there may be in fact some race condition or other strange thingy happening.

**Comment by MorrisJobke** [comment]
Fixed and backported to stable11

**Comment by jospoortvliet** [comment]
But not a 'real' fix, is it? A work-around? Not sure if we want to keep this open...

**Comment by derp4321** [comment]
Well ...  I have this Bug with 

Current version is 13.0.1.
No update available

How do i fix it ... im using /etc/letsencrypt/live so i have a cold atm so my brain cant figure this out because of bad virus update from imune.sys ^^

Webacess works but apps cant connect ... 

Also under admin setting i am told the server has no internet connection while i access it via internet ...

Error | internet_connection_check | GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations: CAfile: /tmp/oc_tmp_H8Q5o0-.crt CApath: /etc/ssl/certs/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103:GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132:GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/html/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25:GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)/var/www/html/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43:GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134:GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132:GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/html/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25:GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)/var/www/html/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43:GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134:GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165:GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))/var/www/html/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('http //www.next...', Array)/var/www/html/nextcloud/settings/Controller/CheckSetupController.php - line 129:OC\Http\Client\Client->get('http //www.next...')/var/www/html/nextcloud/settings/Controller/CheckSetupController.php - line 112:OC\Settings\Controller\CheckSetupController->isSiteReachable('www.nextcloud.c...')/var/www/html/nextcloud/settings/Controller/CheckSetupController.php - line 426:OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()[internal function] OC\Settings\Controller\CheckSetupController->check()/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161:call_user_func_array(Array, Array)/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91:OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\CheckSetupController), 'check')/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 115:OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\CheckSetupController), 'check')/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App main('OC\\Settings\\Con...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/settings/ajax/...')/var/www/html/nextcloud/index.php - line 37: OC handleRequest(){main}
-- | -- | --
