### ISSUE TITLE
Huge Preview Folders

### ISSUE THREAD

**Issue by bnjbnj** [nextcloud/server#29144]
As described here: https://github.com/nextcloud/server/issues/5717 or https://help.nextcloud.com/t/16gb-files-in-folders-appdata-oc3o8gj7dyh8-and-appdata-ocz20q5nkq0d/125056 the `data/appdata_xxxxx/preview` folder get's huge, often larger the the files itself. In my case it's 16GB (with 25GB of files), the 2nd link reports of even 44GB of the size of preview-folder.

Nextcloud version: 21.0.5
Operating system and version: Linux 4.9.0-16-amd64 x86_64
Apache or nginx version : ???
PHP version : 7.3.31

**Comment by a-0-dev** [comment]
I have the same problem. It's super unresponsive to not cache previews, so I really need those that _are_ needed in my appdata folder. I'm also using the Preview Generator App now (https://github.com/nextcloud/previewgenerator), which can pregenerate them as well. 

However, I'd like to have a setting for how long previews should be kept after their last use (for my use case this would be 6 months e.g.), so that the thumbnails don't take up too much space (currently 60GB for 300GB of data). Also, as I don't really need thumbnails for anything but pictures, some file extension include/exclude list would be nice, so it doesn't need to store renderings of the thousands of .txt, .md., .pdf etc. files I have. So generally having an optional config file for thumbnails with the following options would be super nice:

- How long a thumbnail should be kept after its last use
- Whether thumbnails should be precomputed once a file is uploaded (see current functionality of Preview Generator)
- File type filtering (what types of files shall / shall not be rendered as thumbnails)
- Resolution of thumbnails
- Maybe a thumbnail path, if one wants to store them on faster storage / ramdisk

I know that one should not ask OS contributors to implement lime costly features, and I highly apprectiate your work! Still, imho this would be a very needed and convenient improvement of Nextcloud, so I thought I'd elaborate on it :)

**Comment by kesselb** [comment]
For one file multiple previews are generated. That's how our preview system works. It's always a trade off. It's not on the roadmap to change the general approach. Yet you can configure some parameters:

https://github.com/nextcloud/server/blob/48d7e45f5c827d702e430b0952f2db3a95820a9e/config/config.sample.php#L995-L1101

I'm closing the report as a lot of previews / huge preview folder is (currently) the expected behaviour.
