### ISSUE TITLE
security warning for readonly server config

### ISSUE THREAD

**Issue by fuu0** [nextcloud/server#29173]
### Steps to reproduce
1. Install Nextcloud with readonly config and start it
2. Login to Nextcloud and click on Administration / Overview
3. You get a warning for a valid and good decision in the category "Security & setup warnings"

### Expected behaviour
This can maybe a informal hint, but it should not be a warning. I would prefer a security hint if the file **is writable**

### Actual behaviour
Error:
The read-only config has been enabled. This prevents setting some configurations via the web-interface. Furthermore, the file needs to be made writable manually for every update.

### Server configuration

**Nextcloud version:** 22

**Updated from an older Nextcloud/ownCloud or fresh install:** both

**Comment by danieljkemp** [comment]
This is because nextcloud is using the config files to write both static/install-time settings (like DB config, which obviously can't be stored in the database) and dynamic config settings like SMTP config.

Additionally it stores the current version in the config file and expects to write that on every update.

This was discussed a while back but seems to be dropped due to low interest. It makes for a rather messy cloud deployment, since the config directory needs to be a dynamic/provisioned volume just to store a version variable, and then the static config files need to get mounted into that. 

This was discussed a while back, but would require a change to how configuration is loaded/managed. Probably a worthwhile change but there wasn't enough interest.

Ideally the config.php file would contain only static settings that are set during/before install. Other settings made in the UI are already saved in the database, so there is no reason for them to be stored in two places. Generated values should also be stored in the database. 

See: https://github.com/nextcloud/server/issues/3704
Also: https://github.com/nextcloud/server/issues/11075

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
