### ISSUE TITLE
Single File with Multiple Paths

### ISSUE THREAD

**Issue by kmcb** [nextcloud/server#2928]
I was entering this request to tie to the discussion on the forum.  This feature request is to add the capability to have a single file have multiple paths so it would appear in multiple folders.  
        https://help.nextcloud.com/t/single-file-with-multiple-paths/6403/4

This shows some information on using this feature on Google Drives. 
        https://www.labnol.org/internet/add-files-multiple-drive-folders/28715/

After doing some investigation, some of the logic appears to have been implemented already

Biggest Benefits:
 - Improve New User Experience in a many file shared repo, by allowing users not familiar with file structure to take hierarchal drill down approach to find the same file.
 - Saves Spacing for Mobile applications
 - Changes to the file would not require being individual updates to each different path.

Downside:
 - Maybe it is a limited use case ;)

Simple Example- (in practice, the same file may exist in 40-60 paths for my particular use case)
Main Directory
-----Applications
----------- Fire Trucks
----------------*File: Fire Truck and Crane Chains
-----------Cranes
----------------*File: Sprocket for Cranes
----------------*File: Fire Truck and Crane Chains

-----Manufactures
----------- Jim’s Sprockets
----------------Catalogs
----------------Brochures
----------------------*File: Sprocket for Cranes
----------------Pricing 
----------- FMP Chain
----------------Catalogs
----------------------*File: Fire Truck and Crane Chains
----------------Brochures
----------------Video Demos

----Product Type
----------- Chain
----------------*File: Fire Truck and Crane Chains
----------- Sprockets
----------------*File: Sprocket for Cranes

**Comment by MorrisJobke** [comment]
This is basically symlinking. I don't know if we want to build this into Nextcloud it could get very easy super complex.

cc @karlitschek @icewind1991 @rullzer

**Comment by karlitschek** [comment]
Interesting idea. But this is a lot of work because we have to consider all the corner cases. Also the User Experience needs to be completely seamless.

**Comment by kmcb** [comment]
Does it reduce the complexity by offer this feature for people viewing the directory via web browser and using the IOS/Android Apps?  Would that give you a good first step?

**Comment by MorrisJobke** [comment]
> Does it reduce the complexity by offer this feature for people viewing the directory via web browser and using the IOS/Android Apps only? Would that give you a good first step?

No. Everywhere we use WebDAV as API.

**Comment by kmcb** [comment]
It looks like WebDAV has a draft that covers some of this.
[](https://datatracker.ietf.org/doc/draft-ietf-webdav-collection-protocol/)

**Comment by putt1ck** [comment]
+1 for this feature. Not an edge case in organisations, it's about document ownership versus document need. So for example:

finance/admin department maintain policies, keep insurance certificates up to date etc.; they want to do this in an area or areas(group folder(s)) controlled by them, with read access more widely to some parts of their area, and will maintain a file structure that works best for them as a function.

Sales department needs to include some of these documents in tenders, and wants to have easy access to them to maintain efficient working, and in their group folder have a "resources" folder that contains the documents they need, *some* of which will be from finance/admin, some from health and safety, some from HR and some they maintain themselves - that folder should contain shortcuts to the maintained document, rather than: 
copies of the documents of interest (version control issues and/or overhead);
a document with a list of where to find such documents (clumsy, hard to maintain/use, probably leads to copies).

It occurs to me that the shortcut approach could just be about supporting URLs like the External Sites app, where the URL could be restricted to the NC server domain and possibly include domains of trusted NC servers. 

I'm not sure whether/how the URL shortcut approach would be supported in webdav or the sync client - but that's true of the features in other apps, so it doesn't have to be seen as a showstopper.

**Comment by kmcb** [comment]
@putt1ck I am probably biased ;), but well said.

Another use case, based on what you wrote, is quality management systems (IE ISO 9001).  Large organizations have many work instructions. This could be use to maintain control in the quality organization, but organize the pertinent documents for specific job functions/departments

**Comment by radoeka** [comment]
What about a virtual folder?  Tag the file 'Fire Truck and Crane Chains' with tags:

Applications/Fire Trucks
Applications/Cranes 
Manufactures/FMP Chain/Catalogs
Product Type/Chain

Display the files based on their tag.  Wouldn't this work?

**Comment by kmcb** [comment]
@radoeka  the main reason was new user navigation.  A new user would need to understand the tags system and tags to find the information.  If there is a hierarchy, a new user can browse and drill down for the information.

**Comment by radoeka** [comment]
@kmcb: depends how the tags are presented.  When they're presented in a hierarchal structure it's the same as your proposal.  But instead of using the data on the file system (filenames), data from a database (tags linked to the file) are used.

The tag presentation system should support a hierarchy, as you can see I used the same hierarchy as what you displayed in the filesystem:
Applications/Fire Trucks
Applications/Cranes
Manufactures/FMP Chain/Catalogs
Product Type/Chain

When this is displayed as:
Applications
...Fire Trucks
Applications
...Cranes
Manufactures
...FMP Chain
...Catalogs
Product Type
...Chain

You get what you wanted, and very flexible ;)

**Comment by kmcb** [comment]
@radoeka,
I would agree that would get us pretty far along the path.  Can NC support that type of presentation or would that require a separate app?

**Comment by radoeka** [comment]
@kmcb: have a look at the [bookmarks](https://apps.nextcloud.com/apps/bookmarks) app.  This app provides 1 layer tags.  I think that a new app is needed for this (owncloud may have one: [systemtags_management](https://marketplace.owncloud.com/apps/systemtags_management) )

**Comment by radoeka** [comment]
https://help.nextcloud.com/t/possibility-of-a-hierarchical-structure-for-tags/4509/5

**Comment by harveyc5** [comment]
Has there been an update on this feature? 
As is in google drive - it would be very useful.
@kmcb

**Comment by loeffelpan** [comment]
+1

**Comment by robin-thoni** [comment]
Another use case is as follow:
```
data1/...
data2/...
devices/laptop-1/
devices/phone-1/
```
I have data folders and one folder per device. I use those folders to control what each device syncs, cause I don't need all data everywhere. With this feature, I can "symlink" all the data I want to sync per-device, like:
```
data1/somedata/...
data1/someotherdata/...
data1/...
data2/...
devices/laptop-1/data1/somedata -> /data1/somedata/
devices/phone-1/data1/someotherdata -> /data1/someotherdata/
```

As opposed to uncheck folders in the client, this allows to remotely select which folders must be synced on which device, before even connecting the client, if needed.

**Comment by sk-alexis** [comment]
Yeah this would be a nice feauture +1

**Comment by TehMightyPotato** [comment]
I'm also looking for exactly that feature. 
I have a lot of books stored as pdf files in a 'books' directory on my nextcloud. But I also have a directory for all my university related stuff like assignments and papers where I normally just create a shortcut to the respective files in the 'books' directory. 
Like that: 
```
books/topicX/bookA.pdf
books/topicY/bookB.pdf

uni/assignment/shortcutToBookA.lnk
uni/assignment/shortcutToBookB.lnk
```
however those links only work on one machine and not when syncing to another one since Windows shortcuts are absolute. (they also do not work on the server obviously). 
Just uploading the files twice is no option since some of those books are 100+MB in size. 
Directly linking to a nextcloud link is also not really great since I already have them on my machine.

I would really appreciate this feature or at least a workaround to relatively link to files on my own machine. (I guess the latter is more a Windows thing than a nextcloud one tho)

**Comment by ostasevych** [comment]
As a workaround you may try to use [Link editor app](https://apps.nextcloud.com/apps/files_linkeditor). I suppose to re-use it and add symlinks to NC. 
Let me add, Google Drive has added shortcuts feature.

**Comment by skjnldsv** [comment]
@MorrisJobke @rullzer do we want this? Is this even doable?

**Comment by MorrisJobke** [comment]
> @MorrisJobke @rullzer do we want this? Is this even doable?

Most likely we don't want this. There should also be other symlink like feature requests.

**Comment by fredjoz** [comment]
Hi,
+1 for this request.
Very usefull fonctionnality.
With the opensource app GoFAST (https://www.ceo-vision.com/) you can share one doc in multiple directories without duplicate it. A very simple way to manage versions and publications.
Many thanks in advance if it could be implemented one day.

**Comment by RomanFenioux** [comment]
+1 
I would also be very interested by this feature for a use case similar to the one described by @kmcb . 
Either the tags or symlinks / shortcuts solution mentioned above would work I think. 

The idea is to have a file accessible at different locations, but linked to a single file (source) to avoid copies that create synchronization issues when modifications are needed.

People responsible for modifying / updating files would rather have all their files in a single folder or a structure that makes sense to them.
People who need some of those file would rather have them available at different locations relevant to them, rather than having to browse through the folder / folder hierarchy created by the maintainers.

**Comment by hampton8** [comment]
I see this has been marked as closed but, as someone trying to migrate to using my Nextcloud instance instead of Google Drive as much as possible, I was shocked to find that shortcutting wasn't possible - I use this extensively in Gdrive, as do many others I'm sure.

**Comment by SKeLeToNya** [comment]
+1 to
The idea is to have a file accessible at different locations, but linked to a single file (source) to avoid copies that create synchronization issues when modifications are needed.
Need symlinks / shortcuts

Now I have to copy the same "Library" folder several times for each new project, and then when changes are made in "Library" I have to copy the files or the entire folder to all other "Library" project folders.
