### ISSUE TITLE
Support CRAM-MD5 or SCRAM-SHA-* for SMTP email submission

### ISSUE THREAD

**Issue by jas4711** [nextcloud/server#29333]
Nextcloud only supports LOGIN, PLAIN and NTLM for SMTP email sending server authentication -- see Settings -> General -> Email.  Supporting CRAM-MD5 and/or the newer SCRAM-SHA-* would be great.

**Comment by joshtrichards** [comment]
Done. 

CRAM-MD5 support added in #30349 and documented in nextcloud/documentation#10023. Released in NC26.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html?highlight=crammd5#configuring-an-smtp-server

Please close this Issue out.

P.S. If you want support for any additional methods, you'll have to take that upstream since we rely [Symfony Mailer](https://github.com/symfony/symfony). :-)

**Comment by jas4711** [comment]
I don't think CRAM-MD5 should be removed -- the IETF never got around to deprecating it, IIRC.  CRAM-MD5 is not insecure when used under TLS.  While I agree with adding SCRAM, I think that should be filed as a separate bug (possibly in Symfomy as suggested).  Since my original request has been fixed (adding CRAM-MD5 or SCRAM) I am closing this request.  Thank you for adding CRAM-MD5!
