### ISSUE TITLE
Recommendation: file identification

### ISSUE THREAD

**Issue by ariesbi** [nextcloud/server#29623]
I use nextcloud to manage my tens of thousands of e-books, but I don’t have the classification of files. Can I add file tag functions, such as status tags: important, currently reading, and read.
Classification tags: history, technology, etc.

Thanks

**Comment by joshtrichards** [comment]
I realize this is an old issue and it may have gotten misplaced/overlooked, but this sounds like a support request.

This venue is for bug reports and enhancement requests for the core developers of Nextcloud.

Your query sounds like a perfect topic to bring up at the [community help forum](https://help.nextcloud.com).  

If you do believe your request is a bug report or request for enhancement, submit a new Issue by filling out the entire form so that your request can be properly concerned.

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webgui.html?highlight=tags
