### ISSUE TITLE
Add native support for Amazon Cloud Drive

### ISSUE THREAD

**Issue by Storycrafter** [nextcloud/server#2971]
Acd_cli will work at the OS filesystem level, but native support for ACD would probably be better - bringing management of the backend in line with Google, S3, Swift, etc.

I had started work on this some months ago with Owncloud.  I intend to restart that work here.

**Comment by MorrisJobke** [comment]
Maybe try to adapt an app like https://github.com/icewind1991/files_external_ftp - this can then be loaded as separate app and doesn't require to be all in one place. Thanks :)

**Comment by chris001** [comment]
I vote for the app.  The added bonus is, the app should be compatible with both owncloud and nextcloud.
The best part of having your own app control panel, is you can let the user easily manage the encryption keys you pass to `ocd_cli`, so that the actual files stored on ACD are encrypted, while the app and own/nextcloud only sees the decrypted view of the files.

**Comment by Storycrafter** [comment]
My progress on this has halted as Amazon has taken away my Cloud developer access and hidden the Cloud SDK access behind an invite only program.  I've asked several times for invitation and tried to follow up with a support request (with no response).   At some point I may get on the phone.

**Comment by chris001** [comment]
Oh that's awful.  What's their reason why??

**Comment by chris001** [comment]
If developing new code to do fully native access is not possible at the moment, then developing a front end which calls thru `acd_cli` should just work.

**Comment by masteranalyze** [comment]
@chris001 - the reason is Money!

in the meantime this option does not make much sense,as the Unlimited plan is gone,and every 1tb will cost 60$ per year,i think people just like in the case of microsoft Unlimited witch was shutdown but much more early,on amazon it did take 2 years to shut it down.

you can have an maximum of 30tb,but for every 1tb you will pay 60$ per year, basically the price goes in line with all the others providers,this is bad news but this is,the party is over.

**Comment by masteranalyze** [comment]
users should be aware:who haves the Unlimited plan on expiration it will be just 1tb of data,who haves more then that for example if you have 10tb ,amazon will bill you 600$ instead of 60$,if you don t have the money,an good advice is to start moving your data or make an backup of all your data,as you might lose it,as your acct will be closed and i don t think they will retain your data if you don't pay in 30days.

this will be very similar to what happened on Google some time ago,it was an good article on nextcloud writed on this problem:never put all your eggs in one basket it was called if i remember very well.

start your backup engines those who have more then 1tb in amazon cloud drive or make some cash reserve to be able to pay for all stored data once your Unlimited plan will expire.

**Comment by Storycrafter** [comment]
For my part, I'm no longer interested in working on this.  Amazon Developer services have pretty much ignored my requests for follow up on the API status, and with this recent change in marketing, this isn't something I'm interested in supporting.  Good luck to the rest of you that still desire direct ACD support in NextCloud.

**Comment by masteranalyze** [comment]
Case closed.

**Comment by chris001** [comment]
Thanks for the update.  Still a decent deal $30 for 1TB storage only, they have to make a little margin on it.

**Comment by masteranalyze** [comment]
is 60$ for 1tb,of course they should make money,but on the Unlimited plan i think people start abused and they canceled it same as on the microsoft deal.

the deal might look decent,but it isn t so good,if you take in consideration all their network limitations.

**Comment by masteranalyze** [comment]
now is officially and amazon started info email:

Dear Amazon customer, 

Amazon is no longer offering an unlimited storage plan. As a current unlimited storage plan customer, you can choose to keep your existing unlimited plan through the end of your current subscription. 

At any time, you can cancel your subscription or switch to a new annual storage plan of 100 GB for $11.99 per year, or $59.99 per 1 TB per year up to 30 TB.

as nobody will do this integration for nextcloud,this issue can be closed too.

**Comment by chris001** [comment]
Note for anyone who wants to do this even though ACD is $60/TB/yr, a FUSE driver for ACD could work well, it's pretty cool.
