### ISSUE TITLE
Missing option to enable installing experimental apps from app store

### ISSUE THREAD

**Issue by jbicha** [nextcloud/server#2976]
The [documentation](https://docs.nextcloud.com/server/11/admin_manual/installation/apps_management_installation.html#adding-third-party-apps) says:

"Click the gear icon on the lower left to browse experimental apps in the ownCloud Apps Store. Install experimental apps at your own risk."

But the Apps page has no Settings at all in the bottom left corner.

I also tried adding `'appstore.experimental.enabled' => true` to my config.php but I still didn't see any 'experimental' apps on the Apps page. That option was mentioned in older ownCloud documentation.

Also, the documentation here should say Nextcloud, not ownCloud, right?

### Configuration
Nextcloud 11. Browsers tested: Firefox 51 Beta and Chromium 55 on Ubuntu.

**Comment by MariusBluem** [comment]
Correct. But this is more about the [appstore](https://github.com/nextcloud/appstore) than the server component 😁 What do you think about this @BernhardPosselt 🤔 

> Also, the documentation here should say Nextcloud, not ownCloud, right?

You are right. Documentation is not updated yet. We should do that 😅 Maybe you also want to step-in 👊 I've opened an issue for that in the repo of the docs: https://github.com/nextcloud/documentation/issues/308

Closing here for now 😉

**Comment by BernhardPosselt** [comment]
There is no such notion as experimental apps anymore. Because you can't publish an app without signed certificate on the store anymore we can lock apps to developers. This means that no one except the calendar maintainer can register and upload calendar app archives. We can also do background checks to a certain degree, e.g. if the registered app matches the devs repo, etc.

At some point certain apps will get labels/orgs so you can for instance check which apps are maintained and supported by the inc or which apps are maintained in the Nextcloud org. However this is not yet implemented. This feature will roughly mimic the experimental app label but makes it clearer how it works.

**Comment by jbicha** [comment]
Do you know why this app isn't available for install in in my app store?

https://apps.nextcloud.com/apps/passman

**Comment by BernhardPosselt** [comment]
@jbicha because you arent running 11

**Comment by jbicha** [comment]
My admin interface says I'm running 11.0.0.

**Comment by BernhardPosselt** [comment]
Ok, checked the app and there are only pre-releases https://apps.nextcloud.com/apps/passman/releases?platform=11#11

Currently the server does not yet allow you to install nightlies and pre-releases, they are filtered out when displaying the apps page, cc @LukasReschke

**Comment by jbicha** [comment]
Should I open an appstore issue requesting an option to enable easy install of nightly/unstable,etc. apps?
