### ISSUE TITLE
Config setting `config_is_read_only` should prevent Nextcloud from writing to `config.php`

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#29901]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Description

The config setting `config_is_read_only` currently only prevents Nextcloud from checking for writable config in server health checks.

That's also how the setting is described at https://github.com/nextcloud/documentation/blob/6efc785734a23786bff4c6340a03fa2acbf12f42/admin_manual/configuration_server/config_sample_php_parameters.rst#nextcloud-verifications.

Still, users/admins expect the setting to prevent Nextcloud from writing to `config.php`. That would be helpful, e.g. to prevent admin users from accidently changing server configuration.

### Steps to reproduce
1. Set `'config_is_read_only' => true` in `config.php`
2. Make changes to Nextcloud config via admin interface or `occ`
3. Nextcloud writes to `config.php`

**Comment by Dreamsorcerer** [comment]
The solution to this (but, not the problem description) directly contradicts the goals of #11075.
Before, it was possible to get through an upgrade by manually making changes to the config file, now it aborts immediately even when there are no changes to be made to the config file.

Old behaviour:
Nextcloud would call `set('theme', '')` etc. Because the existing config has the same values, it would not attempt to write anything to the config file. If the config file would get changed, then it gives an error if the read-only option is set.

New behaviour:
The same call is made and immediately errors despite the fact that the config file will not be changed.
