### ISSUE TITLE
Nextcloudpi News Update

### ISSUE THREAD

**Issue by Mowjeewowee** [nextcloud/server#30169]
Update to 21.0.5 
Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by joshtrichards** [comment]
This isn't a NC server Issue or bug. Your problem is (or was - I realize this is quite old!) with the News app. It moved to requiring 64-bit way back in early 2021:

https://github.com/nextcloud/news/blob/master/CHANGELOG.md#1600---2021-06-16

The updater saved you from installing a breaking change.

Close.
