### ISSUE TITLE
Feature: Add config option to move appdata filesystem

### ISSUE THREAD

**Issue by JasonLocklin** [nextcloud/server#3034]
### Steps to reproduce
1.  Install Owncloud on a system with a small/fast SSD.
2.  Put datadirectory/ on a big/slow HDD or NFS mount.
3.  Do not use external storage backend, or anything like that.

### Expected behaviour
Web UI should be quick, as Owncloud should be able to do everything *except* read the user's files without touching the big/slow disk.

### Actual behaviour
Several media components of the web UI sit in the appdata folder, within datadirectory, and so the whole web UI is slowed down whenever it needs to wait for those components. This is *especially* true for the gallery -as all of the thumbnails are in appdata, but affects other areas that use appdata as well. 

Appdata/ tends to be much smaller than user's data, and does not necissarily *need* to be on the big/slow storage.

### Workaround
Bind mount appdata/ from somewhere else on the SSD into datadirectory/

This will cause problems if Owncloud ever starts without that bind mount.

### Cleaner fix.
Add an 'appdata' location option to config.php, just like there is a 'datadirectory' option, so it can be placed somewhere else on the system.

**Comment by nickvergessen** [comment]
Well especially the thumbnails/previews can be a lot of data and therefor should be in the data directory.

But maybe @rullzer has another idea?

**Comment by rullzer** [comment]
This would be very hard. Since we just leverage the internal filesystem code. Splitting this will be a real pain.

**Comment by JasonLocklin** [comment]
Understandable. I'll just bind mount appdata to somewhere on the SSD.

**Comment by ChappIO** [comment]
Could this be reconsidered? I am running into a usecase that requires this.

Our files are stored on a large hdd array which spins down on idle. Because of the appdata folder, the drives have to spin up every time someone visits Nextcloud.

This behavior makes Nextcloud pretty much unviable for us.

**Comment by nickvergessen** [comment]
The solution above doesn't work for you?

**Comment by ChappIO** [comment]
I did bind the directory to the cache array, however nextcloud still spins up my hard drive array every time the folder is accessed. Probably because the link is resolved.

**Comment by ChappIO** [comment]
To be clear, my usecase isn't to speed up the system, but rather to keep my drives idle as much as possible.

**Comment by fritut08** [comment]
> 
> 
> To be clear, my usecase isn't to speed up the system, but rather to keep my drives idle as much as possible.

Did you find a solution for this? I would also like to keep my drives idle or in standby but access to the appdata directory frequently spins them up.

**Comment by t3nk3y** [comment]
I wanted to leave my comment that I'd also like this feature.  The bind workaround is acceptable, but not at all ideal, especially since there is a hash added to the path name.

Google Photos wants to charge now, and I've moved all our photos in to nextcloud, suffice it to say, the previews folder is really big, and has a huge number of files in it.  But that's "really big" in relation to what we might initially expect for a thumbnail store.  It's actually only 15GB, and while that might sound like a lot, it is easily a worthwhile cost for improving the performance when browsing through photos.  My storage drives and usage runs in the TB, a 15GB speedy cachey folder doesn't really fit that bill, but it goes just right in the high speed SSD world.

**Comment by ChappIO** [comment]
@fritut08 not really, instead I started developing my own application.
