### ISSUE TITLE
User Profile: Allow server admin to specify/override visibility defaults

### ISSUE THREAD

**Issue by chris246** [nextcloud/server#30383]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Nextcloud 23 introduced the "User Profile". Per default, some user information is per default publicly accessible. Especially in regard to GDPR guidelines I find this problematic, as personal information is per default accessible to the public.

**Describe the solution you'd like**
Besides the suggestion to ship Nextcloud with more privacy-friendly defaults, I want to suggest to give administrators the possibility to
* limit profile visibility (override user settings)
* customize profile visibility defaults

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bartosz347** [comment]
Just in case someone is looking for a temporary solution to disable all profiles, I've managed to do it with the following query:
```sql
UPDATE oc_accounts SET data = JSON_SET(data, "$.profile_enabled", JSON_OBJECT('value', 0, 'scope', 'v2-local', 'verified', 0));
```
Disclaimer: it's a dirty hack. I'd love to see a more elegant solution :)

**Comment by scharel** [comment]
> Just in case someone is looking for a temporary solution to disable all profiles, I've managed to do it with the following query:
> 
> ```sql
> UPDATE oc_accounts SET data = JSON_SET(data, "$.profile_enabled", JSON_OBJECT('value', 0, 'scope', 'v2-local', 'verified', 0));
> ```
> 
> Disclaimer: it's a dirty hack. I'd love to see a more elegant solution :)

This does not seem to work if any user has not yet made any changes to his profile and the JSON object does not yet contain `profile_enabled` at all:
```
nextcloud=> UPDATE oc_accounts SET data = JSON_SET(data, "$.profile_enabled", JSON_OBJECT('value', 0, 'scope', 'v2-local', 'verified', 0));
ERROR:  column "$.profile_enabled" does not exist
LINE 1: UPDATE oc_accounts SET data = JSON_SET(data, "$.profile_enab...
                                                     ^
```

**Comment by Schmuuu** [comment]
I have users on my server who definitely don't want to see their name a profile picture visible publicly. 
I can't understand how this setting could be the default and why admins can't set another default. This seems to be the opposite of taking back control over your data, when a "feature" is suddenly added without informing the user after login and directly asking him if he wants to share this information publicly. And opted-out should be default for a platform like Nextcloud.

Unfortunately my users are not that techy that they easily understand who to change their profile settings on their own. Some don't log in that often. And now I made their data publicly available by accident, just because I upgrade the server.
Oh man ... :(

**Comment by chris246** [comment]
You can disable access to the `/u/` directory on the webserver level.
This prevents this and did not produce any negative side effects for me until now.

**Comment by szaimen** [comment]
It will be possible to disable/change the default with the next release of NC23.
See https://github.com/nextcloud/server/pull/31624

**Comment by chris246** [comment]
Cool, thanks
