### ISSUE TITLE
New version of the Virtual Folder API (31st Jan 2022)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#30407]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Align and implement API for virtual folders for photos/gallery as well as multiple shares (as in the multi-step approach mentioned by @skjnldsv: create virtual folder, add files, create share).

**Due Date**
31.01.2022

**Comment by matiasdelellis** [comment]
Sorry for the audacity.  Mark the comment as spam if you think it is necessary, 😉 

Right now I was looking for information for this.. In the our Face Recognition application, we expect to use this.

A few days ago I am exploring the possibility of exposing the information through dav (See https://github.com/matiasdelellis/facerecognition/pull/549). I am replicating systemtags interf,ace, and with the latest commits, I can get the same results as filtered by tags, and quite efficiently..
So, knowing the name of the person, I can get all the photos (and with all the necessary davs properties) where this person is included, and I could use this information very easily in the photo application. 

My problem starts, it is that first it is necessary to obtain the names of the persons, and I can't do it without including a new Dav Collection in Nextcloud [RootCollection](https://github.com/nextcloud/server/blob/c9918477abfd125d05e4acf475d18f1472bbe3a3/apps/dav/lib/RootCollection.php#L121-L131).

I don't want to make a PR to this repository to add support for my application in this way, since it is a very particular application, and it will never be an official part of Nextcloud (Hopefully sometime, but let's face it.. haha), and it is not sensible to have to add every possible application that wants to do this.

All in all at least now I need a way to dynamically add a dav collection,  but I understand that Sabre DAV does not work in this way. 
Well, I don't know how you are going to implement it, but please know, that I am interested in this, and I hope to help you.
