### ISSUE TITLE
Deleting a preview folder stops writing previews to disk

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3041]
### Steps to reproduce
1. Upload an image
2. Remove the `data/appdata_*/preview/{fileid}` folder
3. Reload the page

### Expected behaviour
Preview folder should exist again and have the previews saved

### Actual behaviour
Previews are displayed but not written to disk

@schiessle as discussed

@rullzer I see potential to fail for administrators there.
I'd also assume that deleting the folder would simply regenerate.

**Comment by rullzer** [comment]
It fails hard because we assume it is there (it is still in the DB). Did you rescan?

**Comment by nickvergessen** [comment]
No I did not rescan. But that is exactly my point. Most users will not rescan since they see the previews in the UI. It just stops writing them to the disk and will therefor recreate them all the time in memory, fail on writing but still serve it.

**Comment by rullzer** [comment]
I think your previews are just temp cached. If you force refresh they will fail. The thing is that we only know this failed the moment we try to read. Because before that we do it all in the database.

**Comment by adduxa** [comment]
It is tricky to rescan preview storage because
```
occ files:scan --path /appdata_randomid/preview/
```
leads up to `Unknown user 1 appdata_randomid` error

But there is workaround:
Since whole root data dir is a regular storage, we can mount it to some user directory as local external storage and scan like
```
occ files:scan --path /some_user/files/nextcloud_root_mount/appdata_randomid/preview/
```

So maybe add option to `occ files:scan` command to rescan just previews? Seems like after all user recognition [staff and checks](https://github.com/nextcloud/server/blob/master/apps/files/lib/Command/Scan.php#L224) it simply [call](https://github.com/nextcloud/server/blob/master/apps/files/lib/Command/Scan.php#L160) `\OC\Files\Utils\Scanner->scan($path)` [function](https://github.com/nextcloud/server/blob/master/lib/private/Files/Utils/Scanner.php#L165) with regular string path in the argument so it shouldn't be too hard.
