### ISSUE TITLE
Remove Weather Widget from Core (or disable by default)

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/server#30436]
As stated and discussed in this issue https://github.com/nextcloud/server/issues/23399, the widget creates a lot of confusion and it will probably not be configurable, I propose to remove it from core and make it an optional App or disable it by default for new installations.

I am sadly with a whole bunch of the community. A simple config.php variable would probably enough and make it default showing the current time. As long as this hasn't happened I will probably delete this widget, as it causes more harm than good. 

Somebody looking at the dashboard, seeing the time and maybe thinking even this is the current time, rushes to get to whatever and realising it sometime later, when he looks at an actual watch.
At this current state it harm more than it brings use to most of the community, I think, confusion of admins and users.

Not in disrespect, but just this whole topic reminded me of Apples practices (only in this case you could fiddle with the source code).

I don't want to disrespect the work that has been done in this widget, it is great, but weighing the pros and cons and finding more cons for people having it on by default and getting confused.

**Comment by skythomp16** [comment]
I just installed Nextcloud and I also agree. This should be disabled by default because it is confusing and completely useless to show me what the conditions will be like 6 hours from now. Most people just want to know the current temperature outside.  I know the developer doesn't see it that way but at least give the option rather than fighting against the entire community.  If the developer wants to make the app useless to all their users, just remove it from the default installation.

**Comment by jancborchardt** [comment]
Hi everyone, rather than removing the widget, we finally fixed the underlying issue with https://github.com/nextcloud/server/pull/30496 – thanks all for the feedback and staying friendly! :)
