### ISSUE TITLE
Delete IP from oc_bruteforce_attempts via occ command

### ISSUE THREAD

**Issue by guddl** [nextcloud/server#3058]
At the moment you have to delete an IP address which was blocked by a brute-force-detection via an SQL command on the database.

https://help.nextcloud.com/t/how-can-i-unblock-an-ip-blocked-through-brute-force-detection/5731

It would be nice to to this via an "occ" command.

**Comment by LukasReschke** [comment]
Works for me. :)

**Comment by aweinert** [comment]
Would it make sense to allow deleting an IP from this table via the admin-panel?

**Comment by LittleNo** [comment]
since the brute force protection is not working properly for all users (for example NATted networks are a big problem) this feature definately should be there

**Comment by nickvergessen** [comment]
Maybe this could be part of the app that was developed around bruteforce protection already.

**Comment by MorrisJobke** [comment]
Another approach to relax the situation here: #6376

**Comment by MorrisJobke** [comment]
I meant #3156

**Comment by Wikinaut** [comment]
ping @jospoortvliet as discussed publically after your 36c3 talk. I regard a final solution of this issue as easy and as important.

**Comment by kesselb** [comment]
Would you mind to share your use case? The throttling is only for a certain ip address. This is only a issue for nat or your reverse proxy configuration is invalid (nextcloud do not see the correct ip).

https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/private/Security/Bruteforce/Throttler.php#L256-L274

If anyone want's to submit a patch. You can reuse some of the code from there. Happy coding :coffee:

**Comment by Wikinaut** [comment]
@kesselb use case? Very stupid simple use case: Nextcloud on a rented server. User/s try to hack a password, get blocked by the mechanism. Same happens, if your clients (not using the dedicated token method but password) use the wrong password - because user had changed that on via the web interface--- so there are many use cases.

As an admin I wish to have a plugin or admin setting which allows to safely delete specific or all blocked IP from the table.

**Comment by Wikinaut** [comment]
Like here https://github.com/nextcloud/bruteforcesettings/issues/9

**Comment by Wikinaut** [comment]
But as an admin setting in the web panel.

**Comment by Wikinaut** [comment]
I discussed this in/after @jospoortvliet s talk at the 36c3.

**Comment by kesselb** [comment]
> Very stupid simple use case: Nextcloud on a rented server. User/s try to hack a password, get blocked by the mechanism. 

So? Their IP address is blocked. You can still login.

**Comment by Wikinaut** [comment]
No. my own IP address is blocked, because my own other devices - when connected via username/password, not with token, were using the old (wrong) password.

You do really not understand the problem, whereas @jospoortvliet does. Please ask him.

**Comment by kesselb** [comment]
> You do really not understand the problem, whereas @jospoortvliet does. 

That's rude. Please use a more polite language the next time. Anyway I do understand the problem. Probably someone will pick it up. I don't see a strong urge to implement such a feature. 

Please refrain from asking for progress. :+1: the issue and subscribe for updates is enough.

**Comment by joeried** [comment]
I would like to take a look at this issue.
What would be the correct namespace of such a occ command? 'security:bruteforceattemps:reset-for-ip'?

@kesselb You quoted code that can be reused. My first thought would be to extend the resetDelay function so that:
- metadata and action are optional arguments
- another optional argument exists, which switches whether the given IP or the whole subnet of the given IP is used/unblocked

Does that make sense?

**Comment by kesselb** [comment]
Cool 👍

I think that's much additional complexity for this method. 

As start you might write a command to delete a single IP from the list. We can always extend later. Probably not bad to also write a command that lists the current blocks (if there is no such command yet).

**Comment by joeried** [comment]
It would increase complexity, but on the other hand a new method would be relatively similar to the existing one.
The querry to delete the attemps for one IP would need one different where condition ('ip' instead of 'subnet') and omit two other where conditions
With my proposal I actually wanted to delete only one IP. The proposed flag for switching between subnet and ip would have been needed at this point to switch the where condition from 'subnet' (current usage) to 'ip' (usage for this case).

But I also understand your argument and that was also one of the reasons why I wanted to ask.
