### ISSUE TITLE
Implementing Nextcloud Customized Widgets

### ISSUE THREAD

**Issue by Gowtham-eng** [nextcloud/server#30607]
### Feature Request

Hi, I have installed and used the Nextcloud application for my organization. As I am new to this platform, I am exploring some ideas and implementation for the Nextcloud Application.

I require to add a widget of different applications in my Nextcloud dashboard example like GMAIL, HRIS, etc. Similar to SharePoint. 
 

#### Summary
1) Nextcloud Application Should be used as a SharePoint.For that, we will have all the applications in a single Nextcloud application.
2) Is this possible by importing the API of different applications to Nextcloud to do the job.

**Comment by GretaD** [comment]
this was open on mail repository, so i transferred it on server

**Comment by Gowtham-eng** [comment]
> this was open on mail repository, so i transferred it on server

Can you Provide any link to check this

**Comment by Spartachetto** [comment]
Did you check the apps in https://apps.nextcloud.com/categories/dashboard or https://apps.nextcloud.com/categories/integration ?

**Comment by Gowtham-eng** [comment]
> Did you check the apps in https://apps.nextcloud.com/categories/dashboard or https://apps.nextcloud.com/categories/integration ?

This is a default application that is there in Nextcloud. I need as a 3rdparty application to bring it into Nextcloud what are all the requirements to go for it.

**Comment by joshtrichards** [comment]
This sounds like a support request.

This venue is for bug reports and enhancement requests for the core developers of Nextcloud.

Your query sounds like a perfect topic to bring up at the [community help forum](https://help.nextcloud.com) - which also has a section for those developing third-party add-ons for NC.

You may also find some of the information you need in the Developer Manual:

https://docs.nextcloud.com/server/latest/developer_manual/

If you still believe your request is request for enhancement, submit a new Issue by filling out the *entire* form so that your request can be properly considered.

**Comment by joshtrichards** [comment]
Hi @Gowtham-eng - Are you asking for resources because you want to develop an application? If so:

- https://docs.nextcloud.com/server/latest/developer_manual/
- https://nextcloud.com/developer/
- https://help.nextcloud.com/c/dev/11

I'm going to close this for now. Feel free to reply if I've misunderstood you're request.
