### ISSUE TITLE
Clicking an app update notification should open app updates

### ISSUE THREAD

**Issue by rigrig** [nextcloud/server#30836]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When I see a notification about available app updates, I always click it expecting to go to the app updater page, but that doesn't work. So I have to navigate there myself: open Apps from the menu, select Updates on the left, which is a bit annoying (not so much the navigation, but that clicking the notification doesn't work.)

**Describe the solution you'd like**
It would be nice if admin users could click on the notification, to open the app updates page.   
Complicating things a bit: this should only happen for *admin* users: other users without access to the settings can also get notified, but clicking the notification should not try to open a page they don't have access to.

**Additional context**
Clicking here as admin user: 
![image](https://user-images.githubusercontent.com/2941436/150958736-c00f5b48-a5bb-4c83-a152-d32697ebffeb.png)
Would take you directly to `/settings/apps/updates`

**Comment by ogasser** [comment]
@nickvergessen would this be possible by adding a simple link or does modification in the notifications app?

CC @jancborchardt

**Comment by nickvergessen** [comment]
That is exactly what we are doing since 4+ years:
* Server

https://github.com/nextcloud/server/blob/37f40cdd468a2826f6269bacc81ff74d8c606d23/apps/updatenotification/lib/Notification/Notifier.php#L133-L135

* Apps

https://github.com/nextcloud/server/blob/37f40cdd468a2826f6269bacc81ff74d8c606d23/apps/updatenotification/lib/Notification/Notifier.php#L153-L155

* Admin check

https://github.com/nextcloud/server/blob/37f40cdd468a2826f6269bacc81ff74d8c606d23/apps/updatenotification/lib/Notification/Notifier.php#L179-L187

But I also see that it is not working on our company instance.
I will try to have a look again

**Comment by nickvergessen** [comment]
Now it made click.... fix is in https://github.com/nextcloud/notifications/pull/1276/
