### ISSUE TITLE
Disable public user’s contact information - domain.tld/index.php/u/<user>

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#30850]
With a public share (add to my nextcloud) you can get the username of a nextcloud user.  With 

domain.tld/index.php/u/username

you then get the full user information also if you do not have an account on this nextcloud.

**discussion:** https://help.nextcloud.com/t/disable-public-users-contact-information-domain-tld-index-php-u-user/132006

**Additional information:**
Perhaps only a bug on Nextcloud 23.

**Comment by devnull4242** [comment]
See also open pull request https://github.com/nextcloud/server/pull/29372

**Comment by joshtrichards** [comment]
Fixed in #29372.

Profile docs were also updated: 
https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/profile_configuration.html

And new parameters are included:
`occ config:app:set settings profile_enabled_by_default --value="0"`
`'profile.enabled' => false,`

Closing this out.
