### ISSUE TITLE
Exclude file name by patterns; required for Gentoo webapp integration

### ISSUE THREAD

**Issue by LeCoyote** [nextcloud/server#3112]
Gentoo's webapp-config generates files in the nextcloud installation folder that causes the integrity check to fail. This issue was addressed in owncloud by allowing the exclusion of file name patterns. This is done in this commit: https://github.com/owncloud/core/pull/26782/commits/bf72f47c34b6e2579cfcbdcf4a582e42fd67c181
The patch applies nicely to nextcloud (changing the string "owncloud" to "nextcloud" obviously) and solves the problem.

**Comment by LeCoyote** [comment]
Pull request created: https://github.com/nextcloud/server/pull/3113

**Comment by stefangweichinger** [comment]
I hit this issue as well right now and successfully applied the mentioned patch (before even noticing this PR). "Voting" for and bumping the PR this way ;-)

**Comment by Anrock** [comment]
As a workaround, i've added `'integrity.check.disabled' => true` to `config/config.php`

**Comment by okias** [comment]
I think it's "higher" priority enhancement, because it's really annoying + disabling integrity check doesn't sound like right thing to do.

Please guys, merge this commit :)

**Comment by okias** [comment]
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .webapp-nextcloud-12.0.2

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp-nextcloud-12.0.2] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```

This bug is still valid. Could be please assigned to fulfill integrity check under Gentoo servers?

**Comment by okias** [comment]
Could someone _please_ remove label enhancement and mark it as a _regular_ issue?

**Comment by okias** [comment]
small remainder, about broken Nextcloud integrity check on Gentoo systems.

**Comment by svoop** [comment]
NC13 is out – yet no fix. Please consider this:

The [Gentoo Wiki](https://wiki.gentoo.org/wiki/Owncloud#Disable_integrity_check) suggests you disable the integrity check. You don't want people to do this.

However, if you don't disable it, when you're hacked, you won't realize it because you're used to always see the warning and don't check the corrupted files list never ever.

No matter what you do, the security check feature is broken on Gentoo. And worse, when NC servers are hacked, NC will take the blame, not Gentoo.

Please add the `.webapp-nextcloud-*` files to the manifest!

**Comment by okias** [comment]
@nickvergessen Hello Nick, I wonder why you consider this **issue** to be enhancement. This is clearly crippling security feature for Gentoo users. I'm aware that Gentoo is not so widely used by community as Ubuntu, but still it's used by many advanced users or system administrators and **people focused on security**.

Can you give us information, when someone looks at this issue?

**Comment by jdunn0** [comment]
> I wonder why you consider this issue to be enhancement.

The reason this pull request is an enhancement is because it enhances the Integrity Check function with the ability to exclude file names that meet a specific pattern.
At the same time this pull request will enable users using webapp-config to use the Integrity Check feature which as you mentioned will enhance security for Gentoo users (and users of other Gentoo based systems that also use webapp-config).

As another user of Gentoo's webapp-config with the same issue, I decided to look at the Integrity Check function  code and I don't think the enhancement to NextCloud is needed as webapp-config will only create the two files `.webapp` and `.webapp-nextcloud-[installedversion]`.

If you check for the file by using a fixed string plus a variable value by uing `'.webapp-nextcloud-'.$OC_VersionString` instead just the fixed string of of `'.webapp-nextcloud-*'` in the $excludedFilenames array then the regular file name matching works without issue.
So far, I think the way I thought of is better because instead of using the '*" wildcard for matching, it uses a version variable to match the file which is better security wise as the Integrity Check function will not allow all files that begin with '.webapp-nextcloud-', only the file that matches the installed version of Next Cloud.


The changes required in `lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php` to do that are these 2 steps:
1\. Near the top of the file add `require OC::$SERVERROOT . '/version.php';` so that the `$OC_VersionString` variable will be available.
2\. Replace the line excluding `.webapp` in the $excludedFilenames array with these 2 lines:
`'.webapp', // webapp-config uses this to identify an installed webapp`
`'.webapp-nextcloud-'.$OC_VersionString, // webapp-config uses this to identify a specific version of an installed webapp`

Note: I replaced the `.webapp` line to update the the comment after it to be more descriptive of what webapp-config does and to remove the mention of any specific *nix distributions as it's not important for the specific distributions that include webapp-config to be listed, similar to how the entry for '.directory' just says 'Dolphin (KDE)' but doesn't list every distribution that includes Dolphin and/or KDE.

I have not actually created a patch file yet or tested it on my Gentoo system but it should work.
The only potential problems I can see with the above code is that:
1\. There might be an issue if the '.webapp-nextcloud-[oldversion]' file still exists while an upgrade install is in progress.
An upgrade install with webapp-config is usually quick enough that it would only matter if NextCloud was accessed during the short period of time (about a minute or so) the upgrade process is running.
2\. This will fail to work if the version installed by webapp-config does not match the version contained in the version.php.
This should not happen with any of the ebuilds in the gentoo repository at the moment.
Those are nextcloud-13.0.0, nextcloud-12.0.5, nextcloud-12.0.4 and nextcloud-11.0.6.
I have only used nextcloud-13.0.0 but I assume the other versions install a version.php file with the same version number.
Unless a Gentoo specific version of NextCould was created with a name like nextcloud-13.0.0-r1 then the version number would always match.
I can't think of a reason that a Gentoo specific version would be created for NextCloud though as it's a self contained application that doesn't need any modifications to work in a specific distribution.

These issues can be handled though if the Integrity Check function is updated to read the .webapp to use the WEB_PVR value as the version when checking for the '.webapp-nextcloud-[installedversion]' file.

This could be done by adding a new function to check for a `.webapp` file in the application root directory before the `$excludedFilenames` array is checked and if the '.webapp' file exists, use a function like parse_ini_file to read the file and put it's values in a temporary array called $webappconfig (parse_ini_file won't work in PHP7 for this purpose so a different function would be needed though) then add two entries to `$excludedFilenames` array of `.webapp` and `'.webapp-nextcloud-'.$webappconfig['WEB_PVR']` and then the function which checks the `$excludedFilenames` array will know to exclude those files.
If the new function doesn't see a .webapp file in the root directory then it just skips that part entirely and goes right to the regular behavior of skipping the files in the `$excludedFilenames` array.

That new function would be a bit more complicated but it would resolve the issue of ebuild versions not matching the exact ones in `version.php` and not require the including of the `version.php` file in the `ExcludeFileByNameFilterIterator.php` file.

It wouldn't that hard to write the code to do so, if the NextCloud developers would prefer not to add a dependency on version.php.
If so then I will create a patch that adds this function or I can create a patch based on the code listed earlier in my comment.
Either way is fine with me but I'm not really that familiar with the NextCloud code (Or even the OwnCloud code) so there could be issues with either method that I have not considered.
So I don't plan to create a patch and pull request until I know what the NextCloud developers would prefer.
The last thing I want to do, is create an unnecessary dependency on version.php if the version can be obtained a different way or accidentally create a potential security issue with a new function that has to parse a .webapp file if it exists to work (There may already be better function then parse_ini_file available that will handle comments with a Hash Symbol prefix, that read configuration data in the format `KEY="VALUE"` but I'm not sure what that function would be if it's available).
Either way, I think those 2 methods should be more secure then the pattern matching function in this pull request as they only exclude the two files created instead of excluding all files that start with '.webapp-nextcloud-'.

**Comment by svoop** [comment]
@jdunn0 

> Unless a Gentoo specific version of NextCould was created with a name like nextcloud-13.0.0-r1 then the version number would always match. I can't think of a reason that a Gentoo specific version would be created for NextCloud though as it's a self contained application that doesn't need any modifications to work in a specific distribution.

One very possible reason is a bug in the ebuild (aka: package) itself. Gentoo doesn't do silent updates, ebuild fixes will therefore always result in `r`-level updates. Same goes for ebuild updates made necessary due to changes in Portage (aka: package manager) unless a NC update happens at the same time.

However, I don't see any real security benefit from matching exact versions. Just be a little bit more restrictive when it comes to the pattern matching and you're all go:

```
/\.webapp-nextcloud-(\d+\.){3}(-r\d+)?/
```

**Comment by jdunn0** [comment]
@svoop: That is a good point, sometimes the revision is just the ebuild itself being updated.
The pattern you listed would be better then the pattern in pull request #3113 but the code changes in that pull request are still needed to add support for excluding files with pattern matching instead of exact string matches to the Integrity Checker function.

It appears that pull request #3113 was closed due to the pattern included with the pattern matching code of `/^\.webapp-nextcloud-.*/` could match a lot more files then intended.

If that pull request can be reopened and the code changed to use the more restrictive pattern you listed of `/\.webapp-nextcloud-(\d+\.){3}(-r\d+)?/` then the pull request might have a better chance of being accepted.

If the NextCloud developers just don't want the pattern matching code in the Integrity Checker function then one of the two methods I listed would need to be used instead.

I can just create a patch to fix this and put it in `/etc/portage/patches/www-apps/nextcloud` so portage automatically applies it or disable the Integrity Checker function altogether so it doesn't really matter to me if this issue is resolved or not.

In general, a patch should be accepted that deals with the '.webapp-nextcloud-[installedversion]' file so users using webapp-config no longer need to disable the Integrity Checker or see annoying notifications from it.

**Comment by svoop** [comment]
@jdunn0 This `/^\.webapp-nextcloud-.*/` is indeed a bad idea since the `.*` is eager and will swallow anything (including `/`) if there's another `/` coming later. So it would match stuff like `.webapp-nextcloud-10.0.0/../../hackerstuff.php/`. To make it safe, either use my pattern from above or simply add a question mark like so: `/^\.webapp-nextcloud-.*?/`. It makes sure, the `.*` is not eager anymore and will stop at the first `/` coming up. Either way, I don't see any additional security risk by using a solid (non eager) pattern. Prove me wrong, but until so, I have to consider this argument invalid.

**Comment by jdunn0** [comment]
@svoop: That makes sense but because @MorrisJobke closed pull request #3113, I don't think the author of the pull request @LeCoyote can change the pull request to use the pattern you listed instead.
I think pull request #3113 needs to be opened again if possible so @LeCoyote can change the code to use the pattern you listed and then hopefully someone will merge the pull request and then this issue would be fixed.

**Comment by svoop** [comment]
@jdunn0 

@LeCoyote can update the pattern on his fork and create a new PR. Or anybody else can fork his fork, update the pattern and create a new PR.

**Comment by LeCoyote** [comment]
@jdunn0 @svoop Created a new pull request because I must have done something wrong with my fork: https://github.com/nextcloud/server/pull/8647

**Comment by LeCoyote** [comment]
In spite of my efforts, it seems that the patch I grabbed from OwnCloud is not good enough. I'm sorry but I just cannot dive into NextCloud & PHPUnit or whatever else is needed just to fix this. I hope someone else can pick it up.

**Comment by GreatEmerald** [comment]
I hope it gets merged soon. It certainly took a while to do something as trivial as excluding two files...

**Comment by danielkesselberg** [comment]
`/\.webapp-nextcloud-(\d+\.){3}(-r\d+)?/` does not work for `.webapp-netxcloud-12.0.5`?
