### ISSUE TITLE
[Bug]: Calling remote.php trows an error in front

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#31137]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Go to https://demo1.nextcloud.com/remote.php

![image](https://user-images.githubusercontent.com/12234510/153706828-02d66045-b0b1-40f3-9a74-81e8111aaf52.png)

### Steps to reproduce

1. Go to https://demo1.nextcloud.com/remote.php with the browser

### Expected behavior

This should't silently redirect to `index.php` instead?

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by rawtaz** [comment]
> This should't silently redirect to index.php instead?

@acsfer Unless I'm mistaken, this endpoint is meant for API communication so not really something that should redirect to an interactive index page. Does that make sense? What makes you feel that it should redirect to the index page?

**Comment by acsfer** [comment]
Call the file `console.php`, it's what happens.

**Comment by rawtaz** [comment]
The `console.php` is not meant to be used over HTTP(S), while the `remote.php` is, so you can't really compare them.

Again, what makes you think that an application making an API request to `remote.php` without asking for a valid service should get anything else than a 404 in return? It seems perfectly valid to me. It's the right code for when what they asked for doesn't exist, and redirecting them to the login page makes no sense because the requesting application won't have any idea what to do with that.

**Comment by acsfer** [comment]
Again, calling a file directly shouldn't return this kind of page (see screenshot first post). No matter what file is.

**Comment by rawtaz** [comment]
You are not answering my question. What other action should it do than return a 404, which is exactly the right code for when the requested resource isn't found? If you think it should redirect to the index page, why do you think so, given what I wrote earlier?

Also, since you mention the webpage - what would you expect to see there instead? Just some nicer graphics? Remember, no human should ever access this page, so it's not really supposed to look good.
