### ISSUE TITLE
filescan retrun "entry will not be accessible due to incompatible encoding"

### ISSUE THREAD

**Issue by abolinhas** [nextcloud/server#3136]
Hi,
I'm using nextcloud11, I move a lot of folders/files from my old cloud to nextcloud, now when I execute the command php occ files:scan --all I get this error
Entry "/admin/files/Informa▒▒o Geografica/Areas_PGF/Caima.dbf" will not be accessible due to incompatible encoding
Entry "/admin/files/3_Eixo/Primeira Interven▒▒o/Sectores entidades.dbf" will not be accessible due to incompatible encoding
Entry "/admin/files/3_Eixo/Primeira Interven▒▒o/LEE.shp" will not be accessible due to incompatible encoding
and more...

How can I fix it?
Best regards

**Comment by nickvergessen** [comment]
@icewind1991 any idea what users can do?

**Comment by abolinhas** [comment]
Hi,
Any tips about it?

**Comment by icewind1991** [comment]
Do these files come from an OSX system?

The "most correct" way would be to upload the files trough the web interface, webdav or sync client which will ensure the encoding of the unicode characters is correct.

Alternatively you can convert the NFD encoded filenames (which OSX uses) to NVC encoded ones (what the rest of the world uses) while copying over the files. (see https://serverfault.com/questions/397420/converting-utf-8-nfd-filenames-to-utf-8-nfc-in-either-rsync-or-afpd for example)

**Comment by abolinhas** [comment]
No, I just copy from one folder to another on the same linux server.
Eg the command that I use
cp -R /oldcloud/home/folder /nextcloud/home/

**Comment by icewind1991** [comment]
It's possible that previously a client messed with the encoding then.

Can you try doing the encoding conversion while copying  (`rsync -a --iconv=utf-8-mac,utf-8 ...`)

**Comment by MorrisJobke** [comment]
No reply: I guess this is solved then. 

We are happy to reopen if this hasn't solved the issue for you.

**Comment by wendall** [comment]
I had the same issue with Russian symbols in folder/file names. @icewind1991 is right, the problem was in NFD encoded filenames.
Just installed **convmv** and run:
`convmv -f utf-8 -t utf-8 -r --notest --nfc <nextcloud-data-folder>`
After this a simple reindex helped me to see my data in Nextcloud:
`php occ files:scan --all`

**Comment by Gatak** [comment]
Just a note to say this fixed the issue for me too. Weird thing is that I have no idea how I got the NFD encoded filenames to start with!

**Comment by philippebaque** [comment]
> I had the same issue with Russian symbols in folder/file names. @icewind1991 is right, the problem was in NFD encoded filenames.
> Just installed **convmv** and run:
> `convmv -f utf-8 -t utf-8 -r --notest --nfc <nextcloud-data-folder>`
> After this a simple reindex helped me to see my data in Nextcloud:
> `php occ files:scan --all`

thank you Wendall..this fix it , you saved my time a lot! clap…clap…clap…

**Comment by mraniki** [comment]
thanks. this has helped me.

**Comment by plu** [comment]
`convmv -f utf-8 -t utf-8 -r --notest --nfc <nextcloud-data-folder>`

This command just said everything is already in utf8, and it did not rename anything.

`convmv -f utf-8 -t utf-8 --nfc -r --nosmart --notest <nextcloud-data-folder>`

Adding `--nosmart` fixed it finally.

**Comment by Dulanic** [comment]
Even tried the comment from @plu  and I still can't get mine fixed. I can't find that these files exist!

```
dulanic@mediaserver:/mnt/nextcloud$ docker exec -it nextcloud occ files:scan dulanic
Starting scan for user 1 out of 1 (dulanic)
        Entry ".dtrash/files/2023\ 01\20140614_104333_C6F53E88-84c7c26a.jpeg" will not be accessible due to incompatible encoding
        Entry ".dtrash/info/2023\ 01\20140614_104333_C6F53E88-84c7c26a.dtrashinfo" will not be accessible due to incompatible encoding
+---------+--------+--------+--------------+
| Folders | Files  | Errors | Elapsed time |
+---------+--------+--------+--------------+
| 465     | 105941 | 2      | 00:00:19     |
+---------+--------+--------+--------------+
```

**Comment by pgmillon** [comment]
I tried using convmv on files rsync'ed from my old Synology to a dedicated linux desktop and it completely messed up the files. I ended up with plenty of convmvtmp files.
I'll try [detox](https://github.com/dharple/detox) as an alternative to remove latin characters entirely.

**Comment by ph818** [comment]
Hey thanks for the suggestion of `detox`

I was able to use one of the other tools to create safe versions of the Mac-style encodings (I'm sorry I don't remember which tool) but unfortunately now I'm left with duplicate directories, one which works and one which is incompatible, such as: 

```
Henri Dikongué # incompatible
Henri Dikongué # compatible
```

I think the web browser automatically converts them both into correct encoding, but in the terminal, the top one has the accent floating high above the 'e' while the bottom one has the normal accented 'e'.

With `detox` I was able to use `detox --dry-run -s utf_8-only` on the pair of names, and it renames the 'wrong' one with underscores, allowing me to delete it. I did not trust to run detox on everything because even with this -s sequence, it wants to rename a lot of things that don't bother nextcloud.
