### ISSUE TITLE
Tedious bug tracker

### ISSUE THREAD

**Issue by stanelie** [nextcloud/server#3167]
### Steps to reproduce
1. get an error with Nextcloud that you want help with
2. go to github to file a bug report
3.

### Expected behaviour
Filing a bug report should be a short, easy process. There should be a form in the Nextcloud admin panel with a button labeled "file bug report" that when pushed, collects a dump of all the relevant log files, sanitizes them and bundles them with a description of the issue, before posting it directly on github or to the relevant outlet. 

### Actual behaviour
There is a long and tedious form to complete, and I am required to gather lots of logs from numerous places using cabalistic commands

**Comment by aventrax** [comment]
100% right, I did it one time, now I'm waiting other people to fill the bug request if the issue is not so important for me :)

**Comment by nickvergessen** [comment]
There is an app for it: https://github.com/juliushaertl/issuetemplate

Otherwise sorry that it bothers you so much. The problem is most of the time so much information is missing, that we have to answer each others posts 2-3 times, before the necessary information is provided. And some additional information you wouldn't ask for explicitly for end up helping from time to time e.g. when you see that an app is activated/missing etc.

I created an issue on the app it should be added to the appstore, so you can install it with one click and then it should be rather easy.

Sounds good?

**Comment by stanelie** [comment]
It's not that it bothers me that much, it's just time consuming and I thought it could be improved. I was not aware of this app, it looks great, exactly what I wanted!

Thanks!

**Comment by stanelie** [comment]
Hum, I am unable to install it, the "enable" button is disabled with the following error message : 

> This app cannot be installed because the following dependencies are not fulfilled:
>     Server version 9.2 or lower is required.

I have owncloud 11.0.1 installed.

**Comment by juliushaertl** [comment]
@stanelie I've just released the app to the app store and it is now also compatible with Nextcloud 11.
