### ISSUE TITLE
Shared Photos not rendering on Discourse forums due to object tag

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#32148]
**Describe the bug**
Sometimes shared photos are one-boxed when they should be embedded.  [See this discussion on the forum for why Nextcloud photos are not displayed properly](https://meta.discourse.org/t/nextcloud-images-not-displaying-in-discourse/148908).  

This is because of a missing og:type meta tag. Currently it is set to object. If it was set to image onebox would treat it as such.

**To Reproduce**
1. Go to '...'  Share Photo by url and append ?format=.jpg

**Expected behavior**
Image can be shared to a discourse forum and embedded with the proper url scheme.

**Comment by carlcsaposs** [comment]
Is the expected behavior:

1. https://cloud.disroot.org/s/RSZgiiS4AmpicEF embeds as image in Discourse
2. or https://cloud.disroot.org/s/RSZgiiS4AmpicEF/preview embeds as image in Discourse?

Based on some brief testing on https://try.discourse.org, the 2nd option already works as expected (as long as the link is on its own line).

**Comment by sunjam** [comment]
> the 2nd option already works as expected

Better to ask discourse devs literally.  [meta.discourse.org](https://meta.discourse.org/t/nextcloud-images-not-displaying-in-discourse/148908/7)

Their exact advice:

`Nextcloud can fix this by setting a proper og:type meta tag. Currently it is set to object. If it was set to image onebox would treat it as such.`

If you want clarification you can ask them; they are a friendly and responsive bunch.

**Comment by carlcsaposs** [comment]
@sunjam My interpretation is that Falco's (discourse dev) suggestion was to add the `og:type` tag to get the 1st option to display as an embedded image instead of as "one-boxed" (as a link preview with a small image & text).

However, after reading your original post on the linked thread, I was wondering if you only expected the 2nd option to display as embedded instead of both the 1st and 2nd option--could you clarify what you imagine the "expected behavior" is?

-----

Also, @skjnldsv I was wondering if the current behavior is what's expected--that the 1st option generates a link preview instead of an embedded image when shared on Discourse.

**Comment by leighboz** [comment]
Seems like the issue is fixed. Thread on meta.discourse.org specifically says that links with '/preview' on the end don't display inline but if you test it on try.discourse.org as carlcsaposs says, they do.

**Comment by szaimen** [comment]
> Seems like the issue is fixed.

thanks for checking
