### ISSUE TITLE
[Bug]: trusted_proxies check passes security and setup warnings checks with any value

### ISSUE THREAD

**Issue by timkgh** [nextcloud/server#32299]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I run NC 23.0.4 behind a Caddy proxy, using php-fpm. Caddy 2.5.1 runs on the same host and it's configured as a reverse proxy with the directive `php_fastcgi unix//run/php/php7.4-fpm.sock`

Without the `trusted_proxies ` set in config.php, I get a warning about the reverse proxy that points to
https://docs.nextcloud.com/server/23/admin_manual/configuration_server/reverse_proxy_configuration.html

I discovered that I can set `trusted_proxies ` to any random value, even invalid values, e.g. string instead of array and the warning goes away, it's all green. This does not seem right.

### Steps to reproduce

1. configure NC 23.0.4 with Caddy 2.5.1 as reverse proxy via Caddy directive `php_fastcgi unix//run/php/php7.4-fpm.sock` (on Ubuntu 20.04)
2. Without `trusted_proxies` set, you will see a warning about reverse proxy  
3. Now, with `trusted_proxies` set to ANY value (even invalid values), the warning goes away

### Expected behavior

The security check should validate the `trusted_proxies` value is correct.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Other

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
default
```

**Comment by timkgh** [comment]
I think the problem here has something to do with PHP-FPM via a Unix socket. Caddy sets the header `X-Forwarded-For` and Nextcloud thinks the request is coming via a proxy. Can Nextcloud be configured so that it recognizes php-fpm via a Unix socket as trusted?

**Comment by chemnic** [comment]
@timkgh, did you find more info about this problem?

This issue happens since Caddy 2.5.0. Before that I didn't see the warning.

I have tested with NC 22 and 23; PHP 7.4 and 8.0, with the same results.

For now my workaround is to put `127.0.0.1` as `trusted_proxies`.

Other ideas?

**Comment by redr00t** [comment]
hi guys!! is the "127.0.0.1" / "localhost" workaround safe to use?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Eimuex** [comment]
@szaimen I have exact same issue on 25.0.2 but with nginx proxy. I saw warning about month ago for the first time and when I add trusted_proxies even with random string, warning goes away.

**Comment by joshtrichards** [comment]
> Without trusted_proxies set, you will see a warning about reverse proxy

This is expected behavior *if* you lack a `trusted_proxies` value in your `config.php` AND the NC server receives an `X-Forwarded-Host` header in the HTTP request.

This is the first part of the check we do for a valid and functioning reverse proxy configuration in the CheckSetupController. Triggering this part of the check causes an immediate failure because it indicates you're using a reverse proxy, but don't have NC configured for it so we have no way to verify if the headers we're receiving are from an actual *trusted* reverse proxy.

> Now, with trusted_proxies set to ANY value (even invalid values), the warning goes away

If the prior check passes, we then confirm:

- `trusted_proxies` is a valid array
- the HTTP request `REMOTE_ADDR` header is in the `trusted_proxies` array
- the HTTP request `REMOTE_ADDR` header isn't equal to "127.0.0.1"
- the HTTP request `REMOTE_ADDR` header isn't equal to the `X-Forwarded-For` header

The reason this cropped up for you is because of the [change of default behavior in Caddy v2.5.0](https://github.com/caddyserver/caddy/releases/tag/v2.5.0). Caddy, probably more properly, now includes the `X-Forwarded-Host` header by default if it knows it's operating as a reverse proxy. This means NC now can tell for certain it's behind a reverse proxy. And, in the case of the folks on this Issue, it exposes that the `trusted_proxies` isn't configured properly in your NC setup.

In your situation, Caddy is operating as your reverse proxy so it's appropriate to follow NC's conventions by configuring a `trusted_proxies` parameter in your `config.php`. It just happens that without the `X-Forward-Host` parameter that NC would allow your situation to work. But since Caddy started populating `X-Forwarded-Host` as of v2.5.0, by default, NC is now recognizing it's truly behind a reverse proxy.

> For now my workaround is to put 127.0.0.1 as trusted_proxies.
> hi guys!! is the "127.0.0.1" / "localhost" workaround safe to use?
> This sounds right as a workaround, I don't think it matters when using PHP-FPM.

We can't actually check for certain whether you've entered a _correct and complete_ list of RPs in your `trusted_proxies` setting from a single simple setup check like we're doing here. We can only detect if your current HTTP request (the one triggering the test while you're logged in as an admin) is flowing through an RP.

You'll still want the values included in your `trusted_proxies` parameter to accurately reflect your reverse proxy topology. The value "127.0.0.1" might be appropriate, but it depends on your environment and the IP network link between your RP and FPM (or Web server, where applicable) and RP configuration. Even on the same physical host this can vary a bit (think Docker container networking).

You can tell if it's working (for the most part) by seeing what IP addresses get logged in your `nextcloud.log` (they should be the client IP addresses not the reverse proxy IP address) and whether you're getting hitting unexpectedly by things like the Brute force protection (you should not be) when you know you didn't trigger it yourself.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=trusted_proxies

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html?highlight=trusted_proxies

**Comment by joshtrichards** [comment]
@timkgh - Closing this out, but feel free to follow-up if you don't think addresses your query.
