### ISSUE TITLE
OCS Share API - "permissions" parameter has no effect

### ISSUE THREAD

**Issue by timowevel1** [nextcloud/server#32611]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The OCS Share API doesnt work properly. One is not able to set the permissions, it always stays "17".

### Steps to reproduce

1. Create Share Link via API with the desired permissions

### Expected behavior

Permissions are set correctly

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Only default apps, fresh install
```

**Comment by jplitza** [comment]
I guess the problem is this else block:
https://github.com/nextcloud/server/blob/62919ac81eb856a15c0131f3cf948bb11b2a5b1f/apps/files_sharing/lib/Controller/ShareAPIController.php#L569-L586
It has been like that since the introduction of the API, but obviously ignores the permissions requested by the client. I'm not sure why that block is there at all, IMO it could simply be removed. But there may be a reason to cap the permissions to something applicable to files (like read & update?).

**Comment by timowevel1** [comment]
Still not fixed, I am not able to set the permissions. It doesnt matter which value the "permissions" parameter has, it always gets permission "17"
![image](https://user-images.githubusercontent.com/25285295/219853265-e3e5730d-fe7f-4e57-a8ad-eca2deb807f4.png)
![image](https://user-images.githubusercontent.com/25285295/219853276-435ee304-855e-4357-8107-0cd453696d8d.png)
