### ISSUE TITLE
[RFC] Drop /apps Route in Apps URLs

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#3263]
Just a quick idea. Please excuse, if this was discussed before, but...

would it be possible to drop the `apps` in the URLs of apps. 
So 

`http://exmaple.org/nextcloud/apps/calendar/`
becomes
`http://example.org/nextcloud/calendar/`

Just look how sexy that reads. 😍  

Or https://epp.cloud/calendar

We only would have to restrict possible app names from standard namespaces, like /settings, etc.

@LukasReschke @MorrisJobke who else to mention for this?

**Comment by MorrisJobke** [comment]
we just do this for proper namespacing. Otherwise we could run into issues where we want to have an internal route but an app with the same name would collide.

But in the end: if we define some of our internally used names and forbid them I would like this approach.

@nickvergessen @rullzer @icewind1991 @schiessle @blizzz @karlitschek Opinions on this?

**Comment by LukasReschke** [comment]
I'm not a fan of this, this limits us massively in the future on choosing names for URLs. My favour would be with keeping the `/apps/`

**Comment by rullzer** [comment]
I must say I'm with @LukasReschke here. If we must do this then do if fancy like the short sharing url. So: https://epp.cloud/a/calendar although IMO we should then go with https://epp.cloud/awesomoApps/calendar

**Comment by MorrisJobke** [comment]
Okay ... we keep it -> closing ;)
