### ISSUE TITLE
Gender-neutral language

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#32720]
Ref https://help.nextcloud.com/t/geschlechtsneutrale-sprache-genderneutral/82200/107

## In general

* user → person/people or account/accounts based in the context
* participant → member

## Specific items

* [ ] Settings: Personal/Individual/User
* [ ] First run wizard / About
* [ ] Users
  * Decide to use “People”(Personen) or “Accounts”(Konten) - accounts being the preferred wording if applicable
  
* [ ] Apps
* Navigation:
  * Documentation for Developers → Development documentation
* Sidebar:
  * Documentation for Users → Usage documentation
  
* [ ] Help
* Navigation:
  * Documentation for Users → Usage documentation
  * Documentation for administrators → Administration documentation
  
* [ ] Dashboard
  * Weather: Set custom address → set address

* [ ] Files
* Sidebar:
  * Internal Link: Only works for users ... → Only works for people
  * Link share
    * custom → advanced
    * Note to recipient → Note

### To do

- [ ] Find the old terms grepping through the language master file
- [ ] Replace old terms with new ones (see at the top)

**Comment by Croydon** [comment]
I understand this problem in (strongly) gendered languages like German. 

I don't really understand this issue, which seems to be about the English language. None of the terms you mentioned above are gendered. Could you clarify if you really mean to replace these terms in English?

**Comment by AndyScherzinger** [comment]
@Croydon you are right of course and I updated the description. For User and Participant it is a bit different though, we want to get rid of "Users" for example and use "People" or "Accounts" because

- It’s more understandable
- more human language
- easier for translators

**Comment by despens** [comment]
Maybe replacing the term "user" with "person" should be discussed independently from gender neutral language. Terms like "user," "administrator," and "developer" are very useful signifiers for power relationships in software. These power relationships don't go away when you change these words and make everyone a "person." It is understandable that software developers want to do good and want to express that by calling their users as "people," but that essentially makes invisible the role of the user and prevents important discussion.

**Comment by AndyScherzinger** [comment]
Just to clarify that last comment, there is no statement to treat the terms user, developer and administrator with the same term. Person/people is for the term user only.

**Comment by Spartachetto** [comment]
I do appreciate the effort, yet I'll pose you a challenge I face.

When talking about users of a system, I find useful the distinction between a "person" and a "user".
I use often in explanations the second term for "a person which has access to the system", while the first is used for "any person, even one that still has not access to the system ".
This distinction is almost always useful during the registration phase.

Do I miss something?

**Comment by AndyScherzinger** [comment]
> Do I miss something?

Can't say for sure :D 

But that is why @jancborchardt defined both term as the new terms to be used for "user/s" based on the context:

* account/accounts
* person/people

**Comment by Spartachetto** [comment]
I was missing the "account/accounts" bit.

That indeed solves the issue I was talking about

**Comment by Ornias1993** [comment]
I agree @despens that the user->person thing has nothing at all to do with gender neutrallity, as both are gender neutral already.
But I also actually completely disagree with this at all.

- A person is entity representing a natural person. 
- A user is an object that uses a system.
Hence: A user isn't inherently a person and a person is not inherently a user.

Maybe this is different in german (and I'm also a bit "not okey" if such important discussions are mostly limited to german but are affecting other languages as well) but in English this change does not really make any sense.

**Comment by PeterSchmidt23** [comment]
Thank you for making Nextcloud almsot unusable for handicapped people:

https://www.dbsv.org/gendern.html

**Comment by PeterSchmidt23** [comment]
https://www.dbsv.org/gendern.html#erlaeuterungen

**Comment by capelo0** [comment]
Go Woke and Go Broke.

**Comment by PeterSchmidt23** [comment]
> I'm sorry @PeterSchmidt23 but what you have been referencing is exactly what is the goal here to be achieved, so no nobody here is making Nextcloud unusable for handicapped people.

Why dont use another language option. 

- Deutsch/Du, 
- Deutsch/Sie, 
- Deutsch/Neutral

It will be much easier to revert if it will change in the future.

**Comment by PeterSchmidt23** [comment]
It seems that there is not much room for discussion, if it doesnt fit your ideology. That's bad for a company. Respect the downvotes!

**Comment by AndyScherzinger** [comment]
I am sorry @PeterSchmidt23 if you are not happy with your opinion being judged but your comments aren't constructive in anyway, see 

> Thank you for making Nextcloud almsot unusable for handicapped people:

And you seem to be simply ignoring the point, we are not aiming for a gendered terms (MitarbeiterInnen) but gender-neutral terms (Mitarbeitende) if you are fighting this you are simply the intolerant part in the discussion. So framing this as censorship using terms like ideology is plain wrong or rather points towards idiology issues on your end.

**Comment by Ornias1993** [comment]
> I am sorry @PeterSchmidt23 if you are not happy with your opinion being judged but your comments aren't constructive in anyway, see
> 
> > Thank you for making Nextcloud almsot unusable for handicapped people:
> 
> And you seem to be simply ignoring the point, we are not aiming for a gendered terms (MitarbeiterInnen) but gender-neutral terms (Mitarbeitende) if you are fighting this you are simply the intolerant part in the discussion. So framing this as censorship using terms like ideology is plain wrong or rather points towards idiology issues on your end.

Agreed, for german users the generisation issue makes more sense from a language perspective. Even byond idiology.
For english a good discussion can be had, But I take the milestone tag is mostly aimed for just german use?

**Comment by PeterSchmidt23** [comment]
> I am sorry @PeterSchmidt23 if you are not happy with your opinion being judged but your comments aren't constructive in anyway, see
> 
> > Thank you for making Nextcloud almsot unusable for handicapped people:
> 
> And you seem to be simply ignoring the point, we are not aiming for a gendered terms (MitarbeiterInnen) but gender-neutral terms (Mitarbeitende) if you are fighting this you are simply the intolerant part in the discussion. So framing this as censorship using terms like ideology is plain wrong or rather points towards idiology issues on your end.

It seems there is a communication problem with the translators, as you can see in the screenshot. 

![image](https://user-images.githubusercontent.com/130473712/235614218-2bf6034d-d56d-4231-9151-52f6f37c92ca.png)

**Comment by AndyScherzinger** [comment]
> It seems there is a communication problem with the translators, as you can see in the screenshot.

Yes @PeterSchmidt23 - that was not the goal since this is obviously not gender-neutral

cc @jancborchardt since I think we didn't define anything for moderation and also cc @rakekniven

**Comment by metsuke0** [comment]
If this is just a translation issue and only applies to German, perhaps the title and description should change to reflect this?

**Comment by PeterSchmidt23** [comment]
> Yeah, seems we need guidelines for German translation then. In these 2 cases it can just be "Administrierende" and "Moderierende".
> 
> "Admins" is fine too but quite informal, and "Moderierende" is shorter, more inclusive and less complex than "Moderator:innen".

Ok. But, at the end everything sounds not natural. And that is what most people are thinking about. Look at the downvotes. 
This one sentence would have been enough. 

Gender-Hinweis

Aus Gründen der besseren Lesbarkeit wird auf die gleichzeitige Verwendung der Sprachformen männlich, weiblich und divers (m/w/d) verzichtet. Sämtliche Personenbezeichnungen gelten gleichermaßen für alle Geschlechter.

Source https://www.ihk.de/aachen/servicemarken/gender-hinweis-5174804
And many other companies are doing it this way.

**Comment by jancborchardt** [comment]
@PeterSchmidt23 the one sentence is enough, yes – if you are a man and content with the "generisches Maskulinum" and the issues it entails, which is why we want to fix it in the first place.

For more details on why we won't add an explanation like that, see the section "Gender-Fußnote, Generalklausel" on https://de.wikipedia.org/wiki/Geschlechtergerechte_Sprache#Strategien_des_geschlechtergerechten_Formulierens

Excerpt (German)
> „Wir halten sie für nicht sinnvoll. Angesichts der inzwischen vorliegenden psycholinguistischen und kognitionspsychologischen Erkenntnisse ist es klar, dass diese Form keineswegs eine ‚erleichterte Lektüre‘ erzeugt. Im Gegenteil: Für Frauen (also immerhin statistisch gesehen die Hälfte aller Personen, die den Text lesen) bedeutet diese Praxis ebenso wie die unkommentierte Verwendung des ‚generischen Maskulinums‘ eine erschwerte Lektüre, weil nicht aus den sprachlichen Formen selbst zu erkennen ist, wann sie ‚mitgemeint‘ sind und wann nicht.
> Diese Fußnote trägt nichts zur Verbesserung der Gendergerechtigkeit des Textes bei und hat rein rechtfertigende Funktion: Sie ist ein Versuch, die Regeln gendergerechter Sprache einerseits zwar anzuerkennen, andererseits aber ihre Anwendung zu vermeiden, ohne dafür gescholten zu werden.“
> – Gabriele Diewald, Anja Steinhauer (April 2020)

**Comment by prilly-dev** [comment]
I dont undestand this, why do we need gender neutral? is it so difficult to separate he and she?

**Comment by AndyScherzinger** [comment]
Hi @rakekniven,
never have done that. Any pointers on where to write what on TX? Or would you write that as a translations lead?

**Comment by MrRinkana** [comment]
In Swedish the above mentioned terms do not have a gender (very few words in general have gender in Swedish). This is also the case in English which is used as the source language.

On other platforms the term user and participant is more established, both in English and Swedish. 

In the case of participant/member "Member" is used mostly for "member of club/association" - never as "member of meeting" for example. Since calendar/meetings is a common usage in Nextcloud, that change will lead to poor translations. (Swedish)

In a list of users as given in the description, "persons" feels a bit wrong in Swedish, as few people are their nextcloud accounts - however "accounts" sounds very dry and nonpersonal. "Users" does not have these problems. 

Especially "Internal Link: Only works for users ... → Only works for people" and such is not very accurate (it does not work for people, only accounts on the instance) and might be confusing for users. I suspect it is even more so in Swedish, where "people" is more similarly broad as "humans". "..works for persons" does not work either.

In general for Swedish, the term "user/users" is better than the replacements. In cases where people intend to interact with "persons", such as when sharing, the terms "persons" or "users" are already not used (instead just: "share" or "share with someone"). Where users is used, the distinction is necessary (such as the "... only works for users") and "persons" does not work well.

 In Swedish "Development" is more used in contexts such as "landscape development", "technological development" or "personal development". The specific term "developer" is much, much more strongly tied to software and coding. Hence "Development documentation" will not be as immediately clear as "developer documentation" would.

Another example is the term "user documentation" where the term user cannot be replaced by neither "person" or "account": 
<details> 
  <summary>Example misstranslation: </summary>
 I just found a button under "Nextcloud help resources" (Help button from account icon) that has been translated to "Account documentation" ("Kontodokumentation") which will make no sense to a swede. I'm not sure if this is from an automated translation or if a translator got confused since context is sometimes hard to find/understand in Transifex. The correct translation for this would be "Användarhandbok" (user manual). While it is possible to just use "manual", its distinction from the other options would be much less clear (button is next to "administration documentation" and "generic documentation").
</details>

---

It is my belief that this makes translating affected strings a little harder as:
1. It will be less clear to translators what a string is supposed to mean, as "user" is a more established term used at other platforms. "User" is in some cases, as the example above from the description, more accurate.
2. It will lead to miss-translations as translating the term literally will lead to errors, or unnatural language. Context is hard to find in transifex, as you don't see the UI where the string is used, and it might be hard to find for the translator.  
3. It gives no benefit to languages where those terms are not gendered.
4. "Account" can feel very dry and sterile/nonpersonal if used in context other than "manage your account".

---

I occasionally translate or review the Swedish translation, how do you want me to proceed? Is it okay that I keep "user" in places where it makes more sense, only using person where it sounds natural and keeping "account" only in "manage account"-type contexts? Or would you prefer if we tried to replace the term everywhere except cases where it really cannot be used, like the given example with user documentation?

Just to be clear: I support the effort towards usage of gender neutral language, I just have identified some problems/disadvantages to this particular change, in the context of the English-source and Swedish.

**Comment by skjnldsv** [comment]
@MrRinkana we can't control or investigate all translations, we'll put our trust in our dear translators to make the right choice :)

I think you get the point, we've explained the direction and goal of this from the English perspective (even with a few French or German examples on the transifex announcement), since my Swedish knowledge is nonexistent, I hope you'll be able to find a proper noon that fits the goal we're trying to achieve here! :hugs: 

Thanks for taking the time to write your message! It's nice that you show interest and motivation! :muscle:
