### ISSUE TITLE
user-based nextcloud apps with default web interface

### ISSUE THREAD

**Issue by ralfi** [nextcloud/server#32755]
Dear Nextclouders,

it would be very helpfull to make it possible to configure user-based apps for the nc web-interface, f.i. user 1 is able to use talk, user 2 is able to use deck and photos, user 3 use only collabora online and so on.

**Comment by Spartachetto** [comment]
You can define users groups and then determine which users groups have access to an app. 
It should work with most apps.

Does this answer your need?

**Comment by ralfi** [comment]
Hi Spartachetto,

of course this could be possible for some apps but in german i call this " from behind through the breast in the eyes ... " do you know... BTW i really dont know what to do (god protect me for self coding ...) with coding to realize this. This is only a tip.

Regards

**Comment by joshtrichards** [comment]
This is already supported, as @Spartachetto pointed out.

https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html#managing-apps

The manifest for an app must *not* contain `prevent_group_restriction`. There are also a few apps that can't support this for various reasons because other things might break.

Of the ones you listed in your example:

- Talk (Spreed): [prevents this explicitly](https://github.com/nextcloud/spreed/pull/203)
- Deck: supports this
- Photos: I don't see it explicitly prevented but the app type may prevent it
- Collabora Online (richdocuments): [prevents this explicitly](https://github.com/nextcloud/richdocuments/commit/d359d1452fd990d470caad6393ef9f523551ed71)

So `server` already supports the functionality. Please create enhancement requests with the respective apps via their defined channels and/or third-party developers (where applicable) to discuss the possibility.
