### ISSUE TITLE
[Bug]: Text editor displays encrypted text  from encrypted external folder

### ISSUE THREAD

**Issue by jbuggie** [nextcloud/server#33146]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When create a new text file on an encrypted external shared, Nextcloud text editor opens up the file without decrypting its content thus showing the encrypted content

### Steps to reproduce

1. New Nextlcoud installation 24.02, enable server encryption,  external folder
2. Create a new external folder, select "Encryption: yes"
3. Create a new text file on the external folder, Nextcloud will open up the file and display encrypted content

### Expected behavior

The text editor should display decrypted content of the file

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nxcloud"
        ],
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "overwrite.cli.url": "https:\/\/nxcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.1
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.6
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.1
  - richdocumentscode: 22.5.301
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.2
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Error	files_external	Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1003 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/)	
2022-07-06T18:15:10-0400
Error	files_external	Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1002 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/)	
2022-07-06T18:14:17-0400
Error	files_external	Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/)	
2022-07-06T18:14:12-0400
Error	files_external	Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/)	
2022-07-06T18:14:03-0400
Error	files_external	Exception: Bucket has to be configured.	
2022-07-06T18:13:50-0400
Error	core	Doctrine\DBAL\Exception\ConnectionLost: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away	
2022-07-06T18:11:20-0400
```

### Additional info

The desktop client can sync the encrypted file fine and the content of the file is unencrypted on the desktop

**Comment by EGermond** [comment]
Similar issue: but when adding files from my computer.
### Bug description

When create a new text file on my computer, then synchronise it on my nextcloud, it shows the encrypted content in Markdown Editor. The problem is the same with Collective, probably because it depends on Markdown Editor.
### Steps to reproduce
-     Nextlcoud installation updated to 24.0.8, enable server encryption deault module, nextcloud client on the desktop version 3.4.2 (Ubuntu), Collective plugin, Markodown editor plugin
-     Create a new markdown or text file on the computer in the collective folder then synchronise it with nextcloud
-     The file will show encrypted in the collective tab and in Markdown Editor.
-     The file stays decrypted on the computer.

### Installation

Nextcloud 24.0.8 on web hosting

`Accessibility 1.10.0

Activity 2.16.0

Brute-force settings 2.4.0

Calendar 3.5.4

Circles 24.0.1

Collectives 1.6.3

Comments 1.14.0

Contacts 4.2.3

Contacts Interaction 1.5.0

Cospend 1.4.10

Dashboard 7.4.0

Deck 1.7.3

Default encryption module 2.12.0

Deleted files 1.14.0

Draw.io 1.0.5

Federation 1.14.0

File sharing 1.16.2

First run wizard 2.13.0

GPodder Sync 3.7.1

Log Reader 2.9.0

Markdown Editor 2.3.6

Metadata 0.17.0

Monitoring 1.14.0

News 20.0.0

Notes 4.5.1

Notifications 2.12.1

Password policy 1.14.0

PDF viewer 2.5.0

Photos 1.6.0

Privacy 1.8.0

QOwnNotesAPI 22.10.0

Recommendations 1.3.0

Right click 1.3.0

Share by mail 1.14.0

Social sharing via email 2.5.0

Support 1.7.0

Tasks 0.14.5

Text 3.5.1

Update notification 1.14.0

Usage survey 1.12.0

User status 1.4.0

Versions 1.17.0

Weather status 1.4.0

Auditing / Logging 1.14.0

Bookmarks 11.0.4

Collaborative tags 1.14.0

External storage support 1.16.1

LDAP user and group backend 1.14.1

Nextcloud announcements 1.13.0

Theming 1.15.0

Video player 1.13.0`

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
