### ISSUE TITLE
Style of 2FA login page is broken

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3326]
Followup to #3207 

bug is still not fixed for 2FA pages:
![bildschirmfoto von 2017-01-30 14-10-02](https://cloud.githubusercontent.com/assets/1374172/22424282/2d216004-e6f6-11e6-84c9-e61f906d7999.png)

cc @skjnldsv @ChristophWurst

**Comment by skjnldsv** [comment]
@ChristophWurst Since we now use the guest.css file, you would require to add it on your twofactor_totp app.
How do you plan to make your release compatible with older version of nextcloud then?

I could add in from core so all page that doesn't uses the scss compiler have the guest file by default, but I'm not sure this is such a great idea. What do you think?

**Comment by ChristophWurst** [comment]
> @ChristophWurst Since we now use the guest.css file, you would require to add it on your twofactor_totp app.
> How do you plan to make your release compatible with older version of nextcloud then?

We must not break compatibility there. This file should be included automatically, by the server. Apps should not rely on style sheets being available in server. We could remove that file in the future.

**Comment by skjnldsv** [comment]
Okay, will fix tonight! :ship:
