### ISSUE TITLE
[Bug]: Unsupported `opcache.file_cache_only`?

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#33325]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Configure PHP-FPM opcache with `opcache.file_cache_only=1`
Nextcloud will output warnings on the Admin page.

>The maximum number of OPcache keys is nearly exceeded. To assure that all scripts can be hold in cache, it is recommended to apply `opcache.max_accelerated_files` to your PHP configuration with a value higher than `10000`.

>The OPcache buffer is nearly full. To assure that all scripts can be hold in cache, it is recommended to apply `opcache.memory_consumption` to your PHP configuration with a value higher than `1536`.

>The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply `opcache.interned_strings_buffer` to your PHP configuration with a value higher than `96`.

Full configuration:

```
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=1536
opcache.interned_strings_buffer=96
opcache.max_accelerated_files=1048793
opcache.file_update_protection=5
opcache.validate_permission=1
opcache.validate_root=1
opcache.file_cache_only=1
opcache.file_cache=/tmp
opcache.file_cache_consistency_checks=1
```

@MichaIng mind to have your input here?

### Steps to reproduce

1. Configure PHP-FPM opcache with `opcache.file_cache_only=1`

### Expected behavior

No warnings

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

### Additional info

Solved removing any `opcache.file_cache*` configuration.

**Comment by MichaIng** [comment]
The recommendations of the admin panel with our settings are correct, since with `file_cache_only`, memory-based OPcache is disabled, breaking performance a lot, and the other settings which are checked are without effect. Can you verify e.g. via https://github.com/amnuts/opcache-gui that used memory, interned strings and cached keys are all zero?

Is `/tmp` a tmpfs in your case? If so, I don't really see a difference between your setup and simply skipping the `file_cache`, aside of that letter will use the native OPcache feature instead of some configuration-wise round trip which surely works less effective than the intended shared memory.

`opcache.file_cache` is usually used to faster restore the regular shared memory OPcache e.g. after server or service restarts, or when clearing the cache after it was full. `file_cache_only=1` however disables the shared memory OPcache completely. Just assure that this is what you wanted to achieve, and if so, the admin panel is correct that your setup isn't optimal from performance point of view.

**Comment by solracsf** [comment]
Well, in this case, these warnings are pretty intrusive. Sysadmins who enable file_cache do it for a good reason (eg. shared systems where memory based Opcache is unsuitable for some reasons) so when this is detected, Opcache setup checks should just be skipped. Otherwise, NC admins thinks this is a setup issue while it is not (again, server side perspective, not NC one).

**Comment by MichaIng** [comment]
Hmm, especially on a shared system I'd think that the memory based OPcache is better suited than a file based one, since user A cannot invalidate the cache of user B then, assuming that dedicated FPM pools (hence dedicated OPcache instances) are used. If it is intended that the cache is shared between all users, wouldn't it be better then to just use a single FPM pool instead of a shared file cache, so also workers can be shared more efficiently?

However, of course there are cases where it makes sense to set `opcache.file_cache_only=1`, which is why the option exist.

The main question is whether we generally want to give performance recommendations which are right and applicable in most cases, but of course can never be right or applicable in 100% of cases, also e.g. if system memory simply does not allow to further increase the cache. There are a lot of checks which one must ignore in certain cases, or which simply cannot be addressed in all cases, like shared hostings, containers etc. So for admins which know what they need and can do with their setup, it is expected that some notifications may need to be ignored. They are made as hints to look at for those admins which might not exactly know about every piece of their Nextcloud, webserver and PHP setup. In this particular case:
- Using `opcache.file_cache_only` disables the memory based OPcache and hence decreases performance, so in general it is right to show a recommendation.
- You know your specific setup best and whether you may follow the recommendation or not.
- Others who are probably new to the topic may be thankful for the hint that there are performance enhancements possible.

But we should at least check for `opcache.file_cache_only=1` in particular and then show a dedicated recommendation (like we do with `opcache.enable`), instead of showing the tree recommendations about settings which have no effect in this case.

**Comment by solracsf** [comment]
> But we should at least check for opcache.file_cache_only=1 in particular and then show a dedicated recommendation (like we do with opcache.enable), instead of showing the tree recommendations about settings which have no effect in this case.

At the very least, yes ;)

**Comment by MichaIng** [comment]
PR up: #35365

**Comment by Jolopu** [comment]
The warnings are finally gone on my shared host. But now, we got a new annoying warning:

Der OPcache mit gemeinsamem Speicher ist deaktiviert. Für eine bessere Leistung wird empfohlen, opcache.file_cache_only=0 in Ihre PHP-Konfiguration aufzunehmen und den Dateicache nur als Second Level Cache zu verwenden.

Unfortunately there is now way I can set opcache.file_cache_only on my shared host. So you just introduced a new warning, which we on shared hosts are doomed to live with.

**Comment by Jolopu** [comment]
I asked my hosting provider to change the setting. His answer might be of interest to you:

Der Parameter kann leider Benutzerseitig nicht verändert werden. Das können wir nur über den Support umsetzen, da dies direkt in der Systemkonfiguration gesetzt werden muss.

Ich möchte hier vorher aber auf eine Sache hinweisen. Der Opcache lagert die Daten dann im SHM also im shared Memory ab, dieser ist per se nicht geschützt und es kann sein das andere Benutzer des Servers diese Daten mittels einiger Tricks auslesen können. Es gibt zwar einige Parameter welche das etwas absichern, aber eine 100%ige Lösung ist das nicht. Aus dem Grund ist der SHM Teil des Opcache erstmal per Standard abgeschaltet.

Einen starken Einfluss auf die Performance im Nextcloud dürfte das nicht unbedingt bringen (Installations- und Verwendungsabhängig), nur prüfen die Entwickler das nicht richtig und gehen automatisch davon aus das SHM aktiv ist, wodurch es dann zu diesen unschönen Meldungen kommt.

**Comment by Jolopu** [comment]
Would be nice if this warning could be disabled if nothing can be done about it on a shared host and it doesn't apply anyway.

**Comment by MichaIng** [comment]
Why? Your know now that you shared hosting provider has a sub optimal PHP configuration performance-wise, probably to safe on hardware (RAM). Good to know IMO, so you can ask him to change it, or change the provider, or ignore the information.

Do not feel annoyed by a Nextcloud admin panel warning. There are many which do apply in some cases, not in others. I have 3 resp. 5 warnings on my instances, which I know are not relevant in these particular cases, but good to know about in general. And these are instances where I have full control of the system, PHP setup etc. On a shared hosting provider, I would be pretty surprised to not see a bunch of warnings, at least as long as it is not advertise to support Nextcloud well in particular.
