### ISSUE TITLE
Cache quota for 60 seconds

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#33553]
Check how to cache quota for 60 seconds, trade-off could be to just do this in the webUI and just do it for the left sidebar info.
Still check if applicable in other places on webUI.

**Comment by AndyScherzinger** [comment]
ping @CarlSchwan because we talked about it

**Comment by PVince81** [comment]
context was: ViewController is querying quota stuff to be able to populate the UI somehow, need to check the detail

there was a bug where ViewController was triggering the same event 3-4 times which caused apps to also query more stuff, perhaps also quota, this was handled in #33547

**Comment by PVince81** [comment]
in https://github.com/nextcloud-gmbh/server/issues/511 we have ideas to remove the quota population in ViewController by using the one from PROPFIND

**Comment by PVince81** [comment]
this is the expensive bit when checking used space: https://github.com/nextcloud/server/blob/master/lib/private/Files/FileInfo.php#L379

because it includes all mount points

it's triggered in:
- ViewController: https://github.com/nextcloud/server/blob/master/apps/files/lib/Controller/ViewController.php#L259
- PROPFIND on "oc:size" property: https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/Node.php#L239
- and getstoragestats for the legacy quota check

so three times within a page load of files app at least

**Comment by PVince81** [comment]
@icewind1991 thoughts on where to cache ? it seems there is no good location to cache it at all, and also it might mean querying the memcache factory from inside the FileInfo

I was thinking of maybe caching the submounts in FileInfo::updateEntryfromSubmounts.
