### ISSUE TITLE
Share to social networks

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3368]
* allow to share files/folders to social networks:
  * Facebook
  * Twitter
  * Google+
  * ... 

Maybe we look into https://github.com/owncloud/core/pull/25576 and adjust to our needs.

**Comment by rullzer** [comment]
So personally I really do not like this. Also it makes us select what we want there which is kind of meh...

Maybe some sort of plugin system would be better. So that people that want to share to status.net can do so. Or people that use digg can enable the digg-share-app or whatever.

Or maybe one app where we can enable/disbale things. Not sure.

Because we simply can't add everything to make everybody happy.

**Comment by MorrisJobke** [comment]
@nickvergessen @schiessle @karlitschek Any ideas for this?

**Comment by karlitschek** [comment]
Hmm. I think social sharing buttons in in general not a bad idea. The question is which and how to integrate them and where. @jancborchardt any ideas?

**Comment by rullzer** [comment]
See #3679
