### ISSUE TITLE
[BITV] Menus must be focus trapped

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#33743]
Tabbing out of a menu should close it.

Need to check all the menus in the top bar:
- [x] search: https://github.com/nextcloud/server/pull/35233
- [x] notifications: https://github.com/nextcloud/notifications/pull/1367
- [x] Popover component: check if they do (at least with Escape key)

Also: probably the menu should close when Escape is hit while inside the menu ? (need to check if WCAG requires this)

**Comment by Pytal** [comment]
Notifications https://github.com/nextcloud/notifications/pull/1367

**Comment by Pytal** [comment]
@PVince81 @skjnldsv focus trap all header menus like in https://github.com/nextcloud/nextcloud-vue/pull/3489 or allow tabbing out and closing like in https://github.com/nextcloud/server/pull/35090/files#diff-ae814dad42ef834e47dfd1d175e798e67c703ede5105470317fafabec5c2f60f

**Comment by skjnldsv** [comment]
I added focus trap on https://github.com/nextcloud/nextcloud-vue/pull/3489 too to help with your ongoing accessibility work :)

**Comment by Pytal** [comment]
Roger, so since they are mutually exclusive then which one should we go for @skjnldsv @PVince81?

**Comment by Pytal** [comment]
- [ ] https://github.com/nextcloud/server/pull/35381
  - [x] user menu
  - [x] contacts menu

**Comment by Pytal** [comment]
- [ ] Clarify with accessibility reviewer

**Comment by Pytal** [comment]
@michaelnissenbaum for the top-right menus we have 2 options

1) Allow tabbing out + automatically closing these menus and setting the focus on the next element in the page
2) Trap focus within these menus so that tabbing after reaching the last item will loop back to the first menu item and allowing users to close these menus by hitting the Escape key

Which option would pass the accessibility audit?

Menu | Screenshot
--- | ---
**Global search** | ![image](https://user-images.githubusercontent.com/24800714/204673462-f86df7f7-d5ba-4c43-81ee-fc44a0b4cf94.png)
**Notifications** | ![image](https://user-images.githubusercontent.com/24800714/204673516-e0b1a3be-b1f1-4283-9153-ef85097e21bf.png)
**Contacts** | ![image](https://user-images.githubusercontent.com/24800714/204673541-3a4bf9ce-2e86-405d-af62-f9aaada5d41d.png)
**User menu** | ![image](https://user-images.githubusercontent.com/24800714/204673555-054cb12a-ba29-4048-896b-f950c9320dd1.png)

**Comment by michaelnissenbaum** [comment]
My favourite is the version one - tabbing out and auto closing. The second version is OK as well, but then keep in mind that after you leaved the dialog using ESC key the keyboard focus must be returned back to the element which was used to open it and has to be clearly visible. And there's always a possibility that users don't know that they can use ESC to close the dialog.

**Comment by Pytal** [comment]
Thanks for your feedback @michaelnissenbaum!

After discussions with @PVince81 we've chosen go with option 2 as we have already been focus trapping many other UI elements and this will keep it consistent across the entire interface

**Comment by Pytal** [comment]
Transferred "contacts menu"
- https://github.com/nextcloud/server/issues/35638

**Comment by Pytal** [comment]
Transferred "Port notifications menu"
- https://github.com/nextcloud/notifications/issues/1426

**Comment by Pytal** [comment]
Transferred "Port global search menu"
- https://github.com/nextcloud/server/issues/36202

**Comment by Pytal** [comment]
Transferred "user menu"
- https://github.com/nextcloud/server/issues/36201
