### ISSUE TITLE
First email notification link wrong

### ISSUE THREAD

**Issue by fpamelard** [nextcloud/server#33754]
Dear NextCloud team,

We've got a NextCloud instance into a subdomain mysub.mydomain.com. I've checked the config.php and everything seems good.
However, the first email for a new member refers to a link with mysub..mydomain.com (double dots).

Is there a way to fix it?

Regards,
Fabien

**Comment by nickvergessen** [comment]
Email in question: https://github.com/nextcloud/server/blob/3b656446afcac16b53aeb5906cb0d2dd57a23d7e/apps/settings/lib/Mailer/NewUserMailHelper.php#L99-L162

**Comment by joshtrichards** [comment]
Hi @fpamelard - Can you provide your config (i.e. output of `./occ config:list system`) so we can try to reproduce this? 

Since your issue was created in a different repo initially it may have bypassed the normal bug report form. Some other bits of info might be useful too (you can see what's normally requested here: https://github.com/nextcloud/server/issues/new/choose), but your basic config may turn out to be sufficient.

**Comment by joshtrichards** [comment]
If willing, test PR #39607 to see if it fixes your situation.
