### ISSUE TITLE
Settings panel in sidebar, separation a bit too weak visually

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33802]
BUG: design: settings panel in sidebar, separation a bit too weak visually

![image](https://user-images.githubusercontent.com/3404133/187960106-d76e18b7-a10f-4c14-905f-5cfb94871279.png)

**Comment by jancborchardt** [comment]
So @juliushaertl and I looked at this, and we wanted to add some additional whitespace on top if the menu is open (it should not be there when closed as otherwise the distance to the entries above will be too much.

Unfortunately, the .open/.opened class is applied only to the settings content, not to the whole container, so we can not add extra padding based on that. It could be fixed by applying the .open/.opened class to the settings container which includes both the settings header/button and the settings content.
