### ISSUE TITLE
share properties panel doesn't hide/covers file properties

### ISSUE THREAD

**Issue by adsworth** [nextcloud/server#3383]
### Steps to reproduce
1. navigate to the "share with others" page in the files app.
2. click on a shared directory, so that the right hand properties pane is displayed
3. now navigate into the shared directory.
4. select a file. The list now resizes so that share, ... menu, size and modified are displayed.
5. in the ... menu, select info.

### Expected behaviour
When navigating away from the shared with others page the shares properties should be hidden. At the latest the shares properties should be hidden when something else uses the right side pane.

### Actual behaviour
I still see the share properties of the share from step 2. If I close the shares properties pane using the X in the top right of the pane the file properties are displayed.

So what seems to be happening is that the file properties are displayed but underneath the shares, properties.

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
/.x
**Nextcloud version:** (see Nextcloud admin page)
11.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
update
**Where did you install Nextcloud from:**
manual
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.0
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
</details>

### Client configuration
**Browser:**
Firefox 50.1.0
**Operating system:**
GNOME/Linux

**Comment by jancborchardt** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://nextcloud.com/install/) and then please use the [issue template](https://github.com/nextcloud/server/issues/new/choose). You can also contribute directly by providing a patch – see the [developer manual](https://docs.nextcloud.com/server/stable/developer_manual/). :slightly_smiling_face: 

Thank you! (And don’t worry, we can always reopen this issue.)
