### ISSUE TITLE
text on some buttons has primary color

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33851]
Not sure if it is meant to be this way

See 
![image](https://user-images.githubusercontent.com/42591237/188110805-7a5800b1-96fb-46db-b6f6-901e8b75cdf2.png)

Or 
![image](https://user-images.githubusercontent.com/42591237/188110995-b50ece90-e706-4055-b240-99dc9b2b7344.png)

**Comment by szaimen** [comment]
This is especially a problem when a light color was chosen: 
![image](https://user-images.githubusercontent.com/42591237/188127852-6bc36397-1657-4d08-a22e-717c4b24dbd0.png)
![image](https://user-images.githubusercontent.com/42591237/188127890-8740b602-c218-4e97-8911-f8dd2451438a.png)

**Comment by juliushaertl** [comment]
In case of the light value it is probably using --color-primary-* instead of --color-primary-element-* as the css variables

Depending on their use we may want to switch to tertiary styles:
https://nextcloud-vue-components.netlify.app/#/Components/NcButton
<img width="804" alt="Screenshot 2022-09-02 at 13 23 26" src="https://user-images.githubusercontent.com/3404133/188129143-0fbb6e6d-50f2-4217-913f-356b065660e9.png">

**Comment by szaimen** [comment]
This seems to be a problem with all secondary buttons which is the default button if not specified. cc @nextcloud/server-frontend do you have a workaround or idea how to solve that? cc @jancborchardt as well...

**Comment by jancborchardt** [comment]
In general, what needs to be fixed is as Julius said above, so move from --color-primary-* to --color-primary-element-*


For the Dashboard buttons, we need to make the weather and edit settings buttons look like the "Set status" button
- switch to color-main-text
- make the text not bold
- adjust the background to translucent

**Comment by szaimen** [comment]
Do I need to adjust this in the vue component or somewhere in server?

**Comment by jancborchardt** [comment]
@szaimen the feedback part on the dashboard buttons is specific to Dashboard, so server.
The part Julius mentioned I assume goes into nextcloud-vue. cc button expert @marcoambrosini

**Comment by szaimen** [comment]
I had a look and the wheather button is an unmodified secondary button. The set status button on the left is not.

So this likely needs fixing in the vue components.

cc @marcoambrosini

**Comment by marcoambrosini** [comment]
This is similar to the settings button in the navigation. Here's how we did it. Probably we should introduce this as a use-case in the library

<img width="342" alt="Screenshot 2022-09-12 at 08 45 18" src="https://user-images.githubusercontent.com/26852655/189589965-8b98e3ce-ca16-4509-94c1-6d9126a44a52.png">


<img width="309" alt="Screenshot 2022-09-12 at 08 46 14" src="https://user-images.githubusercontent.com/26852655/189590004-d735047f-3b99-4032-849e-23bdff092e5d.png">

Why not bold @jancborchardt ?

**Comment by jancborchardt** [comment]
@marcoambrosini because if it’s bold, it calls much too much attention. And e.g. in Files, Mail, Calendar or any other apps with an AppNavigation, none of the entries are bold, so it would look very off to make it bold.

So there are some exceptions to bolding buttons, of which 2 are the Dashboard buttons and Settings buttons. And for settings, we also don’t want the background, as mentioned before.

**Comment by szaimen** [comment]
So for me is this not acceptable from a accessbility perspective when choosing a very light primary color:
![image](https://user-images.githubusercontent.com/42591237/192893251-ee0fc4c8-50c0-4593-88ac-2e8c8c1a92da.png)
Do we need to fix this in the vue component?

**Comment by szaimen** [comment]
Same problem in dark mode when choosing a very dark primary color: 
![image](https://user-images.githubusercontent.com/42591237/192893882-8c1a9ed9-8a5e-4a59-b956-2572cda08b67.png)

**Comment by szaimen** [comment]
found a solution in #34333
