### ISSUE TITLE
pdfviewer is a bit cut-off on public view

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33871]
See 
![image](https://user-images.githubusercontent.com/42591237/188126648-a1f080bd-ada9-40a2-8041-5fba4d82346c.png)

**Comment by CarlSchwan** [comment]
@jancborchardt @nimishavijay We would need your input here on how to solve this issue as the pdfviewer part comes from a lib and can't be changed

**Comment by jancborchardt** [comment]
I would say that since the PDF viewer is a "Viewer" thing, sort of like the image viewer or Office or Text, it would be good if we can make an exception here, meaning:
- Not use the border-radius here
- Extend all the way to the left and right
- Extend all the way to the bottom too

Would that be possible? If it’s difficult, I’d say next best thing would be if we can just reduce the border-radius a bit (e.g. halve it) so it doesn’t look as weird with the icons.

**Comment by szaimen** [comment]
I'll see if we are able to do that in the pdfviewer app tomorrow.

**Comment by szaimen** [comment]
Found a fix in https://github.com/nextcloud/files_pdfviewer/pull/655
