### ISSUE TITLE
LDAP "Import Address info & Phone Numbers from Active Directory users" 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#33987]
Currently if adding address info & phone number under users AD the info it will not import  the info into Nextcloud 

AD Attributes to look for 

- streetAddress   

>  Will be the Street

- st                        

> Will be the State/Province

- l                          

> Will be the City

- postalCode         

> Will be the Zip/Postal code

- co                        

> Will be Country/region

Since has had multiple to location to input phone number here are the most used
- telephoneNumber
- mobile

**Comment by andyxheli** [comment]
Also phone numbers https://github.com/nextcloud/server/issues/33886

**Comment by andyxheli** [comment]
Since has had multiple to location to input phone number here are the most used

attributes: telephoneNumber
attributes: mobile

**Comment by brianjmurrell** [comment]
How does this relate, if at all, to the _User profile attributes_ in _LDAP/AD integration_ > _Advanced_?  Can I set the _Phone Field_ to `telephoneNumber` to have the phone number taken from LDAP and populated into the _Personal Info_ page?

**Comment by brianjmurrell** [comment]
@AndyXheli There seems to be a big circular reference of issues with this topic all closed for one reason or another yet none with a definitive answer about how this is is expected to work.

Can you please provide a reference for the canonical issue about importing address and phone number information from LDAP into NextCloud because even with the most recent 29.x.x release, this is not happening for me.  Thanks!
