### ISSUE TITLE
[Bug]: Avatar New style looks weird

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#34006]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/59488153/189403002-e2613534-c5db-46d8-a9bb-0d7ccd3cb212.png)  ![image](https://user-images.githubusercontent.com/59488153/189403459-765585f9-2cf9-483a-8e81-6300b750bc07.png)

### Steps to reproduce

After this was implemented https://github.com/nextcloud/server/pull/33752
 

### Expected behavior

Should look more clear. Th users back end is running LDAP @CarlSchwan what do you think? 

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Na
```

**Comment by andyxheli** [comment]
Not fixed in NC 25 Beta 7 


Same results 

![image](https://user-images.githubusercontent.com/59488153/191092393-516f36b2-b090-4a91-8848-a6f039c7cee0.png)![image](https://user-images.githubusercontent.com/59488153/191092458-fc1628e9-3433-402a-a32d-ba4461188af2.png)

**Comment by CarlSchwan** [comment]
Oh now I see the issue, it wasn't about dark theme but the weird border

**Comment by andyxheli** [comment]
Let me know if you have a manual patch you'd like to me test out

**Comment by szaimen** [comment]
@CarlSchwan could this happen if imagick is not enabled on an instance?

**Comment by andyxheli** [comment]
Just to confirm I do have imagick installed

**Comment by andyxheli** [comment]
Hi @CarlSchwan sorry to bug you I know your super busy any news on this? Still an issue on NC 25 RC3

**Comment by skjnldsv** [comment]
@andyxheli does your imagick setup have svg enabled?

**Comment by andyxheli** [comment]
Hi @skjnldsv  yes I have php-imagick & imagemagick installed. In the server overview I got a green check no issues or recommendations

**Comment by Ho551** [comment]
Same problem on NC 25.0.1

**Comment by skjnldsv** [comment]
@Ho551 have you upgrade through beta or RC before reaching stable 25 ?

**Comment by Ho551** [comment]
Thanks for the hint!
I've updated through beta channel. I wanted to test NC in my test system first.
I tried to generate the avatars again. Now the avatar in top bar looks good (for one user), but in setttings and talk it looks still weird:

![image](https://user-images.githubusercontent.com/15242832/202653658-48b9c561-220e-4a6c-8735-f0d14c5ac059.png)
![image](https://user-images.githubusercontent.com/15242832/202653758-7b412c89-e0c9-4ecb-9b1d-b90483b3b4f1.png)


![image](https://user-images.githubusercontent.com/15242832/202652802-de9f253f-b139-4115-b19c-86464a3df4a7.png)
![image](https://user-images.githubusercontent.com/15242832/202653011-b5a6932b-4222-4ab1-b69f-b92de1115de0.png)

**Comment by skjnldsv** [comment]
I'm guessing this is a browser cache issue. Please clear cache or try in a private window @Ho551  ?

**Comment by Ho551** [comment]
That's what I suspected too, but the problem still persists. 
It occurs on Chrome, Safari and Firefox browsers.
Is there any way I can help further @skjnldsv?

**Comment by skjnldsv** [comment]
Thanks, it means the problem persist indeed :)
I'll think about how to tackle that

**Comment by MoritzDPTV** [comment]
Hey there,

I'm having some similar issues. It seems to be related with the **User Status app**. After disabling it, the not-so-beautiful avatars appeared. Re-enabling the app only changed my personal avatar in the top right corner (which returns to be not-so-beautiful when (re)loading the page, but is replaced after the page is fully loaded with the better avatar.)

![Screenshot from 2022-11-24 12-17-31](https://user-images.githubusercontent.com/35461483/203774482-0e2e68a4-3908-484d-aa58-679d5f0b10af.png)
![Screenshot from 2022-11-24 12-17-52](https://user-images.githubusercontent.com/35461483/203774487-d7c7f085-d9c5-414d-8f0a-51f0875de743.png)
![Screenshot from 2022-11-24 12-18-26](https://user-images.githubusercontent.com/35461483/203774492-1fa25a0f-132e-4773-8c45-528f0f26af6f.png)

Nextcloud Version: 25.0.1
Firefox Version: 106.0.2 (64-bit)
Client Ubuntu Version: 22.04.1 LTS

**Comment by Ho551** [comment]
@skjnldsv Looking at the generated images, this seems to be the problem.
In the 64x64px image, the unsightly edge is already visible
![avatar 64](https://user-images.githubusercontent.com/15242832/203795578-828adafe-811b-4db9-aafe-3936ab69b622.png)

I attach the entire generated avatars in a zip archive
[avatar.zip](https://github.com/nextcloud/server/files/10084919/avatar.zip)

**Comment by skjnldsv** [comment]
Thank you @Ho551 , it really helps! :pray: 
Ok, so it is definitely something with our svg or the php dependency

**Comment by skjnldsv** [comment]
@come-nc ring a bell? Maybe a difference in parameters between 8.0 and 8.1?

**Comment by andyxheli** [comment]
I'm running PHP 8.1 on NC25.0.1 and still have issue

**Comment by come-nc** [comment]
> @come-nc ring a bell? Maybe a difference in parameters between 8.0 and 8.1?

Hum, kind of. I remember having a problem with gd or imagick changing result is *some* PHP version.

**Comment by come-nc** [comment]
I have this test script left over on my disk, which indicates I did have trouble with this:
```
<?php

$font = '/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf';

var_dump(imagettfbbox(12, 0, $font, 'E'));
```

But I’m failing to find any more information on this.
All I can see is I have commands in my history to check which version of gd/freetype is linked to my PHP build. So I can only advise to test the result of `imagettfbbox` and compare it accross PHP versions and setups.

**Comment by come-nc** [comment]
Here is what I have locally:
```
> php ~/dev/test-freetype.php
array(8) {
  [0]=>
  int(1)
  [1]=>
  int(0)
  [2]=>
  int(8)
  [3]=>
  int(0)
  [4]=>
  int(8)
  [5]=>
  int(-11)
  [6]=>
  int(1)
  [7]=>
  int(-11)
}
> php --info|grep -i gd
/etc/php/8.1/cli/conf.d/20-gd.ini,
gd
GD Support => enabled
GD headers Version => 2.3.0
GD library Version => 2.3.0
gd.jpeg_ignore_warning => 1 => 1
> php --info|grep -i freetype
FreeType Support => enabled
FreeType Linkage => with freetype
```

And with my PHP 8.2 built from source for tests:
```
> ~/dev/php-src-git/sapi/cli/php ~/dev/test-freetype.php
array(8) {
  [0]=>
  int(1)
  [1]=>
  int(0)
  [2]=>
  int(8)
  [3]=>
  int(0)
  [4]=>
  int(8)
  [5]=>
  int(-12)
  [6]=>
  int(1)
  [7]=>
  int(-12)
}
> ~/dev/php-src-git/sapi/cli/php --info|grep -i gd
Configure Command =>  './configure'  '--with-ldap' '--with-ldap-sasl' '--with-zip' '--with-curl' '--with-openssl' '--with-zlib' '--enable-mbstring' '--enable-pcntl' '--enable-intl' '--with-password-argon2' '--with-freetype' '--with-jpeg' '--enable-gd' '--with-imagick' '--enable-exif'
gd
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
gd.jpeg_ignore_warning => On => On
> ~/dev/php-src-git/sapi/cli/php --info|grep -i freetype
Configure Command =>  './configure'  '--with-ldap' '--with-ldap-sasl' '--with-zip' '--with-curl' '--with-openssl' '--with-zlib' '--enable-mbstring' '--enable-pcntl' '--enable-intl' '--with-password-argon2' '--with-freetype' '--with-jpeg' '--enable-gd' '--with-imagick' '--enable-exif'
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.11.1
```

So there is a 1 pixel difference between my 2 local versions already.

**Comment by szaimen** [comment]
Interesting! So is the issue reproducible only on php 8.0 and below?

**Comment by come-nc** [comment]
No I think it depends upon which gd and/or freetype version is used. We need to test on as many setups as possible to see common patterns.

**Comment by andyxheli** [comment]
Still an issue on NC 25.0.3

**Comment by andyxheli** [comment]
HI all just wanted to see if there's any updates on this ?

**Comment by schiessle** [comment]
In case some of the devs need a instance to reproduce it. The problem also exists on the LTD's on try.nextcloud.com

**Comment by AndyXheli** [comment]
Still an issue on NC 26.0.0

**Comment by AndyXheli** [comment]
Still an issue on NC 26.0.0

**Comment by AndyXheli** [comment]
Still an issue NC 27

**Comment by AndyXheli** [comment]
Still an issue on NC 27.0.1 tried below and cleared cache still an issue 

# cd into your appdata avatar directory
cd data/appdata_xxxxx/avatar

# look for generated avatar and delete their containing directory
find -name 'generated' -type f -execdir pwd \; | xargs -d '\n' rm -rfv

# update file cache to make Nextcloud generate them again on demand
occ files:scan-app-data avatar

**Comment by danxuliu** [comment]
The problem is in ImageMagick itself; before ImageMagick 6.9.10-36 (specifically, https://github.com/ImageMagick/ImageMagick6/commit/3b6ba12f465dc1b9bb0afddcd5060a19e28e7d5b), if the internal renderer is used (that is, if ImageMagick is built with `--without-rsvg` and Inkscape is not in _$PATH_), the SVG used for avatars in Nextcloud is not properly rendered.

To check this, first save the SVG of a Nextcloud avatar in a _test.svg_ file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="64" height="64" version="1.1" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
	<rect width="100%" height="100%" fill="#e8f1f8"></rect>
	<text x="50%" y="350" style="font-weight:normal;font-size:280px;font-family:'Noto Sans';text-anchor:middle;fill:#1e78c1">U</text>
</svg>
```

Then, build ImageMagick 6.9.10-35 and 6.9.10-36 and check the generated PNG file (note that you will need to replace `{PATH-TO-THE-DIRECTORY-OF-THE-TEST-SVG-FILE}` with the proper value):
```
docker run --detach --interactive --tty --volume {PATH-TO-THE-DIRECTORY-OF-THE-TEST-SVG-FILE}:/tmp/imagemagick-test --name imagemagick-test ubuntu:20.04 bash
docker exec imagemagick-test bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes build-essential git autoconf pkg-config libxml2-dev libfreetype6-dev libfontconfig1-dev gsfonts"
docker exec imagemagick-test bash -c "useradd --create-home imagemagick"
docker exec --user imagemagick --workdir /home/imagemagick imagemagick-test bash -c "git clone https://github.com/ImageMagick/ImageMagick6"
docker exec --user imagemagick --workdir /home/imagemagick/ImageMagick6 imagemagick-test bash -c "git checkout 6.9.10-35"
docker exec --user imagemagick --workdir /home/imagemagick/ImageMagick6 imagemagick-test bash -c "mkdir build && cd build/ && ../configure --without-rsvg && make && MAGICK_CONFIGURE_PATH=/home/imagemagick/ImageMagick6/config:/home/imagemagick/ImageMagick6/build/config ./utilities/convert /tmp/imagemagick-test/test.svg /tmp/imagemagick-test/test-6.9.10-35.png && cd .."
docker exec --user imagemagick --workdir /home/imagemagick/ImageMagick6 imagemagick-test bash -c "git checkout . && git checkout 6.9.10-36"
docker exec --user imagemagick --workdir /home/imagemagick/ImageMagick6 imagemagick-test bash -c "cd build/ && ../configure --without-rsvg && make && MAGICK_CONFIGURE_PATH=/home/imagemagick/ImageMagick6/config:/home/imagemagick/ImageMagick6/build/config ./utilities/convert /tmp/imagemagick-test/test.svg /tmp/imagemagick-test/test-6.9.10-36.png && cd .."
```

To solve the issue you need to update ImageMagick to, at least, ImageMagick 6.9.10-36. If you are using Ubuntu 20.04 you can upgrade to Ubuntu 22.04, [which uses ImageMagick 6.9.11-60](https://packages.ubuntu.com/jammy/libmagickcore-6.q16-6) and therefore no longer has this issue. 

ImageMagick renders SVG files using either its internal render, _rsvg-convert_ or Inkscape, so if you are in an old ImageMagick version and you can not update it you might be able to work around the issue just installing Inkscape.

You could also rebuild ImageMagick with RSVG support, so it renders the SVG files through _rsvg-convert_ rather than its internal renderer. However it seems that _rsvg-convert_ [has its own issues and it is not currently used when generating the avatars](https://github.com/nextcloud/server/pull/37378/files).

Alternatively, if your distributon provides SVG support for ImageMagick in an additional package (for example, [`libmagickcore-6.q16-6-extra` in Ubuntu 20.04](https://packages.ubuntu.com/focal/libmagickcore-6.q16-6-extra)), you can also remove that package to remove support for SVG from ImageMagick; GD will be used instead of ImageMagick to generate the avatars and they will look as expected. The drawback is, however, that you may lose some other feature that depend on SVG support in ImageMagick, like [theming icons](https://github.com/nextcloud/server/blob/f21cbfff64bad26b7d80b8b8a1f918611dfa82c3/apps/theming/lib/ImageManager.php#L358-L377).

Finally, note that the rendering was wrong too with the old avatar style, but since Nextcloud 16 the problem was not visible because the font could not be found (the path to the font was not updated [when _lib/private/Avatar.php_ was moved to _lib/private/Avatar/Avatar.php_](https://github.com/nextcloud/server/commit/bf1253cb49a4931244a6bbde4dfa44bf084f4377#diff-24c58ce6079fdc9b2889e35ccc379109fcd986108bf5e219f50485c676136fbfL323)) and thus it always ended being rendered with GD; with the new avatar style [the path got fixed](https://github.com/nextcloud/server/commit/f98ae2b5b0567f28a875106724c0475d6395f3c5#diff-24c58ce6079fdc9b2889e35ccc379109fcd986108bf5e219f50485c676136fbfL131-R133) and thus the problem appeared.
