### ISSUE TITLE
[Bug]: NC25 not working with disabled Theming app

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#34338]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when the theming app is disabled, NC is loaded without css.
Error "Could not find initial state background of theming" in browser console

### Steps to reproduce

1. Apps -> disable Theming app
2. Refresh Page

### Expected behavior

Avoid the feature to disable the Theming app, when its that important

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Theming
```

**Comment by genma** [comment]
I've the same issuses a written a blog post in French with some screenshot https://blog.genma.fr/?Nextcloud-25-l-application-theming-casse-l-affichage-des-CSS

**Comment by AndyScherzinger** [comment]
Looping in @PVince81 and @juliushaertl

**Comment by PVince81** [comment]
and @Pytal

**Comment by Pytal** [comment]
Some dashboard js depends on theming to adjust the header

Tracking in https://github.com/nextcloud/server/issues/33969

**Comment by nickvergessen** [comment]
Since the theming app now also hosts the accessibility settings, should we force enable it?
Feels weird that an admin can decide to punish people for their accessibility lacks by disabling an app they just don't need themselves?

**Comment by szaimen** [comment]
WIP here: https://github.com/nextcloud/server/pull/34609 however I didn't test yet what happens if you disable the app and upgrade to this branch.

**Comment by kyrofa** [comment]
Hey @szaimen, the theming app is disabled by default in the snap because it adds warnings about not having imagick. Did you ever test updates when this app is disabled? Any bad side effects? Has anyone considered splitting critical functionality out of a non-critical theming app so folks who don't want imagick installed don't constantly see a warning?

**Comment by nickvergessen** [comment]
it's not a warning as it's not yellow and not an error as it's not red. It's an info.
The problem is when there are no errors/warnings the headlines still say "Setup warnings", so that's why you might confuse it for that. 

Also note, since Nextcloud 25 the Theming app is one of the apps that must always be enabled:
https://github.com/nextcloud/server/blob/stable25/core/shipped.json#L100
https://github.com/nextcloud/server/blob/stable26/core/shipped.json#L100
https://github.com/nextcloud/server/blob/master/core/shipped.json#L100

The reason is it was merged with the accessibility features as they shared to many settings and technics and need to work hand-in-hand, but Accessibility is **not optional**, it's one of the core principals of the Nextcloud project, see https://nextcloud.com/about/ (middle of the page, seems to miss anchors at the moment).
So please remove any code that would try to disable/remove/prevent theming.

**Comment by kyrofa** [comment]
>  So please remove any code that would try to disable/remove/prevent theming.

That's just signing us up for triaging more invalid bug reports. Can we please consider moving accessibility to another trimmed down app specifically for it?

**Comment by szaimen** [comment]
I think the best way forward would be this: https://github.com/nextcloud/server/issues/36607

**Comment by tonyguepin** [comment]
Due to the theming app being forcibly enabled, as of 25,
we're running into problems when using our own customized theme which required the theming app to be disabled.
Our customized theme redefines some css-vars and styles , these are now being overwritten by the theming app.

Do I understand correctly that the reason for the forcibly enabled theming app is the need for  "accessibility features" ?

**Comment by gioman** [comment]
> Due to the theming app being forcibly enabled, as of 25, we're running into problems when using our own customized theme which required the theming app to be disabled. Our customized theme redefines some css-vars and styles , these are now being overwritten by the theming app.
> 
> Do I understand correctly that the reason for the forcibly enabled theming app is the need for "accessibility features" ?

@tonyguepin similar situation here. I was trying to use just one instance of NC 27 for multiple domain names, and depending on the domain show a different theme. I spent quite a lot in reading posts and docs, and it seemed feasible as some of the configs worked, while others not

i.e.
https://help.nextcloud.com/t/howto-individual-themes-per-domain/27585

the part that isn't working is the override/injection of some CSS property, as described in this legacy page of the docs

https://docs.nextcloud.com/server/12/developer_manual/core/theming.html

and finally/sadly read this post

https://help.nextcloud.com/t/howto-individual-themes-per-domain/27585/24

So I kindly ask: now that is not possible to disable theming, how to override/inject CSS properties into custom themes ("themes" folder, using the "example" theme/folder as template for others) now that functions in _defaults.php_ like

```
public function getScssVariables() {
    return [
        'color-primary' => '#745bca'
    ];
}
```

are ignored or simply overridden by the theming functionality?

Thanks in advance
