### ISSUE TITLE
QA issues due to excessive focus on new features

### ISSUE THREAD

**Issue by fschrempf** [nextcloud/server#34351]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

The NC development and releases have a strong focus on adding new features while leaving behind important tasks like:

* code maintenance
* maintenance of a healthy and productive community
* bug fixing
* issue triaging
* increasing test coverage
* restructuring/reworking/rewriting code

My impression is, that this leads to issues with (code) quality, stability, performance, user experience, etc. One example is the groufolders app that is considered by many to provide core functionality, but didn't act up to the expectations in the past (see https://github.com/nextcloud/groupfolders/issues/1215 for details).

This impression seems to be shared by others. Some examples of public voices:

<blockquote>
Nextcloud, on the other hand, is hyped everywhere. It has grown very, very quickly and the number of add-ons is now almost unmanageable. In my eyes, this is also the problem with Nextcloud. The quality and cleanup of bugs often takes a back seat.
</blockquote>

[^1] Norbert Rüthers, June 2022 (Deepl translation)

<blockquote>
At what point does an open source project count as a failure if the number of bugs keeps increasing? From my point of view Nextcloud needs some bugfix releases, a kind of feature stop, a spring cleaning through all areas covered by Nextcloud.
</blockquote>

[^2] Schroeffu, July 2021 (Deepl translation)

<blockquote>
Nothing against Nextcloud. It's a great suite if you want to run a home cloud center with little resources and knowledge. But this advantage is also a disadvantage in my eyes. Nextcloud has grown functionally incredibly fast, and quality assurance and bug fixing have often taken a back seat here. I'm not even talking about the rapid development cycle and the often problematic updates. Of all things, Nextcloud now often fails in its original core competence of "cloud storage". Almost no day without conflict files or hanging synchronization. Unstable Internet connections or even offline work are particularly deadly. Welcome to Germany. Nextcloud has the potential to become a system that can do an incredible amount and nothing right. A pity, actually.
</blockquote>

[^3] Gerrit Heim, May 2022 (Deepl translation)

<blockquote>
I don't want to badmouth Nextcloud, but I see some problems with the current development. Instead of just maintaining and fixing the many bugs for a while, I see the developers in constant pressure to bring new developments to consolidate and expand the position in the still competitive cloud market. The normal user then falls by the wayside, who does not benefit from the many enterprise functions, but suffers from all the errors in the basis of the software.
</blockquote>

[^4] Ferdinand Thommes, June 2022 (Deepl translation)

Reading about the strategy of NC founder @karlitschek, I don't get the impression that the focus will be shifted towards aiming at a more sustainable and stable product. It rather sounds like the previous course of adding new features at all costs will be continued.

<blockquote>
Besides the privacy and security aspects of Nextcloud, it’s also super important that Nextcloud empowers its users. If Nextcloud would fall behind the big tech solutions in functionality and usability, then people would stop using it. Therefore, we have ambitious plans to keep pushing Nextcloud forward to be the leader in the marketplace.
[...]

We are experimenting with more innovative ways to enable our users to be more productive while lowering their mental load and protecting their privacy. Ideas transform new and powerful automation features, innovative intelligence and machine learning functionalities. Of course, all executed locally to keep the users in control of their digital life. Stay tuned or, even better, get involved.
</blockquote>

[^5] Frank Karlitschek, June 2022

Being able to compete with other products on the market in regards of features doesn't help in the long run if basic functionality lacks stability and causes users to turn away, which is actually happening right now.

[^1]: https://gnulinux.ch/seafile-das-verkannte-syncing-tool
[^2]: https://schroeffu.ch/2021/07/warum-ich-von-nextcloud-server-zu-seafile-gewechselt-bin/
[^3]: https://curius.de/2022/05/seafile-als-open-source-cloudspeicher-unuebertroffen/
[^4]: https://linuxnews.de/2022/06/seafile-die-bessere-next-cloud/
[^5]: https://karlitschek.de/2019/08/nextcloud-strategy/

**Describe the solution you'd like**

Aiming for a full-featured groupware alternative is all right, but please maintain a certain level of quality and stability for the core features that people can live with.

Providing privacy-friendly alternatives is an important task but these alternatives need to be functional and until all groupware features can compete with their proprietary counterparts, people want to use only a subset of (core) features, which for NC is file sharing.

I suggest for Nextcloud GmbH to:

* announce a changed strategy with more focus on stable core features
* announce a feature stop and one or more releases that only target fixes and cleanups, no new features
* define which features/apps are core features and treat them accordingly (maybe even move them to the server core)
* create and apply a strategy for establishing and sustaining a healthy community

Feel free to let me know what you think!
Thanks in advance for any response!

**Comment by solracsf** [comment]
Problem is, Nextcloud is indeed open-source, but **not community driven**.
One example: on the last 100 issues, maybe 2 or 3 had core-team input.
They're not even triaged, let's not talk about fixing them...

Bugs are fixed, if:
- they break Nextcloud almost completely,
- they're submitted by Nextcloud customers,
- they're found by core-team in their CI.

Community only exists to _"submit a PR, or wait for it to, maybe, be fixed"_. 😞 
Without a 180° strategy change, what Nextcloud need is **a Community driven fork**.

**Comment by jospoortvliet** [comment]
> Without a 180° strategy change, what Nextcloud need is a Community driven fork.

I'm very curious how you expect that to work out. What would happen if you forked Nextcloud? 'cuz you can, you know. It's very easy.

**Comment by solracsf** [comment]
I didn't say I would do it. I was speaking about a community. But having a good Nextcloud Server (serving files) instead of a "big commercial Hub" would be a good thing. This is what community was expecting when Owncloud was forked, not a Microsoft/Google challenger with features, features and more features.

Because today, Nextcloud is serving "other interests" than having a stable Server (I repeat, Server).

**Comment by fschrempf** [comment]
> I'm very curious how you expect that to work out. What would happen if you forked Nextcloud? 'cuz you can, you know. It's very easy.

What are you aiming at? I think you know what @solracsf meant. Of course forking is easy, but creating a community to maintain a sustainable fork is not.

**Comment by sunjam** [comment]
@fschrempf it is unfortunate that the way this is phrased drives it to fail, because it lacks the tact of your group folders issue from 2021.

> Please note, that I don't mean to blame anyone. I really appreciate the huge amount of work all of you put into this.
> Still I would like to ask if anyone sees some way to improve things?

I think this helped get so much developer feedback on the groupfolders issue in 2021, but you seem to have forgotten that you are not owed anything... absolutely nothing.  No one on the team owes us free users anything at all, and I doubt adding a lot of quotes makes your post any more appealing.

> What are you aiming at?

I would ask you the same rhetorical question, because this will not doubt rapidly continue to devolve into a very unproductive, locked thread.  Since you prefer being very blunt, let's be blunt as random users who give nothing to the server repo and ask for everything in return.

You have no desire to personally assist in fixing any of these issues, yes?  In that case there is nothing more to demand.  Report bugs, yes.  Ask for blunt updates on status, maybe if they have time... although I do not expect even this response.

I do agree with your frustrations on technical landmines in need of address, but this does not feel productive in what you wish to address.

> I suggest for Nextcloud GmbH to:
>     * announce a changed strategy with more focus on stable core features
>     * announce a feature stop and one or more releases that only target fixes and cleanups, no new features
>     * define which features/apps are core features and treat them accordingly (maybe even move them to the server core)
> Feel free to let me know what you think! Thanks in advance for any response!

But they don't have to respond, nor do any of these things.  So don't pressure them, because I want to quote you and your excellent, older wording in my own way:

I don't blame anyone.  I really appreciate the huge amount of work all of you put into this, I really do!  If you can think of new ways to connect with the community we'd love to make more meaningful contributions!  But, we also understand that your paid time is dedicated to your support contracts, because those users are the ones paying for your time and development.  The community in this instance are those users willing to create Pull Requests, or code their own Nextcloud apps in order to add the functionality they want... if that sounds difficult it is because I like the skills needed to actually help.  Perhaps someone else in the community is willing to offer solutions..?

No one from the team has lied to us on where their development time goes.  If this is not the self hosted tool for you... well, maybe that is the answer.

[The dogs are barking, but the caravan moves on](https://en.wiktionary.org/wiki/the_dogs_bark,_but_the_caravan_goes_on).

**Comment by solracsf** [comment]
@sunjam I agree with almost everything you wrote, specially this:
> but you seem to have forgotten that you are not owed anything... absolutely nothing. No one on the team owes us free users anything at all

But:
> Report bugs, yes. 

My only question is (and this is what I've stated earlier, maybe it was not clear, so let be me more clear); what's the point to have Issues tab on Github (bug reports) if they're _mostly_ ignored? Why not open Github to contributions only (PRs) and move all "community discussions" to https://help.nextcloud.com?

A lot of Open Source projects work like this (open contributions only); at least, users don't get this feeling of wasting their time writing bug reports that no-one will even read (triage) or taken care of. My whole point is this one, not Nextcloud's vision.

Because, as you've stated:
> If this is not the self hosted tool for you... well, maybe that is the answer.

**Comment by sunjam** [comment]
> Why not open Github to contributions only (PRs) and move all "community discussions" to https://help.nextcloud.com?

I think you accurately describe the situation, because PR's are what is asked for.  Still, I greatly appreciate that we are allowed to post thoughts without making code contributions.  My opinion, I super appreciate being able to write up suggestions as-is, which I'm sure can be tiresome, if not unhelpful to the developers themselves as often as not.

> users don't get this feeling of wasting their time writing bug reports that no-one will even read (triage) or taken care of

I think the best we can do, aside from coding, is to write quality bug reports while putting our best foot forward in showing total respect to all of the great work we already benefit from... no way is any number of bug reports more work than actually maintaining Nextcloud.  If possible, I'd love to be able to continue having discussions, although I think help.nextcloud.com is a much better place to talk freely without demanding developer attention with each reply.  Perhaps we could continue a similar discussion there more focused on practical solutions and respect.

Later!

**Comment by solracsf** [comment]
> I think help.nextcloud.com is a much better place to talk freely without demanding developer attention

This is exactly where problem is; here, there is **no developer attention**.

As an example _(there are many others)_ of good maintained Git issues, where issues are triaged, assigned, answered, PRs on the way, etc., see: https://github.com/netdata/netdata/issues

As a bug reporter, you're pleased to see that, for developers, aside paid customers _(because yeah, FOSS may be open, may be free to use, but certainly it's not free to maintain)_ they actually **care** about the software and it's quality.

This is what this is all about, IMHO.

**Comment by fschrempf** [comment]
> I think this helped get so much developer feedback on the groupfolders issue in 2021, but you seem to have forgotten that you are not owed anything... absolutely nothing. No one on the team owes us free users anything at all, and I doubt adding a lot of quotes makes your post any more appealing.

I think you misunderstand me. I do not have forgotten that. This is not about claiming any responsibility from anyone to fix technical issues. I still adhere to the same tone that I used in the groupfolders issue you quoted, even if I didn't express it so clearly here.

The quotes I added to the post are simply there to support my own opinion and make clear that this is not an issue that only I'm experiencing, but a fundamental issue that affects many and does harm to NC. They were also added to raise awareness of the public response for those that are not yet aware of it.

> I would ask you the same rhetorical question, because this will no doubt rapidly continue to devolve into a very unproductive, locked thread. Since you prefer being very blunt, let's be blunt as random users who give nothing to the server repo and ask for everything in return.

Yes I prefer being blunt as this is kind of a last resort and it seems like other approaches have failed. And I'm very far from those users who give nothing and ask everything. I'm totally aware of my position and I respect every decision of the core developers or management. I simply want to challenge them to think about what they are doing. If they don't care it's sad but I will accept it and move on.

You should treat this issue not as a complaint. This is ought to be constructive feedback especially targeted at people like @karlitschek, @jospoortvliet and @jancborchardt who (as far as I know) are decision makers at NC and would have the possibility to adjust the course of NC development on a basic level.

**Comment by fschrempf** [comment]
> Problem is, Nextcloud is indeed open-source, but **not community driven**.

Indeed, without proper integration and maintenance of a healthy community a project like NC won't work. It's not only about core developers responding to issues (the capacity is very limited here as we have seen). It's also about integrating people from the community in the development process and assigning responsibilities. I [picked up a point](https://github.com/nextcloud/groupfolders/issues/1215#issuecomment-1265244851) from @ChristophWurst in the other thread about this topic.

I've added the community aspect to the first post above as I consider this equally crucial as the other aspects mentioned.

**Comment by DaphneMuller** [comment]
Dear all,
My name is Daphne, I am manager alliances, ecosystem, and support.

First of all I would like to share with you I have discussed your concerns internally and with several community contributors. I can see you put a lot of time in writing this we understand your frustrations. 

I am going to close this thread and I would like you to understand why. This is a very polarising atmosphere in every reply. 

Tagging Frank, Jos, or other top managers is like calling Steve Jobs (R.I.P.) because your Macbook is not functional. 

Our goal is to create a lovely community with which I mean respectful and helpful and we would not like to accept these intense ways of phrasing and communicating.  

Some of the concerns you raised, like the process around bug reports, are well known and not new. We have asked for qualitative and constructive feedback in our community survey last year and we have read every reply and analysed the results. The issues that were often raised are reflected upon internally and where realistic, acted upon. 

You have to realise what kind of emotional impact your thread has had on people who have been working day and night to create a mind-blowing release. I do not accept putting our lovely team of contributors and employees under this emotional pressure in our community. 

@sunjam already gave plenty of suggestions how to better contribute in the future and I would really love to thank him for supporting our community.

**Comment by fschrempf** [comment]
@DaphneMuller This will be my last post in this thread as I respect your decision to lock it. Still I would like to reply to your statement and clarify a few things that might have been misinterpreted. I hope you won't mind.

> First of all I would like to share with you I have discussed your concerns internally and with several community contributors. I can see you put a lot of time in writing this we understand your frustrations.

Thanks for the effort and the statement. I really appreciate it. My main motivation is not frustration but rather concern about the future of the NC project. In general I really like it and respect and appreciate all the work that is being done.

> Tagging Frank, Jos, or other top managers is like calling Steve Jobs (R.I.P.) because your Macbook is not functional.

I get your point, but the analogy doesn't really fit in my opinion. It would, if this is a bug report, but it's more intended to be an open letter.

> Our goal is to create a lovely community with which I mean respectful and helpful and we would not like to accept these intense ways of phrasing and communicating.

Thanks for mentioning this and for pursuing this goal.

> You have to realise what kind of emotional impact your thread has had on people who have been working day and night to create a mind-blowing release. I do not accept putting our lovely team of contributors and employees under this emotional pressure in our community.

If my way of communication was harmful to someone I want to apologize. This was not my intention and I still adhere to what I wrote in https://github.com/nextcloud/groupfolders/issues/1215#issue-778211414: *Please note, that I don't mean to blame anyone. I really appreciate the huge amount of work all of you put into this.*

> Some of the concerns you raised, like the process around bug reports, are well known and not new. We have asked for qualitative and constructive feedback in our community survey last year and we have read every reply and analysed the results. The issues that were often raised are reflected upon internally and where realistic, acted upon.

It seems like I missed that there is something such as the community survey. I just had a look at the 2021 results and it's good to hear that you are actively gathering feedback and try to take it into account.

> @sunjam already gave plenty of suggestions how to better contribute in the future and I would really love to thank him for supporting our community.

Again, the focus of my arguments is not about better contributions. It is about changing the overall strategy of the project. I know perfectly well what efforts are needed to get all those small things done and that there are plenty of tiresome tasks. As I said before, I'm not just a thankless, ranting user who fails to understand how open-source projects are working. In 2021 I spent plenty of hours of my sparse free time to help triaging issues in the groupfolders app because I know that many helping hands are needed to get somewhere.

**Comment by DaphneMuller** [comment]
@fschrempf thank you for your constructive reply ❤️

**Comment by jospoortvliet** [comment]
@fschrempf  Thanks for the input, and I appreciate you care. In that spirit, let me reply with my personal thoughts.

The balance between features vs bug fixes is not an easy one to find. You will find features people say Nextcloud needs to be 'basically useful' while others say Nextcloud is unusable because of a bug they found. But most bugs bother somebody some of the time - not everybody all the time. Those get fixed quickly.

As a company AND community, we have to deliver the features users want and find interesting to get MORE users, and thus more resources to further improve the software. And that with a stability that is not perfect but works for the vast majority of users. Market share matters, also for an open source project. If we fail to do that, we stagnate or shrink and, as the rest of the world (Google, Microsoft etc) moves on and build the features users want, we become irrelevant. You can look around at other projects to see what happens if you "focus on bug fixing" and lose the feature race to Big Tech.

I realize we probably sometimes get the balance wrong and users have different needs. Some would probably prefer more bug fixing and polishing, others want more features. But that's how a middle ground works.

My point is - we think about it and we always try to improve. But I think a 180 degree turn would be bad for Nextcloud.

**Comment by DaphneMuller** [comment]
I'm deleting your comment Jos, because this discussion is closed for reasons outlined above.
