### ISSUE TITLE
Remove folder creation option in the 'select file' dialog box

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/server#34640]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
There is no need to create a folder when you just have to pick a file

1. Attach file
2. select shared file
3. pop up 'file selection box' comes up
4. There is a + after the folder path which can be used to create a folder

**Describe the solution you'd like**
Remove the folder creation option

![image](https://user-images.githubusercontent.com/16174035/196056226-440d4f28-d5df-43c5-82cc-20bf53af625b.png)

**Comment by szaimen** [comment]
What about https://github.com/nextcloud/server/blob/f4efc76d21940cfd1a61f625684c5b06d4fee212/core/src/OC/dialogs.js#L32?

**Comment by szaimen** [comment]
So maybe changing https://github.com/nextcloud/deck/blob/630fa5b07e19ead8658e9089cd9445348075898c/src/components/card/AttachmentList.vue#L122 to `.allowDirectoryChooser(false)` makes it work?

**Comment by marcelklehr** [comment]
It should still be possible to attach Folders, though, no?

**Comment by szaimen** [comment]
Not sure. It is called `File to share`...

**Comment by marcelklehr** [comment]
@juliushaertl @jancborchardt Your call needed then :)

**Comment by szaimen** [comment]
But then being able to create a new folder in the picker also makes sense, IMO?

However I think you should change the tile of the picker in that case anyways!

**Comment by DJE98** [comment]
Thank you for your assessments about the bug fix. In the version of the current master branch, you can't attach folders, neither from your local file system nor from Nextcloud files. So I think the file name is right and the `allowDirectories()` should be removed. Apart from that issue is the general discussion about attachment of folders as useful feature. In my understanding of the [current API](https://deck.readthedocs.io/en/latest/API/#cards) is this feature not integrated at the moment. Can you agree with my point of view? Please thumbs up or down.

**Comment by szaimen** [comment]
> Thank you for your assessments about the bug fix. In the version of the current master branch, you can't attach folders, neither from your local file system nor from Nextcloud files. So I think the file name is right and the `allowDirectories()` should be removed.

All right! Then I thknk the solution makes sense!
