### ISSUE TITLE
[Bug]: missing tags name in the flow app 

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#35465]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since 25 release, certain tags are missing in the flow app.

existing tags beginning by "wp"
![image](https://user-images.githubusercontent.com/87175513/204312441-5a23926a-170e-4738-ab70-600676b7a63b.png)

no tags when searching from the flow app:
![image](https://user-images.githubusercontent.com/87175513/204312691-d370a3bc-7264-4f7e-bb40-a310f4acfcaa.png)

also, tag field is empty (rules were set before upgrading to NC25)
![image](https://user-images.githubusercontent.com/87175513/204312860-54901fb8-eb00-4d5b-9e37-fbc8236e1a0e.png)

But the FAC rule is working.

### Steps to reproduce

no idea :(

### Expected behavior

tag name should be displayed in the tag field.
tag should be searchable

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
ltd
```

**Comment by PVince81** [comment]
I assume that the group membership of the test user did not change after upgrading ?
because the list of tags you used are "restricted"

**Comment by PVince81** [comment]
My steps:

1. Setup v24.0.7
2. Create a user "alice" and add them into group "named-users"
3. Go to the admin settings page, section "Basic settings"
4. Create a public tag "publictag"
5. Create a restricted tag "restritag"
6. Install the "files_accesscontrol" app: `occ app:enable files_accesscontrol`
7. Create a new flow "Block access to file" in the admin settings, under "Flow"
8. Select "Filter by tag" and pick "Restritag"
9. Click "Save" to save the rule
10. Upgrade to v25.0.2rc1
11. Refresh the admin page
12. Type "p" or "r" to find the tags that exist

At least I can say that the tags did not get deleted.

However I see the following problems:
a) you cannot search by "tag" which is a string in the middle, you need to type the first letters. Might be a bug with multiselect, but the multiselect will be reworked anyway with a [new component](https://github.com/nextcloud/nextcloud-vue/issues/2504) so will need to replace it here

b) in the flow, the currently selected tag is not visible as selected in the dropdown:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/277525/204558918-9a566c34-3cc9-40da-b3a9-09c1e15104e8.png">

it says "Select a tag" even though there is a selection.
Clicking on it does show the tag list.

Regarding @maximelehericy's report, it feels like we don't have the same symptoms.
Maybe the search now requires you to type "WP" instead of "wp" when searching ? That would align with my finding that the search seems to work differently. (I didn't test it in NC 24 though)

**Comment by PVince81** [comment]
https://github.com/nextcloud/server/issues/34395

**Comment by maximelehericy** [comment]
Hi @PVince81 :)
Thanks for testing ! 
Symtom you describe in b) is the same as the one I experience.

In my case, the dropdown shows a list, certain tags appear, while others are missing, I cannot find a common denominator, certain tags have space in their name, certain tags are public, others restricted, others invisible...

**Comment by benmprojects** [comment]
Any update this is happening on v25.0.3

**Comment by maximelehericy** [comment]
I finally understood 🤯

The dropdown list basically shows only the first five results in alphabetical order 😑
As there are only five rows shown in the dropdown menu, you only see the first five tags.
To reproduce the issue (see below), you need more than 5 tags.

To reproduce:
1. create 7 tags:
- tag1
- tag2
- tag3
- tag4
- tag5
- tag6
- tag7

2. Go to the flow app.
3. Create a new flow, select a rule based on tagging.
4. Click the tag field, to show the dropdown menu
5. It will show tag1 to tag5.
5. Try to search tag6 by typing 6 for example > it says no tag found.

6. Now, go to the basic settings.
7. Delete tag1

8. Repeat steps 2 to 4
9. tag6 is shown in the list
10. try to search for tag7, you're screwed.

@blizzz @PVince81

**Comment by blizzz** [comment]
@Pytal  does it sound like something to be fixed with https://github.com/nextcloud/nextcloud-vue/pull/3747 ?

**Comment by Pytal** [comment]
Yes @blizzz, should already be fixed in server back to 25 with https://github.com/nextcloud/server/pull/36754

**Comment by blizzz** [comment]
Thank you @Pytal 

Closing as fixed with 25.0.5.
