### ISSUE TITLE
[Bug]: Incorrect prefixes used for file sizes

### ISSUE THREAD

**Issue by Zipdox** [nextcloud/server#35464]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud files displays the wrong prefix for file sizes. It counts the file size in binary but then labels them as decimal. For example, it counts the amount of mebibytes (MiB) but labels them megabytes (MB). This contradicts both the international system of units as well as IEC 80000-13.

Please refer to https://en.wikipedia.org/wiki/Byte#Multiple-byte_units

There are two possible solutions to this problem:

- Display binary prefixes (KiB, MiB, GiB, etc.)
- Count file size in decimal

### Steps to reproduce

1. Create a file of known size (1000000 bytes for example)
2. Upload the file to Nextcloud
3. Read the file size label (977 KB with this example)

### Expected behavior

The file size reads the correct amount (1000 KB or 1 MB) or uses the binary prefix (977 KiB).

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "REDACTED",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "REDACTED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.6.1",
        "overwrite.cli.url": "https:\/\/REDACTED\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "tempdirectory": "\/mnt\/ncdata\/tmp\/",
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "htaccess.RewriteBase": "\/",
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/"
    }
}
```

### List of activated Apps

```shell
- accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - apporder: 0.15.0
  - calendar: 3.5.2
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.2
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud-aio: 0.2.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - notify_push: 0.5.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.3.1
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.6
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.5
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Not applicable
```

**Comment by elsiehupp** [comment]
The (admittedly somewhat silly) macOS approach to binary vs decimal prefixes is to change the underlying calculation to use decimal (since this is what storage-device manufacturers use) rather than changing the unit prefixes to the correct yet less recognizable binary ones.

The main advantages with this approach are:

* It avoids introducing terminology that less technically savvy users might not understand; and
* It prioritizes consistency with the units used by other stakeholders (i.e. hardware manufacturers and, by extension, some software vendors like Apple).

The main disadvantage is that it requires changing the underlying calculation rather than just the terminology used in the interface.

The expected behavior for [the following](https://github.com/nextcloud/nextcloud-files/blob/05c0255d9ac9e3191698df667bda4815f1f0655b/__tests__/humanFileSize.spec.ts#L33-L38), then:

```typescript
[0, '0 KB'],
[125, '< 1 KB'],
[128000, '125 KB'],
[128000000, '122.1 MB'],
[128000000000, '119.2 GB'],
[128000000000000, '116.4 TB'],
[128000000000000.0, '116.4 TB'],
```

...would instead be:

```typescript
[0, '0 KB'],
[125, '< 1 KB'],
[128000, '128 KB'],
[128000000, '128 MB'],
[128000000000, '128 GB'],
[128000000000000, '128 TB'],
[128000000000000.0, '128 TB'],
```

Which would involve changing [the following](https://github.com/nextcloud/nextcloud-files/blob/05c0255d9ac9e3191698df667bda4815f1f0655b/lib/humanfilesize.ts#L40-L45):

```typescript
// Calculate Log with base 1024: size = 1024 ** order
let order = size > 0 ? Math.floor(Math.log(size) / Math.log(1024)) : 0;
// Stay in range of the byte sizes that are defined
order = Math.min(humanList.length - 1, order);
const readableFormat = humanList[order];
let relativeSize = (size / Math.pow(1024, order)).toFixed(1);
```

...to:

```typescript
/*
 * @note This block previously used Log base 1024, per IEC 80000-13;
 * however, for consistency with desktop shells this has been
 * changed to Log base 1000. Log base 1024 may be reintroduced
 * as an option at a later date, but would require a corresponding
 * addition to the options UI.
 */
// Calculate Log with base 1000: size = 1000 ** order
let order = size > 0 ? Math.floor(Math.log(size) / Math.log(1000)) : 0;
// Stay in range of the byte sizes that are defined
order = Math.min(humanList.length - 1, order);
const readableFormat = humanList[order];
let relativeSize = (size / Math.pow(1000, order)).toFixed(1);
```

Does this approach make sense?

**Comment by Zipdox** [comment]
Yes. but I suggest making at a setting then.

**Comment by Zipdox** [comment]
Holy crap there's a lot of instances of that function. Adding a setting in the UI is the easy part. Finding and changing all the calls to the function is another thing. I propose adding a shim function inside Util, and another function to change the setting.

**Comment by elsiehupp** [comment]
Shouldn't the calls to an updated version of the function just... work? I mean, the function could load the Log base from settings, rather than adding it as a parameter in the function signature. Changing the function signature seems like an unnecessary complication. (If for some reason it would be desirable for some calls to use a specific Log base regardless of settings, you could add an optional parameter, which other existing calls would just ignore.)

**Comment by Zipdox** [comment]
How would you go about loading the setting from within the function itself?

**Comment by elsiehupp** [comment]
> How would you go about loading the setting from within the function itself?

Currently [`humanfilesize.ts` imports localization](https://github.com/nextcloud/nextcloud-files/blob/4a490b7ac39191b21f012d038c2da99fd46862c6/lib/humanfilesize.ts#L24) like so:

```typescript
import { getCanonicalLocale } from '@nextcloud/l10n'
```

Presumably you would similarly import either [`UserSettings`](https://github.com/nextcloud/server/blob/9de329a4c2327767d86bd7f594b232eb56af0d01/apps/settings/js/usersettings.js) or [`AppConfig`](https://github.com/nextcloud/server/blob/14e57bf70a612c16eccdd733b3562d46053419c5/core/src/OCP/appconfig.js) and load and save parameter values using one or the other as an interface to user preferences.

(I assume global settings are a singleton, much like localization would be, hence why you could call them from anywhere, rather than having to pass them as a function parameter.)

As for how to actually do this... and how to implement a UI for setting said preference... that's way beyond my competency with regard to Nextcloud Server.

(Most of my familiarity is with Nextcloud Desktop, and I got looped in when John Molakvoæ pinged the entire nextcloud/desktop team on your pull request.)
