### ISSUE TITLE
JavaScript API: More flexibility for custom entries in the new file menu

### ISSUE THREAD

**Issue by danth** [nextcloud/server#35503]
Hi,

Currently the JavaScript API for the new file menu forces apps to prompt for a filename within the menu.

[This was confusing for users of my Transfer app](https://github.com/danth/transfer/discussions/3) as it was not clear whether to enter the file name or the URL into that prompt.

As a workaround, I made the plugin add itself to the menu directly, so that it can show its own dialogue:

https://github.com/danth/transfer/blob/0965b12d0660ce29d9807f039728035087330d85/js/views/App.svelte#L20-L104

[This broke with the release of Nextcloud 25](https://github.com/danth/transfer/issues/79) due to the IDs of the related page elements being changed.

It would be helpful if the JavaScript API allowed adding menu entries which lead directly to an action, similar to the upload file option.

**Comment by shawnlocal** [comment]
bump

**Comment by joshtrichards** [comment]
Cc: @skjnldsv

**Comment by skjnldsv** [comment]
Nice catch @joshtrichards, thanks for the ping !!!

@danth since Nextcloud 28, I introduced a new file action API
Please have a look at the documentation: 
- https://nextcloud-libraries.github.io/nextcloud-files/functions/addNewFileMenuEntry.html
- https://nextcloud-libraries.github.io/nextcloud-files/interfaces/Entry.html

It is an ongoing process and you can follow it [here](https://github.com/nextcloud/server/projects/6) and [here](https://github.com/nextcloud/server/issues/39914)

We moved away from having too much of an interaction with the menu itself and have a cleaner API.
Any Entry is responsible for nothing but themselves... You can decided to have an effect on the files list with global events.
You can see the first very basic example [here](https://github.com/nextcloud/server/blob/e3c127f046c05f8afa23d062788f0b97f9c9a079/apps/files/src/newMenu/newFolder.ts#L65-L96)

**Comment by te-online** [comment]
@skjnldsv Can you please explain how to mimic the old behavior with the new API?

I'm trying to port my app [Linkeditor](https://github.com/te-online/files_linkeditor) to Nextcloud 28 and am struggling big time.

The old API allowed me to call `addMenuEntry` with a `templateName`. This took care of (1) prompting the user for a file name with the given template, (2) making sure no file with the same name already exists, (3) calling the handler with the name the user chose and (4) giving me an API (`fileList.createFile`) to actually create the file.

I've tried `addNewFileMenuEntry` from `@nextcloud/files`, but there doesn't seem to be any documentation available besides the TypeScript file, which is very frustrating. How do I cover points 1-4 without reinventing the wheel? I don't want to add my own component to show a modal for the user to type the filename. Highlighting/selecting just the filename in the input, without the extension, to allow for easy editing would take me hours to implement.

Any help is appreciated as [I have people standing in line](https://github.com/te-online/files_linkeditor/issues/92) to get an update to this app, which turned out to require a rewrite of the integration with the Files app with only these 2 bullets to go by...

![grafik](https://github.com/nextcloud/server/assets/4127167/b1da9deb-8e67-4b95-b972-bc6cccd8658b)

I appreciate the huge amount of work that went into the rework of the files app, but it's all going a bit too quickly in my view.

**Comment by skjnldsv** [comment]
>  I don't want to add my own component to show a modal for the user to type the filename. Highlighting/selecting just the filename in the input, without the extension, to allow for easy editing would take me hours to implement.

1. You can find examples here:
	- https://github.com/nextcloud/server/blob/8be4704e1125b6eb6fe17a58c8b54c651fa40c0c/apps/files/src/components/NewNodeDialog.vue
	- https://github.com/nextcloud/server/blob/8be4704e1125b6eb6fe17a58c8b54c651fa40c0c/apps/files/src/utils/newNodeDialog.ts#L38-L57
2. The [`NewFileMenu Entry`](https://nextcloud-libraries.github.io/nextcloud-files/interfaces/Entry.html) [handler argument](https://nextcloud-libraries.github.io/nextcloud-files/interfaces/Entry.html#handler) provides the list of files and the current folder. Detecting conflicts can be done with [`hasConflicts`](https://nextcloud-libraries.github.io/nextcloud-upload/functions/hasConflict.html)
3. Should be done automatically from your dialog, not much of a trouble
4. We won't do that, you need to call the creation yourself. Any dev can do some different thing, we cannot provide this from the files list, this is hacky and not maintainable.
  BUT, we do provide simple ways to get the webdav library working right away for you, which you can use to create a simple file afterwards.
   - get the webdav client: https://nextcloud-libraries.github.io/nextcloud-files/functions/davGetClient.html
   - create the file:: https://github.com/perry-mitchell/webdav-client#putfilecontents
   - emit the event stating the file has been created with a proper [`File`](https://nextcloud-libraries.github.io/nextcloud-files/classes/File.html) object:
   ```ts
   import { emit } from '@nextcloud/event-bus'
   import { File } from '@nextcloud/files'
  // import the client
  // upload your file 
   const node = new File({...})
   emit('files:node:created', node)`
   ```

**Comment by te-online** [comment]
Thanks a lot for your extensive answer – I will take a closer look in a few days 👍 🤗

**Comment by te-online** [comment]
I've made some progress on this, but it's a difficult way. I'm not using Vue, so that may be why it's difficult.

The issue with your example is that `client.putFileContents` returns `boolean`, while the `File` constructor expects me to pass in a `fileid`. How am I supposed to know that id? 

> The [NewFileMenu Entry](https://nextcloud-libraries.github.io/nextcloud-files/interfaces/Entry.html) [handler argument](https://nextcloud-libraries.github.io/nextcloud-files/interfaces/Entry.html#handler) provides the list of files and the current folder. Detecting conflicts can be done with [hasConflicts](https://nextcloud-libraries.github.io/nextcloud-upload/functions/hasConflict.html)

> We won't do that, you need to call the creation yourself. Any dev can do some different thing, we cannot provide this from the files list, this is hacky and not maintainable.

I'm not sure about that. As far as I understand, the new situation is this:
- There's no API I can call to trigger the built-in and well-design dialog to create files
- I have to roll my own dialog, which is still much worse now that I've spent and afternoon implementing it
- There's no single API I can call to create a file and update the UI to signal success to the user and highlight the file in the list. 
- The experience of creating a file will be vastly different, depending on how the developer of the integration implemented this flow

The previous API had all these things. I can see why some apps don't want that. You may want to open a full screen editor or something like that. But the solution to that is not _do-it-yourself_. My wish would be for a solution that improves the API to support these use-cases.

What I'm doing now is more _hacky_ than before and it lowers the quality of my app.

**Comment by skjnldsv** [comment]
> The issue with your example is that `client.putFileContents` returns `boolean`, while the `File` constructor expects me to pass in a `fileid`. How am I supposed to know that id?

`OC-FileId` https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#response-headers

> There's no single API I can call to create a file and update the UI to signal success to the user and highlight the file in the list.

Yes, use the appropriate events.
You can also change the file and highlight it by changing the URL to the new fileId.
The UI will scroll down and focus the specified fileid (if found in the list)
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/files.html#router
