### ISSUE TITLE
The current session (in the devices & sessions section) cannot be renamed

### ISSUE THREAD

**Issue by jsimon18** [nextcloud/server#35882]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The current session (settings > security > devices & sessions) cannot be renamed. It would be easier to tell what it is (from another device/session) if it could be tho.

**Describe the solution you'd like**
Being able to rename the current session. It could say: "Current session: <Given name>" for example.

**Describe alternatives you've considered**
I've logged in from 2 web browsers on different devices at the same time and changed the name of the other entry in each case.

**Additional context**
![image](https://user-images.githubusercontent.com/58323703/209489450-15533885-b769-44e0-a8c8-c16d40d0e25a.png)

**Comment by joshtrichards** [comment]
Hi @jsimon18 - Thanks for the input!

This looks to be a duplicate of #30447. **If you agree, please close this Issue** and click the :+1: on #30447 to indicate you're impacted by the same situation (this assists with prioritizing issues). Also you may wish to subscribe yourself to #30447 to receive updates (since that's where further updates on this matter will likely be tracked).

**Comment by jsimon18** [comment]
see previous comment.
