### ISSUE TITLE
Email notifications for pending upgrades

### ISSUE THREAD

**Issue by steckerhalter** [nextcloud/server#3596]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I think it would be great if Nextcloud could notify the Admin via Email if there are pending upgrades. This would make it easier to deal with upgrades also on instances one is not actively using but rather just maintaining.

**Comment by nickvergessen** [comment]
Since Nextcloud 10 we have update notifications delivered by the notifications API. When you have a sync client set up and connected, it will bring the notifications to your desktop.

However I just discussed with one of my colleges today, that it would also be cool to send a reminder email after some days to the admin when the instance is still not updated.

**Comment by 001101** [comment]
why not just make it auto-update able?

**Comment by baldurmen** [comment]
To me this is very important since as a sysadmin I manage some Nextcloud instances that I don't use myself.

Using the desktop app to know a new upgrade is pending is thus not a solution.

**Comment by Dreamsorcerer** [comment]
Alternatively, how about Nextcloud instances that you do use, but not through the web interface or a Nextcloud app? Then you don't see any notifications at all.

i.e. I use Nextcloud primarily for syncing contacts/calendar. This is done through the online accounts in GNOME on my laptop and syncevolution on my phone. Neither of these tell me anything about upgrades.

**Comment by c33s** [comment]
an email on pending updates is really important. having such a widespread app, you should add such a important feature to make the web a little bit more secure.

> that it would also be cool to send a reminder email after some days

 i am clearly against a delay. the email should be sent instantly, not with some days delay. if there is a security hole, the admins want to be notified (instantly). 

i assume that updates are only shown to the admin user, so keep in mind, that you require me to work as admin with my sync app to get such important informations.

workaround i found (german text but the code is english): 
https://spielwiese.la-evento.com/xelasblog/archives/75-Mailbenachrichtigung-bei-verfuegbaren-Nextcloud-Updates.html

**Comment by michaellass** [comment]
@nickvergessen I tend to disagree here. As an admin, I may only use ownCloud using the web UI or just for syncing calendars and contacts. Or I may administer an instance for other people so I don't use it myself at all. Running a client all time just to be informed about updates is a not very comfortable.

**Comment by nickvergessen** [comment]
Well if you are using ownCloud we can't help you anyway. [/joke]

But well, I do agree that this should be fixed. I'm just saying it's not as bad as people are drawing it.

**Comment by Dreamsorcerer** [comment]
It's as bad as we're saying, for the group of people such as myself, who currently receive no notifications, because we don't use the sync app or similar.

Maybe it's only a small number of users, but for those users, it is a moderately serious security issue, as there is no obvious way to get notified promptly about upgrades. Currently, I typically find out about security updates weeks or sometimes even months after they are released, when I just happen to log in to the web interface.

**Comment by danielkesselberg** [comment]
I added https://github.com/nextcloud/server/releases.atom to my rss reader.

**Comment by danielkesselberg** [comment]
@baldurmen https://github.com/nextcloud/server/pull/10836 (unfortunately too late for nextcloud 14)

**Comment by c33s** [comment]
@danielkesselberg of course these links help, but still they show all releases. normally a admin does not care for beta releases or release candidates. the admin wants to know is there a security update for my current installation. 
we are all flooded with messages from multiple services: emails, newsletter, github, rss feeds, social networks,... so nextcloud should add this feature to help admins to net get drowned in too many unneeded emails and only send an email if the admin should act.

**Comment by hjbotha** [comment]
A perspective that may not have been considered just yet: For the past year I've been wondering what's wrong with my instance that it's not sending me an email when new versions are released. It only occurred to me as I was typing up a question on the forum that I may have misunderstood the function, and to read the notification option carefully and search for it (which brought me here). Others may be letting their instance go unupdated not realising that there's numerous updates available.

The reason I haven't seen the notifications is because I rarely use the web app, like others here. The sync is done on my server, and I access the synced directory over the network.

**Comment by AquaL1te** [comment]
This would also be useful for update notifications of apps. Sure I also have the sync client and see notifications there. But the workflow of a sysadmin for these kind of things are usually via email notifications.

**Comment by baldurmen** [comment]
I was using the old `owncloud` client and I used to get notified of updates this way, but now that I switched to the `nextcloud` client I don't get those notifications anymore...

I've hacked some icinga2 tests to check for app updates and core updates for now, but this is getting really painful :(

**Comment by nickvergessen** [comment]
That should actually work quite fine

**Comment by ezzra** [comment]
> This would also be useful for update notifications of apps.

I want to emphasize this statement, because it seems to be much more important to me. I am currently managing more than 20 Nextcloud instances which I am not using by my own. So I rarely login there. I actually do follow the Nextcloud releases stream, so I know when its time to update my instances. Some of the are even managed and therefor updated by another company. 

But for all of these instances there are different apps active, for some instances there are even other users enabling/disabling apps. So I would need to know which apps are active in which instances and then follow all the release streams and login manually to the concerned instances and press the update button. And thats even for the managed instances because normally app updates are not included in the management. That is more than inconvenient and its feeling very much unprofessional. 

A Mail notification with a direct link would help here, because then only the concerned instances would notify. An autoupdater for apps **as an option** (and and activity notification) would make this  even more handy for a lot of environments.

**Comment by andreapx** [comment]
I've just seen this and I have to agree, email notification would be really useful.
Why has this issue been closed?

**Comment by baldurmen** [comment]
Since the addition of `occ update:check` you can run a cronjob to alert you by email when there are updates available or use the ouput in a proper monitoring system.

**Comment by ezzra** [comment]
that wont work if you don't have terminal access. This is true for managed nextcloud setups.

**Comment by ilippert** [comment]
Why not simply add a checkbox-based choice of whether the specified groups (to be informed about updates) should also be informed by email?

**Comment by fosple** [comment]
Agree with @ilippert

**Comment by joostvkempen** [comment]
a checkbox would be perfect!

**Comment by kesselb** [comment]
@fosple @joostvkempen please use [GitHub reactions](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/). If you comment everyone subscribed to the issue get's a notification.

**Comment by ZeikoFr** [comment]
Any progress on this issue ? Really it could be so usefull to receive these mails

**Comment by c33s** [comment]
or at least allow us to config a webhook which is triggered if an update is available, then we can send the emails by ourselfs

**Comment by TmCrafz** [comment]
I agree that an email notification is very important

**Comment by zeus86** [comment]
I would really like to see this feature, too. This is just missing IMHO.

**Comment by nickvergessen** [comment]
Should be solved via https://github.com/nextcloud/notifications/issues/314 now
