### ISSUE TITLE
Why not run with systemd?

### ISSUE THREAD

**Issue by cyberdynesoftware** [nextcloud/server#36231]
I've just started to read the documentation for nextcloud server and was surprised of the rather involved installation process. Is there a reason a nextcloud server cannot simply be started with systemd? 

To be more precise, my expectation for running a nextcloud server was this:

    dnf install nextcloud
    systemctl enable --now nextcloud

Done. Obviously, things are quite a bit more involved than this. I would like to ask, why? Is this something I can hope for in the future? Or are there reasons that firering up a nextcloud server cannot be this simple?

**Comment by NateNate60** [comment]
This is because Nextcloud is, at its core, a set of PHP files (yes, it's more complicated than that but this is a good enough simplification). PHP programs are run by web server software whenever a user access that file. So when a client accesses `index.php` then your web server software runs the PHP code in `index.php` and delivers the result to the client.

When you install Nextcloud, it's really nothing more than:

1. Installing the web server software and configuring it appropriately
2. Putting the PHP files in the right places
3. Installing the necessary modules that the web server software needs to run that PHP code
4. Setting up the database that Nextcloud will use to remember information
5. Adjusting configuration files as necessary, perhaps through a web-based frontend

Easy installation of Nextcloud is actually possible but as a Snap package. It is not possible to ship Nextcloud as a native package because the Nextcloud developers would then have to consider dozens of different distros and web server configurations. A Snap package gets around that by running in its own separate, and most importantly, uniform, environment on every distribution. The Snap package also includes the Apache web server software.

```
snap install nextcloud
```

As for Systemd, since Nextcloud doesn't run in its own process, but rather, relies on the web server to execute its PHP code, the only thing that needs to run in the background is the web server, which often *is* controlled by `systemd`.

```
systemctl enable --now httpd
```

**Comment by solracsf** [comment]
As stated, you can run it on a snap, also on a docker container if you're looking for simplicity. See:

https://github.com/nextcloud/docker
https://github.com/nextcloud-snap/nextcloud-snap
https://github.com/nextcloud/all-in-one

For further discussion on this, please move to https://help.nextcloud.com 👍
