### ISSUE TITLE
Deprecation and removal of PHP8.0 support

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#36437]
Continuation of https://github.com/nextcloud/server/issues/35025

PHP8.0 will run out of security support end of year.

Some usage stats can be found on https://ncpw.mdns.eu/.
Ref https://www.php.net/supported-versions.php

We should do this in two steps again
* [x] Deprecate the version but still support it + documentation (Nextcloud 27)
* [ ] Drop support with Nextcloud 28 if released before EOL
* [ ] Drop support with Nextcloud 29 if v28 still supported it

cc @AndyScherzinger @juliushaertl @nickvergessen

**Comment by ChristophWurst** [comment]
That is also fine. We can still deprecate with 27 to give admins more time and only make the breaking change with 29.

**Comment by AndyScherzinger** [comment]
So let's do it like that then: deprecate PHP8.0 with v27, v28 last version supporting it (if released before PHP8.0 EOL), drop with v29 (except when 28 already would drop it).

**Comment by ChristophWurst** [comment]
PHP8.0 runs out of security support in five months. With our current release pace we'll probably finish 28 slightly earlier. Thus 8.0 support is rather not to drop in 28 but in 29.

**Comment by isdnfan** [comment]
hi team another heads up - for some reason NC30 still supports PHP 8.0 which is EOL since 26.11.**2023**!! 
please keep in mind PHP 8.1 "*Active support*" ends in less than 2 months on on 1 Jan 2025

**Comment by nickvergessen** [comment]
30 does not support 8.0: https://github.com/nextcloud/server/blob/stable30/lib/versioncheck.php#L9

Also note, that we will keep 8.1 (as it's still security supported) until a dependency bump of non replaceable dependencies like symfony, doctrine dbal or the likes forces us to drop it.

**Comment by AndyScherzinger** [comment]
@isdnfan yes, we decided for v30 to have 8.0 support given that at the time of the release SLES did not have php8.0 support, hence we were forced to keep it, else instances running SLES would have been locked on an older Nextcloud version since the underlying stack could not be upgraded.

**Comment by isdnfan** [comment]
thank you for clarification @nickvergessen and @AndyScherzinger . In fact I was misleaded by unfortunate linking issue from https://docs.nextcloud.com which links NC30 to a "stable* docs branch and NC31 to a "latest" while in fact NC30 is "latest"

https://help.nextcloud.com/t/drop-of-php-8-0-support-in-nextcloud-30/209361/8?u=wwe

> we decided for v29 to have 8.0 support given that at the time of the release SLES did not have php8.0 support,

the relevant metric is not "time of release" but the time of EOL. Support period of any NC version must not exceed supported PHP version EOL. there will be always some *"important"* distro like Debian or Ubuntu LTS failing behind supported versions. From my experience enterprise customers running LTS and Enterprise versions prefer clear roadmap so required updates can be planned in advance. A reliable road map with NC support aligned to PHP support would really help - which is not the case now e.g. NC31 with supposed EOL in Feb/Mar 2026 is already behind PHP 8.1 EOL.

Customers relying on ancient application versions could use paid enterprise support model where old versions remain supported longer..

**Comment by AndyScherzinger** [comment]
@isdnfan I beg to differ...

We do deprecate and ultimate remove support for php versions going EOL from a PHP roadmap point of view at the earliest moment possible. In order to do so the important part is OS/distro support for PHP versions _not_ PHP's own roadmap. 

Stick to my example: SLES until very recently didn't provide PHP beyond 8.0 for _ANY_ SLES version yet according to your arguiment based on the PHP roadmap we should have thrown it out, hence customers (or community) would not be able to update to that Nextcloud version because the OS lacks support of the minimum PHP version.

> Customers relying on ancient application versions could use paid enterprise support model where old versions remain supported longer..

Customers aren't relying on ancient application versions but might be locked in on a certain PHP version depending on their distro of choice. So we would then force them to run an older Nextcloud version - why should we? Tellign a customer they can't run latest Nextclioud because the latest OS doesn't support is is not very customer-centric or -friendly. And the quotation marks can be droped. The OS _IS_ important, it is a fundamental decision by an IT department throughout the operational landscape for all or most applications run for/at a company so comapnies want standardized infra hence one plattform and the OS is part of that, you don't want to run multiple distro. So it is not about importance of an OS is ensuring folks can run the latest NExtcloud on the latest distro versions.

---

> thank you for clarification @nickvergessen and @AndyScherzinger . In fact I was misleaded by unfortunate linking issue from https://docs.nextcloud.com/ which links NC30 to a "stable* docs branch and NC31 to a "latest" while in fact NC30 is "latest"

This is currently about to be fixed, thanks for the info 👍

**Comment by isdnfan** [comment]
@AndyScherzinger  I don't get your arguments. LTS releases come together with advantages and limitations like missing drivers for new hardware, older libraries like PHP which at some time become unsupported by newer applications. Every admin or company choosing an LTS or *enterprise" distro primarily look to run the system unchanged over the long period of time. Installing latest Nextcloud version sounds like an anti-pattern for such installations. 

Keeping 8.1 supported  after PHP 8.4 release on Nov 21, 2024 will require support and testing for 4 PHP versions..

**Comment by AndyScherzinger** [comment]
Let me try to rephrase, maybe that helps.

* as a software vendor I want to give the decision on when to upgrade Nextcloud to the customer. So given the scenario a feature has been build wanted or even needed for a customer (or community member) I would not want to to force their hand. Ultimately this would else mean, need new feature, change the distro.
* In case of SLES it is not about LTS but about no new version at all on any version of the distro.

> Keeping 8.1 supported after PHP 8.4 release on Nov 21, 2024 will require support and testing for 4 PHP versions..

We drop support for 8.1 with the next major release shipping after the EOL date of 8.1 because

* php 8.1 is EOL _AND_
* all supported distros supported before the next major release are still supported for the next major release

Dropping php versions without looking at the list of distros you support and just dropping them based on php schedule means the distros you support vary between major releases or get support at a later point in time when a distro may add support of a php version in range. This is a huge complexity for operating parting. Hence we as Nextcloud ensure that all supported OS distros are supported at any time while the version needed to operate Nextcloud changes over time, with the specific OS version pinned on a per Nextcloud major release way.
