### ISSUE TITLE
sync client does not obey selective sync

### ISSUE THREAD

**Issue by cryptochrome** [nextcloud/server#3661]
The Windows and OS X sync clients do not obey selective sync options. For example, if I configure the sync client to only sync root_dir/sync1 and then add a new folder to root_dir, like root_dir/do-not-sync, the sync client automatically selects the new folder and starts syncing. 

Judging forum posts about this, the client has been doing this for a long time:
https://help.nextcloud.com/t/how-to-stop-file-sync-client-from-automatically-selecting-new-folders/6143

**Comment by brianbgness** [comment]
@cryptochrome Hi I'm Brian the original author of that forum post.  At my organization we've spend a lot of time trying to understand this behavior.  I read about csync and poured over the desktop client code for 2 days.  I'm not a programmer but was able to glean some insight.  The client works be selecting folders.  And when a folder is selected, it's parent is also selected.  Additionally the root folder is always selected for each user.  If it wasn't this way, the whole discovery process would be broken to find new files and folders to sync.  Therefore by default everything gets selected.  The "selective sync" feature is simply the ability to de-select folders after the fact.

In my opinion, it's too late in the life of the Nextcloud platform to radically change the desktop client.  It would be risky.  The fantastic reliability of today's desktop client comes after years of refinement.  My wish is that the desktop client acted like backup software where you tell it to sync just a few specific folders and their children.  So the client would have to be re-written to permit selecting the equivalent of multiple root folders.  Today's logic of always selecting the base root folder would be gone, which would necessitate adding the capability to select individual files.  That's not going to happen anytime soon.  It would probably be easier to start over again with a new desktop client than to change the underlying assumptions of the existing code.

Again I no longer want the developers to "fix" selective sync.  It's not broken, as it's behaving exactly as designed.  But in my organization's environment the behavior has been confusing to say the least.  What I now tell my confused users is that the desktop client behaves the same as Dropbox, and after a moment of thinking about it, they generally accept it.  Therefore by default new folders are automatically selected to sync.  And sometimes they'll have to de-select new folders they don't want.

**Comment by cryptochrome** [comment]
It's never too late :)

What made me report this is what happened to me: I added a Google Drive external storage to my Nextcloud root folder the other day. That Google Drive has 680 GB of storage. Needless to say it started syncing all of that down to my local computer. Because I wasn't aware of it - I never would have expected that this would happen - it filled my local hard drive over night.

If something like this can happen, and I am sorry to say so, then the design is broken. Severely broken.

No other sync client, be it Dropbox, Google Drive, Box or what have you, would do something like that. They understand what selective sync means.

**Comment by brianbgness** [comment]
Exactly.  That's why I've been afraid of adding external storages for fear of filling one of my user's hard drives!  In the upcoming version 2.3 desktop client there is a new feature:  "Ask for confirmation before synchronizing external storages".  Just confirmed it works.  It's enabled by default and I couldn't be happier.  You should check it out.
https://owncloud.org/install/#testing-development

**Comment by nickvergessen** [comment]
The client has now been released, so case closed I guess?

**Comment by nshobe** [comment]
Personally, I wouldn't call this "fixed" in any manner. My client is up to date at 2.3.3.1 and we only have mild workarounds. This should be a feature request, not necessarily a bug.

It seems to be like most users feel that when they "manually selectively sync" a folder, they have no interest in the parent folder's updates beyond what they manually select. The manual selection mode of the client should be smart enough to understand partial and full selection boxes (as the gui would indicate from knowing the difference between a partially filled square and a check mark). Yet, this isn't the behavior at all.

To be perfectly clear, if I _manually_ only selected:
/files/groupA/projectA/teamA/mystuff

And someone added a folder:
/files/groupB

Suddenly my client wants to sync it.

What user would expect that? Which is why people on forums call it a bug. If the underlying sync daemon tracks all files for reliability (which I understand and am glad the client sync service is so reliable), then there should be a higher up logic that is able to de-select items based upon the user's selections.

Adding an "only sync when I say too" or "don't sync new folders over a certain size" are crude workarounds. What if I work with big files in MY space, but simply don't want to deal with the clutter elsewhere? What if I need new folders synced under MY selected folders continually throughout the day and don't want to be bothered telling it to sync? Like I said, crude.

**Comment by jessebobrien** [comment]
I agree, this is really painful functionality for multi-user collaborative teams. If the client is going to do **anything** with a freshly discovered directory, I'd want it to raise a notification and let me react accordingly.

**Comment by mkudlacek** [comment]
Hi,
I would like to share my use-case, which results in the same unwanted behaviour as described above.

I run for my family and friends a simple backup solution via Nextcloud. I install them a client and show them dedicated folder where they can store data and it will be automatically uploaded to Nextcloud. Each night, I perform backup of the Nextcloud installation on my server with BackupPC and after that I do offsite backup of the encrypted BackupPC folder to another machine in different physical location (yeah, I'm that thorough/paranoid). For low level users it's great - they just save their important things into that folder and everything else is automatic. They don't need to do anything else and in case of disaster, I will set them new computer and Nextcloud client and they will have their files back.

But for some family members I am also sharing folders. They will receive email, they know how to login into web UI and check what's new, but I don't want the shared folders to be automatically synced to their computer. And since new shared folder appears directly in root folder, I cannot set some ignore flag before it happens.

There are multiple ways how to avoid this, one could be this (just on top of my head):

Create semi-folder called "Shared with me", where all the new shared data will be stored instead of the root folder. After installation of Nextcloud client, I could exclude this folder from syncing once and for all. Any other folder in root folder would still be synced.

**Comment by jospoortvliet** [comment]
So by default, the client syncs any new sub folders that appear in any existing synced folder. I think that that is the sane and logical thing to do...

Note that you don't have to sync the root folder at all, you can simply only sync ```/nextcloud/customers/project B``` with a local folder, for example ```My Documents/Projects/Project B 2018``` and you can, that way, sync any number of local and remote folders at will. But you can only do that if you don't sync the root folder.

Second, and that is probably more what you want, you can make sure the client asks for permission for any new folder being added. For that, set this setting to 0 mb:
![screenshot_20181121_131603](https://user-images.githubusercontent.com/551757/48840923-41370b00-ed90-11e8-9d8d-22ffe3c3ceb4.png)

I haven't tried it right now but I believe this should do the trick. If not, that's worthy of a bug report and something that can be fixed.

Also note that we're working on a better way of doing this whole sync thing - but that is for a solution next year :night_with_stars: 

Of course, if this is an issue in your company, you can always contact our support team (if you have a Subscription) or let us know we should prioritize this issue through your account manager.

**Comment by polvoazul** [comment]
I think that a nice way to think about this is that folders can be selected (sync folder's files and new children), deselected, or have children selected. Today, if a folder has children selected, then it is also SELECTED. I dont see why this needs to be the case. You could have folder x/y/z selected, but no interest in x/ or x/y beign selected. 

Could we re-open this issue?
