### ISSUE TITLE
[Design reqeust] shared with me symbol

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/server#3680]
Hey would it be possible to rotate the icon? I think that make it easier to separate the two entries
![grafik](https://cloud.githubusercontent.com/assets/11041576/23509375/d53ab3ae-ff55-11e6-9fef-f221ae4e9beb.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
No, as it's basically the same and it would confuse people as it's used nowhere else in this rotated fashion.

Actually we should simplify the sidebar by primarily offering one entry to show all shared files, with the specific filters only as subentries.

**Comment by eppfel** [comment]
@jancborchardt: So, ◀️ and  ▶️ is the basically the same,too. 😉 

> it's used nowhere else

this is not an argument

> Actually we should simplify the sidebar by primarily offering one entry to show all shared files, with the specific filters only as subentries.

This is an argument.

just my 2  💵 /100

❤️

**Comment by pixelipo** [comment]
"it's used nowhere else" is an excellent argument in this case. Icons are meant to quickly inform user of the meaning, without the need to read the label. Hence, they are only useful of they are easy to interpret and/or have generally accepted meaning (because they are used everywhere). Inverted share icon fulfills none of these criteria.
