### ISSUE TITLE
Translations with ' are escaped

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#3692]
When the `t()` translation function is used with angular, angular seems to escape the `'` character provided by `t()`, resulting in `&#039`, see below on the personal settings page, and https://github.com/nextcloud/calendar/issues/269 on the calendar app itself.
![](https://cloud.githubusercontent.com/assets/2197836/23545215/a4f07fd0-fffa-11e6-938b-85bc09677b1f.png)

Ref. https://github.com/nextcloud/calendar/issues/357

**Comment by georgehrke** [comment]
The sidebar in the screenshot is definitely not angular based ;)

**Comment by tcitworld** [comment]
Indeed. But it's generated through js too it I recall.

**Comment by MorrisJobke** [comment]
We generally escape all strings. I guess this is the reason for this. @LukasReschke Anything we could do here? I guess translations are safe to be not escaped, or am I wrong?

**Comment by LukasReschke** [comment]
The reason that this is escaped by default is to make it for developers as unlikely as possible to introduce an XSS vulnerability by mistake.

We cannot really change the default behavior of `t()` here as this would break existing code and potentially introduce vulnerabilities.

That said: `t('core', '<>\'"')` returns `&lt;&gt;'"` for me. So only the `<` and the `>` are escaped via JS. So I'd say this is actually caused by some code in the AngularJS part which we don't handle in core at all.

**Comment by georgehrke** [comment]
@LukasReschke The screenshot posted by @tcitworld is from the personal settings. Something that does not use angular and definitely is a part of core ;)

**Comment by LukasReschke** [comment]
Then the issue should state so 😉

**Comment by LukasReschke** [comment]
So this is basically because of the regular expression magic in `settings/personal.php`. Basically https://github.com/nextcloud/server/blob/d6e7cee60779d85d05264ba360463ab9eabc7d35/apps/twofactor_backupcodes/templates/personal.php#L10 is regex'd at https://github.com/nextcloud/server/blob/9480b29413daba34432885642b575065ed5f5d6d/settings/personal.php#L245-L266 which is then printed using `p()` at https://github.com/nextcloud/server/blob/4ec05ef0507d840f18bebc7750b05e31a67bc21b/settings/templates/personal.php#L15-L19 and thus double-escaped.

I don't feel comfortable adjusting this right now though as this could introduce vulnerabilities. So something for 13 IMO. A proper patch instead of some regular expressions would be way saner here… :)

**Comment by MorrisJobke** [comment]
This specific issue is solved. If there is another one, we can have a look. I will close this for now.
