### ISSUE TITLE
'Enable only for specific groups' also for core apps

### ISSUE THREAD

**Issue by rgr101** [nextcloud/server#3707]
It would be helpful to have this feature also for the core apps like Activity, Federation etc. 
as I want to set up a group "guests" with VERY limited access.

### Server configuration
**Nextcloud version:**
11.0.2

**Comment by nickvergessen** [comment]
The problem is that apps that are restricted wouldn't work fully anymore.
E.g. when you disable the activity app for the guest group, and a guest user changes a file, the change would not be written into the activity log of your admin account, because the app was not loaded for the user. There needs to be more work done in terms of splitting the API and the UI on the apps, to be able to support disabling the UI only.
Until then, this is not really an option.

**Comment by rgr101** [comment]
Ah ok, I see. 
So, I’d be glad if you kept it on the wishlist - as I believe this really makes sense :)

**Comment by Tanarri** [comment]
I think this is a great idea, to have a "guest" user with very limited access.
For this reason I am experimenting with a second NC instance, which has all apps diabled. 
The files for the guest user are synced over night to his home directory directly. (I don't know a better solution, because the sharing apps also disabled)

So, it would be great if there is a solution (within one NC instance) to disable/enable the core apps for specific users/groups.

Is it also possible to forbid this guest user to change his personal settings - especially his password

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
