### ISSUE TITLE
Remove X-Robots-Tag warning

### ISSUE THREAD

**Issue by aentwist** [nextcloud/server#37331]
## User Story

I unset the X-Robots-Tag header and do not want to be warned about it.

The header provides control over how search engines index pages. However, with [this robots.txt](https://github.com/nextcloud/server/blob/master/robots.txt), the pages are never even *crawled* in the first place, let alone *indexed*.

I do not want this header. I do not want to be warned about this header.

## Proposed Solution

Remove the warning.

## Alternative Considerations

- add option to disable the warning
- actually stop setting the header

## See Also

> The [X-Robots-Tag](https://developers.google.com/search/docs/advanced/robots/robots_meta_tag) HTTP header is used to indicate how a web page is to be indexed within public search engine results. The header is effectively equivalent to `meta name="robots" content="…"`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#x-robots-tag

**Comment by aentwist** [comment]
Related to https://github.com/nextcloud/docker/issues/1218

**Comment by apg1980** [comment]
Hello, is here any workarround?

**Comment by tcitworld** [comment]
Do you mind explaining why you don't want this header?
[Google does not accept `robots.txt` as a way to prevent crawling](https://developers.google.com/search/docs/crawling-indexing/robots/intro?hl=en)
> A robots.txt file tells search engine crawlers which URLs the crawler can access on your site. This is used mainly to avoid overloading your site with requests; it is not a mechanism for keeping a web page out of Google. To keep a web page out of Google, [block indexing with noindex](https://developers.google.com/search/docs/crawling-indexing/block-indexing) or password-protect the page.

**Comment by MichaIng** [comment]
There are in fact examples of Nextcloud instances found on Bing (since the previous `none` was is not understood by Bing), despite the `robots.txt` being in place, and I know the same for some pages of our server, until we switched to `noindex, nofollow`. `robots.txt` is NOT preventing page indexing. I'm not sure why this is, since for me the (admin) intention of `Disallow` should be clear, but I remember reading quite some good explanation.

E.g.

- https://cloud.dresden.de/robots.txt
- ```console
  # curl -I https://cloud.dresden.de/
  X-Robots-Tag: none
  ```
- https://www.bing.com/search?q=cloud.dresden.de

Although probably not the best example, since it is indexed in Google as well, despite header and robots.txt: https://www.google.com/search?q=cloud.dresden.de

**Comment by aentwist** [comment]
Wow that's insane - am definitely adding it back. Thanks for sharing some of your knowledge; I see that Nextcloud is in good hands. This issue is silly to begin with. Hopefully future searchers will find it somewhat useful.
