### ISSUE TITLE
Webdav

### ISSUE THREAD

**Issue by ddanielww** [nextcloud/server#3738]
I have webdav working but sometimes I get an error on windows client saying "the network name cannot be found", however, if I test this with the demo version of nextcloud it works every time without issues.

Restarting Webclient on windows help, however, sometimes this is not possible.

Any ideas what could be wrong ?

Version 11.0.2
php 7

**Comment by MariusBluem** [comment]
Well... To assist you best, it would be great if you could provide us a filled out [issue template](https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md) with all the information about your instance 💪 

You may also want to consider about asking for help in our forums (help.nextcloud.com) for help ... because this is only our issue tracker for bugs in our code generally and not for individual configuration problems ... I am pretty sure that we will find a solution over there 😁

**Comment by MorrisJobke** [comment]
Close due to no feedback for 2 months.
