### ISSUE TITLE
Feature To-Do: integrate updates notification area

### ISSUE THREAD

**Issue by 001101** [nextcloud/server#3775]
Integrate a Notification Area for admins in the right corner, next to the username.

Functions to include:

-Update notification
-One button update applying
-Seperate notification for apps and server

Like on Sandstorm, they just made a simple bubble, showing you the notification and the notification has already a action button for simple stupid updates.

https://en.wikipedia.org/wiki/KISS_principle

greets

![noti update](https://cloud.githubusercontent.com/assets/8197408/23719323/34c01c12-043b-11e7-8807-997b0b52738e.jpg)

**Comment by nickvergessen** [comment]
For the server update this is definitely nothing we want to do at the moment. It's just too complex for now.

The reason why we don't do it for app updates is, that currently when you update an app and the server doesn't load correctly afterwards the app is disabled with a quick route. This can not be done by apps showing the notification. That's why, for now, you need to click on the message, get redirected to the apps management page and can update it there.

**Comment by nickvergessen** [comment]
But there is also https://github.com/nextcloud/server/issues/3182 which could then obsolete this idea anyway ;)

**Comment by MorrisJobke** [comment]
We currently show if there is an update and a button to get to this page. And this is for now all we will do in the notification area. It is still a notification area and not the updater area.
