### ISSUE TITLE
[Bug]: WebDAV very high CPU consumption

### ISSUE THREAD

**Issue by 7ritn** [nextcloud/server#37851]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,
I experience very high CPU utilization and extremely slow transfer rates when transferring small files using WebDAV with rclone. Regardless of the file size, Nextcloud can't seem to handle more than 5 files per second before completely maxing out the CPU, which makes uploading thousands of very small files almost impossible. The same behavior is **not** observed with the Nextcloud Linux Client, which seems to be able to upload around 100 Files/s.

### Steps to reproduce

1. Upload directory with lots of small files to Nextcloud using WebDAV
2. `rclone copy --verbose --update --transfers 10 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s Test nextcloud:Test`

### Expected behavior

WebDAV performance is similar to Linux Client performance

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Other

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hymalia.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "http:\/\/cloud.hymalia.duckdns.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "mail_smtpmode": "sendmail",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_scripts: 2.2.1
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - metadata: 0.18.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quota_warning: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - bruteforcesettings: 2.6.0 (installed 2.6.0)
  - encryption: 2.14.0
  - files_external: 1.18.0
  - suspicious_login: 4.4.0 (installed 4.4.0)
  - twofactor_totp: 8.0.0-alpha.0
  - user_ldap: 1.16.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

The server has a midrange Intel CPU from 2012 or so. Raw copying data to the Nextcloud drive is really fast and should not be a problem.

**Comment by joshtrichards** [comment]
Tiny files are sort of the bane of WebDAV clients. It's much easier to optimize for large file transfers.

In fairness to webdav client implementations, it's challenging to optimize beyond a certain point due to constraints in the webdav protocol. That said, my experience is that webdav support in many of the client-side offerings out there is subpar or under optimized (relative to potential) for non-large files. And it's really easy for small extraneous things in client implementations - that don't show up on the testing radar when using larger files - to create loads of extra overhead when doing many individual and particularly small files.

I can't speak for rclone, but you can easily test (do) basically anything WebDAV related with cURL. Which provides an interesting opportunity both to benchmark against as well as - in some uses cases - use instead.

I whipped up a quick local test folder of 1000 files 60 bytes each:

```
#!/bin/bash

for i in {0001..1000}
do
  echo "some some some some some some some some some some some text" > "file_${i}.txt"
done
```

I then used the following webdav clients to compare:

* rclone
* cURL
  -`time curl -Z --parallel-max 8 -u USERNAME:PASSWORD -T "file_[0001-1000].txt" "http://nc-test.local:3680/remote.php/dav/files/USERNAME/curl_multi_test/"`
* Cyberduck
* Windows 10 (natively supports webdav as a network location including drive mapping)

Results (first two executed via unix `time` command; balance based on wall clock observation cross-verified with log files):

* Rclone: 7 minutes 41 seconds
* cURL: 2 minutes 20 seconds
* Cyberduck: 12 seconds **(!!!)**
* Windows 10: 4 minutes 45 seconds
* WinSCP: 26 minutes (ouch)

Looking at the traces there are some immediately different behaviors just in the requests:

* Rclone does a MKCOL on the parent folder (why?) for every file uploaded then does a PROPFIND on each uploaded file immediately after upload.
* cURL and Cyberduck appear more similar in that they stick to PUTs only
* Cyberduck also looks like it does additional optimizations related to authentication and cookies in every single PUT - and I'm not sure what else. It's certainly worth digging in to if other clients can learn from it! I suspect the auth/cookie stuff was the biggest win and good parallel upload management, but I'd have to poke around more
* I didn't dig more into Windows
* I didn't dig more into WinSCP

For fun I also did a cURL run without using parallel mode (-Z). It took about 8 minutes in that scenario (so similar to rclone), but that was also without causing a serious CPU load on the server-side so still probably preferably over rclone today (if useable in your use case).

WebDAV is a protocol *highly* sensitive to client-side bits no matter how reasonable the server is.

Rclone both wasn't the slowest, but it appeared to have the highest impact CPU-wise on the server-side. For rclone I messed with numerous parameters (along with `--transfer` variations) and results all came up similar. I even discovered the upcoming v1.63 beta has one parameter I was really excited would make difference (`--webdav-pacer-min-sleep 1ms`). Alas, it didn't for me but maybe I misused it.

A broader benchmark of the webdav clients out there is probably a valid bit of work to help nudge some of these implementations forward (even within the confines of the WebDAV protocol itself).

As an aside: Depending on your needs, rclone may be drastic overkill for uploads. cURL might be sufficient!

Some interesting follow-up questions:

* Why is Cyberduck so flipping fast?
* What can be done to help rclone speed up their webdav backend (generally and/or with regard to NC)?
* What can the NC community do to nudge 3rd-party WebDAV clients forward?
  - My initial list: benchmarks of clearly documented scenarios, digging through debug logs and packet traces to assess differences, submitting bug reports/enhancement requests (and PRs where applicable)

**Comment by joshtrichards** [comment]
A further follow-up: I scripted up a bulk upload implementation of the same test that using cURL that uses Nextcloud's Bulk Upload API (designed specifically for small files: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/bulkupload.html) that was added a year or so back and it cuts things down more than half (to under a minute versus the 2m20s number above not using the bulk upload API).

I also did some testing with davfs2 and it takes ~17m (though the user experience on the client-side makes it appear instant because it pushes the uploads into the background -- i.e. they don't really show up on the server until 17m later).

Obviously massive variation among WebDAV clients.

While there may be opportunities do further enhancements on the server side, the bigger area of opportunity appears to be in getting WebDAV client implementers to optimize things a bit more on their end.

**Comment by 7ritn** [comment]
I also performed some tests with the 1000 files and here are my numbers:
Curl: 2:59
rclone: 8:02
cyberduck (Windows): 0:17
duck.sh (Linux): 1:36

It's really astonishing how fast cyberduck is. curl is naturally faster than rclone since it uploads files no matter if the file already exists on the server or not, while rclone is a backup and sync tool. The reason why I even want to use rclone is because the official Nextcloud client also deletes local files, when they are deleted on the cloud, making it as a backup tool unusable.

With the bulk upload, a client like rclone would first need to check which files are already present on the Nextcloud and then only upload those which are new/newer.

**Comment by joshtrichards** [comment]
>  curl is naturally faster than rclone since it uploads files no matter if the file already exists on the server or not, while rclone is a backup and sync tool.

That's part of the reason perhaps, but I'm not convinced it's the only significant reason. I tried things like `--no-check-dest` in my earlier quick and dirty testing and didn't see much difference IIRC.

It ends up being faster to send the file than check for it first in these situations, hah.

> The reason why I even want to use rclone is because the official Nextcloud client also deletes local files, when they are deleted on the cloud, making it as a backup tool unusable.

Yes, the client is a sync app first and foremost.

> With the bulk upload, a client like rclone would first need to check which files are already present on the Nextcloud and then only upload those which are new/newer.

Yeah rclone would need specific support for this functionality. They already have some other Nextcloud specific stuff so maybe they'd accept a PR if someone gets around to implementing it for rclone in a clean manner.

**Comment by coh7eiqu8thaBu** [comment]
Hello,
I got a very similar bug, with windows desktop sync client. It beagin sync, and sudenly CPU loop and dead lock on windows client. the only think is to kill nextcloud client.
Why is similar ? because I got this message : 
`{"reqId":"innhfU5I2sNXURl4ieAq","level":3,"time":"2023-05-01T18:58:08+00:00","remoteAddr":"2a01:e0a:c21:b63:0:4:1:9799","user":"***hidden data***","app":"webdav","method":"POST","url":"/remote.php/dav/bulk","message":"Unknown error while seeking content","userAgent":"Mozilla/5.0 (Windows) mirall/3.8.1stable-Win64 (build 20230419) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.6.1","exception":{"Exception":"Sabre\\DAV\\Exception","Message":"Unknown error while seeking content","Code":500,"Trace":[{"file":"/home/www/***hidden data***/htdocs/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php","line":129,"function":"isAt","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/apps/dav/lib/BulkUpload/BulkUploadPlugin.php","line":71,"function":"isAtLastBoundary","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPost","class":"OCA\\DAV\\BulkUpload\\BulkUploadPlugin","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/home/www/***hidden data***/htdocs/nextcloud/remote.php","line":172,"args":["/home/www/***hidden data***/htdocs/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/www/***hidden data***/htdocs/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php","Line":111,"message":"Unknown error while seeking content","exception":{},"CustomMessage":"Unknown error while seeking content"}}`
and Apacha log got a 408 error.
With the linux client, i didn't see the same lock. I try client 3.7, 3.8 and 3.8.1 with the same dead lock

**Comment by joshtrichards** [comment]
Closing this since there's not much we can do on our side. This is a matter for rclone.

Our sync clients all use WebDAV as well, so third party tools can connect in exactly the same way to Server if they so choose.
