### ISSUE TITLE
[Bug]: Base table or view not found: 1146 Table 'nextcloud1.oc_users' doesn't exist

### ISSUE THREAD

**Issue by W-Cu** [nextcloud/server#38244]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/45815031/b6d68700-70c3-4720-8153-502b1f70a8e8)

### Steps to reproduce

1.install
2.
3.

### Expected behavior

while install this ，it noticed that   “” Table 'nextcloud1.oc_users' doesn't exist“”

### Installation method

Other Community project

### Nextcloud Server version

24

### Operating system

None

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
install
```

**Comment by joshtrichards** [comment]
This looks like an installation issue rather than a bug.

I suggest you post about your situation on the [community help forum](https://help.nextcloud.com).

Also:

* Please make sure you're using a currently maintained release (v25 or v26)
* Verify your environment meets [the requirements for running Nextcloud](https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html#). It looks like you may be trying to install directly onto Windows. You may find a different installation approach of interest, such as [Nextcloud All-in-One on Windows 10 & 11](https://nextcloud.com/blog/your-guide-to-the-nextcloud-all-in-one-on-windows-10-11/).
