### ISSUE TITLE
Wanted: Multiple URLs for accessing same archive (for app)

### ISSUE THREAD

**Issue by evilantishad0w** [nextcloud/server#38326]
**Is your feature request related to a problem? Please describe.**
If I access my archive via my private network URL (or direct IP) I can't readily share links to content with others, since the URLs generated aren't for public access.  Alternatively, if I access my archive via my public URL, the hairpinning on my network results in really poor upload/download performance.  (I also wasn't able to access it at all until I got the hairpinning working.)

**Describe the solution you'd like**
I'd like to be able to specify multiple URLs for the archive, and be able to mark one as public access, and mark others for preferred local access (or for fallback).

**Describe alternatives you've considered**
Considered monkeying with the DNS to have internal access always passed to the server running Nextcloud but that would mess with access to other internal services on other servers that I also need to access via external URL.

**Additional context**
n/a

**Comment by joshtrichards** [comment]
Just tossing an idea out there.

Are you already running a caching DNS resolver internally? This is common in a SOHO, for example, since many Internet routers include this functionality by default. If so, it's usually possible to add simple static DNS entries there that only apply internally.

* EXTERNAL authoritative DNS (as-is): `nc.domain.com` --> your_external_nc_ip
* INTERNAL DNS override on your border router (often already running a caching DNS resolver in many environments): `nc.domain.com` -->your_internal_nc_server_ip

As long as you use a dedicated hostname (`nc.whatever.com`) for your NC instance it doesn't matter if you're sharing the external/internal IP address with other services/servers since they'll either not use that NC-specific hostname and/or have their own hostnames. The latter of which you'll have discretion over pointing at either your internal or external IPs so you won't be forced to route all internal services the same way.

Might find some other ideas over at the [Nextcloud Community Forum](https://help.nextcloud.com). This is a fairly common scenario.
