### ISSUE TITLE
[Bug]: Nextcloud server creates files as read only

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/server#38594]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When ever I create a file or folder via a client (e.g. Laptop) that syncs (via NC client app) to the server, the server permissions are read only and consequently those files/folders cannot be moved.

### Steps to reproduce

1. Create new file on Macbook or Windows Laptop 
2. Installed NC client will sync to NC server
3. Try to move newly created folder
4. Error - file cannot be moved
5. Only logging into the NC server and making Chmod 777 on the new folder will allow proper processing in the NC client app

### Expected behavior

Server creates files/folders as RW and not R only
File/Folder can be moved from NC client

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
CLI complains about wrong PHP version (7.4.33) although I have correct 8.0 running
```

### List of activated Apps

```shell
CLI complains about wrong PHP version (7.4.33) although I have correct 8.0 running
```

### Nextcloud Logs

```shell
no entry on that date
```

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by joshtrichards** [comment]
@MarcS1975 There's virtually no way that's the current Community Docker image if you're getting a such a weird PHP version at the command-line.

```
www-data@492f51535795:~/html$ php -v
PHP 8.2.6 (cli) (built: May 23 2023 09:42:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.6, Copyright (c), by Zend Technologies
```

So, yeah, let's take the discussion over to the forum (https://help.nextcloud.com), and get this figured out. 🦾

**Comment by MarcS1975** [comment]
configuration report
`Warning: Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
The current PHP memory limit is below the recommended value of 512MB.
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.9.180:8585",
            "cloud3.uk-cra.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "http:\/\/192.168.9.180:8585",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "filelocking.ttl": 3600,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2
    }
}
`

**Comment by MarcS1975** [comment]
`Warning: Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
The current PHP memory limit is below the recommended value of 512MB.
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.9.180:8585",
            "cloud3.uk-cra.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "http:\/\/192.168.9.180:8585",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "filelocking.ttl": 3600,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2
    }
}
`

**Comment by MarcS1975** [comment]
So am I logging the same issue again there..from scratch?

**Comment by joshtrichards** [comment]
All I'm saying this isn't a reproducible bug in the server component. At best, it would be one in the community-maintained docker image (which has it's own repository/process for bug reports/etc). *But* that's also not the case, for the record. If this were a bug I'd have like ten of my Docker-based NC stacks not functioning at the moment and this Issue could have like 1000 comments on it from other NC users experiencing the same bug. :-)

Given you other recent issue (#38353) my suspicion is you're running a customized image (which is fine) and something from that is creating these issues for you. The output I provided above is literally from the same image you're supposedly running and it's not matching yours so something is very wrong/different with what you've got running. My wild guess is you inadvertently installed `php` via `apt` (perhaps while trying to add smbclient to it or something) in your image. Since that image doesn't use the `apt` provided PHP installation these days, that situation would negate the entire image's configuration (a number of things will break because it no longer has the PHP config adjustments documented in the NC admin manual for one).

This is going to require - if you want help - digging into your Docker Compose file and Dockerfile (and any manually steps you may have initiated too).

In any case, it's not a Nextcloud server bug that a  Nextcloud *core developer* will need to be involved in resolving (which is what this repository is for). The help forum is the channel for configuration and technical support matters (well, unless one has an enterprise arrangement for support with Nextcloud Gmbh).

For the record, I'm just a community member like - I'm presuming- you are. I'm not paid or anything. Just trying to keep this repository clear of things that don't belong in it so the developers can focus on the work they need to do. Every single Issue and comment here goes to the devs. They don't need to see us troubleshooting whatever this issue is that is not going to require a code fix on the Nextcloud side of things. Make sense?
