### ISSUE TITLE
Enable/disable user over OCS behaves wrong

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3890]
* fire curl according to documentation:

```
curl -u admin:password http://example.org/ocs/v1.php/cloud/users/abc/disable -i -X PUT -H "OCS-APIRequest:true"
```

this returns a 200 without body and doesn't disable the user:

```
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: text/xml; charset=UTF-8


```

But sending it with ` -d key="disable" -d value="true"`

It returns the correct body and also disables the user:

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

cc @schiessle @rullzer 

ref https://github.com/nextcloud/documentation/pull/389

**Comment by nickvergessen** [comment]
The problem is it reaches:
https://github.com/nextcloud/server/blob/8626ccab1c8344a5e2c392a0c26da42061e70332/lib/private/AppFramework/Http/Request.php#L407-L414
> "put" can only be accessed once if not
application/x-www-form-urlencoded or application/json.

That's automatically done by curl when specifying `-d value`. You can also add ` -H "Content-Type: application/json"` and the request will work.
The problem is, that without this the userId is null ... over.

Adding
```php
&& $this->getHeader('OCS-APIRequest') === null
```
To the condition helps. Not sure if it breaks something.

Let's ask @LukasReschke as request expert.

**Comment by ds4a** [comment]
@nickvergessen thanks for that explanation. I've walked with that and so now understand that the endpoint is just expecting any array to be presented to it.
So this works as expected:
curl -v -X PUT -H "OCS-APIRequest:true" -d "true" http://user:secret@local.nextcloud/ocs/v1.php/cloud/users/{userid}/disable
as does
curl -v -X PUT -H "OCS-APIRequest:true" -d "1" http://user:secret@local.nextcloud/ocs/v1.php/cloud/users/{userid}/disable
or
 curl -v -X PUT -H "OCS-APIRequest:true" -d null http://user:secret@local.nextcloud/ocs/v1.php/cloud/users/{userid}/disable
