### ISSUE TITLE
S3 Storage: Save files in a folder for each user

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/server#38967]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Nextcloud with S3 Storage as primary storage save the files for all users on the bucket directly. 
**Describe the solution you'd like**
I want nextcloud to consider that before uploading any data to the bucket. for only first time, create folder for each user in the bucket, then uploading the files related to each user on his own folder in the bucket.
**Describe alternatives you've considered**

**Additional context**
This will give me confidence that if there is any issue in the nextcloud server or any other scenario, at least I can know where the user data is uploaded in the bucket.

**Comment by joshtrichards** [comment]
Hi @FALErwi  - Thanks for participating in the community and contributing your ideas.

Unfortunately, S3 doesn't have folders. It's an entirely flat structure within a bucket. You could, however, accomplish what you're asking if you use S3 as External Storage (rather than Primary Storage) by provisioning a dedicated bucket for each user. But I may not be fully grasping your underlying goal.

Can you elaborate on your use case a bit more - and what's behind your enhancement idea?

**Comment by joshtrichards** [comment]
Yes, some S3 platforms/tools have methods for rendering the appearance of folders in their control panels, but it's just a frontend construct. S3 itself has no awareness of it. It's effectively a prefix appended to things. That's fine.

I was trying to dig a bit deeper to understand your primary concern(s) and what problem(s) would be targeted with this enhancement request. I'm interested in understanding your use case better. Did you have any response to the rest of what I wrote:

> You could, however, accomplish what you're asking if you use S3 as External Storage (rather than Primary Storage) by provisioning a dedicated bucket for each user. But I may not be fully grasping your underlying goal.
>
> Can you elaborate on your use case a bit more - and what's behind your enhancement idea?

To clarify: One of the reasons I asked for further details is that you seem interested in this functionality in terms of a data backup & restore strategy. But even if individual user "folders" (of whatever sort) were implemented for when Object Storage is used in Primary mode , the individual objects (user files) would still not be readily recoverable on their own since all metadata (including filenames) is stored in the NC database. 

It's also why I pushed back a bit - by bringing up External Storage as a potential solution - since in External mode basic metadata (like filenames) is then available to you regardless of the state or availability of Nextcloud's database.

**Comment by EchedeyLR** [comment]
> some S3 platforms/tools have methods

This is compatible with any S3 platform I have been aware and is not just a frontend construct, the rendering is, the long object key is not.

Main S3 implementation which you use (AWS) performs this properly. I don't think this is a proper reason to discard organization.

**Comment by joshtrichards** [comment]
I suspect the real request here is store files in S3 by their filename rather than by their internal `fileId` when using Object Storage as Primary Storage. The folders are sort of incidental.

But I don't like making assumptions, so let's try this a different way...

When NC is configured to use S3 Object Storage in Primary mode all objects in the store show up like this:

`urn:oid:106`
`urn:oid:104`
`urn:oid:3`
etc

(Note the lack of filenames - i.e. no metadata gets stored in S3 when it's used in Primary Storage mode)

Your proposal is that we add a folder suffix:

`johnsmith/urn:oid:106`
`johnsmith/urn:oid:104`
`johnsmith/urn:oid:3`

But I suspect that may not get you what you want. :-)

So I'm *trying* to learn more about what you are seeking so that I may better understand the underlying problem and what - if any - might be the best approach to tackling it. It could well be that I misunderstood your original request. Hence, my follow-up questions. :-)

So:

* Why will utilizing Object Storage via External Storage mode in NC *not* work for your use case? It's clear Primary mode does not work in the desired way for you, but it's less clear why External mode does not (though I have some guesses).
  - https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html#differences-from-external-storage
* Can you elaborate on your use case a bit more - and what's behind your enhancement idea? For example, why are you not requesting filenames be added as well?

**Comment by EchedeyLR** [comment]
I apologize things, I just joined the conversation to clarify that, I was not aware that filenames were also not set and understood that was just all mixed with its correct filenames, but I guess it has some sense these are not saved since object keys could end being the same.

**Comment by joshtrichards** [comment]
> This will give me confidence that if there is any issue in the nextcloud server or any other scenario, at least I can know where the user data is uploaded in the bucket.

@FALErwi: I'm going to close this out in favor of tracking further improvement ideas, discussion, and progress for this area of work in #39765 and #30824 (and to some extent also #34509). I believe these issues overlap/cover your idea for the following reason(s):
 
- Even with "folders", additional metadata would need to be obtainable for recovery
- Presumably whatever mechanism is used to to provide the metadata would inherently include the directory tree

I encourage you subscribe to those issues. Also please feel free to contribute your ideas and feedback to any discussion(s) that take place in them. Also never a bad idea to give one or both of those issues a :+1: to further re-enforce your support for them...

P.S. Speaking as a user/admin, at the moment the best practice I'm aware of for object storage recovery with NC is one or both of the following:

1. Retaining a series of periodic database backups (with the depth dependent on your use case). Along with, of course, backing up the data in the object store itself.
2. Backing up all data stored in Nextcloud.
