### ISSUE TITLE
[feature request] Add ability to show all user's "last seen" date and time on CLI with `occ`

### ISSUE THREAD

**Issue by nooblag** [nextcloud/server#39048]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
A specific user's last seen date and time can be found with `sudo -u www-data php /var/www/nextcloud/occ user:lastseen <uid>` but there is no capability to return this information for *all* users.

**Describe the solution you'd like**
Perhaps all `--all` switch for the `occ` command, to return list of all user's last seen date and time?

**Describe alternatives you've considered**
Have considered shell scripts discussed on [this forum thread](https://help.nextcloud.com/t/get-last-login-date-for-all-users-active-users/114454), but they're cumbersome.

**Additional context**

![Screenshot from 2023-06-29 07-44-06](https://github.com/nextcloud/server/assets/1122344/4fda92fc-395d-4752-a5fe-2e5088c431ec)

**Comment by isdnfan** [comment]
existing occ user:list command with little postprocessing provides exactly such report
```occ user:list --output=json --info| jq '.[] |{(.user_id): .last_seen}'```

https://help.nextcloud.com/t/email-alerts-for-non-logged-users-more-than-30-days/157945/3

**Comment by nooblag** [comment]
Thanks, and sure, can do postprocessing (after installing `jq` by-the-way) or fiddle around with bash scripts to do iterating, but none of this is an ask for that.

I'm more asking for an `--all` switch (like other `occ` commands), to save all this mucking around :smiley:

**Comment by joshtrichards** [comment]
Given `occ` is already a command line tool... doing a little additional "mucking around" using broadly accepted tools (like `jq`) would seem the solution.

I doubt this Issue will get any traction if you wait for someone else to implement it - since there is a perfectly reasonable solution/alternative and there are "a million" other items (that don't have alternatives) that will always take core developer priority. :-)

Both the json output support and `jq` were basically made for this sort of use case.

You're welcome to to implement a built-in `--all` parameter, however, if it's that important to you. Feel free to do so and submit a PR. :-)

**Comment by nooblag** [comment]
Okay cool, [here's a PR](https://github.com/nextcloud/server/pull/39669) for it.
