### ISSUE TITLE
Slow Nextcloud

### ISSUE THREAD

**Issue by emillod** [nextcloud/server#3911]
### Steps to reproduce
1. Try to open cloud(i mean, login page)

### Expected behaviour
I just want to open (in short time) login page.

### Actual behaviour
I need to wait (i check this clock) 5 min for load login page 

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache

**Database:** MySQL

**Nextcloud version:** 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** original source

<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** nextcloud

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Comment by michaelletzgus** [comment]
5 minutes is REALLY long.
Are there any errors in the browser console?

Performance problems are currently discussed here:

NextCloud is unacceptably slow without asset pipelining #2272
Researching/Discussing web UI speed optimization/tweaks #3790 
Deferred script loading v2 #3696

**Comment by emillod** [comment]
I don't have any errors(in this time, for now), but it's weird because i need to wait just for login page. When i log in, everything works ok... 🤔

**Comment by michaelletzgus** [comment]
Hmm... any network timeouts in the browsers network console?

**Comment by MorrisJobke** [comment]
This looks more like a setup problem. So only loading the login page is slow?

If the login page is fast, but after clicking the "Login" button it takes really long, then this could be the brute force protection (if this is the case you can disable it in config.php to verify it). Otherwise please ask in the forums for help: https://help.nextcloud.com

**Comment by DJCrashdummy** [comment]
i can confirm this issue:
it takes not 5 Minutes but nearly 1-2 Minutes to load the login-page (so also after logging out) and to login, but then everything works normal.

- my first thought was, maybe the problem is a general password protection of the superordinate folder i installed via htaccess because they maybe muck up each others turf, but after removing nothing changed.
- i also tried `'auth.bruteforce.protection.enabled' => false,` in the config.php as @MorrisJobke suggested, but also nothing changed.
- but a other instance of nextcloud on the same server works as it should!
- unfortunately i can't tell since when i started to behave so strange...! :-(


differences to my setup from @emillod:

- my server is ubuntu
- i don't use encryption
- no external storage
- and the clients i tested are ubuntu & windows with firefox & midori

**Comment by DJCrashdummy** [comment]
sorry for forgetting the logs! i got multiple times 

```
Warning		core		Login failed: '[the_used_htaccess_user]' (Remote IP: '[my_clients_ip]')
Info		admin_audit	Login attempt: "[the_used_htaccess_user]"
```

...so what is the matter with nextcloud and htaccess password-protection? (within the same protected folder i installed several CMS, and all their login work without any trouble!)

**Comment by emillod** [comment]
@DJCrashdummy 
Thanks for your comment! 
I was thinking about dropping this problem because on help.nextcloud.com i never recieve help.

But maybe when other users have the same problem, dev team do something :D

**Comment by DJCrashdummy** [comment]
@emillod: well... i'm not 100% sure that we suffer the same problem!
- have you tried `'auth.bruteforce.protection.enabled' => false,` in the config.php?
- have you ever used a password protection (via htaccess)?
- what does your logs say?
- when started your nextcloud to behave like this?
- what apps are you using?

please try to answer this questions, because without information nobody can help you/us or fix a eventual bug!

with less information it gets more costlier to help/fix a bug and the less people will try to do so. - maybe that's the reason why you don't get any further assistance...
_it's like telling the mechanic via mail your car goes too slow, he mustn't touch it but tell me what's wrong... in this case nearly no mechanic will guess the right problem or even try to do so and even less repair it._

**Comment by emillod** [comment]
Shiiiiiiiiiiiiit...... After I add 'auth.bruteforce.protection.enabled' => false, to config.php, Nextcloud works OK ! :D 
@DJCrashdummy **You made my day**!!!! Thanks :)

**Comment by MorrisJobke** [comment]
@emillod that should've not be disabled. If this is needed then your configuration is not correct. It seems that the proxy in front of the Webserver doesn't properly forward the clients ip

**Comment by emillod** [comment]
I know, but this is just my private Nextcloud in my Local Home network

**Comment by MorrisJobke** [comment]
> I know, but this is just my private Nextcloud in my Local Home network

Totally up to you but this protects from attacks where people try a ton of passwords.

**Comment by emillod** [comment]
@MorrisJobke  thanks for advice.
Is there any other way to increase security and still have fast access to Login page? 😄

**Comment by MorrisJobke** [comment]
> Is there any other way to increase security and still have fast access to Login page? 😄

Configure your proxy correctly to propagate the client IP addresses via HTTP headers. Long answer short: no.
