### ISSUE TITLE
🔎 Advanced search

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#39162]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The current unified search dialog in the top right is quite small and compact. 

**Describe the solution you'd like**
For the powerful things it supports, it would make more sense to have a bit more ways of filtering. E.g. having a left sidebar with filtering which app to focus on, or some detailed selections on owner of file, or date range, or size.

Edit by @sorbaugh (Last check: 04-09-2023): Since the requirements have shifted somewhat over the course of the discussion (and will likely continue to do so), here is a breakdown of the current state in tasks to minimize confusion. I will make an effort to keep this up to date:

Mockup (original comment -> https://github.com/nextcloud/server/issues/39162#issuecomment-1651037351) 
<img width="736" alt="Bildschirmfoto 2023-09-04 um 13 50 04" src="https://github.com/sorbaugh/example1/assets/62374139/8f61efb8-0a57-4a33-b305-1e3c08b8c574">

Frontend Task breakdown:

- [ ] #40238
- [ ] #40239
- [ ] #40240
- [ ] #40237

Backend Task breakdown:
- [ ] #40246
- [ ] #40249
- [ ] #40250

---

**Date**
For things like date range, we have to make sure it works across different apps like Files, Calendar, Contacts, Talk, Mail etc with different types of dates, so we need to define which date it is for the relevant type:
- Files: modification date (probably more relevant than creation date)
- Calendar: event date (probably more relevant than creation date) https://github.com/nextcloud/server/issues/41345
- Deck card: due date (probably more relevant than creation date, if it exists)
- Talk: message date
- Mail: message date https://github.com/nextcloud/mail/issues/8864
- Contacts: ? birthday
- General fallback would be "Modified date"
- etc. …

**People**
The person dropdown could pick from what the "People menu" in the top right also lists, which is both Nextcloud accounts and Contacts. This would then e.g. for Mail also cover the "Recently contacted" address book which is nice.

- Files: owners and sharees
- Calendar: participants https://github.com/nextcloud/server/issues/41345
- Deck card: assignee
- Talk: message poster and/or person replied to
- Mail: sender and recipients https://github.com/nextcloud/mail/issues/8864
- Contacts: the contact itself, possibly manager also
- General fallback would be sharing

We need mockups for this @nextcloud/designers :)

**Comment by schiessle** [comment]
Just as a reference, this is how the search view of the fulltext search looks:



![Image](https://github.com/nextcloud/server/assets/1589737/c09492d2-37fb-47dc-bf1d-d50f883c0d81)

It allows you already to filter between Deck boards, files and file extensions. I think it make sense to have one advanced search in the future which does also full text search if enabled. Maybe even as a option/checkbox to decide if the user wants to search for filenames/folders only, for content only or for both.

**Comment by marcoambrosini** [comment]
I did some research and interviews on this and I think that while there's room for UX improvements in the global search, we should not make it more complex than it already is. A few reasons: 

* **Different searchable items require different types of filters**, so it would be better to have a tailor-made solution for each app instead of trying to make something that works for every searchable item in the same UI.
For example, if I'm looking for a contact I might be interested in knowing whether it belongs to a group, while if I'm looking for a pdf I would want to filter by file type. I think that trying to reconcile the complexity that will emerge from all use-cases in the same UI will end up being confusing.

* Users generally report that **if they know what they're looking for, they search it from within the app.** 

* This also seems to be the trend in our competitors' solutions: **global searches are simple** and provide quick and relevant results, **in-app searches allow fine-tuning** and more complex searches.

---
While conducting interviews I found out that **most people felt frustrated with global search and never or rarely use it**. They resort to syncing their files and emails to their OS and search there. 

A few recurring themes: 

* **Users don't trust the search**: the lack of full-text search and fuzzy search renders the functionality unreliable and frustrating for most users because it doesn't return the expected amount of results.
One user compared their local OS search with the global search with the same keyword. The local OS search yielded 40 results while the global search only 2;

* **Users are unhappy with the performance**. It takes a long time to get the results.

* Users think that the search results are **not relevant to them**, and wish the search was "smarter". 

* **The interface is "messy"**. 
---

**So it seems that the feature is there but it's not very useful to people. To change this I think we need to tackle the issue from 2 angles.**

1) **Layout.** there are a lot of little improvements that would make the search experience much better. A few ideas: 
  - Better display of the search filters that are already there (not in a menu);
- Different components for different types of results. Now all the search result components are 70px tall and not many of them fit in the view;
- **Modal or fullscreen view** to accomodate more results;
- **Lazy loading** while scrolling instead of having to click on "More results" if a filter is applied;
- **Relevance:** Think about a set of rules on what to prioritise for each user? For example one user complained that a lot of results coming from shares took priority over their own files.
- **Previews** if technically possible?  (this emerged from a user that values the previews in their OS search and I think it'd be useful to have);
On top of global search improvements, we should also take a step back and open a meta issue on search in which we track what's going on in each app and bring it all up to par. What do you think @nextcloud/designers? 

2) **Reliability and performance.**  
For the full-text and fuzziness side of things which is a major issue, is that something we tackle @AndyScherzinger? Looping in @juliushaertl too as he had some technical advice about how indexing could be implemented. From a UX perspective I think that this is something that most users would expect and it'd be super useful.

**Comment by AndyScherzinger** [comment]
> For the full-text and fuzziness side of things which is a major issue, is that something we tackle @AndyScherzinger?

No. Full-text search is something we have already given the FTS app is actually installed and set up (usually not the case since it requires further components, i.e. elastic search). Fuzzy search when don't have at all and currently isn't on the roadmap.

**Comment by marcoambrosini** [comment]
Here's a proposal on the layout changes mentioned above and incorporating some feedback from the design team.

<img width="1643" alt="Screenshot 2023-07-14 at 12 43 23" src="https://github.com/nextcloud/server/assets/26852655/cd324f70-3692-4774-8a8c-10b2be6755a3">

**Comment by juliushaertl** [comment]
Looks very nice, one small comment it might be good to have a reset filter to quickly get back to all results.

Has there been any thought around how this would impact the search icon in the to right? Shall it just open the modal then or is the modal in addition to the existing popover?

**Comment by marcoambrosini** [comment]
> one small comment it might be good to have a reset filter to quickly get back to all results.

I thought this could be in the menu. What do you think @juliushaertl?

> Shall it just open the modal

Yes :)

**Comment by juliushaertl** [comment]
> I thought this could be in the menu. What do you think @juliushaertl?

I think a quick reset option outside might be nice, at least when more than one filter option is selected (to reduce the amount of clicks needed, but either way would be fine I guess.

**Comment by gennaios** [comment]
I think full screen results, perhaps from some link in the box that says show all, is ideal. Some have thousands of files or many contacts. 

As for search performance, all supported databases have built-in FTS. Unlike the current FTS plugins, one specifies specific columns with which to create an FTS index. All large databases use such or something external like Sphinx. Such would offer fuzzy search, allow terms to be specified in any order, handle diacritics, etc. Performance would then be solved and there would be no need for lazy loading. 

Large databases do not use like queries. They all use some form of FTS. As NC supports multiple databases, it merely takes more work to support them all.

**Comment by AndyScherzinger** [comment]
Mockup looks nice and provides a first set of options to narrow down the search by limiting the apps to be respected when searching for relevant items.

I discussed the feature with Frank and the initial idea is to basically improve the UI side of search but still base search on what we have offered by the backend as of today. Afaik we already have ways to limit the search scope yet it is hard to discover and the goal would be to raise such scope-limiting capabilities to the UI in a discoverable way.

cc @jancborchardt @marcoambrosini 

@karlitschek what do you think about https://github.com/nextcloud/server/issues/39162#issuecomment-1635223315 as a first step? It would limit the search scope where the first limiting step would then always be the app. This could be a trade off that is okay.

**Comment by jancborchardt** [comment]
@marcoambrosini we talked about this again and since in-app search will likely still be further out, we should ideally have some more filtering in the global search already.

For reference here a screenshot from Google Drive, so we could do the bar of selections like:
- Apps (instead of type)
- People
- Date (cause it’s not always modified)
- Title only (for fulltext yes/no)
- Maybe something else special that we can think about?

![image](https://github.com/nextcloud/server/assets/925062/66e35f81-18a0-42c0-855f-9a5e4da15bb7)

**Comment by florom** [comment]
Hi Devs, 

I would like to add the downsides of the current Global search here, since I got a link in the [forum](https://help.nextcloud.com/t/global-search-is-unusable-imho/166617/2?u=florom) thanks to jtr.
In priority order.

1. The search Window is to small - I barely see the results even on a big screen
     - Small Window in the side
     - Symbols too big
     - For Example in Files: Filename in next line path (uses too much space) the screen is usually has more width than height.
3. It does not load all results - I always have to load more results this is very very uncomfortable
4. There is no way to sort anything like date, size, format
5. It searches everywhere - usually I want to search the section I am in at the moment (It should first search in the section you are in and then if you like everywhere else.
6. If you search in Files there is no recursive Search (only the level you are in which is usually not where you find the file anyway)

If you place more buttons in this tiny window it will even get worse IMHO. The presentation here is 250% bigger then it will be implemented. Even in the mockup only 4! results (totall 8) are visible. Usually it is not so clear what filename it was so there should be at least 20 results. @jancborchardt @AndyScherzinger 

In my opinion this should be a a whole new app window (Global Search) and the Search in the menu only considers the current open app.

Another thing I do not understand is why contacts have an additionally search button in the menu bar.
The contacts quick search is amazing and and I see no benefits in having it one-click available when it uses up so much space all the time.

Thanks for reading.

**Comment by marcoambrosini** [comment]
After design call it has been decided that we're going to use multiple selects, some of which with tags. Much like google drive search posted above. Here's the updated mockup. 

![Screenshot 2023-07-26 at 14 34 54](https://github.com/nextcloud/server/assets/26852655/6e4966ed-38ef-4b62-bb3e-fa4cfdad7458)

Shared components used for the filtering: 
- `NcSelect` with multi option and wrapped for "places"
- `NcSelect`  single for "modified" options being (today, this week, this month, this year and custom). Clicking custom should open a small dialog (mockup on the right) that allows us to set the after and before fields. 
- `NcSelect` for one single user at a time for "People", [there's an example of this in the Vue documentation](https://nextcloud-vue-components.netlify.app/#/Components/NcSelect)
- Tertiary `NcButton` for the "Title only" option. This is a stateful button and the `pressed` state can be toggled via prop. 
- To the right we have another tertiary `NcButton` that allows us to clear all filters at once. 

cc @nextcloud/designers for any further comments

**Comment by gennaios** [comment]
An old thread that was closed in favor of this one, as well as several others, has many comments about improvement to search itself. As it seems no one or few reply to such, perhaps somehow the topic is being avoided. Yes I think FTS is the only method. It perhaps merely would take a few weeks per database to figure it out. If someone just said yes we need to figure it out, perhaps others including myself would help.

Any kind of search results showing some limited number out of total, isn't it really best and perhaps only truly useful in such a case to show the most relevant, and then show others with options to sort by for example name, city, date created/modified, etc.?

**Comment by jancborchardt** [comment]
@Altahrim @marcoambrosini any help needed at this stage, or what is the status? I can’t see a linked pull request

**Comment by AndyScherzinger** [comment]
@jancborchardt there is none, also had to be dropped for 27.1

Research state is: that i.e. `in:files` is supported i.e. to limit it to just search in files but currently there is no other limiting/filtering criteria present for unified search to limit it's search scope for files. so anything we want would need to be build (hence v28).

Si for example for files the statement is that anything we can do in dav search should be relatively easy to be added to search (for files)

**Comment by jancborchardt** [comment]
@marcoambrosini this is now in for 28, so we can proceed. :) The direction with the mockup is great, only can you combine both the mockups made, so basically to the latest one add the following:
- [ ] "Places" dropdown should be converted to show at least the first few apps as chips, then a 3-dot menu, otherwise it is not as discoverable
- [ ] The top mockup has the additional buttons like "Search in Talk", "Search in Contacts", these would be good to add back as a jumping off point to the in-app-searches. The "Load more results" should continue to behave like now as loading the next few results in place.

**Comment by marcoambrosini** [comment]
> at least the first few apps as chips

@jancborchardt how many? The original mockup did show a few and as you can see there's not much space for it with the fixed multi-selects in place. Should we make this dialog bigger or fullscreen to accommodate all this?

**Comment by florom** [comment]
Hi all,

I see that nextcloud tends to quote goole, microsoft or other big players for design purpose.
like:

> much like google drive search posted above. Here's the updated mockup.

Keep in mind that these are big player who want and can force their ideology onto users.
So if they design something it is not necessarly the best for the users but represents their perspective of the world and how users should behave or use something. The rest of the arguments which could follow I am sure you can imagine yourself.

Thanks.

**Comment by jancborchardt** [comment]
@marcoambrosini 3 would already be enough for example, to tease the feature. Fullscreening the modal is definitely too much though. Is that possible ti accomodate?

@florom it's mostly because they a) spend a bunch of money on usability testing and user research and b) are widely used and known systems, so yes while we don't need to do everything 100% like them, looking at prior art is always a great first step.

**Comment by Spartachetto** [comment]
Please, do allow the possibility to see the search results in the main window.

This would contribute to solve two problems cited previously:

1. >     The search Window is to small - I barely see the results even on a big screen
2. >     Previews 

Having a button that says "_open in a new window_" or "_open in the main window_" would contribute to solve this. 
In addition one could examine deeply each search result by opening it in a new tab.

**Comment by marcoambrosini** [comment]
Here's how it would look in a size large modal dialog

<img width="763" alt="Screenshot 2023-09-12 at 08 47 56" src="https://github.com/nextcloud/server/assets/26852655/742b2ad6-0777-4488-9016-4f41b4ef4df2">

**Comment by florom** [comment]
Hi @marcoambrosini ,

i still think: "Load all results" is necessary.

Thanks.

**Comment by marcoambrosini** [comment]
Hi @florom, hopefully, this is something we can add soon to the app search so that if you need all results, you'd just click "search in files" and you'd be shown all the results there.

**Comment by sorbaugh** [comment]
> Here's how it would look in a size large modal dialog
> 
> <img alt="Screenshot 2023-09-12 at 08 47 56" width="763" src="https://user-images.githubusercontent.com/26852655/267172207-742b2ad6-0777-4488-9016-4f41b4ef4df2.png">

Maybe it's just me but something is a unclear to me about the App filters. I assume the app filters like Files and Talk are meant to work like "on/off" switches (as suggested by the grayed out Mail-App filter), but the "x" on the right also suggests  that this would remove the filter completely from the interface. If this is the case, where can this be activated again?

And if it is an on/off switch, wouldn't it be better to handle it like the "Title only" filter?

**Comment by marcoambrosini** [comment]
You're right indeed @sorbaugh, the 'X' button shouldn't be on the chip, just like in the first mockup.
As far as styling goes, you're right that now that we have that button there'd be an inconsistence in styling. What do you think about this @jancborchardt should we increase the size of the apps toggles to regular 44px tall buttons?

**Comment by jancborchardt** [comment]
@marcoambrosini yeah, if the apps toggles are 44px they also look less strange in comparison to the inputs. :)

Can you update the mockup to have the latest state of everything in one?

**Comment by marcoambrosini** [comment]
here it goes

<img width="556" alt="Screenshot 2023-10-03 at 18 27 09" src="https://github.com/nextcloud/server/assets/26852655/dc82bda4-b503-419b-b7e1-bd85d8e35681">

**Comment by marcoambrosini** [comment]
Design review: 3 dot menu instead of mail and 1 more item 
typo in modified

**Comment by ChristophWurst** [comment]
> people

Please clarify how search will identify people. Nextcloud Files use user IDs, Calendar uses email addresses for participants, Contacts have a UUID, sharing can work with federated cloud ID.

Which data source is used to filter by *People*?

> date range

For Calendar we need to deal with timezones, because events typically have them. Do we limit time ranges to the timezone of the searching user or will there be an option to filter for date ranges in other timezones?

**Comment by sorbaugh** [comment]
Thanks! Updated original comment with latest mockup to avoid confusion.

**Comment by marcoambrosini** [comment]
@jancborchardt On second thought the multi-select cannot be an action menu, just have a look at the amount of places that we have in the global search. The multi-select allows quick search, adding and removing of these. An action menu would complicate things a lot.

@ChristophWurst shouldn't we use all those data sets for their respective categories? For example, if a search yields results both from calendar and files, I think should be able to filter "person" in both datasets. 

> Do we limit time ranges to the timezone of the searching user

I would do this yes.

**Comment by ChristophWurst** [comment]
> if a search yields results both from calendar and files, I think should be able to filter "person" in both datasets.

And how do I identify "person" in code? What data and type does the *Person* dropdown pick from?

**Comment by marcoambrosini** [comment]
@ChristophWurst It should probably be a merge of the datasets you mentioned above. But I don't know exactly how to answer this question as that would be a bit counterintuitive (duplicates, triplicates, etc.). 
Early on I encountered several possible conflicts that will arise from using a fixed set of filters with so many different search providers. And many more that I haven't thought about could pop up since any app can register a provider. That's why in the original proposal I argued for a simpler solution for global search and more complex filtering only in-app ([here](https://github.com/nextcloud/server/issues/39162#issuecomment-1631801315) and [here](https://github.com/nextcloud/server/issues/39162#issuecomment-1635223315)).
@jancborchardt what would you do here? Could we go back to a simpler version for this?

**Comment by Altahrim** [comment]
In my early work for backend, I imagined things as it:
 - each application is able to declare its supported filters (and can declare specific filters). For that, I assume we'll have to keep `filter: value` syntax for advanced users. For example: `john work_as:engineer work_at:nextcloud` (just an example, I don't know if we can do that).
 - if an application don't recognize a filter, its response will be empty. With previous request, there is no need `files` care about it
 - if an application register a filter `person`, it will be linked to a specific type (user, group, circle…)

I think we'll map each filter from the mockup to a well known filter in backend that each application can implement.

**Comment by jancborchardt** [comment]
It is defined in the original post under "For people:" what that means for the individual providers/apps (same as it is for date). What is the specific confusion here? @ChristophWurst @marcoambrosini 

Also cc @AndyScherzinger for info since we specified this in a meeting a while ago so it is clearer.

**Comment by ChristophWurst** [comment]
What data and type does the Person dropdown pick from? Does it list Nextcloud users?

**Comment by jancborchardt** [comment]
The person dropdown could pick from what the "People menu" in the top right also lists, which as far as I know is both Nextcloud users and Contacts – right?

This would then e.g. for Mail also cover the "Recently contacted" address book which is nice.

**Comment by nimishavijay** [comment]
2 points discussed with @sorbaugh in Files planning:

- [ ] if multiple apps are selected, aggregate the filters shown (eg. if `A (filter 1, filter 2, filter 3)` and `B (filter 2, filter 3, filter 4)` are selected, show `filter 1, filter 2, filter 3, filter 4`) so that you are able to adjust without unselecting apps. Follow-up/nice-to-have: change the filter labels if it's not clear which app a filter belongs to.
- [ ] Allow selecting multiple items in the "Places" filter 

cc @marcoambrosini

**Comment by marcoambrosini** [comment]
@nimishavijay I don't understand point 1. Point 2 would already be the case. 

I was thinking about this and I think that how we currently handle places is really unclear (mixing toggles with another element for the same filter). I would just use our select component on its own without the tags/toggles. What do you think @nextcloud/designers @sorbaugh ?
This is the component 

https://github.com/nextcloud/server/assets/26852655/8b0f4188-911e-4094-9b26-c17403fde36a

**Comment by nimishavijay** [comment]
>  I don't understand point 1

It is about aggregating all the filters for the selected apps and not showing only the ones that are common. 

`A (filter 1, filter 2, filter 3)` and `B (filter 2, filter 3, filter 4)` are selected => show `filter 1, filter 2, filter 3, filter 4` and not only `filter 2, filter 3`

> I would just use our select component on its own without the tags/toggles.

This looks good to me as well 👍

**Comment by marcoambrosini** [comment]
Then let's go back [to this design](https://github.com/nextcloud/server/issues/39162#issuecomment-1651037351)?

**Comment by nimishavijay** [comment]
Notes form design review with @jancborchardt @Fenn-CS @sorbaugh @szaimen 

### Overall
* [ ] Heading: "Global search"
* [ ] Close button missing for the modal
* [ ] "Global search" --> "Search term..."

### Filter chips (Files, Talk, etc)
- [ ] style it like NcUserBubble component
- [ ] Border radius pill
- [ ] Background: --color-primary-light or grey
- [ ] Smaller close icon

### Search results
- [ ] should be like NcListItem component
- [ ] remove shadow
- [ ] Show "Search in \[appname\]" only for the apps that have an in-app search. Files doesn't have an in-app search yet, so don't show "Search in Files"
- [ ] App name in "Search in [appname]" should have capital first letter as it is a proper noun ("Search in Talk", "Search in Mail" instead of "Search in talk")

### Places
- [ ] Wording: "Apps and settings"
- [ ] Style should be NcButton
- [ ] Clicking on button opens an NcActionMenu with a list of the available apps, similar to app list in mobile view header bar 

![image](https://github.com/nextcloud/server/assets/52440189/df66c26a-228d-419d-a4ce-ff0344626066)


### People filter
- [ ] Needs label "People"
- [ ] Use component NcSelect with userSelect prop

### Date and time filter
- [ ] NcButton component
- [ ] Button name "Modified"
- [ ] On click, open action menu with predefined date options and a date range picker
- [ ] Use native date picker for date range

![image](https://github.com/nextcloud/server/assets/52440189/f74a885f-f35d-4983-b43b-e70fcb02d6ea)

**Comment by marcoambrosini** [comment]
<img width="439" alt="Screenshot 2023-10-23 at 11 46 48" src="https://github.com/nextcloud/server/assets/26852655/27afbb3a-438c-42f3-a15e-7453c85387a6">

@jancborchardt @nimishavijay  @szaimen can we drop this pattern of selects within small tooltips? It's very clumsy. Everyone uses a dialog here.
