### ISSUE TITLE
Don't raise integrity issues when deleting by-default skeleton files

### ISSUE THREAD

**Issue by Zulgrib** [nextcloud/server#39314]
When skeleton files are deleted to save space on new profiles (and because the file may not be in the appropriate language anyway), the integrity checker raise an issue.

The skeleton directory should be excluded in scan and raise an issue only if dangerous file format exists there, like binaries or script files.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/a756600b915dcd9bab5338a610ade97d667edfe8/config/config.sample.php#L243-L253

Did you try skeletondirectory?

**Comment by joshtrichards** [comment]
Indeed.

> You may distribute a set of default files and folders to all users by placing them in directory that is readable by the webserver user. **This allows you to overwrite the files that are shipped by default with Nextcloud in `core/skeleton.`**

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/default_files_configuration.html

`'skeletondirectory' => '',`

For no skeleton files to be copied.

Or a variation pointed at your own custom folder (which would be outside the scope of the integrity checker).

Closing this issue since I think this enhancement is addressed with existing functionality. And it's also documented already. 

Feel free to follow-up if you disagree or feel we misunderstood your use case!
