### ISSUE TITLE
New app menu makes external links very hard to use

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3959]
I just wonder if we can do anything against this.
Yes people should use different icons, but maybe we can also do something else for this special app?

> ![dateien_-_nextcloud_-_2017-03-20_12 37 43](https://cloud.githubusercontent.com/assets/213943/24098331/40393456-0d6a-11e7-85e2-d6914f85898c.png)

@nextcloud/theming @juliushaertl

**Comment by juliushaertl** [comment]
We could show some icons like the avatar fallback with the first character of the external site name instead of using the external icon. Then the users would at least be able to differentiate between different sites. 

Input from @nextcloud/designers  would be good as well.

**Comment by MorrisJobke** [comment]
> We could show some icons like the avatar fallback with the first character of the external site name instead of using the external icon. Then the users would at least be able to differentiate between different sites.

Sounds nice, but I would do then the avatars in monochrome to not distract too much. So basically a white circle with a transparent letter in .7 opacity or so.

**Comment by jancborchardt** [comment]
In the past I thought it would be great to add favicons here. That of course looks bad because they are colored on a colored header. Gladly Apple pushed the `link rel="mask-icon"` which is used in Safari for pinned pages. We support it with Nextcloud and so do many other pages. 

So that’s something we could do. However I heard that mostly organizations embed sites within their system there, hence having the same favicon. For that then a monochrome version of the avatar fallback might be best.

Another option: Be able to choose from a set of icons – like all the ones we have in `img/actions` (of course filtering out duplicates with -white etc)

**Comment by nickvergessen** [comment]
You can already upload icons yourself. But yeah I thought there might be an easier way.

Any strong opinion on the "move every navigation which is lower then 80 into the dropdown?

**Comment by jancborchardt** [comment]
@juliushaertl what do you think about
> move every navigation which is lower then 80 into the dropdown

**Comment by MorrisJobke** [comment]
Too late for 12.

**Comment by jancborchardt** [comment]
@juliushaertl @nickvergessen wasn't this done already? I faintly remember something.

**Comment by nickvergessen** [comment]
Well we at least show the page name now directly on hover with the tooltip, and not only after 5sec waiting. So "fine by me"
