### ISSUE TITLE
File names with colons

### ISSUE THREAD

**Issue by jevonlongdell** [nextcloud/server#3996]
My nextcloud instalation (ubuntu snap) seems to have problems with filenames that contains colons. In the logs it said "internal server error" whenever it tried to sync these. I added "*:*" to my ignore list and the problem has gone away.

**Comment by MariusBluem** [comment]
Thank you for your report. Since this seems to be an issue with the Nextcloud snap appliance, please open an issue over here: https://github.com/nextcloud/nextcloud-snap 👊

I've tested syncing a file called `he:llo.md` with the iOS client. Worked on a non-snap instance. So it seems to be related to this appliance and its configuration 😉
