### ISSUE TITLE
CIFS External Storage doesn't respect file permissions

### ISSUE THREAD

**Issue by stunivention** [nextcloud/server#4009]
I configured a CIFS external storage to access an existing file share provided by Samba. Users can access the share with their login credentials. All tests have been done using UCS 4.1 and nextcloud 11.0.1.

The external storage shows all files a user has read access and allows the user to change files or to upload new ones. As long as the user has full read and write access to the files and directories in the external storage everything works fine. But the usage is confusing or even wrong if the user has no write permissions:

- changes (i.e. editing a text file) to files without CIFS write permissions are lost
- uploaded files to directories without CIFS write permissions are visible in nextcloud, but not in the CIFS share. The user has the impression everything is fine, but the file is actually not transfered to the external storage.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @blizzz

**Comment by icewind1991** [comment]
@stunivention can you try connecting the the smb share using `smbclient`, running `ls` on such a read only folder and posting the result

**Comment by stunivention** [comment]
@icewind1991 : mhm, it gives me a list of files/directories? What exactly are you looking for?

Example:

```
user@server:~$ smbclient //server/shared-files
Enter DOMAIN\users's password: 
Domain=[DOMAIN] OS=[] Server=[]
smb: \> ls
  .                                   D        0  Fri Mar 17 16:36:23 2017
  ..                                  D        0  Fri Mar 17 16:40:42 2017
  Downloads                           D        0  Thu Aug  4 21:22:57 2016
  audio                               D        0  Wed Mar 29 16:52:40 2017
  video                               D        0  Mon Aug 22 22:38:12 2016
  build                               D        0  Sat Feb  5 19:11:21 2011
  documents                           D        0  Thu Sep  6 20:37:34 2012
  data                                D        0  Tue May 17 20:16:56 2016
  backup                              D        0  Fri Sep 16 22:24:35 2016
  photo                               D        0  Wed Mar 29 17:27:48 2017

		5814216772 blocks of size 1024. 2947236904 blocks available
smb: \> 
```

**Comment by blizzz** [comment]
@icewind1991 ping

**Comment by va1entin** [comment]
I can confirm that this is still an issue with Nextcloud 12.0.5 and External Storage Support plugin version 1.3.0 (tested on UCS 4.2-3).
At least the behaviour in the first test scenario should me change imho.


I tested the following:

Modifying a file without write permission:
- Notification: _Saved_
- Changes are lost

Opening a folder without read or "list folder contents" permission:
- folder is empty, no notification or indication of missing permission

Creating a file in a folder without read or "list folder contents" permission:
- file is created and visible
- Nextcloud tries to open the editor right after, which immediately results in an error pop-up: _Cannot read the file._
- when the folder is re-opened, the file is not visible anymore

Creating a file in a folder without write permission:
- Notification: _Could not create file "test3.txt"_
- seems okay to me. A more detailed notification might be helpful, though.

**Comment by icewind1991** [comment]
Please follow the steps above and run `ls` from `smbclient` in a folder containing read only files or folders.

If the listing for the file is not listed with an `R` then the smb server is not reporting the permissions correctly and there is nothing we can do on the Nextcloud side.

```
foo.txt                             R        0  Tue Jan 23 13:30:08 2018
```

**Comment by va1entin** [comment]
Thanks for the quick reply! 
By read-only I don't mean that the folder itself is set to read-only, but the specific user or group does not have write permission.

In my case the LDAP user that I use in Nextcloud is also used for the Kerberos logins from my Windows client. One of the groups, that this user is in, is denied write permission for this folder, which results in the behaviour explained above.

<pre>smbclient //server/share
smb: \> ls
  .                                   D        0  Tue Feb 13 14:19:40 2018
  ..                                  D        0  Mon Feb 12 14:45:15 2018
  read_only_file.txt                  A        0  Tue Feb 13 14:15:58 2018
  read_only_directory                 D        0  Tue Feb 13 14:18:23 2018

                18548924 blocks of size 1024. 15423348 blocks available
smb: \></pre>

**Comment by va1entin** [comment]
@icewind1991  So if I understand you correctly the plugin only checks if a dir/file is read-only ("R") but does not check the actual permissions?

If that's correct, `smbclient` could be used to gather permissions using `getfacl`: 

To check if a user has write permission in a folder:
<pre>smb: \> getfacl no-write-dir\
# file: \no-write-dir\
# owner: 2013
# group: 5054
user::rwx
user:2013:rwx
group::r-x
group:5054:r-x <- group 5054 is denied write permission. 
Deny takes precedence over allow, so user 2013 is not allowed 
to change this file because he is a member of group 5054
...
</pre>

same goes for files:
<pre>smb: \> getfacl no-write.txt                             
# file: \no-write.txt                                    
# owner: 2013                                       
# group: 5054                                       
user::rwx                                           
user:2013:rwx                                       
group::r-x                                 
group:5054:r-x <- group 5054 is denied write permission. 
Deny takes precedence over allow, so user 2013 is not allowed 
to change this file because he is a member of group 5054
</pre>


To check if the user is allowed to write files to a dir or list the contents of a dir, one could also just try the actual operation with smbclient:

<pre>
smb: \> put local-file no-write-dir\remote-file
NT_STATUS_ACCESS_DENIED opening remote file \no-write-dir\remote-file
</pre>

<pre>smb: \> cd no_read_directory\
smb: \no_read_directory\> ls
NT_STATUS_ACCESS_DENIED listing \no_read_directory\*
</pre>

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
