### ISSUE TITLE
↔️ User-configurable app order

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40241]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Users should have the possibility to modify the order in which apps are listed in the top bar and also to define a "default" app that should always be loaded when a user "starts" Nextcloud. 

**Mockup and comments by @szaimen**
Here -> https://github.com/nextcloud/server/issues/40245#issuecomment-1709999731

Reference to old issue asking for this feature: #39162
Reference to comment defining the requirements:  https://github.com/nextcloud/server/issues/4917#issuecomment-1699025806

* This is a user-setting only, no admin setting
* First sorted app will be default app (if set, it will override the default app config setting)
* This has to be a settings block in "Appearance and accessibility", similar to the sorting in "Artificial Intelligence" or the column sorting in Tables so it is both accessible via mouse and keyboard. No sorting by drag & drop directly in the navigation

<img width="929" alt="Bildschirmfoto 2023-09-04 um 14 45 22" src="https://github.com/sorbaugh/example1/assets/62374139/699f528c-f081-4cfb-a443-7608898b44ca">

Task breakdown:
- [ ] #40245
- [x] #40254
- [ ] #40255
- [x] #40256

**Comment by sorbaugh** [comment]
See Mockup:  https://github.com/nextcloud/server/issues/40245#issuecomment-1709999731

**Comment by ichier** [comment]
this is great news! but i've got one question:
[#4917](https://github.com/nextcloud/server/issues/4917) states that:

> Admins should be able to
>     set an default order for apps
>     set, whether users should be allowed to change the order of the apps

is this the case now?

because this is the only reason i didn't upgrade after 24.
imho it is less important for users to be able to customize, than for admins to set up the environment first to make sense according to the use-case.

most important of course is, that there's no dashboard-fuzz but plain files after login. by default. not per user customization.

the ability for users to customize sure is a nice feature, but 99% won't. its the task of admins to provide a clutter-free work-space with no customization necessary.

**Comment by susnux** [comment]
> most important of course is, that there's no dashboard-fuzz but plain files after login. by default. not per user customization.

This is already possible for quite some time by using the `defaultapps` config options:

https://docs.nextcloud.com/server/27/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=defaultapps#apps

But with Nextcloud 28 this will also be provided in the admin settings UI. Meaning administrators can override the default app(s) which will be shown on login / clicking the logo. (also the default app will be shown on the very left of the menu bar as the first entry).

**Comment by ichier** [comment]
great! (did't know, since i'm sticking at 24. nice! so i guess i'd finally upgrade on 28 \o/)
but how about the default order?
we started our setup with a custom order [files, photos, notes, forms, polls, activity] a change would be irritating an inconvenient.

activity at the end here is crucial for the ux; it's the second most useful feature, while being last you find it best, also it is meta, while everything else is a solid tool. for a different group we've got talk at the end, same reasoning. if i'd use groupware i'd probably default to mail and put files last, in order to make it 2nd most accessible. those examples show, that different orders indeed make sense for different use-cases.
