### ISSUE TITLE
Add `in:users` as a search filter to limit searches to users

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40287]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently when you have large installation in terms of users and you need to search for a user, you can only do that via unified search. This works and filters down the list of users in case you are at `*/settings/users` on your instance. The downside is that this then also trigger searches in all available search providers.

**Describe the solution you'd like**
Provide a app-filter `in:users` that can be added to the search query like it can be done for other apps like files and within the actual user search just remove any occurrence of `in:users` and just search with the rest of the search string (trimmed). Due to the in-filter all search providers will be skipped which is what is the desired behavior.

**Describe alternatives you've considered**
Implement an in-app search in users like present in talk but that would be way more work.

---

This shall be backported down to v25

**Comment by sorbaugh** [comment]
Update. Original solution included a User search result list in the search dialog. However, expected behavior still unclear about what should happen when we click on a user (among other things). So we decided to reduce the scope to the original intent of this issue and just add the SearchProvider to have the in:users filter and revisit adding the search result list and how it should behave with a new issue.
