### ISSUE TITLE
[Bug 27.1 RC3]: File drop shows all files per default

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#40431]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a new File Drop share, the default behavior is that the files are shown.

### Steps to reproduce

1. Share a folder as usual
2. Set File upload

### Expected behavior

The end user should only see an upload button.

### Installation method

Other Community project

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
N/A (reportimg from mobile)
```

### List of activated Apps

```shell
N/A (reportimg from mobile)
```

### Nextcloud Signing status

```shell
N/A (reportimg from mobile)
```

### Nextcloud Logs

```shell
N/A (reportimg from mobile)
```

### Additional info

cc @small1

**Comment by szaimen** [comment]
cc @AndyScherzinger @sorbaugh @Fenn-CS

**Comment by small1** [comment]
Just tested some more.  File drop works as it should when you select it below the share link text.  If you click on customize it might say custom permissions instead of drop folder.

If you change from custom to just file drop.  Custom permission is still there.  It doesn't change to file drop (when inside the customize link view).

This can probably be closed.  But the customize link part needs to eb a bit clearer

**Comment by Fenn-CS** [comment]
So the actual issue here is that, when moving from custom permissions, the file dropped cannot be selected. When clicked the highlight with a grey/ash shows that's active/focused item but when actually selected the highlight is light blue. The select does not happen unless one is coming from a different permission which is not custom.

| Clicked Registered | Click not registered |
| ------------------------  | -------------------------  |
| ![Screenshot from 2023-09-15 11-24-59](https://github.com/nextcloud/server/assets/14317775/27213e12-9848-40a1-b7e4-7560623d2a2b) | ![Screenshot from 2023-09-15 11-25-16](https://github.com/nextcloud/server/assets/14317775/9367a4ea-9e89-45d4-9cde-95483d83487b) |

**Comment by Fenn-CS** [comment]
Thanks for providing more information @small1 a ticket to fix this inconvenience is now on its way and it should disappear in the next release :)
