### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bentpurist** [nextcloud/server#40728]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cannot delete files from the Files App.

### Steps to reproduce

1. Open the Files app.
2. Choose New document (This creates an OnlyOffice document called "New Document" in the list of folders and files and opens the document in Only Office. 
3. Open the Files app again. 
4. Locate the New Document file in the list.
5. Check the box to select the document.
6. Click on the three dots on the right side of the file in the list and select Delete.
7. An error message appears saying the file could not be deleted. There are no more details in the message.

### Expected behavior

The file to be deleted.
<img width="841" alt="Screenshot 2023-09-29 213213" src="https://github.com/nextcloud/server/assets/110345920/8ebac5ef-9505-4bff-8d3f-d5569510d890">

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @bentpurist - Thanks for your report.

You will need to check your Nextcloud server logs for additional details and troubleshoot further before reporting this as a bug. 

You also did not fill out most of the bug report form (which makes it challenging to look into your bug report).

This may be a local configuration matter. If you're unsure, please post for assistance at the [Nextcloud Help Forum](https://help.nextcloud.com/) before reporting as a bug. Thank you.

P.S. If after troubleshooting it appears to be an actual bug, feel free open a new issue and fill out the form so that your issue can be given the attention it deserves.
