### ISSUE TITLE
sharing by mail doesn't allow password, expiration date, secure drop

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#4078]
When sharing a file by link, you have a bunch of settings to control the sharing like password, expiration date, secure drop etc.

If you enter an email address to share with, you can enable and disable editing but nothing else... That is not nice!
![screenshot_20170326_190934](https://cloud.githubusercontent.com/assets/551757/24333438/5e7fffd8-1258-11e7-8944-1c032af5a061.png)

It would fit just fine in the ... menu ;-)

**Comment by jospoortvliet** [comment]
Jan said @schiessle worked on this?

**Comment by d1ffuser** [comment]
https://github.com/nextcloud/server/issues/2357

**Comment by schiessle** [comment]
Password and expire date will come with this pr: https://github.com/nextcloud/server/pull/4136

"File Drop" doesn't make sense to me because "Share by Mail" is more like a internal share, just to a user who doesn't have a account. E.g. for federated shares we also don't have "file drop". It is a share to one specific person and not a link you send to many people and want them to upload stuff without viewing it.

At least that's how I see mail shares, what others think? E.g. @jancborchardt

**Comment by moritzthecat** [comment]
looks great - hope the email templates will come back so users can make their text as neeeded.
And will there be a switch in the admin page to set the default for "can edit" ?
In our case we would prefer to have "can edit" as unchecked default.
