### ISSUE TITLE
Allow `'enforce_theme' => 'highcontrast',` to system-following darkmode

### ISSUE THREAD

**Issue by ne0YT** [nextcloud/server#40908]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I use the setting described here:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html

### Steps to reproduce

1. put  'enforce_theme' => 'highcontrast', inside nextclouds config.php
2. restart the nextcloud server
3. I cannot change the theme anymore, BUT I still have the theme from before, not the configured theme

### Expected behavior

The configured theme 'highcontrast' is enforced on all users.

### Installation method

Community SNAP package

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Try `'enforce_theme' => 'light-highcontrast',`

(I belive `highcontrast` has been renamed, but not documented...).

**Comment by ne0YT** [comment]
@solracsf This actually works. And it helps me partially already :)
But I would like to use highcontrast but having it automatically switch with the systems light / dark-mode.

**Comment by solracsf** [comment]
I don't think this is possible ATM.

**Comment by joshtrichards** [comment]
Responding to comment from @ne0YT on the above PR:
> @joshtrichards so it's not gonna be possible to set highcontrast while usign dark-lightmode of the system?

Well, that's a legitimate enhancement request. I'm actually surprised there isn't an existing Issue covering that, but I can't find one. In any case,your initial report (this issue) was a bug report purely about `enforce_theme` parameters not working as documented. 

The title of your issue completely changed later on. That change turned your Issue into an enhancement request about adding a client system following theme mode, which is an entirely separate matter. :)

I could update the title to clarify this no longer has anythign to do with `enforce_theme` and re-open, but it's going to get confusing real fast since the report doesn't mention anything about that (and what's in it has been addressed).

So probably best for you to open a new Issue (Enhancement Request) specific to the desired support for a system following light/dark mode high contrast  theme.
