### ISSUE TITLE
Installation Wizard not accepting database username and password

### ISSUE THREAD

**Issue by umardraz** [nextcloud/server#41074]
Hello

The Installation wizard is not picking mysql information Here is the information what I had provided through environment variables.

```
-e MYSQL_HOST=10.0.201.120 \
-e MYSQL_DATABASE=ncdb \
-e MYSQL_USER=ncloud \
-e MYSQL_PASSWORD=ncloud12345 \

```
On the first run the installation appears and asked for crate an admin account.

But when I clicked on Finish setup button then an error appears.

Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user ‘oc_admin15’@’%’ to database ‘client1’

```
‘dbtype’ =>; ‘mysql’,
‘version’ =>; ‘13.0.5.2’,
‘dbname’ =>; ‘ncdb’,
‘dbhost’ =>; ‘10.0.201.120’,
‘dbport’ =>; ‘’,
‘dbtableprefix’ =>; ‘’,
‘mysql.utf8mb4’ =>; true,
‘dbuser’ =>; ‘oc_admin15’,
‘dbpassword’ =>; ‘Q9hwc3uqbzqU2G9E+TkJt6XWGqmGjE’,
```

Don't know why it is not accepting username and password, the other options are ok, like dbname, dbhost.

Would you please any body help me.

**Comment by joshtrichards** [comment]
Related: #36428

**Comment by joshtrichards** [comment]
Closing this for the following reasons:

- This Issue has seen any traffic in >3 years ago
- The creation of a dedicated `oc_*` user with *less* privileges than the superuser account is documented behavior. There are ways of avoiding it as well if desired (but they require taking some manual steps such as provisioning the databases and credentials ahead of time and/or applying the approach in #36428)
- Both the Docker image and the installer process in Server have had several changes in the area of retries/etc since this Issue last saw traffic
- Docker's own healthchecks + `depends_on` can be used if you wish to have the app container(s) wait until the db container is on-line

Refs:

- https://docs.nextcloud.com/server/latest/admin_manual/installation/installation_wizard.html#database-choice
- https://docs.docker.com/compose/how-tos/startup-order/
- nextcloud/docker#2250
