### ISSUE TITLE
[BITV]: Create possibility to open an app details via keyboard

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41310]
For now it is not possible to open app details via keyboard. It is only possible to open them via clicking to the row table ;(
We have to change it.

![Peek 2023-11-06 16-21](https://github.com/nextcloud/server/assets/6078378/e75e0644-f6da-4606-8d96-93c5bc6698b1)

@nimishavijay @marcoambrosini do you have any suggestions from design-wise how to resolve this problem?

**Comment by marcoambrosini** [comment]
Hi @JuliaKirschenheuter, 
the easy way would be adding an `<a />` element within the name of the app `<td />` element and showing the outline on `focus-visible` only.

<img width="724" alt="Screenshot 2023-11-07 at 12 03 38" src="https://github.com/nextcloud/server/assets/26852655/055340a8-ef58-47cb-b100-90ed9341e845">


----
I think the proper way would be abandoning the table and using a flex layout so that we can achieve this 

<img width="732" alt="Screenshot 2023-11-07 at 12 03 20" src="https://github.com/nextcloud/server/assets/26852655/c19c2109-7ce1-43fa-bc9e-1aef50fe4246">

**Comment by JuliaKirschenheuter** [comment]
The ting unfortunately is that it is semantically not a `link`. A `link` have to be used in form of "forwarding" to somewhere. What could we do instead?

**Comment by nimishavijay** [comment]
This seems similar to opening a sidebar, could we do something similar? Like the second screenshot by @marcoambrosini but instead of an `<a />` tag we can use whatever we use for the sidebar, would that work? :)

**Comment by JuliaKirschenheuter** [comment]
@marcoambrosini could we create a new button "Open app details"? And place it closed to another action buttons in a table and in tile views? And move this open action to the button only?

**Comment by marcoambrosini** [comment]
I think that's too much @JuliaKirschenheuter 

For a quick fix I think we could just wrap the title of the app into a button `type="tertiary"` and adapting the styles to the table.

**Comment by marcoambrosini** [comment]
@JuliaKirschenheuter It can be a link because there is a URL change, and it opens a sidebar at the same time.

**Comment by ShGKme** [comment]
It changes the URL indeed. So we can use a link there.

And we can just add the link (even visually hidden, or on the app name) without getting rid of the table layout. Having a link (even visually hidden) is enough for screen reader navigation, clickable row is also read as "clickable".

Another related issue is to inform a user that this "navigation to another page" actually opens the sidebar.
