### ISSUE TITLE
[BITV] 9.1.4.4/4.1 - When zoomed in at 200% and selecting multiple media files simultaneously, the labels for the "add" and "delete" buttons disappeared - please refer to the screenshot. (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41852]
![image](https://github.com/nextcloud/server/assets/6078378/0b64c43b-c6ff-4396-80fb-73929d6f1b8b)

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-c41a0aed27-v4-n1

**Comment by JuliaKirschenheuter** [comment]
@artonge could you please help us with this ticket?

**Comment by artonge** [comment]
At 200% zoom level, the device is considered as a mobile, so we remove label to not overload the interface.
However, aria label is still present on the buttons. Isn't it enough? What can we add to make the icon button accessible? Because we have a lot of icon buttons in other places that don't seem to be a problem.

**Comment by ShGKme** [comment]
> At 200% zoom level, the device is considered as a mobile, so we remove label to not overload the interface. However, aria label is still present on the buttons. Isn't it enough? What can we add to make the icon button accessible? Because we have a lot of icon buttons in other places that don't seem to be a problem.

The problem is that the content of the buttons disappears.

**Comment by JuliaKirschenheuter** [comment]
backport have to be done

**Comment by JuliaKirschenheuter** [comment]
done now
