### ISSUE TITLE
[BITV] 9.4.1.2/3.7 - In the breadcrumb navigation, there are "aria-label" attributes on "li" elements, which is not allowed, such as aria-label="Go to the "/" directory". (2)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41895]
https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v3-n7

9.4.1.2/11.7 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v11-n7

**Comment by JuliaKirschenheuter** [comment]
@szaimen not resolved?

**Comment by szaimen** [comment]
> @szaimen not resolved?

I may have moved it by mistake...

**Comment by szaimen** [comment]
We have this here now:
![image](https://github.com/nextcloud/server/assets/42591237/7d97dc54-45e2-4d63-8eed-62eddbddc812)
Is this the correct implementation @susnux @ShGKme @emoral435 @Pytal @JuliaKirschenheuter ?

**Comment by JuliaKirschenheuter** [comment]
semantically it is correct but `aria-label` seems to be not translated. @emoral435 what was the last stand 🤔?

**Comment by emoral435** [comment]
<img width="609" alt="image" src="https://github.com/nextcloud/server/assets/110193237/471f3eee-34e0-495d-aee1-651be4b2caef">

This is what we came up as our decision (copied and pasted it from my messages with skjnldsv - won't tag him because I do not want to bog him down with another ping, LOL).

So as far as implementation, it is correct, however, upon testing right now, it seems as if the aria label for the home section seems to be untranslated, probably due to it being not a component that we made. It is a component supplied by Vue itself. Will be correcting this!

**Comment by szaimen** [comment]
Seems like aria-label="Home" is still not translated?
![image](https://github.com/nextcloud/server/assets/42591237/86cade6b-c28a-4ebb-9939-f3e1ced73641)

**Comment by ShGKme** [comment]
> Seems like aria-label="Home" is still not translated?

Is it informal or formal German?

**Comment by szaimen** [comment]
formal German

**Comment by emoral435** [comment]
@ShGKme Would you be able to handle the translations here? I unfortunately do not know formal German. However, I also would not mind doing it myself, I am just now familiar with how our translation system works. A pointer in the right direction would help me lots :)

**Comment by ShGKme** [comment]
That was unexpected, but this string to exactly this place was intentionally translated as "Home" in Transifex.

From a little research, this is indeed a common way to translate "Home" in a context of "Home directory".

So everything is fine here.

cc @susnux for a native speaker

**Comment by susnux** [comment]
Yes quite common, but could also be "Start" or "Startverzeichnis". cc @rakekniven
