### ISSUE TITLE
Make configurable length of shared link token

### ISSUE THREAD

**Issue by savely-krasovsky** [nextcloud/server#419]
For example now, I have this: 
`l33t.host/s/CpjUhnJuFEyMQzn`

And we can have this:
`l33t.host/s/AvJHo`

But It's my personal service for maybe 1000 or 10000 (max!) shared files.
And for this aim even 4-5 characters is enough. Why 15?

In Owncloud we don't have theming, now we have, and it's very cool. So why not?

**Comment by mar1u5** [comment]
> But It's my personal service for maybe 1000 or 10000 (max!) shared files.

You are right, but there are some other users, using more than 1000 files and shares 😜 I think shortening the URL makes sense anyway. An option for personalize the URLs would be nice. I think of something like `l33t.host/s/pictures-of-party`.

If the URL is too long for your use (e.g. Twitter) you could also shrink the URL with a service like `goo.gl` 😉

**Comment by Lord-Protector** [comment]
@mar1u5 okay, lets use simple math.
We have common formula for combinations:
![a73cf8428fc85510cade14325f0d8a3f460ed0c6](https://cloud.githubusercontent.com/assets/5345489/16894312/5bcf49c0-4b5b-11e6-8b2e-3ae60f9041cf.png)
Where is `n = 52` (lowercase + uppercase) and `k` is length of our token.
So no lets calculate:
For 4 symbols:
![msp92920i342afidcgh17h00003daec986hdhd4iid](https://cloud.githubusercontent.com/assets/5345489/16894326/85b85e7a-4b5b-11e6-9e24-ab72da7cb0cd.gif)
**270 725!**
For 5 symbols:
![msp2647212ii36c900g1he5000010hic0biac6fhiii](https://cloud.githubusercontent.com/assets/5345489/16894329/900a08e2-4b5b-11e6-87aa-3203e62258d6.gif)
**2 598 960!**
For 6 symbols:
![msp1741238856ff5de0g2320000160egg0g46fg2dga](https://cloud.githubusercontent.com/assets/5345489/16894341/c3aa11a6-4b5b-11e6-9e97-e3f7fa847acc.gif)
**20 358 520!**
If you really so scary for some strange users, just set 6+ symbols by default. But for me even THREE symbols is enough (22 100 combinations!).

**Comment by rullzer** [comment]
It is not only about the number of possible shares. It is also about security. You don't want people to be able to guess your tokens.

**Comment by Lord-Protector** [comment]
@rullzer okay, we can show people some attentions about security and by default set 15.

**Comment by rullzer** [comment]
Well a password is yet another thing to distribute.

With 15 tokens you are fairly safe to somebody even finding a link that works. It is all about reducing the attack vector.

**Comment by Lord-Protector** [comment]
@rullzer I understand that it's reducing. But It's not the "critical security point", it's just a little plus to security. I think it should be customizable with some attentions. Why I have to use goo.gl, bit.ly and other such services if I already have short domain name that enough for me.

I use Nextcloud with [ShareX](https://getsharex.com/) for fast creating gif, screens, video, etc. It's very useful and convenient for (just try!) And I always get those long link! This is the only negative.

**Comment by mar1u5** [comment]
If you already have a short domain name, https://yourls.org could be a workaround  ... this is for hosting your own URL shortener. Maybe you could also develop an proper integration as an app 😉

**Comment by rullzer** [comment]
I get that it is one of things that is nice to have. but it is another configuration variable in the matrix. With the potential downside that if people mess up (and people will mess up) exposed data.

I agree with @mar1u5 that an app that does shortning would be better.

**Comment by Lord-Protector** [comment]
@mar1u5 thanks for idea with yourls.org. With ShareX I automate it:
![image](https://cloud.githubusercontent.com/assets/5345489/16902609/f0e2aac2-4c6c-11e6-80c0-908a60debcb1.png)

**Comment by ernolf** [comment]
Hi @savely-krasovsky,

You made some errors and unfortunately no one has noticed it yet.

> okay, lets use simple math.

Your math is not simple enough :wink:

The first error is the incorrect number of available characters, you used 52 characters in your calculation, which excludes the digits.
The character set is A-Z, a-z, and 0-9. This totals 62 characters (26 uppercase + 26 lowercase + 10 digits).

The formula you used:

$$
\binom{52}{4} = \frac{52!}{4! \times 48!} = 270,725
$$

is for calculating the number of ways to choose 4 distinct items from a set of 52 without regard to order. This formula assumes that each character can only be used once. This calculation is correct for determining combinations when items cannot be repeated and the order does not matter.

But since in this case the string can be filled by any of the 62 characters with repetition allowed, the correct formula to calculate the number of possible combinations is

$$
k^n
$$

.. where

- 𝑘 is the number of available characters (62 in this case).
- 𝑛 is the length of the string (4 in this example).

Calculation: $62^4$ =14,776,336 possible variations

and for the others:

Tokenlength = 5
wrong:

$$
\binom{52}{5} = \frac{52!}{5! \times 47!} = 2,598,960
$$

correct: $62^5$ = 916,132,832 possible variations

Tokenlength = 6
wrong:

$$
\binom{52}{6} = \frac{52!}{6! \times 46!} = 20,358,520
$$

correct: $62^6$ = 56,800,235,584 possible variations

---
and here some more:

- Tokenlength = 7 = $62^7$ = 3,521,614,606,208 possible variations
- Tokenlength = 8 = $62^8$ = 218,340,105,584,896 possible variations
- Tokenlength = 9 = $62^9$ = 13,537,086,546,263,552 possible variations
- Tokenlength = 10 = $62^{10}$ = 839,299,365,868,340,224 possible variations
- Tokenlength = 11 = $62^{11}$ = 52,036,560,683,837,093,888 possible variations
- Tokenlength = 12 = $62^{12}$ = 3,226,266,762,397,899,821,056 possible variations
- Tokenlength = 13 = $62^{13}$ = 200,028,539,268,669,788,905,472 possible variations
- Tokenlength = 14 = $62^{14}$ = 12,401,769,434,657,526,912,139,264 possible variations

- Tokenlength = 15 (**This is the default**)
  $62^{15}$ = 768,909,704,948,766,668,552,634,368 possible variations

- Tokenlength = 16 = $62^{16}$ = 47,672,401,706,823,533,450,263,330,816 possible variations
- Tokenlength = 17 = $62^{17}$ = 2,955,688,905,823,059,073,916,326,510,592 possible variations
- Tokenlength = 18 = $62^{18}$ = 183,252,712,161,029,662,582,812,243,656,704 possible variations
- Tokenlength = 19 = $62^{19}$ = 11,361,668,153,983,839,080,134,359,106,715,648 possible variations
- Tokenlength = 20 = $62^{20}$ = 704,423,425,546,998,022,968,330,264,616,370,176 possible variations

and just f.y.i., the maximum possible

- Tokenlength = 32 = $62^{32} = 2,272,657,884,496,751,345,355,241,563,627,544,170,162,852,933,518,655,225,856$ possible variations

---

I would classify the use of URL shortening services as a much greater security risk.

---
ernolf

**Comment by savely-krasovsky** [comment]
Thanks for the clarification, I would agree now after 8 years, especially after working 3 years in information security :D
