### ISSUE TITLE
[BITV] 9.4.1.2/10.2 - Both autocomplete comboboxes "Enforced groups" and "Excluded groups" were not implemented in the right way using ARIA, making them not really accessible for screen reader users. (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41909]
A functioning example can be found, for example, at https:// www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/

![image](https://github.com/nextcloud/server/assets/6078378/54ba028e-b9a0-450d-b082-c466a53035d4)

https:// www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v10-n2

**Comment by JuliaKirschenheuter** [comment]
not the same as https://github.com/nextcloud/server/issues/41908?

**Comment by emoral435** [comment]
After looking at the codebase, it seems like the issue seems to just be within a Vue component that is being loaded - if we fix the accessibility issue with the component, a lot of similarly accessibility issues will be solved alongside this

Specifically, the issue is with the NcSelect component - looking further into the component.

**Comment by JuliaKirschenheuter** [comment]
@susnux could you please observe the implementation of this ticket? Thank you!

**Comment by JuliaKirschenheuter** [comment]
following work have to be done from: https://github.com/nextcloud/server/issues/41902#issuecomment-1838405393
