### ISSUE TITLE
Public shares "Download"-option downloads everything as ".tar" :(

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4195]
The button should also offer a `.zip`-file download option. `.tar` is too technical 😁 (Windows users, ...). Could be solved over an Dropdown menu.

**Comment by MorrisJobke** [comment]
It downloads as zip file, and as tar file on macOS, because of a bug in the macOS zip implementation that would not allow to extract a zip file with umlauts in it.

So this is the intended behaviour. And it should work out of the box extracting the zip/tar automatically on the system of your choice with preinstalled apps.
