### ISSUE TITLE
Shared folder loses 'Secure Drop' after gets 'linked shared' by other user

### ISSUE THREAD

**Issue by pfiff45** [nextcloud/server#4223]
### Steps to reproduce
1. Create Secure Drop folder
2. Share it with other user
3. Change to the user
4. Share folder by link

### Expected behaviour
Shouldn't it stay on 'secure drop' and the link of the origin should be reused?

### Actual behaviour
Users can see the files of the originally 'secure drop' folder

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0 alpha
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
git master

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer

**Comment by schiessle** [comment]
I think that's a hard question. Intuitively I would say that we should re-use the link but this has multiple challenges:

* Should the other user be allowed to change the settings (e.g. removing secure drop, changing expire date, changing password)
* if the share is password protected and the link is shared across multiple internal users, only the user who set the password know it.

I think that's some of the reasons why at the moment each user which access to the file can create one public link by it's own if re-sharing is allowed. That's probably also most intuitive for the user. Also I don't see a hard requirement why we need to keep the "secure drop" settings. Just because userA want to share a folder to friendA as secure drop doesn't mean that userB want to share the folder to friendB as well as "secure drop".

So I would say that this is the intended behavior for now. @rullzer do you agree?

**Comment by rullzer** [comment]
Yes it is intented. If userA shares a folder with userB then userB can share it how they see fit (given they have reshare permissions).

userB does not need to know that userA shared the link at all (it is non of their buisness).

Also like @schiessle said it gets confusing pretty quick. Like if a password is set. How is userB supposed to guess the password? The server can't tell you since we don't store it.

It basically comes down to if userA gives userB the rights to share files. Then they can do that.
