### ISSUE TITLE
[Bug]: Apps UI not working in WebKit browsers (Safari, iOS/iPadOS, GNOME/Epiphany)

### ISSUE THREAD

**Issue by BJKle** [nextcloud/server#42249]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When selection any app in the "your apps" "active apps" "disabled apps" section always the same app will be displayed. E.g. selection "Activity" -> "Versions" is displayed. Scrolling doesn't work as well.
<img width="1537" alt="Screenshot 2023-12-13 at 21 53 33" src="https://github.com/nextcloud/server/assets/88108046/9215bd57-0f61-4c4e-82a2-c103baa6f5c2">

### Steps to reproduce

1. Open Apps
2. Select an app to manipulate
3. in my case "Versions" is displayed

### Expected behavior

The selected app should be displayed to enable/disable

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @BJKle - I'm unable to reproduce this behavior. Can you try a different browser and/or device and/or disable extensions like ad blockers?

If it persists after that, please share what browser(s) and OSes you're seeing this behavior on. Thanks!

**Comment by tiptoptrash** [comment]
Hi @joshtrichards: I have the same problem.
Using Safari on macOS Sonoma, iOS 14.2 and iPadOS 14.2, the problem ist present.
Using Firefox on macOS Sonoma, the problem is not reproducible.

Affected are the list under "Your apps", "Active apps", "Disabled apps", "App bundles" and "Feautured apps". All those lists are static and cannot be scrolled.
The other items starting with "Customization" behave totally normal.

I hope, that helps, thanks a lot!

**Comment by BJKle** [comment]
No change with 28.0.1 😔

**Comment by derrickpeavy** [comment]
Can affirm:

Using Safari on macOS Monterey (12.7.1), Safari 17.1, the problem is present.
Using Firefox on macOS Monterey (12.7.1), no problems.

This problem IS still present in NextCloud 28.0.1.

Pretty sure this is a CSS change that was introduced with 28.0.0.11, the list of apps will not scroll and clicking to enable or disable any app simply brings up an info panel on some other app which was not clicked.

**Comment by BJKle** [comment]
I tried different browsers (FF/Edge) on iOS/iPadOS and is not working as well.
This really needs to get fixed.

**Comment by joshtrichards** [comment]
Reproduced successfully in GNOME Web (Epiphany), which is also WebKit based just like all reported browser scenarios so far.

**Comment by BJKle** [comment]
I don't know where it belongs to, but must have to do with WebKit as well.
In "Files" on a Mac I cannot "drag-and-drop" any file in Safari to my Cloud. I tried it in Firefox and it works.

**Comment by cloudguy23** [comment]
I'll add that Forms app is also affected.   I'm able to create forms, complete, and share forms via Safari.   However, a user will encounter an error - "There was an error submitting the form" - when submitting a form that was shared with them via Safari.  Chrome, Brave, Firefox all work without issue.

**Comment by eweinhold** [comment]
Nextcloud 28.0.2 RC3 still not scrolling on safari :(

That not scrolling Bug persists in Nextcloud 28.0.2 RC3.

All Safari Browsers on all systems are affected Desktop, iPad, iPhone. 
Last Version and just updated current version 17.3 iOS and 14.3 macOS 

<img width="1462" alt="apps-view" src="https://github.com/nextcloud/server/assets/1260476/90537b11-d035-46b6-b5df-f90bdf3a5265">

**Comment by eweinhold** [comment]
> Nextcloud 28.0.2 RC3 still not scrolling on safari :(
> 
> That not scrolling Bug persists in Nextcloud 28.0.2 RC3.
> 
> All Safari Browsers on all systems are affected Desktop, iPad, iPhone. Last Version and just updated current version 17.3 iOS and 14.3 macOS
> 
Nextcloud 28.0.2 RC4 still not scrolling :(

affected views:
/index.php/settings/apps
settings/apps/enabled
settings/apps/disabled
settings/apps/app-bundles
settings/apps/featured
settings/apps/search

the other apps views / preview Lists are not affected. they do scroll.

**Comment by eweinhold** [comment]
Nextcloud 28.0.2 RC5 not scrolling.

**Comment by eweinhold** [comment]
Nextcloud 28.0.2 release - this bug is still not fixed. :(

**Comment by joshtrichards** [comment]
@eweinhold Yes, that's why this issue is still open. If you want to help nudge things forward, the underlying cause needs to be identified before a fix can be made. So feel free dig a bit into what might be causing it.

**Comment by 001101111011101101** [comment]
Can confirm the bug as of version 28.0.2 on Safari 17.3 (19617.2.4.11.8)
It is affecting only the Apps section. The Administration Settings section behaves as expected.

**Comment by nicnab** [comment]
I'm not sure if this belongs in here as well but I updated a customer's Nextcloud instance to 28.0.2 last night and got the report from one (weekend working and rather tech savvy) user this morning that they can't upload files via safari anymore because when dropping a file, the "screen jumps around like crazy".

I don't have a Mac here so I can't confirm. In LibreWolf/Linux all works fine. In order to avoid bigger problems, I just downgraded to 27.1.6 via snapshot of the machine and, unfortunately, forgot to have the user send a screenshot of some kind. Maybe someone else with a Mac can confirm?

**Comment by 001101111011101101** [comment]
> I'm not sure if this belongs in here as well but I updated a customer's Nextcloud instance to 28.0.2 last night and got the report from one (weekend working and rather tech savvy) user this morning that they can't upload files via safari anymore because when dropping a file, the "screen jumps around like crazy".
> 
> I don't have a Mac here so I can't confirm. In LibreWolf/Linux all works fine. In order to avoid bigger problems, I just downgraded to 27.1.6 via snapshot of the machine and, unfortunately, forgot to have the user send a screenshot of some kind. Maybe someone else with a Mac can confirm?

Can confirm on Sonoma 14.3 with Safari 17.3 (19617.2.4.11.8)

**Comment by eweinhold** [comment]
> I'm not sure if this belongs in here as well but I updated a customer's Nextcloud instance to 28.0.2 last night and got the report from one (weekend working and rather tech savvy) user this morning that they can't upload files via safari anymore because when dropping a file, the "screen jumps around like crazy".
>...Maybe someone else with a Mac can confirm?

can confirm.
Fileuploads with safari via drag&drop just result into heavy flickering (Drag&Drop UI Loading and showing and unloading disappearing) uploads via safari browser are not possible with drag and drop.

**Comment by BJKle** [comment]
@eweinhold @001101111011101101 
See above. I mentioned it.
We need a solution not a longer thread.

**Comment by tiptoptrash** [comment]
> I'm not sure if this belongs in here as well but I updated a customer's Nextcloud instance to 28.0.2 last night and got the report from one (weekend working and rather tech savvy) user this morning that they can't upload files via safari anymore because when dropping a file, the "screen jumps around like crazy".
> 
> I don't have a Mac here so I can't confirm. In LibreWolf/Linux all works fine. In order to avoid bigger problems, I just downgraded to 27.1.6 via snapshot of the machine and, unfortunately, forgot to have the user send a screenshot of some kind. Maybe someone else with a Mac can confirm?

Here you go. Attached is a video showing that bug. Drag&Drop is completely unusable right now with Safari.
I am very lucky that this is only my personal nextcloud instance and not the big instance I am administrating, too. I avoid Nextcloud 18 because I expect a flood of user complaints.

I hope that helps a bit to track down the problems.

Best greets!


https://github.com/nextcloud/server/assets/21986310/1b7861ae-414a-402c-b773-f4b95cae74b7

**Comment by BJKle** [comment]
again it is another issue. see https://github.com/nextcloud/server/issues/43135
a fix is linked in this issue.
please don't spam this issue, which needs to be fixed

**Comment by eweinhold** [comment]
The Change that was made is the switch form a list of divs for the apps-list-container in NC27 to a html table in NC28
I guess some attributes of that old apps-list-container div do not work on a html table

works in safari
> NC 27 apps-list-container as list of divs
> <img width="492" alt="NC27_apps-list-container_as_div" src="https://github.com/nextcloud/server/assets/1260476/5353f81d-be10-4019-a7c4-981221d70c02">

dosen't work in safari
> NC 28 apps-list-container as one html table
> <img width="565" alt="NC28_apps-list-container_as_Table" src="https://github.com/nextcloud/server/assets/1260476/4fd81b05-96e5-4e24-884a-59e14253d542">

this switch to an HTML TABLE was only made on some settings pages - which all doesn't scroll on safari.

**Comment by BJKle** [comment]
Since we know the problem. Is there someone able to fix it?

**Comment by gcoretech** [comment]
As an example see: /settings/apps/installed/calendar
That page is divided into three sections: the category on the left, the app list in the middle and the details of the selected app on the right. 

The page seems to be generated by:
https://github.com/nextcloud/server/blob/master/apps/settings/src/components/AppList/AppItem.vue

The following style is defined at the bottom of AppItem.vue:

```
.app-name--link::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```

If you add background-color: yellow to that, the whole app list is yellow. Set _content: 'X'_ and change _position_ to _relative_, you will see just an X with yellow background right after every app name. The whole list is not yellow anymore and it's scrollable again.

I cannot fully test this because /apps/settings/src/components/AppList/AppItem.vue is not available on my nextcloud server. It seems to be added with webpack so it's not easy for me to test it.

Perhaps someone could try to remove .app-name--link::after from AppItem.vue and see if that fixes it.

**Comment by mhzawadi** [comment]
So I have this issue and have gone to test editing the `/apps/settings/src/components/AppList/AppItem.vue` file, but I dont have it on my server. My `apps/settings/` is missing the `src` directory

Is that the issue that the file is missing?

**Comment by mhzawadi** [comment]
also the community zip file is missing the `/apps/settings/src` directory

**Comment by gcoretech** [comment]
@mhzawadi A nextcloud developer should have a look at this as those files are not part of a regular nextcloud installation. The code these files produce is seemingly packed/minified into javascript files that your nextcloud installation uses but it's hard to edit them directly because of the minification.

**Comment by mhzawadi** [comment]
Hey @gcoretech 

I have the docker dev environment setup and working, I have edited `.app-name--link::after` to have yellow and can see it in Opera. But Safari is not yellow and still doesn't scroll.

**Comment by gcoretech** [comment]
Hey @mhzawadi
_background-color: yellow_ visualizes which area is affected in safari, scrolling works after changing _position: absolute_ to _position: relative_.

This is from Safari developer tools (position changed to relative):

![yellow-relative](https://github.com/nextcloud/server/assets/13226031/203aa654-f146-4973-b666-d273e2300f7d)

All apps in the app list now have an X with a red border and yellow background right after the app name and scrolling works:

![yellow-relative2](https://github.com/nextcloud/server/assets/13226031/a734fad2-6775-4265-88a2-9045c58bb102)

Changing position back to absolute the whole app list is yellow and all the apps are behind the yellow pane so you can't see them. Imagine the picture above all yellow, without any text.

Hope this helps.

**Comment by mhzawadi** [comment]
can confirm that removing `position: absolute;` allows the table to scroll

<img width="304" alt="image" src="https://github.com/nextcloud/server/assets/11944327/2e945b8f-7153-46b7-a308-bb031b337047">

**Comment by tallinn1960** [comment]
As this issue only mentions scrolling, I would like to add that app selection in the active app list is broken as well on macOS 14.4/Safari 17.4 in NC 28.0.3. On my system, the browser selects the last app in the list (in my case, the weather app) and sticks with it, no matter what app one is clicking on.

**Comment by derrickpeavy** [comment]
> As this issue only mentions scrolling, I would like to add that app selection in the active app list is broken as well on macOS 14.4/Safari 17.4 in NC 28.0.3. On my system, the browser selects the last app in the list (in my case, the weather app) and sticks with it, no matter what app one is clicking on.

THAT IS CORRECT FOR ME AS WELL!

**Comment by ShGKme** [comment]
The issue is caused by Safari not applying `position: relative` on `<tr>`
See: https://bugs.webkit.org/show_bug.cgi?id=240961

Both issues: broken scrolling and opening an app in the sidebar.

Removing `position: absolute` fixes the issue, but it removed the ability to click on the row to open app in the sidebar, making only the text of app name clickable.

#44236 should with both issues keeping row clickable.

**Comment by darthmarx** [comment]
Not fixed in 28.0.4

**Comment by joshtrichards** [comment]
It's fixed in v29. It's going to require some manual intervention to finalize the backport for v28 it looks like (pending in #44327).

**Comment by nicnab** [comment]
Thanks for keeping us in the loop, @darthmarx and @joshtrichards !

**Comment by mehlkopf** [comment]
It's still not fixed in 28.0.6. Honestly, it is a great symptom of what is wrong with Nextcloud's fast update release cycle: either I am supposed to stay longer on the older versions, but then all bugs should be fixed first on these versions, OR I should always update and can assume the latest versions to be the most reliable, but that is obviously also not the case. It is really frustrating.

**Comment by nicnab** [comment]
Are you sure it isn't? This [post](https://help.nextcloud.com/t/april-2024-final-releases-29-0-0-28-0-5-27-1-9/189041/8?u=n2o) says it is. I will try to test myself before upgrading my customer's instance but I first have to find a Safari to test on.

**Comment by mehlkopf** [comment]
Unfortunately, for me, it is not fixed as of 28.0.5.

**Comment by nicnab** [comment]
Oh I'm sorry. Reading skills sometimes do help. As I will be the only one dealing with apps it iis not a problem for me at the moment but I understand it is for you.

**Comment by joshtrichards** [comment]
It's fixed in v29, but the backport requires extra manual intervention: #44327

**Comment by ShGKme** [comment]
Sorry, will be backported to v28 before the next minor release.

**Comment by mehlkopf** [comment]
@joshtrichards Thank you for your reply! First and foremost, I am very thankful for all the work you are doing, and it is good to have these clarifications regarding update strategies.
Nevertheless, I think the version 28 cycle has been very rough for lots of people, and I think it should result not only in clarification of these update strategies, but also regarding testing procedures and release schedules. This app screen bug is a very minor annoyance in comparison to lots of bugs introduced in 28.0, which were thankfully gradually improved on in the .0.x versions. However, I personally think 28.0.0 should never have been released in this state, there were way too many bugs that simple testing routines (like drag and drop a file into the browser, try to move/duplicate files, overwriting files at upload, not handling new file creation properly, etc., all these things were not working in v28) could have prevented. And in the same vain, a simple test of all screens (scrollable? clickable?) in different browser would have prevented this app list bug from shipping (at least unknowingly).
For me, it was the first time in years I had more than 1-2 minor issues when running a new version. So, in my opinion, something fundamentally went wrong and it would be great to see the development process learning from that – because it also cannot be the goal to just allow the most hobbyist users to use the most recent version. So overall, I think development on new things should slow down and testing should be more rigorously at least such that new .0 versions will be as stable as the other 20s version were.
And I know there are lots of people working with constrained resources, so I am very thankful for all your work – I am just not certain the resources are always appropriately assigned to new developments vs. reliability/bug fixing.

**Comment by adegans** [comment]
I have this too on NC28.0.5 with Safari macOS and also on my iPad.
I don't come in that dashboard too often, but I think it worked fine on earlier versions.

**Comment by mehlkopf** [comment]
> Sorry, will be backported to v28 before the next minor release.

Unfortunately, 28.0.6 did not fix it for me …

**Comment by nicnab** [comment]
> > Sorry, will be backported to v28 before the next minor release.
> 
> Unfortunately, 28.0.6 did not fix it for me …

For me neither. I'm currently unsure how to proceed. Thinking about setting up a test instance with 29 and have some Mac users do tests there and then upgrade straight through to 29 if it works.

**Comment by adegans** [comment]
Works for me on safari/macos with 29. But it continues a bunch of other stupid issues. Like the endless socket timeout problem when the macbook awakes from sleep. And heaps of pointless sync issues I can't explain which go away after a minute or so.
