### ISSUE TITLE
Ability to acknowledge logged errors in security & setup warnings

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#42383]
Now with NC 28 once we have error in the logs. Admin can see them under the Security & setup warnings checks. And if server has error is give you a warring that there error like the below pic

It would be nice to have an option to acknowlade the error or warrning so when the setup warnings checks runs again it give you a green check. 

![image](https://github.com/nextcloud/server/assets/59488153/8c010ba7-5d5a-400e-bf01-a237d88d9e0f)

**Comment by isdnfan** [comment]
another idea regarding this warning would a hyperlink directly navigating to the filtered log view showing the errors.

**Comment by franzhartwig** [comment]
The errors in the logfile are not necessarily regarding the setup. So the new hint could be misleading. Perhaps it is a good idea to leave the green tick as before and add an additional hint:
"Additionally, there are xx entries in the logfile. Please, review the logs and  resolve the related issues."
"review the logs" could be a link to the logs. I have chosen "entries" instead of "error". There may be some entries with another log level than error.

**Comment by paierh** [comment]
If you actually have some activity on your server the chance of a green checkmark is slim to none, because log rotation events are logged as warnings.

**Comment by JoshuaPettus** [comment]
Most "errors" are benign, incidental, on app developers, or generally nothing really the end user can do anything about.
Is it really a good idea to be hounding system admins on something they can't control and therefor not very useful?   I can't help but feel this new "Good Idea"  is just causing admins and troubleshooters unnecessary grief and little to do with system security or stability.   If there are no configuration issues can we just let the box be green?   The log has always been readily accessible for those that check.  Even more so with the new interface.

**Comment by AndyXheli** [comment]
Personally I liked it the way it was before.  Either add on acknowledge or move it back to the way it was.

**Comment by plazotronik** [comment]
if your log file weighs gigabytes (as we have 3-5 GB) per day, then the check fails with an error. I know for sure that there should have been information about the indexes in the database (after updating - db:add-missing-indexes) and another message about the necessary setting 'maintenance_window_start'. but this information did not appear due to a log scan error. when I deleted the log file 'nextcloud.log' (renamed it), everything immediately worked as expected.
this feature is not a feature, it is a bug. it should be possible to disable such scanning in the file config.php
![Screenshot_20240331_212822](https://github.com/nextcloud/server/assets/39593034/573c9d32-d01d-478d-bc03-58af78642c90)

**Comment by slapcat** [comment]
My current workaround is to **disable the logreader app**. Yes, this makes the logs inaccessible in the web UI, but I can also check the nextcloud.log file myself if there is an issue.
