### ISSUE TITLE
Current S3 Implementation lacks support for different endpoints (e.g. S3 Transfer Acceleration)

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#42675]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently, if a customer wants to mount an external S3 storage, it works as documented here: https://docs.nextcloud.com/server/26/admin_manual/configuration_files/external_storage/amazons3.html

However, to make buckets available across several regions, customers might want to use S3 Transfer acceleration as described here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html?icmpid=docs_amazons3_console

When enabled, the transfer accelerated endpoint is:
[bucket].[s3-accelerate.amazonaws.com](http://s3-accelerate.amazonaws.com/)

But the external storage app converts the settings to:
[bucket].s3.[region].[amazonaws.com](http://amazonaws.com/)
and adds a .s3 to the url.

This problem might not be solely related to S3 Transfer Acceleration, but any situation when the endpoints differs from what the current implementation expects.

**Describe the solution you'd like**
We would need to modify the s3 implementation to tell the aws sdk to use the different endpoint.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sorbaugh** [comment]
cc @Altahrim @icewind1991

**Comment by dennisTGC** [comment]
I reported this through Nextcloud support as we have an active subscription (Ticket#9655063) but the reply was:

> The handling of Amazon S3 Transfer Acceleration is unfortunately at the moment not available in our software. I have let the product manager know about your request and it might be added to our roadmap. 

> Further discussing with our engineers confirms that this is a use case that the current implementation wasn't designed for. However we understand why this is important to you. If the business impact of the implementation of this feature is very high for you or it is blocking your project, I would recommend you to contact your account manager  via [***E-MAIL ADDRESS ACCOUNT MANAGER***] to talk about the possibilities. 

So they see this as a feature request instead of an bug. I can argue for both. Let's hope @icewind1991 feels like fixing this.. ;-)

**Comment by joshtrichards** [comment]
Out of curiosity, are your NC app server instances far away from your S3 endpoints currently? 

I ask because acceleration doesn't help if your *NC users* are dispersed all over, but only if your NC server instances are not close to your S3 endpoint(s). 

You can sort of see what I mean by going to the [s3 accelerator speed test tool](http://s3-accelerate-speedtest.s3-accelerate.amazonaws.com/en/accelerate-speed-comparsion.html) and looking only at the very first test's results (assuming your web browser is reasonably close to an existing S3 endpoint) since the other test are not applicable with NC's current architecture. The results of accelerated versus non-accelerated will be exactly the same (well, within 1%-2%, with any variance just being because they are different endpoints not due to acceleration).

Unless your architecture has your NC servers nowhere near your S3 endpoints, there will be no improvement in performance.

It might matter at some point if NC clients could bypass server to access S3 stored files (e.g. #14675), but that's not the case today. 

It would help though if your NC server mounts/uses far away S3 endpoints today (and only if you're unwilling - or unable - to solve that through other architectural changes).

Also semi-related: #30917

**Comment by joshtrichards** [comment]
> When enabled, the transfer accelerated endpoint is:
[bucket].[s3-accelerate.amazonaws.com](http://s3-accelerate.amazonaws.com/)
>
> But the external storage app converts the settings to:
[bucket].s3.[region].[amazonaws.com](http://amazonaws.com/)
and adds a .s3 to the url.
>
> This problem might not be solely related to S3 Transfer Acceleration, but any situation when the endpoints differs from what the current implementation expects.

The External Storage GUI is a bit more rigid then the Primary Storage configuration parameters for S3, but you should be able to configure at least the endpoints you have in mind for acceleration in the GUI by treating the situation as if it was a non-Amazon S3 backend (I think). That is, specify your own hostname/etc. For better docs on this, see more recent documentation versions (the 26 one doesn't have some of the doc changes, but the implementation is the same):

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/amazons3.html

**Comment by dennisTGC** [comment]
> Out of curiosity, are your NC app server instances far away from your S3 endpoints currently?

Yes, the bucket is in NL-AMS and the instance is in AUS-Sydney. Currently, we are replicating the bucket to a bucket in AUS to fix this. Hence, the request to use the accelerated bucket.

**Comment by dennisTGC** [comment]
> The External Storage GUI is a bit more rigid than the Primary Storage configuration parameters for S3, but you should be able to configure at least the endpoints you have in mind for acceleration in the GUI by treating the situation as if it was a non-Amazon S3 backend (I think). That is, specify your own hostname/etc. For better docs on this, see more recent documentation versions (the 26 one doesn't have some of the doc changes, but the implementation is the same):

I don't think this is possible through the GUI, that's why Nextcloud support created this github issue. 

as @sorbaugh said:
> When enabled, the transfer accelerated endpoint is:
[bucket].[s3-accelerate.amazonaws.com](http://s3-accelerate.amazonaws.com/)

> But the external storage app converts the settings to:
[bucket].s3.[region].[amazonaws.com](http://amazonaws.com/)
and adds a .s3 to the url.

If I input the accelerated bucket with the available fields in the GUI it will create:
[bucket].s3.[s3-accelerate].amazonaws.com
but it needs to be:
[bucket].[s3-accelerate].amazonaws.com
