### ISSUE TITLE
[Bug]: Unable to enable server-side encryption

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43123]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/1374172/4a1d6a04-6529-404e-9452-57cb6e3664a3)

```
TypeError: Object.entries(...).find(...) is undefined
    data Encryption.vue:113
    VueJS 6
    93952 main-admin-security.js:51
    Webpack 5
vue.runtime.esm.js:3065:16
    VueJS 8
    93952 main-admin-security.js:51
    Webpack 5
```

### Steps to reproduce

1. Install nextcloud
2. Enable the default encryption app
3. Go to admin security settings
4. Enable server encryption
5. A toast pops up telling me to enable encryption in the admin settings (that is what I am doing?)
6. Reload the page

### Expected behavior

I can enable server side encryption

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
On stable28 I was able to enable encryption. The flow is as follows:

![Bildschirmfoto vom 2024-01-25 17-30-32](https://github.com/nextcloud/server/assets/1374172/7d64cb6c-d967-4c45-8eed-f117f06a8719)
![Bildschirmfoto vom 2024-01-25 17-30-42](https://github.com/nextcloud/server/assets/1374172/96cd52c8-d02f-4985-bba4-a2d31c0734d5)
![Bildschirmfoto vom 2024-01-25 17-30-50](https://github.com/nextcloud/server/assets/1374172/1703c7be-a595-4a24-8dfd-2e2577989839)
![Bildschirmfoto vom 2024-01-25 17-30-54](https://github.com/nextcloud/server/assets/1374172/c6e56c43-a1b4-4a26-8964-7c1d831e071a)

**Comment by joshtrichards** [comment]
The underlying cause for what you experienced is likely the same as #44532. It's a front-end bug. It'll break in <master too. The initial value is fine, but if Default encryption module gets clicked it breaks. The console error starts that point.

In some scenarios the "Enable server-side encryption" radio button switches off upon a page reload. It is impossible for the admin to fix in the Web UI, but easily fixed via occ:

 `occ encryption:set-default-module OC_DEFAULT_MODULE` 

(but it'll break again if you touch the UI).

The toast itself may be related or another matter. To be determined. In any case, been a bug likely since NC25 from the looks of it. PR #44604 remedies it.
