### ISSUE TITLE
[Bug]: File Version Restore is Not Working

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/server#43262]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When file shared with other users with full permissions initial version of file cannot restored.

### Example

https://github.com/nextcloud/server/assets/67455295/72855892-d149-4582-97db-74c2fa0da19f

### Steps to reproduce

1. Share a file with multiple user that have full permission and try to restore initial version of file

### Expected behavior

Initial version of file must be restored without any problem.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Nothing in the logs?
ALso, open the browser console and see what happens.

**Comment by 0jsg** [comment]
I am experiencing this issue in 27.1.6. The only error in the log is below.

Restoring/Downloading any intermediate Version works as expected, this issue is only with the Initial Version.

I have also attached the browser console log.
[console-export-2024-2-1_12-2-51.txt](https://github.com/nextcloud/server/files/14128519/console-export-2024-2-1_12-2-51.txt)


`[webdav] Error: Error: Call to a member function getEncryptedVersion() on bool at <<closure>>

 0. /var/www/html/apps/files_versions/lib/Versions/LegacyVersionsBackend.php line 177
    OCA\Files_Versions\Storage::rollback("/myfile.ods", 1706804806, ["OC\\User\\User"])
 1. /var/www/html/apps/files_versions/lib/Versions/VersionManager.php line 103
    OCA\Files_Versions\Versions\LegacyVersionsBackend->rollback(["OCA\\Files_Ver ... "])
 2. /var/www/html/apps/files_versions/lib/Versions/VersionManager.php line 185
    OCA\Files_Versions\Versions\VersionManager->OCA\Files_Versions\Versions\{closure}("*** sensitive parameters replaced ***")
 3. /var/www/html/apps/files_versions/lib/Versions/VersionManager.php line 103
    OCA\Files_Versions\Versions\VersionManager::handleAppLocks(["Closure"])
 4. /var/www/html/apps/files_versions/lib/Sabre/VersionFile.php line 118
    OCA\Files_Versions\Versions\VersionManager->rollback(["OCA\\Files_Ver ... "])
 5. /var/www/html/apps/files_versions/lib/Sabre/RestoreFolder.php line 76
    OCA\Files_Versions\Sabre\VersionFile->rollBack()
 6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 160
    OCA\Files_Versions\Sabre\RestoreFolder->moveInto("target", "versions/0jsg/versions/162/1706804806", ["OCA\\Files_Ver ... "])
 7. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 612
    Sabre\DAV\Tree->move("versions/0jsg/versions/162/1706804806", "versions/0jsg/restore/target")
 8. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpMove(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
 9. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:MOVE", [["Sabre\\HTTP\\ ... ]])
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
11. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
12. /var/www/html/apps/dav/lib/Server.php line 365
    Sabre\DAV\Server->exec()
13. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
14. /var/www/html/remote.php line 172
    require_once("/var/www/html/a ... p")

MOVE /remote.php/dav/versions/0jsg/versions/162/1706804806
from 172.16.0.1 by 0jsg at 2024-02-01T16:34:14+00:00`

**Comment by solracsf** [comment]
Are you both using encryption?

**Comment by 0jsg** [comment]
In my case, Administration > Security > Server-side encryption is turned off.
I have attached the output of occ config:list.
[occ_config_list.txt](https://github.com/nextcloud/server/files/14132541/occ_config_list.txt)

**Comment by alperozturk96** [comment]
> Are you both using encryption?

Encryption is off.

From Log I saw this error.

Error
Call to a member function getEncryptedVersion() on bool

**Log**

[nextcloud_log.log](https://github.com/nextcloud/server/files/14178043/nextcloud_log.log)

**Comment by artonge** [comment]
Hello, could you confirm that the issue is not with shared files, but files that are initially empty when created?

**Comment by 0jsg** [comment]
This does appear to be the case in my testing.
