### ISSUE TITLE
Sharing folder which contains a shared file/folder fails

### ISSUE THREAD

**Issue by faulix** [nextcloud/server#4328]
### Steps to reproduce
1. Someone shares a file/folder with you
2. Save/move the file/folder to one of your folders
3. Try so share your folder with anyone

### Expected behaviour
As long as I have the full permissions for all containing files including the ones shared with me, I expect that sharing my folder is possible even though it contains an other shared folder.

### Actual behaviour
Error "Path contains files shared with you"

**Comment by MorrisJobke** [comment]
I guess this is expected behaviour, right @rullzer and @schiessle

**Comment by rullzer** [comment]
Yes. This is by design.

The owner of the files should always know who has access. If you share a topfolder of a share then this information is not there. We chose for a flat sharing model instead of a hierarchical model.

**Comment by faulix** [comment]
But I can directly share the file/folder with additional people, so where's the difference? In the end I can still share the file/folder with whoever I want, so why not conveniently by sharing the parent folder?

**Comment by rullzer** [comment]
Yes you can share the folder with who you want (if sharing permissions are given to you). But if you share the same folder the owner will know it. If you share the parent folder this becomes non trivial. We need to do a lot of booking them and this is just not doable from a performance/scalability point of view.

**Comment by faulix** [comment]
But then a valid tradeoff would be to check if the shared folder already have the required permissions and in this case to allow the sharing, wouldn't it be?

**Comment by MorrisJobke** [comment]
> But then a valid tradeoff would be to check if the shared folder already have the required permissions and in this case to allow the sharing, wouldn't it be?

Yes, that would be the solution, but the tradeoff here is performance and we just want to go for performance than for this solution.

**Comment by ppreiss** [comment]
Thank you for the explanation. 

I run into this issue with a shared folder containing many subfolders. How do I figure out _which_ subfolder is preventing me from sharing the parent folder? There are too many to check individually.

**Comment by ErikUden** [comment]
I would like for this issue to be reopened, especially due to the fact of federation. If someone of a different instance shares something with you, you can re-share it with a link by the local instance. The original creator of the share will have no idea this happened. Hence resharing directories with shared content (from a different instance) inside should be possible.

What am I trying to do?

Imagine I have pictures of someone, partially stored on a different Nextcloud instance, partially stored on mine. Lets say the other instance is for specific purposes (political, clubs, etc.) and my instance is for personal stuff. However, I'd like to have one place where all the images come together! I've compiled that place with all the images from both sources.

Now let's say that person asks “hey, can you send me all the images you have of me?”

Okay, now that I'm writing this I am realizing that all I need to do is share two links. Still, I think this should be possible, I still love Nextcloud in case you decide not to add this, though.
