### ISSUE TITLE
Making it possible to invite friends & family (but not the whole world) to create an account

### ISSUE THREAD

**Issue by keunes** [nextcloud/server#4359]
I know that in the admin panel I can create a new user account with a login and password and optionally an email address.

I'd like to request a new 'feature' where you, in the admin panel, **have a way to invite users to create an account** with your instance. I imagine that _you fill in their full name, email address_ (in future this could even be linked to the contacts app) and the groups they should belong to, and that _Nextcloud send them an email invite with a personal URL_ where users can choose their username + password.

That way **they can pick their own username and password**, hopefully increasing the chance they'll remember it (& this means I don't have to come up with this for them).

This would be a great benefit compared to the 'Registration' app since it would comply with password policy, enables me to select groups in advance, and - most importantly - **doesn't open registrations to the whole world (as does the Registration app)**. I just want to invite my family & friends; the whole world doesn't fit on my Raspberry Pi ;)

**Comment by LukasReschke** [comment]
This would be something that should be implemented in an own app such as the registration app. I'd recommend asking on https://help.nextcloud.com/ whether someone has interest but like the registration app this doesn't seem to be core of Nextcloud.

**Comment by keunes** [comment]
To be honest I don't see why this should be implement in a seperate app and not in core; it is just another (I would say more admin-friendly) method of registering new users, compared to the current method already present in core.
Core already allows you to add an account by making a username and password, why wouldn't it let you create an account by entering an emailaddress. It's not quite a 'feature' as a 'Calendar' or 'Mail', rather a very basic admin option?

**Comment by jphaskins** [comment]
I would just like to add my support for this feature.

Since the default install supports more than one individual via multiple accounts it must be an intended function. Using the user management features requires the admin knowing each user's password (or relying on each to change it). This results in a bad situation for both parties. A simple URL invite that could be shared through any channel would be a more private and secure method of allowing users to create their account.

I can understand it not being a priority but I really do believe it belongs in core. Thanks.

**Comment by ChrisU-bckspc** [comment]
I wish to have this feature, too.
Every time i add a new user i think "mail invite would be nice".
I hope we'll get this feature some day.

**Comment by tjwmagic** [comment]
I agree, my company started using NextCloud, and wanted to allow for easy user registration when a client needs access to our cloud, by simply sending an email through the system. Or simply having the user request it them self and letting them register, removing the IT department and creating a self-serve environment. 

This would be nice to have.

**Comment by sbaker-gsc** [comment]
Yes this is pretty much an essential for our needs. I'd love to implement this as a secure file sharing solution for research data... but without the ability for users to invite others it's a no-go - while at the same time the registration app is too open with no ability to restrict to only approved users.

**Comment by ITwrx** [comment]
IMHO, this is part of nextcloud's main use case... with most nextcloud instances you will want to invite at least some users instead of micro-managing their creds, including transmittting passwords securely (which can be non-trivial depending on circumstances). i can only imagine the insecure ways creds are being passed around/reused right now because of the current limitation.

@LukasReschke  **why** shouldn't this be in core? i would have thought it would be in scope from the beginning. also, from a security perspective, i think just about anything basic, having to do with user registration, should be implemented by core devs and get a look by you and any other security people. I typically won't enable any unoffical app having to do with critical core functions like user registration. 
Thanks

**Comment by tjwmagic** [comment]
The main issue I have with the registration app is users can register for the NextCloud instance if they know the registration URL. This is a really **bad** security. It's extremely hard for me to set up a user account because I have to create a dummy password, then send it to the user via email and walk them through how to change their password.  Which causes issues if that email were to be intercepted, lost, etc. 

I will also not install any unofficial app unless I can validate that it will not breach security. The downside is, I might have to move off of NextCloud due to its weak security with user registration. These features **should** be installed by default or at least available via an official app. I do not want a third-party creating a registration app for my server. 

@LukasReschke Please take a second look at the user registration and security for NextCloud. It's a great web-based file server. It just lacks what I would think "common sense" for user registration and security.

**Comment by kaffeeringe** [comment]
"Set the Send email to new user-checkbox allows you to leave the Password field empty. The user will get an activation-email to set his own password."

https://docs.nextcloud.com/server/13/admin_manual/configuration_user/user_configuration.html#creating-a-new-user

**Comment by ChrisU-bckspc** [comment]
Thank you for this hint. This is the solution i was looking for!

ChrisU

**Comment by mglinux** [comment]
Its not the best solution since I want new users to choose their own username.
