### ISSUE TITLE
[Bug]: Files larger than 100MB not uploading

### ISSUE THREAD

**Issue by N-Hertstein** [nextcloud/server#43729]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am using Nextcloud behind nginx proxy manager and cloudflare. I have given a few family members access to my Nextcloud server, however they cannot upload files larger than 100MB due to the cloudflare upload limit. Now I understand that I can change the max chunksize in the client config file, however this is not a real solution. I can't teach my gandpa how to installl teamviewer so I can fix his shit every time he has a new laptop. And businesses cannot be expected to change this for every pc in a large scale deployment. Since Cloudflare is so widely used either the default chunksize needs to be <100MB or I need to be able to adjust this from the server. 

### Steps to reproduce

1. Have a nextcloud server
2. Set it up with cloudflare
3. Install nexcloud client on family's computer
4. Wait until they inevitably have a file >100MB
5. Get constant errors
6. Get constant texts about errors 

### Expected behavior

1. Have a nextcloud server
2. Set it up with cloudflare
3. Install nexcloud client on family's computer
4. Wait until they inevitabaly 
5. Chunksize is <100MB resulting in a working system OR: Get errors and adjust chunksize in server

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
You can adjust `max_chunk_size` server side.
See docs or reach help at https://help.nextcloud.com

**Comment by joshtrichards** [comment]
> You can adjust `max_chunk_size` server side.

AFAIK this only changes it for the Web client. 

> And businesses cannot be expected to change this for every pc in a large scale deployment. 

Businesses often have other preferred ways of mass deploying internal software such as the Desktop client, including config customizations. In addition, as noted, it's not an issue for the Web client.

It's possible the Desktop client is being more aggressive than our Web client at determining maximum chunk size.

I think [the uploader in Web](https://github.com/nextcloud-libraries/nextcloud-upload/blob/9480a44ef982d610a9ed40afab9252063b24f13d/lib/utils/config.ts#L1) most of the time effectively uses the default of 10 MiB (unless the file is particularly large or the admin has changed it from the default).

I haven't fully been through the Desktop client's approach in this area, but I going from memory I got the sense Desktop may start out trying to use as few chunks as possible (and therefore much larger ones), whereas Web kind or does the opposite.

I may be wrong though because I only glanced at the code a bit back and so take with a grain of salt.

https://github.com/search?q=repo%3Anextcloud%2Fdesktop%20maxchunksize&type=code

The Desktop client also has a dynamic mode that adapts based on target duration parameters, which further complicates things (and I'm not aware of the Web client having any such thing).
