### ISSUE TITLE
[Bug]: Local files deleted when syncing after fresh install docker container 

### ISSUE THREAD

**Issue by flimofly** [nextcloud/server#43792]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Server side: TrueCharts Nextcloud 28.02 (enterprise train) on Truenas Scale (23.10.1 Cobia)
Client : macOS Nextcloud desktop client 3.12.0 (macOS 14.1.2)

Extant Nextcloud folder on client is populated with default files from NC server. All local files present in the folder are deleted. They are not present in Trash afterwards.

### Steps to reproduce

1. New install of docker container - TrueCharts enterprise train
2. Recreate users with existing username in the web interface
3. Log in as a user in the web instance
4. On the client, press sync in the NC app (menu bar)

Extant Nextcloud folder on client is populated with default files from NC server. All local files present in the folder are deleted. They are not present in Trash afterwards.

### Expected behavior

Files and folders present in the extant Nextcloud folder are synced to the server
Alternatively, a new folder called Nextcloud1 is created, populated by the files on the server.
Ideally, a warning is issued or choice is presented.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

None

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
It sounds like you're trying to sync a preexisting client with a replacement server. 

This is expected behavior:

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/restore.html#synchronising-with-clients-after-data-recovery

In a true server replacement situation you'd presumably have matching data already on the server-side... Or you'd follow the approach described in the above link to override treating the server as authoritative.

In your scenario you're doing neither. Either configure a second account in the client and treat the new server as a new server (which it sounds like it is)... Or follow the above documented approach.

**Comment by flimofly** [comment]
Thanks! 

TBH there should be a warning before deleting massive amounts of data. At the very least this data should be moved to trash, not permanently deleted.
