### ISSUE TITLE
Request to store file upload datetimestamp in the database

### ISSUE THREAD

**Issue by joopmartens** [nextcloud/server#4403]
The files_retention plugins currently uses the file modification date to verify if a file should be deleted instead of the upload date. This results into the situation that files are often deleted within a day because their modification date is often older than the retention period.

Using the upload date is currently impossible since this information is not being saved by Nextcloud.

See: [https://github.com/nextcloud/files_retention/issues/23](https://github.com/nextcloud/files_retention/issues/23)

Likely most people would like their retention period to be based on the upload date since that makes better sense for the use case to automatically cleanup uploaded files.

Because of this I would like to request a change to store the file upload date/time in the database so it can be used by plugins.

### Steps to reproduce
See: [https://github.com/nextcloud/files_retention/issues/23](https://github.com/nextcloud/files_retention/issues/23)

### Expected behaviour
File upload date/time stored into database

### Actual behaviour
File upload date/time not stored into database

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**List of activated apps:**
files_retention

**Comment by nickvergessen** [comment]
This was already reported in https://github.com/nextcloud/server/issues/3572

**Comment by lopezio** [comment]
Hi, I also face issues of several kinds with nextcloud deployments with the "new" behavior.

It does not only affect the retention plugin, but I have reported cases also privacy / security issues involving not wanting to share the actual modification date of a file. This is different with personal or shared synced folders, of course, where the retention of the original dates is almost always a wanted and expected feature.

In my opinion, since now we have this feature,  _ideally_, there should be:
- The inclusion of an upload time
- Retention app: Settings within the retention app where we can specify, for each selected tag, whether the rule applies to upload, creation, or modification time (default: upload).
- Settings (both server wide defaults and user) to specify if the server should overwrite creation/modification times with the upload times for the web client (here: either an offering is made to specify which kind of client, and if not, then in my opinion it should specify that it only applies to the web client)

Best,

Lorenzo

**Comment by szindel** [comment]
I would also very much like this feature.

**Comment by nickvergessen** [comment]
this is done nowadays, see #3572 and the comments and links there
