### ISSUE TITLE
[Bug]: Segmentation fault on cron every 15 mins

### ISSUE THREAD

**Issue by Dreamsorcerer** [nextcloud/server#44588]
### Bug description

Every 15 mins I get a report from cron.php which just says "Segmentation fault", with no further information.
This is happening on 28.0.4, it was also happening once or twice per day on 28.0.3. Not sure how many versions before it may have been happening, as I upgraded several major releases last month.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_

### Configuration report

```shell
Segmentation fault
```

### List of activated Apps

```shell
Segmentation fault
```

**Comment by Dreamsorcerer** [comment]
Adding some echos seems to have narrowed it down to this call:
https://github.com/nextcloud/server/blob/c93d44bb3feda711160bbf2e0aadff2a8179ef79/lib/base.php#L706

**Comment by Dreamsorcerer** [comment]
Further debugging narrows it down to here:
https://github.com/nextcloud/server/blob/61f2453a863914e513c6b9916e0b61fac9a6b18b/lib/private/AppFramework/Bootstrap/Coordinator.php#L129

Specifically, the `class_exists($applicationClassName)` call seems to cause the segfault when $applicationClassName is `OCA\Calendar\AppInfo\Application`.

**Comment by Dreamsorcerer** [comment]
The calendar is apparently at version 4.6.7, which seems slightly odd because the changelog for that project only lists versions upto 4.6.5.

**Comment by joshtrichards** [comment]
What PHP version and what distribution/version/architecture specifically?

Typically this is an OS level or PHP matter. We're not generally the root cause of these sorts of situations, since we're merely a PHP app.

The PHP folks suggest a backtrace to troubleshoot and report:

https://bugs.php.net/bugs-generating-backtrace.php

Might be worth checking your distro's package bug reports too.

> The calendar is apparently at version 4.6.7, which seems slightly odd because the changelog for that project only lists versions upto 4.6.5.

The changelog in the version specific branch has it:

https://github.com/nextcloud/calendar/blob/v4.6.7/CHANGELOG.md

And not all of our apps use GitHub Releases, but instead their artifacts are sent out via a dedicated releases repo where you can also find the log:

https://github.com/nextcloud-releases/calendar/releases/tag/v4.6.7

**Comment by Dreamsorcerer** [comment]
> What PHP version and what distribution/version/architecture specifically?

I included it in the original details, but it's Debian stable, with the default, included version of PHP (8.2).

**Comment by Dreamsorcerer** [comment]
> The PHP folks suggest a backtrace to troubleshoot and report:

Can't seem to get those instructions to work...

**Comment by joshtrichards** [comment]
> I included it in the original details, but it's Debian stable, with the default, included version of PHP (8.2).

Specific PHP versions are 8.2.x so it was a fair question (particularly not knowing the specific distro+release nor whether Sury - https://deb.sury.org/ - was being used):

https://www.php.net/ChangeLog-8.php#PHP_8_2

I also asked about architecture, for the record, since that can be relevant in these situations. :)

For what it's worth, we have a lot of Debian 12 installations and our general Docker image is Debian 12/Bookworm based. I haven't see this yet in any of my test environments (most are Debian/Docker and at least half of them probably w/ Calendar installed)... so whatever it is it may be something more unique to your environment that is bringing it out.

> Can't seem to get those instructions to work...

It may require compiling PHP with debug options. It's been awhile since I've had to do it.

Either way, this error is coming from your OS/distro or PHP. It's not an error we generate. Not much we can really do here... 

Have you modified any PHP config options, even slightly, from stock? If so, it might provide some further clues as to how else to reproduce this.

**Comment by Dreamsorcerer** [comment]
> I also asked about architecture, for the record, since that can be relevant in these situations. :)

Yeah, I already edited my response before you replied.

> Have you modified any PHP config options, even slightly, from stock? If so, it might provide some further clues as to how else to reproduce this.

These are the changes I make:

Change settings in `/etc/php/8.2/fpm/pool.d/www.conf`:
```
pm = static
pm.max_children = 50
pm.max_requests = 1000
```

Change settings in `/etc/php/8.2/fpm/php-fpm.conf`:
```
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 1m
```

Adjust `/etc/php/8.2/fpm/php.ini`:
 * Append to `disable_functions`: `shell_exec,exec,system`
 * Update values to:
 ```
realpath_cache_ttl = 3600
error_reporting = E_ALL
log_errors_max_len = 4096
html_errors = Off
post_max_size = 128M
upload_max_filesize = 128M
allow_url_fopen = Off
session.use_strict_mode = 1
session.cookie_secure = On
session.cookie_httponly = On
session.cookie_samesite = "Strict"
session.sid_length = 48
session.sid_bits_per_character = 6

opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.revalidate_freq=10
opcache.log_verbosity_level=2
opcache.file_cache=/var/tmp/php/
opcache.file_cache_consistency_checks=0
```
 * Add `apc.shm_size = 256M`

Copy for CLI (with hardlink):
```
cd /etc/php/8.2/cli/
rm php.ini
ln ../fpm/php.ini php.ini
```

**Comment by Dreamsorcerer** [comment]
I guess only the php.ini is relevant, as the error only occurs with CLI usage.

**Comment by Dreamsorcerer** [comment]
I think it's happening on FPM now, getting 502s since the server rebooted.
Trying to bypass the if conditions, it seems that `new $applicationClassName();` also fails when pointing to that class. So, seems to be an issue with that class, rather than the class_exists() function.

**Comment by Dreamsorcerer** [comment]
And, after editing the file that class is in (and the one for notes), it's all working again. No code change, just making an edit to the file seems to have fixed it.

Must have been something weird with opcache...
