### ISSUE TITLE
Set share_folder per user

### ISSUE THREAD

**Issue by elgesl** [nextcloud/server#4471]
Hello,

 I want to request the feature that the share_folder can be set per user (by the user) instead on server level.

**Current situation**:
In the moment, one can define in config.php via the value of share_folder where folders shared with a user are linked. For example if share_folder='/share' and user B shares folder DB with user A and user A shares folder DA with user B, then user A can access DB as /share/DB and user B can access DA as /share/DA. However per definition this can only defined on server level, i.e. for all users at the same time.

**Requested situation**:
I would like to have an option for every user (editable by the user), where this folder can be set. For example A could set 'his/her' share_folder='/share' and B 'his/her' share_folder='/' and therefore B can access DA in /share/DA while A can access DB in /DB.

Best regards,

Chris

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by DanielArmengod** [comment]
I'd like to express support for this feature request (although I must say I find OP's explanation a bit convoluted and difficult to follow).

Request: a user-configurable setting: default "shared with me" folder.

With the default settings, a user's root directory will soon become cluttered with shared files.

If a user wants to de-clutter their root folder, they have to sift through the contents of the root folder manually, as there is no option to "sort by share status". This is a bit tedious, and definitely error-prone. The left hand-side "Shared with me" category is of no use here, since items cannot be mass-selected when in this view.

Setting share_folder in config.php mitigates this, but presents difficulties with i18n (shared folder name is hardcoded) and UX (we're forcing our preferences onto users with this solution; perhaps they want different?)

**Comment by jospoortvliet** [comment]
@DanielArmengod very good description, yes. This will help de-clutter the root folder from incoming shares.

**Comment by Bibo-Joshi** [comment]
Hi! I'm aware that supporting an enhancement request should be done by reaction emojis (and I did), but since this issue has been inactive for a while and was declared as "not on the roadmap right now", I'd still like to ask, if there is the possibility to add it to the roadmap :)

**Comment by micheelengronne** [comment]
I want to symlink my Nextcloud folders with my local default folders (the famous 'music', 'videos', 'documents' available in every desktop). That way, I would like to symlink to a local 'shared' folder but the fact that every share is in root forbid me to do so.

I am aware that I can set it globally but the other users of my Nextcloud instance may have different strategies.

Can it be at least reopened ?

**Comment by Bibo-Joshi** [comment]
I head a go ad this and a WIP PR is at #28157
