### ISSUE TITLE
[Bug]: webdav files download Base64 encoded

### ISSUE THREAD

**Issue by the-djmaze** [nextcloud/server#44724]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you store a PDF file and then later download it, it is Base64 encoded.

### Steps to reproduce

```php
$fp = \fopen('file.pdf');
$oFiles = \OCP\Files::getStorage('files');
$oFiles->file_put_contents('Documents/issue-44724.pdf', $fp);
```

`https://nextcloud.example.com/remote.php/webdav/Documents/issue-44724.pdf`

---

Also see the default `https://nextcloud.example.com/remote.php/webdav/Documents/Nextcloud%20flyer.pdf`
![afbeelding](https://github.com/nextcloud/server/assets/3752035/d4effd85-3bd2-448b-a8b1-c85a86927765)

### Expected behavior

Transfered without encoding OR set the `Content-Transfer-Encoding` header.

### Additional info

https://github.com/the-djmaze/snappymail/issues/1541

**Comment by the-djmaze** [comment]
I've tested v25 and up.

@einhander should report here which version he/she/it/them uses.

**Comment by einhander** [comment]
@the-djmaze,  I use nextcloud 27.1.7

**Comment by joshtrichards** [comment]
I don't follow. The original PDF is downloaded. Are you suggesting that the downloaded file (`https://nextcloud.example.com/remote.php/webdav/Documents/Nextcloud%20flyer.pdf`) is base64 encoded when saved at the client? Because that's not my experience testing and checking the downloaded file from any of my Nextcloud Server instances. It would be a serious bug if so.

The response in the browser tools looks the same for any sort of binary download AFAIK - e.g. Download `https://github.com/the-djmaze/snappymail/releases/download/v2.36.0/snappymail-2.36.0.zip`. So I'm not sure that's a good indicator anything is being encoded in base64.

And `Content-Transfer-Encoding` isn't a valid header used in HTTP to my knowledge (well one can specify it but it doesn't do anything).

The linked bug report says this:

> Click on save to local PC or Nextcloud

So it sounds like this is happening even when Nextcloud isn't in the picture.

If I'm missing something, feel free to clarify.

**Comment by the-djmaze** [comment]
> The response in the browser tools looks the same for any sort of binary download AFAIK - e.g. Download `https://github.com/the-djmaze/snappymail/releases/download/v2.36.0/snappymail-2.36.0.zip`. So I'm not sure that's a good indicator anything is being encoded in base64.

You are right. I've tested this further and Firefox indeed shows almost all in base64 instead of binary data.
Some tests i did, didn't show in base64, but now they do.

So this is a browser thing.
