### ISSUE TITLE
JS tests failing on CI

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4487]
Seems related to https://github.com/karma-runner/karma-phantomjs-launcher/issues/126

**Comment by LukasReschke** [comment]
Let's just migrate away from the PhantomJS launcher and switch to headless Chrome instead: https://github.com/karma-runner/karma-chrome-launcher/pull/111

**Comment by ChristophWurst** [comment]
Ouch. This is bad. Headless Chrome doesn't qualify for a short-term solution as that PR has not been merged.

**Comment by ChristophWurst** [comment]
cc @nextcloud/javascript

**Comment by LukasReschke** [comment]
@MorrisJobke mentioned that pinning Karma 1.5.x might make sense as a temporary workaround.

**Comment by MorrisJobke** [comment]
I thought it is because the dependencies has changed, so I looked it up and this is the diff between working and not working:

<img width="302" alt="bildschirmfoto 2017-04-25 um 10 19 04" src="https://cloud.githubusercontent.com/assets/245432/25387288/b9421f5a-29a0-11e7-835d-8b404f139302.png">

That means we should check if pinning jasmine-core helps.

**Comment by MorrisJobke** [comment]
"Fix" is in #4494

Nevertheless we should migrate to the other launcher if this is the only option. 🙈
