### ISSUE TITLE
Column is type Bool and also NotNull, so it can not store "false"

### ISSUE THREAD

**Issue by yuriry** [nextcloud/server#45576]
It seems this constraint is incorrect:
https://github.com/nextcloud/server/blob/a5fd623469b40c44881e4635de073d334b371bae/lib/private/DB/MigrationService.php#L569

Oracle can have not null constraint and can store both true and false values
https://oracle-base.com/articles/23/boolean-data-type-23

*Boolean columns can have NOT NULL and CHECK constraints applied to them. They can be part of UNIQUE, PRIMARY KEY or FOREIGN KEY constraints.*

The same is true for PostgreSQL:
https://www.postgresql.org/docs/current/datatype-boolean.html

PostgreSQL example:
```SQL
create table foo (a bool not null default false);
insert into foo (a) values (false);
insert into foo (a) values (true);
select * from foo;
--  a 
-- ---
--  f
--  t
-- (2 rows)
drop table foo;
```
I ran into this problem when migrating my old app from Nextcloud v18 to v30.  The app still works in V25 without problems.

**Comment by kesselb** [comment]
We added constraint 2022-04 with https://github.com/nextcloud/server/commit/e20d5fa7fc567b0762226b79572f9aca6609e59f.

Oracle 23ai added support for booleans and was released 2024-05. 
We still support older versions of Oracle. 

There are also some quirks with our OCI integration: https://github.com/nextcloud/server/issues/45630.

I assume the check/constraints will stay for a while because Oracle 23ai was just released.
My recommendation: Save yourself some trouble and use an integer instead of boolean.

**Comment by yuriry** [comment]
> We added the check/constraint 2022-04 with [e20d5fa](https://github.com/nextcloud/server/commit/e20d5fa7fc567b0762226b79572f9aca6609e59f).
> 
> Oracle 23ai added support for booleans and was released 2024-05. We still support older versions of Oracle.
> 
> There are also some quirks with our OCI integration: #45630.
> 
> I assume the check/constraint will stay for a while because Oracle 23ai was just released. My recommendation: Save yourself some trouble and use an integer instead of boolean.

Sorry I didn't realize Oracle added support for boolean types (SQL99) only last month 😢
