### ISSUE TITLE
[Bug]: .mjs files : Nextcloud should not force admins to modify a working configuration

### ISSUE THREAD

**Issue by canoine** [nextcloud/server#45748]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As I said in the chosed #43757, I think the way Nextcloud tests itself is wrong. My Nextcloud instances (apache webservier behind a nginx reverse proxy) do work as expected, but Nextcloud says not, because it can't connect to the reverse proxy to pass its tests. 

So, if I understand well, my Nextcloud instances want me to modify a working configuration, only to suppress some warning messages. Which is, for me, not normal.

### Steps to reproduce

1. Do not configure Nextcloud as it wants
2. Update it regularly
3.

### Expected behavior

Nexcloud reports only real problems.

### Installation method

Other Community project

### Nextcloud Server version

29

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
It is a setup check, so it tries to check if you have configured your infrastructure correctly to help you with finding issues.
If you set up your infrastructure in a way Nextcloud can not perform this health checks (either by a faulty DNS setup or a firewall rule), then it is up to you to ignore it.

Meaning:
This is only a **warning** because we can not help you checking your installation, it is **not** an error.
If you think it is ok for your usecase, then simply ignore the warning, that what it is for.

> So, if I understand well, my Nextcloud instances want me to modify a working configuration, only to suppress some warning messages. Which is, for me, not normal.

What would be the alternative? Silently ignore it?
The test has three possible outcomes:
1. Success -> Test could run and was successful -> Admin does not need to check anything
2. Error -> Test could run and failed -> Admin needs to fix the setup
3. Warning -> Test could not run. This means either it is broken or not but we need to warn the admin that they need to validate it manually that everything is working.

**Comment by canoine** [comment]
> It is a setup check, so it tries to check if you have configured your infrastructure correctly to help you with finding issues. If you set up your infrastructure in a way Nextcloud can not perform this health checks (either by a faulty DNS setup or a firewall rule), then it is up to you to ignore it.

A good tutorial is better than a bad check.

> Meaning: This is only a **warning** because we can not help you checking your installation, it is **not** an error. If you think it is ok for your usecase, then simply ignore the warning, that what it is for.

Not easy to ignore : 
![Capture d’écran_2024-06-13_12-24-09](https://github.com/nextcloud/server/assets/8430237/a9674ab5-3c5a-4414-a32d-c9cb6398ab7f)

I precise that **all** the warnings shown here are useless, as this instance does work as expected.

> What would be the alternative? Silently ignore it?

Yes ! As already said, a good tutorial is better than a bad check.
