### ISSUE TITLE
Update from 20.0.14

### ISSUE THREAD

**Issue by qqchdelouis** [nextcloud/server#45744]
I inherited an 20.0.14 NC instance on an 18.10 Ubuntu server. I would like to update the tech stack, and I'm having problems installing the next required version of PHP on such an old server. 

My preferred work-around is to move the 20.0.14 NC instance to a 24.04 Ubuntu server and then try to make the updates there.  To that end, I was able to install an old version of PHP (7.2) on the new server.  I couldn't figure out how to install an old version of MariaDB.

I have some very basic questions, and the NC Web site doesn't render any help pages.

0/. How can I install an old version of NC (20.0.14 or 21.0.0) on a 24.04 Ubuntu server. Is there a guide for that ? 

1/. Can an old version of NC work on the current version of MariaDB ? Or must I use MariaDB 10.1.38 (currently in use for NC 20.0.14) ? Is there an easy installation guide for old versions of MariaDB (as I go through the process of upgrading NC) ?

2/. My plan was to migrate the NC directory from `/var/www` from one server to the other if I could not easily install NC 20.0.14 on the new server. Do I need a 20.0.14 NC install, or can migrating the directory (and updating the PHP config file) suffice ?  Do you recommend a process to update the current 20.0.14 NC instance other than migrating it to a 24.04 Ubuntu server (where the updates will be made) ?

**Comment by joshtrichards** [comment]
Hi @qqchdelouis - I suggest posting your query to the Community Help Forum - https://help.nextcloud.com. It may also be worth searching there (migrations - including dealing with different PHP versions/etc - are a common topic). You may find the [Migrating to a different server](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/migrating.html) section of the Admin Manual helpful too. I'm going to close this issue out here, since this is a bug reporting channel for development. I wish you the best of luck and may see you over there on the forums myself!
