### ISSUE TITLE
Navigation entries hard to see on normal monitors

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#4627]
Testing master right now.

Just a quick photo how the news app looks on a normal 22" 1980p monitor

![news](https://cloud.githubusercontent.com/assets/195053/25583407/e94b806a-2e91-11e7-9472-86cf6f06b358.jpg)

Can you see which entry is active? I find it very hard since the 2px? blue border seems to merge with the display border.

@jancborchardt

**Comment by LukasReschke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
I would say the main issue here is that there’s a lot of stuff going on ad it’s all battling against each other. How about:

- Only highlighting the _one_ row which is active, not the full containing folder
- Removing the gradient effect for folders
- I assume the orange entry is highlighted because of an error? That could be more elegantly done via an icon like in Contacts: https://github.com/nextcloud/contacts/pull/85 (the screenshots seem to be broken, but it’s an icon-error on the right of the row. No additional color.)

**Comment by BernhardPosselt** [comment]
Agree on everything. However even with everything addressed the active entry highlight merges with the display border. There should be something that separates the blue bar from the border (like a white bar, comparable to white subtitles with black border for movies) or an additional visual hint that this entry is active (e.g.: use a bullet point, extend color further with a gradient, also place it on the right side, underline, etc etc etc).

I don't have a preferred way of solving it, it's just that the current approach is not enough for me to quickly find the highlighted entry. And I'm neither visually impaired nor do I need glasses (according to my doctor :))

**Comment by jancborchardt** [comment]
@juliushaertl do you think we should go back to highlighting the full row? cc @nextcloud/designers

**Comment by juliushaertl** [comment]
@jancborchardt I think we should actually just increase the width of the activity indicator. For nested lists, we need to make sure that only the active submenu entry has the active indicator:
![bildschirmfoto vom 2018-03-19 16-23-42](https://user-images.githubusercontent.com/3404133/37604792-1477a3f6-2b92-11e8-9e09-e2f20cca4309.png)
