### ISSUE TITLE
Use png for logo in email header

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4647]
Gmail and Inbox do neither on web nor native support SVG images. We need thus to use a regular image in our emails.

**Comment by LukasReschke** [comment]
The link is generated by calling `\OCA\Theming\ThemingDefaults::getLogo` in `\OC\Mail\EMailTemplate::addHeader`. So I suppose we either add a parameter like `$svg = true` to `getLogo` or we add another function. Opinions?

**Comment by jancborchardt** [comment]
Yeah, just getLogo I guess? We previously used a gif for the emails so it worked on all platforms. Was it removed because that’s not necessary anymore, by checking on caniuse.com or so? cc @Espina2 @MorrisJobke

**Comment by MorrisJobke** [comment]
> Yeah, just getLogo I guess? We previously used a gif for the emails so it worked on all platforms. Was it removed because that’s not necessary anymore, by checking on caniuse.com or so? cc @Espina2 @MorrisJobke

I guess it was removed due to "we want to use the theming logo". Which is sometimes an SVG, sometimes a PNG and sometimes a JPG.



> by checking on caniuse.com or so?

This doesn't work, because this highly depend on the email provider. Gmail does other sanitising than outlook than web.de, than ... :/ That's the general problem with emails. And also the reason why we use a massive amount of `<table>` ... something like 20-50 per email.

**Comment by michag86** [comment]
This is only working with default logo. If you use custom logo (svg) set by theming app, this is not working.
Is there a way to get this working?
cc @MorrisJobke @LukasReschke
