### ISSUE TITLE
When changing file extension ask for confirmation

### ISSUE THREAD

**Issue by T0mWz** [nextcloud/server#46528]
We sometimes see users changing a file name, unintentionally / unknowingly deleting the extension dot or removing the whole extension.  After which they cannot open the document because it is no longer recognized as such, resulting in user confusion.

Where on an operating system is explicitly asked for confirmation when accidentally changing / deleting an extension.
Is there a possibility to check if there is still an extension present when editing, or else give a notification?

Example what an OS will ask you, by changing an extension.
![remove_extension](https://github.com/user-attachments/assets/de59fc62-36cb-4239-b782-08a847bca78e)
![change_extension](https://github.com/user-attachments/assets/c3eff7ee-f861-4edb-9e34-8bea4af74618)

**Comment by jancborchardt** [comment]
Sounds reasonable and helpful indeed. @sorbaugh @AndyScherzinger @marcoambrosini for Files planning.

**Comment by AndyScherzinger** [comment]
I'd agree, while @T0mWz mentioned the OS level. So yes, I think this seems reasonable in general and something you can catch on the client level, so (since we are in the server repo) it makes sense to catch this in the WebUI and is would likely also be easily doable for the Mobile apps, yet for Desktop OS we would need to rely on the OS either asking the user, or not asking the user. Screenshots are from MacOS, but I can't say how the different Linux distros or rather their Desktop/file manager handle such renames - Windows behaves the same way like MacOS.

So I would say web and Mobile should check if the file extensions (characters _after_ the last dot changed) and if so launch an expicit confirmation screen with an explanation of the potential consequences as shown above.

**Comment by jancborchardt** [comment]
Yup, that’s how I also understood, as a function of the web interface (and mobile, yup).

**Comment by sorbaugh** [comment]
This would be a really nice QoL improvement. We'll look into it.

**Comment by sorbaugh** [comment]
This is a Frontend only task. 

Some notes:
- [ ] Also add a "don't ask me again" option
- [ ] Add a config option 
- [ ] Add the Dialog (probably needs to be added to only 1 place)

Estimation: 3-5 days

**Comment by sorbaugh** [comment]
Assigning @Fenn-CS

**Comment by marcoambrosini** [comment]
<img width="454" alt="Image" src="https://github.com/user-attachments/assets/e3099e55-5a7d-43fd-afdf-667987cc725d" />

Looks great, will the don't ask again part be implemented? Or is it tracked somewhere else?

**Comment by marcoambrosini** [comment]
Problem: It's currently impossible to rename a file, only to change its format. Don't know if this is related to the pr addressing this issue. 

cc @sorbaugh @nfebe
