### ISSUE TITLE
Missing expected parameters in change user hook when setting avatar

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#4654]
When setting the avatar from the personal page I get an error in my log

```
{"reqId":"NlqXrDbK99wl1enmvnp3","level":2,"time":"2017-05-02T09:12:26+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"no app in context","method":"POST","url":"\/avatar\/cropped","message":"Missing expected parameters in change user hook","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.16"}
{"reqId":"NlqXrDbK99wl1enmvnp3","level":2,"time":"2017-05-02T09:12:26+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"no app in context","method":"POST","url":"\/avatar\/cropped","message":"Missing expected parameters in change user hook","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.16"}
```

@schiessle I think this might be because of your changes to the verification stuff there.

**Comment by juxorevo** [comment]
I have the same issue on nextcloud 10.0.3.2

**Comment by ChristophWurst** [comment]
When the avatar is changed, we first [unset it and emit the changes](https://github.com/nextcloud/server/blob/75c437a96a845e149f0054d28d779d6f486d27fb/lib/private/Avatar.php#L158) and then eventually [set it to the new value](https://github.com/nextcloud/server/blob/75c437a96a845e149f0054d28d779d6f486d27fb/lib/private/Avatar.php#L139). The problem is that we're not passing the new `value`. Not sure if that even makes sense for the avatar.

**Comment by MorrisJobke** [comment]
@schiessle @LukasReschke @rullzer @ChristophWurst Need to be moved to 12.0.1

**Comment by Railsimulatornet** [comment]
Same Problem with Nextcloud 12.02

**Comment by MorrisJobke** [comment]
Same as #3375 ?

**Comment by MorrisJobke** [comment]
@schiessle 🏓
