### ISSUE TITLE
File tags showing as the tag id not tag name

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#46695]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I enable collaborative tags app I observe strange behaviour clicking on the tags section:
![image](https://github.com/user-attachments/assets/ee7e043c-c034-489a-9755-ecad419d372c)

### Steps to reproduce

1. Enable Collaborative tags app
2. Go to tags
3. Observe the list of figures

### Expected behavior

As far as I understand here I have to see the list of tags or something else?

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by max-nextcloud** [comment]
Observing the same. Looks like the tag ids are listed instead of the tag names. When I click on one of the folders I actually do see a tagged folder. If I click on that it tries to open the folder id in the tags url (`files/tags/84`). Once i change that to `files/files/84` it actually opens the right folder. I'll create a screencast.

[Bildschirmaufzeichnung vom 23.07.2024, 12:28:07.webm](https://github.com/user-attachments/assets/2ba299d9-b2b1-4de7-8d8a-5b37c0e90c8f)

**Comment by J-Doc** [comment]
Hi,

I confirm this behavior since 28.0.8.

![image](https://github.com/user-attachments/assets/e061e698-e0d5-44b7-9687-84677efa644c)

**Comment by mdrobisch** [comment]
Hi,
same behavior for the actual version 29.0.4 (snap-install).
Only the ids of the tags get listed.

Imho this was working ok in 29.0.4 and seems a regression of the update from 29.0.2.

**Comment by thekk1** [comment]
This problem seems to be self-made as it is close to these bugs:
https://github.com/nextcloud/groupfolders/issues/2430
https://github.com/nextcloud/groupfolders/issues/2527
https://github.com/nextcloud/groupfolders/issues/3068

I would assume that you guys do not test your own software before release it.
This generates a whole bunch of work and time waste for thousand of other people.
It's a pity.

**Comment by J-Doc-Hugues** [comment]
hello  @susnux , 
as you are involved to fix issues/3068 which is quite near of this issue, have you an idea about this issue which makes non-operational 28 & 29 versions for everyday's users  ?
Thanks for help   : - )
    Hugues

**Comment by hamiltra** [comment]
This issue also came up in the [Support channel](https://help.nextcloud.com/t/file-tags-showing-as-the-tag-id-not-tag-name/198938).

**Comment by J-Doc-Hugues** [comment]
Thank to you  @susnux @skjnldsv @joshtrichards     ;-)

**Comment by ostasevych** [comment]
are any workarounds to fix the display of tags immediately?

**Comment by susnux** [comment]
No, you will have to wait for 29.0.5

**Comment by skjnldsv** [comment]
> What about the backport to v28?

28.0.9 :)
