### ISSUE TITLE
Contacts drop down too short if only one result shown

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4744]
* open the contacts drop down
* search for a term where only one contact is returned
* open the three dots menu
* expected: menu is shown properly
* actual: menu is cut and you need to scroll

<img width="390" alt="bildschirmfoto 2017-05-08 um 12 15 06" src="https://cloud.githubusercontent.com/assets/245432/25815979/3df7e42c-33e8-11e7-9b93-34a1863f6d30.png">

cc @georgehrke @ChristophWurst

**Comment by ChristophWurst** [comment]
Caused by the overflow-y: https://github.com/nextcloud/server/blob/dfa3aaa0c63c63e4fc074551381ade97da657057/core/css/styles.scss#L1093

I could, however, not fix it. Neither did it help to move the overflow to a parent element (the search input would be scrolled too) nor could I style this with the help of flexbox. I'm a bit clueless here. @nextcloud/designers ideas/recommendations?

**Comment by jancborchardt** [comment]
It was actually the height:100% which was missing. :) Pull request at https://github.com/nextcloud/server/pull/4889
