### ISSUE TITLE
[Bug]: Filename not validated when calling `IFolder->newFile()`

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#47563]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With the new [`IFilenameValidator` implementation](https://github.com/nextcloud/server/pull/46371) I would expect `IFolder->newFile()` to throw an error if passed file name is invalid. But it seems like that's not the case. `newFile()` still returns a File object and only further operation on this object fail. I guess there's a bug somewhere.

I discovered this issue while developing https://github.com/nextcloud/text/pull/6271.

### Steps to reproduce

1. Call `IFolder->newFile()` with windows compatibility turned on and an invalid filename as argument
2. See that it returns a File object instead of throwing an exception

### Expected behavior

I would expect `IFolder->newFile()` to throw an error if passed file name is invalid.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
This is expected behavior. 
You need to check the validity before creating. 

It is only checked in webdav. The reason is that we use that api also for internal things that break with that validation (setup, appdata, updater).

So all user facing files should be validated but the IFolder and FilesView api are also used for private stuff

**Comment by mejo-** [comment]
Ok, thanks for clarification. I would have expected server functions to do the validation when a file gets created. Let's close this then.

**Comment by susnux** [comment]
>  I would have expected server functions to do the validation when a file gets created.

Yes normally agree, but those functions also can be used for app data, which does not have those limitations.
So no validation, thats why we have the public interface `\OCP\Files\IFilenameValidator`

**Comment by kesselb** [comment]
It looks like we already validate `oc_filecache.path` (4000), but not `oc_filecache.name` (250). Since appdata is also tracked in `oc_filecache`, I’d suggest reopening this issue and ensuring that `newFile` / the FileApi at least validates whether records with such information (e.g. names longer than 250) can actually be written.
