### ISSUE TITLE
Rework theming logic to invert header icon color

### ISSUE THREAD

**Issue by justin-sleep** [nextcloud/server#4776]
The current method of determining whether or not to invert the color for header icons (after 68a63ad3f33c683d726219a508bb31de7b9ab1d0) is insufficient.  Currently, it allows darker icons on a fairly dark background, e.g. my current theme color:

![1494362061](https://cloud.githubusercontent.com/assets/14955039/25871547/7eb6a15c-34cd-11e7-8df4-8520412a63ad.png)

One possible solution would be to raise the lightness threshold for inverting the colors.  This is what it looks like after I raised the threshold past 55 (my background color's lightness):

![1494363045](https://cloud.githubusercontent.com/assets/14955039/25872131/4a19a76c-34cf-11e7-9e5f-9cf61d1d5adb.png)

As what looks 'better' may vary from person to person, another possible solution to this would be to simply allow the user a button in the theming interface to toggle dark/light header icons.

### Steps to reproduce
1. Open theming settings
2. Change background color to a value straddling the lightness threshold (e.g. \#745CBA)

### Expected behaviour
The header icon colors should not be dark.

### Actual behaviour
The header icon colors invert to their dark variants.

**Comment by MariusBluem** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
@justin-sleep Makes sense, but we should make sure that there isn't an issue with another color with this new threshold.

**Comment by nickvergessen** [comment]
@juliushaertl could you have a look again.

Seems like `OCA.Theming.inverted` is set to true but not used by the header menu:

![dateien_-_jobisch_cloud_-_2017-07-31_11 14 57](https://user-images.githubusercontent.com/213943/28771349-bcaa1f1a-75e2-11e7-8b4a-c8509a439c36.png)

Notifications icon is black because it uses the value.
https://github.com/nextcloud/notifications/blob/ca1977cf6ee28c835985892ff6f74c6f13630db8/js/app.js#L388

This worked in 11, now broken on 12

**Comment by MorrisJobke** [comment]
Fixed in #6344

**Comment by jancborchardt** [comment]
Good proposal @justin-sleep! More design feedback and contributions are appreciated :)
