### ISSUE TITLE
Group admins cannot see disabled users

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#4789]
### Steps to reproduce
1. Create user `ray` and `paul`
2. create group `marketing`
3. assign `paul` to group `marketing`
4. make `ray` to group admin of `marketing`
5. login as `ray` and go to user management
6. disable `paul`
7. Click on Disabled to list the disabled users

### Expected behaviour
`ray` should appear under disabled

### Actual behaviour
`ray` does not appear under disabled (empty response)

### Server configuration
**Nextcloud version:** 12 beta 2
**Updated from an older Nextcloud/ownCloud or fresh install:** update from 12 beta 1

#### Nextcloud log (data/nextcloud.log)
```
no errors logged
```

#### Browser log
```
/index.php/settings/users/users?offset=0&limit=50&gid=_disabledUsers&pattern=
HTTP Code 200
Empty response
```

**Comment by benediktg** [comment]
I can reproduce this (I also have NC 12 beta 2) but if I add `ray` to the `admin` group then `ray` can see `paul` in "deactivated".

Maybe this is not a bug but a feature?   
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
> Maybe this is not a bug but a feature?
> cc @MorrisJobke

Looks like bug.

cc @blizzz @nickvergessen

**Comment by Neraste** [comment]
Is there any progress about this issue? I experience the same problem…

**Comment by Neraste** [comment]
It seems that this is due to the way [`settings/Controller/UsersController.php`](https://github.com/nextcloud/server/blob/63d98574e983116e20b056af223683efde8fb4de/settings/Controller/UsersController.php#L295) works.

Disabled users are listed using a fake `_disabledUsers` group, even if they are actually member of a real group. When you're not a super admin, the `index` method calls the `displayNamesInGroup` method with `_disabledUsers` as arguments, which returns an empty array, because there is no such a group.

I have tested a quick solution where listing disabled users lists all disabled users for the groups the current user is sub admin of ([line 342](https://github.com/nextcloud/server/blob/63d98574e983116e20b056af223683efde8fb4de/settings/Controller/UsersController.php#L342)). It works as expected. What remains is the counter for groups with disabled users, as it count them as well. I will propose a PR as soon as possible.
