### ISSUE TITLE
Asturian language is missing

### ISSUE THREAD

**Issue by enolp** [nextcloud/server#4820]
### Steps to reproduce
1. Go to user settings
2. Go to the language selector
3. See that Asturian is missing

### Expected behaviour
The possibility to change Nextcloud language to Asturian

### Actual behaviour
Asturian language is missing

### Server configuration

**Operating system**:
Raspbian

**Web server:**
Lighttpd

**Database:**
MariaDB

**PHP version:**
5

**Nextcloud version:**
12.0 Beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 11.0

Additional information: Right now I'm the only active translator of NextCloud on Transifex so I wonder if you could make me coordinator of the Asturian language. I'll appreciate that. Thank you.

**Comment by MorrisJobke** [comment]
This is because the resources `core` and `settings` on transifex are less than 50% translated. Once this percentage is reached it will automatically appear.

https://www.transifex.com/nextcloud/nextcloud/translate/#ast/core/90993966
https://www.transifex.com/nextcloud/nextcloud/translate/#ast/settings-1
