### ISSUE TITLE
[Bug]: Outdated Mariadb version 10.5.x?

### ISSUE THREAD

**Issue by mat-m** [nextcloud/server#48271]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With Nextcloud Hub 9 (30.0), I now see a warning about MariaDB 10.5.

![image](https://github.com/user-attachments/assets/f6f7dd9f-97ce-493d-9188-a6a3bc49958b)

### Steps to reproduce

1. Deploy a docker imahe of Nextcloud v30
2. Go to Administration settings 
3. Wait for the security scan to complete

### Expected behavior

No warning on outdated version for software provided by the docker compose file

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> No warning on outdated version for software provided by the docker compose file

You control your Compose file, not us. And we don't provide MariaDB. :-) So specify a different MariaDB version if you like. :) 

We periodically update requirements.

The supported versions (as well as most recommended) for use with Nextcloud Server v30 are here:

https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server

The supported versions for use with v29 are here:

https://docs.nextcloud.com/server/29/admin_manual/installation/system_requirements.html#server

Now all that said, dmittedly 10.5 was supported during the pre-release cycle for v30 the last time I updated those checks (#45241). I hadn't realized there was a second pass that bumped it out for the v30 final. There's a chance that was an oversight since 10.5 is an LTS release that [still has a few more months of life left](https://mariadb.org/about/#maintenance-policy) in it (5/2025). I doubt it'll have any immediate ramifications since we were testing against it until recently (#46121), but I'd suggest you should prepare to move up either way. Plus we've been [recommending 10.6 for the last few majors](https://docs.nextcloud.com/server/27/admin_manual/installation/system_requirements.html#server) so it really shouldn't be news. :)

**Comment by susnux** [comment]
> admittedly 10.5 was supported during the pre-release cycle for v30

No, the support was already dropped since June (included in beta 1).
It is also documented since that date: https://github.com/nextcloud/documentation/pull/11934/files

---

As already mentioned this seems to be a problem with your installation method which seems not to be any of the official supported (archive, VM or docker all-in-one). So please check this with the provider of your docker compose file.

Especially if you just use docker images I recommend to use 10.6 or better directly upgrade to 10.11

**Comment by mat-m** [comment]
Ah, my bad, forgot to update the docker-compose.yml file...
Just did a pull/down/up, but that works only for minor versions. I will remember
