### ISSUE TITLE
X-Frame-Option DENY - NGINX

### ISSUE THREAD

**Issue by gfelot** [nextcloud/server#4863]
### Steps to reproduce
Fresh install of an Ubuntu 16.04 server + Nginx + Owncloud
=> Got a warning about `X-Frame-Option` header not set to `SAMEORIGIN`

Some search lead me to : https://github.com/nextcloud/server/issues/4764
and the release note.

Even with the the header commented `#add_header X-Frame-Options SAMEORIGIN;` I still have the warning.

In Chrome dev tool I can see this header set to `DENY`.
<img width="1360" alt="screen shot 2017-05-14 at 23 38 43" src="https://cloud.githubusercontent.com/assets/7879555/26037991/09d0b7d4-38ff-11e7-9c14-48fdca124963.png">

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Ubuntu 16.04 LTS
**Web server:**
Nginx 1.10
**Database:**
MariaDB
**PHP version:**
PHP7.0.15
**Nextcloud version:** (see Nextcloud admin page)
11.X

Nginx server block 

```
upstream php-handler {
    server unix:/var/run/php/php7.0-fpm.sock;
}

server {
    listen 80;
    listen [::]:80;
    server_name cloud.gfelot.xyz;
    # enforce https
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name cloud.gfelot.xyz;

    include          snippets/ssl-cloud.conf;
    include          snippets/ssl-params.conf;

    # Add headers to serve security related headers
    # Before enabling Strict-Transport-Security headers please read into this
    # topic first.
    add_header Strict-Transport-Security "max-age=15768000";
    #add_header X-Frame-Options SAMEORIGIN;
    #add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;

    # Path to the root of your installation
    root /var/www/nextcloud/;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # The following 2 rules are only needed for the user_webfinger app.
    # Uncomment it if you're planning to use this app.
    #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json
    # last;

    location = /.well-known/carddav {
      return 301 $scheme://$host/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host/remote.php/dav;
    }

    # set max upload size
    client_max_body_size 512M;
    fastcgi_buffers 64 4K;

    # Disable gzip to avoid the removal of the ETag header
    gzip off;

    # Uncomment if your server is build with the ngx_pagespeed module
    # This module is currently not supported.
    #pagespeed off;

    location / {
        rewrite ^ /index.php$uri;
    }

    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
    }
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
        deny all;
    }

    location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        #Avoid sending the security headers twice
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass php-handler;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    location ~ ^/(?:updater|ocs-provider)(?:$|/) {
        try_files $uri/ =404;
        index index.php;
    }

    # Adding the cache control header for js and css files
    # Make sure it is BELOW the PHP block
    location ~* \.(?:css|js|woff|svg|gif)$ {
        try_files $uri /index.php$uri$is_args$args;
        add_header Cache-Control "public, max-age=7200";
        # Add headers to serve security related headers (It is intended to
        # have those duplicated to the ones above)
        # Before enabling Strict-Transport-Security headers please read into
        # this topic first.
        add_header Strict-Transport-Security "max-age=15768000;
        #  includeSubDomains; preload;";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;
        # Optional: Don't log access to assets
        access_log off;
    }

    location ~* \.(?:png|html|ttf|ico|jpg|jpeg)$ {
        try_files $uri /index.php$uri$is_args$args;
        # Optional: Don't log access to other assets
        access_log off;
    }
}

**Comment by ToeiRei** [comment]
same here with 12 on a gentoo/nginx box.

**Comment by Ciiss0u** [comment]
My headers and security config are set in a /etc/nginx/security.conf file, called in http block in nginx.conf in order to aply a global security policy to all server blocks : 

extract of my nginx.conf : 
`http {
  [...]
  include /etc/nginx/security/*.conf;    #includes security conf file
  include /etc/nginx/sites-enabled/*;
  [...]`

my security.conf :
`###  All available SSL certs. To make Curl and other thing works, used LetsEncytpt's certs & keys have been symlinked form /etc/letsencrypt/live/sky-fvt.com/...
ssl_certificate /etc/ssl/certs/fullchain.pem;
ssl_certificate_key /etc/ssl/private/privkey.pem;
#  DH 4096 generated by openssl
ssl_dhparam /etc/ssl/private/dhparams.pem;
#  ssl session config and reneg
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_session_tickets off;

###  modern configuration. tweak to your needs.
ssl_protocols TLSv1.2;
ssl_ciphers "ECDH+AESGCM256:DH+AESGCM256:ECDH+AES256:SH+AES256:RSA+AESGCM256:RSA+AES256:!aNULL:!MD5:!kEDH";
#ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-S HA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES25 6-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DE S:!RC4:!3DES:!MD5:!PSK';
ssl_prefer_server_ciphers on;

# OCSP Stapling ---
# fetch OCSP records from URL in ssl_certificate and cache them
ssl_stapling on;
ssl_stapling_verify on;

#HPKP https://report-uri.io/home/pkp_hash
# X4 bkp added => commented due to bug SSLTEST Qualys
add_header Public-Key-Pins 'pin-sha256=""; pin-sha256=""; pin-sha256=""; pin-sha256=""; max-age=2592000; includeSubdomains;';

# HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months) (31536000 seconds = 12 months)
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload;";

#Referrer Policy https://blog.appcanary.com/2017/http-security-headers.html
add_header Referrer-Policy "no-referrer";

#### NOT COMPATIBLE WITH NGINX PROXY PASS TO EMBY, FA icons sites, etc. SET IT BY SUBDOMAINS IF YOU WANT (ALREADY SET FOR OWNCLOUD/NEXTCLOUD IN NGINX CONFIG SAMPLE)
# Content Security Policy (CSP)
# https://www.owasp.org/index.php/Content_Security_Policy
#add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:;";

# Add headers to serve security related headers
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;`

So i have to "REMOVE" This header in nextcloud config. and nginx module of nginx do this well, on debian install it with : 
`apt install libnginx-mod-http-headers-more-filter`

Then in  /etc/nginx/sites-enabled/nextcloud.conf : 
`upstream php7-handler {
    server unix:/var/run/php/php7.1-fpm.sock;
}

server {

    listen 8443 ssl;
    server_name cloud.sky-fvt.com 192.168.0.250;

    ###
    #SSL / HEADER / & Others security relative parameters are now globally sets in /conf.d/secyrity.conf (loaded before the sites)
    ###
    #Remove X-Frame-Options header : header has been moved to the PHP processing and outside of .htaccess so that applications can decide themselves if they want to be iframed. For example for iframing a public Nextcloud calendar or so.
    more_clear_headers 'X-Frame-Options';

    # Path to the root of your installation
    root /var/www/nextcloud/;

[...]
}`

Now security advert has gone.
