### ISSUE TITLE
External Storage APP can't use kerberos ticket to connect to samba share

### ISSUE THREAD

**Issue by sotor-rus** [nextcloud/server#4955]
I propose to add authentication support for the client samba with the help of the kerberos ticket to the External application. Since the php-smbclient supports this method of authentication.

**Comment by Carbenium** [comment]
That'd be indeed a great feature!

To work around the problem we had to patch the ```icewind1991/SMB``` library directly.
As a hint here the diff: 

```
diff --git a/src/NativeState.php b/src/NativeState.php
index 7ddce83..b08f124 100644
--- a/src/NativeState.php
+++ b/src/NativeState.php
@@ -70,6 +70,7 @@ class NativeState {
                        return true;
                }
                $this->state = smbclient_state_new();
+               smbclient_option_set($this->state, SMBCLIENT_OPT_USE_KERBEROS, True);
                $result = @smbclient_state_init($this->state, $workGroup, $user, $password);
 
                $this->testResult($result, '');
```

**Comment by u0046038** [comment]
I tried this workarround (change this lin in /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeStat.php) but I'm still not able to connect external storage in Nextcloud 14 !
I'm authenticating by SAML.

**Comment by aignerat** [comment]
I tried to make this work for some time now, in the documentation it is said that you need to provide a valid ticket. I found out that you can't use the login-ticket because it seems not useable for php/nextcloud/files_external. With v15 it seems, that you only need to provide a valid ticket, and you can use smb/cifs with kerberos ticket.

My question is, if there is some best-practice documentation on how to handle the ticket for files_external, the only documentation I found in the code was "don't destruct the ticket too soon" and if someone managed to make this scenario work.

**Comment by marcohald** [comment]
Does the Ticket reach the Nextlcoud instance via SAML?
I think the ticket goes only to the SAML IDP and not to nextcloud
The Readme https://github.com/icewind1991/SMB/blob/2877a6e3da289b505314d50e4e2534d6cf3d8585/README.md mentions that 
"Note that this requires a valid kerberos ticket to already be available for php"

**Comment by aignerat** [comment]
I think kerberos doesn't use SAML. https://en.wikipedia.org/wiki/Kerberos_(protocol)
Kerberos-tickets are only similar to SAML-Responses.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/9635 implemented this
