### ISSUE TITLE
Enhancement: Provide Admin App View with apps that were active previously (or cleanup "Your Apps")

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/server#5029]
(... as suggested: https://twitter.com/jancborchardt/status/866575043505082369)

The updater disables some apps automatically to prevent issues with incompatibilities. However, after the update is finished, it is quite easy to forget that such apps must be re-enabled (or checked) manually. This can even be a security problem, if you, for instance, forget to re-enable the Two Factor Auth app or so.

It would be great to have an Admin App View that shows only apps that were **actively** enabled by the admin and also their status (enabled/disabled). 

You say "But there is 'Your Apps'". Yes, that's almost what I am talking about! However, this "Your Apps" view is incredibly cluttered in my opinion. It shows standard apps that are enabled by default and in my case it also shows quite a lot of disabled apps that I have never enabled before (External storage, LDAP, whatever).

I personally would suggest to clean "Your Apps". The final view should show only apps that were **actively** enabled by the admin. What the "Your Apps" view does at the moment is not what I personally would expect it to do.

**Comment by jancborchardt** [comment]
@ho1ger the view you are looking for is »Enabled apps«. :) The issue you mention is valid, but different from the one we talked about on Twitter:

- »Your apps« should have apps which were disabled due to an update sorted up top.
- All the »System apps« like texteditor, imageviewer, etc might need a separate section further down in »Your apps«
- In general, the »Your apps« section should probably have headings inbetween then, like the »App bundles« section.

cc @eppfel @nextcloud/designers

**Comment by eppfel** [comment]
Really nice insight, but I fell this is not about adding another category. Maybe a solution would be to enable "removal" of system apps. Instead of removing the actual files, like with apps from the store, we could flag them and still show them in the appstore categories below. Then "Your apps" would make much more sense and would be much less cluttered.

We have to keep in mind, that we're just in the middle of the app management redesign e.g.
 there will most likely be a category "Updates". #3194

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
