### ISSUE TITLE
Random error in log: Default encryption module not loaded

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/server#5089]
### Steps to reproduce
Not sure how to reproduce that issue: At random points in time the error "Default encryption module not loaded" appears in my log. The "outage" takes sometimes minutes, sometimes hours. I am happy to provide my log file by mail or so to whoever needs it.

Does anybody else notice that issue?

### Server configuration
**Operating system**: Linux xxxxx 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u6 i686

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.55

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, apcu, curl, gd, json, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, readline, sqlite3, mhash, apc, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - contacts: 1.5.3
 - dav: 1.3.0
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxpod: 2.1.2
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - comments
 - files_external
 - files_versions
 - files_videoplayer
 - systemtags
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oct67191dgn6",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxxxx"
    ],
    "datadirectory": "\/var\/www\/ownclouddata",
    "overwrite.cli.url": "https:\/\/xxx",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "nextcloud",
    "mail_domain": "xxx",
    "versions_retention_obligation": "5",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": "7, 28",
    "activity_expire_days": 14,
    "theme": "",
    "loglevel": 3
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by Mennoxx** [comment]
Also have the Issue since upgrading to version 12. "Default encryption module not loaded" gets spammed 4 times every second in my admin log.
I have tried many things to fix it, even disabled encryption as a whole and reactivated. But it still gets spammed.
But my files still seem encrypted, also new files seem to be encrypted..

I'm also getting a new error telling me that the X-HEADER for "secure transport system" is not set, even though it is in my nginx-conf, same i was using with Nextcloud 11 with no issues.

I'm a bit frustrated at this point, not knowing what to do next to fix those issues. Also can't find anything as relating as this thread.

**Server configuration**

**Operating system:** Ubuntu 16.04.02
**Web server:** nginx
**Database:** mariadb
**PHP version:** 7.0
**Nextcloud version:** 12.0.0

**Comment by ho1ger** [comment]
Yes, it is quite strange. My instance works as well, files are sync'd and as it seems encrypted. But I do not have a good feeling with this as failing encryption/decryption might really børk things...

**Comment by Mennoxx** [comment]
I don't think we're the only ones with the problem, but it also doesnst seem widespead of course. This is still a niche, with not many people upgrading to version 12 and having our configuration.

And I'm absolutly with you with the bad feeling. How can you have a good feeling with encryption that seems to work but says it failes haha. Any little dork and the files are junk.

So I would be happy to find a solution, since downgrading (new install, plus import I guess) is not really an option for me. I want to use the latest version, especially if it's stable and I don't want to invest the time in a new install. I will do it, if there is no other way.. but let's hope.

Since the updater only finds updates on the daily channel, I'm thinking to install one from there, to see if it helps, but I'm skeptical; I really wanted to stay on the stable branch.

**Comment by ftiede** [comment]
I have the same problem since upgrading from Nextcloud 10.x to 11.0.3.2 and have not seen any possible solution.

The problem persists with php-5.6 as well as php-7.0, using nginx with recommended configuration as httpd.

**Comment by MrOerni** [comment]
Same here. This spams my log for ages. Never bothered. But now I want the receive a federated share. -> I get the notification. -> I accept. -> Nothing

**Comment by deg0nz** [comment]
I have the same problem as @MrOerni. 
The Federated share problem as well as the the `Default encryption module not loaded` issue.

NC: 12.0.0
PHP 7.0.18-0ubuntu0.16.04.1

**Comment by Mennoxx** [comment]
I just upgraded to version 12.0.2 from 12.0.0.
Upgrade worked smoothly and for now the log seems clean. My last entries are from the updater.

**Comment by MrOerni** [comment]
Same here. 12.0.2 fixes the Problem for me! Great!
