### ISSUE TITLE
Stable 12, user page, console warning

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/server#5115]
Stable 12 (upgrade from 11.3 via upgrade app), loading users page.

js console says:

Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification merged-template-prepend.js:2246:4

**Comment by LukasReschke** [comment]
Naive guess: related to https://github.com/nextcloud/server/issues/5114#issuecomment-304528115

**Comment by michaelletzgus** [comment]
Thanks for the hint - this resolves the missing message.
Now I have message like

`Fehler beim Anlegen des Benutzers: {message}`

**Comment by ChristophWurst** [comment]
> Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification merged-template-prepend.js:2246:4

This is just a warning because some code (partly in apps) has not been adjusted to this change yet. Everything *should* work nevertheless.

**Comment by MorrisJobke** [comment]
We are trying to get rid of all the Notification.hide() calls in the future. As of now you can safely ignore it, because the fallback code is still in place. It's basically a warning for us. As this is in the server code we will properly find it and replace it with the correct code. It's only helpful for developers of apps, that they know that there needs something improved on their side as well.

Thanks for the report anyway 👍
