### ISSUE TITLE
android session not shown on personal settings

### ISSUE THREAD

**Issue by sgiannulli** [nextcloud/server#5144]
Hello,
NC11.0.3 on Debian Jessie (Apache 2.4-PHP 7-MariaDB 10)
Android client 1.4.3 on Asus Zenfone Laser 2 with Android 5
Android client session is not shown on personal setting tab

anything to be checked or port to be forwarded on router?

Many thanks

**Comment by ChristophWurst** [comment]
Hi,

are you using your login password or an app-specific password?

**Comment by sgiannulli** [comment]
Hi,
I'm using standard username and password created with administrator account; I would like to move to 2fa but I'm afraid it won't be possible if my android device it's not shown in personal setting page.
Thanks

**Comment by ChristophWurst** [comment]
@sgiannulli because clients will authenticate on *every* request, we're not showing those as active sessions. The list would quickly fill up with hundreds of entries. Technically, we could of cause group those, maybe based on a combination of IP and user agent, but if clients don't use cookies we have nothing to distinguish them.

Regarding 2fa, just go ahead and use it. The only thing you have to change is to use an app-specific password on all connected devices because the standard password is not allowed as soon as 2fa is enabled.

**Comment by MorrisJobke** [comment]
This will change with Android 2.0 and the clients will show up properly.
