### ISSUE TITLE
Nextcloud client side encryption with Cryptomator (Feature-Request)

### ISSUE THREAD

**Issue by Immontalis** [nextcloud/server#5145]
Hello,

I would like to ask the developer if it is possible to cooperate with Cryptomator and make an app for client side encryption. I think many people want this app and it woud be a great step forward for Nextcloud encryption.
The Server side encryption is very good if you store your data on google drive or somthing like this but if you have an provider (sometimes it makes senes for some  pepole) where you host Nextcloud and that have access to the data you are partially save.

here the link to cooperate with Cryptomator 
https://cryptomator.org/coop/

I hope you know what i mean and somone can help to improve this vision.

**Comment by LukasReschke** [comment]
That would be better suited for help.nextcloud.com instead a issue :)

**Comment by elsiehupp** [comment]
I don’t know if the way Issues work on this repository has changed in the past four years, but it does appear that feature requests (i.e. “[enhancements](https://github.com/nextcloud/server/issues?q=label%3Aenhancement+)”) are presently within the scope of this Issue Tracker, so I’m reopening this Issue.

Obviously incorporating Cryptomator support would require work on both the server and the clients, so there should be linked issues on other issue trackers, as well, and I will try and dig up any existing related issues.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
