### ISSUE TITLE
NC12.0 upgrade from 11.03: file nextcloud  manual.pdf is still from NC11 and is corrupted

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#5183]
[nextcloud.txt](https://github.com/nextcloud/server/files/1039766/nextcloud.txt)

On NC11.03 this nextcloud manual.pdf is working.
Now I upgraded to NC12.0 and the file is still NC11 (not upgraded) and its corrupted as well:
PDF.js v1.4.20 (build: b15f335)
Message: Invalid PDF structure

Should I be replacing for all users the  NC12 nextcloud manual.pdf file manually or should it be done during upgrade automatically?

cheers, jeroen

**Comment by nickvergessen** [comment]
The file was corrupted, yes and sorry. You can get the new file from https://docs.nextcloud.com/server/12/Nextcloud_User_Manual.pdf

We do not replace the file on update. Only new members should receive the new file. The issue is, we don't know if the user renamed the file, deleted it or did something else...
