### ISSUE TITLE
CTRL+F in a text file does not seem to work any more

### ISSUE THREAD

**Issue by hugoroy** [nextcloud/server#5198]
### Steps to reproduce
1. Go to a text file and open it with the Nextcloud server web interface editor (url like <https://nextcloud.example.org/index.php/apps/files/?dir=/directory&fileid=11118#editor> )
2. Press CTRL+F (Chrome, but apparently bug also with other browsers)
3. Nothing happens 

### Expected behaviour
1. Go to a text file and open it with the editor 
2. Press CTRL+F 
3. Get the browser built-in "find" feature

### Actual behaviour
The editor seems to hijack the CTRL+F binding and prevents the browser built-in find feature from working.

Should be easy enough to reproduce, tested with very different configs by different people who could reproduce (Windows, Mac, etc.).

**Comment by nickvergessen** [comment]
Yeah the editor brings up it's own search for me:
![bildschirmfoto vom 2017-06-01 10-38-56](https://cloud.githubusercontent.com/assets/213943/26671672/ac0d0268-46b6-11e7-8f1b-0ab5d0bf6d4b.png)

However, if you have an issue with this or think it should change, please open your issue in the repo of the app: https://github.com/nextcloud/files_texteditor

**Comment by hugoroy** [comment]
Please don't close this.

It does not bring the editor own search for me. I did not remember there was such a feature in the editor of the web interface of nextcluod itself. Otherwise I wouldn't have filed this issue at all if the "find" feature was working in any way.

**Comment by e-alfred** [comment]
I can confirm that the text editor does not open a search box if CTRL +F is pressed. Here is the error log from the browser:

`The resource from “https://server/index.php/apps/files/ext-searchbox.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).`

I am using Nextcloud 12 with Firefox 54.0.1. The problem does not happen in Vivaldi 1.10, here the search bar of the browser is opened and works well..

**Comment by agrudsky** [comment]
I am also getting this issue. Upon checking the Chrome dev console, the problem appears to be an incorrect MIME type for the searchbox:

`Refused to execute script from 'https://nextcloud.server.com/apps/files/ext-searchbox.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

This error is thrown every time I hit CTRL+F in a text file.
