### ISSUE TITLE
Feature Request: Show Shared Folder Name

### ISSUE THREAD

**Issue by jdadame** [nextcloud/server#5201]
Would like it if the shared folder name would be showed on the page once.

**Comment by nickvergessen** [comment]
Can you explain with a screenshot what you mean?

**Comment by Yxanu** [comment]
**I think he's talking about displaying the name of the shared folder inside the directory.**

Sometimes it would make sense to show the folder name above the files - for example when sharing folders with clients as "only-download". 

Currently the folder (root) is represented by the little house instead of showing the name.

<img width="235" alt="screen shot 2017-06-01 at 15 48 36" src="https://cloud.githubusercontent.com/assets/13252927/26683106/06dbfe48-46e3-11e7-80e0-9091c390e5b4.png">


Ran into the problem myself. Is there a code snippet for adding the folder name to the download page?

**Comment by jdadame** [comment]
@Yxanu is correct. We send download only links to clients to download files but the name of the folder is important. If maybe we could have the folder name show right next to the Home icon that would be helpful.

**Comment by tessus** [comment]
I think displaying the folder name should be an option, not done by default.

**Comment by MorrisJobke** [comment]
Implemented for single file and folder shares in 13 via #5827:

![bildschirmfoto 2017-08-31 um 13 23 11](https://user-images.githubusercontent.com/245432/29920817-9f8d6ef2-8e4f-11e7-9858-80e07d41d8ab.png)
![bildschirmfoto 2017-08-31 um 13 23 29](https://user-images.githubusercontent.com/245432/29920818-9f9869b0-8e4f-11e7-855c-c728d82c000e.png)
