### ISSUE TITLE
Drive client like Seadrive has one

### ISSUE THREAD

**Issue by eglipeter** [nextcloud/server#5250]
As a feature request for future, it would be nice to see a Drive client like Seadrive has one (cf. https://www.seafile.com/en/features/).
This client allows one to mount the user directory as a Windows drive including a drive letter. It would be nice to see such a client also in Nextcloud.

**Comment by simonspa** [comment]
Nextcloud provides a WebDAV interface and there is a plethora of Windows WebDAV clients out there (even Windows itself provides a native client), so there really is no need to reinvent the wheel.

**Comment by blizzz** [comment]
what @simonspa says → closing

**Comment by fr500** [comment]
are you implying webdav is even similar to seadrive client?
you should read about what it does (also google for dropbox project infinite)

WEBDAV SUCKS.

**Comment by alexxy** [comment]
Webdav dont work in reliable way. So we now looking some other cloud storage system to migrate to it. Since some people want to mount it like a network drive (in mixed envirememt).

Seafile has fuse like client for its protocol. So it seems to me if nextcloud implement such a client it will be a good addition. 

PS WebDav must die in flame.
