### ISSUE TITLE
Folder icon not themed when using drag and drop feature

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#5349]
### Steps to reproduce
1. Theme your instance
2. Click and hold on a folder
3. Move the mouse

### Expected behaviour

The folder should stay the same colour

### Actual behaviour

The folder reverts to default blue

@nextcloud/designers

**Comment by jancborchardt** [comment]
cc @nextcloud/theming

**Comment by patschi** [comment]
I've tried some things, and so I have figured out the cause:
40228c0c2b17c800fa5e227b4d2e8d074da82075/apps/files/js/files.js#L364L366

When creating the dragShadow it's hardcoded using the `files/folder.svg` file instead of the themed one. So, if I simply remove the `IF` the icon gets dynamically loaded by submitting the mimeType of the current object to move - in my case `httpd/unix-directory`, so folder icon is being shown:

![image](https://user-images.githubusercontent.com/2029878/27055259-1c475978-4fc4-11e7-99da-d81e86d4d53c.png)

Using:
```javascript
var mimeType = elem.mimetype;
if (elem.type === 'dir') {
	mimeType = 'folder';
}
Files.lazyLoadPreview(path, mimeType, function(previewpath) {
	newtr.find('td.filename')
		.css('background-image', 'url(' + previewpath + ')');
}, null, null, elem.etag);
```

Just one thing I've not solved is, when using the `Files.lazyLoadPreview` function...
1. It warns about deprecation: `DEPRECATED: please use lazyLoadPreview() from an OCA.Files.FileList instance`
2. It tries to retrieve a preview pic for folder and is resulting in a HTTP 404: `GET https://cloud.domain.tld/core/preview.png?file=%2FPublic&c=5939baabf14b7&x=32&y=32&forceIcon=0`

**Comment by juliushaertl** [comment]
> When creating the dragShadow it's hardcoded using the files/folder.svg file instead of the themed one. So, if I simply remove the IF the icon gets dynamically loaded by submitting the mimeType of the current object to move - in my case httpd/unix-directory, so folder icon is being shown:

That folder icon should be obtained by using OC.MimeType.getIconUrl(mimeType).

> It tries to retrieve a preview pic for folder and is resulting in a HTTP 404:

That should not happen if the if/else condition stays, right?

@patschi Thanks for investigating. Do you want to open a pull request to fix that as well? That would be awesome. :wink:

**Comment by patschi** [comment]
Tested, working on my setup, PR created. Thanks @juliushaertl!

> That should not happen if the if/else condition stays, right?
Yep.

**Comment by MorrisJobke** [comment]
Thanks @patschi for this quick fix 🚀
