### ISSUE TITLE
Idea: Ransomware protection

### ISSUE THREAD

**Issue by patschi** [nextcloud/server#5350]
### Background & Idea
Ransomware has been a quite big topic recently and probably will be a continuous threat for users' data. Therefore I would suggest any further preventive actions in the nextcloud server to protect the private data on infected clients against possible ransomware attacks taking over nextcloud.

The server should be safe and getting backup'ed anyway, but clients may get infected. Infected clients where private files may get encrypted may encrypt the data on the Nextcloud as well. Ofcourse there may be the version control app which could save couple of times, but...
* revisions of files will be cleaned when available quota is getting critical, specially through all the new encrypted data.
* App could be disabled (in the whole instance or just enabled for specific clients)
* Anything else could go wrong. Keep in mind: Murphys law.

### Why
Security and privacy is important - and they are one of the most important goals of Nextcloud. To give ransomware less chance for causing damage, giving users unique protection, offering new benefits compared to different solutions and - mostly important - keep users' data safe, we could implement some sort of protection here. (Could be a quite good feature for marketing purposes as well?)

### How
Even though it may be hard or nearly impossible to create an 100%-working protection against ransomware, we can try to reduce damage. On an infection we could stop client-based synchronization on the server-side till it gets enabled again in the personal area. Some thoughts about of mine:
* We could re-use parts of the `workflow` or `accesscontrol` apps.
* Using heuristic we could detect massive filetype changes on a specific client to detect potential ransomware infection. For example, if 250x files of type `image/png` gets renamed and/or the mimeType changes to anything else within three seconds, it could be a possible infection.
* We could detect valid images, which can be viewed, and if hundreds of images gets changed and are not readable anymore after, the images may have get encrypted and therefore it could be a ransomware attack as well.

What are you thinking about this idea?

[![](https://api.bountysource.com/badge/issue?issue_id=46147459)](https://www.bountysource.com/issues/46147459-idea-ransomware-protection)

**Comment by tflidd** [comment]
Unfortunately, there are a few use cases where you change a lot of file names: Reorganizing your media (renaming respecting meta information of files), sorting pictures, running logrotate, ...

I was thinking of a new mode for the version control, so that you can set a period (e.g. one week) for which all files must be restorable.

**Comment by patschi** [comment]
> Unfortunately, there are a few use cases where you change a lot of file names: Reorganizing your media (renaming respecting meta information of files), sorting pictures, running logrotate, ...

Some thoughts:
* When reorganizing media: We do not neccessary need to check for any metadata or visual changes of the picture itself. We would just need to verify that it's still a picture when the same file gets replaced.
* When sorting pictures: Usually when sorting/renaming pictures, the file itself should be the same. So when the file itself does not change and just the name, we could safely ignore it. Can't we?
* About logrotate: I see this functionality not on the server itself where the server is running on. In usual cases clients may not run any logrotate daemon on their NC-client-share. Or did I possibly understand that point wrong? :)

> I was thinking of a new mode for the version control, so that you can set a period (e.g. one week) for which all files must be restorable.

I see two issues here:
* A lot can happen within one week, or even within one day. But ofcourse better than nothing when the worst-scenario happens.
* If you think about service provider or big Nextcloud instances you will need a lot of additional space to save even more revisions of small or even very big files.

Just some thoughts. Any input from @LukasReschke, @nickvergessen or from the marketing-side @jospoortvliet?

**Comment by nickvergessen** [comment]
sounds like a good idea, the question is, how ransomware works, because if it first encrypts your nextcloud.cfg file, you are "save" since it should not be able to sync anymore?

The steps you mention sound like a good idea. Do we know how the encryption works and how a file looks like afterwards? Is it binary, renamed or something?

**Comment by tflidd** [comment]
> sounds like a good idea, the question is, how ransomware works, because if it first encrypts your nextcloud.cfg file, you are "save" since it should not be able to sync anymore?
> 
> The steps you mention sound like a good idea. Do we know how the encryption works and how a file looks like afterwards? Is it binary, renamed or something?

Locky used to rename the files: https://www.bleepingcomputer.com/news/security/the-locky-ransomware-encrypts-local-files-and-unmapped-network-shares/

But we can't rely on a special renaming pattern, or even the file type (the text in a text file can easily be encrypted without changing the filetype, on other file types it's probably more difficult). The nextcloud.cfg is probably the last one being changed, because such file types often break software and during the encryption process they don't want to risk being discovered.



> When sorting pictures: Usually when sorting/renaming pictures, the file itself should be the same. So when the file itself does not change and just the name, we could safely ignore it. Can't we?

You want correct a wrong white balance (red-eyes, lens deformation, dust-removal, re-compression, ...) on all pictures? I just want to point out that there are a number of legitimate reasons to do renaming and it's hard to imagine all possible use cases.

What if the ransomware copies the file first, encrypts the copy and then deletes the original?

Therefore I proposed, to keep versions of each file back to at least 1 week. This way we don't have to care about how the ransomware works as long as the incubation period is less than a week. When you change a lot of files, there is a risk to exceed your quota.

**Comment by jasonbayton** [comment]
Great idea and absolutely not unique as I've seen these sorts of fail-safes in many enterprise solutions. I work with one daily in fact that'll discard any LDAP changes exceeding a specified percentage change in order to ensure the system continues to function as intended. If required it can be overridden too.

Putting a temporary hold on sync where a change threshold has been exceeded seems like a reasonable feature, even completely outside the scope of a ransomware attack; user error, hardware/software issues, etc could cause the server to overwrite the client or client to overwrite the server, and getting a notification just to confirm that action could save a lot of headaches.

**Comment by warnerbryce** [comment]
We should better look at extensions of files.
Some ransomwares i saw don't rename the files, but all of them rename the extensions. 
So when a folder of 130 Files of pictures, change suddenly to an obscure extension, Nextcloud should stop the sync and warn the user and the Admin.

**Comment by jospoortvliet** [comment]
@warnerbryce thing is also - such renames would come with an encryption so Nextcloud would go into a fit: it would consider the original files to be deleted and the new ones to be entirely new. It would most likely respond by putting the 'deleted' originals in the trash (easy to recover!) and upload the new ones.
Of course, depending on the server settings, the trash size is limited so the protection this offers is limited too. But for a limited number of files it would work, I think...

**Comment by patschi** [comment]
_Posting this here as a reference._

There is something new on this topic:
https://github.com/nextcloud/ransomware_protection
(Thanks @nickvergessen!)

There is even an official news post about this new app:
https://nextcloud.com/blog/nextcloud-presents-ransomware-protection-app/

Should we consider this issue now as closed?

**Comment by jasonbayton** [comment]
I think we're done here yep, any further convo would be about enhancements I guess, which an issue can be created in the above ransomware repo
