### ISSUE TITLE
Daily build has version string 9.0.52 and is from stable9 branch

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#537]
The `daily build` on nextcloud.com has the version string 9.0.52. See version.php:
````
<?php
$OC_Version = array(9,0,52,0);
$OC_VersionString = '9.0.52';
$OC_Edition = '';
$OC_Channel = 'daily';
$OC_VersionCanBeUpgradedFrom = array(8,2);
$OC_Build = '2016-07-22T23:01:04+00:00 3be8f7a369e91f8eed9fdd1df099e03a87001442';
````
This causes problems when you want to upgrade from 9.0.53 to `daily` via updater app: 
https://help.nextcloud.com/t/using-updater-app-to-get-nc-10-beta-or-daily/1856

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by childnode** [comment]
same for https://download.nextcloud.com/server/prereleases/nextcloud-10.0beta.tar.bz2
it is 9.1.0.13

time to update this, this is alpha :)

**Comment by okias** [comment]
I change version to 9.1.0.13 to 9.1.0.16 to pass it, I hope it wont create any mess..

**Comment by childnode** [comment]
just to get some attention on it and / or to get some information to understand this:
What is the nextCloud versioning scheme?
In which relation, cyclus or scheme is this (still) synced with it's origin ownCloud?
Is nc 10 still activly patched with anything from oc 9.1 or is nc 10 (rebase nc10 onto oc9.1) a dedicated fork aside oc9.1?
It's not that clear to me reading https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
if it's a real fork, we should prevent direct updates from oc. We should get safe to not allow any implicit upgrade paths that are totally unsupported but "working" since oc versionscheme is lower than nc 
Perhaps we might then correct the versioning files and take some action to handle migrations from oc to nc excplicit?!
~Marcel

**Comment by MorrisJobke** [comment]
The versions should be compatible and it should be totally fine to upgrade between them like between minor versions of them:

OC 9.0 - NC 9
OC 9.1 - NC 10
OC 9.2 - NC 11

This was done by intention to not scare away the community with unnecessary incompatibilities. Nevertheless should this be done carefully.

**Comment by tflidd** [comment]
But the daily build, shouldn't it be newer than the last release?

Even today the daily build has the version string `9.0.52` (OC_Build: 1158c473dcde426ed6ac6682738d216e09479e7b). Interestingly this submit was for the stable9-branch.

Isn't daily supposed to be built from master?

**Comment by MorrisJobke** [comment]
@LukasReschke could you answer @tflidd's questions?

**Comment by LukasReschke** [comment]
Those should be fixed now :)
