### ISSUE TITLE
WebDAV 404 page is not styled due to CSP policy

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5443]
* open http://192.168.99.100/server/remote.php/webdav/welcome2.txt (with a logged in account and an unavailable file or just not logged in)
* expected: styled error page
* actual: unstyled error page:
![bildschirmfoto 2017-06-16 um 10 58 52](https://user-images.githubusercontent.com/245432/27234561-09e2a758-5283-11e7-9383-e6ebc88d9a21.png)

cc @LukasReschke @juliushaertl @skjnldsv

**Comment by juliushaertl** [comment]
That would require setting a proper CSP header here: https://github.com/nextcloud/server/blob/master/apps/dav/lib/Files/BrowserErrorPagePlugin.php#L81-L81

@LukasReschke That should not be a security problem, since it will only be used on error pages where no user controlled content is shown, right?

**Comment by szaimen** [comment]
This works for me now. (it shows the 404 page correctly if I am logged in). -> closing.
