### ISSUE TITLE
URL rewrite to lose index.php with Apache & fastcgi ?

### ISSUE THREAD

**Issue by autrui** [nextcloud/server#5576]
### Steps to reproduce
1. Open any Nextcloud page
2. URL contains index.php

### Desired behaviour
URL does not contain index.php (=shorter URL)

### Server configuration
**Operating system**: CENTOS
**Web server:** Apache
**Database:** mySQL
**PHP version:** 7
**Nextcloud version:** 12
</details>

I know it's possible to have NC rewrite URLs so they don't end in index.php. Makes the URL prettier but most importantly **shorter**. 

I can fiddle with config.php all I want but it was my understanding that the restriction was beyond simple user control.

Is it possible to do that in a shared hosting environment (with Apache & fastcgi/mod_fastcgi) where users don't have permission to edit the server config? Or is it still restricted to Apache and mod_php?

If so, would you please consider expanding support to the Apache + fastcgi/mod_fastcgi combi (for restricted users with no root access)?

Thank you.

**Comment by dirigit** [comment]
Use .htaccess for this.

It will fail integrity check afterwards but, maybe they exclude it from check at some time (it's really annoying).

**Comment by MorrisJobke** [comment]
Just set `'htaccess.RewriteBase' => '/server/',` (or wherever you have installed your Nextcloud) to the config.php and execute `occ maintenance:update:htaccess` and you should get a proper htaccess file and URLs without index.php.

For more help ask in the forums: https://help.nextcloud.com/

**Comment by autrui** [comment]
@MorrisJobke 
Isn't it a bit premature to close this? Before starting this thread here I did search help.nextcloud.com, and there are **several** threads by diffeent people concerning the removal of index.php from the URL, hinting at a problem with Apache and fastcgi (which I checked is true in my case as well).
The remedy you suggested was mentioned there somewhere. I've tried that before and just now, without any effect on the URL.

Just to be on the safe side, I've edited the first post to include the contents of my config.php. My Nextcloud resides in the webroot of a subdomain BTW.

**Comment by MorrisJobke** [comment]
> Just to be on the safe side, I've edited the first post to include the contents of my config.php. My Nextcloud resides in the webroot of a subdomain BTW.

Usually this is all that is needed:

* update the `htaccess.RewriteBase`
* call `occ maintenance:update:htaccess` (and have an .htaccess file that is writable by the web server user of course)

The only thing that comes to my mind is: Is the `.htaccess` even used in your environment? The apache config needs to set the `AllowOverride All` config option for your web root. If this is not set there is not much we can do.

I closed this ticket because this is working for a lot of instances and really looks like a setup/environment problem than a real bug. If the web host doesn't support the htaccess file, we can't do much. And the bug tracker here is for bugs. If you need help with the environment and setup then the forum is the better place.
