### ISSUE TITLE
Share via link: different behaviour create vs update

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5598]
Server: 
- always ask for password: true 
- enforce password protection: true

**New share via link**
https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html#create-a-new-share
Url: /ocs/v1.php/apps/files_sharing/api/v1/shares
shareType: 3
password: 11
This results in a 401.
If I then look at the responseBody I can see a detailed error message "the password must contain at least 8 characters".

**change existing shareViaLink**
Pair {password 11}
Url: /ocs/v1.php/apps/files_sharing/api/v1/shares/226
This results in a 200.
Response body then is 
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>400</statuscode>
  <message>Das Passwort muss mindestens 8 Zeichen lang sein</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

I would expect to have a consistent behaviour here?

**Comment by schiessle** [comment]
I will have a look at it

**Comment by schiessle** [comment]
I had a look. The difference is the following:

If creating a share failed we return "Forbidden" if changing a Share fails we return "Bad Request". I think both makes sense. I would also prefer not to change it because of API stability. In this case we would probably have to increase the version of the API.

That you get a 200 is the default behaviour of OCS v1. OCSv1 always return 200 if the OCS call as such was success, even if the operation failed. The status of the actual operation is encoded in the json.

To get the correct error code I would suggest to switch to OCSv2 for the client, OCSv2 is available for all Nextcloud version, so this shouldn't be a problem. Just change the URL to:

````
/ocs/v2.php/apps/files_sharing/api/v1/shares
````

@tobiasKaminsky please let me know if this works for you.

**Comment by tobiasKaminsky** [comment]
We are using ocs v2 since quite a long time.
Thank you 👍
