### ISSUE TITLE
encryption compatible list 

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#5607]
Hello,

I think about to enable encryption on my Nextcloud Server and post an question to the [forum,](https://help.nextcloud.com/t/enable-encryption/14927) if enabling encryption with 100 GB Data is save. 

The answer from the moderator tflidd was:

'Not all apps are compatible with the encryption app, please test this before you enable it (I don't know if there is a list with compatible apps). Also note that the encryption app only protects data if they are store on an external storage. On local storage, there is very little benefit and the encryption makes many things much more complicated.'

My Question is, is it save to do this? The encryption app only encrypt an mounted external storage on nextcloud, or the whole userspace?
Which apps are compatible with encryption? I found no List at the FAQ,
 
Best regards

Lars

**Comment by Huster-at-github** [comment]
I agree. This would be very helpful!   

More and more people are using storage outside Nextcloud .....

**Comment by schiessle** [comment]
All main apps are compatible with encryption. In general the encryption app is completely transparent for both the users and the app developers. As long as the app only accesses the files through the Nextcloud filesystem API.

At the moment the preview generation app is not compatible because it runs in the background and process your files and of course it can access them if they are encrypted. I don't know any other app but because we never know any app and everybody can write a Nextcloud app it is the responsibility of the App developer to mention such incompatibilities in the app description and handle this cases properly.

By default it encrypts everything. But you can disable it for the root storage in the admin settings once the encryption is enabled and the default encryption module is enabled, the setting is called "Encrypt the home storage".

If you decide to use encryption I would really recommend to enable the master key: `/occ encryption:enable-master-key` directly after you enabled encryption (this is only possible as long as no file is encrypted!).

**Comment by Huster-at-github** [comment]
@ @schiessle : Thanks a lot!  :+1:

**Comment by Happyfeet01** [comment]
Thanks @schiessle
