### ISSUE TITLE
Deactivated Accounts still show up in Contacts for Chat and Videocalls

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/server#5608]
Opened here as per receommendation of [this closed issue](https://github.com/nextcloud/contacts/issues/238).

### Steps to reproduce
Deactivate an account

### Expected behaviour
Accounts should be unavailable for chat and videocalls

### Actual behaviour
Contacts show up as able to chat and for videocalls

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Contacts version:** (see Nextcloud apps page)
1.5.3
**Updated from an older Nextcloud or fresh install:**
Updated since owncloud 6, migrated to Nextcloud 10 from owncloud 9

**Comment by MorrisJobke** [comment]
cc @georgehrke @ChristophWurst

**Comment by MorrisJobke** [comment]
cc @nextcloud/spreed

**Comment by MorrisJobke** [comment]
Same happens in the contacts dialog: #9824 and the share menu: #6755

**Comment by MorrisJobke** [comment]
@danxuliu @skjnldsv Mind to have a look at this?

**Comment by tcitworld** [comment]
There's two issues : 
* Remove user card from system address book when it's updated and deactivated (easy) - fixes the contact dialog
* Ignore deactivated users when listing them (for sharees and talk app). It's harder because it makes sql queries harder, and has to be implemented for all backends.

I'll try to push something soon.
