### ISSUE TITLE
Hide more sensitive information in server config report (occ config:list system)

### ISSUE THREAD

**Issue by Tormen** [nextcloud/server#5635]
### Steps to reproduce
1. login to server and change to Nextcloud dir
2. run: sudo -u www-data php occ config:list system

### Expected behaviour
This command should hide (so mask field values in it's output with ***REMOVED SENSITIVE VALUE***) also secondary information, which will for most users still be sensitive information (privacy and/or security relevant) from these fields:
* overwrite.cli.url
* trusted_domains
* dbname
* mail_from_address
* mail_domain

### Actual behaviour
The above fields are listed in cleartext, allowing people to snoop for email addresses in the github issues and/or know enough about the setup of a certain domain to well attack it...

As requested:

/cc @LukasReschke @nickvergessen

**Comment by MorrisJobke** [comment]
cc @LukasReschke and @nickvergessen for this

**Comment by nickvergessen** [comment]
The problem is, that most issues I looked at the config, it is because the urls are wrongly configured. If we remove those, it just makes it more trouble some to find the mistakes, since you need to ask for them explicitly. Also people get scared when you ask for their domain settings directly and there is no easy command to get it with the urls on.

For the dbname I think it makes sense to add.

**Comment by Tormen** [comment]
Yeah... it's what I thought... if you remove the above there is not much left ;)

If you add the mail_from_address and/or mail_domain to your list, then that's already better as it is now.
It might seem far-fetched, but grabbing emails for spamming is still a business.
