### ISSUE TITLE
Make u2f and totp workable without secound click

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#5640]
Hi,

i am using u2f and totp for my nextcloud account. Working nice... but I would be great if I did not have to select one before I tab my yubikey or enter a number. Would be great if it will be possible enter enter without second click directly after login, like it works on github or gitlab. I also opened an issue at u2f but I think it have to be firstly supported by the server its self!?
[https://github.com/nextcloud/twofactor_u2f/issues/57](https://github.com/nextcloud/twofactor_u2f/issues/57)

**Comment by ChristophWurst** [comment]
Ref https://github.com/nextcloud/twofactor_u2f/issues/57#issuecomment-312559974

**Comment by ChristophWurst** [comment]
This is unfortunately not possible because from the experience with working with Nextcloud 2FA providers I know that many do actions when their template is rendered (esp. sending messages/notifications to external systems) and we'd have to majorly change our provider API to allow this flow.

I'm closing this ticket now since there haven't been any similar tickets so I assume the priority is quite low.
