### ISSUE TITLE
Datepicker design improvements

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/server#5691]
This is a copy of nextcloud/deck#205 because the same datepicker is used in many Nexcloud apps, inlcuding nextcloud/files and @nextcloud/calendar 

It would be useful to highlight "today" in the datepicker. It's a small fix, but some feedback from @nextcloud/designers is needed first.

Here's my suggestion:
![image](https://user-images.githubusercontent.com/4129927/28111136-c271a906-66f4-11e7-84de-f7aa27be46e1.png)

However, two things must be considered as well:

1. datepicker doesn't look very much integrated into the general UI (buttons, icons, colours, fonts...) - do we want to make a more general overhaul of it? Here's an example of what it might look like:
![image](https://user-images.githubusercontent.com/4129927/28112430-45cfccac-66f9-11e7-8d2a-984b68884ea0.png)

2. Files app by default disables (in "set expiration date") dates older than "tomorrow", so it might not be weird to highlight "today". This is how my suggestion would appear over there:
![image](https://user-images.githubusercontent.com/4129927/28111363-849466cc-66f5-11e7-80bb-d708e6294e62.png)

**Comment by comradekingu** [comment]
@pixelipo I am not one of the designers, but:

![calendar](https://user-images.githubusercontent.com/13802408/28115516-8e539f6a-6705-11e7-86fa-cffb32de703a.png)

![calendarsentered](https://user-images.githubusercontent.com/13802408/28115499-7e9d84a0-6705-11e7-84e7-7adae51dcbba.png)

**Changes:**
Moved all dates 4 pixels to the left. Image two has the single digit dates centred.
They are still aligned topwards, since there is an odd number of pixels. 25x25
The horisontal alignment isn't immediately obvious though.

Since dates never go into the triple digits, i don't understand why they are right-aligned.

**Rationale:**
My thinking is that having two squares, meddles the field between what is the selection, (if i am reading it correctly,) and what is the current date.

Distinguishing the current date from the selection can be done by having both current month, and current day, displayed in blue.

**Months on the side:**
Having other months alongside could be useful if the user is bad at remembering the ordering of the months.

**Time field**
I don't see the point of having a time field, if it is so that it only displays user-time. (This is an assumption on my part.) Seeing as the user is conditioned into looking for it elsewhere.

**Comment by jancborchardt** [comment]
Agree with both of your suggestions @pixelipo @comradekingu. Just small additions:

- It isn’t immediately apparent which is today’s date and which is the selected date, especially not if only coloring of the text is used (as in your proposal @comradekingu). In the current jQuery UI you can see the days of the past are greyed out, which is an immediate indicator.
- We should additionally also indicate the weekend like we do in the Calendar app. cc @nextcloud/calendar
- Let’s simplify moving from »box around each day« to a simpler grid, and also removing the double outer border. This lifts the design out of the last decade. ;)

Here’s a a rough mockup:
![datepicker](https://user-images.githubusercontent.com/925062/28124080-f4406f98-6722-11e7-92ab-529e542a3582.png)
What do you think @nextcloud/designers @nextcloud/calendar?

**Comment by comradekingu** [comment]
Me again:

![calendar2](https://user-images.githubusercontent.com/13802408/28123954-9613d054-6722-11e7-9a7c-50821857f388.png)

**Changes**:
Boxen are reduced 4 px each axis. Making them equidistant from borders and each-other.

**Rationale:**
This should make it easier to go one year back quickly.
For illustration, i added other months, it would be useful to have them there as a vertical dropdown to span quickly for both year and month. It would have to push the current month downwards, seeing as there is no vertical space upwards available.

Ideally, worst case:

    jan
    feb
    mar
    apr
    may
    jun
    jul
    aug
    sep
    okt
    nov
< des* >        < current year* >

Actual result:

<  ↓ >        < current year* >
    jan
    feb
    mar
    apr
    may
    jun
    jul
    aug
    sep
    okt
    nov
    des*
 
@jancborchardt Looks much cleaner. If not a bit low on contrast.
I can't remember what was done to the similar calendar in elementary OS, but it was also sleek.

**Comment by comradekingu** [comment]
@jancborchardt  Something like this?
![calendar3](https://user-images.githubusercontent.com/13802408/28125749-d58390bc-6727-11e7-9b1b-75c0ca6eddbc.png)

Changes:
More contrast, separate month and year fields, added weekday names, coloured current.

Rationale:
Knowing what days relate to which column is useful. If even just as a mouseover till you get used to it. "Does it start on Sunday or Monday?" would be the question to ask.

**Comment by pixelipo** [comment]
@comradekingu selected date should be more visible than __today__ - the opposite is try in your example.

Separation of month and year would be nice, but that is not as simple to do as all the other changes so far mentioned

**Comment by jancborchardt** [comment]
This is a 3-step approach, and we need to make sure not to bunch it up too much or over-discuss it or we risk not getting anything done. ;)

1. Highlight the current date. This is quickly done and important.
2. Modernize the design. See my mockup. This is pure CSS and also quite easily done.
3. Think about if we want to modify the elements available in the dialog. This includes modifying the jQuery UI dialog and could be more difficult. Also we should make sure this is the same also in the Calendar app (as I intentionally checked the top left part of the calendar app and modeled the popover after it). We should do this last, only as soon as the other changes are done and merged, as this will take more work and deliberation.

**Comment by pixelipo** [comment]
Steps 1. and 2. ready for review in #5713

**Comment by Espina2** [comment]
@jancborchardt in your design it will look better if you had more margins in all the sides.
