### ISSUE TITLE
Add annotation to allow access to Controller methods, even if access to app is group-restricted

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#581]
Follow-up of https://github.com/strukturag/nextcloud-spreedme/issues/31

tl;dr:
It would be nice to add support for a new annotation (something like `@NotGroupRestricted`) which can be added to methods of `Controller` classes to still allow access to them, even if use of the app has been restricted to certain user groups via the App manager:
![image](https://cloud.githubusercontent.com/assets/1249295/17131653/bda96a98-531e-11e6-94dd-656784e2ac9a.png)

**Comment by MorrisJobke** [comment]
@rullzer I guess this is currently restricted by our strict autoloader which doesn't allow the loading of an app namespace if the current user is not in this group. For public pages there is no user so there is not even a chance to look into the annotations because the whole app is forbidden to be loaded, right?

**Comment by icewind1991** [comment]
Yes, it's not routes that are being blocked, the entire app is never loaded

**Comment by rullzer** [comment]
So this means that when adding the autoloader dirs we have to check all enabled apps and not just for a given user.

**Comment by icewind1991** [comment]
In general this is not something that can easily be done, in order to even check if a route is allowed we need to have the app loaded which is something we dont want to do if the app is not enabled for the user
