### ISSUE TITLE
Delete Symbol not visible

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#6122]
Hello,

i don know if this is new, but i would delete some Files (Folder, ZIP Files, Textfiles ...) in an Directory but this is not possible.

![bug_ff_deleteall](https://user-images.githubusercontent.com/3295104/29308898-da52b79a-81a7-11e7-856f-63b1946938e1.png)

---

Nextcloud version _(eg, 10.0.2)_: 12.0.2
Operating system and version _(eg, Ubuntu 16.04)_: 16.04.2 LTS
Apache or nginx version _(eg, Apache 2.4.25)_:  Apache 2.4.18
PHP version _(eg, 5.6)_: 7.1.8
Browser: Firefox 55.0.1
Operation System Desktop. Linux Mint 13.1

Is this the first time you've seen this error?:

no also in 12 and 12.0.1

Can you reliably replicate it? (If so, please outline steps):

1. open an Folder where files you would delete
2. open an PDF File and Close this file again
3. The URL has changed (e.g.: cloud.domain.tld/index.php/apps/files/?dir=/Downloads&fileid=8)
4. mark an file to delete
5. Download Button is not visible
6. leave the Folder
7. access it again and mark the file you would delete
8. Download Button is visible

**Comment by MorrisJobke** [comment]
This is caused, because somehow the _onResize is called when the PDF viewer is opened and the window is detected as wider, but on close this does not change and the table head is still "too wide".

https://github.com/nextcloud/server/blob/12c9b1efb077a45a6ef0bf29ac7e5b149539cf49/apps/files/js/filelist.js#L559

Maybe someone from @nextcloud/javascript want to look into this.

**Comment by Happyfeet01** [comment]
ah okay thanks
