### ISSUE TITLE
App Passwords disappear in personal settings but password appear to keep working

### ISSUE THREAD

**Issue by eggithub** [nextcloud/server#6139]
This issue seems to be related to #4535 but this report is from another nextcloud instance running on a rpi3 with apache2, mariadb and php7

This issues happened after an upgrade from 12.0.0 to 12.0.1. and persists in 12.0.2

passwords appear to keep working but none are shown in personal settings.

**Comment by eggithub** [comment]
Everything appears to be working!

**Comment by leonardomarino** [comment]
**Expected behavior**

Sessions and App Passwords should appear

**Actual behavior**

App Passwords do not appear. However, when created they are working.
Sessions do not appear.

<img width="839" alt="screen shot 2017-10-26 at 3 52 55 pm" src="https://user-images.githubusercontent.com/7528337/32073947-d6ee72b4-ba65-11e7-9f04-9df620244510.png">

Server configuration

Operating system: Debian buster 64bit

Web server: Apache

Database: MariaDB

PHP version: 7.0

Nextcloud version: 12.0.3
