### ISSUE TITLE
Theming is broken in 12.0.1

### ISSUE THREAD

**Issue by mwaeckerlin** [nextcloud/server#6156]
Since Upgrade from Nextcloud 12.0.0 to 12.0.1, theming is not shown anymore, even though it is still correctly configured in the background:

Configuration is still ok:
![image](https://user-images.githubusercontent.com/4056726/29373862-d427aa98-82af-11e7-9158-00d514db3429.png)

Login page does not show configured settings, but the default:
![image](https://user-images.githubusercontent.com/4056726/29373934-046c721a-82b0-11e7-808a-c861ffba718a.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by danxuliu** [comment]
I could not replicate this on a fresh Nextcloud 12.0.1 installation.

I have also tested updating a Nextcloud 12.0.0 instance to Nextcloud 12.0.1 and I could not replicate it either, although it was not a _real_ instance (it was created fresh in Docker and then updated). Here are the steps that I used:
1. In a GNU/Linux console, run `docker run --detach --volume nextcloud-custom_apps:/var/www/html/custom_apps --volume nextcloud-config:/var/www/html/config --volume nextcloud-data:/var/www/html/data --publish 8080:80 --name nextcloud-test nextcloud:12.0.0` to create a new Nextcloud 12.0.0 instance.
2. In the browser, visit _localhost:8080_, set an admin user and password and finish the setup. The admin user is logged in to the Files app.
3. In the browser, open the Theming app and set a custom colour.
4. In the browser, log out; the colour is used in the login button.
5. In a GNU/Linux console, run `docker stop nextcloud-test && docker rm nextcloud-test` to stop and remove the Nextcloud instance.
6. In a GNU/Linux console, run `docker run --detach --volume nextcloud-custom_apps:/var/www/html/custom_apps --volume nextcloud-config:/var/www/html/config --volume nextcloud-data:/var/www/html/data --publish 8080:80 --name nextcloud-test nextcloud:12.0.1` to update the previous Nextcloud instance to 12.0.1 (because the _config_ and _data_ were kept in Docker volumes and thus reused by the new instance).
7. In the browser, visit _localhost:8080_. Click _Start update_ to... well, start the update :-P Once finished you are redirected to the login page. The button has the custom colour (and, if it is not, refreshing the page several times eventually sets the proper colour).

Note that in 12.0.1 there was a bug ([fixed in 12.0.3](https://github.com/nextcloud/server/pull/6067)) due to which the Theming app did not preview the colour as it should (and never removed the _Loading preview_ message nor the loading icon); however, even if the preview did not work, the colour was properly set and was shown once refreshed in the login button, the header and so on.

@mwaeckerlin, could you be hitting a browser cache problem?

**Comment by mwaeckerlin** [comment]
@danxuliu, no, no caching problem, problem is still unsolved. The theming does not work anymore, even tough the configuration is still there.

URL to the nextcloud instance: https://ggr.mrw.cloud

I'm using docker too, from my own Dockerfile, that implements a special app:

https://github.com/mwaeckerlin/ggrwinti

which inherits from my default nextcloud Dockerfile:

https://github.com/mwaeckerlin/nextcloud

which inherits from my default Ubuntu base Dockerfile:

https://github.com/mwaeckerlin/ubuntu-base

Persistent volumes are:
- /var/www/nextcloud/data
- /var/www/nextcloud/config

And of course, the database is in a persistent volume.

This is how it was started:
```
docker run -d --restart unless-stopped --name ggrwinti-volume mwaeckerlin/ggrwinti sleep infinity
docker run -d --restart unless-stopped --name ggrwinti-mysql-volume mysql sleep infinity
docker run -d --restart unless-stopped --name ggrwinti-mysql --volumes-from ggrwinti-mysql-volume -e 'MYSQL_DATABASE=nextcloud' -e 'MYSQL_USER=nextcloud' -e 'MYSQL_PASSWORD=xxx' -e 'MYSQL_RANDOM_ROOT_PASSWORD=1' mysql
docker run -d --restart unless-stopped --name ggrwinti -p 8002:80/tcp --volumes-from ggrwinti-volume --link ggrwinti-mysql:mysql -e 'ADMIN_PWD=xxx' mwaeckerlin/ggrwinti
```

Thus is how it was upgraded:
```
docker pull mwaeckerlin/ggrwinti
docker rm -f ggrwinti; docker run -d --restart unless-stopped --name ggrwinti -p 8002:80/tcp --volumes-from ggrwinti-volume --link ggrwinti-mysql:mysql -e 'ADMIN_PWD=xxx' mwaeckerlin/ggrwinti
```

**Comment by mwaeckerlin** [comment]
What I see as difference to your code, @danxuliu, is that I do note keep `/var/www/html/custom_apps`, a directory path, that does not even exist in my installation:
```
user@host:~$ docker exec -itu www-data ggrwinti bash
www-data@docker[c2d70b0d9048]:~/nextcloud$ ls custom_apps
ls: cannot access 'custom_apps': No such file or directory
```

**Comment by MorrisJobke** [comment]
Could you change the color to a different one and then back again? Maybe this is a problem within the theming cache buster.

**Comment by lenusch** [comment]
I can change Color but not Background :-)

**Comment by mwaeckerlin** [comment]
Changed to red, nothing happens. «Load preview» rotates for ever, color is not changed.
When I leave the setting and come back, the new red color is in the dialog, but not in the theme, theme is still default blue. The settings are stored, but not applied to the theme.

**Comment by mwaeckerlin** [comment]
Nothing works for me, neither the name. nor the url, nor the slogan, nor the color, nor th logo, nor the image. :(

**Comment by mwaeckerlin** [comment]
Same in Chromium as in Firefox: «Load preview» rotates for ever, color is not changed, so it's not a browser related problem.

**Comment by MorrisJobke** [comment]
@juliushaertl Any idea?

**Comment by juliushaertl** [comment]
@mwaeckerlin Any errors in your log. Strage is, that the generated theming.css file on the instance you've mentioned above doesn't contain anything.

**Comment by mwaeckerlin** [comment]
@juliushaertl see the attached log file from this server:

[nextcloud.log.zip](https://github.com/nextcloud/server/files/1276693/nextcloud.log.zip)

**Comment by skjnldsv** [comment]
@mwaeckerlin could you post the failing request response from your browser?

If the loader keeps spinning, it must be a xhr failure.

**Comment by mwaeckerlin** [comment]
@skjnldsv How can I get the request response (from firefox or from chromium)?

**Comment by skjnldsv** [comment]
Open the dev tools, click the network tab, change your theming settings, see the new request, click on it, click the response tab and copy/paste! :)

**Comment by skjnldsv** [comment]
@mwaeckerlin But far too much information in the whole har data.
I edited your post, having access to your username and encrypted cookie isn't really a good thing! :(
Please change your password! :)

On the other side, I'm checking it right now.

**Comment by skjnldsv** [comment]
Strange, it doesn't seems to refuse the request! It's not a settings registration issue.
Don't you have any errors in the browser's console?

![capture d ecran_2017-09-05_16-15-37](https://user-images.githubusercontent.com/14975046/30065554-943dc57e-9255-11e7-810b-ff981fbc1f8a.png)

**Comment by MorrisJobke** [comment]
Isn't this fixed with #6067 (in upcoming 12.0.3)?

**Comment by mwaeckerlin** [comment]
@MorrisJobke in this case, I'll retry when 12.0.3 is out (when?)

**Comment by MorrisJobke** [comment]
> @MorrisJobke in this case, I'll retry when 12.0.3 is out (when?)

Planned for next week, but can't promise anything.

**Comment by juliushaertl** [comment]
@mwaeckerlin You can already help testing the 12.0.3 release candidate: https://nextcloud.com/blog/help-test-nextcloud-12.0.3/

**Comment by mwaeckerlin** [comment]
works for me now, thank you

**Comment by melikyuksel** [comment]
I'm having this problem again on latest, 16.0.4.1. Settings save for theming, but have no effect.

**Comment by kesselb** [comment]
@melikyuksel please create a new issue.

**Comment by melikyuksel** [comment]
> @melikyuksel please create a new issue.

I thought it was related to this one since the manifestation was identical. I ran some tests and seems like my problem is related to #13718. Seems to be related to having both `trusted_proxies` and `overwritehosts`in the config file. I removed `overwritehost` and the problem went away.
