### ISSUE TITLE
Embedding owncloud in a iframe

### ISSUE THREAD

**Issue by aaronegger** [nextcloud/server#6286]
### Steps to reproduce
1. Install Nextcloud 10, 11 or 12.
2. Embed it in an iframe within a html file loaded from a different domain.
3. Navigate to the address of the html file.
4. See that there is a blank screen, because X-Frame-Options is set to Sameorigin (as expected).
5. Navigate to the admin menu and search for an option to set the X-Frame-Options.

### Expected behaviour
Option to change the X-Frame-Options Header, in order to load the NextCloud instance in an iframe.

### Actual behaviour
There is no option to set the X-Frame-Options.

### Server configuration

**Operating system**:

**Web server**: Apache

**Database**: MySQL

**PHP version**: 7.1

**Nextcloud version**: 12.x

**Updated from an older Nextcloud/ownCloud or fresh install**: Update chain from 9 to 12.

I don't think that there are a lot of information necessary, as there is obviously no option implemented to allow embeding the nextcloud from certain domains.

Is there something planed to support it without any workaround with apache rules?
If not, why?

It would be great, if embeding the nextcloud in iframe could be implemented :)

**Comment by MariusBluem** [comment]
@LukasReschke I think we don't do this for security reasons.

**Comment by leonidasv** [comment]
You could force X-Frame-Options to allow certain domains or just disable it by hardcoding nextcloud/lib/private/legacy/response.php line 260. Although it's not recommended by security concerns. Do it at your own risk.

**Comment by MorrisJobke** [comment]
@LukasReschke I guess there are good reason to have it disabled. Could you elaborate on this and close this ticket then? Thanks

**Comment by poef** [comment]
I understand the need for X-Frame-Options in the general case, but I'm writing an app that is expected to be used as an iframe. Because the current header is hardcoded in /lib/private/legacy/response.php instead of a default header in the base Response class, it is not an option to remove it in specific circumstances. 
I'm willing to create a pull request that changes this, but I'd like to know that there is a chance this gets accepted before spending time on it. Is there a write up of the security concerns that lead to the current implementation, so I can read up on it and make sure that any changes I make will still fulfill those requirements?

**Comment by aaronegger** [comment]
I can understand the concerns about security.
But allowing framing from known domains shouldn't have any effects on security.

But i also see that there is no interest to implement such an option.
