### ISSUE TITLE
I cannot upload files throuth web ui

### ISSUE THREAD

**Issue by zhbbupt** [nextcloud/server#6346]
### Steps to reproduce
1. upload new file in web ui

### Expected behaviour
upload file from local file system

### Actual behaviour
It returns "Not enough free space, you are uploading *** but only 0B is left"

### Server configuration

**Operating system**: ubuntu mate 16.04

**Web server:** nginx

**Database:** sqlite 

**PHP version:** php7.0

**Nextcloud version:** (see Nextcloud admin page)  all version

**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:** manual install

**Comment by MorrisJobke** [comment]
Looks like your quota is reached or your disk is full.

**Comment by zhbbupt** [comment]
no， the disk has 1TB left.

**Comment by MorrisJobke** [comment]
Could you please seek first in the forums for help: https://help.nextcloud.com

Once you have reproducible steps we are able to properly fix this because as of now we can reproduce this on our instances.

Other ideas: maybe SELinux or AppArmor is trying to intercept the request? Maybe the configured temp storage has no space left?
