### ISSUE TITLE
Show checkbox where the favorite star is now

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#6361]
As discussed at the conf:

* show the checkbox for selecting an element where currently the star icon is
* add a little star indicator at the top right of the mime type/thumbnail (as on Android and iOS)
* add the "Favourite" action to the three dots menu

cc @nextcloud/designers 

@danxuliu @ChristophWurst Does one of you want to look into this?

**Comment by danxuliu** [comment]
I will take care of this in the next days.

**Comment by jancborchardt** [comment]
An important addition is that the filetype icon / preview should then also be part of the clickable area to open the file / folder.

@danxuliu let me know when there’s something to review. :)

**Comment by danxuliu** [comment]
@jancborchardt I have started to implement this but as you can imagine there are several approaches for the CSS that would work. So any preference with respect to floats, absolute positions and things like that? Although probably someone else with good CSS knowledge will have to clean up my mess anyway :-P

>  An important addition is that the filetype icon / preview should then also be part of the clickable area to open the file / folder.

I assume that the star indicator would not be clickable given that the _Favourite_ action will be now in the three dots menu, right? Otherwise making the star indicator clickable and at the same time using the filetype icon / preview to open the file / folder would be very error prone.

**Comment by skjnldsv** [comment]
@danxuliu, I will help with css. Do everything you can. I will take a look at it! 👍 😉

**Comment by danxuliu** [comment]
>  I will help with css. Do everything you can. I will take a look at it! 👍 😉

Thanks a lot! :-) I will ping you in the next days ;-)

**Comment by jancborchardt** [comment]
> I assume that the star indicator would not be clickable given that the Favourite action will be now in the three dots menu, right?

Exactly, the favorite star would only be an indicator, not clickable. :)
