### ISSUE TITLE
Favicon cut off on the right

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#6375]
This happens in both Firefox and Chromium:
![screenshot from 2017-09-06 14-27-24](https://user-images.githubusercontent.com/925062/30111889-b66b5ef8-930f-11e7-9b07-41bdfa1065e1.png) ![screenshot from 2017-09-06 14-26-48](https://user-images.githubusercontent.com/925062/30111890-b69426bc-930f-11e7-85f8-9b19ce2e6874.png)

Any clue why @juliushaertl @nextcloud/theming?

**Comment by juliushaertl** [comment]
@jancborchardt No idea why this is happening. I also cannot reproduce this on FF/Chromium. Maybe some HiDPI issue? Can you check if https://github.com/nextcloud/server/pull/6460 might fix the issue for you, since it includes a fix to generate different sizes of favicons, so the browsers can pick instead of resizing them by themselves.

**Comment by juliushaertl** [comment]
@jancborchardt Does this issue still exist for you on master?

**Comment by jancborchardt** [comment]
@juliushaertl yep it does, basically still as in the screenshots. Can no one reproduce @nextcloud/designers?

**Comment by MorrisJobke** [comment]
Looks good here:

<img width="447" alt="bildschirmfoto 2017-12-12 um 08 11 31" src="https://user-images.githubusercontent.com/245432/33871740-181ef75e-df14-11e7-8aad-8d0d94b56838.png">

**Comment by pixelipo** [comment]
I was able to reproduce it on master until recently. Looks good since a couple of weeks.

**Comment by skjnldsv** [comment]
Good here too :)

**Comment by jancborchardt** [comment]
I still have it even in incognito mode. But if you all can not reproduce it, might be a problem specific to my setup. :) Closing
