### ISSUE TITLE
Indicator for tagged files in list

### ISSUE THREAD

**Issue by hajika** [nextcloud/server#6424]
It looks like there is no hint or any sign, when a file has tags or comments. You first have to open the details page to check if there is something. It would much more useful, if an icon or anything else would indicate that there are (unread?) comments available for a specific file,

The same is for tags, it could be useful to have an optional column for them (thats maybe a new issue..?)

**Comment by LukasReschke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
It would be a great addition indeed!

**Comment by jancborchardt** [comment]
New comments are indicated in the file list by an icon on the respective file.

Yes, we could also add the tags a file has been tagged with if it has any:
- right next of the filename, like Gmail
- clicking the tag shows all files with this tag

cc @schiessle @blizzz @nextcloud/javascript

**Comment by hajika** [comment]
> New comments are indicated in the file list by an icon on the respective file.

true! I didnt see it before, thats what I intended originally

![screenshot_2017-09-12_13-59-42](https://user-images.githubusercontent.com/27491258/30324837-b9ba62a4-97c2-11e7-9a2b-c141370c12d0.png)

It might be seen better, when the icon is not grey like the other ones but in a more attentive color.

**Comment by jancborchardt** [comment]
True, we could experiment with making it full opacity. Want to contribute that as a pull request @hajika?

**Comment by hajika** [comment]
I tried it with full opacity, Iam not fully convinced by the effect. And unfortunately css `fill` did not work on the `<img>` tag. Couldn't figure out yet why not.

**Comment by rasos** [comment]
Could we even have the Details view open by default, or at least a config option to show the Details by default with Comments at all users? I find the Details view with Tags, Comments or photos with an immediate preview and the Metadata extremely useful- why should we always need to click on the three dots first (which are not very intuitive for e.g. leaving a comment).

![bildschirmfoto_2017-11-11_23-41-02](https://user-images.githubusercontent.com/485723/32694192-00fa3e72-c73a-11e7-977d-cdfba8553d18.png)

**Comment by jancborchardt** [comment]
@rasos this is a separate discussion, please open a new issue. :)

We are talking about showing the sidebar by default on big screens: https://github.com/nextcloud/server/issues/7138

**Comment by skjnldsv** [comment]
@jancborchardt
And how many tags should we display?
I don't think this is a good idea to use a popover if someone wanted to implement that. :)

**Comment by hajika** [comment]
> to use a popover

I would prefer something in that direction, having always the all tags close to the filename would make it very unattractive and unclear. But only a popover for individual files would could make it a bit fiddly. I would like to have the option to show/hide tags for all files. But I'am not sure how that could be achieved in the best way, because making a switch link just for that single feature is a bit overblown.

**Comment by hajika** [comment]
> right next of the filename, like Gmail

@jancborchardt can you post a screenshot of that? Yes, I confess, I dont have a Gmail Account :)

**Comment by skjnldsv** [comment]
I think I would go for like 2/3 tags and a '+' button if enough space and just an empty tag icon if not enough space.

**Comment by jancborchardt** [comment]
@hajika I don't have Gmail either, check DuckDuckGo image search. ;)

@skjnldsv yup, let's say max 3 tags, and ellipsize them. I wouldn't add an interactive "+" though.

**Comment by hajika** [comment]
I'am afraid that it is going to look like this

![screenshot_2017-11-13_22-40-38](https://user-images.githubusercontent.com/27491258/32750711-cb4aa2c2-c8c3-11e7-90b7-13766e2b26f0.png)

**Comment by jancborchardt** [comment]
Well, it is going to be similar of course. However:

- with a limit of 2/3 tags though as mentioned
- and minus the color, or only colored border-radius, or a colored circle left of the text

**Comment by disaster123** [comment]
+1 for this

**Comment by sergio-salas** [comment]
Looking forward to this new feature implemented.

**Comment by jancborchardt** [comment]
@disaster123 @sergio-salas please use Github's built-in function to add a +1 reaction to the issue or a comment. Additional comments do not help and just notify everyone. ;)

**Comment by disaster123** [comment]
Any chance that this will happen? More and more people use tags instead of folders.

**Comment by disaster123** [comment]
No i don't have any research but look at all those duplicates of this request or at https://github.com/nextcloud/server/issues/4699 - there is a lot of noice regarding this topic. Or look at https://www.nayuki.io/page/designing-better-file-organization-around-tags-not-hierarchies

Also GMail, Outlook, Evernote and others have switched to or offer tag support.

**Comment by disaster123** [comment]
https://github.com/nextcloud/server/issues/6778 is more important to me so i donated to this one.

**Comment by fredt34** [comment]
Regarding #14525 : I suggest displaying the tags in a tooltip when the mouse hovers the file or link.

**Comment by putt1ck** [comment]
Tag visibility is useful for workflows - and helps show new user that tags exist as a thing

**Comment by Fmstrat** [comment]
Hi all, in the issue linked just above this comment, I've been proposing the idea of using the existing tags schema to handle note categories. I wanted to add a specific screenshot from that discussion here as it may be a way to not over-clutter the file list, too. The idea is that instead of "Tags" in the left nav taking a user to a "search by tag" page, tags are listed in the left nav and clicking them acts as a filter for the current display:

![after](https://user-images.githubusercontent.com/971474/84810498-6bd35f00-afd9-11ea-9d8b-8f8b08105fbd.png)

**Comment by fechnert** [comment]
I would **love** to see the tags of files (or folders at least) directly in the list view as described in #2838, but fixed to the right side like this:

![nextcloud_padding](https://user-images.githubusercontent.com/1409863/108848472-50493b00-75e1-11eb-927d-2cebafaeb736.png)

Showing a maximum of 2-3 tags together with a "+4" one for example, this would avoid the look of a tag-hell like in the github issue tracker.

Maybe even with custom color if desired like described in #6778. Maybe even re-use the categories introduced with https://github.com/nextcloud/calendar/pull/1540 to not reinvent the wheel ...

Seeing the tags right here in the list view instead of opening a lot of info cards would save a lot of time ...

**Comment by gabuzom** [comment]
> I would **love** to see the tags of files (or folders at least) directly in the list view as described in #2838, but fixed to the right side like this:
> 
> ![nextcloud_padding](https://user-images.githubusercontent.com/1409863/108848472-50493b00-75e1-11eb-927d-2cebafaeb736.png)
> 
> Showing a maximum of 2-3 tags together with a "+4" one for example, this would avoid the look of a tag-hell like in the github issue tracker.
> 
> Maybe even with custom color if desired like described in #6778. Maybe even re-use the categories introduced with [nextcloud/calendar#1540](https://github.com/nextcloud/calendar/pull/1540) to not reinvent the wheel ...
> 
> Seeing the tags right here in the list view instead of opening a lot of info cards would save a lot of time ...

Yes that would definitely be the view that makes the more sense to me. 

Also it could be visible the very same way in shares, for users not necessarily logged into the NC instance.

**Comment by thomasgg23** [comment]
And even could be displayed on the mobile device client with the "+4" sign for example in case of mobile phones.

Would love to see this in the core features.

**Comment by Spartachetto** [comment]
Rereading this issue, I do think that having the information that a file has any number of tags is for me already useful.

Saying it in another way, if I had an indicator which shows "this file has tags", similar to the comment indicator that just says "this file has comments", would already be gorgeous.

I do get the clutter that showing all the tags could lead.
For me a tag indicator would be a wonderful first step. After that a solution to display (some) actual tags could be looked for.

**Comment by PVince81** [comment]
besides the UI part:

there's a potential performance impact if tags are retrieved on the fly because it might require adding new Webdav properties to the PROPFIND (I don't remember if tags are already retrievable there), and populating these values require more database queries, so the file listing will load much slower depending on how this is implemented

a direct join in the database is likely not possible due to abstraction layers in core, so it is likely that other kind of optimizations might need to be considered like caching the tags temporarily somewhere easy to resolve

now if the tags are only displayed on hover, the query would be done on-demand so the performance impact would be much lower

**Comment by fechnert** [comment]
It would be awesome to have this idea implemented some way though.

Having a folder of historically ordered subfolders for like an archive of events is quite common. Having the ability to tag these and search for folders of these tags is our currently quite nice, but it would be even better to have the tags visible in the list.

**Comment by Spartachetto** [comment]
@fechnert this is even more important considering that the extention of search to also cover tags is still not finished. See #26813

**Comment by earendil1** [comment]
Hi,
The usefulness of such a column in order to see what files have been tagged or is high in cases in which the user is looking for differences in properties among files and wants to do that without having to type them all in in a search bar.

I have had a look at the thread and understand the uneasiness connected to the fact that the view might be cluttered. 

However, if we consider that:
- it is the user who is going to choose how many of those tags s/he wants to use and
- the column is optional, 
- the user could define how many tags should be displayed

This could be a service to all those who deem it useful (think of tagspaces.org!), without diminishing the user experience of the others.

Introduction of:
- colours for tags
- tag groups having the same colour

Would be a greatly appreciated improvement too. Thanks!

**Comment by gonzalo** [comment]
I agree it would be great to get this feature available. We're using tags combined with file access control to make some shared folders to be available only from internal network. I would like to identify easily those folders when navigating the structure as @fechnert  proposes
