### ISSUE TITLE
(Group) shares should list all users that received the share

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#6480]
* having a group with user A, B, C, D
* user A shares with this group a folder
* user B now only sees, that it is shared with that group, but does not know who is in this group and therefore maybe reshares to user C

Related to #3392, #4281 and how shares in circles are handled.

cc @nextcloud/designers for nice ideas how to show this
cc @daita for circles
cc @nextcloud/sharing for the general sharing stuff

**Comment by daita** [comment]
I don't know if we should display the memberlist, but maybe (if it is not already the case) check if the file is already shared in any way (circles, groups, ...) to C (and display a message that the file is already shared). Like browsing all provider->getSharedWith() (not sure at 100% on this call). 

Now, what is gonna happen if A share a folder to the group and B shares a single file from this folder to C ?

**Comment by rullzer** [comment]
Listing all members is a big no go. This will explode hard. Assume an LDAP group with 10k members. That is not going to be of any use.

What we should do (what is still on the TODO somewhere) is do more grouping of shares. So that the receiving end doesn't care.

Then we can also lift this silly restrictiong that you can't share to somebody that already got the share. Since it will be grouped anyway.

**Comment by jancborchardt** [comment]
Besides @rullzer’s point what we could do is show a tooltip with the members, or at least the first 10 »and 25 more«. That’s similar to how Github does it for teams when you hover them (see above in @MorrisJobke’s original issue when you hover the designers group) and also how we did it in the video calls app navigation.

**Comment by skjnldsv** [comment]
I guess fixed with 18 righty?
With the new inherited shares :)
