### ISSUE TITLE
[Feature Request] Split View

### ISSUE THREAD

**Issue by slideup-benni** [nextcloud/server#6484]
Hello, 
it would be very nice when you could implement a split view in the files app. 
In my opinion it is very complicated to move files or folders with the webview. With a split view you could implement drag and drop to move files over multiple folders.

**Comment by MorrisJobke** [comment]
Bulk move is implemented with #6273 in 13 and the file picker should be a bit better with #644. I guess we will not add a split view, because it is a very limited use case (moving files) and a major overhaul of the whole UI. I will close this ticket here with the reference to the two mentioned tickets above. Thanks for the feedback anyway

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yup, what @MorrisJobke said.
