### ISSUE TITLE
Add public page template for apps

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#6553]
Many apps now offer public pages that are shown to users that are not logged in to the instance.
There should be a common template for those pages, that apps can use.

Right now every app includes its own template:
- gallery: https://github.com/nextcloud/gallery/blob/master/templates/public.php
- calendar: https://github.com/nextcloud/calendar/blob/master/templates/public.php
- files_sharing: https://github.com/nextcloud/server/blob/master/apps/files_sharing/templates/public.php
- spreed: https://github.com/nextcloud/spreed/blob/master/templates/index-public.php
- polls needs that as well: https://github.com/nextcloud/polls/issues/96#issuecomment-330154123

@nextcloud/designers

**Comment by dartcafe** [comment]
Mabe it could be a layer in front of the login page with some information and the possibility for a login. 

Quick pattern: 
![grafik](https://user-images.githubusercontent.com/26707476/30556010-aeff92d0-9ca9-11e7-9133-c73eca3828fe.png)

**Comment by jancborchardt** [comment]
@dartcafe one of the strengths of our sharing pages is that it basically is as nice and seamless as if you were logged in. Putting it in an extra box would deteriorate that.
It would be problematic too with elements like navigation on the left or sidebar on the right.

Also, mostly link shares are to people who do not have or even know Nextcloud, and most definitely are not on your instance. Also most often there's no way to "sign up" to ones instance. :)

Another point is testability. If we have a different layout induced by the container, we need to be extra cautious to check if things don't break, cause they most likely will.

Short: That's why the sharing views should be modeled after the main views. ;)


@juliushaertl yep, unifying that would be good!

**Comment by dartcafe** [comment]
No problem, this was just a suggestion. 

But to explain my thought: When a user is not logged on and enters nextcloud, he is faced with the customized login page (colors, background, ...). Something like a brand. 

When the same user enters a public page of an app, he could prefer seeing the same brand, but with the public content. An mostly empty page looks very neutral and one is like the other, exept some colors. It's OK for logged on users because the focus is functionality and content. For a public page the focus moves a ittle bit in direction design and layout. 

And as far as I can see, the public pages normally have limited functionality. Additionally it is a clear signal of "You are not logged on!"

Also I understand the challenges...

**Comment by jancborchardt** [comment]
> And as far as I can see, the public pages normally have limited functionality.

This is however not intended. ;) We need to keep in mind future things like commenting display and ability in public pages, and so on.

Also, apps like Calendar and Video calls already use the whole screen and need it too. Having the header for branding is enough here – after all we want to help people get things done, not have brands shoved in their faces over content. :)

**Comment by juliushaertl** [comment]
> Additionally it is a clear signal of "You are not logged on!"

This is something we should consider. It should be easy for the user to recognize that he is not logged in and possible to login and continue with the data from the public page.

**Comment by pixelipo** [comment]
I noticed this as well, recently I had to open 2 PRs (one in [nextcloud/core](/nextcloud/core) and one in [nextcloud/gallery](/nextcloud/gallery) ) to fix a single bug...
