### ISSUE TITLE
Built-in share-by-email date expiration enforcement not working properly 

### ISSUE THREAD

**Issue by hE-rx** [nextcloud/server#6603]
### Steps to reproduce
1. Configure default expiration date
![Set expiration Date](https://image.ibb.co/ei0Hyk/Set_Expiration_Date.png)

2. Share link via mail for external user mail address
![Share By Mail](https://image.ibb.co/mMpGr5/Share_By_Mail.png)

### Expected behaviour
The generated link for external user should have an expiration date set

### Actual behaviour
No expiration date set for shared link
![Shared](https://image.ibb.co/bNX5Jk/Shared.png)

### Server configuration

**Operating system**: Debian 9.1

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0.19-1

**Nextcloud version:** 12.0.3

**Comment by blizzz** [comment]
@nextcloud/sharing

**Comment by mpede** [comment]
Hi there,
firstly - great work on this project. Just a comment on this, I agree that this functionality should be available but I didn't expect it when configuring the server after install, because the share by email settings are separate from the sharing with users settings. And in the sharing by email section there is no expiry enforcement (see screenshot). 
Now you can either combine the two into one section, or have the expiry enforcement selected separately for email. 
For me, from a governance perspective, it would be better to select enforcement only once for both, password and expiry. 
![admin_-_chr15_eu___nextcloud](https://user-images.githubusercontent.com/4440614/32345853-c1d6911c-c00b-11e7-88ff-7a0ea6c50503.jpg)

**Comment by blizzz** [comment]
ping @rullzer @schiessle

**Comment by marcos-guerrero** [comment]
Hi!
Agree with @mpede , it would be great to have only one settings for all kind of sharing "Sharing" and "Share by mail" relating to:
*Enforce password protection
*Expiration date

**Comment by ethantq** [comment]
Any update on this feature? Moving from Owncloud to Nextcloud and found this disappointing as I'm pretty sure OwnCloud had this working since the link was created and then emailed out. We use this for temporary sharing so having this feature is a must. I was forced over to nextcloud because owncloud version 10 could not migrate to mysql from sqlite. Everything feels snappier and much cleaner now.

**Comment by schiessle** [comment]
@ethantq up until now, ownCloud doesn't have share by mail at all. This is a complete new share provider, only exists for Nextcloud. This shouldn't be a excuse. I agree that we might want to have this setting also for the share by mail, but unfortunately other stuff had a higher priority for Nextcloud 14. But I didn't forgot it. Maybe it will make it in Nextcloud 15.

If you want to go back to a "ownCloud-like" experience you can disable the share by mail app, enable instead the "Social Sharing via mail" app https://apps.nextcloud.com/apps/socialsharing_email Then you can create normal public links and send them out by mail, as used to from ownCloud.

**Comment by wiswedel** [comment]
I think this issue's basic question has been solved. 
I suggest to close this ticket and follow @mpede 's feature request here: #14536

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
