### ISSUE TITLE
Update 12.0.0 --->> 12.0.3 - fails on local DEBIAN 9 System

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#6606]
Hi,

If I press update button I only receive the message:

Aktualisierungsfunktion konnte nicht gestartet werden, bitte versuche ein mauelles Update

And I have to manually update the server!

Why do i have to do it all over again each time I would like to update the server ???

Each update - minor or major - is ALWAYS a MAJOR headache!

My advice: NEVER UPDATE A running NC server! It only gives you a big headache !

Regards, Hitam4450

PHP Version 7.0.19-1, Lighttpd 1.4.35, DEBIAN 9.1

![nc_update](https://user-images.githubusercontent.com/9738727/30710295-6445562c-9f05-11e7-9d96-12f38a06adc7.png)

**Comment by LukasReschke** [comment]
Ref https://github.com/nextcloud/updater/issues/144

**Comment by carboneater** [comment]
### Steps to reproduce
1. Wait for new NC version
2. Open Updater
3. Click Start Update
4. Get to Dowload file Step
5. Get 504 Error from NGINX
6. Get error on File Validation (Probably because file is not completely downloaded
7. Update Stalls with "Error parsing response. Step 5 is currently in progress. Please reload this page later."

### Expected behaviour
0. ...
1. Click Update button
2. Download NC Update file (Probably on async)
3. NC Updates server files

Alt: 

0. System downloads NC Update Zip (Either Auto or from admin input)
1. Click Update Button
2. NC Updates server files

### Actual behaviour
1. Click Update Button
2. Download/file verification fails
3. Update Fails & Stalls. For Days

### Server configuration
**Operating system**:
Linux *redacted* 4.11.0-1-amd64 Debian buster/sid 4.11.6-1 (2017-06-19) x86_64 GNU/Linux

**Web server:**
nginx/1.13.5

**Database:**
MariaDB 10.1

**PHP version:**
PHP 7.0.22-3 (cli) (built: Aug 23 2017 05:51:41) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-3, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
12.0.2 -> 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Previously Updated (and failed) from 12.0.1 and 12.0.0 prior

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.4
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dashboard: 4.0.5
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - systemtags
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc6n6tqq77xl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "tsunami.ageg.ca",
            "nextcloud.ageg.ca"
        ],
        "datadirectory": "\/srv\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/tsunami.ageg.ca",
        "dbhost": "localhost",
        "dbname": "nextcloud",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "version": "12.0.2.0",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "openssl": {
            "config": "\/etc\/ssl\/openssl.cnf"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "serveur",
        "mail_domain": "ageg.ca",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "sleipnir.ageg.ca",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope

**Are you using encryption:** yes/no
Not Nextcloud's internal encryption

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------+
| Configuration                 | s01                                                        |
+-------------------------------+------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                            |
| hasPagedResultSupport         |                                                            |
| homeFolderNamingRule          |                                                            |
| lastJpegPhotoLookup           | 0                                                          |
| ldapAgentName                 | cn=nextcloud,ou=services,dc=ageg,dc=ca                     |
| ldapAgentPassword             | ***                                                        |
| ldapAttributesForGroupSearch  |                                                            |
| ldapAttributesForUserSearch   |                                                            |
| ldapBackupHost                |                                                            |
| ldapBackupPort                |                                                            |
| ldapBase                      | dc=ageg,dc=ca                                              |
| ldapBaseGroups                | dc=ageg,dc=ca                                              |
| ldapBaseUsers                 | dc=ageg,dc=ca                                              |
| ldapCacheTTL                  | 600                                                        |
| ldapConfigurationActive       | 1                                                          |
| ldapDefaultPPolicyDN          |                                                            |
| ldapDynamicGroupMemberURL     |                                                            |
| ldapEmailAttribute            | mail                                                       |
| ldapExperiencedAdmin          | 0                                                          |
| ldapExpertUUIDGroupAttr       |                                                            |
| ldapExpertUUIDUserAttr        |                                                            |
| ldapExpertUsernameAttr        |                                                            |
| ldapGidNumber                 | gidNumber                                                  |
| ldapGroupDisplayName          | cn                                                         |
| ldapGroupFilter               |                                                            |
| ldapGroupFilterGroups         |                                                            |
| ldapGroupFilterMode           | 0                                                          |
| ldapGroupFilterObjectclass    |                                                            |
| ldapGroupMemberAssocAttr      | uniqueMember                                               |
| ldapHost                      | ldapi:///                                                  |
| ldapIgnoreNamingRules         |                                                            |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(cn=%uid)))) |
| ldapLoginFilterAttributes     | cn                                                         |
| ldapLoginFilterEmail          | 0                                                          |
| ldapLoginFilterMode           | 0                                                          |
| ldapLoginFilterUsername       | 1                                                          |
| ldapNestedGroups              | 0                                                          |
| ldapOverrideMainServer        |                                                            |
| ldapPagingSize                | 500                                                        |
| ldapPort                      | 389                                                        |
| ldapQuotaAttribute            |                                                            |
| ldapQuotaDefault              |                                                            |
| ldapTLS                       | 0                                                          |
| ldapUserDisplayName           | displayname                                                |
| ldapUserDisplayName2          |                                                            |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                             |
| ldapUserFilterGroups          |                                                            |
| ldapUserFilterMode            | 0                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                              |
| ldapUuidGroupAttribute        | auto                                                       |
| ldapUuidUserAttribute         | auto                                                       |
| turnOffCertCheck              | 0                                                          |
| turnOnPasswordChange          | 0                                                          |
| useMemberOfToDetectMembership | 1                                                          |
+-------------------------------+------------------------------------------------------------+
</details>

### Client configuration
**Browser:**
Both Chrome & FireFox
**Operating system:**
Both Linux & Windows

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
nextcloud.access.log:10.43.47.101 - - [22/Sep/2017:20:38:07 -0400] "POST /updater/index.php HTTP/2.0" 504 176 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0"
</details>
Failed to find relevant logs inside nextcloud.log, nginx.error.log or PHP's error logs

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Failed to find relevant logs inside nextcloud.log, nginx.error.log or PHP's error logs
</details>

#### Browser log
<details>
<summary>Browser log</summary>
No errors on console...
Network logs reports a 504 on POST /updater/index.php
(Sorry, couldn't figure out how to export those before losing it all)
</details>

**Comment by MorrisJobke** [comment]
We haven't seen this issue for a while and many working updates via the web as well as via the CLI updater I will close this ticket. If this is still happening please feel free to reopen.
