### ISSUE TITLE
colored tags

### ISSUE THREAD

**Issue by disaster123** [nextcloud/server#6778]
As folders get more and more outdated today and tags are the new folders. I also see the future of tags in nextcloud.

While using a lot of tags it get more difficult to distinguish between them. A color per tag can make this easier.

**Comment by hitam4450** [comment]
I agree and support your suggestion!

**Comment by juliushaertl** [comment]
Makes sense to have for me. I think also with https://github.com/nextcloud/server/issues/6424 it will make tags much more useful and colors will help recognize them easily.

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Yup. We should however go easy on the color to not make it too garish as also commented in https://github.com/nextcloud/server/issues/6424#issuecomment-344180922 – for example by only coloring the border. And keep in mind for accessibility reasons we should ideally never rely on color alone, except in rare cases where space is limited (like in the cards of the Deck app).

**Comment by skjnldsv** [comment]
I agree with the idea of coloring the border, and maybe coloring the bg as well on hover only. We need to keep it clear! :)

**Comment by stefan-niedermann** [comment]
Coloring on hover would mean you need to invert back- and foreground color when the default background color is white. This hurts my eyes ;-) Just keep it in mind.

**Comment by disaster123** [comment]
Is there a way to pay / sponsor / support this feature?

**Comment by juliushaertl** [comment]
@disaster123 You can donate to a bounty at bountysource: https://www.bountysource.com/issues/50078236-colored-tags

**Comment by disaster123** [comment]
Ok i added a $100usd bounty to bountysource

**Comment by tevon456** [comment]
this still available right?

**Comment by skjnldsv** [comment]
Yes, this is still waiting for someone to take care of it :)

**Comment by disaster123** [comment]
still nobody?

**Comment by earendil1** [comment]
Hi, I suggest to consider using colors to distinguish categories of tags.For example I have a tag set for Animals, its subtags would be Cat, Elephant, Dolphin. These would all have the same color. Then a tag set called Trees: its subtags would be Oak, Cypress, Beech

**Comment by furiousnow** [comment]
Colors for tags would be great to see, please.

**Comment by heisian** [comment]
> Hi, I suggest to consider using colors to distinguish categories of tags.
> 
> For example:
> 
> I have a tag set for Animals, its subtags would be Cat, Elephant, Dolphin. These would all have the same color. Then a tag set called Trees: its subtags would be Oak, Cypress, Beech, etc. All with a different color from the Animals.

yes I generally agree with this idea, however the issue arises when you have many different categories and end up seeing a file list with a whole rainbow of different colors... it eventually becomes meaningless

**Comment by heisian** [comment]
Yes I think a combination of muted colors and/or icons could be cool.. but can't you just add emojis to the beginning of a tag?

..just tested putting emoji's in tags, it works

**Comment by Bugsbane** [comment]
Yes you can put an emoji in a tag, but emojis and icons aren't the same thing. This is likely why we don't just use emojis to represent all the Nextcloud apps in the app menu.

With a proper monochrome icon set, theming can adjust the color appropriately, with emoji's it can't. With icons you can have a clean, monochromatic iconic set of images that all match each other, as in the photo above, unlike with emojis. For example, you can make the icon color match the tag color, unlike emojis. The icons in the tags above are simple and non-distracting, avoiding pulling excessive attention of the user. Emojis are typically too colorful and detailed to be used in many places in a UI without causing distraction. For example if you look at the photo above, the team tag would have to use an emoji like one of the following: 🤼🧑🏿‍🤝‍🧑🏻🫂 instead. None of those are as clean, easily readable or professional looking.

So yes, using an emoji is a currently available dirty workaround, but it doesn't provide the professional, uniform, scalable, themeamable look of a well chosen icon set. It also doesn't provide options such as shrinking tags where space is limited to just use the icon instead of the whole tag name.
