### ISSUE TITLE
Calendar: Remove valarms from objects in read-only shared calendars

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#679]
In ownCloud once there was a patch that removed valarms on shared calenders.
The purpose is to not be flooded by alarms by read-only shared calenders.

Ref: https://github.com/owncloud/core/issues/24377

**Comment by nursoda** [comment]
My family and my colleague use NC and have their own calendars. They shared some of them read-only and some of them read-write. They set up alarm, all of them ring on my phone, but I don't want to see/hear all their reminders!

I write this since I think that the proposed "solution" doesn't eliminate the root issue. Why?

I'm a secretary. I manage appointments for my boss. I see 3 possible user expectations:
- I also set up reminders for him (only), since that's what he expects me to do: manage all his calendar.
- I might set up alarms in his calendar that are meant to me (like to prepare the room). One might argue, that in that case I should add an event with alarm in my own calender. OK, I can live with that.
- Only my boss may set up reminders on his events (since it's his phone ringing then, after all).

So, I vote alarms be INDEPENDENT of the calendar status (read-only vs. read-write). Proper solutions could be to add a property that lets a user select
- whether or not to share valarms (read-write/read-only same as calendar itself) -or-
- whether or not to import valarms - or-
- for which user(s) an alarms should ring.

**Comment by tobiasKaminsky** [comment]
Closed as moved to calendar repo

**Comment by georgehrke** [comment]
I know that the caldav sharing standard says something about reminders. Will have to research that

**Comment by aartsr** [comment]
@georgehrke just wondering if there's any progress on this issue, it's the one thing that's stopping us from starting to use nextcloud :)

**Comment by georgehrke** [comment]
So, that's the [CalDAV sharing standard](https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-sharing.txt).

In section [5.5.4](https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-sharing.txt#L775) it says:
> Servers MUST support "per-user" calendar data in calendar object resources stored in shared calendars.  This allows each sharee and the sharer to store their own alarms and free busy transparency status without "interfering" with other users who also have access to the same calendar object resources.

=> we need something like a `calendarobjects_per_user` table to store custom custom alarms and transparency settings on a per sharee basis

**Comment by nursoda** [comment]
@georgehrke To me it seems that now no bug is open to address this (https://github.com/nextcloud/calendar/issues/211 is closed, too) - or I have overlooked it. Could you please check (and post a reference here)?

**Comment by georgehrke** [comment]
This very bug we are commenting is open.

**Comment by vmuth** [comment]
Hi, in https://github.com/owncloud/core/issues/24377 I posted a file for this issue with owncloud 9.0. I think this hack ( https://github.com/owncloud/core/files/461943/caldavbackend.php_oc90-no-Alarm-For-ReadOnly-Shared-Calender.txt ) can also be modified to work with nextcloud(?)

Have a look for "clearVALARM" in line 536 and line 586 as well as 'katinkas hack' in line 1396-1425. 

It's running now in company with more than 100 employees for months now and works fine.

Maybe somebody can tell me (or send a link) how to check in these lines in the code base? :)

**Comment by jkalousek** [comment]
@vmuth solution seems almost right but for my use case it would need to be applied to all calendars because I have multiple users, all with write access but I don't want any reminders to be shared between them (so each of them can setup theres personal reminders). So maybe option to filter out any reminder synchronization between calendars?

**Comment by nursoda** [comment]
Please do add a milestone to this issue.
