### ISSUE TITLE
Proposal: add CMIS Standard for files

### ISSUE THREAD

**Issue by frank-dspeed** [nextcloud/server#6850]
CMIS is the defacto Standart for Content Managment this project should adopt it.
- https://de.wikipedia.org/wiki/Content_Management_Interoperability_Services

**Comment by Escubaer** [comment]
Yes, this should be added quickly! Ideally fully tested with Apache Chemistry.

**Comment by nickvergessen** [comment]
It's highly unlikely that someone implements a SOAP backend in our php code.
Feel free to do it yourself when you got some knowledge there. Otherwise you will have to look for a Webdav CMIS bridge or something

**Comment by frank-dspeed** [comment]
@nickvergessen your probally right i should reqrite nextcloud in nodejs

**Comment by rullzer** [comment]
@frank-dspeed by all means feel free to do that.

But I agree with @nickvergessen this is not something we'd want to add to the server as it would require yet another endpoint to maintain. If somebody wants to do it they should write an app that does it.

**Comment by marneu** [comment]
May I second the request? 
Within LibreOffice 6 a function exists "Store on Server" and you can connect to most of the big player services incl. sharepoint a.s.o.  using CMIS.
In my opinion this should rather be one other possible connector from the base - not from a 3rd.

**Comment by nickvergessen** [comment]
@marneu You can use the WebDAV option for that:
* Type: `WebDAV`
* Host: `cloud.yourdomain.com`  (check save connection when you use https to access the site)
* Description: `My Nextcloud`
* Root: `/remote.php/webdav/`

Afterwards you are asked for username and password. Instead of the password I would recommend to give it an App Token, so go to `https://cloud.yourdomain.com/index.php/settings/user/security` and create one.

I just tested this and it works quite fine.
