### ISSUE TITLE
Support XMPP Authentification - XEP-0070

### ISSUE THREAD

**Issue by tigre-bleu** [nextcloud/server#687]
It would be nice if nextcloud support XEP-0070: XMPP Authentification.
http://xmpp.org/extensions/xep-0070.html

This would allow to authenticate the connection to nextcloud via any XMPP instant messenger. A plugin for wordpress already exists: https://wordpress.org/plugins/xmpp-auth/

**Comment by tigre-bleu** [comment]
I would imagine a workflow like this in order to give the choice between XMPP and Password authentification:

Add a Jabber/XMPP authentification admin setting to enable/disable the function and configure the auth server.

Login page is not changed when a user first arrives.
Then user enters the user name:
* If the text does not look like a jid, keep the page as it is with the password field.
* If the text does look like a jid (something@something.xxx): Split the password field from the username field and insert something in between a button for XEP-0070 authentification like this:

--
>[_user@domain.com_] //Text Field
>
>   Authenticate with 
>
>[ InstantMessage ] //Button
>
> Or
>
>[_password_] //Text Field

--

**Comment by Bugsbane** [comment]
Would xmpp based authentication not be done as a plugin/app as, presumably, LDAP authentication is done now?

If so then it seems that we're not just designing the ui for xmpp based login, but for how we handle having more than one authentication method people can use to authenticate. If that's the case, then we should also think about what ui we present if we have more than 2 login methods available later, so it remains consistent.

I'd recommend having text like "Log in using:" and then buttons underneath eg "Jabber/XMPP" and "Federated Cloud ID" etc. Clicking one reveals fields requesting the appropriate info for that authentication method. This would only show where more than one authentication was enabled, otherwise it goes straight to requesting the info for the enabled method.

If we go this route, I'm happy to help with any icons needed for the buttons.

**Comment by MorrisJobke** [comment]
> Would xmpp based authentication not be done as a plugin/app as, presumably, LDAP authentication is done now?

Yes. This should be done as app. Check out all the user_* apps, that provide user backend. user_saml for example.

**Comment by poVoq** [comment]
Has anyone started working on this? Would be a cool option for allowing people to use a 3rd party XMPP server for logging in and then using federated chat via the XMPP chat app that is already available (using an external XMPP server).
