### ISSUE TITLE
[Question] Why not disable apache mod_dav in .htaccess?

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#6894]
In admin manual, the example nextcloud apache config contains disabling the apache `mod_dav`: https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#apache-web-server-configuration

This makes sense, as nextcloud has it's own dav implementation. But why this is not just added to the default `.htaccess` file, shipped by nextcloud? To make nextcloud as good working on shared hosts as possible, I guess every apache and php setting possible, should be (also) shipped with the `.htaccess` file.

**Comment by blizzz** [comment]
Since it can only be set in a "directory" context (cf. https://httpd.apache.org/docs/2.4/mod/mod_dav.html#dav) which is to be set within server configuration, not  .htaccess (cf. https://httpd.apache.org/docs/2.4/mod/directive-dict.html#Context). Thus it is a limitation of the  module (or apache itself). Hope that answers the question.

**Comment by MichaIng** [comment]
Ah okay, I interpreted directory context also as .htaccess since it is also set for just it's directory. Yeah this answers the question thx.
