### ISSUE TITLE
Detect walled garden on android

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#6967]
We want to detect if a wifi connection can be directly used as internet connection or if it has some login portal.
Therefore we try to get an empty file, wich then returns only 204.
Is there something like that already in the server?

Ref: https://github.com/nextcloud/android/pull/1672

**Comment by rullzer** [comment]
Why can't you already request one of the already publicly available files? Like status.php? Or the public capabilities?

Or does it really need to be an empty response with a 204 return?

Adding that is no problem. But if not needed I prefer not to ;)

**Comment by hilbix** [comment]
I think the problem is, that there are so many and weird walled gardens out there.  Some might just serve everything with 200 until authenticated.  However it is unlikely that such a setup ever will return 204 as it makes no sense in that scenario.  I like the idea with 204 ;)

This also might be good to be able to detect if some really weird content sniffer application out there has tampered with the data.  You cannot use SSL-cert-checking reliably, because [BlueCoat](https://en.wikipedia.org/wiki/Blue_Coat_Systems) always will compromise TLS.  (Read: Never trust TLS, so we need a mandatory second layer of security on app layer as well.)

**Comment by tobiasKaminsky** [comment]
Yeah, I already had the idea with status.php. Then I'll have to parse it and check if it is a valid json and not any arbitrary file returned by the walled garden setup.

**Comment by rullzer** [comment]
Ok as discussed with @LukasReschke this should be fine.

Let me do this tomorrow so it can go into 13

**Comment by rullzer** [comment]
PR in #7041
