### ISSUE TITLE
Using unix socket for dbhost no longer works

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/server#7058]
Note that this is using the daily master tarball, as well as the daily stable12 tarball.

### Steps to reproduce
1. Use for example `localhost:/tmp/sockets/mysql.sock` in the Database Host field during installation, as recommended here: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html .
2. Submit

### Expected behaviour
Nextcloud should use the specified socket for the database like it does in v11.

### Actual behaviour
It doesn't accept it.

![image](https://user-images.githubusercontent.com/946674/32392967-f244bc78-c094-11e7-953f-7809a306ae72.png)

**Comment by kyrofa** [comment]
This regression was introduced by #6645. It now assumes anything with a colon is an ipv6 address, which is not the case.

**Comment by kyrofa** [comment]
This change was backported to v12 in #6774.

**Comment by sempervictus** [comment]
Regex for matching ipv6 is a google search away, this is some serious breakage for a very greedy match on ':'  which will break a lot of installs. How did that even make it to master?

**Comment by kyrofa** [comment]
I'm also concerned that there's no test to ensure unix sockets continue to work.

**Comment by MorrisJobke** [comment]
Okay - let's revert the stable12 backport and then have a look on master at it. Thanks for finding this.

**Comment by MorrisJobke** [comment]
Fixed via #7102

**Comment by xekon** [comment]
was this ever resolved?
I am trying to setup nextcloud now:

	wget https://download.nextcloud.com/server/releases/latest-13.tar.bz2
	tar -xjvf latest-13.tar.bz2
	rm -f latest-13.tar.bz2
	sudo mv nextcloud /var/www/html/nextcloud/

using ubuntu 18.04, nginx, postgresql10

on the installer page I get the following error that suggests its still trying to use IPV6 instead of my unix socket, in pg_hba.conf I have commented out everything except for the unix socket, I have tested the socket from the command line and it does indeed work, so my only guess is this issue is not yet resolved?:

here are the directions I followed which outline how to specify the socket: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/config_sample_php_parameters.html

under the database configuration I specified the socket:
localhost:/run/postgresql/.s.PGSQL.5432

which can be found with the following command:
sudo find / -type s

here is the error I get when trying to install nextcloud:
![nextcloud-error](https://user-images.githubusercontent.com/106644/39541810-acda0dd8-4dfb-11e8-9a5c-b06100fed544.PNG)

If you require any more input from me, I would be happy to help. Thanks.
