### ISSUE TITLE
strange problem when shared with password 

### ISSUE THREAD

**Issue by alahwany** [nextcloud/server#7258]
hello,

i have problem when shared a file or folder with password 

when shared it and set password some devices when opening the link and write the password the icon for login not active !!!!!! and some devices working fine 

i have tested it with internet explorer working fine will all devices but with google chrome or firefox some devices working and some devices not working 

can any one helping me please ?

Nextcloud version 12
OS: Centos with Cpanel

![capture](https://user-images.githubusercontent.com/14204438/33167324-de752730-d045-11e7-9e49-d2457edffc87.JPG)

**Comment by LukasReschke** [comment]
Please fill out the issue template so that we have more information about your setup. Thanks.

**Comment by alahwany** [comment]
i have attached the image but i don't know how to male this issue in template can you help me ?

**Comment by splitt3r** [comment]
Have a look at https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

**Comment by shaneonabike** [comment]
### Steps to reproduce
1. Go to a folder
2. Click Share
3.Set a password
4. Try to test that link with password set on Ubuntu - Firefox / Chrome and get invalid password

### Expected behaviour
Entering the password would be valid and work

### Actual behaviour
Entering the password loops around in indicating that I should try again. I **believe** that I discovered the actual problem! If I enter a password and click _away_ from the password dialogue, it saves, and then creates a link. When I tried it again on both browsers doing this the link and password are **fine**. I think what is happening is that the password dialogue is storing the actual _hard return_ if that's possible. Then when I attempt to log in for Chrome or Firefox it doesn't work.

### Server configuration

**Operating system**: Ubuntu
**Web server:** Apache2
**Database:** Mysql
**PHP version:** php 7.1
**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes
**Where did you install Nextcloud from:**
Your download page
**Signing status:**
<details>
<summary>Signing status</summary>

```
No failures
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.2.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - encryption
  - files_external
  - files_texteditor
  - files_versions
  - firstrunwizard
  - nextcloud_announcements
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocph33vhu3m1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.blahbla.com"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.blahbla.com",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "php",
        "mail_from_address": "someperson",
        "mail_domain": "blahbla.com",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "mail.blahbla",
        "mail_smtpport": "465",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "preview_max_scale_factor": 1,
        "asset-pipeline.enabled": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "updatechecker": false,
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** N/A
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** Nope

### Client configuration
**Browser:** Chrome  64.0.3282.140

**Operating system:** Ubuntu
