### ISSUE TITLE
Some issues with cancel button and delete icon when comments are edited

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7281]
The _Cancel_ button shown when a comment is edited overflows in the next comment, as can be seen in the screenshot below:
![comment-edit-cancel-overflow](https://user-images.githubusercontent.com/26858233/33220566-a1902d6a-d149-11e7-8342-b9b2c1bb44ae.png)

It is more evident when the next comment is also in edition mode, as in that case the _Cancel_ button of the previous comment and the _Delete_ icon of the next comment overlap:
![comment-edit-delete](https://user-images.githubusercontent.com/26858233/33220580-b2c4ca14-d149-11e7-8024-af962237c9f5.png)

Regarding the _Delete_ icon, it is shown only when the cursor is on the comment element. As the _Cancel_ button is a child of the comment element but is visually outside it that causes the _Delete_ icon to appear when hovering on the _Cancel_ button and disappear when moving the cursor to the sides of that button, which is a bit strange.

Besides that, the _Delete_ icon is aligned to the top and right border of the comment element, and it has no padding nor margin. When the cursor enters the comment element on the top right the _Delete_ icon appears immediately under the cursor, which also feels strange; it would be better if it had some margin so the icon appeared slightly before the cursor was on top of it.

Also, I have not tested it, but I guess that showing the _Delete_ icon only when the cursor is on the comment could be problematic on touch screens. Similarly, the area to interact with the icon should be increased on touch screens, as 16x16 is not very usable in that case.

@nextcloud/designers

**Comment by jancborchardt** [comment]
When editing, can add a bit more vertical whitespace so the button has space?

**Comment by MorrisJobke** [comment]
@nextcloud/designers Another polishing issue for the fixing phase of the 13 release.

**Comment by Abijeet** [comment]
Hey @skjnldsv - Mind if I take a crack at this? Summarizing the issue, there are three things that need to be done here,

1. Cancel button overflowing.
2. Add some margin and padding to the Delete button
3. Show the delete button at all times to avoid usability issues with touch screens.

**Comment by skjnldsv** [comment]
@abijeet of course, go ahead! 😊

**Comment by Abijeet** [comment]
Just checkted this issue out on the File > Details section and I'm unable to reproduce 1 and 2 (from above),

![screenshot-localhost-2018-01-07-22-09-44-405](https://user-images.githubusercontent.com/1685517/34651555-b3a715f6-f3f7-11e7-9c93-ae91b5213ddf.png)

@danxuliu - Am I checking in the correct location? I checked on Firefox and Chrome.

I'm able to reproduce 3.

In addition, I also found that if I click on edit and without editing the comment I press the arrow icon, the edit section turns gray but doesn't show any message. After thinking for a while I understood that this is happening because I did not make a change to the comment text. Find screenshot below,

![screenshot-localhost-2018-01-07-22-15-03-698](https://user-images.githubusercontent.com/1685517/34651601-65dda8a2-f3f8-11e7-99ae-947e4cee2b89.png)

Seems a little awkward. I suggest that we simply go back to displaying it as is, rather than the gray color.

**Comment by danxuliu** [comment]
@Abijeet 
>  Am I checking in the correct location?

Yes, you are :-) You can not reproduce 1 because it was fixed (unexpectedly, I must admit :-P ) by #7316.

Regarding 2 (the padding and margin), however, from what I can see it is still too small (26x26px, while it should be at least 44x44px).

The additional issue you found seems to be a regression introduced in #7266; it should indeed go back to an editable state (or maybe it would be even better if it just exited the edit mode like done if the text is modified).

**Comment by Abijeet** [comment]
@danxuliu - I spent some more time on this and I notice that there are a few more issues here - 

1. Edit icon and the submit icon are also not of the required size. As you mentioned all of these need to be made 44x44px.
2. While editing a div is being put inside the `ul` which is not a valid HTML structure at all.
3. While editing the cancel button is floated to the right, and hence the height of the comment div does not stretch to fit the element. We've kludge fixed this by adding `margin-bottom: 30px;`. Check image below.
4. The Edit icon is also visible only when we hover on top of the comment div, causing a similar issue as the delete icon with touch devices.

![comment-issue](https://user-images.githubusercontent.com/1685517/34688443-272a5250-f4d8-11e7-87c3-7ebf3ce84aba.png)

Would you mind if I spend a bit of time redesigning the comment system to be something like this? 

![disqus](https://user-images.githubusercontent.com/1685517/34687882-21efba8e-f4d6-11e7-8e1a-00323a114367.png)

- Instead of **Reply** and **Share** we would have **Edit** and **Delete**.
- Notice that the avatar is bigger. We would do the same. Current avatar's are maybe a little too small.
- Clicking on the edit would bring about the edit window the same way as it does, but the edit and cancel buttons would be below the contenteditable div.

OR I could simply fix the delete button issue and the regression. :)

**Comment by jancborchardt** [comment]
@Abijeet I would prefer a simple fix rather than a rebuild. :) The UI you show is just another way to do it, and not necessarily how we design it in Nextcloud.
For example, the Delete action would be much too present - it's fine to have it only in edit mode. And the avatar is also fine imo?

Maybe it makes more sense to put the cancel button above, in the same line as the avatar / delete button for uniformity.

**Comment by Abijeet** [comment]
@jancborchardt - I can fix the initially reported issues that are,

1. Increase the size of the delete button to take up 44x44px.
2. Show the delete button at all times to avoid usability issues with touch screens.

Should I skip the issues below?

1. Edit icon is also shown only on hover, which will cause usability issues.
2. Edit icon is also 26x26px currently, should be 44x44px.
3. Submit icon is also not of the recommended 44x44px.
4. Technical but, on the editing of a comment, we are adding a div inside a ul which is semantically incorrect.

The reason I gave the UI in the image as an example is,

1. Larger avatars. I do feel that the avatars in Nextcloud are a tad small.
2. Lesser gap between comments

**Comment by jancborchardt** [comment]
@Abijeet the additional 4 issues you mention are also good to fix. :)

The avatar size is standardized and the whitespace intentional. We could talk about changing that, but it's separate from this. Let's keep concerns isolated and not pile on too much at a time. :)

**Comment by MorrisJobke** [comment]
I would say it's fine to move this to 14 and maybe backport to stable13 afterwards. No need to block the release for this papercut.

**Comment by Abijeet** [comment]
@jancborchardt - Fair enough. I'll work on a total of 6 issues mentioned.

I like how you guys put smiley's after you disagree with something an outside contributor said. :)

**Comment by jancborchardt** [comment]
> I like how you guys put smiley's after you disagree with something an outside contributor said. :)

:D haha! Yeah, since online communication doesn’t carry mimic and emotions, it’s important to add that to be friendly. ;)
