### ISSUE TITLE
Update to 12.0.4 RC3 fails on web

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7331]
The web based updater does not get triggered when pressing the button. I'm pretty sure it worked fine in RC1. I also tried to revert #7257 but it didn't changed anything.

![bildschirmfoto 2017-11-28 um 20 38 21](https://user-images.githubusercontent.com/245432/33341199-82822936-d47e-11e7-8f8a-b1039f4f7759.png)

I reproduced this on two instances.

Ideas @blizzz @nickvergessen @rullzer @ChristophWurst @skjnldsv ?

RC3 can be found at: https://download.nextcloud.com/server/prereleases/nextcloud-12.0.4RC3.zip

**Comment by blizzz** [comment]
is there more in the console log? network log?

**Comment by blizzz** [comment]
console output looks a bit similar to what is reported in https://github.com/nextcloud/server/issues/7145

**Comment by blizzz** [comment]
also it appears that getting merge-template-prepend.js was aborted, but from the browser?

**Comment by danxuliu** [comment]
I can not reproduce it :-( I have used the following steps:

  1. Install Nextcloud 12.0.3 with SQLite using the official Docker container
```
docker run --detach --publish 8000:80 --name test-update-12.0.4 nextcloud:12.0.3
docker exec -it --user www-data test-update-12.0.4 bash -c "php occ maintenance:install --admin-pass=admin"

```
  2. Open http://127.0.0.1:8000 in a browser and login as _admin:admin_
  3. Perform a manual update to Nextcloud 12.0.4RC3 (delete everything except for _.htaccess_, _.user.ini_, _custom_apps_, _config_ and _data_ from the Nextcloud directory and copy the contents of Nextcloud 12.0.4RC3 there)
```
docker exec -it --user www-data test-update-12.0.4 bash -c "rm -r 3rdparty AUTHORS apps console.php core cron.php db_structure.xml index.html index.php l10n lib occ ocs ocs-provider public.php remote.php resources robots.txt settings status.php themes version.php"
docker exec -it --user www-data test-update-12.0.4 bash -c "curl https://download.nextcloud.com/server/prereleases/nextcloud-12.0.4RC3.tar.bz2 > /tmp/nextcloud-12.0.4RC3.tar.bz2"
docker exec -it --user www-data test-update-12.0.4 bash -c "cd /tmp && tar xjf nextcloud-12.0.4RC3.tar.bz2"
docker exec -it --user www-data test-update-12.0.4 bash -c "cp -r /tmp/nextcloud/* /var/www/html/"
```
  4. Reload the page in the browser; the updater appears and clicking on _Start update_ works as expected

>  also it appears that getting merge-template-prepend.js was aborted, but from the browser?

As far as I know _OC_ and _OCA_ "namespaces" are defined in _merged-template-prepend.js_, so if that file failed to load the other errors are expected. Moreover, the click handler for the _Start update_ button is set in [core/js/update.js](https://github.com/nextcloud/server/blob/v12.0.4RC3/core/js/update.js#L156), so if _OC_ is not defined the execution of the file would fail when defining _OC.Update_, due to which the _$(document).ready_ handler would not be set, and thus clicking on the button would do nothing.

What I have no idea is why _merged-template-prepend.js_ failed to load :-S The _net::ERR_ABORTED_ indeed seems to point to something in the browser.

I tried to configure Apache to send just _merged-template-prepend.js_ really slow to check if it could be caused by clicking on the button before the script was loaded. However, after struggling with that for too long I gave up and assumed that I am too dumb to get Apache to behave like that :-P

Anyway, if I am not mistaken, even if _merged-template-prepend.js_ took very long to load it would not be possible to click on the button before it finished, as the scripts are loaded synchronously and [they block the rendering of the DOM until they are processed](https://developers.google.com/speed/docs/insights/BlockingJS#overview). So... I am clueless, sorry :-(

**Comment by MorrisJobke** [comment]
> What I have no idea is why merged-template-prepend.js failed to load :-S The net::ERR_ABORTED indeed seems to point to something in the browser.

I used Chrome and Safari and also two different instances :/ 



> Anyway, if I am not mistaken, even if merged-template-prepend.js took very long to load it would not be possible to click on the button before it finished, as the scripts are loaded synchronously and they block the rendering of the DOM until they are processed. So... I am clueless, sorry :-(

I still think, that we should not load the generated stuff on the update page and have only a very limited set of JS code available there to not mess with it (maybe served from inline script tags - we do the same for the web based updater to not cause too much trouble if a file gets not loaded and lock yourself out).

**Comment by MorrisJobke** [comment]
I also tried to reproduce this again and the issue didn't happen afterwards anymore :/ I tried to reupgrade both instances, but then all went fine and the upgrade was possible.

Closing this as a false flag and some network hiccup. 😢

**Comment by MorrisJobke** [comment]
While debugging through this I cleaned up a bit the upgrade check handling: #7354
