### ISSUE TITLE
Update Server ubuntu 17.04 -> 17.10, no external smb share is working

### ISSUE THREAD

**Issue by m4ntic0r** [nextcloud/server#7359]
so today i updated multiple servers from 17.04 to 17.10 and only my nextcloud server is making trouble..
its a vm and i tried the upgrade 3 times, but always all my external smb shares are not working.
i only use smb shares on my nextcloud server.

ubuntu 17.04 with nextcloud 12.0.3 install, mysql database is on a separate server.

after "do-release-upgrade" i tried everything i know.. reinstalled necessary php packages (there was a update from 7.0 to 7.1) and compared all loaded modules with **php -m**

php-smbclient is installed, too.

everything is working, i can login and work with nextcloud but i cannot mount my smb shares.

i tried my old kernel from 17.04 but no success :/

i changed log level in /config/config.php to 0 and the only thing i see is:
https://mm-vault.de/chevereto/image/7xkd

can somebody help me or give any tips?

atm i am running my 17.04 vm again without issues.

**Comment by jgrete** [comment]
Sorry, no help for you... Just want to state that I see the same behaviour and currently investigating. Today in the (very early) morning I've cloned the vm carrying Nextcloud 12.0.3 and installed Nextcloud 13 beta1. Surprisingly it works much better. Now I can mount external storage via smb/cifs what diddn't work with 12.0.3. Some strange things remaining though. Because it was very early I did not investigate any further but will do this weekend (my OS: OpenSUSE 42.3).
Regards
Jürgen

**Comment by MorrisJobke** [comment]
> i changed log level in /config/config.php to 0 and the only thing i see is:

This means that there is a problem with the SMB mount. Could you try with an SMB cli tool to connect from the Nextcloud vm to that mount (to check if the underlying server/client works). If this also doesn't work it is a setup issue with the SMB server or mount.

**Comment by m4ntic0r** [comment]
because of an other error on an other server i migrated all my ubuntu servers to debian 9 and i dont have any issues atm.
