### ISSUE TITLE
Re-think position of "Add to favorites"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7379]
<img width="233" alt="bildschirmfoto 2017-12-03 um 17 13 51" src="https://user-images.githubusercontent.com/19711361/33527235-68c093a2-d84d-11e7-8b87-1772d11b395e.png">

Call me conservative, but I still look back to the good old times where the first point in this list was "Details" and the last point "Delete" ... what happens in the middle is irrelevant but I am experiencing it now since days that I am trying to open the "Details" menu and instead I am favorite a file :(((

What do you think?

**Comment by pixelipo** [comment]
Allow me to go look this from a little bit wider perspective.

I think many are aware of the problem of sidebar not being very easy to discover/access. There is talk of having it "always visible" on FHD. In my opinion, that doesn't solve the problem.

I would propose that the sidebar ("Details") are shown when single-clicking on an item, and move the current single-click (open folder or view item) to a double-click action.

It solves both this and the "invisible sidebar" problem. It also seems quite natural/obvious. It would also allow for an easy multiple select. Google Drive works in a similar manner.

@nextcloud/designers am I talking stupid?

**Comment by jancborchardt** [comment]
> I would propose that the sidebar ("Details") are shown when single-clicking on an item, and move the current single-click (open folder or view item) to a double-click action.

Sorry but this interferes with both the main flow, and with what people are used from web apps. Double-click is relegated from the primary action (opening) to secondary action (zoom in picture or maps apps, or liking on Instagram – and that only on touch devices). Single click always needs to be opening the folder or file, as it also is for navigation elements.

Double click we should not use at all except for enhancements or shortcuts as it is not commonly used in web apps at all.

Really this might just be a problem of labeling, because the share icon actually opens the sidebar with all info. Maybe until the icon is shared, we should use the `icon-info` icon, which also opens the sidebar, in the sharing tab.
Another important point is to finally **combine file Activity, Comments and Versions into unified »Activity« timeline tab** so the sidebar itself is less cluttered – see #658. And of course showing the sidebar by default on big screens will be a big step in the right direction.

The core of the problem @MariusBluem mentions is simply the need to get used to an interface change which we did to fix a bunch of problems (multiselect not being obvious, filetype icon click not opening the file but selecting, etc). It doesn’t warrant a complete change which breaks the overall flow. :)

**Comment by MorrisJobke** [comment]
Makes sense. I would close this here for now and have a look once the two issues that @jancborchardt mentioned are fixed. 👍
