### ISSUE TITLE
Favicon in theme not used

### ISSUE THREAD

**Issue by frisi** [nextcloud/server#7422]
currently it is not possible to replace the favicon in a custom theme just by putting it into
themes/mytheme/core/img/favicon.ico

### Steps to reproduce
1. activate example theme in config.php
2. open nextcloud webinterface in a browser
3. show page source

### Expected behaviour

favicon should be fetched from the activated theme:

```html
<link rel="icon" href="/themes/example/core/img/favicon.ico">
```

### Actual behaviour

the default nextcloud favicon is fetched
```html
<link rel="icon" href="/core/img/favicon.ico">
```

### Server configuration

**Operating system**:
debian stretch

**Web server:**
apache 2.4.25

**Database:**
mysql 10.1

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.37
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - theming
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "519dc4226a5d2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maintenance": false,
        "theme": "example",
        "trusted_domains": [
            "cloud.foo.com"
        ],
        "trashbin_retention_obligation": "auto, 14",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "htaccess.RewriteBase": "\/",
        "skeletondirectory": "",
        "overwrite.cli.url": "https:\/\/cloud.foo.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "foo.com"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by frisi** [comment]
also reported by @io-node in https://github.com/nextcloud/server/issues/5036#issuecomment-303351282

**Comment by frisi** [comment]
@Gomez any idea what's the problem here?

when i enable the theming app, the favicon is taken from the default theme
```html
<link rel="icon" href="/core/img/favicon.ico">
```
instead of /apps/theming (https://github.com/nextcloud/server/issues/5036#issuecomment-303357444)
```html
<link rel="icon" href="/index.php/apps/theming/favicon/files?v=15">
```

**Comment by frisi** [comment]
updated from 12.0.3 to 12.0.4 today and still the wrong favicon is used.
hint: when sharing a file/folder via link and accessing this link, the favicon of the theme is used.

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by tessus** [comment]
@MorrisJobke I hope it is ok to add a comment here. it is not my intention to hijack this thread. please let me know, if I shall open a new issue. I also did not find a repo for the admin/theming page, so I guess it is a server issue.

I've noticed that I cannot change or add my own favicon in `settings/admin/theming`.

It's possible to upload a custom image and logo, change the base color, but there's no way to upload a favicon. Is this intentional or was it just forgotten? Is this something, you want in there?
If yes, maybe I can try changing the theming code and add it.

**Comment by tessus** [comment]
@MorrisJobke Thank you very much for the info.

**Comment by MorrisJobke** [comment]
Added to theming app: #8540

**Comment by truewt** [comment]
Sorry to reply to closed issue, but to me it's not clear how it will be addressed. If I understand correctly the fix for favicon in custom themes (not theming app) is coming in Nextcloud 14?

Just to describe why I'm asking this... I think that after version 13 there was always NC favicon from app's core used and not the one from custom theme. For me this is still the case after upgrade to 13.0.4, but it worked in all previous major versions I've used (from 10 on). However, it's not such an issue, but it would be nice to have this resolved if it already worked once. Anyway, thanks for doing such a great work with NC and keep rocking ;)

**Comment by juliushaertl** [comment]
> Sorry to reply to closed issue, but to me it's not clear how it will be addressed. If I understand correctly the fix for favicon in custom themes (not theming app) is coming in Nextcloud 14?

We've added the favicon as an option to the theming app to make it easier to theme this one as well. The theming app should be the preferred way to adjust the look of your Nextcloud.

> Just to describe why I'm asking this... I think that after version 13 there was always NC favicon from app's core used and not the one from custom theme. For me this is still the case after upgrade to 13.0.4, but it worked in all previous major versions I've used (from 10 on). However, it's not such an issue, but it would be nice to have this resolved if it already worked once. Anyway, thanks for doing such a great work with NC and keep rocking ;)

Please check if you have disabled the theming app in that case for 13. If there is still a problem, please open a new issue.

**Comment by deusoz** [comment]
@juliushaertl   
I just discovered your Custom CSS app.  It seems that last year then, you were advising to use theming app over using custom themes folder.   Does this still apply?  in conjunction with your Custom CSS app?  Would that be the preferred way to change a theme?

**Comment by MorrisJobke** [comment]
> I just discovered your Custom CSS app. It seems that last year then, you were advising to use theming app over using custom themes folder. Does this still apply? in conjunction with your Custom CSS app? Would that be the preferred way to change a theme?

At least it's the one that's easier to maintain from your side.

**Comment by deusoz** [comment]
Thank you for replying.  Can you explain why that is?  I'm thinking that maintaining a theme folder as a git submodule seems fairly simple.  However, my main question is this... IS the Custom CSS app able to affect more of the core css than using a Theme folder?  

For instance, I want to specify different colors for default "folder" icon, another for "external folders" and a different background color when hovering over menu items, etc.  The "Theming App" gives one "color" which will change all of those items to elected color.  But what if I want a different color for the default folder icons than the external folder icons?  What about the default color for an .ods filetype or other filetype icon colors?

I tried adding a "filetypes" folder to my custom Themes folder and hoped the app would use those images instead of supplied core images (similar to way a WordPress Child theme works) but only way I could affect individual filetype icon colors was to directly change the core img svgs.  Is there any way to specify the colors inside the svg files for the different file and folder types without hacking the core?

Thank you for your time

**Comment by deusoz** [comment]
Another consideration is custom images. With Custom CSS,  I just tried it out, but to get to my logo in theme folder, background-image: url('../../../../../themes/db5dcc/core/img/tile_head1.png');
Does Custom CSS app have a preferred folder to find custom images?

**Comment by deusoz** [comment]
I figured out how to change the file/folder icon colors without editing core.  Add "filetypes" directory here:   /themes/mytheme/core/img/filetypes/

Place any revised svg icons with changed "fill" values in that folder. Then run this command:

`occ maintenance:mimetype:update-js`   

Which updates the core/js/mimetypes.js file and my revised icons are now being read from my theme folder.  Brilliant!  

So, as to my original question, maybe using Custom Css and Theming App is easier, but it seems (unless I'm missing something there) that using the custom themes folders is way more powerful as I don't see that Custom CSS / Theming App can change colors of filetype icons, whereas theme folder can.

**Comment by tessus** [comment]
Yea, it would be great to know, if one can use the theming app in combination with one's own theme folder, or if these two approaches are mutually exclusive.
In case of the latter, maybe there's away to point to one's own theme in the theming app thus allowing the use of both.
