### ISSUE TITLE
Option to Dissallow Group Admins changing Quota

### ISSUE THREAD

**Issue by ajeoc** [nextcloud/server#7429]
Please add the ability of the Admin to decide disallow Group Admins changing the Quota.

e.g. Add a line with checkbox under Settings: <checkbox> Group Admins can change Quota value
Group Admins see the Quota drop-down menu greyed out.

Only the Admin and Users in his group should be able to set quotas, which can't be changed by Group Admins.

**Comment by skjnldsv** [comment]
Fixed by #8824

**Comment by ElpyDE** [comment]
I was really looking forward to see this issue addressed in Nextcloud 14. Unfortunately, I still see this as not fixed - at least in the way I understand it:

If I understand this issue correctly, the permission of group admins to change ANY user quota should be optional.

The linked duplicate #9191 is different in so far as it only disallows a group admin to change his/her OWN quota. That issue was indeed fixed by the updated users page.

Just for clarification, I want to add a use case: We want to set up a Nextloud for a Youth organization with several local groups (calling them "sections" here to differentiate from Nextcloud's groups). The sections will all get their own group and someone from each section will get the group admin priviledge. These group admins should be able to create new users in their group. However, no user should get a quota above the default quota - unless one of the (server) admins approves.

Any help on how that could be achieved would be appreciated - even solutions with a dedicated custom App that changes the users settings page.

@skjnldsv or @MorrisJobke could one of you comment on this, please?

**Comment by ajeoc** [comment]
Yes, at least optionally, the Admin should be able to disallow Group-Admins changing quotas from ANY user.
In NC14 the Group-Admin can still set for Users in his Group the Quota to UNLIMITED.
The Admin (which is also responsible for the Storage Availability on the Server) can in this case not prevent that the Storage limit is hit.
This way the Server-Admin cannot control Storage-Resources-Assignment to different groups.
This way a User which got from the Group-Admin the quota UNLIMITED can easily fill up the server!

**Comment by team-a2** [comment]
It would be very useful to have the feature of preventing group admins from changing quotas (for themselves AND users).

Can You please implement this?

Thanks in advance!
