### ISSUE TITLE
Feature-Request: Linking "Objects" together

### ISSUE THREAD

**Issue by frogueat** [nextcloud/server#7435]
### Steps to reproduce
1. Edit some object and reference an other ...

### Expected behaviour
It would be great to have the posibility to link Objects together. E.g. to reference in a calendar-item a file, a user, a note, a task or something else. Therefor a **notation** would be necessary - like in confluence or here on github ... Something like @[instanceuri->]class:name. E.g. referencing a file in a calendar-item would be @file:/documents/mydocs/myfile.txt. In an md-File referencing a calendar item cold be @calendar:20171209/mytitle and so on ...

It could be than a clickable link on the link and pretty embedding (thinking on youtube-links in fac_bo_k) of the object would be possible ...

Sure, that's not simpel - but wouldn't it be great ;-)

**Comment by Spartachetto** [comment]
I think this is related to **Link tags to other objects** #4850.

Actually Nextcloud could have both the possibility of linking tags to other objects (as defined in #4850) and linking objects together (as define here)

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by karlitschek** [comment]
I agree that this would be a great feature. Especially for collaboration. The challenge is probably the right user interface for this

**Comment by Spartachetto** [comment]
the proposal of @frogueat would allow an extension of the _contacts popover_ concept....

if I have "@Calendar:20171209/mytitle" in a comment, show a popover with some info on the calendar item; then, if I click on the popover, show me the calendar item. The same is true for "@file:xxx" or "@task:xxx" or ...
It could be elegant from an user interface point of view, even if not technically easy to realize

**Comment by frogueat** [comment]
I am happy to see, this idea finds some interest! To push it further i'd like to make you familiar with the concept of backlinks (I know this frpm a different dms/ecms/wf/cloud-product). Logically this is simple: linking an object implicates that the linked object (the target) sees the object fomulating the link (the source). This helps users much in exploring the "network" and generates very useful information.

**Example**: 2 Calendar items (i_tem1, item2_) links a _file_. At the _file_ in the backlinks you see 2 links: one to _item1_, one to _item2_.

The challenge here is the removing the backlinks too, if the link is removed.

**Example**: The aboce calendar _item1_ removes the link to the file. At the _file_ in the backlinks you see only the link of calendar item2.

**Comment by sehucke** [comment]
As I wrote in #11015 (maybe it fits better in here): I think the key challenge - beside the UI - is to have an extensible concept so that other apps could add their own "things" the users can reference from other apps. E.g. if I would write a recipes app I would "instantly" be able to reference a recipe in a calendar appointment and vice versa (e.g. `@recipe:steak-with-fries`). Maybe something like a publish/subscribe service for object referencing:
1. The app `A` subscribes to the "linking service" (let's call it `Linker`), telling the service
    1. a unique keyword,
    1. the URL to resolve a "linked object" and
    1. an API endpoint for loading autocompletion entries.
2. The user types `@<keyword>:` in app `B`. This triggers an API call to `Linker`'s auto completion endpoint (as soon as the user types the first character after `:`). That endpoint would then call the corresponding endpoint registered by app `A` to load the autocompletion entries and to return them to app `B`.
3. And finally, app `B`'s UI could trigger API calls to `Linker`'s endpoint for adding hyperlinks to referenced objects.

That would be the general flow for a basic version. I could think of some more neat features - like registering templates for popovers or adding additional columns for the autocomplete / search function (e.g., when you want to reference the recipe "Steak with Fries" but you type something that is only mentioned in an additional description field).

Opinions? Suggestions?

**Comment by nickisashkir** [comment]
Linking Documents / Related documents is a powerful form of NLP document management. This is one of the fastest growing fields and NextCloud's competitor's all support it right now. SpringCM is probably the furthest along. 

The ideal thing is while "tags" are great. But, tags aren't easily accessible. You can't see them in the sidebar. To link objects together, tags are a great direction. But, part of it is similar to how SpringCM does it via Additional Fields/Attributes.

These Attributes let me link a Sub-Contract to a Contract. So in the sidebar I can click on the "parent contract" or see other sections.

**Comment by skjnldsv** [comment]
@jancborchardt it is interesting.
We did not really took a stance on this, any thoughts?
