### ISSUE TITLE
Allow customized checks on bootstrap

### ISSUE THREAD

**Issue by fgsl** [nextcloud/server#7491]
This change allows that system administrator can add running constraints to a specific Nextcloud installation. It can help to meet different customer requirements.

### Steps to reproduce
1. Create a PHP file starting with 'check_';
2. Write constraints code (essencially a if structure with an exit command);
3. Add that file to folder lib.

### Expected behaviour
If condition in added file is satisfied, application doesn't start but shows programmed message to user.

### Actual behaviour
Only constraints in file check.php are verified.

**Comment by MorrisJobke** [comment]
cc @karlitschek @rullzer @blizzz Does that make sense?

@fgsl Do you have more examples for us?

**Comment by karlitschek** [comment]
Sorry. I don't fully understand the usecase

**Comment by fgsl** [comment]
Hi, @MorrisJobke and @karlitschek.

Most of all our customers have legacy user environments and they can't update them because some applications are incompatible with new software versions.

Think about a customer with more than five thousands of workstations running Internet Explorer 10 or lower as standard browser because some web applications depends on it. For this customer we can show a message when users try access Nextcloud, warning that they have to open Chrome (the other allowed browser in their environment).

I believe that this change can attend similar use cases.

**Comment by MorrisJobke** [comment]
> Think about a customer with more than five thousands of workstations running Internet Explorer 10 or lower as standard browser because some web applications depends on it. For this customer we can show a message when users try access Nextcloud, warning that they have to open Chrome (the other allowed browser in their environment).

Then we should not use this kind of dirty hack, but show a proper page with a nice explanation and not a white page with black text.

That check in there is for hard system dependencies that can only be worked around with an error message if the system has not fully started, because that would already crash. Reusing this for other user related issues is kind of bad and makes only the code harder to maintain.

> I believe that this change can attend similar use cases.

Do you have another example?

**Comment by fgsl** [comment]
@MorrisJobke , this is a feature of customization. This change alone doesn't show a new page. Each sysadmin is responsible to create a proper page. Current check page (lib/versioncheck.php) is a white page with black text, but I didn't think about change it, only to allow additional checks. As it is implemented in this pull request is possible to show friendly pages, but only for additional checks.

I believe that similar cases can happen when a customer requires that Nextcloud runs under hard system dependencies of other applications. 

But I understand your worries. They are related to code quality and maintenance of application. Completely right. For the case of my additional comments are not enough, do you have some guideline for scenario that I described? I don't want to create a fork of Nextcloud in production. 

Thanks!

**Comment by fgsl** [comment]
I fixed branch of this pull request. It had other commits not related to proposed change.

**Comment by rullzer** [comment]
Allow me to provide some context of the versioncheck. (Because I added it). The version check is actually needed to be done in such a crude way. Because if you have the wrong php version you will get a 500 error otherwise.

All other bootstrap checks should be done in a proper way IMO.

**Comment by MorrisJobke** [comment]
> I don't want to create a fork of Nextcloud in production.

Develop an app and use that to do the checks. Apps can basically inject a lot of stuff to the whole system and do stuff like this. having yet another mechanism to add extensions to is the wrong way in my opinion.

TOTP app hooks for example in the authentication: https://github.com/nextcloud/twofactor_totp
First run wizard for example in every app on the first login: https://github.com/nextcloud/firstrunwizard

So there are basically a lot off ways to handle stuff and no need to do this in some weird PHP files that are placed right into the server code. Also the integrity check would fail then, because we don#t allow custom code except in apps.

**Comment by fgsl** [comment]
Great, @rullzer and @MorrisJobke.  These guidelines are alternatives that I needed. 
I will create an app.
So I close this issue.

Thanks!

**Comment by MorrisJobke** [comment]
Nice 👍
