### ISSUE TITLE
Feature Request: TOTP sharing of files and folders

### ISSUE THREAD

**Issue by apus2016** [nextcloud/server#7494]
I'd like to see the following feature in Nextcloud.

Assuming one has to access private files in a public place, for example in a session of a program via Import(...), then it would be practical to have access to those files via a Time-based One-time Password (TOTP). That way, as soon as the session is over and the imported/included file and its content is removed from memory, the Import statement can't be used anymore and the content of the imported file remains private. Ideally this could be done on a per-folder basis (not a different key on a per-file basis, that would be impractical), just like the sharing is done now with a static password.

From my point of view this would be awesome when you aren't working on your private system and want to import your own functionality without downloading and placing that file on the public system.

Perhaps someone has good ideas how to implement this. It would be practical to have access to those files via a url that has the filename in it and as few as possible random characters, so it is easier to remember and type. Alternatively we could put a short url per file in the ios and android app, so one can look the url up.

At least in my use case the TOTP password would need to be entered via GET in the url, i.e. ?totp= .

**Comment by MorrisJobke** [comment]
> At least in my use case the TOTP password would need to be entered via GET in the url, i.e. ?totp= .

The OTP needs to be configured as a second factor and can't be used alone. It would make sense to include this into a different sharing mechanism like #740 but without this it does not make sense, because the initial token (to setup the OTP) needs to be distributed/set up first, which needs to be done behind an additional security mechanism - otherwise it would not make sense.

I would see this as an additional provider of #740 and thus close this one here as duplicate.
