### ISSUE TITLE
Limit sharing functionality usage to per user or group

### ISSUE THREAD

**Issue by realies** [nextcloud/server#7618]
Would be great if the ability to share files has more granular per user or group functionality instead of being a global option for all.

**Comment by MorrisJobke** [comment]
cc @karlitschek @nextcloud/sharing for the general idea of making it more granular.

I would try to avoid this, because it adds a huge amount of complexity for very little advantages.

**Comment by rullzer** [comment]
You run into the same issues we face every time. How to make a solution everybody is happy with. Limiting per group it not the issue. Well there is the UX issue but I'm sure we can come up with something.

But what happens when a user is part of multiple groups? Is it the min of the two? The max? Does it add up?

**Comment by realies** [comment]
Thanks for the comments. I would expect the behaviour to be the same as it is for group limitation available to apps.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
