### ISSUE TITLE
Issues while migrating from Owncloud 10.0.4 to Nextcloud 12.0.4

### ISSUE THREAD

**Issue by rinchen** [nextcloud/server#7655]
Hi,

I migrated off of OC 10.0.4 today to NC 12.0.4. I ran into some resolvable issues and wanted to document them for the dev team (and anyone else who runs into these issues).

Issues:
1) The automated migration script immediately decided it didn't know about my owncloud instance nor the latest version of nextcloud (I closed the tab before I memorized what it said but I suspect it triggered on "currentVersion = 'unknown'").

2) I abandoned the script in disappointment and moved to the manual upgrade. The wiki page (https://docs.nextcloud.com/server/12/admin_manual/maintenance/migrating_owncloud.html) is out of date as it doesn't indicate support for my migration path but a blog post did (https://nextcloud.com/blog/nextcloud-12.0.4-is-here-time-to-upgrade/).

3) The upgrade directions (https://docs.nextcloud.com/server/12/admin_manual/maintenance/manual_upgrade.html) fail to tell you to change maintenence = true; or similar.  I had backed up my config.php, in which maintenance was false;, and when the server restarted it had issues. I turned off apache2, edited the config.php file, and restarted apache.  The good news, occ upgrade worked great!

4) Because I was migrating from OC with Lets Encrypt to NC, my /etc/apache2/sites-enabled/default-ssl.conf was broken.  After fiddling with certbot and this config file for some time, the magic sauce was to modify the file and replace the existing SSL certs with the apache2 defaults:
`            SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
            SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
`
After that was done, certbot worked correctly.

5) Next up was seeing a webpage with only 

> nextcloud/core/templates/403.php

I remembered getting this with owncloud a while back. The solution was to edit .htaccess and remove everything after
> #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

What's odd about this is, the .htaccess file was the one distributed with NC 12.0.4. I followed the upgrade instructions precisely and moved my old OC install to a different directory and just renamed the NC directory to be the one I was using.

6) Finally, during client sync I had several thousand files which were erroring out with checksum issues. It seems that whatever was in mysql (put there by OC) was not correct.  The solution to fix this was to manually reset them:
`UPDATE oc_filecache
SET checksum = ''
WHERE COALESCE (checksum, '') <> ''
`

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache2

**Database:**
mysql

**PHP version:**
7.0.22

**Nextcloud version:**
12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Migrated from OC 10.0.4

**Where did you install Nextcloud from:**
nextcloud.com download

**Comment by MorrisJobke** [comment]
cc @jospoortvliet @nickvergessen @rullzer

**Comment by rinchen** [comment]
Another item: In the migration documentation there is no entry which speaks to migrating the user-base desktop clients. In testing we discovered we could simply keep the desktop files in-situ and just point the sync client location to it.  However, for caution (and avoidance of any potential sync conflicts), I had everyone use a different local directory and sync down the all the server files.

**Comment by tflidd** [comment]
Thanks for the feedback. In the meantime, the migration information on the web site was updated (https://github.com/nextcloud/nextcloud.com/pull/728). 

> The automated migration script immediately decided it didn't know about my owncloud instance nor the latest version of nextcloud (I closed the tab before I memorized what it said but I suspect it triggered on "currentVersion = 'unknown'").

This was probably fixed in the mean time. There are several report that it works right now.




> I abandoned the script in disappointment and moved to the manual upgrade. The wiki page (https://docs.nextcloud.com/server/12/admin_manual/maintenance/migrating_owncloud.html) is out of date as it doesn't indicate support for my migration path but a blog post did (https://nextcloud.com/blog/nextcloud-12.0.4-is-here-time-to-upgrade/).

Put a bug report on https://github.com/nextcloud/documentation/issues, we probably don't need a duplicate of the migration page on the homepage.



> The upgrade directions (https://docs.nextcloud.com/server/12/admin_manual/maintenance/manual_upgrade.html) fail to tell you to change maintenence = true; or similar. I had backed up my config.php, in which maintenance was false;, and when the server restarted it had issues. I turned off apache2, edited the config.php file, and restarted apache. The good news, occ upgrade worked great!

It says to stop the webserver. This is even better because folders are renamed and content is copied. During these procedures, users could see a setup page, access not allowed, ...



> Because I was migrating from OC with Lets Encrypt to NC, my /etc/apache2/sites-enabled/default-ssl.conf was broken. After fiddling with certbot and this config file for some time, the magic sauce was to modify the file and replace the existing SSL certs with the apache2 defaults:
> SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
> After that was done, certbot worked correctly.

Regarding certificate, I don't know if there is an official recommendation because people can use different cert authorities. So it is nice to share this information but I wouldn't know where to put it in the documentation. Ideas?



> Next up was seeing a webpage with only
> 
>     nextcloud/core/templates/403.php
> 
> I remembered getting this with owncloud a while back. The solution was to edit .htaccess and remove everything after
> 
>     DO NOT CHANGE ANYTHING ABOVE THIS LINE
> 
> What's odd about this is, the .htaccess file was the one distributed with NC 12.0.4. I followed the upgrade instructions precisely and moved my old OC install to a different directory and just renamed the NC directory to be the one I was using.

Yes, this shouldn't happen. What did you put there as additional lines? Sometimes the configuration can change a bit that some old settings might not be a good choice any more, so you should review such manual additions. Between minor version in NC, there shouldn't be a problem, for migration from OC to NC or major upgrades within NC, there can be problems. Perhaps something we should put in the upgrading guide (can you open a report in the documentation bug report as well)?

> Finally, during client sync I had several thousand files which were erroring out with checksum issues. It seems that whatever was in mysql (put there by OC) was not correct. The solution to fix this was to manually reset them:
> UPDATE oc_filecache SET checksum = '' WHERE COALESCE (checksum, '') <> ''

This is actually an issue which should stay here. It's the "main" bug.



> Another item: In the migration documentation there is no entry which speaks to migrating the user-base desktop clients. In testing we discovered we could simply keep the desktop files in-situ and just point the sync client location to it. However, for caution (and avoidance of any potential sync conflicts), I had everyone use a different local directory and sync down the all the server files.

That's an excellent remark. Users can continue using their ownCloud client, however a migration should be possible. But that's also for the documentation repo.

In the future, try to separate the issues a bit. In such long topics, some remarks and ideas are easily lost.

**Comment by MorrisJobke** [comment]
As there is no report since a while I will close this ticket. If this is still happening please feel free to reopen.
