### ISSUE TITLE
GDrive is not available since NC13

### ISSUE THREAD

**Issue by krombel** [nextcloud/server#7714]
The GoogleDrive functionality got removed in #6149 and I have not found (yet) a working replacement of that functionality.
The code seems to be moved to an [owncloud-repo](https://github.com/owncloud/files_external_gdrive) but that is not compatible to NC13 (yet; tested with NC13-b4)
and furthermore not part of the app store.

I first got a popup `Some of the configured external mount points are not connected. Please click on the red row(s) for more information`
And on the share I have: `Unknown storage backend googledrive`

**Comment by MorrisJobke** [comment]
Currently we are lacking a maintainer for the google drive integration and also the API isn't that easy to use anymore, because google now requests the developer of a service to register with google or you need to ask for a self-signed exception. 

We also remove the dropbox integration and @icewind1991 build it as an app: https://github.com/icewind1991/files_external_dropbox

The same thing should be done for google drive and it should not be done within the server but as a separate app.

Sorry for the bad news and for this regression, but running unmaintained code sadly also not a useful option.

So anybody who is up to help maintaining this could look into how the dropbox app is build and do the same for google drive integration.

**Comment by krombel** [comment]
@enoch85: I used the GDrive integration to access shares of other people who preferred to not use own-/nextcloud...

**Comment by mabramux** [comment]
@encho85: I used GDrive integration in conjunction with encryption. It's a nice feature to store all data in external storage, but encrypted by nextcloud.

**Comment by enoch85** [comment]
@krombel Time to improve your sales skills then ;)

@mabramux In your case I would do `rclone  copy gdrive:/* nextcloud:/<datafolder> && rclone delete gdrive:/*`

**Comment by mabramux** [comment]
@encho85: Ok, I think you misunderstood me. I know how to migrate my data, but I don't want to do, because GDrive is a nice free storage. Of course there are other free storage provider, but how can I be sure, that other connectors will work in future. I don't understand, why NC drops support for one of the most important "free storage systems" all over the world.

Perhaps it's my fault, but I didn't noticed, that GDrive Support was deprecated in NC 12. I think admins and users should get an **early** notification before dropping features. And early should be at least one major release before dropping.

**Comment by enoch85** [comment]
@mabramux It's my personal opinion. As little Google as possible is better IMHO.

I also think Nextcloud is way better than GDrive + the feeling of security and privacy. Even if you use Nextclouds encryption I wouldn’t feel comfortable having anything at all at GDrive. 

I do agree that it's a regression though, and I also think that the situation could have been handled better even if I'm not using it myself I do understand the users that do.

**Comment by mabramux** [comment]
@enoch85: Ok, I understand your point with Google. ;-)

My main argument is the discontinuation of support. This is - sorry - not very professional, but you mentioned the suboptimal handling yourself. On the other hand ... perhaps that's really professional looking to "professional" concerns like Apple, MS ... They are doing such things with every new release. ;-)

I hope there will come a solution with [https://github.com/owncloud/core/pull/28074](https://github.com/owncloud/core/pull/28074)

**Comment by NastuzziSamy** [comment]
Hey guys !

I am working on it here: https://github.com/NastuzziSamy/files_external_gdrive
It currently only can read and access to Google Drive.
I will push into the app store when it will be fully functional ;)
