### ISSUE TITLE
The local external storage folder not always visible.

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#7927]
### Steps to reproduce
1.Install nextcloud normally
2.In settings->External storages:configured the Local external storage correctly.
3.In filelist->external storage:the folder is visible,when I click others,then I click the external storage,the folder I created is invisible.Why?Sometimes it occered.I see the nextcloud.log,nothing helped to me.

### Expected behaviour
Whenever I click the external storage,I can see the folders I created.

### Actual behaviour
when I click others,then I click the external storage,the folder I created is invisible.After fresh it visible,sometimes invisible. 

### Server configuration

**Operating system**:Ubuntu 16.04.1 LTS

**Database:**:10.0.33-MariaDB

**PHP version:**PHP 7.0.22

**Nextcloud version:** (see Nextcloud admin page):Nextcloud 14.0.0 alpha
![image](https://user-images.githubusercontent.com/34739130/35079801-a746f0c4-fc44-11e7-987d-9e4cefafdfa3.png)
![image](https://user-images.githubusercontent.com/34739130/35079810-b735f692-fc44-11e7-9548-84b4224ab1f0.png)
![image](https://user-images.githubusercontent.com/34739130/35079830-d52a63fe-fc44-11e7-892d-b6b4b3321f74.png)

**Comment by ziqingshi** [comment]
@icewind1991 @blizzz @skjnldsv thanks.

**Comment by ziqingshi** [comment]
@icewind1991 @blizzz I see the nextcloud.log,nothing helped to me....

**Comment by blizzz** [comment]
have nothing like this observed recently when i added a local mount. 

I understand there's nothing popping up in the Nextcloud log?

Can you check the network console for Ajax requests?

**Comment by ziqingshi** [comment]
@blizzz @icewind1991  I check the network console.It didn't help me.The problem is,when I refresh the page，then I click the recent or external storages,the folder or files are exist,then I click the all files,now I click the recent,the folder or files are invisible after I refresh the page it visible.
![problem](https://user-images.githubusercontent.com/34739130/35256549-539ea0d6-002f-11e8-96a0-9647318f44c1.jpg)

![1](https://user-images.githubusercontent.com/34739130/35256557-5c48321a-002f-11e8-9345-510a2cbb227a.png)

![56](https://user-images.githubusercontent.com/34739130/35256567-649d5846-002f-11e8-9fa8-ac5fdd3e5b7d.png)

![3](https://user-images.githubusercontent.com/34739130/35256575-6a660250-002f-11e8-9237-cdb7bc4aeee2.png)

![4](https://user-images.githubusercontent.com/34739130/35256580-71f0a4e4-002f-11e8-9219-fee85cf199d4.png)

**Comment by stratosmacker** [comment]
This issue is still persistent

**Comment by kocur** [comment]
still occurs

**Comment by jesse-osiecki** [comment]
Is there debugging output that I can enable? I can reproduce this reliably so I should be able to fix it
