### ISSUE TITLE
Settings> Personal> Sharing shows a blank if federated sharing is disabled

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#7965]
edit @tflidd: Show sharing point on personal page only if the sharing app is enabled.

------------------
When I go to Settings> Personal> Sharing I get a blank page.

System setup in #7831 but with RC2. Nothing in error log. Will turn up debugging if no-one can reproduce this.

**Comment by tflidd** [comment]
I can't reproduce this on Debian 8/apache/mod_php7 (dotdeb). Perhaps some old, broken shares? A bit more information would be helpful.

**Comment by rubrik** [comment]
Still in RC4. @tflidd how can I get you more information?

**Comment by tflidd** [comment]
> should I expect output to data/nextcloud.log?

Since the specific error is not known, the server error logs or php error logs (check their configuration where logs are put and which log levels are set) should be considered as well.

**Comment by jbrrrr** [comment]
Just to support rubrik - I face the same issue after upgrade from 12.0.5 to 13.0.0.14 (Migration and upgrades from Owncloud 9):

> When I go to Settings> Personal> Sharing I get a blank page.

**Comment by jbrrrr** [comment]
Thanks @tflidd - Now I get it.
Federated Cloud Sharing was not allowed. As soon as I allowed it, the page wasn't blank no more.
As you suggested - maybe not showing the 'sharing' menu under personal if federated cloud sharing is not allowed would be less confusing for the users.

**Comment by rubrik** [comment]
I enabled "Allow users on this server to send shares to other servers" now and I can see the page. An error message would be better I think.

**Comment by bobblkabb** [comment]
Word.
Shouldn't be present if federated cloud sharing is not activated. Confusing.

**Comment by Wikinaut** [comment]
I have the same problem on my nextcloud instances (empty page on endpoint ```nextcloud/index.php/settings/user/sharing``` )

**Comment by cdmlb** [comment]
Why is that tab called sharing, why not rename it to federated sharing, since that's what it says on the page when you click on it.

If you go in the admin system sharing and remove the check marks for federation sharing, the page does become blank.

I even disabled the federation sharing app, and the tab still stays active in the list with the content depending on the settings either blank white page or the actual contents to share on social medias.

I would expect disabling the app would remove the tab and its options all together, but it does not, and it's the only app that seems to have this issue.

The only error I have in any system log or nextcloud log is because I'm using php 7.3:

"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php#321
--

**Comment by Tobsche** [comment]
I have to second @cdmlb . Providing a blank "Sharing" page because federated sharing is disabled is completely confusing to admins and users. 
Please rebrand the user sharing page to "Federated Sharing", or display a message "federated sharing disabled by admin" instead of the blank page if there is nothing to show.
Thanks!
