### ISSUE TITLE
"Your apps" does not indicate enabled/disabled apps

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#8038]
The "Your apps" listing should indicate which apps are enabled and which are disabled.

**Comment by rullzer** [comment]
Mmm here it shows the `Enable` or `Disable` which pretty much tells you which of the ones it is now...

**Comment by juliushaertl** [comment]
We could add section headers to that, but from my POV the current layout is already quite obvious.

@nextcloud/designers

**Comment by pixelipo** [comment]
I agree with @rullzer - "Enable/Disable" button is quite informative. Plus, there are already specific categories "Enabled apps" and "Disabled apps" in the sidebar which can be used as needed

**Comment by rubrik** [comment]
This issue came about because of issue #7970

I wanted to install the Retention app, but in the latest RC of NC13 it was not listed under "My Apps", "Enabled", nor "Disabled". It was only listed under "App Bundles> Enterprise", with a button for me to enable it. Strange.

I have the feeling that there are two types of can-be-enabled app: apps that are installed but are disabled, and apps that are not installed and but have an enable button. In the first cast the app is where you expect, in the second case it is missing.

**Comment by skjnldsv** [comment]
Having an opacity play could be a good alternative to quickly check if the app is enabled or not.
What do you think? Or should we close this? :)

**Comment by MorrisJobke** [comment]
> I have the feeling that there are two types of can-be-enabled app: apps that are installed but are disabled, and apps that are not installed and but have an enable button. In the first cast the app is where you expect, in the second case it is missing.

I guess this is the reason: retention is not available in code. It would be installed from the appstore. The enabled/disabled sections only show apps, that are in the `apps/` folder. All other apps from the appstore are not shown there. The app bundles as well as the section show them, because they ask the appstore about those details.

**Comment by jancborchardt** [comment]
We need to be more clear here, and section headers for "Your apps" aas @juliushaertl mentioned are good:

- Enabled
- Disabled (with a subtitle like: "Installed but not enabled")

------

When we have those headers we can even get rid of the "Enabled apps" and "Disabled apps" navigation entries as they just duplicate info and are a historical leftover cause they existed before the unified "Your apps".

**Comment by MorrisJobke** [comment]
> Disabled (with a subtitle like: "Installed but not enabled")

I still think that nobody gets this. For a normal person installed and enabled is the same. Mostly like our "updater" (replaces the code from old to new version) vs "upgrade" (runs the actual migration and so on).

**Comment by szaimen** [comment]
In my opinion is it already pretty clear which apps are enabled and which disabled by looking at the buttons in this overview. Since overviews for enabled and disabled apps already exist you can also filter for those.
Also there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
