### ISSUE TITLE
Also translate the Calendar invitation email

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#8086]
As a follow up of #2338 it would be nice if the invitation emails were translated into *the recipients language*, just as we do with the login screen and everything else.

Would that be possible?

cc @georgehrke

**Comment by georgehrke** [comment]
The server part is already done, but it needs changes to the calendar app that were not merged yet but are in the works.

**Comment by enoch85** [comment]
Great news!

**Comment by georgehrke** [comment]
For reference: https://github.com/nextcloud/server/blob/e43138a6587e6c7ed93d8fd47a77c3326df16f13/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L158L159

**Comment by enoch85** [comment]
I hope that this also includes the timezone? In Thunderbird for example it translates my timezone to the recipients in the invitation.

So if I'm in Sweden and the recipient are in Australia, I set 19:00 on Monday, and when the recipient gets it, it's 08:00 Tuesday* (their local time). 

* I'm not sure if the hours are correct, but you get the point.

**Comment by georgehrke** [comment]
No, because there is no unique relation between language and timezone.

Even if we are talking about countries with their own language and only one timezone (like Germany or Sweden), you can't really say that a person is living in Sweden just because Swedish is their preferred language. What about Swedes that moved to a different country? 

Even worse are countries with multiple timezones. en_US would map to 6 timezones. Australia has 5 different timezones (and some regions have DST, some don't ...)

Additionally I myself (like many other) use all software in english, but still I'm living in the timezone `Europe/Berlin`. Any of the 6 en_US timezones would be wrong.

---

BUT: For the "accept invitation via email link" feature I'm planning to add a special page that shows information about the event and will allow you to add additional guests coming with you or allow you to add comments.
This page will automatically detect your timezone and the localized version of the time.

**Comment by enoch85** [comment]
Fair enough. :)
