### ISSUE TITLE
occ files:scan doesn't work correctly with group folders

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#8148]
### Steps to reproduce (various, example)
1. On NC data server, navigate to a group folder and then create a folder
2. Run occ files:scan --all
3. Add files in web UI to new folder

### Expected behaviour
Tell us what should happen
New folder should be found and then act as if a new folder was created in web UI

### Actual behaviour
Tell us what happens instead
New folder is found, but has wrong permissions assigned

NC 12.04, updated multiple times.

Additional: similarly when sub folder drag and drop issue https://github.com/nextcloud/server/issues/8139 leaves detritus in the DB, files:scan --all doesn't clean it up

**Comment by xonlinedevelopment** [comment]
NC 14.0.3 Permission is apache:apache and chmod 755 on /var/lib/nethserver/nextcloud/__groupfolders ( and subdirs 1/2/3/4/... ) Still the same problem...  So what do you mean "Manually setting the permission" ?
You will be able to find your folder id using
occ groupfolders:list
occ groupfolders:scan <folder_id>  ( Gives another error, could be fixed in version 15 ??? )
I installed mysqladmin and found my undeletable folder in the oc_filescache table.
After deleting the row from the filecache table the folder was removed from the list.

**Comment by richman1000000** [comment]
I had same issue for a 5 month!

I found it setting permissions in file
lib/private/legacy/util.php

change permission to desired level and comment out  error line
.
![image](https://user-images.githubusercontent.com/9943374/82058029-db99b580-96cc-11ea-8a8b-5d5a899c5f69.png)

**Comment by nortonpt** [comment]
maybe some of the folders that you copied arent set with the user/group www-data.
change the owner and group to **www-data** of the folders/files that you want to detect with occ.

after you change this, occ will detect your files and folders!

**Comment by richman1000000** [comment]
this files created by FTP service and OCC. cause of this it must be group accessible

**Comment by fschrempf** [comment]
@putt1ck Is this still an issue? If yes, can you please move it to the groupfolders project so we can close this?

**Comment by putt1ck** [comment]
@fschrempf not tried it since reporting the bug. Can be closed from my perspective but others have reported it more recently than me.

**Comment by szaimen** [comment]
please use the applicalble command of those to scan grupfolders. Thanks! https://github.com/nextcloud/groupfolders#command-line-configuration-via-occ
