### ISSUE TITLE
NC12/13 - Time "in a few seconds" is wrong

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#8194]
Change "in a few seconds"  to "a few seconds ago" ? 

![image](https://user-images.githubusercontent.com/16019165/35855772-5e4516fe-0b34-11e8-9ebc-af5cc4a49571.png)

This statement is wrong since the event occurred in the past.

**Comment by MorrisJobke** [comment]
Could you report this in the log reader app: https://github.com/nextcloud/logreader/issues

Thanks a lot 👍

**Comment by MorrisJobke** [comment]
cc @icewind1991 just clear this and max out at `now()`

**Comment by BornToBeRoot** [comment]
It's not only related to the log reader:

![image](https://user-images.githubusercontent.com/16019165/35867784-0092e2bc-0b5b-11e8-8aeb-bfae70b832ab.png)

**Comment by MorrisJobke** [comment]
This is a different issue then - also this is always tricky, because it is most likely due to wrong clocks and we had lengthy discussions about this. The time is transferred like this and we just show the value. 


See #827 for example.

Let's focus on this in #2700 and hope that we can address this properly without hacking the UI representation.
