### ISSUE TITLE
e-mail  templates editor is missing NC13

### ISSUE THREAD

**Issue by IamAliBaba** [nextcloud/server#8350]
Hi Guys,

I'm using NC 13 and cant find E-mail templates editor.

could anyone tell me how to do it ?

Thanks,
Ali

**Comment by cornouws** [comment]
please see #7229 
We had the problem that E-mail to users had invisible password reset button and link to shared document because color is taken from Admin > Themes > Color ..
So your request makes a lot of sense to me.

**Comment by Volker-K** [comment]
Hi there!

Just made the step from 12.0.3 to 13.0 yesterday in our testing environment looking forward to see the template editor and didn't find it. 

Since we "customize" the welcome- and password-reset-mail by editing the l10n-Files on each update the editor would be very helpful.

Thanks,
V.

**Comment by Perry2493** [comment]
Hi,
i set up a new NC13 instance - but can't find that template editor described in NC13 Documentation..

is there any way to enable it?

**Comment by MorrisJobke** [comment]
We removed the template editor, because we changed how they work. You could overwrite them by writing a class that implements the template interface (or extends it to not need to copy over everything). Easiest way is then put this class into an app and load it (so you do not need to patch it in on every update).

An example is here: https://github.com/nextcloud/templateeditor/issues/23#issuecomment-328175633

The documentation is outdated and not valid anymore. @MariusBluem could you check that and update it?

That is the interface of the class that needs to be implemented: https://github.com/nextcloud/server/blob/master/lib/public/Mail/IEMailTemplate.php

That is the implementation that could be extended and used to see how it works: https://github.com/nextcloud/server/blob/master/lib/private/Mail/EMailTemplate.php

Easy way is not possible anymore, because the theming was very limited and did result in a lot of broken emails. Also we put a lot of effort into the theme to look the same in all the different email clients out there and it works very well with the theming app.

**Comment by MorrisJobke** [comment]
Duplciate of #5152
