### ISSUE TITLE
Request: Zip folder tree when File Drop upload would otherwise fail

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#8383]
When exporting from Nextcloud server that it will sometimes create a zip file.  [Issue #4163](https://github.com/nextcloud/server/issues/4163) related.  I’ve noticed users having trouble uploading folders via `file drop (upload only)` as opposed to individual files.

What about the server zipping the folders and then uploading them, specifically when the upload would otherwise fail.  This would be helpful for anonymous uploads where the user lacks the knowledge to zip files themselves.

**Comment by MorrisJobke** [comment]
> What about the server zipping the folders and then uploading them, specifically when the upload would otherwise fail. This would be helpful for anonymous uploads where the user lacks the knowledge to zip files themselves.

The problem is already during upload. So the server can't do much. Either the files get delivered properly, then it would not make sense to zip and unzip them on the server - they are already there. And in the other case they don't even reach the server.

Sorry for the bad news here. We still will improve the upload experience by providing for example chunked upload for large files and better folder detection. Thanks for the feedback anyways

**Comment by sunjam** [comment]
Thanks the feedback.  Problem I’ve noticed is folders / sub-directories
just straight up failing to upload with no feedback given to the file drop
uploader or admin.  Unless the client has taken the time to zip a directory
it will fail to upload to a file drop.  This makes the file drop much less
useful.
