### ISSUE TITLE
`stat` is being launched for every file that is scanned.

### ISSUE THREAD

**Issue by StyXman** [nextcloud/server#8405]
I just installed NC 13.0.0 and I noticed that it was taking a lot to scan my photos. I attached an `strace` the the scanner and I found out that's it calling `stat` for each file! I'm not talking about the C or PHP function, I'm talking about `coreutils`' `/usr/bin/stat`!

This has a huge performance impact in my server, and looking at the code, I can't figure out why this is tried before using the PHP function `filesize()`. And why it isn't even using `[stat](https://secure.php.net/manual/en/function.stat.php)`? Not to mention that is not calling `escapeshellarg()` either.

**Comment by juliushaertl** [comment]
@StyXman Are you running NC on a 32-bit system? It seems that the exec is used there to workaround integer size issues. Anyway the arguments are properly escaped there using escapeshellarg https://github.com/nextcloud/server/blob/c1e4f9f30563d5eda1718d716d631d6092cd4e28/lib/private/LargeFileHelper.php#L148

**Comment by marco44** [comment]
Disclaimer: I'm not a PHP developper. So I may miss the point.

But since I faced this issue, or something similar, I gave it a look...
If I read correctly, to get filesize, the code should use curl before doing an exec for file size, which should avoid an exec ? It doesn't in my environment, so I feel something is wrong with getFileSizeViaCurl (curl is activated in php.ini)

I still have a lot of execs. Because this is also used for getting mtime, using stat %Y. And this seems to be a waste of resources, as I should be ok until 2038 on this small arm device :)

Anyway, this has a huge cost in my use case. Commenting both execs made the load go from 4 CPUs to 10% of one in this environment...

**Comment by marco44** [comment]
Hi,

Here is a proposal... I can do a pull request if you tell me it seems ok...

[diff_LargeFileHelper.txt](https://github.com/nextcloud/server/files/2004962/diff_LargeFileHelper.txt)

**Comment by marco44** [comment]
BTW the thing I missed: if you perform a getfilemtime on a file bigger than 2GB, PHP throws an exception… hence the exception block around it.

**Comment by juliushaertl** [comment]
@marco44 The changes make sense to me. It would be great if you could open a pull request for this so we can discuss the changes properly. :+1:
