### ISSUE TITLE
Request: allow weak passwords on shared folders after confirmation

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#8464]
Please consider allowing weak passwords (1,000,000 most common passwords) for users who choose to use one on a shared folder even after being warned not to.  Main reason is sending someone a folder with editing capability, which doesn’t need either a complex password or a set expiration.

**Comment by tflidd** [comment]
Why do you set a password at all? It's not very likely that someone guesses the sharing id in the URL and if someone gets his hands on the mail with the URL it probably contains the password as well.

**Comment by sunjam** [comment]
My thought is to allow the receiver (a user with no knowledge of Nextcloud)
to optionally request their own password irl for a folder they’ve created.
If they choose “Doug” I’d like to just stick with it.  The email sent to
them in this case would just include a folder url.

**Comment by MorrisJobke** [comment]
Currently there is no way to configure this depending on the type of password. Either you enable the password policy or not. If you don't want to use it we recommend to disable the app then simply.

I will close this ticket for now, because this feature is not on the near roadmap. If somebody wants to work on this, then the code can be found at https://github.com/nextcloud/password_policy
