### ISSUE TITLE
Add Open Sans fonts WOFF2 file format

### ISSUE THREAD

**Issue by coliff** [nextcloud/server#8509]
Currently the Open Sans font which is bundled with Nextcloud is only available in WOFF and TTF. It'd be great to add WOFF2 as the file size is smaller which makes for faster download speeds. WOFF2 browser support is very good (https://caniuse.com/#search=woff2) and older browsers can always fallback to WOFF.

**Comment by MorrisJobke** [comment]
Our goal is to have as few fallbacks as possible because then it's harder to debug certain issues. I guess for now we will not use WOFF2. TTF is only there because some distros do not support WOFF fully, so we use on the PHP side TTF.

Sorry for the bad news, but we have a lot of other more urgent stuff that also demands our time and there is no real issue with WOFF for now.

Thanks for the request anyways.
