### ISSUE TITLE
Add Avatar to Groups

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/server#8525]
It would be nice to have the possibility to add avatars to the Groups. The grey "?" Circle could look better with an own avatar. 👍 
This could be seen especially in the "shared with" view when you share folders by groups.

**Comment by ChristophWurst** [comment]
Although this sounds like a nice feature, the number of requests for this are quite low. Currently there a no plans to implement such a feature, hence I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Thank you :v:

**Comment by klodr** [comment]
![Capture d’écran 2022-06-23 à 06 17 08](https://user-images.githubusercontent.com/489942/175207972-1a103022-327f-4e70-ab00-6e5074fb0915.png)
![Capture d’écran 2022-06-23 à 06 16 49](https://user-images.githubusercontent.com/489942/175207976-9c93e0a7-e785-4e82-8395-c51d7bcb9f56.png)
Can't believe it's still not implemented after four years.
The shareoverview is so unreadable because of that ! 
Even the First letter of the group is missing. Just a silly question mark !

Please upvote this basic change ! 👍

**Comment by ilicz** [comment]
It's similiar on the Deck board overview, when deck is shared to a group of users:
![image](https://user-images.githubusercontent.com/98597308/199234589-7c4fcc5e-401c-4cac-bca0-03a1c16dff40.png)

**Comment by jacksbox** [comment]
bump, useful feature. Displaying "not found images" looks kinda shitty and un-professional

**Comment by xundeenergie** [comment]
It's november 2025... and still open...

**Comment by aurisnoctis** [comment]
An (optional) icon would be even nicer than just the current 2-char abbreviation. 🙏
