### ISSUE TITLE
Synced data gets synced to sync point and to $SNAP_DATA

### ISSUE THREAD

**Issue by jhodapp** [nextcloud/server#8551]
### Steps to reproduce
1. Install nextcloud via the snap package: snap install nextcloud
2. Set sync points not located in $SNAP_DATA, for example $HOME/Documents
3. Observe that synced data from other machines on the server goes into /var/snap/nextcloud/common/nextcloud/data/$USER/files/Documents instead of just into $HOME/Documents

### Expected behaviour
Synced data should only go to the sync point outside of the snap, not just into $SNAP_DATA

### Actual behaviour
It seems that my data is synced both to the sync point outside of $SNAP_DATA and to $SNAP_DATA

### Server configuration

**Operating system**:
Ubuntu 17.10

**Web server:**
snap default version

**Database:**
snap default version

**PHP version:**
snap default version

**Nextcloud version:** (see Nextcloud admin page)
12.0.5snap1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
snap install nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Happy to provide my log but it's too large to attach here.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
@kyrofa mind to have a look at this?

**Comment by kyrofa** [comment]
> Set sync points not located in $SNAP_DATA, for example $HOME/Documents

I don't quite understand what you mean by this. It almost sounds like you're talking about the client. Can you please explain further? Perhaps give the commands you used?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

Also keep in mind, that maybe https://github.com/nextcloud/nextcloud-snap is the better place to report it.

Thanks

**Comment by jhodapp** [comment]
Definitely still happening. Not sure why you'd close it even though nobody has addressed it.

**Comment by kyrofa** [comment]
> Not sure why you'd close it even though nobody has addressed it.

Because you weren't addressing it, either :wink: . You need to be responsive to questions-- we can't leave issues open forever!

**Comment by kyrofa** [comment]
Ah, I see what you're saying. Indeed, it goes to `$SNAP_COMMON` by default. You can change this however you like in the `config.php`, but I bet if you think about it, you won't want it in `$SNAP_DATA`-- in fact, this very snap is the reason `$SNAP_COMMON` was created in the first place (although it was ownCloud back then). Let me explain.

`$SNAP_DATA` (in `/var/snap/<snap name>/<revision>`) is _versioned_ data. This means that, as you upgrade revisions of the snap, the `$SNAP_DATA` that went along with each revision is kept in its own area, which is an important part of the rollback strategy: did the Nextcloud upgrade migration bork the mysql database? Oops, revert the snap: thankfully, the mysql data was in `$SNAP_DATA`, and you just rolled back to the previously-working version.

`$SNAP_COMMON` (in `/var/snap/<snap name>/common`) is _unversioned_ data, i.e. data common to all revisions of the snap. The reason for this is simple: The raw data in Nextcloud instances can be massive. Mine is well over 2TB. snapd by default keeps three old revisions around to be available for rollback: I actually don't have enough HD space for that to be multiplied by three! `$SNAP_DATA` is not supposed to be used so that you don't need to backup your data, it's supposed to be used however the snap needs to in order to empower rollbacks. This is exactly how the Nextcloud snap uses it.

To conclude, please feel free to move your data wherever you see fit, but this is not a bug in the Nextcloud snap.

**Comment by jhodapp** [comment]
@kyrofa Makes sense, and I appreciate the bit about how to configure it to point elsewhere, but I still think the default storage location is less than ideal. Usually the partition that I have /var under is not a big one, usually as small as I can get it was some wiggle room. I want most of my data somewhere under /home as that's always my largest partition by far. This is true for a desktop/laptop of course. Which makes me wonder if Nextcloud is typically treated by most users more like a serious server piece, in which case they may install it on a box with Ubuntu Server with a large /var partition. So maybe it's sane.

But I was also seeing the data copied twice, somewhere under /var but also under $HOME/<a_sync_dir>. It shouldn't be copying twice, right? And I misspoke in my last reply. I want it to go to something like $HOME/Documents if I'm trying to sync that point across all participating machines. I don't want it going into $SNAP_DATA for the reasons you pointed out. Make sense?

**Comment by kyrofa** [comment]
> Which makes me wonder if Nextcloud is typically treated by most users more like a serious server piece, in which case they may install it on a box with Ubuntu Server with a large /var partition.

Yes. Or in my case, a huge array mounted into `/media/` somewhere. So do you have the server and client on the same machine? Both client and server keep a copy of the data, so if you have them both installed you will indeed see two copies of the files.
