### ISSUE TITLE
Add temperature sensor data to Administration>Monitoring

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/server#8700]
This is a feature suggestion. I'd like to see a addition to the Administration>Monitoring that displays different temperature sensors that are available. This would be a nice quick way to identify possible hardware issues or even possibly rouge processes on the system.

**Comment by MorrisJobke** [comment]
> This is a feature suggestion. I'd like to see a addition to the Administration>Monitoring that displays different temperature sensors that are available. This would be a nice quick way to identify possible hardware issues or even possibly rouge processes on the system.

The rouge processes should already be identified by the load on the system. I doubt that we will bring this feature into the server info app, because there are a lot of other metrics that then also could be shown (active php-fpm workers, detailed network connection speeds, disk utilization, etc) and this would basically overcomplicate this app. It should provide some easy feedback. If you need more details a real monitoring solution is the way to go.

You can find the code of the app in https://github.com/nextcloud/serverinfo

I will close this ticket here, because of the above reasons and because this repo is about the server code and not the code of the serverinfo app.
