### ISSUE TITLE
In a shared folders, favorite status of files should be reflected to others too

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#8885]
When working together in a shared folder, the favorite status of files/folders therein should be reflected to the other participants of the share.

cc @camilasan cause it happened when we collaborated on a folder and expected the favorites to be reflected for each other.

@nextcloud/sharing

**Comment by rullzer** [comment]
Really? Favorites are private. Because if I think a file is useful doesn't mean somebody else thinks the same.

Also. If it is reflected in a shared folder I would expect it to also be reflected in all the share overviews. Because else I don't know if I have to favoriete it again myself.

But then again this is weird because I don't want all the favorites of files in shared folder to show up in my favorite list.

As an example. I have a few huge shared folders of pictures with family and friends. We might all have very different favorite pictures. Putting them all on one big pile feels wrong.

**Comment by MorrisJobke** [comment]
Also we then should think about the "download all favorites on mobile by default", because this would have interesting impact to how you can use the app and the favorite system.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
