### ISSUE TITLE
Implement "only plain-text e-mail" option

### ISSUE THREAD

**Issue by rysiekpl** [nextcloud/server#9031]
We are using Nextcloud with a GPG encrypting SMTP proxy ([kuvert](https://github.com/az143/kuvert)). HTML e-mail is notoriously problematic with GPG encryption, and things break especially when there are attachments added to the mix (like calendar invites).

It would be a very welcome feature if it were possible to check a check-box somewhere in e-mail settings to instruct Nextcloud to *only* sent plain-text e-mails (no HTML what-so-ever).

**Comment by GoetheG** [comment]
Yes. This idea soubds great, @rysiekpl.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @nextcloud/designers @rullzer

**Comment by jancborchardt** [comment]
Sure, sounds reasonable as config setting. Not sure it's necessary to show in the admin settings interface.

**Comment by MorrisJobke** [comment]
> Well, is there a good reason not to show it? It will make it much easier for admins to discover this option if it's available directly in the admin interface, and instance admins can be expected to be technical enough to not get daunted by it being there, no?

Because we put only things there that have a broad audience and see the config.php flags as some hidden things, that you really should look for if you want them. The options in the settings should be really broadly used ones, that actually benefit for all. Otherwise you would be drowned in settings like here:

![jtmfhcn](https://user-images.githubusercontent.com/245432/38256421-85d6862a-375e-11e8-8281-7b7464176dce.png)


We want to give admins and users a nice experience and if there is a super special corner case (like what you described, if you run a GPG encryption on your email server), then you could set this special flag. There is also a reason why Firefox or Chrome don't put all of their feature flags in the settings but on a special page.

**Comment by rysiekpl** [comment]
Fair enough. I am a strong supporter of "click here for advanced settings", but that's obviously your call. As long as it's implemented somewhere and documented, I am a happy happy admin. :)

**Comment by MorrisJobke** [comment]
Fix is in #9205

**Comment by rysiekpl** [comment]
Fantastic news, thank you!
