### ISSUE TITLE
Music/Audio player apps not grabbing audio files over shared folder

### ISSUE THREAD

**Issue by mzeyrek** [nextcloud/server#9039]
### Steps to reproduce
1- mount local music folder as admin with enable sharing option and available for admin only.
2- share mounted music folder with users (or group) with cannot edit and cannot reshare options.
3- login with user and start a manual library scan from music app or audioplayer app. Audio files visible via Filemanager but not considered as audio under music apps.

### Expected behaviour
users should be able to listen music from relevant app. like music app or audio player app.

### Actual behaviour
only admin can listen music rest is able to download music only.

### Server configuration
Operating system: Debian 9 Stretch
Web server: nginx/1.10.3
Database: MariaDB 10.2
PHP version: 7.0
Nextcloud version: (see Nextcloud admin page) 13.0.1

**Screenshots and detailed problem
https://help.nextcloud.com/t/music-app-not-showing-shared-external-drive-files/27961

**Comment by MorrisJobke** [comment]
Please report this to the music app. I guess this is because the scan of the music app is not properly detected. Maybe because the music app does only an initial scan and then listens to the "upload" and "delete" hook and not rescans periodically, because mount points and shares don't trigger those. At least this is my guess what the underlying issue is here.

**Comment by Rello** [comment]
Hello,
please ensure, that occ-filesync is done properly. Audio Player will only index whatever is in the filecache table.
Another starting point would be to use the `--debug` option in the `occ audioplayer:scan` command for further insights.
if you need more assistance, please report to https://github.com/rello/audioplayer/issues
