### ISSUE TITLE
[DESIGN BUG] Minor - Add buttons for "Stay Logged In" & "Forgot Password"

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#9061]
This is a minor bug in Nextcloud V13, I would recommend making the "stay logged in" and "forgot password" into buttons, this would help them stay noticeable regardless of the background and color scheme chosen.

Currently this is what happens:

https://i.imgur.com/loHmUmr.png

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

I would keep them as they are, because they should be not as prominent as the actual login button.

**Comment by skjnldsv** [comment]
The remember login checkbox will disappear soon, so I'm not convinced about this :)

**Comment by c0fe** [comment]
@MorrisJobke no, but they should be visible somewhat

**Comment by MorrisJobke** [comment]
> @MorrisJobke no, but they should be visible somewhat

@ChristophWurst didn't you add some CSS to make them more visible?

**Comment by ChristophWurst** [comment]
> @MorrisJobke no, but they should be visible somewhat
> 
> @ChristophWurst didn't you add some CSS to make them more visible?

Nope :man_shrugging:

**Comment by MorrisJobke** [comment]
> @ChristophWurst didn't you add some CSS to make them more visible?
> Nope 🤷‍♂️

maybe @skjnldsv ?

**Comment by juliushaertl** [comment]
We have a slight text shadow on the forgot password text, which is black. Since your background image is pretty dark, there is not much we can do about that, because by default we would have black text on the lighter green background color, which would work fine there.

For that theming constelation, you might want to checkout the theming_customcss app and set some rules to make the text color fit better to your background image.

@nextcloud/designers As @MorrisJobke said, I'd keep it like this, since with multiple buttons there would be too many elements trying to get the attention of the user and it should be clear to the user what the main action (login) is.

**Comment by skjnldsv** [comment]
> maybe @skjnldsv ?

Nope :man_shrugging:, Don't recall editing the guest page since a long time :)

**Comment by c0fe** [comment]
Is the CSS styles completely custom made for Nextcloud or does it use bootstrap as well?

**Comment by MorrisJobke** [comment]
> I see I was hoping that there would have been some highlight type of element already there.

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
You could simply copy the CSS of the buttons and add it as custom CSS for the elements you want to button-ify. Or even simpler: Make the text of those functions white.

As said by the others above already, this is not something we will do in core:
- The buttons will fight for attention with "log in" but are way less important
- "Remember log in" might go away anyway since it’s going to be remembered automatically (unless people log out of course)
- That shade of green might be right on the edge of where text is either black or white. And then the background image is darker.
