### ISSUE TITLE
Nextcloud Helm Chart

### ISSUE THREAD

**Issue by feluxe** [nextcloud/server#9086]
Hi there!

I just wanted to install Nextcloud in a Kubernetes cluster and was a little bit surprised, that there is no [Helm](https://helm.sh/) Chart for it, at least I couldn't find one on https://kubeapps.com and else where.

Owncloud has one available:

https://hub.kubeapps.com/charts/stable/owncloud

https://github.com/kubernetes/charts/tree/master/stable/owncloud

**Comment by MorrisJobke** [comment]
> I just wanted to install Nextcloud in a Kubernetes cluster and was a little bit surprised, that there is no Helm Chart for it, at least I couldn't find one on https://kubeapps.com and else where.

The core project only provides the release archives. Packaging the application then should be done by people actually using it and being able to maintain it. That's how it is also done with the docker image or the snap package. So we would love to see this, but the server team will not do this, because we want to improve the software itself and not deal with all the possible packaging mechanisms out there. Nevertheless we help anybody having trouble packaging it.

I hope you can understand our point of view here as well. We are good in maintaining the software itself and want to focus on this :)

**Comment by crankbird** [comment]
it looks like someone has already put the chart into the stable kubernetes lamp examples here

https://github.com/kubernetes/charts/tree/master/stable/lamp/examples

I honestly dont know enough about kubernetes or distributing nextcloud to say for certain, but rather than being "closed, won't do" (which is fair enough), it might be nice to do some basic confidence testing and mark it "closed, fixed"

**Comment by instantlinux** [comment]
The link cited by crankbird above is a stub. There is a real owncloud helm chart in that repo, but as of this date there is no nextcloud chart.

**Comment by pfuhrmann** [comment]
FYI, There is now [stable/nextcloud](https://github.com/helm/charts/tree/master/stable/nextcloud) helm hence why this ticket was closed :)

**Comment by Hokwang** [comment]
update: chart is here. https://github.com/nextcloud/helm
