### ISSUE TITLE
Simplify email template

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9119]
@skjnldsv as discussed :)

| Verification email | welcome email |
|:--:|:--:|
| ![verify](https://user-images.githubusercontent.com/925062/38460427-cc8c58c0-3ab9-11e8-98b7-f5afba2e543d.png) | ![welcome](https://user-images.githubusercontent.com/925062/38460428-d3538eee-3ab9-11e8-97b9-3bb42d91605c.png)|

border-radius:3px on those buttons as per our standard would be cool to, or is there a reason we left that out?

**Comment by nickvergessen** [comment]
I dont think most email clients support border radius

**Comment by jancborchardt** [comment]
@nickvergessen ah ok. We could just add it and then it’s skipped when not supported.

**Comment by Django-BOfH** [comment]
What a 'bout really simplifying email templates ('cause there are some strange errors with html mails => #9102) and send plain-text mails as a (configurable option! => #9031)

**Comment by jancborchardt** [comment]
@Django-BOfH let's not derail this issue. As you mentioned, issues for those separate discussions exist already.

**Comment by c0fe** [comment]
@jancborchardt @nickvergessen here is a guide to what is supported on what email clients:

https://www.campaignmonitor.com/css/box-model/border-radius/

**Comment by KuenzelIT** [comment]
We just realized in our company, that the mails of nextcloud are not displayed correctly in Outlook, because it does not support border-radius (as shown [here](https://www.campaignmonitor.com/css/box-model/border-radius/)). This leads to a really strange looking logo.

Is this a known behaviour? Do we need to create a custom mail template or is there any chance of this getting fixed shortly?

Thank you!

**Comment by skjnldsv** [comment]
Superseded by https://github.com/nextcloud/server/issues/48095
