### ISSUE TITLE
Certain characters cause CalDAV calendar synchonization to fail via emClient

### ISSUE THREAD

**Issue by Pazu** [nextcloud/server#9123]
If a calendar contains certain characters such as 0x15 or 0x17, then CalDAV synchronization will fail via emClient 7.1 to Nextcloud (12.0.6, in my case), which throws a System.Xml.XmlException, after which the client abandons all subsequent synchronization.

The question is, should Nextcloud refuse to accept such characters into a calendar item, or perform some clean-up on such characters during storage, or filter them out during synchronization, or something else?

`11:02:46 Account [CalDAV / CardDAV]  MailClient.Accounts.ConnectionException: '', hexadecimal value 0x17, is an invalid character. Line 1661, position 55. ---> System.Xml.XmlException: '', hexadecimal value 0x17, is an invalid character. Line 1661, position 55. `

I have examine the actual ics BLOB and it does, indeed, contain these characters.

In general, it appears calendar storage of existing calendars is very permissive. If I export this problematic calendar from Nextcloud, then import it again, many (69 in this case) errors occur.

See also <https://forum.emclient.com/emclient/topics/calendar-contains-character-0x17-emclient-throws-system-xml-xmlexception>.

(I'm forgoing the usual overlong issue template as I do not believe my individual server configuration is relevant.)

**Comment by Pazu** [comment]
See if I ever submit a bug report like this again.

**Comment by stefan817** [comment]
I have a similar problem. eM Client throws exception because of bad character. When I analise the logfile I can see, it is a Unicode replacement char (EF BF BD). 
![grafik](https://user-images.githubusercontent.com/26048888/206228363-fa2b93ef-3422-40c0-8f3a-0592c028cb16.png)
The way of my Event is long: 
I have imported a Google Calendar into Nextcloud Calendar with the App Google Import. So I'm not sure, if the bad character was already in Google too. 
In every case the question is: Shouldn't Nextcloud check the content it generates to CalDav against issues of bad characters and clean them, so that the ICS-Data are valid?
