### ISSUE TITLE
Read-Only or Master/Slaves options for sync dirs

### ISSUE THREAD

**Issue by jult** [nextcloud/server#9212]
I did not really find any clear info on this in the documentation, so I'll post this as an issue;
When I started using/installing nextcloud, I came from using syncthing, [lsyncd](https://github.com/axkibe/lsyncd) and rsync. I was really surprised to find nextcloud lacking many of their options. What strikes me as strange is the way nextcloud doesn't tell me at what side it will assume files can be deleted. It does warn me about deletions, but all after the fact. I think NC should offer read only syncs, or use a Master-Slaves principle, I expected something more configurable in that regard. Also, it completely disregards actions happening outside of nextcloud apps, in nextcloud's server folders, which is kind of strange as well. I have to do a files:scan with console.php from shell every time something changes, which can be tedious since I have ~280000 files up there. And then when files have been deleted server-side, after a scan nextcloud somehow assumes I've deleted them on my desktop. This really needs to have some config: At the very least an option to make sync dirs read-only. This is also crucial on mobile apps.

**Comment by MorrisJobke** [comment]
> I have to do a files:scan with console.php from shell every time something changes, which can be tedious since I have ~280000 files up there.

Nextcloud was simply not build to change files directly on the server. It is a huge performance gain, if you don#t need to check the filesystem every now and then just because some admin could have placed some files.



> And then when files have been deleted server-side, after a scan nextcloud somehow assumes I've deleted them on my desktop.

No - it does think: "the user deleted it" and thus deletes it from the desktop as well. It actually syncs the state.


The requests for a read-only feature are quite low. You could create app tokens that don't have filesystem access at all.

Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by jult** [comment]
> No - it does think: "the user deleted it" and thus deletes it from the desktop as well. It actually syncs the state.
That's not my point; The desktop app *claims* it discovered deletions were done locally, while they were never deleted locally. And it notifies the desktop user after the fact. Both are really dubious developer decisions.
If this is your 'reasoning' for not offering any config whatsoever regarding when, why, at what point, nextcloud decides to delete files, I guess I have made a huge mistake here, in trying to rely on syncing using nextcloud. Wasn't too happy about the android app, but the lack of a read-only setting for a sync takes the cake. For me this is a deal-breaker. nextcloud looked promising, but I still don't see why syncthing, nextcloud and seafile can't be put into 1 nice collaboration with a functional result. All 3 are severely lacking in their syncing behavior and options. Thus far the best results for me came from using bittorrent sync, but since that is closed source it didn't do it for me.

**Comment by MorrisJobke** [comment]
Could you then open a ticket for the client? https://github.com/nextcloud/desktop
