### ISSUE TITLE
server/apps/theming – standard nc css gets loaded before theming app css

### ISSUE THREAD

**Issue by digsig** [nextcloud/server#9246]
### Steps to reproduce
1. load nc without cached browser files   
2. theming app loads a ~1,8Mb background picture  
3. internet connection with 1,5Mb/s download

### Expected behaviour
- theming app's css should be loaded FIRST.
- standard nc css (nc logo, blue background colour) should be loaded 	IN NO CASE!

### Actual behaviour
1. standard nc css (nc logo, blue background colour) gets loaded (more or less completely)
2. after 0.3-1.5 sec it gets replaced with the desired theming app's css (black background, background picture, theming app logo)

### Server configuration

**Operating system**:
debian 9

**Web server:**
apache2

**Database:**
mysql (MariaDB)

**PHP version:**
7.0.27

**Nextcloud version:**
13.0.1

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by juliushaertl** [comment]
We are actually still using a static css file "guest.css" on the login page, we'll probably need to check if we can just drop that for a scss based one, since if I remember correctly, we just need this file on the maintenance/install page since we don't have the SCSS cacher ready then. With that we could make sure that we actually don't load the default styles.

Besides that, this seems to be handled differently by different browsers. Firefox shows the default styles, while chromium waits for the theming css to be loaded before rendering the page.

**Comment by szaimen** [comment]
I suppose this issue is still valid?
