### ISSUE TITLE
Generate avatar for guests

### ISSUE THREAD

**Issue by mario** [nextcloud/server#9457]
In conversations, we sometimes have guests which don't belong to the server, however, we still need an avatar for them.

What I'd suggest is that if userId is not found, generate a "?" avatar on top of some color.
Or something else, as long as it solves the problem.

**Comment by weeman1337** [comment]
I would like to take over this one. @mario which conversations do you mean?

**Comment by mario** [comment]
@weeman1337 for Talk. My initial idea was using this for Talk.

Keep in mind that @skjnldsv looked into this and though there are security/caching issues involved, so might want to consult him too :)

**Comment by weeman1337** [comment]
@mario for me it looks like 

> What I'd suggest is that if userId is not found, generate a "?" avatar on top of some color.
Or something else, as long as it solves the problem.

is already solved:

![image](https://user-images.githubusercontent.com/6216686/42394760-91910502-815b-11e8-94e1-ff160e597da1.png)

_T_ is a guest named _Test_.

If this ticket is about something else I didn't get it. In that case could you please clarify the problem to solve or goal of this ticket?

Otherwise this ticket may be closed.

**Comment by mario** [comment]
@weeman1337 have you tried this via the api? :)

**Comment by weeman1337** [comment]
Okay got it. The one above is a JavaScript solution.

@mario can you tell mt the called API path?

**Comment by mario** [comment]
baseUrl + "/index.php/avatar/" + Uri.encode(name) + "/" + avatarSize;

**Comment by MorrisJobke** [comment]
Move to 15

**Comment by MorrisJobke** [comment]
Moved to 16.
