### ISSUE TITLE
Sabre\DAV\Exception\BadRequest: expected filesize 2584835 got 1114112

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9471]
Hello,

I have received the following fatal error messages:

Sabre\DAV\Exception\BadRequest: expected filesize 2584835 got 1114112 2018-05-13T17:43:08+0200
Sabre\DAV\Exception\BadRequest: expected filesize 61724962 got 26787840 2018-05-13T17:24:48+0200
Sabre\DAV\Exception\BadRequest: expected filesize 2707452 got 1785856 2018-05-13T16:41:51+0200
Sabre\DAV\Exception\BadRequest: expected filesize 1193422 got 884736 2018-05-13T16:30:52+0200
abre\DAV\Exception\BadRequest: expected filesize 61724962 got 4636672 2018-05-13T16:30:51+0200
Sabre\DAV\Exception\BadRequest: expected filesize 8191601 got 2326528 2018-05-13T16:19:23+0200

Currently I do not receive any of these error messages anymore.

Version 13.0.2 is used, PHP Version: 7.2.5, mysql 5.7.22.

I was informed that there are problems regarding IOS 11.3.1. App version is: 2.20.8.00003, files are displayed for synchronization, but this is not done.

Best regards

Christian Huml

**Comment by hume1991** [comment]
I have overridden values ​​in the database, seems to work.
It is a bug. INSERT INTO oc_appconfig ( appid , configkey , configvalue ) VALUES (‘files’, ‘max_chunk_size’, ‘524288000’);

**Comment by danut2006** [comment]
Hello, I have the same issue, please can you help me with the file ant the path to modify for this issue? Thank you.

**Comment by hume1991** [comment]
Hello danut2006,

This is done in the database. Open phpMyAdmin, search oc_appconfig Edit Value and insert.

Best regards 

Christian Huml

**Comment by hume1991** [comment]
Sometimes mistakes come again.
Wait for Update...

Best regards

Christian Huml

**Comment by gregharvey** [comment]
Worth noting this is sometimes caused by `request_terminate_timeout` being set too low in the PHP configuration if you're using PHP-FPM. What happens is if the connection is too slow for a 'chunk' of a large file to upload, PHP-FPM just shuts off the connection part way through, and you see exactly this in the log.

**Comment by rahra** [comment]
I know that this issue is already closed but according to some mailing lists and a Google search it seams to be a persistent problem. It could be caused for a lot of different reasons. I'd like to mention this thread: https://forum.owncloud.org/viewtopic.php?f=17&t=32517 which lists many possible reasons.

In my case it seams to be caused by Apache's reqtimeout module. I could observe sudden TCP resets sent by the server which lead me to the DoS protection mechanisms. Disabling the module eliminated the problem. Probably it is just a matter of correct settings which fit the Nextcloud server.

I'd further like to point out that I had the same problem on another Nextcloud server where we installed a web application firewall in between which in some cases terminated the sessions because of false positive signatures during the file upload. The Nextcloud server issued exactly this error message as stated within this thread and it was not obvious firsthand that it was caused by the WAF.

**Comment by Ochlup** [comment]
few years still same bug .. is impossible upload big file (5gb+) with any setting ..

**Comment by Rickier** [comment]
> Worth noting this is sometimes caused by `request_terminate_timeout` being set too low in the PHP configuration if you're using PHP-FPM. What happens is if the connection is too slow for a 'chunk' of a large file to upload, PHP-FPM just shuts off the connection part way through, and you see exactly this in the log.

You are right. the max_execution_time need to be set a higher value than 30s in php.ini, by the way.

**Comment by kpleines** [comment]
Since today I got the same issue.
Did anybody fixed this Problem? Please help.
nextcloud 15.0.2
Thx

**Comment by jwilczek** [comment]
Also seeing this issue.

**Comment by rahra** [comment]
Have a look at my comment from 25th of July. This probably may help you.

**Comment by jwilczek** [comment]
Interesting, I am running behind a reverse proxy, not sure if it has any protections. But your comment definitely gives me some avenues to pursue. Thanks!

**Comment by ivr588** [comment]
> Hello danut2006,
> 
> This is done in the database. Open phpMyAdmin, search oc_appconfig Edit Value and insert.
> 
> Compare Value.
> 
> Best regards
> 
> Christian Huml

Hi,

I'm seeing the same issues. Can you please explain a little further what you mean by what you've posted? If oc_appconfig is selected, there are three columns. Here is the SQL:

INSERT INTO `oc_appconfig`(`appid`, `configkey`, `configvalue`) VALUES ([value-1],[value-2],[value-3])

so, which column does "Compare Value" go into?

thanks,

**Comment by ChrisAbela** [comment]
> I know that this issue is already closed but according to some mailing lists and a Google search it seems to be a persistent problem. It could be caused for a lot of different reasons. I'd like to mention this thread: https://forum.owncloud.org/viewtopic.php?f=17&t=32517 which lists many possible reasons.
> 
> In my case it seams to be caused by Apache's reqtimeout module. I could observe sudden TCP resets sent by the server which lead me to the DoS protection mechanisms. Disabling the module eliminated the problem. Probably it is just a matter of correct settings which fit the Nextcloud server.
> 
> I'd further like to point out that I had the same problem on another Nextcloud server where we installed a web application firewall in between which in some cases terminated the sessions because of false positive signatures during the file upload. The Nextcloud server issued exactly this error message as stated within this thread and it was not obvious firsthand that it was caused by the WAF.

This is to confirm that disabling Apache's reqtimeout module on Slackware 14.2 (apache-2.4.39) resolved this problem on my NC server. Thank You.

**Comment by jsaraiva** [comment]
@rahra 's advice is spot-on. When I disabled the reqtimeout_module in Apache's httpd.conf (centOS+CWP, latest version), the problem went away. Thank you very much!

**Comment by cbartondock** [comment]
Disabling reqtimeout_module sped up my nextcloud server enormously but unfortunately did not get rid of this error when uploading via webdav
