### ISSUE TITLE
Show only my files filter

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#9528]
in the menu of the files app I find quick filters for "shared with me" and "shared by me".
I'd like to suggest to add "Only my files" too

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@schaarsc this is the first time (as far as I am aware) that we get this request, and since we prefer to keep things simple, it would be good to know what your use-case is. Essentially, instead of describing what you want, describe which issues occur. We can then look for the best solution.

**Comment by schaarsc** [comment]
Use Case:
- user has three folders
- user has 50+ shared folders from other users
- user wants to navigate to one of it's folders

**Comment by schaarsc** [comment]
An alternative to "show only my files" filter could be a per user share_folder.
Instead of a fixed name in config.php, allow users to define a folder name in their user settings.

**Comment by jeffgdotorg** [comment]
I too would love a way to see "Only my files" in the Files application. That is to say, a shortcut similar to "Shared with others" / "Shared with you" / "Shared by link" which shows only files that my user owns.

**Comment by skjnldsv** [comment]
@jancborchardt thoughts? 
I think this is out of scope and would complicate things.

**Comment by schaarsc** [comment]
I still think that  it would make sense to have a filter "show only my files"

**Comment by knarrff** [comment]
I wonder how this request can be "out of scope". As I see it, "files" is a file manager and should help users manage files. Since "files" handles shares too, not just files owned by the respective owner, I can't see why a filter that only shows their own files would be "out of scope of the app". It may be out of the scope of how some users use it, but that's something different.

As for a use-case: one was already described. I also came here because of this: I wanted to cleanup my files and that means: "my files". I didn't want to touch my shares - if I wanted to do that I'd have the mentioned filters. I do have a lot more shares than own files. However, I couldn't find something that does "please show me only _my_ files". As I see it, _not_ having this option complicates things for users, as their overview of "which files are mine and which are shares" is affected.

**Comment by knarrff** [comment]
Can we please have this issue be re-opened, since nothing was addressed here? It was only the stale-bug that closed it (and now apparently refuses to re-open it)? It was waiting for feedback from the developers if I understand correctly - and was closed because none was given for some time...

**Comment by knarrff** [comment]
Bad bot!

**Comment by skjnldsv** [comment]
Done on 29
