### ISSUE TITLE
Check box suggestion

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#9560]
Currently the size of the checkbox in the web UI is 10 px by 10 px my suggestion is to make it 20 px by 20 px. I can open a PR if this is accepted. I find the current check box style too small.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Hey! Could you provide some screenshot so we can give our opinion? :)

**Comment by c0fe** [comment]
@skjnldsv will do later today.

**Comment by c0fe** [comment]
Sorry for the delay: https://imgur.com/a/wriaBl6

I still need to fix the checkmark itself.

**Comment by skjnldsv** [comment]
I'm not entirely convinced  :)
I see your point, but the design feels inadequate :/ 

Maybe increase the size, but not that much? @nextcloud/designers

**Comment by MariusBluem** [comment]
Instead of 10x10px - try 15x15px ...

**Comment by c0fe** [comment]
@skjnldsv why don't you like it double?

@MariusBluem I will try that in the morning and will post screenshots.

**Comment by skjnldsv** [comment]
Feels too big and out of the design scheme we're using :)

**Comment by juliushaertl** [comment]
> Instead of 10x10px - try 15x15px ...

Just in case we we go for this, 14x14 px would be the best to match the icons we have in the files list.

![image](https://user-images.githubusercontent.com/3404133/40528444-578e27a8-5ff1-11e8-8040-6f8634071746.png)

I'd be fine for making them a bit bigger in the files list, in in other parts of Nextcloud, checkboxes are clearly related to the label text they refer to and therefore should have the same height as the text. So I would not change the size of other checkboxes besides the ones in the file list.

**Comment by c0fe** [comment]
I guess my taste in design may be just weird :P

**Comment by jancborchardt** [comment]
Checkboxes are mostly next to text, in the settings etc. That's why the size is according to the text size.

Any size increase, even the one to 14px, makes it look off and imbalanced compared to the text.

**Comment by c0fe** [comment]
@jancborchardt don't know, dropbox has bigger checkboxes than font and it looks fine, imo.

**Comment by c0fe** [comment]
What about increasing the text size as well?

**Comment by jancborchardt** [comment]
@c0fe could you post a screenshot?

Actually increasing text size would be possible, but it’s a waaaay bigger thing since it has implications across all of Nextcloud. It requires more research also which standard size we should settle for (14px e.g.), which unit to use, etc – best to start with research what others do, and definitely this is a separate issue. Feel free to open an issue with research and discussion. :) cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Here is an example of where the checkboxes also show up next to text:
![](https://user-images.githubusercontent.com/245432/40617566-f941c9ca-628e-11e8-8181-c7d1973f2aac.png)
In Material Design for example it’s similar, the checkboxes are basically the height of an uppercase character. Bigger would be strange and unbalanced.

About increasing text size: That would have to go hand in hand with editing the interface sizes, as otherwise it will just look like we crammed larger text in the same UI. And it’s definitely a bigger task. And we have to research well and decide which size/unit is common or what we should use.

**Comment by c0fe** [comment]
@jancborchardt i just have a feeling that the current size feels a bit outdated, for a lack of better term.  So maybe playing around with this would be a suggestion for version 14?

**Comment by jancborchardt** [comment]
Sure. :) Playing around is good, just make sure it's balanced with the font size (and keep the two separate), and works everywhere there's checkboxes, not only in the file list.
