### ISSUE TITLE
Over 50% of the top tool bar is blank with most tools shoved into the additional tools bin ...

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/server#9570]
Over 50% of my top tool bar is empty. I have 7 active tool icons, 8 counting the o0o symbol and 11 in the ... additional tool apps bin. Why are the developers leaving 60-70% of the top tool bar empty space? Users need to be presented at a glance with as many of the active tool icons as possible without hiding them in the additional app tools ... bin. Nextcloud version 13.0.2

**Comment by ASmith-** [comment]
'Let's try out a 50% Blank Toolbar', that isn't a reason. Its like let's move the sofa closer to the Television. I fail to understand how leaving more than 50% of the upper toolbar Blank serves the users of Nextcloud whatsoever. That forces Nextcloud users to hunt and dig into the additional active tools after they badger the administrator asking endlessly about a specific tool which they could have instantly seen and used.

**Comment by jancborchardt** [comment]
We set a limit to how many apps are displayed because it would be way too much visual noise in the top bar. Since that top bar is shown everywhere, it would be a sea of icons (without text) always visible. If you have a list of 20 icons in the top bar without text it’s a bit impossible to distinguish, hence the "most important" ones (like Files, Calendar, Contacts, Talk etc) go first and are shown directly in the bar, while others are put in the list with accompanying text.

We don’t offer settings for every single small thing like adjusting that limit, because then our settings would be overflowing with unimportance where the really important things would not be findable. Also, they would need to be maintained to ensure working – which is unlikely for a small change like this. See the [Nextcloud design guidelines](https://nextcloud.com/design/) or the especially relevant read [Choosing our preferences](http://ometer.com/preferences.html).

We know that traditionally, open source projects tend to go for a »show everything« and »provide settings for everything« approach, but this is not sustainable as it makes for horrible usability and also increases workload on the limited resources open source projects have.

You are very welcome to check the linked pull requests and patch your Nextcloud yourself, or even write _and maintain_ an app for it. :)

**Comment by umrath** [comment]
Too bad that the developers don't honor the request of the users.
It's really not user friendly to have the three dots displayed even though there is a massive amount of real estate unused.

**Comment by jancborchardt** [comment]
> Too bad that the developers don't honor the request of the users.

We have design reasons for that as stated above. They are concerned with user-friendliness too, to not have everything cluttered. (As traditionally, open source software unfortunately is.)

In the linked issues there's also mentioned how to change this. So feel free to do that. But don't assume that your own preference should be a default for everyone.

**Comment by umrath** [comment]
How can a menu in a menu be more user-friendly than having the icons available straight forward on an otherwise huge empty space? That's completely illogical.
And yes, I do understand quite a bit about usability. This has nothing to do with being self centered.

Do A-B testing with non-tech people and ask them to open an app that is hidden behind the "..." and compare the results with a bar that offers the apps right away!

You did not offer any solution. You went the way all open source developers go when they believe that they have taken a sip from the fountain of truth and everyone else is wrong: You told me to change the code myself.
That is not a solution because I'm not a coder.

A solution would be at least an option to change this configuration.

**Comment by jancborchardt** [comment]
> You went the way all open source developers go

Just to be clear: I’m not a developer, but an interaction designer, did a bunch of usability work and also [wrote a "book" on it](https://jancborchardt.net/usability-in-free-software).

> How can a menu in a menu be more user-friendly than having the icons available straight forward on an otherwise huge empty space? That's completely illogical.

For the same reason that on an iPhone not _all_ apps are on one huge screen. It makes you get lost in a long list without any anchor point. Also it’s totally distracting to have a list of lots of icons on the top at any point.

A recommended read is [»How Chunking Helps Content Processing«](https://www.nngroup.com/articles/chunking/).

> Do A-B testing with non-tech people and ask them to open an app that is hidden behind the "..." and compare the results with a bar that offers the apps right away!

So then what happens when the screen is smaller? When it’s on a tablet or mobile, as many people nowadays use? Or when it’s more apps than even a desktop width can hold? At some point there has to be a break because there’s simply not enough space.


> A solution would be at least an option to change this configuration.

If we add settings for each simple thing, we also need to maintain all these and test them. And soon our interface will look like described in the article [»This Is What Happens When You Let Developers Create UI«](https://blog.codinghorror.com/this-is-what-happens-when-you-let-developers-create-ui/).

Another important read is [»Choosing our preferences«](https://ometer.com/preferences.html).

--------


@umrath If you are a designer and would like to get involved making Nextcloud better, please check the [Nextcloud design page](https://nextcloud.com/design/) and join us. :) Also, let’s keep the tone nice. We all do our best, and friendliness goes a long way.

**Comment by umrath** [comment]
I stay friendly when I'm treated equally. I did not feel that way. They way people argued before was very much "from above" and "we know better. shut up!"
Closing the request is also not a way to show respect.

Sadly, I do not have enough time to join the development. Nevertheless I'm still willing to test and provide feedback. That's actually the department where I have most experience.

The iPhone is actually a bad example because it's a mobile device with very limited real estate.
Here we are talking about a desktop app where we have more space than we can use.
Additionally, the iPhone in fact uses the full space available and does not leave 2/3 of the space empty.

The more proper comparison would be macOS and maybe something like the dock. Here the dock behaves exactly the way I described above: It scales up and uses as much space as there is available. There is no arbitrary, fixed limit and it doesn't randomly start to outsource additional apps into a sub menu.

I'm not arguing against using the "..." when you run out of space, which might be the case on very small screens.
But the crazy part is: The fixed 33% rule is actually forcing this situation because it requires a screen 3 times as big to display all icons.
In most cases the issue would not ever occur if the 33 % rule would not be enforced.

Additionally, the ui could (and should) be different on (small) mobile devices and not be "one size fits all".

**Comment by HongPong** [comment]
Could we put that 33 number into a preference (oh a slider who doesn't like sliders?) - having 7 showing and 3 hidden is not a preferred use of real estate. i understand the default would just like to show max 10 i think.

**Comment by teotikalki** [comment]
> We set a limit to how many apps are displayed because it would be way too much visual noise in the top bar. Since that top bar is shown everywhere, it would be a sea of icons (without text) always visible. If you have a list of 20 icons in the top bar without text it’s a bit impossible to distinguish, hence the "most important" ones (like Files, Calendar, Contacts, Talk etc) go first and are shown directly in the bar, while others are put in the list with accompanying text.
> 
> We don’t offer settings for every single small thing like adjusting that limit, because then our settings would be overflowing with unimportance where the really important things would not be findable. Also, they would need to be maintained to ensure working – which is unlikely for a small change like this. See the [Nextcloud design guidelines](https://nextcloud.com/design/) or the especially relevant read [Choosing our preferences](http://ometer.com/preferences.html).
> 
> We know that traditionally, open source projects tend to go for a »show everything« and »provide settings for everything« approach, but this is not sustainable as it makes for horrible usability and also increases workload on the limited resources open source projects have.
> 
> You are very welcome to check the linked pull requests and patch your Nextcloud yourself, or even write _and maintain_ an app for it. :)

@jancborchardt FOR YOU.  It would be too much visual noise FOR YOU. PLEASE realize that this is a PERSONAL PREFERENCE. It may be shared by many but it is FAR FROM UNIVERSAL. The number of issues I'm finding opened about this SHOULD be informing you of this!

This does NOT need an app. This needs a single setting in user preferences (yes, USER preferences, so that each USER can tailor this setting according to their PERSONAL preferences. That's how UI elements SHOULD be.) I personally don't think that even as a server admin I should be telling my users how they MUST layout their screens. That's philosophically antithetical to the same love of freedom that makes me an open-source enthusiast in the first place.

As far as MY personal experience goes, I find that having much more empty space than the amount of icons I have in the dropdown to be annoying and it gets MORE annoying every time I have to pointlessly click through the dropdown. I also can't think of anything else that enforces this large blank space... it seems far more common that as users choose to add apps they lose 'empty space' because it's being filled with THEIR CHOICES.

**Comment by 150d** [comment]
I hit this snag today as well when I installed more apps than the bar displays for the first time.

It's a shame that the designers feel they know better than the ones actually using the thing. This "function follows design approach" may work for Apple, but... you're not Apple.

Why not introduce a setting for the config file to remove the block and display everything? Leave out the UI option if you must, but don't block usability because you feel that "it looks nice".

**Comment by GrimDevelopment** [comment]
This really should be reopened. It's such an annoying layout.:persevere:

**Comment by jancborchardt** [comment]
This is a duplicate of https://github.com/nextcloud/server/issues/13079 where we long ago already agreed on a design where you could move the "more apps" icon to show more apps.

It would be great if instead of the 100th comment, someone would like to contribute this as a fix. Thanks a lot!
