### ISSUE TITLE
A home for your digital identity

### ISSUE THREAD

**Issue by laarisyko** [nextcloud/server#9612]
# A home for your digital identity

**I have a dream of a Nextcloud App, which lets me share personal information like birthday, adress, telephone number, etc. with webservices and others.**

I guess a lot of people are bored by these endless user account setup sessions, even though you just want to order something once in your life time. The new DSGVO even makes it much more difficult for companies to handle all these user data stored on their server.

What if you could share and revoke your personal with each single service?

# How could this look like
1. store your data in Nextcloud
2. create a shared link with password each time you want to create an account for something
3. From now on the webservice has access to your personal data, but you can control and update it at any time without the need of logging in to each single service. 
4. All services are up to date, if you want. You are now in control!
5. If you don't want to share your personal data any more, just click revoke and they do not have access any more (very similar to the already exisiting app-password function in Nextcloud)
6. The link could even contain a legally binding request that the service has to delete all dublicates of your data (--> DSGVO) 

# Technical implementation 
I would stick to a standard format like vCard. The shared link will just point to an individually generated vCard and the password gives the external service access to it, whenever it needs to process your personal data. We could even have a two factor authentifiaction or ssh system!? 

What do you think about this kind of functionality? I would love to have it 👍 I'm curious to read your opinion about this new feature?

**Comment by MariusBluem** [comment]
First, thank you for your input & ideas 🙈 The problem with this is, that you would need to have an (RFC) Standard for doing this ... of course we would have the ability to something like Gravatar for Name, E-Mail, Birthday, Avatar and other information technically.

But now to the problem: Which Service would be compatible to this? We are not going to create our own technical protocols if no other service is compatible with. With the open dav/caldav/carddav protocols we rely on open standards everybody is able to use. Same for Federated Shares which is compatible with ownCloud, Pydio and other services ...

A „Nextcloud Identity Protocol“ sounds nice, but the effort would be wasted because nobody else is using it (social media platforms, ...)

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. 
I'll suggest you raise this app idea on our forum, on the app ideas section, where you could have better feedback! :v:
