### ISSUE TITLE
Migrate from GitHub to git.nextcloud.com

### ISSUE THREAD

**Issue by JonasDralle** [nextcloud/server#9728]
[Microsoft will aquire GitHub](https://www.bloomberg.com/news/articles/2018-06-03/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github) ([second source here](https://siliconangle.com/blog/2018/06/03/microsofts-acquisition-github-said-done-deal/)).  
The perfect time to bring up the discussion point that centralization is hurting the FOSS Community.

I hereby propose to move the collaborative work on NextCloud over to a free collaboration platform run by NextCloud and thus, away from GitHub.
Running GitLab (or other platform) on git.nextcloud.com might be a good or bad idea (open for discussion)

Please vote with 👍 and 👎 .

**Comment by MorrisJobke** [comment]
We should not over-react here. Our whole workflow is currently handled over here and just because Microsoft has acquired Github doesn't mean it will be unusable within days. We just first check out if this makes sense at all and what the impact to the community itself is.

We should keep an eye on it but don't overreact. We should also not forget that hosting this also bounds some resources that we could otherwise use to develop Nextcloud itself (for people in the community & company) or run CI on it (for the machines).

cc @karlitschek

**Comment by karlitschek** [comment]
I suggest to monitor the situation closely and see how it goes. Moving to a different platform is a huge amount of work and we might be cut of from the rest of the community here. I suggest to see what happens and evaluate this after some time.

**Comment by MorrisJobke** [comment]
Let's close this for now and keep it in our heads for future decisions.

@JonasDralle Thanks for bringing it up anyways.

**Comment by JonasDralle** [comment]
Thanks for considering it.

I know it's a huge step that most FOSS communities aren't willing to make. After all, if anything is open then Microsoft has nothing to grab that it couldn't previously grab with their search engine.

**Comment by JonasDralle** [comment]
Microsoft _did_ acquire GitHub.  
Enough reason for me to move all my projects to somewhere else.

**Comment by Serkan-devel** [comment]
Note that Microsoft does press propaganda against the GPL-license and still have thousands of software patents to use against independent developers. Last I've heard is, they're trying to push Alpine Linux into a more permissive license, so hey can restrict, hen publish it on the Windows store

**Comment by JonasDralle** [comment]
This ticket does not concern itself with the fight of Alpine or VLC.
Personally I fear that Microsoft does the same to GitHub as they did with LinkedIn: turning it into a garbage fire of JavaScript and advertising.

[Selling free Software is okay](https://www.gnu.org/philosophy/selling.en.html). Even when the things itself (VLC, Alpine, ...) are available gratis via other means.
Sucks for the user who buys aline via the store instead of using their web browser to obtain it from official source for free.

**Comment by JonasDralle** [comment]
Its been half a year and GitHub has been aquired by MS. Nothing happened yet as Microsoft surely waits until the dust has settled.

NextCloud is an open source super-star. What the project maintainers decide has impact on how the world of FLOSS looks at GitHub. [Migrating to GitLab is easy](https://docs.gitlab.com/ee/user/project/import/github.html).

Please notice how I _recommend_ hosting your own and avoid GitLab.com. GitLab.com is hosted in Microsoft Azure. Decentralization is important to the world of FLOSS just like WOT or fosdem is.

@MorrisJobke should I open a new ticket or is this the right place to speak of a move from GH to `<something something maybe selfhosted>`. I know that a migration is expensive and might not have obvious return values. But it sure would be the right thing to do in current times.

**Comment by Serkan-devel** [comment]
Last thing I'm aware of is that Gitlab is moving to Google Cloud Services or something.
I think Phabricator already has git support and would be better suited than Gitlab. Especially for php projects

**Comment by JonasDralle** [comment]
I'm not talking about GitLab.com but the Software GitLab itself.
I don't know about Phabricator. For me it's less about software and more about independence.

**Comment by jospoortvliet** [comment]
Hi everyone,

We're a pragmatic project - you don't get stuff done without that. Most contributors are on Github - that's why we moved here in the first place. As long as that is the case, we stay here, just like we're active on Twitter (even though we think everyone SHOULD be on Mastodon) and so on. Ownership isn't really relevant tbh.

Perhaps it is possible to set up a copy on Gitlab - if anyone is up for the work doing that, join one of our Contributor Weeks or the conference and talk to us about it. Otherwise, we're going to end this conversation and lock this discussion as it is simply a waste of time.
