### ISSUE TITLE
php mail bug in swift

### ISSUE THREAD

**Issue by guenterpl** [nextcloud/server#9730]
Hi,
I think there is an error in php mail /swift

it call the php mail function with the sender exem. office@xxx.xom 

<-foffice@xxx.com>
instead of statt
-f <office@xxx.com>
 
so some mail programm doesnot accept the mail with not valid sender

there is a problem which the $extraparams in swift /transport

best regards
Günter

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @rullzer

**Comment by pawel-slowik** [comment]
I don't think this is a bug, at least not in the Nextcloud server.
The Nextcloud server delegates `From:` address handling to Swift Mailer:                                                             
https://github.com/nextcloud/server/blob/528eb1b2239a66826f0793fead0e06ab576b7a13/lib/private/Mail/Message.php#L40-L41             
https://github.com/nextcloud/server/blob/528eb1b2239a66826f0793fead0e06ab576b7a13/lib/private/Mail/Message.php#L98-L103

I'm guessing that this:

> there is a problem which the $extraparams in swift /transport

refers to Swift Mailer source code:
https://github.com/swiftmailer/swiftmailer/blob/181b89f18a90f8925ef805f950d47a7190e9b950/lib/classes/Swift/Transport/SendmailTransport.php#L115-L117
https://github.com/swiftmailer/swiftmailer/blob/181b89f18a90f8925ef805f950d47a7190e9b950/lib/classes/Swift/Transport/MailTransport.php#L28-L29

If there's a problem with that, it should be reported to Swift Mailer.

Most likely, hovewer, there is no bug in Swift Mailer either, because the syntax reported as an error is actually correct.
I.e. this is correct: `-foffice@xxx.com`.
There should be no space between the `-f` flag and the email address.
Look it up in `man sendmail` or on https://linux.die.net/man/8/sendmail.sendmail

I suspect that this is a server configuration issue.

**Comment by kesselb** [comment]
Is this still relevant?
