### ISSUE TITLE
Advanced Theming Support

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#9737]
I have a suggestion for Nextcloud to provide either documentation or support for better theming options. I am basing this on how Wordpress has structured their CMS and how it supports themes. If you design a theme, you have to make various designs for different parts of the CMS features, such as menus. This is done through PHP hooks, which simplify the process from the designers perspective.

I figured that the various features of Nextcloud can be setup so they are called out by the PHP hooks which would allow for much more different designs of Nextcloud.

**Comment by MorrisJobke** [comment]
We plan to not provide more options for theming. The theming app should the the go-to approach of how you could theme it. In the past custom themes caused people a lot of work and were not stable enough to survive more than a few patch releases.

Setting logos and colors is all that we will support in the near future. And there is nothing on the roadmap to drastically change this.

cc @nextcloud/theming @nextcloud/designers

**Comment by c0fe** [comment]
@MorrisJobke I am curious as to why that is, most themes for Wordpress can survive version updates without problems. It is only problematic for major version jumps and even then it is more kick the tires and walk around to see if everything is there. I figured that was the beauty of PHP.

**Comment by juliushaertl** [comment]
As @MorrisJobke said, offering theming like wordpress is doing it would have to much potential of breakage. Having some hooks might work well for Wordpress, since those are basically static sites that are generated. In Nextcloud there is a lot of JavaScript for the frontend, so a lot of dirty hacks would be required to make all the different things themable.

> It is only problematic for major version jumps and even then it is more kick the tires and walk around to see if everything is there. I figured that was the beauty of PHP. 

That is acutally another reason against more advanced theming. Once we introduce it, it needs to be maintained and tested for every release.

**Comment by c0fe** [comment]
@juliushaertl i see, i was not aware of the extent javavscript plays a store, if it does that much then yeah it would be a mess.

**Comment by MorrisJobke** [comment]
We tried it in the past and it was a huge problem for many people. Nowadays nearly everybody loves the theming app and we try to extend it with useful features (like dedicated favicon for 14 or the GDPR links for 13). Let's close it for now - thanks for the idea nevertheless.

**Comment by jancborchardt** [comment]
Also, let's keep in mind that we can't really compare Nextcloud and Wordpress. Wordpress themes are very important because it's basically website designs, facing outward – everything needs to be adjuatable. For Nextcloud, it's mostly an internal tool with sometimes collaboration – theming does not need to be as extensive here.
