### ISSUE TITLE
[Request]Add options to hide or change user name in shared files 'file shared by user'

### ISSUE THREAD

**Issue by yunlhan** [nextcloud/server#9789]
Hello,

This is actually not a bug report, rather a feature request. It seems nobody has mentioned this. The closest issue I found is [issue 9587](https://github.com/nextcloud/server/issues/9587).

Thanks,
Yün

### Steps to reproduce
1. Share a file from NC, then a link URL to the shared file will be generated;
2. Grab the link, and open web browser then go to the URL;
3. On top left corner of the banner of the download page of shared file, it shows

+-------------------------------------------------------------
 |  LOGO | SHARED FILE shared by USER
+-------------------------------------------------------------

### Requested behaviour
Is it possible to add extra options when sharing the file, we can hide the USER name or change it to Anonymous etc.?

### Actual behaviour
It is not changeable and shows the the user who has shared file. 

### Server configuration
NC 13.0.2

**Operating system**: Debian 9.0 stretch, LEMP stack on home server

**Comment by MorrisJobke** [comment]
> It is not changeable and shows the the user who has shared file.

That is the whole idea of that feature.

cc @nextcloud/designers for the option for this.

IMO this is nothing we should implement.

It's about the "von Morris geteilt" in this image:

![bildschirmfoto 2018-06-08 um 08 44 23](https://user-images.githubusercontent.com/245432/41143087-5567ecea-6af8-11e8-82ed-815b0c9788f1.png)

**Comment by MorrisJobke** [comment]
@yunlhan Why do you want to hide this information?

**Comment by yunlhan** [comment]
Thanks for your reply. I know it is important to show who's shared the file with colleagues. But if it is just a general share with the internet, i.e., the link is available in public domain, is it still necessary to show the name of the sharer? I am not sure if a bot can get a user name and auto generate passwords to attack a NC server. 

So what I was thinking was if the share is in 

- private group, the name is necessary. 
- public domain, would be able to hide the name?

Thanks,
Yün

**Comment by juliushaertl** [comment]
I don't think the target group for that feature would be big enough to justify introducing another option for this. In most cases the sharer name is a useful information and should be kept. 

@yunlhan you could just hide it visually like the following post in the forum suggests https://help.nextcloud.com/t/how-to-remove-shared-by-name/32492/5 Note that this will not hide it from the source of the webpage.

Otherwise how about just using a different user account that doesn't contain name details?

**Comment by yunlhan** [comment]
@juliushaertl Thanks for your link. I think creating a dummy account for general sharing will work.

**Comment by mamama1** [comment]
I and many others use this as a private dropbox. As it being private I don't want my real name to be shown to the whole world if I share something on the internet.

I think this is a legitimate request, think outside the box of nextcloud being an on-premises, online inhouse, colleague-collaboration platform.

those days privacy is a thing and to me it is ridiculous to not having an option to hide the real name.

**Comment by pge** [comment]
I have to second that.
As a platform that is meant to be used not only in a closed context like a company, family, etc. it should be possible to somewhat  anonymize shared links. 
There is nothing odd about privacy :)

**Comment by mamama1** [comment]
Unfortunately it seems this is not getting much resonance. This is nuts, who wants to publicly disclose his or her name when sharing some data in some (e.g.) forum?

Also, using some random, second user without a name doesn't seem very user friendly. How am I supposed to use this feature, if I have the Nextcloud client installed on my PC? If I want to share somethig with the world, use the Webclient? lol...

@nextcloud/designers please let us know...

**Comment by pge** [comment]
Nuts is to assume theres no audience for such a feature.
People that use nextcloud as an on-premise dropbox alternative like me are missing the "public folder" in Dropbox. 
And @mamama1 is right. I don't see the need to always disclose my identity when sharing a link.

**Comment by danielkesselberg** [comment]
> Also, using some random, second user without a name doesn't seem very user friendly. How am I supposed to use this feature, if I have the Nextcloud client installed on my PC? If I want to share somethig with the world, use the Webclient? lol...

Its possible to connect multiple accounts with same client. If you need to use this regularly this might work for you.

**Comment by danielkesselberg** [comment]
Here is an example if someone wants to work on it: https://github.com/nextcloud/server/pull/11898 

Hide download button is similar and the same steps (new database field, extend sharing model, some ui stuff) are required for "anonymous sharing" option.

**Comment by spackmat** [comment]
In https://github.com/nextcloud/groupfolders/issues/758 I described another usecase for that: We as a support team share files from a team-groupfolder for external people (like clients), but we don't want to expose our internal team members as this information is a) internal and b) very confusing for the external people accessing the files, when they talked to another team member and the file is shared by somebody, they don't know. We get this question on a regular basis: "Is this the right file, it says shared by someone, I don't know?"

So maybe in many cases this information is useful, but in other cases it is not, but confusing instead. In the past, all team members worked on one team account to solve that, but that was quite a stupid idea.

**Comment by dartcafe** [comment]
@MorrisJobke Is it leagal to reopen this issue? As shown, there are many use cases for this. Last but not least it is a confentially and organisation's policy thing and I second, that the sharer should be able to define if his username gets exposed or not.

**Comment by mamama1** [comment]
this is just ignorance and stupidity, that they're not going to implement this on purpose.

**Comment by dartcafe** [comment]
> this is just ignorance and stupidity, that they're not going to implement this on purpose.

No, it is a question of balancing values against costs. It's in the own interest of nextcloud to improve the system with customer valuable features. But not every feature is valuable at first sight. This is because things get discussed.

**Comment by mamama1** [comment]
> 
> No, it is a question of balancing values against costs. It's in the own interest of nextcloud to improve the system with customer valuable features. But not every feature is valuable at first sight. This is because things get discussed.

Usually this is true but in this case it has been deliberately decided to not implement this feature because they think we "are using it wrong", by wanting this feature. #SteveJobsStyle.

**Comment by dartcafe** [comment]
This issue was closed by the OP, because he found his way to solve his problem. But the thread shows some other use cases and arguments, which appeared after closing. 

As a user story I would say: 
1. As a user I want to be able to disclose my name from public polls, because my organisation has a policy not to expose personal infomations of our employes. (Organisation's force) Or 

2. as a user I want to be able to disclose my name from public polls, because I don't want my name to be exposed on wide spread shares. (user decision based on self determinated privacy)

The solution how to solve this, is another task. I.e. this could be done on as a global setting (to meet user story 1) or on a share basis (user story 2 with the cost of one more share option). But I would leave this to the UX pros.

> because they think we "are using it wrong", by wanting this feature.
This kind of discussion and arguing leads to nothing! I prefer staying factual.

**Comment by kesselb** [comment]
@mamama1 https://nextcloud.com/contribute/code-of-conduct/

**Comment by mamama1** [comment]
All those issues and feature requests are referring to each other for years now, although the use-case is more than obvious. This is absolutely ridiculous, hence my frustration and anger regarding this.

Posting the code of conduct doesn't help but only confirms the utter ignorance.

**Comment by jancborchardt** [comment]
@mamama1 please make sure to keep a friendly tone even if you are frustrated – being friendly and factual actually helps solve issues, while being aggressive and insulting does the opposite. Thank you! :)

@dartcafe nice proposal! Maybe it’s best to open a new issue with that instead of discussing in this old closed one? :)

**Comment by mamama1** [comment]
@jancborchardt not easy, since this is being discussed for at least almost three years now.

**Comment by spackmat** [comment]
@dartcafe Thank you for those user stories!

I would add just one aspect: If this is solved as a global setting it should be two settings: One for personal shares and one for shares from a group folder. In my organization and for my described usecase, this makes a huge difference: When I share from my personal storage, I want my name to be shown, but when I share from a group folder, I want the group name or no name at all to be shown.

Nevertheless, I would prefer to decide on a share basis, because the wanted behavior differs from share to share just like the other settings like an expiration date or a password.

**Comment by jospoortvliet** [comment]
> @dartcafe Thank you for those user stories!
> 
> I would add just one aspect: If this is solved as a global setting it should be two settings: One for personal shares and one for shares from a group folder. In my organization and for my described usecase, this makes a huge difference: When I share from my personal storage, I want my name to be shown, but when I share from a group folder, I want the group name or no name at all to be shown.
> 
> Nevertheless, I would prefer to decide on a share basis, because the wanted behavior differs from share to share just like the other settings like an expiration date or a password.

I would say that that's an additional option. It would be solved by making it configurable per share. A per-server setting effectively exists with the CSS change, I'd say.

**Comment by jospoortvliet** [comment]
> @jancborchardt not easy, since this is being discussed for at least almost three years now.

Sure, but you need a volunteer to do the work, don't you? Unless you pay someone, that is. And I don't know about you, but I rarely get motivated by people acting angry towards me to do something that helps those angry people... The main problem here, I think, is that it is a super niche problem. It might be real, but only 0.001% of our users has it - so finding a volunteer that wants to do it is hard. And a paid person won't do it, as we have to focus our efforts on things that help 90% of the users, and of course our customers. I'd love to be able to make everyone happy, but that would need 1000 more developers and who's going to pay for that...

Anyhow, thanks to the constructive efforts of @dartcafe the problem is now described in a way that someday might make a solution possible. I commented there, too. If you need/want this, I suggest you either find funding or volunteers - and keep the roadblocks in mind which I described in my reply there. This won't be a one-day-of-work kind of thing, for sure.

**Comment by dartcafe** [comment]
> A per-server setting effectively exists with the CSS change, I'd say.

Which only hides the name, but does not meet privacy expectations.
