### ISSUE TITLE
Consider about PHP 5.4

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#98]
PHP 5.4 is not longer supported by the PHP community, which causes that bugs (also security ones) might not get fixed 😱 Nextcloud 9 does still support this version (for whatever reason). Dropping it instantly makes no sense, because it is currently supported in Nextcloud 9.

We have two options. 

- Warn users in "Security & setup warnings" section about the outdated PHP version
- Dropping PHP 5.4 with Nextcloud 10

**Comment by MorrisJobke** [comment]
cc @karlitschek @LukasReschke

**Comment by LukasReschke** [comment]
Requirements such as versions should always be driven by: "How widely is something available?"

When it comes to PHP 5.4, it is luckily the case that all decent distributions ship 5.5, 5.6 or even 7.0. Below list contains the current supported versions by the current distribution supported OS versions:

- Ubuntu 12.04: 5.3 (This means you anyways need PHP from third-party sources)
- Ubuntu 14.04: 5.5
- Ubuntu 16.04: 7.0
- Debian 8: 5.6
- RHEL 6: 5.3 (you can update via SCL up to 5.6)
- RHEL 7: 5.4 (you can update via SCL up to 5.6)

This means that the installation experience for RHEL 7 and CentOS 7 users will be a little bit harder since you manually need to update to PHP 5.6 via SCL. It would however be possible to detect these cases and display the required commands in the dependencies screen on setup.

Considering that SabreDAV will drop support for 5.4 (http://sabre.io/dav/install/) we indeed may have to discuss this more. Personally, I don't see so many advantages on 5.5 vs. 5.4 from a developer point of view though. It's not like there would be a lot of awesome synax sugar as in PHP 7 :-)

**Comment by karlitschek** [comment]
let's discuss for the next major release. at the moment it has to stay because of old enterpriser distributions.

**Comment by LEDfan** [comment]
> Warn users in "Security & setup warnings" section about the outdated PHP version

This already happens. Tested with default PHP from Centos 7:
![selectie_426](https://cloud.githubusercontent.com/assets/2996275/16082804/1bbf2f5e-3313-11e6-8cd8-ed55cc00d5cc.png)

Note that these PHP versions are EOL for the PHP developers but the distributions still support them.

**Comment by happyreacer** [comment]
> 
    Warn users in "Security & setup warnings" section about the outdated PHP version 
This already happens. Tested with default PHP from Centos 7:
selectie_426
Note that these PHP versions are EOL for the PHP developers but the distributions still support them.

the same is in debian 7. The php 5.4 is supported bei the debian long term support.

**Comment by PascalReintjens** [comment]
I think this warning is too halfhearted. I'd change it and clearly state that php 5.4 and 5.5 have reached end of life and that it's therefore a major risk to still use these. 

On the subject of dropping support: I would drop it as soon as Owncloud drops it - to keep full compatibility. It basically seems decided that Owncloud will stop supporting PHP 5.4 as of version 9.2 so I would drop it in the Nextcloud equivalent too: https://github.com/owncloud/core/issues/25408

Additionally, it may be possible that Owncloud 9.2 will drop PHP 5.5 too (see https://central.owncloud.org/t/kill-php-5-5-as-well-for-9-2/866) and I'd follow this decision likewise.

And yes, there is still Debian Wheezy (with EOL on 31 May 2018) for example, but Nextcloud 10 would still be there for these guys. Someone who runs really outdated (versions of) distros, should be perfectly fine with not running the absolutely latest Nextcloud release.

**Comment by MorrisJobke** [comment]
> On the subject of dropping support: I would drop it as soon as Owncloud drops it - to keep full compatibility.

That is already the plan. They asked us to comment on this thread too. :)

**Comment by MorrisJobke** [comment]
Move to Nextcloud 11. we will support PHP 5.4 with Nextcloud 10.

**Comment by mar1u5** [comment]
#1211 ... Closing here :wink:
