### ISSUE TITLE
enhancement: merging accounts

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9816]
Hello,

i have discovered the APP Social Login from zorn-v, witch allow users to used their google/github/whatever social accounts to create/log-in in nextcloud ( from https://github.com/zorn-v/nextcloud-social-login ).

It would be nice to have the capability to MERGE accounts, as a users can have a full accounts with regular login, and another with social login... ( and not only in that case ).
This feature, if she make sense, would be available only for the admin, for security reason.

What do you think ??

**Comment by GoetheG** [comment]
I second it!

**Comment by MorrisJobke** [comment]
From a technical point it's not that easy to merge accounts, because we don't have a central knowledge of what apps stores what user data in which table. Thus as of now this is not really possible. You could nevertheless migrate files/folders and outgoing shares to another user with the occ command `files:transfer-ownership` which should accomplish most of the stuff you wanted.

I will close this ticket here for now.
