### ISSUE TITLE
Server not found due to periodic JS reloading

### ISSUE THREAD

**Issue by ogasser** [nextcloud/server#992]
### Steps to reproduce
1. Open Nextcloud in one tab (wifi connected)
2. Disconnect your wifi or Internet connection
3. Nextcloud reloads automatically and "Server not found" is displayed
### Expected behaviour

If no connection is available the Nextcloud tab should not go to "Server not found".
### Actual behaviour

Nextcloud should gracefully ignore when no connection is available

ocs/v2.php/apps/notifications/api/v1/notifications?format=json
### Server configuration

**Nextcloud version:** 10
### Client configuration

**Browser:** Firefox

**Operating system:** Linux
### Problem analysis

I found a possible reason for the above problem: Nextcloud seems to call `ocs/v2.php/apps/notifications/api/v1/notifications?format=json` every 10 seconds. If the network connection is cut this will fail with a "Server not found" error.

**Comment by jancborchardt** [comment]
Can confirm that this is very annoying. We should handle being offline more gracefully. cc @LukasReschke @schiessle

**Comment by rullzer** [comment]
I have seen the same behaviour. But I don't think it is the notifications app. Since @nickvergessen has a fuction in place to handle that gracefully.

https://github.com/nextcloud/notifications/blob/master/js/app.js#L208

But we indeed should look into this and fix it properly.

**Comment by rullzer** [comment]
It is the heartbeat call to keep the session alive.

This call automagically reloads if the response to that is an error. Now normally this is OK but if you resume from hibernation you don't have a network connection. So the sequence is

1. Have nextcloud open
2. hibernate/suspend machine
3. open a day later (or something)
4. javascript resumes and triggers the heartbeat reload
5. this results in an error since there is no network connection yet
6. error message with reload is triggered.
7. after 5 seconds the page is reloaded
8. this fails hard since there is no network connection yet

What we probably should do is trigger a special route if the response is invalid (no network). We should display the notification. And do the following

1. If there is no valid status code (so network down) go to special route
2. display notification
3. schedule check over 30 seconds (your network should be back up in 30 seconds)
4a. if all is well resume normal modus operandi
4b. if still fails display a popup error with a button to manually reload. So at least the users knows what is going on.

How does this sound? @jancborchardt @ogasser

**Comment by LukasReschke** [comment]
> We should handle being offline more gracefully. cc @LukasReschke @schiessle

What do I have to do with being offline and JavaScript? 🙈

**Comment by ogasser** [comment]
@rullzer Sounds good to me!

**Comment by jancborchardt** [comment]
@rullzer yeah, sounds good! :)

**Comment by te-online** [comment]
This is a job for a service worker! https://developer.mozilla.org/en/docs/Web/API/Service_Worker_API 😄

**Comment by nickvergessen** [comment]
No, this is "don't refresh the page, when one request failed"

**Comment by te-online** [comment]
Yes, you're right. Just joking. That would be a different story 😉

**Comment by MorrisJobke** [comment]
We fixed this one, right @LukasReschke & @nickvergessen ?

**Comment by MorrisJobke** [comment]
Let's close this one, as we did some work during 12 for this issue. Please comment if this still happens.
