### ISSUE TITLE
Pdf view bug

### ISSUE THREAD

**Issue by yoshimido** [nextcloud/server#9924]
Hi,

I found bug in nextcloud 13.04 in pdf viewer. If click on pdf then nextcloud show pdf view correct. But if pdf is digital signed then pdf file is showed without digital sign. 

If download document a open in default viewer everyting is ok. 

Thx for advance.

**Comment by MorrisJobke** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by MorrisJobke** [comment]
> I found bug in nextcloud 13.04 in pdf viewer. If click on pdf then nextcloud show pdf view correct. But if pdf is digital signed then pdf file is showed without digital sign.

Could you post a screenshot of the broken signature? Or is it just not shown? Then it would be a feature request and I would ask you to open in it the apps repository: https://github.com/nextcloud/files_pdfviewer

**Comment by MorrisJobke** [comment]
> You right. Just not shown digital sing in pdf document. Pdf document with digital sign looks ok but digital sign missing.

Then please open it as a feature request in the pdf viewer app. Maybe also check with the upstream project if they support it already. We use pdf.js from Mozilla - you can try out their demo on https://mozilla.github.io/pdf.js/

If it doesn't work there it makes most sense to file it on their side first and once they support it request it on our side.

Thanks
