### ISSUE TITLE
Sharing folders doesnt work

### ISSUE THREAD

**Issue by DekoLP** [nextcloud/server#9968]
### Steps to reproduce
1. Share a folder
2. Open the downloadlink
3. Password required.

### Expected behaviour
I should be able to download the folder

### Actual behaviour
Nextcloud wants to know a Username and a Password which doesnt exists

### Reason why it happens

the file permission of the "data" folder is apparently changed back to 770 on the call. But Nextcloud does not seem to work with this permission configuration.

**Comment by MorrisJobke** [comment]
> Open the downloadlink
> Nextcloud wants to know a Username and a Password which doesnt exists

If you used the "direct link" then this is expected, because it is basically a deep link to the file and looks like this:
https://cloud.example.com/f/464463


![bildschirmfoto 2018-06-25 um 07 48 58](https://user-images.githubusercontent.com/245432/41832430-4d884194-784c-11e8-8944-be3eb1f078a8.png)

You need to copy the share link, that is generated on sharing the file. It looks like and will work without authenticate again:

https://cloud.nextcloud.com/s/rbTgxs4sSXomMMM

![bildschirmfoto 2018-06-25 um 07 51 32](https://user-images.githubusercontent.com/245432/41832508-9f1d2312-784c-11e8-8826-bd6d16a9fd02.png)


the direct link looks like this:

**Comment by DekoLP** [comment]
I Used The share link but IT ist working

**Comment by DekoLP** [comment]
Isnt*

**Comment by MorrisJobke** [comment]
> I Used The share link but IT ist working

What is then actually not working. Do you have a screenshot? Could you post the URL? Anything in the logs or browser console?

**Comment by MorrisJobke** [comment]
> the file permission of the "data" folder is apparently changed back to 770 on the call. But Nextcloud does not seem to work with this permission configuration.

Is the owner of the files actually the web server? Are all processes run as this user? Also the cron user? 

This looks very much like a setup issue, which is better suited for the forums.

**Comment by DekoLP** [comment]
https://dekoyt.de/nextcloud/index.php/s/xxbwXFkbGFdnpTG

and you dont shared a folder, you shared a normal file. Sharing a normal file works but folder not (German: Ich denke wir können auch Deutsch schreiben)

**Comment by MorrisJobke** [comment]
> (German: Ich denke wir können auch Deutsch schreiben)

As we are an international community we communicate in English ;)

Looks like a setup issue. Maybe your web server is removing some headers that are needed. See https://help.nextcloud.com/t/authorization-required-for-anonymous-upload/1738

For further setup related questions I would ask you to raise them in the forums: https://help.nextcloud.com
