### ISSUE TITLE
User should change his password after a certain time

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9989]
Hello, 

Will there be a password change in the next Nextcloud versions (user must change password after a certain time)?

Best regards 

Christian Huml

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. The usual setup for this kind of policy has an external user management like LDAP and applies the rules there. Currently there a no plans to implement such a feature inside Nextcloud because of the mentioned solution. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out. It's most likely an extension to the password_policy app. For further discussions I would like to move this ticket there.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by hume1991** [comment]
Hello @MorrisJobke, 

There are some things I do not like about the Theming app. When using the Theming App, for example, the link to the same page is displayed (Footer). The adjustments themselves are very little in the Theming App. There are restrictions (Theming App).

Best regards

Christian Huml
